### ISSUE TITLE
Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by akansh22** [afawcett/declarative-lookup-rollup-summaries#1005]
Hi,
I have recently installed dlrs and I am getting metadata API error.
Org id-00D2i0000008hVS, I have given you access

**Comment by afawcett** [comment]
@akansh22 there is a few issues reported on this - i'll close this out - but rest assured i am looking at it. I do not provide support btw - this is a community driven project - https://github.com/afawcett/declarative-lookup-rollup-summaries#community-support
