### ISSUE TITLE
Unable to Remove Test Trigger

### ISSUE THREAD

**Issue by brennanbutlerRAD** [afawcett/declarative-lookup-rollup-summaries#1006]
**Describe the bug**
We have removed a DLRS written that was on the Opportunity Object. However, this did not inactivate the test trigger. This is not not allowing us to make a update to data in the system, on the opportunity object. 

**To Reproduce**
1. Setup>Apex Class> dlrs_OpportunityTest

**Expected behavior**
I expected the test class to be removed when the Opportunity Trigger was deleted

**Comment by afawcett** [comment]
@brennanbutlerRAD did you use the "Manage Child Trigger" button to undeploy the trigger and test code? If you did that should have removed both the trigger and test. However if you or someone else just deleted the trigger - the platform does not automatically delete test classes you have to also remove those manually. Either way it sounds like this can be resolved by manually deleting the test classes under Setup > Apex CLasses
