### ISSUE TITLE
Salesforce release "Check for Null Record Variables or Null Values of Lookup Relationship Fields in Process and Flow Formulas" black calculation of DLRS

### ISSUE THREAD

**Issue by FredNL85** [afawcett/declarative-lookup-rollup-summaries#1009]
Hi community,

I had a big challenge today with a roll up with DLRS for one specific client. Since yesterday their daily rollups did not calculate anymore. 

- I did what i normally do, check if there is still a job that blcoks calculating. There were none. 
- Checked the remote site setting, that was disconnected so i made a new one via the welcome page of DLRS.
- Still if I try to manually calculate them I keep getting the error that there is possibly a job still there. There really arent's I even hard deleted the old jobs in the recycle bin but it didn't change anything. 
- I tried redeploying the chill trigger but it didnt change. 
- We had Salesforce release update we tested yesterday that was still in test mode (Check for Null Record Variables or Null Values of Lookup Relationship Fields in Process and Flow Formulas). When I turned that test mode off i was able to calculate rollups again like normal. 

I do not see the link between DLRS and this update and why it would touch each other. But after the 10th of january that update is required and we can not turn it off again. So from then on we expect DLRS not to work anymore.

The weird thing is I tested this with another client and there the roll ups keep working even if i put that test mode on. So it's seems to be very client specific. Because most of our clients use DLRS I am a bit afraid this is going to be a big issue after the 10th. 

So my concrete questions are:
1. What is the link between DLRS and Release update: Check for Null Record Variables or Null Values of Lookup Relationship Fields in Process and Flow Formulas?
2. Are more people experiencing this?
3. Is there a known workaround/solution for this?

Kind regards 
Frederic Jacobs
Bluedesk CRM

**Comment by FredNL85** [comment]
Salesforce update documentation: https://help.salesforce.com/articleView?id=release-notes.rn_forcecom_flow_release_update_formula.htm&release=228&type=5

**Comment by stephanielitus** [comment]
I have not tested this yet, but I am definitely concerned as the enforcement date is approaching.  @afawcett can you provide some info?

**Comment by afawcett** [comment]
Hmmm yes this is a very odd association indeed - the tool does not use process builder at all internally and it looks like your not using the feature to call  rollup from process builder - so.... yeah very odd. If you clear all records in "Lookup Rollup Calculate Jobs" object you should not get the error you are talking about. The latest version of the tool has some changes to this area, please take a look and also read the README file and install notes as there is some post install steps to consider. Sorry I cannot be of more use on this - i honestly cannot see a connection - hope this helps some. Andy.
