### ISSUE TITLE
Filtering out records using LREngine.

### ISSUE THREAD

**Issue by ekowkaay** [afawcett/declarative-lookup-rollup-summaries#1013]
How do I filter out records when a string is involved in my instance. I keep getting a runtime error System.QueryException: expecting a colon, found 'Yes': Class.LREngine.rollUp: line 86, column 1.
 
ctx = new LREngine.Context(Account.SobjectType,
            Training_Request__c.SobjectType,
            Schema.SObjectType.Training_Request__c.fields.Organization__c,
             'Regional_Bank_of_Hours__c = true AND Using_bank_of_hours__c = Yes AND Account_Region__c = USA'
    );

**Comment by AlexKasper** [comment]
This is a query syntax error, not DLRS. Quotes need to wrap values. Try:

`ctx = new LREngine.Context(Account.SobjectType,
Training_Request__c.SobjectType,
Schema.SObjectType.Training_Request__c.fields.Organization__c,
'Regional_Bank_of_Hours__c = TRUE AND Using_bank_of_hours__c = 'Yes' AND Account_Region__c = 'USA''
);`

**Comment by ekowkaay** [comment]
Your suggestion did not work. I'm still getting a compilation error.

**Comment by AlexKasper** [comment]
Text variables must be wrapped in quotes. It should look like this:

`Regional_Bank_of_Hours__c = TRUE AND Using_bank_of_hours__c = 'Yes' AND Account_Region__c = 'USA'`

If you're still getting an error, it would help to post the error message.

**Comment by ekowkaay** [comment]
The code doesn't compile and I get this message. "<argument> expected, got ''Regional_Bank_of_Ho...'" 
I think the string has to be constructed in a certain way.

**Comment by AlexKasper** [comment]
It's not clear to me in what context you're entering your string. Are you entering this in the **Relationship Criteria** field within a Lookup Rollup Summary record or somewhere else? Please describe.

**Comment by ekowkaay** [comment]
Sorry about the confusing. I'm not using the DLRS GUI. I'm using the LREngine Apex Class and calling the method described in the issue ticket I created.

**Comment by AlexKasper** [comment]
Ah, OK it's likely the same issue - no quotes around your text variables. Note I've added quotes where I see them missing below. It may take a little playing around with.:

`ctx = new LREngine.Context(Account.SobjectType,
Training_Request__c.SobjectType,
Schema.SObjectType.Training_Request__c.fields.Organization__c,
'Regional_Bank_of_Hours__c = TRUE AND Using_bank_of_hours__c = "Yes" AND Account_Region__c = "USA"'
);`

**Comment by ekowkaay** [comment]
Thanks but that doesn't work either.

**Comment by AlexKasper** [comment]
Did you play around with it and try inverting the quotes and/or changing syntax? Did you get it working with just one variable and add the next? It's not clear what you've tried.

Why aren't you posting the errors messages?

**Comment by ekowkaay** [comment]
I have tried different combinations and changed the syntax multiples times but I still get the same compile error message <argument> expected, got ''Regional_Bank_of_Ho...'. The problem is the syntax and that is what I'm trying to figure out. 

The below works fine without any issues, the problem is when I add the additional filter fields which are String values. 
  ctx = new LREngine.Context(Account.SobjectType,
            Training_Request__c.SobjectType,
            Schema.SObjectType.Training_Request__c.fields.Organization__c,
             'Regional_Bank_of_Hours__c = TRUE );

**Comment by AlexKasper** [comment]
It's not clear to me what you're attempting. I see an extra unmatched quote and no WHERE clause. If I were in your position, I would first get the query working perfectly in the [developer console](https://www.salesforcetutorial.com/use-developer-console-salesforce/) and then try to implement it here. Doing too much at once makes troubleshooting a headache. Check out [this reference](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm) for SOQL queries. This just takes a bit of fiddling around, but again it's pretty clearly not DLRS and specific to your use case so perhaps this discussion should be moved elsewhere since all subscribers are getting these responses?
