### ISSUE TITLE
Unable to connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by DanitCimi** [afawcett/declarative-lookup-rollup-summaries#1014]
Hi,
I am Getting the following error in my Salesforce Org although I did the update requested to the Remote Site settings 
Please help me I need to add new roll ups and I can't 

  | Errors
-- | --
  | Unable to connect to the Salesforce Metadata API.This could be because it is the first time installing this tool or your Salesforce domain has changed.A Remote Site Setting must be created or updated in your org before you can use this tool.Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

**Comment by kentallman** [comment]
I'm getting the same error with v 2.12, and creating the remote site setting via the button says it works, but this error continues.

**Comment by jmun-imentor** [comment]
Getting Error `INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=`

I think it has to do with Spring 21 Release. We matched the Session setting to the sandbox that still has Winter 21 and working DLRS though DLRS still failed to connect to Metadata API.

Thank you

**Comment by jmun-imentor** [comment]
Update: We turned on "Lock sessions to the IP address from which they originated" from the Session setting but production DLRS is still not working. However, refreshed sandbox's DLRS is working..Do you know why? Does it take some time for the session change to be affected?

**Comment by smithersnz** [comment]
I'm having the same issue, Unable to connect to the Salesforce Metadata API on 2.12.

**Comment by smithersnz** [comment]
Reverted to 2.11 and it works.

**Comment by wmerritt84** [comment]
I'm experiencing this issue as well in a sandbox after upgrading to 2.12. Same error message:
<img width="1843" alt="Screen Shot 2021-01-29 at 12 13 43 PM" src="https://user-images.githubusercontent.com/12565120/106306094-8f2ae180-622b-11eb-8d01-60270b79406b.png">

**Comment by rrobinsoncpa1** [comment]
Does anyone know the base cause of this? I get the error whether I load 2.12 or 2.11 in production, but I loaded 2.12 in the UAT sandbox, and DLRS is good to go. It's making me nuts...

**Comment by wmerritt84** [comment]
> Does anyone know the base cause of this? I get the error whether I load 2.12 or 2.11 in production, but I loaded 2.12 in the UAT sandbox, and DLRS is good to go. It's making me nuts...

The client that I had this issue with resolved the issue by spinning up a new sandbox. There was something bugged with the sandbox that we had created initially as all of the remote site settings weren't working as expected (this impacted an install of Conga Composer as well which is how we identified the issue wasn't limited to DLRS). When we moved to a new sandbox it worked fine. For reference the sandbox we were working in was a partial copy sandbox - not sure if that is related or not but if yours is partial copy maybe we're on to something there?

**Comment by afawcett** [comment]
Ok - doing some testin today - i "think" its in orgs that don't have My DOmain enabled and its possible upgrading the API version on the VF page changed the behavior of the button to create the Remote Site to use the wrong URL....

**Comment by afawcett** [comment]
The temp fix is to use the URL indicated in the error message and manually edit the Remote Site setting.

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
