### ISSUE TITLE
Professional Edition isn't working

### ISSUE THREAD

**Issue by craskul** [afawcett/declarative-lookup-rollup-summaries#1018]
**Describe the bug**
When we try to add a process builder to trigger the roll-up, there is no choice to trigger an Apex class. How can we use this tool with professional edition?

**Comment by afawcett** [comment]
Try adding RollupActionCalculate APex class to your profile? Also try posting to the Chatter Community group listed in the readme file - support for PE has been a bit hit and miss tbh.
