### ISSUE TITLE
Need to delete unused field on dlrs__LookupRollupSummaryScheduleItems__c - Managed Package Error

### ISSUE THREAD

**Issue by WadeLovell** [afawcett/declarative-lookup-rollup-summaries#1022]
When attempting to follow the guidance here: https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Attention:-Need-to-delete-unused-field-on-dlrs__LookupRollupSummaryScheduleItems__c to delete the no longer required field in a Sandbox, I get the managed package error: 

Cannot Delete Managed Component
--
The component you are attempting to delete is part of a managed package, and cannot be deleted.
Click here to return to the previous page.

How are others getting around this?

Choose to make it a great day,
Wade

**Comment by afawcett** [comment]
@WadeLovell thanks for posting - can you check you have the latest version of the package installed? The field was removed from the lastest package and should be free to delete if you are running the latest version.

**Comment by lbenioff25** [comment]
I have the latest version and when I open the LookupRollupSummary field Salesforce indicates that it can be deleted, but here is not "Delete" button.
