### ISSUE TITLE
Activity Rollup - Pulling in Email Messages

### ISSUE THREAD

**Issue by lyndsayneer** [afawcett/declarative-lookup-rollup-summaries#1023]
Business Use Case - Client wants to pull in the last and next activity date and comments, but exclude email messages since the comments field could get really unruly. They have enhanced email-enable. When I build the DLRS email messages are still being included because it is s completely different object and I can't find the proper relationship criteria to prevent them from being included. Any help would be appreciated. 
![image](https://user-images.githubusercontent.com/15369664/109516961-a133b600-7a5d-11eb-818d-43139d6f9f4f.png)

**Comment by afawcett** [comment]
@lyndsayneer thats an interesting one - unfortunately i am not an expect in this platform feature you trying to use with the tool - i might be better to use the chatter group highlighted in the README file to see what thoughts others have. Thanks. https://github.com/afawcett/declarative-lookup-rollup-summaries#community-support
