### ISSUE TITLE
dlrs_InvoiceTrigger : dlrs_InvoiceTrigger: execution of AfterInsert caused by: System.QueryException

### ISSUE THREAD

**Issue by kumarjiv** [afawcett/declarative-lookup-rollup-summaries#1024]
**Describe the bug**
I am getting an error from the dlrs  Here are the details
dlrs_InvoiceTrigger : dlrs_InvoiceTrigger: execution of AfterInsert caused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing. Even if a field is indexed a filter might still not be selective when: 1. The filter value includes null (for instance binding with a list that contains null) 2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times) Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1 Class.dlrs.LREngine.WithSharingQueryExecutor.query: line 671, column 1 Class.dlrs.LREngine.rollUp: line 238, column 1 Class.dlrs.LREngine.rollUp: line 117, column 1 Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1101, column 1 Class.dlrs.RollupService.handleRollups: line 1001, column 1 Class.dlrs.RollupService.triggerHan

dlrs_InvoiceTrigger: execution of AfterInsert

caused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact https://urldefense.proofpoint.com/v2/url?u=http-3A__salesforce.com&d=DwICaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=vb1WZxXkT5uLxBYU3LTY6LtPk5CFCqE_muGw_tKedG0&m=DIUQJL15nNpPZetG3Y8dbi1L63RlkBBSHZB8gijPR4w&s=aXdB19jYmM-mjiAkgYt2bsSIklzOapv1oshZwRP5XOE&e= about custom indexing.
Even if a field is indexed a filter might still not be selective when:
1. The filter value includes null (for instance binding with a list that contains null)
2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)

Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1
Class.dlrs.LREngine.WithSharingQueryExecutor.query: line 671, column 1
Class.dlrs.LREngine.rollUp: line 238, column 1
Class.dlrs.LREngine.rollUp: line 117, column 1
Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1101, column 1
Class.dlrs.RollupService.handleRollups: line 1001, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_InvoiceTrigger: line 7, column 1

**Comment by afawcett** [comment]
Thanks @kumarjiv for reporting - however this is not an issue with the tool - please review your filter criteria per the advice of the platform. Its a little hard to extract from the excepiton text  so i copied it below for oyu - hope this helps.

"Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing. Even if a field is indexed a filter might still not be selective when: 1. The filter value includes null (for instance binding with a list that contains null) 2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)"

"Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact https://urldefense.proofpoint.com/v2/url?u=http-3A__salesforce.com&d=DwICaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=vb1WZxXkT5uLxBYU3LTY6LtPk5CFCqE_muGw_tKedG0&m=DIUQJL15nNpPZetG3Y8dbi1L63RlkBBSHZB8gijPR4w&s=aXdB19jYmM-mjiAkgYt2bsSIklzOapv1oshZwRP5XOE&e= about custom indexing.
Even if a field is indexed a filter might still not be selective when:

The filter value includes null (for instance binding with a list that contains null)
Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)"
