### ISSUE TITLE
Rollup Summary field doesn't work

### ISSUE THREAD

**Issue by vlasgeorge603** [afawcett/declarative-lookup-rollup-summaries#1027]
Hi. I downloaded and installed the 2.12 declarative lookup rollup summary for two accounts and I have some issues that I can't find solution to. 
First account: I'm trying to install the package and I click Create/Update Remote Site Setting and trying to get into Manage Lookup Rollup Summaries, it gives me an error: Error: Salesforce Metadata API connection failure, click the link below to configure.
Second account: I created a rollup summary field on an object (for a project to calculate the sum of won opportunities) and it doesn't work. The fields of the rollup summary are:
The fields:
Parent Object: Projects__c
child Object: Opportunity
Relationship Field: Project__c
Relationship cirteria: StageName = 'Closed Won'
Field to aggregate: Amount
Aggregate operation: Sum
Aggregate Result Field: Total_donations__c
Active - checked
Calculation Mode: Realtime
Calculation Sharing Mode: System
Aggregate all rows: checked

+ Child trigger deployed

Could you help me, please? 
Thanks a lot!

**Comment by afawcett** [comment]
@vlasgeorge603 sorry about this - the second error is due to the first - which has been reported a number of times and you'll be pleased to know i am sat here looking at a patch now. Will close this out as its for sure a dupe - but feel free to comment further.
