### ISSUE TITLE
Error "Object does not exist" for CombinedAttachment

### ISSUE THREAD

**Issue by chalemic** [afawcett/declarative-lookup-rollup-summaries#103]
Goal: Get a count of files attached to a Case, either directly as an Attachment or through Chatter.

Tried: A rollup of just Attachments excludes files posted through Chatter. A SOQL query on CombinedAttachments (https://www.salesforce.com/developer/docs/api/Content/sforce_api_objects_combinedattachment.htm) works, but the DLRS rejects this object and says, "Object does not exist."

Can this be made to work (maybe something I can contribute)? Will I need to create two separate roll-ups, one on Attachment and one on FeedItems and then combine them?

**Comment by afawcett** [comment]
Sadly having upgraded to the latest API, this still doesn't work, while the docs indicate it can be used in SOQL, its only as a sub-select, this tool requires support for direct queries. Note that the docs at the very bottom state this 'You can’t directly query CombinedAttachment.'. :-1: Sorry.
