### ISSUE TITLE
FSL "Expense" Object Does Not Exist Error

### ISSUE THREAD

**Issue by FullCRM-Consult** [afawcett/declarative-lookup-rollup-summaries#1033]
I am currently configuring an org with FSL set up, and I'm trying to create a DLRS between the Work Order object (parent) and the Expenses object (child). This is so I can roll up all the expenses attached to a particular Work Order (because Salesforce doesn't natively offer that functionality for some reason).

On trying to create the DLRS, I receive an error: "Child Object: Object does not exist.":

![image](https://user-images.githubusercontent.com/82437094/116322331-35708e00-a7ff-11eb-9e7b-37a57e034065.png)

I have triple checked and the API name for the object is definitely "Expense". It is not a custom object so the name does not end with __c.

Has anyone had this issue before? It is very important for my customer that I can achieve this functionality. Thanks.

**Comment by rogeramitchell** [comment]
@FullCRM-Consult what version of DLRS is installed in the org?

**Comment by FullCRM-Consult** [comment]
> @FullCRM-Consult what version of DLRS is installed in the org?

2.12

**Comment by rogeramitchell** [comment]
@FullCRM-Consult upgrade to the latest version [here](https://zoom.us/j/6099759110?pwd=KzZ4RXRvRXR5c0tLL2FYZzVUNU84dz09) (2.13). Expense object is only available starting with Salesforce's API version 49.0, and DLRS version 2.12 was using API version 48.0.

**Comment by FullCRM-Consult** [comment]
> @FullCRM-Consult upgrade to the latest version [here](https://zoom.us/j/6099759110?pwd=KzZ4RXRvRXR5c0tLL2FYZzVUNU84dz09) (2.13). Expense object is only available starting with Salesforce's API version 49.0, and DLRS version 2.12 was using API version 48.0.

Ah I see. Thanks for that Roger. By the way I think your link may be the wrong link.
