### ISSUE TITLE
Remote Site Setting Installed Getting SF Metadata API Connection Error

### ISSUE THREAD

**Issue by NikaPesic** [afawcett/declarative-lookup-rollup-summaries#1036]
Hello, 

I installed the DLRS in my Saleforce DEV Org. 
From the package on the Welcome page I clicked on the Create/Update Remote Site Setting. 
When I go to Manage Lookup Rollup Summaries -  get error "Salesforce Metadata API connection failure, click the link below to configure."

Does anyone know how can I fix this error? 
Thank you

**Comment by NatalyaMurphyCS** [comment]
Looking back at release updates, it looks like you might not need to take this step anymore?  Ref:  https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/925

**Comment by afawcett** [comment]
Yes @NikaPesic if you are in an org that is using My Domain feature you don't need to worry about this. Try installing latest package version as well - as I made quite a bit of updates to this logic in the last release. ANdy.
