### ISSUE TITLE
record looked whit realtime Roll-up

### ISSUE THREAD

**Issue by oavon** [afawcett/declarative-lookup-rollup-summaries#106]
Hello,

I installed your package which is really great, thanks a lot:)

But i ahave one problem, we have 200 000 contacts.
And we want to have the following Rollup:

Nb of Open cases of a contact

But when i started the rollup, we were not able to access Cases, as if these record were looked.

Can you tell me what heppen?
Does the calculation look the records?
How long it takes?

Thanks a lot for your precious help.

Best
Olivier

**Comment by afawcett** [comment]
You'll have to give me more details here, such as a screenshot of your rollup, screenshot of the error and steps your going through to cause the error. THanks.

**Comment by oavon** [comment]
Thanks Andrew for your answer

I'm afraid to start it again, as nobody in my company was able to work on cases anymore;-)
Here is a screen copy of the lookup
![image](https://cloud.githubusercontent.com/assets/10242114/5755344/8850d530-9ca3-11e4-8042-574fcf423d98.png)

Do you have similar problem when the number of contacts is high/
I will retry this weekend anyway

best
Olivier

**Comment by afawcett** [comment]
The description of this issue suggests that your using a real-time lookup, but i see in the screenshot that you have Calculation Mode set to Schedule? So I am still a bit confused about your problem. Also you have not given me an example of the error or steps on how your reproducing it? This is really important if i am to help you. In the meantime, please also reference to the [known issues and limits section](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues).

**Comment by oavon** [comment]
Thanks Andrew,

Yes i will set it to RealTime:-)
i will try it again this weekend when no one in my company works on cases.

But can i ask you if you know about records such as Cases being "locked" during Calculation?
And how long Calculation will takes for 200 000 contacts and the same amounts of cases, but less than 1000 open cases?
(the roll up Summary will count only the open cases for each contact0

Thanks a lot

**Comment by afawcett** [comment]
RE: Locking, the tool does not explicitly lock records no.

RE: Calculation time (via the Calculate button job), its really hard to say, Salesforce varies processing time of background jobs depending on the load on the service at the time. For this reason its also quite hard to benchmark on the platform. 

When you click the Calculate button it submits a Batch Apex job you can monitor under the Apex Jobs page (under Setup). If you watch how long it ticks over from one chunk of records to the next you might be able to predict to some degree how long it will take to complete. 

Salesforce takes your 200,000 records (Contacts) and splits them up into chunks of processing, between each chunk may pause between the next depending on platform load, thus the number of chunks can effect the job overall execution time. By default each chunk is 100 records, so your job will take 1,000 chunks, this could take a while, if you have little Apex logic / triggers on Contacts, you can increase this under Custom Settings to say 1000 (max 2000), which would result in 200 chunks, so more time processing per chunk and generally speaking less time overall for the job to complete.

RE: Calculation time (realtime), once this is on (after the above completes on existing records), as each Case is added/updated/deleted unless you have thousands of cases for a related Contact it should not take a huge amount of time that would impact your end users (subject customisations and apex trigger code in your org). If this is an issue, this is the reason Schedule mode exists, if it does impact realtime you can switch this on, the downside is you will only see it update after each schedule run so your users need to appreciate the rollups may lag behind the data in the objects at any given time.

**Comment by oavon** [comment]
Thanks Andrew,

my error was coming from the fact that i forget the permission set "read" for the Rollup Package object to all users.

Now it works perfectly
Thanks a lot your Package is amaming :-)
I'm impressed;-)
