### ISSUE TITLE
Null object error - Aggregating null currency field on child

### ISSUE THREAD

**Issue by wes1278** [afawcett/declarative-lookup-rollup-summaries#107]
I just ran into an error with this package where I was trying to save an OpportunityProduct on an Opportunity and gave me an apex exception. Several of the fields in question didn't have a default value of 0; changing those fields to have a default value of 0 fixed the issue.

**Comment by afawcett** [comment]
Thanks for sharing. Can you provide some more details so i can try to reproduce this please? Such as a screenshot of your rollup definition, opp and opp product record config, example of the error your getting. Thanks.

**Comment by wes1278** [comment]
to Repro:

# Create a currency field on OppLineItem
## Very important that you do NOT set the default value to 0. Let the default be null.
# create an active rollup summary record to roll that field on OppLineItem to opportunity based on OpportunityId.

Edit the data on an OpportunityLineItem (but don't change the value we're trying to rollup) to cause it try to rollup and it dies for me. I'm trying to dig up the error text from email (which I haven't been able to find in the last 15 minutes) but it was an "Attempt to de-reference a null".

To fix the issue, I went to the field and made sure the default was set to 0. Then, I went and updated the same OppLineItem record to have a value of 0 instead of null and voila, no apex exception anymore.

Just out of curiousity, do you think it would be benficial for you and I to perhaps use a shared dev org to reproduce issues like this?

**Comment by afawcett** [comment]
:+1: for shared repo org, i can create you a user in my test org if you want, do i have your email or do you have mine?

And thanks for this repo, spookly i think another use hit this yesterday, thanks for this, i think i can find the bug from here.

**Comment by afawcett** [comment]
Fixed in v1.17
