### ISSUE TITLE
Validate the Rollup Criteria on Save

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#108]
The Criteria needs to be valid SOQL WHERE clause syntax. Not everyone is that familiar with this and struggles to find the correct syntax. Its not ideal that it does not validate until the rollup is used, especially if the Rollup is a scheduled one. This enhancement is to report problems with the validity of the Rollup Criteria on Save.

**Comment by wes1278** [comment]
How do you think this could be accomplished? I suppose we could be "hacky" and just dynamically build the query and try-catch it. Then add an apexmessage in the catch?

**Comment by afawcett** [comment]
Yeah there is no real 'SOQL validate' faclity other than to run it, i'd was thinking to give it an empty Set of master Id's to prevent it querying anything and yes catch the exception. It just seems it would be handy to know at the time of save, than find out on the child object itself or by monitoring the schedule job for errors.

**Comment by afawcett** [comment]
Fixed in v1.17
