### ISSUE TITLE
When using the Realtime mode, Formula fields as fields to aggregate are not supported 

### ISSUE THREAD

**Issue by jlig** [afawcett/declarative-lookup-rollup-summaries#112]
Any roadmap on adding the ability to use "Formula Fields"?
- If I use the Workflow Rule route to copy the Formula value to a plain currency field.. I'm afraid the new copied "plain currency field" will not stay up-to-date when changes are made later?

**Comment by jlig** [comment]
Using the Rollup Helper app from the AppExchange I was able to use a "Formula Field" (TCC-A__c) that is rolled up to my Quote object.
- See this link: http://screencast.com/t/OwLfVeO2jVV or 
![2015-01-26_2312](https://cloud.githubusercontent.com/assets/1561704/5914033/93788ef8-a5b3-11e4-8d24-df38fb6d8e04.png)

- Do you see a way to duplicate this using the DLRS?

**Comment by wes1278** [comment]
@jlig Formulas will work just fine. However, in my ignorance of creating the pilot visualforce page, you can't select formulas. :) I really need to patch this page. 

If you just edit the record (using standard salesforce edit page) you should be able to use a formula field as the field to roll up.

Thanks.

**Comment by jlig** [comment]
excuse my ignorance here.. what do you mean "edit the record"?

**Comment by jlig** [comment]
ok, formula fields working fine now!

Have two questions:
-------------------------
1) How would I add in the "SOQL WHERE" criteria to only SUM/Rollup items: 
WHERE xx_ord1_line_description__c LIKE "%Fiber Facility%"

I tried the following but no change:
![2015-02-05_1132](https://cloud.githubusercontent.com/assets/1561704/6065502/7b1d097c-ad2b-11e4-979d-9248f7a23817.png)

2) Will the roll-ups automatically update anytime the "Formula" field changes?

**Comment by jlig** [comment]
I added in the "Relationship Criteria" & the "Relationship Criteria Fields" 
![2015-02-05_1523](https://cloud.githubusercontent.com/assets/1561704/6069594/5b9d2d50-ad4b-11e4-9ce2-cfae3fd681b5.png)

but get the following error:
- Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_XX_ORD1_Quote_Line_ItemTrigger: execution of AfterInsert caused by: System.QueryException: line 1:153 no viable alternative at character '"' (dlrs) Trigger.dlrs_XX_ORD1_Quote_Line_ItemTrigger: line 7, column 1: []

If I disable the Roll-Up Summary, the error goes away?

**Comment by wes1278** [comment]
Use single quotes in the relationship criteria.

**Comment by jlig** [comment]
Wes, thanks for all the help..
I updated the "Relationship Criteria" field to the following (see image) but now getting this error:
- Insert failed. First exception on row 0; first error: 
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, 
dlrs_XX_ORD1_Quote_Line_ItemTrigger: 
execution of AfterInsert caused by: 
System.QueryException: unexpected token: 'XX_ORD1__Line_Description__c LIKE "%Fiber Facility%"' (dlrs) Trigger.dlrs_XX_ORD1_Quote_Line_ItemTrigger: line 7, column 1: []

![2015-02-05_2253](https://cloud.githubusercontent.com/assets/1561704/6074705/19a5eace-ad8a-11e4-931b-b03e5b0d1932.png)

I know this should be in proper SOQL but not sure what to try next? Include the WHERE statement?
By the way, this is a great tool!

**Comment by jlig** [comment]
ok, It is working right now. Thanks Wes, the single quotes did the trick!
![2015-02-05_2315](https://cloud.githubusercontent.com/assets/1561704/6074863/25484810-ad8d-11e4-8f2c-9d2011e4d8af.png)

**Comment by jlig** [comment]
One more issue or ignorance on my part: 
- The rollup works fine (in real-time) to copy my formula field (on child object) to the parent object. 
- But any later changes to the child fields (which feed the Formula field) DO NOT get rolled-up (updated) to the parent?
- Looks like the Trigger only works with actual edited fields and does not trigger when a formula field changes to a new value? Is there any way around this? What is the fix?
![2015-02-06_1010](https://cloud.githubusercontent.com/assets/1561704/6082804/942e9458-ade9-11e4-8184-0a18d848a34b.png)

**Comment by afawcett** [comment]
Add your other related fields to the Relationship Criteria Fields list (new line separate), thus the tool will monitor those other fields that feed into your formula field as well. Basically review your fomrula field for any fields it references add them to the Relationship Criteria Fields list.

**Comment by afawcett** [comment]
Let me know if this doesn't resolve the issue for you, we can for sure re-open this issue. :+1:

**Comment by jlig** [comment]
Andrew, thanks so much for your reply & great tool!
I tried adding the related field (from my Formula field) and add it to the related fields box but get error:
![2015-02-07_1939](https://cloud.githubusercontent.com/assets/1561704/6094812/a31ec3ac-af01-11e4-8f5c-aee556cb7433.png)

My object structure is: Quote, with Quote Line Items, with Locations on each Quote Line Item.
- I then have a field on Location object that calculates the total
- It's this total that I need "rolled up" to the Quote

![2015-02-07_1940](https://cloud.githubusercontent.com/assets/1561704/6094828/bbab1500-af02-11e4-83d6-3df5d435bff3.png)

**Comment by afawcett** [comment]
Hmmm i see, i was assuming your formula on quote line would reference other fields on the quote line, that can be made known to the tool.  Sadly the tool only monitors immediate fields on the child object, it cannot watch for changes in fields on related records, such as your location (since salesforce does not make these available in a trigger context). The best you could do, with your current setup, is add the field Location__A__c, thus whenever the location changes the rollup is calculation is triggered.

However, there is a workaround if you are prepared to create another field on Quote Line Item to contain a copy of TCC_A, you can then base the rollup on that field. The solution is actually described in the README file for this repo, under [known issues](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues).

"When using the Realtime mode, Formula fields as fields to aggregate are not supported (validation will be added in a future release to block this). To work around this, either switch to Scheduled mode or in Relatime mode use a Workflow Field Update to copy the formula field value to a physical field and reference that."

**Comment by jlig** [comment]
First question:
- any update to DLRS that allows it to "watch for changes in fields on related records"?

Second question to Andrew:
- when you say "The best you could do, with your current setup, is add the field Location__A__c" what do you mean?
- will it just create "extra overhead" for the trigger, but still work to monitor any changes?

**Comment by afawcett** [comment]
Wow @jlig so sorry for such a late reply here, the DF bump this year just going down! ;-)

RE: Watch for changes on related records no updated on this really, it's best, if there isn't one already, to raise a GitHub issue and i'll flag it as an enhancement. Its a pretty big one tbh, but non the less its a need i've been asked for a few times before, so worthy of a GitHub issue to allow some collective brainstorming on requirements, design and implementation. :+1: 

RE: "best you could do", comment, i ment add Location_A__c to the 'Relationship Criteria Fields' field. At least if that itself changes your rollup will recalculate.

RE: "extra overhead", not significant, its still just checking for changes in the field value nothing else, so no difference between string or checkbox fields in that sense. Obviously the more you add to 'Relationship Criteria Fields'  the more compares it does, but compared to the main part of the work the tool does within a trigger context thats still a small portion, so no don't worry.

P.S. A thought that just occurred about your 'changes in fields on related records' ask that just occured is.... Make a shadow copy (not on the parent layout) of the fields on the related record, the implement on the related record a Process Builder flow that uses Flow's to query for parent records an update the shadow copy of the field on the parent, then include the shadow copy of the field in 'Relationship Criteria Fields' field.

**Comment by jlig** [comment]
Andrew, thanks for the update!
First, I added in the "Location__A__c" to the "Relationship Criteria Fields"
- then tested by making a change to a location, but nothing would ever roll-up to my quote object?
Second, I appreciate the shadow copy/Process builder/flow idea 
- but not sure how to implement yet?

Tools like the "Rollup Helper" app actually work fine to rollup my field value albeit manually, but I'm unwilling to pay their $2000/yr for a "single" real-time rollup!

**Comment by afawcett** [comment]
Ok i've got this working with a Process Builder and DLRS combo deal, short blog on its way! I'll link from the tools repo README file and post in Chatter group.

**Comment by afawcett** [comment]
Here is my write up http://andyinthecloud.com/2016/02/13/rollups-and-cross-object-formula-fields/
