### ISSUE TITLE
Need help writing a SOQL Query for a Rollup

### ISSUE THREAD

**Issue by JenNelsonChicago** [afawcett/declarative-lookup-rollup-summaries#113]
Hi, there - so love this tool - thank you for sharing it with the Community!

I am trying to do a Rollup between a Custom Object called "Volunteer Hours" (from the Volunteers for Salesforce App) to Account.  Volunteer Hours already has M-D relationships to Contact and another Custom Object called Volunteer Job so I am maxed out on native Rollups.

My criteria is somewhat complex - here are the details:
> Parent (destination) object is Account
> Parent (destination) field is Initial_Hours_Required__c - it is numeric (18,0)
> Child (source) object is GW_Volunteers__Volunteer_Hours__c
> Child (source) relationship field to Account is Household__c
> Child (source) field to be rolled up to Account's Initial_Hours_Required__c field is GW_Volunteers__Hours_Worked__c - it is numeric (5,2)
> Criteria for Rollup should be if the following is true on a GW_Volunteers__Volunteer_Hours__c record:
-- Sweat_Equity__c (checkbox) = True
-- GW_Volunteers__Status__c (picklist) = Completed
-- GW_Volunteers__Start_Date__c (Date) <= TODAY()
-- Household__c (Lookup) IS NOT NULL
-- Sweat_Equity_Type__c (picklist) = Initial Hours

Many thanks in advance for the help!

**Comment by afawcett** [comment]
Awesome thanks for this, will take a look Saturday morning for ya!

**Comment by JenNelsonChicago** [comment]
Thank you so much!

**Comment by JenNelsonChicago** [comment]
One minor correction

Parent (destination) field is Initial_Hours_Completed__c - it is numeric (18,0)

**Comment by afawcett** [comment]
I reproduced the object and fields above in my test org, did a few tests, so you should be good to go!

**Relationship Criteria:** 
Sweat_Equity__c = True AND GW_Volunteers_Status__c = 'Completed' AND GW_Volunteers_Start_Date__c <= TODAY AND Sweat_Equity_Type__c = 'Initial Hours'

**Relationship Criteria Fields:**
Sweat_Equity__c 
GW_Volunteers_Status__c 
GW_Volunteers_Start_Date__c 
Sweat_Equity_Type__c

Note that you don't need to include the HouseHold__c field in the criteria, the tool does this for you. I've also included a screen shot of my test rollup as configured in my org.

![screen shot 2015-01-31 at 10 20 26](https://cloud.githubusercontent.com/assets/1167760/5987717/c11dccd8-a932-11e4-843d-4e750f50f617.png)

**Comment by JenNelsonChicago** [comment]
Thank you so much!

I will test this afternoon.

So excited - have a great weekend!

Jen

**Comment by JenNelsonChicago** [comment]
I cannot thank you enough, Andy, it is working beautifully!

There was one minor tweak - just in case anyone else needs this for the V4S app - it appears that the V4S app has a double-underscore in the middle of the API field names (just after Volunteers) so the corrected are:

Relationship Criteria: 
Sweat_Equity__c = True AND GW_Volunteers__Status__c = 'Completed' AND GW_Volunteers__Start_Date__c <= TODAY AND Sweat_Equity_Type__c = 'Initial Hours'

Relationship Criteria Fields:
Sweat_Equity__c 
GW_Volunteers__Status__c 
GW_Volunteers__Start_Date__c 
Sweat_Equity_Type__c

**Comment by afawcett** [comment]
Your very welcome and thank you for the support on twitter! :+1:
