### ISSUE TITLE
Error on Relationship Criteria

### ISSUE THREAD

**Issue by emchampine** [afawcett/declarative-lookup-rollup-summaries#116]
I am using a relationship criteria of "Month_Year__c = LAST_120_DAYS".  I ran a Calculate job and it worked perfectly, however, when I check the Apex Jobs Log, it looks like it worked once and got an error twice - "First error: expecting a colon, found 'LAST_120_DAYS'"  

I have the Lookup Rollup marked as Active and Real Time.  A User received the same error when trying to update the record.

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_Monthly_SpendTrigger caused an unexpected exception, contact your administrator: dlrs_Monthly_SpendTrigger: execution of AfterUpdate caused by: System.QueryException: expecting a colon, found 'LAST_120_DAYS': (dlrs)

Why would it work only sometimes?  What is incorrect about my criteria?

**Comment by jlig** [comment]
Had a similar error/issue with my SOQL WHERE criteria. 
- Try removing your quotes and just use relationship criteria of Month_Year__c = LAST_120_DAYS
- (See http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm or my previous post: https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/112#issuecomment-73067079)

**Comment by emchampine** [comment]
That actually is my relationship criteria.  I don't know why its different
in the Apex Job error.

On Fri, Feb 6, 2015 at 11:02 AM, jlig <notifications@github.com> wrote:

> Had a similar error/issue with my SOQL WHERE criteria.
>
>    - Try removing your quotes and just use relationship criteria of
>    Month_Year__c = LAST_120_DAYS
>    - (See
>    http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm
>    or my previous post: #112 (comment)
>    <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/112#issuecomment-73067079>
>    )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/116#issuecomment-73259611>
> .
>



-- 

*Erica Champine*Salesforce.com Certified Consultant
*Coastal Cloud*
Mobile: +1 (386) 801.8724
Email: erica.champine@coastalcloud.us <chad.borer@coastalcloud.us>
Web: www.coastalcloud.us

**Comment by afawcett** [comment]
I'm not sure why it appears to be working in the Calculate Job mode, as LAST_120_DAYS is not a valid system value. You need to use Month_Year__c = LAST_N_DAYS:120, as per the [docs](http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_dateformats.htm).

**Comment by afawcett** [comment]
Just tested this in my test org, seems to work just fine, let me know if not and we can re-open this issue. :+1:
