### ISSUE TITLE
Support for Lightning Process Builder

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#117]
I want to provide an alternative way to invoke the DLRS engine, via Process Builder. User will still define the rollup in the usual way, but will not be required to deploy an Apex Trigger if they elect to utilise the rollup via a Process Builder process.

**Comment by wes1278** [comment]
Love this idea.

**Comment by afawcett** [comment]
Yeah quite a quick one to implement and will remove the need for Apex Trigger deployment.

**Comment by wes1278** [comment]
Plus it will allow some interesting use cases where we want a condition to be meet before rolling something up.

**Comment by afawcett** [comment]
Added in version 1.18, see README for more.
