### ISSUE TITLE
How do I install this into my org

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#119]
All i've done in the past is install apps from the App Exchange. Can you point me to something that shows me how to get the rollup tool into my Salesforce instance?

Thanks in advance,
Guy

**Comment by afawcett** [comment]
Sure you can find the package install links [here](https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history).

**Comment by guygardner** [comment]
Thanks. Somehow I missed it before. 
Guy
