### ISSUE TITLE
Got some errors when trying to install as follows. This is from production but I also get similar errors when I try to install into a sandbox. Any ideas?

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#120]
......
Status: InProgress 
Status: Completed 
Deployment Complete
Failures:
classes/WelcomeControllerTest.cls(36,38):Dependent class is invalid and needs recompilation:
WelcomeController: line 54, column 4: Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/WelcomeController.cls(54,4):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupSummaryEnhancedController.cls(153,3):Dependent class is invalid and needs recompilation:
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupSummariesTest.cls(41,2):Dependent class is invalid and needs recompilation:
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupSummariesSelector.cls(67,45):Dependent class is invalid and needs recompilation:
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupSummaries.cls(140,106):Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupServiceTest3.cls(44,2):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupServiceTest2.cls(44,2):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupServiceTest.cls(89,3):Dependent class is invalid and needs recompilation:
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupService.cls(174,14):Dependent class is invalid and needs recompilation:
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupActionCalculate.cls(42,60):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupActionCalculateTest.cls(65,62):Dependent class is invalid and needs recompilation:
Class.RollupActionCalculate.RollupToCalculate.toServiceRollupToCalculate: line 42, column 60
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupCalculateController.cls(43,3):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupCalculateJob.cls(41,2):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupController.cls(266,2):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupControllerTest.cls(68,37):Dependent class is invalid and needs recompilation:
Class.RollupController.init: line 266, column 2
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
classes/RollupJob.cls(34,2):Dependent class is invalid and needs recompilation:
Class.RollupService.rollup: line 174, column 14
RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c
triggers/RollupServiceTest3Trigger.trigger(12,6):Variable does not exist: RollupService
triggers/RollupServiceTestTrigger.trigger(12,6):Variable does not exist: RollupService
triggers/RollupSummariesTrigger.trigger(30,31):Variable does not exist: RollupSummaries.class
triggers/RollupServiceTest2Trigger.trigger(11,5):Variable does not exist: RollupService
permissionsets/LookupRollupSummariesFull.permissionset(LookupRollupSummariesFull):invalid parameter value
permissionsets/LookupRollupSummariesReadOnly.permissionset(LookupRollupSummariesReadOnly):invalid parameter value
pages/managetrigger.page(managetrigger):Apex class 'RollupController' does not exist
pages/rollupcalculate.page(rollupcalculate):Apex class 'RollupCalculateController' does not exist
pages/rollupsummaryenhanced.page(rollupsummaryenhanced):Apex class 'RollupSummaryEnhancedController' does not exist
pages/welcome.page(welcome):Apex class 'WelcomeController' does not exist

**Comment by afawcett** [comment]
Oops sorry about this, will sort this out, in the meantime are you sure you want to deploy the code unmanaged? You can use the package install links to install the tool as a package, which is the recommended route for sandbox and production.

**Comment by guygardner** [comment]
Yes. Managed would be preferred. Where are the package install links?  

Should I wait until you resolve the load issues, or May that not get the error?

Thanks for your help on this.

**Comment by guygardner** [comment]
I found the managed package link, used it and it installed fine as a managed package. Yay!

So I am good to go now and starting to use the tool.

Thanks for your help and for creating this tool.

Guy

**Comment by afawcett** [comment]
Your very welcome, i'll sort this issue in due course as well...

**Comment by afawcett** [comment]
Fixed
