### ISSUE TITLE
Currency Fields in the Rollup causing the issues - "Master and detail fields must be the same field type (or text based) for First or Last operations"

### ISSUE THREAD

**Issue by ram-jampana** [afawcett/declarative-lookup-rollup-summaries#121]
Hi...

I have upgraded the package to the new version and added the Fields to the page layout along with the new pick list values to the fields. When I try to create the Rollup summary for the "Payment Txn" and Contact using the Currency fields I am getting the Error.

I want to Rollup the first Payment Txn's "Amount" field to the Contact's "First Gift Amount" field.

Here are the snapshots of the Issue.
Thanks for the help...

![image](https://cloud.githubusercontent.com/assets/11051925/6238912/e138d7dc-b752-11e4-8cdc-8829a2bb2099.png)

![image](https://cloud.githubusercontent.com/assets/11051925/6238942/0ef92b22-b753-11e4-9635-571d26b7bf38.png)

![image](https://cloud.githubusercontent.com/assets/11051925/6238945/13c817bc-b753-11e4-84fc-9283565f8033.png)

**Comment by wes1278** [comment]
I'm not sure the pilot enhanced edit screen supports the fields you need to use for first or last. Try to use standard Salesforce edit page.

**Comment by wes1278** [comment]
To be more specific, you need to set the field to order by to be a date field.

**Comment by ram-jampana** [comment]
Hi @wes1278 

Thanks for the help, But the standard Edit Page is also no help....

![image](https://cloud.githubusercontent.com/assets/11051925/6259231/54d81f8c-b824-11e4-92c0-580028c92f96.png)

**Comment by afawcett** [comment]
This is a bug, i'll sort it, sorry in the meantime...

**Comment by afawcett** [comment]
Fixed in v1.19.
