### ISSUE TITLE
Error in deploying trigger for child relationships

### ISSUE THREAD

**Issue by Nickers3** [afawcett/declarative-lookup-rollup-summaries#123]
Hello,

I'm receiving the following error when trying to deploy a lookup rollup summary: MyProfilePageControllerTest.testSave System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Please clear the value in the account name field and save the account.: [] Class.MyProfilePageControllerTest.testSave: line 34, column 1.

I've tried a mixture of deploying to standard and custom child objects and in each case received this error message.  Any help is appreciated!

Nick

**Comment by Nickers3** [comment]
Cancel this issue.  I was took another look at the debug log and figured out what is causing the issue -  a validation rule.  The rule was from a lookup to another object referenced on the child relationship.  I played with the validation rule a bit and got it working.

**Comment by afawcett** [comment]
Great thanks.

**Comment by creuman** [comment]
Hi Nick, can you give any more detail about how you found the validation rule that was causing the problem? I am getting a very similar error message even when trying a rollup with Account and Oppty.

MyProfilePageControllerTest.testSave System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Required field: [AccountId] Class.MyProfilePageControllerTest.testSave: line 34, column 1

thank you!

**Comment by creuman** [comment]
The error I was having was related to a custom setting in the NGO Connect managed package. The solution is to temporarily disable the "Account is Required" custom setting in rC Bios Contact Validation, then turn it back on after you've created the DLRS trigger.

**Comment by Nickers3** [comment]
Thanks for sharing!  I was able to do a similar method with mine -
temporarily disable a validation rule and it worked like a charm afterwards.
