### ISSUE TITLE
I think it would be great if you had a place here for end users to share how they are using this

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#125]
That would be a social interaction that would allow users to find solutions to problems that someone else has already solved.

Great work! Thanks for making this tool!

Guy

**Comment by afawcett** [comment]
Maybe we should setup a Chatter Group in Salesforce Community?

**Comment by guygardner** [comment]
Makes sense to me.

**Comment by afawcett** [comment]
I've created a [group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p)
