### ISSUE TITLE
'OR' Function on Relationship Criteria

### ISSUE THREAD

**Issue by UsernameNotAvailable** [afawcett/declarative-lookup-rollup-summaries#126]
I'm trying to use this in the the Relationship Criteria field, but I'm getting an error.  Can the OR function not be used here?

CommercientSF8__ITEMCODE__c = '04000' OR CommercientSF8__ITEMCODE__c = '04001'

Error: Relationship Criteria 'CommercientSF8__ITEMCODE__c = '04000' OR CommercientSF8__ITEMCODE__c = '04001'' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: OR'

Thanks!

**Comment by aheber** [comment]
Ca you do it as "CommercientSF8__ITEMCODE__c IN ('04000','04001')" ? 

Is there more to the query? It could be something else causing the problems. You may also want to put the OR clause in parenthesis if you haven't already.

The error being returned is from Salesforce and not necessarily something that DLRS is doing. You may want to work out the query in the Developer Console or another developer tool first. It may be easier and faster to work through.

**Comment by UsernameNotAvailable** [comment]
"CommercientSF8__ITEMCODE__c IN ('04000','04001')" worked.  Thanks so much!
