### ISSUE TITLE
Code Coverage on Manage Child Trigger

### ISSUE THREAD

**Issue by emchampine** [afawcett/declarative-lookup-rollup-summaries#127]
I am receiving a code coverage error when trying to deploy in a new org.  The only packages installed are this one and the Milestones PM app.

null:Average test coverage across all Apex Classes and Triggers is 6%, at least 75% test coverage is required.

**Comment by afawcett** [comment]
Are you running the latest version of the tool? Can you share a screen shot please.

**Comment by afawcett** [comment]
This could be related to this [issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/122).

**Comment by afawcett** [comment]
I suspect this is the same root cause as [122](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/122), closing this one.
