### ISSUE TITLE
Concatenate Distinct Duplicates Values When Rolling up Multi-Select Picklists

### ISSUE THREAD

**Issue by dhoechst** [afawcett/declarative-lookup-rollup-summaries#128]
If I am rolling up a multi-select picklist with concatenate distinct, the distinct only works if all child values are exactly the same.

Scenario 1:
Child 1 = Apple; Orange
Child 2 = Apple; Banana
Parent = Apple; Orange; Apple; Banana

I would expect it to roll up the values to be Apple; Orange; Banana

Scenario 2:
Child 1 = Apple; Orange
Child 2 = Apple; Orange
Parent = Apple; Orange

**Comment by afawcett** [comment]
Ah yes, good spot! Taking a look at your PR now! :+1:

**Comment by afawcett** [comment]
Fixed in v1.19 package.
