### ISSUE TITLE
Set up Continuous Integration to Test Merges

### ISSUE THREAD

**Issue by dhoechst** [afawcett/declarative-lookup-rollup-summaries#131]
It would be great to set up CI with a tool such as Travis so issues with commits could be identified quickly. For example, issue #120 could have been caught with a test build to a clean org.

**Comment by afawcett** [comment]
Yeah was just wondering about looking into something like that as well, good suggestion!

**Comment by dhoechst** [comment]
I should be able to get you the files you need and walk you through setup, but since I don't have permission to the repo, I can't set it up directly. I can even push most things through with a PR.

**Comment by afawcett** [comment]
Done, works a treat, thanks for your help! I think at some point i'll update the Ant script to use the FinancialForce.com undeploy Ant task to ensure we don't get any false results due to prior builds being present in the org.
