### ISSUE TITLE
Rollup multi-select picklist to multi-select picklist

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#133]
See [tweet](https://twitter.com/dhoechst/status/573622118702669824) from @dhoechst

**Comment by dhoechst** [comment]
Actually, it works as long as you put in a delimiter of ;

**Comment by afawcett** [comment]
Ahhh of course, its been a long week, i actually did (manually) test that now that you mention it! Thanks again!
