### ISSUE TITLE
Summary data not correct

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#135]
I have Transaction records rolling up to Contacts based on the GL Account in the Transaction.

I keep getting a 6800 amount but if I report on the transaction object the number is a 8000 number. I have tried creating additional transaction records and then removing but it keeps going back to the 6800 amount. 

I cannot edit the amount directly on the transaction records because they are locked down and the accounting periods are closed.

Any idea what this issue is? This is our first attempt with the product.

Thanks, Lisa

**Comment by afawcett** [comment]
Hi @girlyITgeek you have closed this issue, can i assume your rollups are working now?

**Comment by girlyITgeek** [comment]
Yes. My report criteria was looking at "My" data. Rollups are working
perfectly!
