### ISSUE TITLE
Incorrect result when rolling up Activity Date from an Event

### ISSUE THREAD

**Issue by SusanTr** [afawcett/declarative-lookup-rollup-summaries#136]
I have set up the Activity Object so that it is related to the Campaign object.

I want to calculate the min and max dates of activities associated with the Campaign.  This works GREAT except when the Activity is a All Day Event.  Somehow, if it is an All Day Event the min and max computed are 1 day less than the actual dates.    

Any ideas?

**Comment by afawcett** [comment]
Need to try and reproduce this.

**Comment by afawcett** [comment]
Can you help me reproduce this with a screenshot of your rollup please?

**Comment by SusanTr** [comment]
Hi Andrew,

Thanks for following up on this.

I think it's a SF issue and not a problem with the roll up.

Basically, the problem occurs when I try to rollup the min Event date when
the event is an All Day event.  It doesn't happen when the event is not an
All Day event.  I think the problem has something to do with SF storing
events at GMT and the nature of All-Day events.  e.g. If a user sets up an
All Day Event in San Francisco, how should it look to the user in Cairo?

I think that for some reason, the rollup uses the GMT date/time for the all
day event and not the locale time.  (Probably because that's all SF lets
the rollup use).  When I add  an offset for the GMT time, I get the correct
results.

Would you still like to see this in action?

With Thanks.

Susan

**Comment by afawcett** [comment]
Yep i think thats a reasonable explanation, and yes the code gets GMT date/time info from the system. Are you saying you have a workaround or do you still want to see if we can come up with a code fix here?

**Comment by afawcett** [comment]
Closing this for now, let me know if you still need help and we can re-open.
