### ISSUE TITLE
Issue with concatenate delimiter in 1.19

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#137]
I just added the new fields from 1.18 and then installed 1.19 into my sandbox.

I built a contatenated text rollup (see image), but the concatenate delimiter is not working.  I tried , / and BR() but none added a delimiter between the rolled up strings.
![concatenate_delimiter](https://cloud.githubusercontent.com/assets/8515331/6669102/86f04e60-cbcd-11e4-9662-5e22426c7e5d.jpg)

**Comment by JodiNA** [comment]
I realized that 1.19 created the fields I had just added for the upgrade.  When I changed my page layout to reflect the fields created by 1.19, the delimiter worked.  I'll close this issue.  Oops!

**Comment by afawcett** [comment]
Ha no worries, i wish package upgrades when adding fields to layouts and picklists was easier!
