### ISSUE TITLE
Cannot use "OR" function

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#138]
See my relationship criteria below.

(status__c IN ('Active', 'Active - pending end') AND avtrrt__start_date__c != THIS_WEEK) OR (status__c IN ('Active', 'Active - pending end') AND avtrrt__end_date__c = LAST_WEEK)

Error: Relationship Criteria '(status__c IN ('Active', 'Active - pending end') AND avtrrt__start_date__c != THIS_WEEK) OR (status__c IN ('Active', 'Active - pending end') AND avtrrt__end_date__c = LAST_WEEK)' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: OR'

**Comment by aheber** [comment]
@girlyITgeek I tested your criteria, adapted to my own org, inside the Developer Console and it ran OK.

`select id from case where (status IN ('New', 'Closed') AND CreatedDate != THIS_WEEK) OR (status IN ('New', 'Closed') AND CreatedDate = LAST_WEEK)`

Could you write something similar that will run OK in your Developer Console, or another SOQL tool, and paste it back here with screenshots of your rollup? I don't know what could be wrong but maybe we'll figure it out by seeing the whole picture.

Thanks.

**Comment by wes1278** [comment]
I think you might need to wrap the whole thing in another set of parentheses.

**Comment by girlyITgeek** [comment]
Thank you wes1278!!! That worked.

**Comment by wes1278** [comment]
No problem @girlyITgeek! Glad it works. @aheber, SOQL is a little smarter when it's not being injected from a string like we're doing with this tool.  :)
