### ISSUE TITLE
Scheduled Rollup

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#141]
I setup a scheduled rollup yesterday but it hasn't updated any records. How can I edit the schedule?

Thank you :)

**Comment by afawcett** [comment]
The platform oddly does not allow this see here and vote up the [idea](https://success.salesforce.com/ideaView?id=08730000000H11Q). You will have to delete the scheduled job entry and add a new one. 

As to how rollups get processed. As child records are modified they get 'queued' in an object called 'Lookup Rollup Summary Schedule Items' which should show as a releated list item at the bottom of your rollup definition. If you don't see entries in here then the schedule job will do nothing. 

Entries are added here if the rollup field on the child record is changed or any of the fields listed in 'Relationship Criteria Fields' are edited. Of course the other reason could be its failing for some reason that is not captured in the 'Lookup Rollup Summary Logs' object. Check under Setup menu for the Apex Jobs page for this.
