### ISSUE TITLE
Nightly Scheduled RollupJob running, but Summaries not updating

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#142]
I followed the instructions in this [blog post](http://andyinthecloud.com/2014/02/09/new-release-spring14-declarative-rollup-summary-tool/) to schedule my Summaries Nightly. 

I have 2 summaries. Each are set to Active, set to Scheduled, and have the child triggers deployed. Previously they worked as realtime. When i changed to scheduled i removed and re-deployed the child triggers (What causes the trigger to change/need re-dploying?).

I then scheduled the RollupJob to run nightly, and I can see that it ran. But neither rollup summary actually did anything.  Lookup Rollup Summary Logs is empty, and there are no records under Lookup Rollup Summary Schedule Items on either summary.

Is there a missing step from the blog post instructions, @afawcett? Do I need to also schedule each summary? I am documenting w/ screenshots as I go for the wiki as well.

**Comment by JimBTek** [comment]
in testing one time when I did manual Calculate it ran without fail, but did not update the summary fields. I remove child trigger, tried manual calc, failed, deployed child trigger, ran, it worked, and it summarized correctly.....

**Comment by JimBTek** [comment]
also trying to test without waiting for an hour I've been trying to do:

```
RollupJob p = new RollupJob();
        String sch = '0 0 12 45 * ?';
        system.schedule('RollupJob Nightly', sch, p);
```
but it says "Invalid type: RollupJob"

**Comment by JimBTek** [comment]
jobs screenshot 
![](http://i.imgur.com/o0Vmxhq.png)

**Comment by JimBTek** [comment]
Nevermind, I reread [this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/141)  for the answer.  I will be adding to the wiki!

**Comment by afawcett** [comment]
Yeah as soon as you change child records in a way that effects the rollup, you should see records appear in the Lookup Rollup Summary Schedule Items ready to be processed.

**Comment by afawcett** [comment]
As regards your code above, you'll need the namespace prefix on the class / type...

    dlrs.RollupJob p = new dlrs.RollupJob();
    String sch = '0 0 12 45 * ?';
    system.schedule('RollupJob Nightly', sch, p);

**Comment by JimBTek** [comment]
Great thanks.  Ill add to the FAQ "How can i test the rollupjob?"


On Saturday, March 28, 2015, Andrew Fawcett <notifications@github.com>
wrote:

> As regards your code above, you'll need the namespace prefix on the class
> / type...
>
> dlrs.RollupJob p = new dlrs.RollupJob();
> String sch = '0 0 12 45 * ?';
> system.schedule('RollupJob Nightly', sch, p);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/142#issuecomment-87201947>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by wes1278** [comment]
Hey all,

If the field that is being aggregated is a cross-object formula, is there any way to force a "full" re-calculation of the rollup on a nightly basis? Before I started to dig into code, I wanted to see if you guys had any ideas how to accomplish this.

Thanks.

**Comment by JimBTek** [comment]
Yeah I am interested in this and had a comment on [#145](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/145) about possibly scheduling RollupCalculateJob instead of scheduling RollupJob but I guess you'd have to pass which job to run???

**Comment by afawcett** [comment]
Good idea @wes1278 marking as enhancement.

**Comment by JimBTek** [comment]
Wow that is awesome.

On Sunday, November 29, 2015, Andrew Fawcett <notifications@github.com>
wrote:

> Closed #142
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/142>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/142#event-477055498>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by sbaird80** [comment]
Hi Andrew, this is great. Do you need the trigger installed to run the Schedule Calculate?

**Comment by afawcett** [comment]
No.
