### ISSUE TITLE
Last Date rollup for a text field is not always setting the last record's values

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#143]
Help. I am seeing

I have two rollups that each copy a value from a field in the latest child record into the parent. The latest child record is based on a date field. It works most times but as I edit two different child records there are times when the wrong record's data is plugged into the parent but others were the correct one is plugged in.

I am running version: 1.18

The parent and child objects are both custom objects.

Field To aggregate: A comment field (32k long text) in the child object
Field to Order by: A date field in the child object
Aggregation Operation: Last
Aggregation Result Field: A comment field (32k long text) in parent object
Active: Checked
Calculation Mode: Realtime

There is no relationship criteria and no relationship criteria fields entered.

Any ideas?

Thanks again for a great too. This has already saved me about a day of coding and I am just getting started.

Thanks,
Guy

**Comment by afawcett** [comment]
Can you please include a screenshot of both rollups thank you.

**Comment by guygardner** [comment]
Here you go.

![screen shot 2015-04-01 at 11 37 48 am](https://cloud.githubusercontent.com/assets/11033529/6948603/bc6f4922-d863-11e4-8936-4b6b68b99cad.png)
![screen shot 2015-04-01 at 11 36 07 am](https://cloud.githubusercontent.com/assets/11033529/6948605/bf1f1846-d863-11e4-95ef-74fddd5ef647.png)

**Comment by aheber** [comment]
Is Status_Date__c a true date field or date & time? The reason I ask is that if they have the same date value, 1 April 2015 for instance, then you can't predict the order they will come up when ordered by that field. Just a shot in the dark.

**Comment by guygardner** [comment]
It is a Date (not Date Time)

**Comment by afawcett** [comment]
Good theory @aheber, @guygardner it could be that you don't have enough accuracy in just a date field then, do you see what @aheber is getting at? 

Also the first screenshot did not come through can you try again please.

**Comment by aheber** [comment]
@afawcett, I can see the screenshots.

**Comment by afawcett** [comment]
Ah spookly i can now as well...

**Comment by afawcett** [comment]
Yes now i can see both, i agree with @aheber, its likely that your using a date field type and not date+time field type. In the cases where things are going wrong do you have multiple child records with the same Status_Date__c?

**Comment by guygardner** [comment]
I am hand editing two records's date fields back and forth from one day to another and sometimes the rollup works but at other times it shows the wrong date (not the latest one).

I am not setting the dates to the same date, I set them to a day after or before the other and save and sometimes the rolled up fields are wrong.

Note: The comment and date value displayed are always from the same record, trouble is the date in that record is not always the last one.

**Comment by afawcett** [comment]
Are you editing both records together, say in a multi-edit list view case? Or are you editing one record and then the other. So between the first record edit and second record edit the dates could be the same?

**Comment by guygardner** [comment]
Nope. I edit one child record, save and check the roll up fields in the parent. Some times they are right and other times wrong. Haven't seen a pattern to it yet.

**Comment by guygardner** [comment]
I suggest creating this structure and trying it out. There is something almost random to it. I can also do a webex to show you if you'd like.

**Comment by afawcett** [comment]
Try putting the date field your editing in the Relationship Criteria Fields field on both rollups.

**Comment by guygardner** [comment]
That fixed it. It is now consistently working.

So it looks like an extra validation on saving a roll up might avoid that issue with others.

Thanks again

**Comment by afawcett** [comment]
Your welcome and we've been discussing relabelling the 'Relationship Criteria Fields' in a future release to make them more obvious in there use when there is no criteria.
