### ISSUE TITLE
Mispelling of "Dennied"

### ISSUE THREAD

**Issue by jasloz** [afawcett/declarative-lookup-rollup-summaries#144]
Notice the mispelling of Denied in the below error message:

Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_OpportunityTrigger: execution of AfterInsert caused by: dlrs.SObjectDomain.DomainException: Permission to access an dlrs__LookupRollupSummary__c dennied. (dlrs) Trigger.dlrs_OpportunityTrigger: line 7, column 1: [] Stack Trace==>Class.MembershipRenewalControllerPFLV2.submitMembership: line 180, column 1

**Comment by afawcett** [comment]
Fixed in latest release.
