### ISSUE TITLE
Date literals in rollups

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#145]
I am doing rollups that sum invoice totals Last 365 days, this year and this quarter on Account records where
`Invoice_Date__c = LAST_N_DAYS:365`
`Invoice_Date__c = THIS_YEAR`
`Invoice_Date__c = THIS_QUARTER`

The problem here is that a real time or scheduled Rollup won't fire again in 365 days to remove that invoice from the total on Accounts unless there happens to be another invoice (child record) that was added around that time or after. 

One solution I was looking at is a time based workflow on the invoice with a checkbox to uncheck it in 365 days which would update the record and trigger my nightly scheduled RollupJob.  However I am hitting the limit on adding workflow triggers.

The other solution I am considering is instead of scheduling RollupJob nightly, is to schedule RollupCalculateJob nightly to force a recalc on everything every night. Or possibly keep RollupJob running nightly to make any updates and run RollupCalculateJob every weekend to ensure it's clean.

**Comment by afawcett** [comment]
Its late and this might be a mad idea or even not possible at all, but i did just add process builder and flow support to the tool, one or both of those have schedule facilities, your thoughts around time based workflow made me wonder this.... i'm off to bed before i suggest more crazyness!

**Comment by JimBTek** [comment]
Interesting, I'll ask in the #salesforce IRC chat room, lots of smart devs in there.  Thanks & goodnight!

**Comment by afawcett** [comment]
Anything from the IRC Jim?

**Comment by JimBTek** [comment]
I am succesfully using the "checkbox" strategy for date literals but it is
taxing.  Both workflow time based triggers or process builder can be used
to schedule unchecking a box on a record to not count it anymore.  Workflow
time triggers are limited to 50 an hour in enterprise but can be raised to
500 on request.  Process builder seems to work better but i would combine
this with the idea of scheduling a full recalc and being able to schedule
different summaries separately.

Then you can easily use date literal This_Quarter and schedule
rollupCalculTeJob 4 times a year for just that summary.

For more time sensitive data it woukd be good to force a recalc every
sunday or even every night.

Also it looks like you can now fire apex from process builder either
immediately or scheduled so as long as a user can pick a specific summary
to execute process builder would be able to provide the rest of the
flexibility.



On Saturday, April 4, 2015, Andrew Fawcett <notifications@github.com> wrote:

> Anything from the IRC Jim?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/145#issuecomment-89515331>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by JimBTek** [comment]
It looks like the best solution is to be able to schedule the RollupCalculateJob with a specific lookup summary. Where is the code for the Calculate Button?

**Comment by afawcett** [comment]
Thanks @JimBTek, [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupCalculateController.cls#L45) is the code for the Calculate Button.
