### ISSUE TITLE
Multiple Rollup schedules

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#146]
any way to achieve either scenario:

* Run Scheduled Rollup A nightly at 2am then run Rollup B after A is complete
* Run Scheduled Rollup A nightly and Rollup B weekly

**Comment by afawcett** [comment]
Hmmm another good one @JimBTek your on fire today! :+1: 

Currently not in both regards, with the second one you can schedule the apexclass multiple times but in each case it will attempt to process the same schedule items. Some way to schedule a parameterised job and/or a means to express dependency, i suspet lack of this other feature is causing some other odd issues in schedule mode for folks that have a dependent rollups.

Marking as enhancement.... :+1:

**Comment by afawcett** [comment]
Some discussion [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p&fId=0D53000002FGboo&s1oid=00D300000000iTz&OpenCommentForEdit=1&s1nid=0DB30000000072L&emkind=chatterCommentNotification&s1uid=00530000004OFVZ&emtm=1448311956128&fromEmail=1&s1ext=0)

**Comment by afawcett** [comment]
"Yeah but still with that schedule it would require some action to be taken on the record. Where as in a scheduled calculate ALL would allow for it to re-evaluate records that have not had any changes but no longer meet said constraints."

**Comment by JimBTek** [comment]
@afawcett I believe this is resolved with the new scheduler as you can set a specific rollup to run at any specified hour and even have it run every hour (which I am doing in several places).

I am closing this

**Comment by afawcett** [comment]
Yes, good catch thanks! 👍
