### ISSUE TITLE
Remove from Lookup Rollup Summary Schedule Items when Parent is deleted

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#147]
Scenario:

* Bulk load Accounts (Parent) & Invoices (Child) from API
* Hundreds of Thousands of triggers scheduled
* Some Accounts are mass deleted
* Scheduled Job runs, where accounts are deleted error: "entity is deleted : ENTITY_IS_DELETED ()"
* These Schedule Items stay in Lookup Rollup Summary Schedule Items list

Should these get removed automatically from the Lookup Rollup Summary Schedule Items list?

OR should there be a way to bulk delete them?  If manually bulk delete it's hard to tell which ones you should delete vs. new ones that should be run during the next schedule.

**Comment by afawcett** [comment]
Good catch, auto delete i would say, should be doable.... thanks for marking as enhancement.

**Comment by afawcett** [comment]
Added in v2.4.1.
