### ISSUE TITLE
long text field in query call

### ISSUE THREAD

**Issue by egagnier** [afawcett/declarative-lookup-rollup-summaries#148]
Hi,

I try to aggregate a long text field (Description) in the Result Field. I get this message :
dlrs.RollupSummariesTrigger: execution of AfterUpdate caused by: System.UnexpectedException: field 'description__c' can not be sorted in a query call: (dlrs)

Is there a way to aggregate long text field via a 'Last' Aggregate Operation ?

Thanks

**Comment by afawcett** [comment]
Sadly this is a [platform restriction](http://www.salesforce.com/us/developer/docs/officetoolkit/Content/sforce_api_calls_soql_select.htm#i1422098) and not of the tool. So sorry i cannot doing anything about this, you will have to use a field type that is supported.

**Comment by egagnier** [comment]
What a shame ! thanks for your answer :)
