### ISSUE TITLE
Allow user to add a space after the Concatenate Delimiter

### ISSUE THREAD

**Issue by DeadMoneyDrew** [afawcett/declarative-lookup-rollup-summaries#149]
This is a cool tool and is saving me a lot of work. Good job folks!

Here's an enhancement idea. Allow the user to create a rollup that concatenates string fields with a space after the delimiter. My challenge was that I needed to concatenate together some text that will be pulled from Salesforce into a form letter. Currently there is not an obvious way to add a space in the appropriate place, and my concatenated text looked like this:

State Florida - $25,000,State Michigan - $31,695,State Oregon - $1,234

but what I needed was this:

State Florida - $25,000, State Michigan - $31,695, State Oregon - $1,234

I was able to work around this issue by making the target field a Rich Text formatted field and then adding an HTML non-breaking space clause in the Concatenate Delimiter field, like so:

,&nbsp;

But that took a good bit of brain aerobics. It would be useful to be able to add a space without having to use a Rich Text field or any HTML.

**Comment by afawcett** [comment]
Thanks for the kind words! :+1:  Can you elaborate on 'then adding an HTML non-breaking space clause in the Concatenate Delimiter field' please.

**Comment by afawcett** [comment]
See more info [here](https://success.salesforce.com/0D53000001v4Rub)

**Comment by DeadMoneyDrew** [comment]
Ha. Looks like github parses out the HTML. Let me try it again:

,& nbsp;

(without the space between the & and the n) is how I set the Concatenate Delimiter to show a comma followed by a space. Remember that this requires that the target field be of type Rich Text.

**Comment by afawcett** [comment]
Got it thanks! :+1:

**Comment by wes1278** [comment]
@DeadMoneyDrew @afawcett ,

How would you guys feel about an additional checkbox on the entry page that is named "Add trailing space"?

I think this is something we should fix as I've been asked about this exact issue when we can't make things rich text.

**Comment by afawcett** [comment]
I was thinking of adding NBSP() in addition to BR(), handling by extending the following [code](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/LREngine.cls#L312).

**Comment by afawcett** [comment]
If the target field is a rich text field the code would replace NBSP() with & nbsp ; or just the space character accordingly.

**Comment by afawcett** [comment]
I think this would work right?

**Comment by wes1278** [comment]
I agree. That would be a simple and easy fix.

**Comment by afawcett** [comment]
Fixed in current release.

**Comment by rogerrogers** [comment]
For simple spaces use: SP()
