### ISSUE TITLE
DLRS Not Calculating

### ISSUE THREAD

**Issue by dravenstien** [afawcett/declarative-lookup-rollup-summaries#153]
If the field "Type" on an activity equals "Customer Call" or "Prospect Call", a "1" is logged in the "Activity Record Count" field.  this field is rolling up on the account.  In this case those 2 calls were related to the Opportunity, not the account.  I see why they are not rolling up, but is there a way to count them without relating them to the Account?

![dlrs](https://cloud.githubusercontent.com/assets/11840242/7029888/43b83968-dd26-11e4-9f6d-f95a39594d30.JPG)
![dlrs2](https://cloud.githubusercontent.com/assets/11840242/7029916/831730e6-dd26-11e4-8bfa-57dc8337d546.JPG)

**Comment by afawcett** [comment]
I'm sorry i'm struggling to understand what you mean. Can you include a full screenshot of your rollup and a bit more detail on what is happening and what your expecting please.

**Comment by dravenstien** [comment]
What I didn’t take into account is that the Activity Type could be “Customer Call” or “Prospect Call”, but if it isn’t related to the Account in Salesforce, and is instead related to the Opportunity, it isn’t counting it in the total.  If that opportunity is a child of the Account, and meets the Activity Type criteria, it should count in the rollup.  Is there any way to do this? (I also included a screen shot showing a Customer Call that is related to an opportunity instead of an account.  But that Customer Call should be included in this rollup.



[cid:image001.png@01D0721B.CA0DA640]

[cid:image003.png@01D0721C.1E6C7720]


Diane Ravenstien
[sf]

p 620-931-2965
c 620-727-0061

**Comment by afawcett** [comment]
For some reason the screenshots have not made it, can you login to GitHub and drag drop into a new post, this seems to work... Thanks.

**Comment by afawcett** [comment]
Sorry about this, i'd still like to help, let me know if you still need me to help and can try to attach the screenshots again please.

**Comment by dravenstien** [comment]
I got it figured out.  It wasn’t a problem with the dlrs!  Thank you Andy.

Diane Ravenstien
[sf]

p 620-931-2965
c 620-727-0061

**Comment by afawcett** [comment]
Ah ok phew... thanks for getting back to me! :+1:
