### ISSUE TITLE
Duplicate Field Selected error message

### ISSUE THREAD

**Issue by Henzell** [afawcett/declarative-lookup-rollup-summaries#155]
I receive this error when I save a child record.
Apex trigger dlrs_Financial_Coaching_SessionTrigger caused an unexpected exception, contact your administrator: dlrs_Financial_Coaching_SessionTrigger: execution of AfterUpdate caused by: System.QueryException: duplicate field selected: Confidence_Obtain_Your_Credit_Report__c: (dlrs)

My use case is that I am rolling up from a Session record (child) to a Master record (parent). The field that I am aggregating, Confidence_Obtain_Your_Credit_Report__c, is used in 2 rollup summaries. One  rolls up using the First aggregate function, with aggregate result field being field A on the parent.  The other rolls up the same field, but uses the Last aggregate function, with aggregate result field being field B on the parent.

The error occurs when I have both rollups in Realtime calculation mode. If one rollup is in Realtime and the other is in Scheduled mode, then the error message does not appear.

**Comment by afawcett** [comment]
Ok this sounds like a bug, can you include a screenshot of both your rollups please?

**Comment by Henzell** [comment]
Screenshots attached. I'm hoping I can get around the issue by having one rollup work in Realtime, and the other Scheduled. 
![dlrs 1 2015-04-14](https://cloud.githubusercontent.com/assets/11064950/7150162/8db11c7c-e2dc-11e4-8c89-63ede958deb5.PNG)
![dlrs 2 2015-04-14](https://cloud.githubusercontent.com/assets/11064950/7150163/8f69c014-e2dc-11e4-94b7-b368bc715d47.PNG)

**Comment by afawcett** [comment]
Ok this is a bug, i'll mark it as such. Sorry about this.

**Comment by afawcett** [comment]
I have now fixed this in the GitHub master branch, and will be releasing in a new managed package for install shortly.

**Comment by afawcett** [comment]
Fixed in v1.21 release.
