### ISSUE TITLE
Apex Trigger is 0%

### ISSUE THREAD

**Issue by UsernameNotAvailable** [afawcett/declarative-lookup-rollup-summaries#157]
I'm trying to update the trigger code to only run "after insert". 

/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_CommercientSF8_AR_INVOICEa1aTrigger on CommercientSF8__AR_INVOICEHISTORYDETAIL__c
    (after insert)
{
    dlrs.RollupService.triggerHandler();
}

I tested the change in sandbox and it seems to work well, but when I try to import the set change into production, I get this error: dlrs_CommercientSF8_AR_INVOICEa1aTrigger, Details: Test coverage of selected Apex Trigger is 0%, at least 1% test coverage is required

I have the managed package installed on both sandbox and production on the current version.

Any help would be great.  

Thanks.

**Comment by afawcett** [comment]
You need to also deploy the generated test class with the trigger.

**Comment by UsernameNotAvailable** [comment]
Thanks for the quick reply, Andy!  I thought that might be it, the problem is that I can't actually include the "RoolupService" class in the Outbound Change Set.  I get this message when adding the dependencies to the change set: "Managed package dependency detected
Change sets may not contain components that are part of a managed package, as indicated by the managed icon below. To deploy this change set into another organization, you must first install the AppExchange package(s) containing the managed components into that organization, if they are not already installed."  Any thoughts?

Thanks again!

**Comment by afawcett** [comment]
Wow that is a new one on me, i am sure others have been deploying these classes/triggers via change sets before? Your other option of course it to simply replicate the rollup configuration in production and click the Mange Child Trigger button and tool will do the deploy for you.

**Comment by UsernameNotAvailable** [comment]
Thanks again!  I'm really just trying to change the trigger to run after insert not after updated.  Don't think I can do that in production.  Thanks for your help though.

**Comment by afawcett** [comment]
Ah i see, no you cannot change code in production, you have to go via a sandbox or appexchange packaging process. Let me know if i can help further!
