### ISSUE TITLE
RCED-related errors when users update child records

### ISSUE THREAD

**Issue by alan-birchenough** [afawcett/declarative-lookup-rollup-summaries#158]
Our clients are seeing what look like RCED-related errors when they update child records.  This wouldn't be an issue if we knew exactly what RCED and other security to give them for DLRS, so a summary would be appreciated.  Further details follow.

The error message in one recent incident looked like this:

Apex script unhandled trigger exception by user/organization: 005C00000040YAB/00D80000000beID
dlrs_SCMC_Purchase_Order_Line_a6xTrigger: execution of AfterInsert
caused by: dlrs.SObjectDomain.DomainException: Permission to access an dlrs__LookupRollupSummary__c dennied.
(dlrs)

Until now, I have been inferring - obviously incorrectly - that this package only needed to be installed for Sys Admin to access from a profile / RCED perspective, since other users are using a trigger behind the scenes to accomplish any rollups and should be blissfully unaware that any such rollups are happening.

On seeing this error, I am instead tempted to infer the following:
* Anyone configuring rollups needs RCED on Lookup Rollup Summary (the rule object);
* Anyone who might update a child record needs R on Lookup Rollup Summary;
* It is not clear what level of access they might need to other objects such as Lookup Rollup Summary Log and Lookup Rollup Summary Schedule Item;
* It is also not 100% clear to me whether users could run into difficulty if they cannot see (in FLS) either the "Field to Aggregate" or the "Aggregate Result Field", or if indeed, they lack E permission on the Parent object.

To explain my confusion, I have always thought of triggers as being run by the system rather than by any particular user, so the fact that DLRS need user-specific permissions for rollups to happen seems a little unexpected.

Can you please provide a summary of the security-related (mainly RCED and FLS I guess, since RLS is not likely to apply) requirements of DLRS?  That would be most helpful.  Thanks.

I would also like to take this opportunity to state how excellent this package is. and how grateful we are that you have made it available to the community.

**Comment by alan-birchenough** [comment]
On reading other issues, I see that there are two perm sets provided with this package.  **My bad for not reading those issues and finding the perm sets before.**  These perm sets clarify the expectations regarding the levels of access that users in different roles should have, so I guess I don't need a summary of security requirements after all.  However, it still confounds my expectations that, since correct "trigger-like" behavior is a matter of database integrity, on which the designer must be able to rely absolutely, it seems a bit onerous to require anyone who might edit a rolled-up child object to have R permission on the rule object.  I know that reasonable people can disagree about this sort of thing, so I offer this comment FWIW and would be interested in your opinion on the matter.  Otherwise feel free to close.  Thanks.

**Comment by afawcett** [comment]
I agree, i'll remove the object security checking on the rule object, but for now you need to assign users that are not editing rollups but editing child records they are referencing the 'Lookup Rollup Summaries - Process Rollups' permission.

![screen shot 2015-04-29 at 22 08 22](https://cloud.githubusercontent.com/assets/1167760/7401412/b27539e0-eebb-11e4-9633-be2827752802.png)


![screen shot 2015-04-29 at 22 08 11](https://cloud.githubusercontent.com/assets/1167760/7401402/a8c28c2c-eebb-11e4-9810-4f48ffcd6988.png)

**Comment by afawcett** [comment]
Decided to raise [this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/162) and point this issue and another at it.
