### ISSUE TITLE
Related Objects on relationship criteria and field to aggregate

### ISSUE THREAD

**Issue by peterschultz** [afawcett/declarative-lookup-rollup-summaries#160]
I was testing out this great tool and I had a use case for a client where I basically needed to run this SOQL query to populate the contact through the contact role based on information on opportunity. Maybe I am missing something but using lookups to handle "*Field to Aggregate" and "Relationship Criteria Fields" ? 
SELECT ContactId ,max(Opportunity.Amount) FROM OpportunityContactRole WHERE isDeleted = false AND opportunity.iswon = TRUE AND opportunity.accrual__c = TRUE AND opportunity.fund__c = 'a4a55000000CaR7' AND (role = 'Donor' OR role = 'Soft Credit') group by ContactId

**Comment by afawcett** [comment]
So in this case the parent object would be Contact and the child object OpportunityContactRole, the RelationshipField would be ContactId. So far so good... however...

- The Field to Aggregate has to be an immediate field on the child object (OpportunityContactRole in your case) and you need to aggregate Opportunity.Amount. Also there is no provision for Formula fields on the OpportunityContactRole object.
- Related to the above the tool does not monitor related fields for changes to determine if the rollup should be recaculated, e.g. the OpportunityContactRole.Opportunity.Amount field.

Sorry, better luck next time i hope! :+1:
