### ISSUE TITLE
Allow users to edit child records without needing access to Rollup Summary object

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#162]
Currently you need to assign a permission set to allow users editing child records which have rollups defined to successfully update the record, otherwise an access denied error occurs. Users should be able to edit child records without needing any specific permissions to read what are effectively system objects.

**Comment by afawcett** [comment]
Fixed in GitHub master branch, ready for next package upload.

**Comment by sd5000** [comment]
Thanks!

**Comment by afawcett** [comment]
No problem, i'll be uploading a new package within the next day or so, will update here when its ready.

**Comment by afawcett** [comment]
Fixed v1.21 package release.

**Comment by afawcett** [comment]
You now only need to assign Permission Sets to users who are managing rollups! :+1:

**Comment by aplssf** [comment]
Thanks!
