### ISSUE TITLE
System.TypeException: Cannot have more than 10 chunks in a single operation. 

### ISSUE THREAD

**Issue by alan-birchenough** [afawcett/declarative-lookup-rollup-summaries#168]
We are using additional roll-up triggers on our PSA Project Tasks to roll up totals to Iterations amongst other things.

A colleague was performing a story clone (a large-scale deep clone of stories from one project to another), and received the following error:
Apex script unhandled exception by user/organization: 005U0000000IVbz/00DU0000000JBB3
Visualforce Page: /apex/CloneStoriesFromTemplate
caused by: System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_pse_Project_TaskTrigger: execution of AfterInsert
caused by: System.TypeException: Cannot have more than 10 chunks in a single operation. Please rearrange the data to reduce chunking.
(dlrs)
Trigger.dlrs_pse_Project_TaskTrigger: line 7, column 1: []

It seems we may be indirectly invoking DLRS in such a way as to cause sub-optimal chunking, but we're not sure how to change our approach so as to improve the situation.  Any guidance on chasing this down would be gratefully received.

The error is in our production org, not a client's, so we should be able to reproduce this at the drop of a hat, and get access to logs, etc.

Thanks in advance for your advice.

**Comment by afawcett** [comment]
This might be a similar to this [issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/51), are you running the latest version of the package?

**Comment by alan-birchenough** [comment]
Thanks Andy.  We were on 1.13.  I am upgrading to 1.19 and will re-test.  If all checks out, I will close this issue.  Thanks again.

**Comment by afawcett** [comment]
Any luck @alan-birchenough?

**Comment by alan-birchenough** [comment]
Sorry -

I have not been able to get the instructions to reproduce from the person
who originally ran into this.  I will have another go at eliciting these
and I will dispose this issue accordingly.

Thanks for the reminder,
-- Alan.

On Sat, May 23, 2015 at 8:32 AM, Andrew Fawcett <notifications@github.com>
wrote:

> Any luck @alan-birchenough <https://github.com/alan-birchenough>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/168#issuecomment-104897065>
> .
>



--

**Comment by alan-birchenough** [comment]
I have been able to confirm that this was fixed by the upgrade to 1.19.  Thanks for your patience.

Regards,
-- Alan.

**Comment by afawcett** [comment]
Awesome thanks!
