### ISSUE TITLE
Rollup Not Working... Only when triggered via Process Builder

### ISSUE THREAD

**Issue by Gannuscio** [afawcett/declarative-lookup-rollup-summaries#169]
I am having a heck of a time trying to get the Rollup Triggers to update a field on an opportunity.  I have tried just about everything I can think of and the only thing that is working is when I build a process within Process Builder to fire the trigger.

Any thoughts?

**Comment by afawcett** [comment]
I'll need a bit more info to help please. Can you provide a screenshot of your rollup and the steps your going through to test the rollup please.

**Comment by afawcett** [comment]
Let me know if you want to discuss more, as i said, i'm going to need a little bit more to go on here... :+1:

**Comment by Gannuscio** [comment]
Hello,

Sorry for the delay.  Here is a snapshot of the configuration:

![screen shot 2015-05-24 at 3 25 48 pm](https://cloud.githubusercontent.com/assets/12454718/7789280/3c5e1e44-0229-11e5-847d-4f1da9856115.png)

The triggers are deployed and no errors are received.  When update a record on the Money_on_Account_Redemption__c account, the trigger doesn't update Liability_Money_Credit_Applied__c field.

With that said, I setup a simple process builder to run the Apex Trigger on record updates on the Money_on_Account_Redemption__c object, and the trigger works great.  I just cannot determine why it doesn't work without the Process Builder.

Does that help?

Thx for the support!

Brian

**Comment by afawcett** [comment]
You need to set the Calculation Mode to 'Process Builder', take a look at my [blog](http://andyinthecloud.com/2015/02/16/declarative-lookup-rollup-summaries-tool-dlrs-spring15-release/) for more details.
