### ISSUE TITLE
Cannot locate Apex Type for ID  CaseComment

### ISSUE THREAD

**Issue by aheber** [afawcett/declarative-lookup-rollup-summaries#17]
I get this error when trying to rollup from CaseComment

![image](https://f.cloud.github.com/assets/2173116/2363624/8fab03da-a651-11e3-98cc-42ab83a158bc.png)

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_CaseCommentTrigger caused an unexpected exception, contact your administrator: dlrs_CaseCommentTrigger: execution of AfterInsert caused by: System.SObjectException: Cannot locate Apex Type for ID: 00aS00000027nijIAA: (dlrs)

You can reproduce this error in Anonymous Apex:

``` Apex
Id myId = '00aS00000027nijIAA';

SObjectType childObjectType = myId.getSObjectType();
System.debug(childObjectType);
```

I'm not sure what the solution is as this seems to be a Salesforce bug. I couldn't find this reported in any known issues, but I'm generally new to Salesforce and could just not know where to look.

I'm going to pursue this through other channels, and will update this issue as I gather information.

Any short-term solutions short of very specific workarounds would be appreciated. Worst case I might write a small patch to my version just to meet my business objectives until something else presents itself.

**Comment by bradcis** [comment]
hey @afawcett, is there any movement on this one?

**Comment by afawcett** [comment]
I'll take a look at this next time i get a burst of dev time on the tool.

**Comment by skamensky** [comment]
Thanks for looking into this guys. I'm dealing with an issue unrelated to DLRS and this helped me out. Just in case anyone else sees this I ran into this issue with the a CustomShare object, which shares its id prefix with any other CustomShare object. SALESFORCE OYYY.

**Comment by afawcett** [comment]
Thanks for sharing @skamensky 👍

**Comment by afawcett** [comment]
v2.9

**Comment by KevinBR72** [comment]
After some digging, and experimenting, this appeared to work for me:
(called from after insert, after update, and after delete sections in trigger class)

`  private void declarativeRollupSummary (map<Id,CaseComment> mapOldRecs,map<Id,CaseComment> mapNewRecs) {
    
    dlrs.RollupService.rollup(mapOldRecs,mapNewRecs,CaseComment.SObjectType);
  }
`
