### ISSUE TITLE
Should Account unit test set an account name?

### ISSUE THREAD

**Issue by deckblad** [afawcett/declarative-lookup-rollup-summaries#170]
I'm hitting a unit test error on dlrs_AccountTest because I have a trigger method that assumes Account.Name will be set to a non-null string value.

For now I'll be fixing my method to handle that situation.

But, Account.Name is a required field, is it not? Shouldn't your unit test set a dummy value for that field?

**Comment by afawcett** [comment]
Unfortunately the tool is generic and does not know about the requirements of every object, standard or custom, the generated test really only needs the record to fire the before phase of its trigger, not for the record to insert, however in your case your trigger won't tolerate required fields not being entered (which are not enforced outside of the UI). 

There is another [open issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/122) that speaks about my adding support to allow the rollup definition to contain some default dummy values that will be injected into the test to help with these scenarios. 

So the answer is no, to this question, but yes to the tool helping support this use case better. I'll add another comment to issue 122 above.

**Comment by wes1278** [comment]
@afawcett, perhaps some of the work I did [here](https://github.com/wes1278/Salesforce-Test-Factory/blob/master/src/classes/TestFactory.cls) could help with the autogeneration of test code for preparing records based on their required fields

**Comment by afawcett** [comment]
Yes that might add some intelligence to it i agree. For sure worth exploring this, as i don't want to make the tool anymore complicated for the end user if possible. But then i suspect even with some intelligence there will always be corner cases, so i think some raw mode to led devs modify the generated code (perhaps a field on the rollup) which avoids having to break out into dev tools and deployment etc is the ultimate fall back.

**Comment by afawcett** [comment]
Closing this, as i think the general issue is well covered in [122](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/122)
