### ISSUE TITLE
dlrs_AccountTrigger appears to cause permissions error if Account Owner changed with "Send Notification Email" checked.

### ISSUE THREAD

**Issue by deckblad** [afawcett/declarative-lookup-rollup-summaries#171]
I can't quite say how to fully replicate this issue. I'm not able to provide any logs as it appears the package isn't logging any errors to my standard debug console. But:
Create account
Lick "Change" on Owner field.
Check only "Send Email Notification" option.
Select new user name from list.
Hit "submit"
I'll get an "insufficient privileges" error.

Leaving "send email" unchecked leads to success.
Unchecking "Active" on the Lookup Rollup Summary options also leads to success.
This is a RealTime Calculation Mode currently. I'm going to move to scheduled for the time being.

![rolluperror](https://cloud.githubusercontent.com/assets/4379218/7693388/40c54ce2-fd96-11e4-9679-2f5d4e23066c.png)

**Comment by afawcett** [comment]
Have you assigned the 'Lookup Rollup Summaries - Process Rollups' permission set to the user?

**Comment by afawcett** [comment]
Let me know if assigning the permission set does not resolve the issue and we can re-open this.

**Comment by deckblad** [comment]
I've replicated the issue in a sandbox. Then, added the Permission Set to both users. It still fails with the same generic Insufficient Privileges error.

Is there any way for me to see the debug output from this?

**Comment by afawcett** [comment]
I'm assuming this is because the tool is running and obey sharing rules and the code is running as the user making the change and they cannot update the current owner User record. There is an enhancement being proposed that might help with this scenario [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/183).

**Comment by deckblad** [comment]
Unfortunately, [that](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/183) newfeature didn't alleviate my issue.

I upgraded to 1.20 on my test sandbox. 
Added new Sharing Mode field to LRS edit page, set to 'System,' saved.
Logged in as test user.
Attempted to change owner on account owned by the current user, with "Send Notification" checked.
I get "Insufficient privileges."
If I go back and reassign owner to the same new person but don't check "Send Notification" it works fine.
If I deactivate the LRS rule and check "Send Notification" it works fine.

**Comment by afawcett** [comment]
Hmmm most odd. Can you enable Support Access and give me your Org ID and a list of steps to reproduce and i'll grab a Debug Log to review, you can then disable it.

**Comment by deckblad** [comment]
Oh hey, sure thing. I will have to do that tomorrow, though. Thank you.

Do you have more in-depth documentation on the Developer mode? I want to run it from a trigger context and dlrs.RollupService.triggerHandler(); didn't do anything for me. It seems to call the method but my test user fields don't update to new totals.

Thank you.

**Comment by afawcett** [comment]
Yeah that method is really for the tools own triggers, you need to have Realtime set not Developer mode to call that.  Take a look at this though, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/167.

**Comment by afawcett** [comment]
@deckblad just review the bugs backlog here, this one is old and having reviewed it i don't have enough info to reproduce. I'm guessing you'll likely have moved on now as well. Let me know if not and we can for sure re-open this issue. 👍

**Comment by peternoges** [comment]
@afawcett i am getting the exact same issue. I have granted you support access to troubleshoot in OrgID#00Dd0000000cYfb 

Steps to reproduce the error: 

1. Login to OrgID#00Dd0000000cYfb 
2. Login as user 0050V000006iuZP (Test User (sales management))
3. Once impersonating user 0050V000006iuZP open Account 001d000002Akus0 and click "change" near the Owner field and select user 0050V000006iuZP (test user (account executive)) and select (checkmark) the  "Send Email Notification" option.  If you checkmark that field and save you will see an insufficient privileges error.
