### ISSUE TITLE
Trying to compare ActivityDate with a WhoId's field (error is 'expecting a colon, found)

### ISSUE THREAD

**Issue by egagnier** [afawcett/declarative-lookup-rollup-summaries#172]
Hi,

I try to create a roll up on Events for a contact wich agregate (sum) Duration (no problem for this) ... but I want the roll up only agregate Events where ActivityDate is up to another Date (custom field : Date_du_premier_RDV__c) in the WhoId contact.

I tried the critera ActivityDate >=WhoId.Date_du_premier_RDV__c but I get the error : 

Relationship Criteria 'ActivityDate >=WhoId.Date_du_premier_RDV__c' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'expecting a colon, found 'WhoId.Date_du_premier_RDV__c''

Is there a way to resolve it ?

Thanks a lot for your help.

**Comment by egagnier** [comment]
Hi,

I tried another method. I crated formulas to get every date I need in the objet.

But when I tried a Relationship critera : Date__c>Date_debut_accomp__c, I still get the error :

Relationship Criteria 'Date__c>Date_debut_accomp__c' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'expecting a colon, found 'Date_debut_accomp__c''

What does mean ''expecting a colon, found 'Date_debut_accomp__c'' ? 

Thanks for your help ?

**Comment by wes1278** [comment]
@egagnier This is a platform limitation. You cannot compare two fields when using a SOQL query.  Please see this issue [#72](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/72).

Basically, you need to create a formula that resolves to a boolean value. That formula should do the comparison you're looking to do. Then, in the DLRS record, you can filter on your formula field = 1;

Let me know if that makes sense. I can help you out if you get stuck.

Thanks!

**Comment by egagnier** [comment]
Thanks a lot,

Good Idea! That's what I did ... but ... I have a new problem https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/174

Thnak you
