### ISSUE TITLE
Governor Impact

### ISSUE THREAD

**Issue by aalarson** [afawcett/declarative-lookup-rollup-summaries#173]
I would like to know a detailed breakdown of what impact this package will have on governor limits. Is it certified, or are there plans to get it certified on the AppExchange? That would mean it has its own set of governor limits and the impact would be 0. Otherwise, it is difficult for me to understand what impact it will have. Specifically in my org, I would like to know what impact a Real Time Count rollup would have on SOQL queries.

**Comment by afawcett** [comment]
Yes this is an Aloha package, it was certified back at v1.2, you can see the [README](https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history) (scroll down to v1.2 section) for details. Thanks!

**Comment by afawcett** [comment]
Just to clarify, it will not impact your tab and object limits, also Apex runtime governors are also scoped within its own code.
