### ISSUE TITLE
'Child field to aggregate' not present in picklist Enhanced Pilot ...

### ISSUE THREAD

**Issue by egagnier** [afawcett/declarative-lookup-rollup-summaries#174]
Hi,

I want to aggregate 'Duree__c' (SUM) from Activite__c cutom object.
Activite__c is related to contact object par Who__c field (principal-detail)

But as I chose 'Activite( Who__c)' in Child Object (Field), 'Duree_c' field is not present in 'Child field to Aggregate'

... Help
![decl](https://cloud.githubusercontent.com/assets/11683205/7726953/e59ef928-ff05-11e4-8626-237522792281.PNG)

**Comment by egagnier** [comment]
I found something : 'duree__c' field is a formula and I can't aggregate (SUM) formulas.

Another idea ?

**Comment by wes1278** [comment]
@egagnier This is actually a problem with that visualforce page. You can aggregate formulas, that page just filtered them out (it's a known bug).

To workaround, just select a different field for now, and then use the standard edit page (as opposed to the pilot vf page that you have a screenshot of) to write the API name of the field you want to aggregate.

**Comment by egagnier** [comment]
Thanks @wes1278 I started on this way but that's because it doesn't calculate I tried another way (VF page).

![decl2](https://cloud.githubusercontent.com/assets/11683205/7729104/44961f6c-ff13-11e4-969c-a1b2463cb1d7.PNG)

The result isn't here
![decl3](https://cloud.githubusercontent.com/assets/11683205/7729141/72de540c-ff13-11e4-9aeb-bca5868750bc.PNG)

**Comment by wes1278** [comment]
If you had pre-existing data, it sounds like you just need to hit the
"Calculate" button on the DLRS record so that it will go and fix the old
data. If you were to go and edit a child record, does it update the parent?

Wes Weingartner

**Comment by egagnier** [comment]
Yes I did it. Strange ! The Calculate Button works for some records. Most of them are still 0. They only update when I create a new child record. 

Great ! I need to crate a test record on 22000 contacts :)

**Comment by afawcett** [comment]
Do you see anything in the Lookup Rollup Summary Logs object that might indicate why some records didn't update?

**Comment by egagnier** [comment]
You're right! There are several errors :+1: 
setContactCoordinates: execution of AfterUpdate
caused by: System.AsyncException: Future method cannot be called from a future or batch method: geoLocationHelper.getContactLocation(Set<Id>)
Trigger.setContactCoordinates: line 15, column 1 : CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY ()

**Comment by egagnier** [comment]
I solved the problem by creating (and then deleting) a 1 minute's event for every contact using Dataloader. 

Thanks a lot for your help.
