### ISSUE TITLE
Some tests have hard-coded namespace

### ISSUE THREAD

**Issue by cwarden** [afawcett/declarative-lookup-rollup-summaries#175]
Some of the apex tests have the `dlrs` namespace hard-coded in them so they fail in dev orgs other than @afawcett's packaging org.

**Comment by cwarden** [comment]
I've opened #177 to address this.

**Comment by afawcett** [comment]
Re-opened it until i release the managed package.

**Comment by afawcett** [comment]
Released in v1.20.
