### ISSUE TITLE
classes are running in ‘With Sharing’ mode

### ISSUE THREAD

**Issue by Manjunath0591** [afawcett/declarative-lookup-rollup-summaries#180]
classes are running in ‘With Sharing’ mode , how to make them as ‘Without sharing’.
help please...
It is not calculating for all the users.

**Comment by afawcett** [comment]
I think this means you want a new feature, we need to make this configurable for existing users, so it does not change behaviour without users knowing. Maybe a new checkbox field on the Rollup Summary object 'See All Data', what do you think?

**Comment by afawcett** [comment]
This is a duplicate of [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/183) enhancement request.

**Comment by Manjunath0591** [comment]
ye, it is a good idea but still i think we can run all the classes in without sharing mode and control the sharing rules from profile or permission set.
Anything is fine , Is it possible for you to make it as soon as possible , it an emergency for me, i am stuck in the middle of something because of this.

**Comment by afawcett** [comment]
I can try and take a look at this, at the weekend, however keep in mind this is an open source community project, and thus depends on personal time availability.

**Comment by Manjunath0591** [comment]
ye sure, Thank you for the contribution,looking forward for the new feature.

**Comment by Manjunath0591** [comment]
Hi, any progress on the above requirement.If you don't mind, Is it possible for you to make this app as without sharing for time being?? i have real emergency for this app :(

**Comment by afawcett** [comment]
Yes, i released this in release v1.20 at the weekend, as per the duplicate issue i linked to this case earlier.

**Comment by Manjunath0591** [comment]
i update to v1.20 but i don't see any changes,it is the same old uI, there is no calculation sharing mode option. can you help me on this please.

**Comment by Manjunath0591** [comment]
got it,thanx, it was not added from page layout. :+1:
