### ISSUE TITLE
Required Fields Missing when the dropdown is populated

### ISSUE THREAD

**Issue by sarahforce** [afawcett/declarative-lookup-rollup-summaries#182]
I am receiving the following error when all fields are populated:

Error:
Required fields are missing: [Field to Aggregate]
![2015-05-27_11h03_55](https://cloud.githubusercontent.com/assets/12628752/7839521/a4eb0ff6-0460-11e5-8e2c-fbb66b8f118c.png)

Can you help?

**Comment by wes1278** [comment]
The pilot visualforce page that you're using has a known issue with the count operation. Set the Count to a different value long enough to save the record, then, use the standard salesforce edit page to edit the field to Aggregate to be Id

**Comment by afawcett** [comment]
Yes this is a known issue [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/34).
