### ISSUE TITLE
Greater Than and Less Than

### ISSUE THREAD

**Issue by dravenstien** [afawcett/declarative-lookup-rollup-summaries#184]
How do you correctly express relationship criteria of:
((Type='Customer Meeting' OR Type='Prospect Meeting') AND (ActivityDate>=2015-01-01) AND (ActivityDate<=2015-05-31))

I recently added the "AND (ActivityDate<=2015-05-31)" and it isn't calculating.  No error, it just isn't returning a value.  I'm trying to get Activity Date for just the 1st quarter 2015.

**Comment by afawcett** [comment]
Take a look at the Salesforce [docs](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm), maybe what you need is some of the QUARTER date literals. If your still struggling, please share your question on the Chatter Community group linked on the README file. Thanks! :+1:
