### ISSUE TITLE
First error: Invalid Id for Account

### ISSUE THREAD

**Issue by sbaird80** [afawcett/declarative-lookup-rollup-summaries#185]
A scheduled job throws an error "First error: Invalid Id for Account" I have 9 summaries all scheduled to perform counts sum jobs at a scheduled time each night.

**Comment by afawcett** [comment]
This feels like its related to issue [140](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/140) as well.

**Comment by afawcett** [comment]
Can you share the rollup definitions your using please?

I think i have a hunch about whats going on.

It relates to the OwernId being able to point to different parents i think....

**Comment by sbaird80** [comment]
![image](https://cloud.githubusercontent.com/assets/12708897/8100029/7da4ab74-1049-11e5-97b1-880a9dfe5326.png)
![image](https://cloud.githubusercontent.com/assets/12708897/8100032/862df278-1049-11e5-8ee0-a974f2030587.png)
![image](https://cloud.githubusercontent.com/assets/12708897/8100033/8cc64810-1049-11e5-926a-801daf0b48c1.png)
![image](https://cloud.githubusercontent.com/assets/12708897/8100035/963d6b94-1049-11e5-94f7-c8b7bf3b7ec7.png)

**Note I have changed them to realtime since posting this issue

**Comment by afawcett** [comment]
Are you still getting the issue?

**Comment by afawcett** [comment]
Also are any of your Session__c records owned by Groups/Queues rather than Users?

**Comment by sbaird80** [comment]
Hi Andrew, not since changing to realtime mode. All session__c records are owned by users only

**Comment by afawcett** [comment]
Ah ok, so when in scheduled mode, it was possible that Session__c records where owned by Groups/Queues? If so, i think i've spotted the bug! :+1:

**Comment by afawcett** [comment]
Another example [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/140).

**Comment by afawcett** [comment]
Ok i've made a fix in master for this, i'll package it shortly with a few other fixes i want to make. 

IMPLEMENTAITON NOTE:
- This fix will not address the issue for existing Lookup Rollup Summary Schedule Items records that have been incorrectly setup prior to this fix.

**Comment by afawcett** [comment]
Ok, i've made a further fix so that the schedule job will tolerate existing invalid schedule item records without error, it will delete them as well.

**Comment by afawcett** [comment]
Fixed in v1.21 release.
