### ISSUE TITLE
Got the following error after trying to deploy a trigger to a new object

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#186]
I created a new rollup for a new object and clicked the ManageChild Trigger to create the trigger but got this error:
------
Lookup Rollup Summary
Manage Apex Trigger for KITT_Docs_App_Used__c
 ERROR	
Error:
Salesforce Metadata API connection failure, click the link below to configure.
Return to the Welcome page
------

I then click the return to Welcome Page link and get this error:

------
Declarative Rollups for Lookups
Welcome
 ERROR	
Errors

Unable to connect to the Salesforce Metadata API.
A Remote Site Setting must be created in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.
 Important Post Install Step:
In order to utlise the features of this tool you need to permit the tool access to the Salesforce Metadata API by adding a Remote Site Setting with this Salesforce Server URL https://kpkitt--dlrs.na12.visual.force.com

Click the Create Remote Site Setting button to have the tool perform this step for you.

Overview: This is a tool that helps address a current platform limitation around rollup summaries. Specifically the inability to do rollup summaries between lookup relationships. This is possible between master detail relationships using the declarative mode of Force.com, but not between lookup relationships. You can read more about the tool and watch a video demo by reading this blog.

Release details can be found here.

DEBUG USE ONLY: IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://kpkitt--dlrs.na12.visual.force.com/services/Soap/m/28.0
------

Next I press the Create Remote Site Setting button and get this page:

------
Declarative Rollups for Lookups
Welcome
ERROR	
Error:
undefined
 Important Post Install Step:
In order to utlise the features of this tool you need to permit the tool access to the Salesforce Metadata API by adding a Remote Site Setting with this Salesforce Server URL https://kpkitt--dlrs.na12.visual.force.com

Click the Create Remote Site Setting button to have the tool perform this step for you.

Overview: This is a tool that helps address a current platform limitation around rollup summaries. Specifically the inability to do rollup summaries between lookup relationships. This is possible between master detail relationships using the declarative mode of Force.com, but not between lookup relationships. You can read more about the tool and watch a video demo by reading this blog.

Release details can be found here.

DEBUG USE ONLY: IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://kpkitt--dlrs.na12.visual.force.com/services/Soap/m/28.0
------

HINT:
I just recently start the work to enable SSO on my site. In the past I used NA12.Salesforce.com URLs and have switched over to using KPKITT.my.Salesforce.com style URLs. I think this may be causing some of the issue with this. I just don't know what to do to fix it now. Maybe add some remote sites manually? Other?

Thanks for looking at this. Things have been working great!

Guy

**Comment by afawcett** [comment]
Yes please try as the message suggests adding the remote site under Setup, copy paste the URL in the error message into the remote site setting.

**Comment by afawcett** [comment]
Let me know if this doesn't sort your problem and we can revist.
