### ISSUE TITLE
Implement the new test level features in Summer 15 to deploy triggers faster

### ISSUE THREAD

**Issue by dhoechst** [afawcett/declarative-lookup-rollup-summaries#190]
A new feature of Summer 15 allows us to specify tests to run when deploying code. It would be great to speed up deployments (and reduce failures) by specifying only the needed test when deploying the trigger. Check out my blog post for details: http://www.verticalcoder.com/2015/06/10/deploy-faster-with-summer-15-features/

**Comment by afawcett** [comment]
I'm using my new Priority tag for this one! :+1:

**Comment by afawcett** [comment]
I've recently written up some shared details on the [code coverage](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) issue described in this case, please check the details here and comment at the bottom of the wiki page.

**Comment by afawcett** [comment]
See v1.21 release.
