### ISSUE TITLE
Error deploying trigger:  Manage Apex Trigger for Opportunity

### ISSUE THREAD

**Issue by ibrown9** [afawcett/declarative-lookup-rollup-summaries#192]
I've installed and tested version 1.20 in our Sandbox instance with no issues.
After attempting to install in our Production environment, I get the following error when attempting to deploy the child trigger:

fflib_SObjectSelectorTest.testGetFieldListString System.AssertException: Assertion Failed: Expected: myprefix.Name,myprefix.AccountNumber,myprefix.Id,myprefix.AnnualRevenue,myprefix.CurrencyIsoCode, Actual: myprefix.Name,myprefix.Id,myprefix.AccountNumber,myprefix.AnnualRevenue,myprefix.CurrencyIsoCode Class.fflib_SObjectSelectorTest.testGetFieldListString: line 51, column 1

I'm having trouble discerning what the issue is and how to resolve from this error message.  Any insights or assistance would be greatly appreciated.  Image of the error attached and LRS as examples.

![dlrs_errorwhendeployingchildtrigger_opportunity](https://cloud.githubusercontent.com/assets/3853812/8183614/4f1bfc50-1407-11e5-83c7-170692a851a8.jpg)
![lookuprollupsummar_campaignopportunity](https://cloud.githubusercontent.com/assets/3853812/8183631/6aac5870-1407-11e5-93a7-b26b7c4d8928.jpg)

**Comment by afawcett** [comment]
Looks like your using the Deploy to Salesforce button or doing a managed package install? Sounds like the former? If there is no reason for you to develop or edit the tool code, i would strongly recommend you take the managed package version, its self contained and you won't get an test failures.

If you happen to have fflib unmanaged in your Production environment for other reasons, you'll find the tool currently runs ALL tests in the org when deploying the trigger (something that can now be avoided in a future release of the tool). Thus any unmanaged Apex tests in your Production org are run and will need to pass. Your error looks like an old error reported in fflib (see its repo), you may need to upgrade.

Again, a few possibilities what could be causing this here, need to understand a bit more about a) if your installing package or using Deploy to Salesforce (unmanaged install) and/or b) if you have fflib in your production org for other reasons.

**Comment by ibrown9** [comment]
Hi Andrew,

I installed v1.20 in both production and sandbox from the Production URL/Sandbox URL links on the main github page under Packaged Release History (I assume this is the managed package install versions).  I currently do not need to develop or edit the tool code.

After installing, I created a rollup summary and clicked Manage Child Trigger, clicking Deploy thereafter.  That is when I would encounter the error.

After speaking with my colleague, I was told the fflib installed by our SF partner was resued by our partner for a specific project they were working on.  I was curious about this because we do not have, nor have ever used FinancialForce (although I wish we did!).  As I mentioned, I was told the fflib was generic and being resued by are partner for work they were doing.

In order to bypass the error and deploy the child trigger successfully, we commented out the bad code and re-ordered the assertion elements.  This allowed me to deploy the child trigger successfully and it seems to be working now.

Thank you for taking the time to create this great tool and to responding.

**Comment by afawcett** [comment]
No problem, it is a general open source library FF share, and the community contributes to (i've just merged a community PR as it happens!). The issue with the test, i'm pretty sure has been fixed in the latest version in the fflib open source repo tbh, but if where happy to remove the test for now, thats saved you having to asses an upgrade as well. And yep, your very welcome, thanks for the feedback!
