### ISSUE TITLE
Reevaluate Guidance To Not Aggregate Formula Fields

### ISSUE THREAD

**Issue by cwarden** [afawcett/declarative-lookup-rollup-summaries#193]
The documentation states that aggregating formula fields is not supported.  Minimal testing [finds that aggregating formula fields works correctly](https://github.com/afawcett/declarative-lookup-rollup-summaries/commit/8f2ab0841cff6dbe09680d9c382bae74d2194e7d#commitcomment-11577442).

Test all aggregation functions against formula fields and update the documentation accordingly.

**Comment by afawcett** [comment]
Thanks for opening this.

**Comment by camisotro** [comment]
Any thoughts as to whether this advice should remain in the docs?

As far as I can tell, the only issue with aggregating formula fields is that the child won't trigger if the formula result changes as a result of something other than child data changing (i.e. a value on a related record). So maybe a **warning** is appropriate but not a validation to block formula fields.

What I've done in some orgs is aggregate the formula field in real-time but also add a scheduled calculation to ensure a periodic refresh.

**Comment by DanDonin** [comment]
I think it is just a warning.

**Comment by afawcett** [comment]
Fixed.
