### ISSUE TITLE
Managing Sandbox refreshes and changes sets

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#194]
This is firstly a question, and if there isn't an answer, then I suppose it's an issue.

I love this tool.  It's been immensely useful for my organization's work.  However, when I refresh my sandboxes, the lookup summaries are not included in the refresh.  This means that whenever I do a refresh, I have to manually add the summaries.  Additionally, it's not possible to add a lookup summary to a change set.

Is there anything I'm missing?  Is there a workaround other than manual creation in every sandbox at every refresh and change set deployment?  If not, could there be?

THANKS!

**Comment by afawcett** [comment]
Thanks, glad your enjoying it!

It sounds like you have a Developer or Config only sandbox? If not, you can configure what records are copied accross under the Sandbox config, and select the Rollup Lookup Summaries object.

Regarding Change Set deployment, have a read of [this](http://andyinthecloud.com/2015/06/14/be-one-with-the-platform-through-custom-metadata/)! :+1:

**Comment by afawcett** [comment]
Closing this, as the tool now supports Custom Metadata, which supports Change Sets, since v2.0. :+1:
