### ISSUE TITLE
Make Calculation Mode a multi-picklist

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#196]
A rollup is a definition that describes "what" to calculate, calculation mode is "when" to calculate it.  Currently, these two concepts are tightly coupled resulting in having to define the same "what" multiple times when needs arise to sometimes run it one way (developer mode) and sometimes another (realtime/scheduled).

Making developer mode a multi-picklist would solve this issue while still providing the intended purpose of being able to "not" include something in trigger/scheduled mode.

**Comment by afawcett** [comment]
Good idea, definitely needs a lot of thought, but i get your idea. There is also another enhancement idea around making the developer API behaviour work more like the realtime mode, that i'd put in such a bag of general enhancements in this area. Thanks for the idea. BTW, feel free to contribute if you like! :+1:

**Comment by jondavis9898** [comment]
Thanks Andrew and will try to contribute as soon as I can.  Another variant of this idea is to provide an overload of the rollup(List<SObject> childRecords) method that takes in the modes to include in its processing (rollup(List<SObject> childRecords, List<RollupSummaries.CalculationMode>).  For backwards compat, the existing rollup API would just pass "Developer" but the overload would allow other modes to be included in the processing.  

I think there are pros/cons to making developer mode work more like realtime mode.  In my particular situation, the fact that developer mode doesn't detect changes is actually critical (we delay rollups to occur until after a "large" batch is processed to reduce DML, etc.) so if this is what the other enhancement is goaling towards, possibly making that configurable would meet both ends.

**Comment by afawcett** [comment]
Interesting insight, for sure to maintain backwards compatibility, i'd say it would be a boolean or new API method to have it run like realtime mode anyway.

**Comment by jondavis9898** [comment]
I'm still partial to the multi-picklist to keep the concerns separate and provide declarative control over the "when" part.  The additional API would be means to and end but not as robust of a solution I don't think.  With that said, I'm still coming up to speed on the codebase so not sure what type of impacts making it multi-picklist would have.

**Comment by afawcett** [comment]
Yeah i hear what your saying, but i'm trying not to blur the lines between Realtime and Developer calculation modes. In some respects Realtime mode would probably have been better called 'Declarative Mode', but hey ho. I think its important for the users defining the rollups can control what scope they are used in. So i'd rather focus down making the API do what you want than making Realtime mode work in a API context, this will result in less changes as well, for example you won't need the trigger activation change. Hope this makes sense? Let me know your thoughts.

**Comment by jondavis9898** [comment]
Thanks Andrew.  Yes, definitely makes sense if my understanding of what you're thinking is accurate.  We've got a few different places we've been discussing this so shifting convo to #208 to continue if that's ok.

**Comment by afawcett** [comment]
Yep thanks, i'll close this one.
