### ISSUE TITLE
DLRS code coverage

### ISSUE THREAD

**Issue by SFTerr** [afawcett/declarative-lookup-rollup-summaries#198]
Hi, 3 Declarative Lookup Rollup Summaries Tool triggers have 0% test coverage (after 1.20 version upgrade):
dlrs_c2godaTransactionTrigger
dlrs_c2godaTransactionLineItemTrigger
dlrs_c2godaBankStatementTrigger

When I run related test class I get message for all 3 of them that "(1/1) Test Methods Passed", but code coverage is still 0.
I'm not getting any errors when I click “manage child trigger”.

Please advise

**Comment by afawcett** [comment]
Can you make sure you are running the latest v1.20 release, and ensure the test classes have dlrs.RollupService.testHandler in them, this will give some more error information rather than just a code coverage failure.

**Comment by afawcett** [comment]
You may need to re-generate the test classes in your sandbox, by using Manage Child Trigger button to remove and re-deploy, to get the new style test class. Then attempt again to deploy that via changeset to the production (which i assume your doing?).

**Comment by afawcett** [comment]
I've recently written up some shared details on the [code coverage](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) issue described in this case, please check the details here and comment at the bottom of the wiki page.

**Comment by SFTerr** [comment]
Thank you for that, now I got more meaningful errors, do you mind having a look and advise me on them?

Class	dlrs_c2godaBankStatementTest
Method Name	testTrigger
Pass/Fail	Fail
Error Message	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Bank Statement: Object validation has failed. Current company not set.: []
Stack Trace	(dlrs)
Class.dlrs_c2godaBankStatementTest.testTrigger: line 10, column 1
 
 
Class	dlrs_c2godaTransactionTest
Method Name	testTrigger
Pass/Fail	Fail
Error Message	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction: Object validation has failed. Current company not set.: []
Stack Trace	(dlrs)
Class.dlrs_c2godaTransactionTest.testTrigger: line 10, column 1
 
 
Class	dlrs_c2godaTransactionLineItemTest
Method Name	testTrigger
Pass/Fail	Fail
Error Message	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction Line Item: Object validation has failed. Current company not set.: []
Stack Trace	(dlrs)
Class.dlrs_c2godaTransactionLineItemTest.testTrigger: line 10, column 1

**Comment by afawcett** [comment]
Great, thats the first step to resolving the problem.

By the looks of these errors, it looks like the easiest way, is to simply run the Change Set deploy as a user with a company site. And, critically, have to apply @istest(seealldata=true) to test method instead of just @istest. You should be able to make this edit via Developer Console in Sandbox, test the tests run, then try again to deploy into Production (again when in production ensure the user has a company test).

**Comment by afawcett** [comment]
Of course, you may want to try the tip in the wiki page, to iterate some changes to the test code, via Execution Anonymous to get the precise test code needed, as the above may not work exactly for all objects.

**Comment by SFTerr** [comment]
Thanks Andrew, adding that @istest(seealldata=true) and login in as someone who has a company test and it works great for one of the classes (dlrs_c2godaBankStatementTest), but for remaining two, I'm still getting an error:

Class	dlrs_c2godaTransactionTest
Error Message	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction: Object validation has failed. You cannot create or edit transactions.: []

Class:

/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@istest(seealldata=true)
private class dlrs_c2godaTransactionLineItemTest
{
    private static testmethod void testTrigger()
    {
        // Force the dlrs_c2godaTransactionLineItemTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new c2g__codaTransactionLineItem__c());
    }
}

Class	dlrs_c2godaTransactionLineItemTest
Error Message	System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, c2g.CODATransactionLineItem: execution of BeforeInsert

Class:

/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@istest(seealldata=true)
private class dlrs_c2godaTransactionLineItemTest
{
    private static testmethod void testTrigger()
    {
        // Force the dlrs_c2godaTransactionLineItemTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new c2g__codaTransactionLineItem__c());
    }
}

Obviously no one can edit or create transactions, will you please advise what I can do to correct that?

**Comment by afawcett** [comment]
In this case, you will need to create a dummy document (journal, or invoice) and call the FF post API to generate a transaction this will cause the DLRS trigger to fire and cover the code. In this case you don't need any of the default generated code.

**Comment by afawcett** [comment]
Ok another option occured to me, the DLRS trigger just needs coverage, it doesn't need to via an insert, it could be an update. You may have more luck having the test code do something like this...

    update [select Id from c2g__codaTransactionLineItem__c limit 1];

**Comment by SFTerr** [comment]
so that's dlrs_c2godaTransactionTrigger:

/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_c2godaTransactionTrigger on c2g__codaTransaction__c
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    dlrs.RollupService.triggerHandler();
}

and dlrs_c2godaTransactionLineItemTrigger:

/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_c2godaTransactionLineItemTrigger on c2g__codaTransactionLineItem__c
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    dlrs.RollupService.triggerHandler();
}

both currently have 0% test coverage, where shall I add that update [select Id from c2g__codaTransactionLineItem__c limit 1]; line?

**Comment by afawcett** [comment]
Thats the trigger code, i'm talking about the test class code.

    /** 
     * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs) 
     **/ 
    @istest(seealldata=true) 
    private class dlrs_c2godaTransactionLineItemTest { 
        private static testmethod void testTrigger() { 
            // Force the dlrs_c2godaTransactionLineItemTrigger to be invoked 
            update [select Id from c2g__codaTransactionLineItem__c limit 1];
        }
    }

**Comment by SFTerr** [comment]
Hi, thanks for that, it shows me that dlrs_c2godaTransactionLineItemTest (1/1) test methods passed, but the code coverage is still 0%, same the dlrs_c2godaTransactionTest, but that one still hasn't pass, any suggestions?

**Comment by afawcett** [comment]
Hmmmm i'm trying to avoid you having to do much coding here, other wise my first suggestion has been known to work, e.g. create a journal and post it in the test. Before we get to that though, i'm curious why this approach hasn't worked, maybe its because the platform is realising we have not actually changed anything.... do you happen to have any custom fields added to your transaction objects?

**Comment by SFTerr** [comment]
I did not think of that, yes, both c2g__codaTransaction__c and c2g__codaTransactionLineItem__c have custom fields, some of them, are mandatory:

c2g__codaTransaction__c:
1. Transaction Date   c2g__TransactionDate__c	FinancialForce Accounting	Date

c2g__codaTransactionLineItem__c:
1. Line Number   c2g__LineNumber__c	FinancialForce Accounting	Number(18, 0)
2. Transaction Number   c2g__Transaction__c	FinancialForce Accounting	Master-Detail(Transaction)

**Comment by afawcett** [comment]
Any custom fields which you have added?

**Comment by SFTerr** [comment]
Yes, please see attached for details

**Comment by afawcett** [comment]
Hmmm don't see any attachment, looks like GitHub email doesn't support this? Perhaps you'll have to use the web UI.

**Comment by SFTerr** [comment]
Apologies for that, Transaction object:
Field Label

API Name

Data Type

Agency

Agency__c

Formula (Checkbox)

Always 1

Always_1__c

Formula (Number)

Analysis Total

Analysis_Total__c

Roll-Up Summary (SUM Transaction Line Item)

Cash Trend Date

Cash_Trend_Date__c

Formula (Date)

Closed Won Date

Closed_Won_Date__c

Formula (Date)

Collection Priority

Collection_Priority__c

Picklist

Conference Manager

Conference_Manager__c

Formula (Text)

Consolidation Group

Consolidation_Group__c

Formula (Text)

Credit control Notes

Credit_control_Notes__c

Long Text Area(32768)

CS Manager

CS_Manager__c

Formula (Text)

Current Month

Current_Month__c

Formula (Text)

Current Year

Current_Year__c

Formula (Text)

Deal Type

Deal_Type__c

Formula (Text)

Description

Description__c

Formula (Text)

Dimension 2

Dimension_2__c

Formula (Text)

Due date

Due_date__c

Formula (Date)

Due date

Due_date2__c

Date

Event Date

Event_Date__c

Formula (Date)

Event Start Date

Event_Start_Date__c

Formula (Date)

Finance Telephone

Finance_Telephone__c

Formula (Text)

Next action date

Next_action_date__c

Date

Office

Office__c

Formula (Text)

Opportunity

Opportunity__c

Lookup(Opportunity)

Opportunity Country

Opportunity_Country__c

Formula (Text)

Period Year

Period_Year__c

Formula (Text)

Prior Year

Prior_Year__c

Formula (Text)

Rebook

Rebook__c

Formula (Checkbox)

Reference 3

Reference_3__c

Text(2)

Repeat/Launch

Repeat_Launch__c

Formula (Text)

Reporting Period

Reporting_Period__c

Formula (Text)

Retention

Retention__c

Formula (Text)

Revenue Home Total

Revenue_Home_Total__c

Number(18, 0)

Sales Credit Note

Credit_Note__c

Lookup(Sales Credit Note)

Sales Invoice

Sales_Invoice__c

Lookup(Sales Invoice)

Sales Invoice Number

Sales_Invoice_Number__c

Formula (Text)

Sales value

Sales_value__c

Roll-Up Summary (SUM Transaction Line Item)

Sequence Number

Sequence_Number__c

Formula (Text)

Supplier Reference

Supplier_Reference__c

Text(30)

Tax rate

Tax_rate__c

Formula (Percent)

Tax total

Tax_total__c

Roll-Up Summary (SUM Transaction Line Item)

Week

Week__c

Formula (Number)

Year end close

Year_end_close__c

Formula (Checkbox)


And Transaction Line Item object:
Field Label

API Name

Data Type

Account Name

Account_Name__c

Formula (Text)

Aged Analysis

Aged_Analysis__c

Formula (Text)

As Of Age

As_Of_Age__c

Formula (Text)

As of Outstanding Excl. Tax

As_of_Outstanding_Excl_Tax__c

Formula (Number)

AUD value

AUD_value__c

Formula (Number)

AUD Value - Bill & Collect

AUD_Value_Bill_Collect__c

Formula (Number)

Bill & Collect

Bill_Collect__c

Formula (Text)

Cash Matching History

Cash_Matching_History__c

Lookup(Cash Matching History)

CM

CM__c

Formula (Number)

CM commission

CM_commission__c

Formula (Number)

CM commission rate

CM_commission_rate__c

Formula (Percent)

Conference manager name

Conference_manager_name__c

Formula (Text)

CY

CY__c

Formula (Number)

Days Outstanding

Days_Outstanding__c

Formula (Number)

Days outstanding grouping

Days_outstanding_grouping__c

Formula (Number)

Debtors Dim 2

Debtors_Dim_2__c

Formula (Text)

Debtors event date

Debtors_event_date__c

Formula (Date)

Delegate/SPEX

Delegate_SPEX__c

Formula (Text)

Description

Description__c

Text(255)

Dimension 2 Country

Dimension_2_Country__c

Formula (Text)

Event Date

Event_Date__c

Formula (Date)

Event Month

Event_Month__c

Formula (Text)

Event Name

Event_Name__c

Formula (Text)

Event Period

Event_Period__c

Formula (Text)

Event Quarter

Event_Quarter__c

Formula (Text)

Event status

Event_status__c

Formula (Text)

Event Type

Event_Type__c

Formula (Text)

Event Year

Event_Year__c

Formula (Text)

Expected collection period

Expected_collection_period__c

Formula (Number)

Expected debtor days

Expected_debtor_days__c

Formula (Number)

GBP value

GBP_value__c

Formula (Number)

GP type

GP_type__c

Formula (Text)

Home Outstanding value Excl Tax

Home_Outstanding_value_Excl_Tax__c

Formula (Number)

Home Value - Bill & Collect

Home_Value_Bil_Collect__c

Formula (Number)

Home Value Report

Home_Value_Report__c

Formula (Number)

Launch

Launch__c

Formula (Text)

Office

Office__c

Formula (Text)

Opportunity

Opportunity__c

Formula (Text)

Opportunity Event date

Opportunity_Event_date__c

Formula (Date)

Opportunity Event Period

Opportunity_Event_Period__c

Formula (Text)

Opportunity Event Status

Opportunity_Event_Status__c

Formula (Text)

Overdue grouping

Overdue_grouping__c

Formula (Number)

Period

Period__c

Formula (Text)

Project

Project__c

Formula (Text)

Project Code

Project_Code__c

Formula (Text)

Project Edition

Project_Edition__c

Formula (Text)

PY

PY__c

Formula (Number)

Reconciled

Reconciled__c

Checkbox

Reconciliation Number

Reconciliation_Number__c

Number(10, 0)

Revenue home total

Revenue_home_total__c

Formula (Number)

Revenue Total

Revenue_Total__c

Formula (Number)

Salesperson

Salesperson__c

Formula (Text)

Sales value

Sales_value__c

Number(10, 2)

Sale Type

Sale_Type__c

Formula (Text)

Start Date

Start_Date__c

Formula (Date)

Tax rate percentage

Tax_rate_percentage__c

Formula (Number)

Team

Team__c

Formula (Text)

THL Management fee

THL_Management_fee__c

Formula (Number)

Transaction equals Event Month

Transaction_equals_Event_Month__c

Formula (Checkbox)

Update Field

Update_Field__c

Text(5)

Year

Year__c

Formula (Text)

**Comment by SFTerr** [comment]
Please check your email address, as GitHub does not allow me to send files

Thank you

**Comment by afawcett** [comment]
Will do, i'm just starting a few days away from the computer mostly, but will check when i get an hour or so.... :+1:

**Comment by afawcett** [comment]
Release v1.22 contains support to more easily customise the generated test code, given advice from FinancialForce regarding Apex Test coverage on those objects, you can paste the snippets and adapt them to ensure DLRS tests generate the correct coverage.
