### ISSUE TITLE
Can't get the Rollups to fire

### ISSUE THREAD

**Issue by FRMoore914** [afawcett/declarative-lookup-rollup-summaries#200]
I deployed to Production and created 20 Rollups to a tes parent object with 6 test child objects. I set the rollups to realtime and tried editing one of the child objects, but no rollups semmed to fire. What am I doing wrong.
![image](https://cloud.githubusercontent.com/assets/1120407/8488102/6164acb6-20de-11e5-9a65-6e5a2c57b98f.png)

**Comment by FRMoore914** [comment]
Do I need to set up a batch job to run these rollups. I am going to have 466 of them for this one parent.

**Comment by FRMoore914** [comment]
I found my error. Hadn't filled out the Relationship Criteria Field.

**Comment by afawcett** [comment]
:+1: Happy rolling!

**Comment by FRMoore914** [comment]
Thanks. This was a life saver. My client needed to do around 3400 rollups across 9 custom objects. I am hoping it will all scale.

 

-----------Frank

 

FINAL FM Bus Cards_Back_Low Res

**Comment by afawcett** [comment]
Wow!!!! That is a lot, and none of those are over mater-detail objects? Make sure you pay attention to the README file it has some volume limit guidelines in that, which relate to rows of data rather than number of rollups. Only thing i could think is its likely you may have some rollup dependencies in that lot for sure, these do get complicated fast, they also don't play well in schedule mode where the order of invocation is less deterministic across multiple rollups vs realtime.

**Comment by FRMoore914** [comment]
We’ll see as I roll this out. The use case is I have a client that does audits of Home Health Care Agencies and they wanted a shared tool to record the individual results of patient or Personnel chart reviews on about 10 different forms. Each form has 60 to 130 questions of the Yes, No, N/A variety and they want a parent object to rollup the Yeses and Nos. So far I tested it on 10 questions (20 rollups). Let’s see how it scales.

 

-----------Frank

 

FINAL FM Bus Cards_Back_Low Res

**Comment by afawcett** [comment]
Sounds interesting. And none of these can be master/detail relationships and thus use platform rollups?

**Comment by FRMoore914** [comment]
Roll ups are limited to 10 per object although Salesforce will extend to 25 if you open a Case. I needed up to 350 per object.

----------Frank

**Comment by FRMoore914** [comment]
OK. I ran into the issue I was afraid of. I am up to 100 rollups to the master object and when I created a detail object I got the following message 

 



 

Sounds like I need to do this batch. Any suggestions?

-----------Frank

**Comment by afawcett** [comment]
I'm sorry i don't see the error message in your last post? Can you post again please.
