### ISSUE TITLE
Error with multi-currency

### ISSUE THREAD

**Issue by kvonachen** [afawcett/declarative-lookup-rollup-summaries#204]
I am trying to create a rollup summary to count the # of child records on the parent.  The org has multi-currency enabled and I'm getting the following error when trying to save the rollup summary record:

Invalid field 'CurrencyIsoCode' for object 'ApexTrigger'
Error is in expression '{!save}' in component <apex:commandButton> in page dlrs:rollupsummaryenhanced: (dlrs)

An unexpected error has occurred. Your solution provider has been notified. (dlrs

is there a fix to this?

**Comment by labrams** [comment]
I am have the same issue - is there any way to fix this? Thanks!

**Comment by afawcett** [comment]
Sorry about this, this slipped in as a regression from the last release. I'm doing a new release now!

**Comment by afawcett** [comment]
Fixed in v1.22.

**Comment by kvonachen** [comment]
Thank you so much!  The fix worked...you rock!!
