### ISSUE TITLE
Need to bulkify

### ISSUE THREAD

**Issue by FRMoore914** [afawcett/declarative-lookup-rollup-summaries#210]
I am trying to do almost 500 rollups per object. Ran into an issue at 100 as I have been testing this. Is there a way to bulkify so I can do a lot more rollups per object?

![capture](https://cloud.githubusercontent.com/assets/1120407/8831991/0b44be84-3074-11e5-825a-2dca6cff71d3.png)

**Comment by afawcett** [comment]
Yes, if your bulkifying your DML to the child object, if you produce a debug log are you making only one DML call to update Chart_Review object?

**Comment by afawcett** [comment]
Let me know if i can still be of assistance here and we can re-open.
