### ISSUE TITLE
Failures of DLRS-generated tests on objects that can't be inserted

### ISSUE THREAD

**Issue by alan-birchenough** [afawcett/declarative-lookup-rollup-summaries#211]
We are puzzled by some test failures we are seeing in some of our clients's orgs related to exceptions thrown when the generated test code tries to insert an object.  These failures are relatively hard to manage within our lifecycle because they are so unexpected, and on at least one occasion they have delayed a deployment.

Our understanding was that DLRS auto-generated test code would always wrap any insertion with exception-handling code, and so we should never see these errors.  To be specific, consider a FinancialForce PSA pse__Assignment__c object, which has numerous preconditions for insertion, none of which we propose to satisfy in the test.  An older form of auto-generated test code looked like this:
```java
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_pse_AssignmentTest
{
    private static testmethod void testTrigger()
    {
        // Code to cover the one line trigger, the method called has been tested separately by the packaged tests.
        try { insert new pse__Assignment__c(); } catch(Exception e) { }
    }
}
```
This works well.  It covers the trigger, and passes.  However, the current version of DLRS (at least 1.19 and later) generates the following:
```java
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_pse_AssignmentTest
{
    private static testmethod void testTrigger()
    {
        // Force the dlrs_pse_Assignment rigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new pse__Assignment__c());
    }
}
```
This fails if any precondition on the object being inserted is not satisfied.  For example, we are seeing managed package validation errors complaining that the bill rate field on the assignment is not set.  Is this a defect?  If not, how do we prevent these auto-generated tests from throwing validation exceptions on these harder-to-initialize objects?  Some of my colleagues have started adding explicit initialization code - sometimes quite extensively - to the tests to get them to pass, but my contention is that we should never edit the auto-generated code.  That way madness lies.

Thanks for any guidance you can provide.

**Comment by afawcett** [comment]
This testHandler only throws an error if the DLRS trigger was not executed, the previous code would swallow the code regardless. In Sandbox, because code coverage is not checked, this would differ a future problem when it came to pushing to production. As such i made this enhancement. 

I'm curious though, when using the earlier test class code did you manage to deploy to production with the same child object? I've written up some more details on this problem in the [wiki here](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) btw, it will shed a bit more light on the problem and some solutions.

**Comment by alan-birchenough** [comment]
Many thanks for drawing my attention to the wiki article.  I will get back to you when I more fully understand the issue.

**Comment by afawcett** [comment]
Your very welcome! :+1:
