### ISSUE TITLE
Rollup Summary validations not being enforced on updates after fflib upgrade

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#212]
Prior to fflib upgrade, onValidate of RollupSummaries was invoked in onAfterInsert & onAfterUpdate.  After the conversion to fflib, onValidate is only called by default during onAfterInsert which results in validations not being enforced when a rollup is updated.

**Comment by afawcett** [comment]
Ah good spot, kicking myself for missing that one! :+1:

**Comment by afawcett** [comment]
Fixed in v1.23
