### ISSUE TITLE
Allow rollups to be activated without requiring specifically named trigger

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#214]
We are using DLRS within our trigger framework (fflib).  Each SObjectDomain class derives from a common base class and the common base class invokes DLRS.  Our triggers are named to correspond to our SObjectDomain class and therefore do not conform to the naming convention that DLRS expects in order to allow activation of a rollup.

Enhancement: Enable support to allow activation of rollups without enforcing the trigger name check while still supporting backwards compat with previous library pattern.

**Comment by jondavis9898** [comment]
Proposed enhancement in https://github.com/afawcett/declarative-lookup-rollup-summaries/pull/215

**Comment by afawcett** [comment]
See my comments on the PR.

**Comment by jondavis9898** [comment]
I think we can close this one as we've shifted attention to approach in PR #208
