### ISSUE TITLE
Enhance Order by to allow multiple fields and specify ASC/DESC

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#216]
It appears that there is currently a restriction to only support a single Order By field on rollups.  In a quick review of the code, this might be a limitation at the LRE level.  Would like to see support for allowing multiple order by fields and a way to indicate ASC/DESC sorting.

Use case is related to a concat rollup that is first based on a date and then by quantity. There could be multiples that have the same date so going to a 2nd and even 3rd level for ensuring consistent sort order is required.

Am I overlooking a way to do this or would this need to be an enhancement?

**Comment by afawcett** [comment]
Nope your not overlooking a means to do, i've mark as an enhancement.

**Comment by jondavis9898** [comment]
Great, thanks!  I started the work on this one and have the LRE changes already made and its working as expected.  In my current approach I leveraged fflib_QueryFactory.Ordering which internally leverages fflib_QueryFactor.QueryField since it contains the functionality I need for this enhancement.  The alternative is to replicate that same functionality directly within LREngine.cls.  The only reason I can think of to replicate directly inside of LREngine.cls and not use the fflib classes is to abstract the enhancement so that those changes could be contributed directly to LRE project.

Preference on which way to go?

**Comment by afawcett** [comment]
Please enhance LREngine if you can please.

**Comment by afawcett** [comment]
Note that this will complicate the situation where you can merge rollups into a single LREngine rollup call if the order by's are different. So makes things less efficient. This is somewhat unavoidable if the user wants this functionality.

**Comment by jondavis9898** [comment]
Thanks for the direction, I'll work within LREngine for the enhancement rather than leverage the fflib classes.

Regarding merging rollups, I actually thought of this when I was going through this as I didn't see where merging "identical" rollups based on where clause and order by was currently being done.  I'll take another look through the code and make sure to account for this when implementing the enhancement.  Adding the additional orders by's shouldn't result in changing approach (need to look at the code first), but could result in not being able to merge if the user chooses different orders by's.  As you say, unavoidable if the order by ultimately needs to be different.

**Comment by afawcett** [comment]
Cool and yeah the code is [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupService.cls#L698).

**Comment by jondavis9898** [comment]
Thanks! :+1:

**Comment by afawcett** [comment]
Fixed in v1.24.
