### ISSUE TITLE
Allow Relationship Criteria fields to manage Rollup through Indirect Fields/Relationships.

### ISSUE THREAD

**Issue by mjhill86** [afawcett/declarative-lookup-rollup-summaries#218]
I’d like to be able to filter based on another object’s value through traversing to that object.

For example, in the Relationship Criteria field, the ability to use this syntax would be great: "Object API Name__r.Field Name" = 'XYZ%'

**Comment by wes1278** [comment]
@mjhill86 This isn't possible I don't think. While I think the DLRS tool could handle you putting something like that in the field with correct SOQL syntax, the event you would really care about changing, and thus causing a rollup, would not be on the child record, it would be on some other object where the DLRS trigger doesn't exist.

You might be able to accomplish what you're looking to do if you use a flow/workflow/process builder to perform an update on the children records whose parent's values have changed and would cause an update. Then, DLRS would listen to that field by putting it into the relationship fields data entry point of the lookup rollup record.

If you were to provide more details, I could probably help out more.

Thanks.

**Comment by wes1278** [comment]
@mjhill86 , Did this issue get resolved? Is there any other insight you could share? Should I close this issue?

Thanks!

**Comment by afawcett** [comment]
@wes1278 this is currently not supported

Yes @wes1278 i think after 27 days its time to close the issue. 

@mjhill86 if you need more help you can of course post again here or use the Chatter group.
