### ISSUE TITLE
Using the FIRST and LAST aggregate operations result in incomplete rollups - half my records get updated, the others remain blank

### ISSUE THREAD

**Issue by rcaustria** [afawcett/declarative-lookup-rollup-summaries#219]
First of all, thanks for this tool! It is a godsend! I already have a bunch of custom rollups in place that are running smoothly.

I recently created 2 rollup summaries to keep track of "First Gift Amount" and "Last Gift Amount" in my Account object. My rollup settings are as follows:

I'm using Salesforce - NGO Connect:
Parent Obj: Account
Child Obj: Opportunity
Relationship Field: AccountID
Field to Aggregate: rC_Giving_Closed_Amount__c
Field to Order By: CloseDate
Aggregate Operation: First (Last)
Aggregate Result Field: First_Gift_Amount__c / Last_Gift_Amount__c
Calculation Mode: Realtime
Calculation Sharing Mode: User

Roughly half of my account records get updated, while the others still have blank fields. Clicking on the Calculate button doesn't do much. Curiously I have some records where the First Gift Amount field gets updated and the Last Gift Amount field doesn't get updated, and vice versa.

I also have similar rollups this time for First and Last Gift Dates and those are working smoothly with all records being updated (Field to Aggregate: CloseDate, no Field to Order by).

Hope this gives you enough to go on, and I look forward to hearing from you. Thanks!

**Comment by afawcett** [comment]
Can you try this again and review the Apex Jobs page to see if any of the batches in the Calculate job fail?

**Comment by afawcett** [comment]
@rcaustria did you manage to review your Apex Jobs page?
