### ISSUE TITLE
Apex trigger still active after "removal"

### ISSUE THREAD

**Issue by Henzell** [afawcett/declarative-lookup-rollup-summaries#220]
I was having a conflict with the Contact trigger and other Apex. 
"First error: Update failed. First exception on row 0 with id 003i000000AyTcOAAV; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate
caused by: System.NoAccessException: Entity is not api accessible"

I went to the Rollup Summary that used the Contact Trigger, clicked the Manage Child Trigger button, and removed the trigger. But it's Status is still Active, and still conflicting.

**Comment by afawcett** [comment]
Can you confirm if the trigger has actually been removed? 

I think its a bug that Active still shows even if the trigger is gone.

**Comment by Henzell** [comment]
See attached from Apex Triggers page.
![dlrs 2015-08-13](https://cloud.githubusercontent.com/assets/11064950/9266896/efc72188-420c-11e5-81eb-cc7d82dce450.PNG).
I suspect that the issue has to do with permissions; I received a similar "entity not api accessible" error for the Task trigger yesterday. But as far as I can see, all profiles have permissions to read, etc on DLRS objects.

**Comment by afawcett** [comment]
Sorry i've been a bit dark, df prep.... is this still an active issue?

**Comment by Henzell** [comment]
Yes.

**Comment by afawcett** [comment]
Ok sorry to hear that. Can you create a new rollup (just a basic one) that references Task as the child, then use the Manage Child Trigger button to see if you can remove the trigger. Let me know if there is any error messages shown during the process. Also make sure your running the latest version of the tool (see Readme).

**Comment by Henzell** [comment]
Removing the Task trigger went without a hitch.

**Comment by afawcett** [comment]
Excellent, glad it worked. :+1:
