### ISSUE TITLE
Calculation Button Works, Realtime does not Work

### ISSUE THREAD

**Issue by jflatter** [afawcett/declarative-lookup-rollup-summaries#224]
Here is a screenshot of my rollup declaration. I have deployed the child trigger and activated the rollup. The rollup works when I manually hit the "Calculate" button. But If I edit an Order and change the Status to "Activated", the rollup value does not reflect this change on the appropriate Account object.

![lookup_rollup_summary__orders_to_account___salesforce_com_-_enterprise_edition](https://cloud.githubusercontent.com/assets/788372/9277124/172d2e3e-4276-11e5-8491-f361a1debc9a.png)

**Comment by wes1278** [comment]
@jflatter The relationship Criteria Fields is not correct in your rollup. You need to simply list the fields (their API Names) seperated by lines in that field.

It seems like you are trying to roll up the count of Orders with a status of "Activated" to the "Activated Orders" field on the Account object. 

I'm not entirely sure what/why you have TotalAmount>0. Either way, if it's meant to filter which orders are rolled up, that needs to be in the Relationship Criteria field, not the Relationship Criteria Fields field. The "Relationship Criteria Fields" field should be populated with any field on the Order Object that might cause the rollup to be fired. In your case, it should be AccountId, Status, and probably TotalAmount.

Let me know if you have any questions. (Also, please read the help text on the fields on the Lookup record. they give insight into what you need for each field.)

Good luck!

-Wes

**Comment by jflatter** [comment]
Excellent.

Thanks for the tip. Working beautifully now. It was the "relationship Criteria Fields" field.
