### ISSUE TITLE
Salesforce Security Review

### ISSUE THREAD

**Issue by skasarag** [afawcett/declarative-lookup-rollup-summaries#225]
I see that the homepage says that this app (DLRS) has passed Salesforce's Security Review. Is there a way to get confirmation that it has passed the Security Review? I don't see the app being listed on the AppExchange and when I opened an Service Request with Salesforce, they are saying that it hasn't passed the Security Review. It would be great if you can let me know how I can verify that it has passed the Security Review.

**Comment by wes1278** [comment]
I suppose @afawcett should answer this with certainty, but I know that DLRS is an Aloha package, it was certified back at v1.2.

Let me know if that helps.

**Comment by skasarag** [comment]
Thanks for the comment @wes1278 . I'm not sure if certifying it as an Aloha package would mean that it has passed Salesforce's Security Review. The reason for my ask is that Salesforce Support is saying that it hasn't passed the Security Review. I would like to know if there is another way for me to verify that it has passed the Security Review.

**Comment by afawcett** [comment]
As @wes1278 says it was passed in v1.2, but not later versions, i need to get round to resubmitted it, but DF prep is taking its toll. So i assume Salesforce is saying no to the current versions? I'll keep this case open until its been passed through review again for the latest version. You do only get Aloha if you've passed review, and you can now see under Installed packages if a package is exempt from Limits (which implies Aloha). Aloha however sticks for later versions which may not have been through review. Hope this clarifies, i'll get started submitting latest version this weekend hopefully. :+1:

**Comment by skasarag** [comment]
Thanks @afawcett for the explanation. Please let me know once the latest version has passed the Security review. 

Another related question: Is there a reason this package is not listed on the AppExchange? If it is listed, it would automatically mean that it has passed the Salesforce's Security Review, right?

**Comment by afawcett** [comment]
Latest version 1.24 has passed security review, you can see the [listing here](https://appexchange.salesforce.com/listingDetail?listingId=a0N3000000B45gWEAR).

**Comment by skasarag** [comment]
Thanks for the update
