### ISSUE TITLE
Issue with auto calculation in realtime

### ISSUE THREAD

**Issue by Breama** [afawcett/declarative-lookup-rollup-summaries#228]
Hello,

i have installed the latest Latest Version 1.22 of declarative-lookup-rollup-summaries. 

I believe i have everything setup correctly but, the roll up calculations are not calculating real-time, only when i manually click "Calculate"

Please Help!

Thank you

Tyler

**Comment by wes1278** [comment]
Did you deploy the child trigger and also update the record to have the Active checkbox checked?

**Comment by Breama** [comment]
Yes I have, can you contact me on skype please?

**Comment by wes1278** [comment]
Hello @Breama ,

This is an open source tool and doesn't offer any guarantees on support. I'm sorry. :( The contributors that help make this tool a reality work on this project as free time permits.

Did you get this issue resolved? I'm happy to try and help if you can provide some more context around what isn't working.

Thanks.

**Comment by Breama** [comment]
Hello, I haven’t yet.. I would like to have it looked at to make sure that I have it in there correctly.

Best Regards,

Tyler Schwartz | CEO, Breama Inc.
p: 780 870 2324
e: tylerschwartz@breama.com<mailto:tylerschwartz@breama.com>
w: http://www.breama.com<http://www.breama.com/>
a: 14th Floor, 10665 Jasper Avenue, Edmonton, Alberta, T5J 3S9
[cid:image002.png@01D0E00D.70D97300]

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks.
Breama Inc. is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

**Comment by afawcett** [comment]
@Breama please can you include here a screenshot of your rollup and list of the steps your doing to test it and the results your expecting, more screenshots the better. Thanks. :+1:

**Comment by afawcett** [comment]
@Breama please let us know the above further details and we can help you further.
