### ISSUE TITLE
Reduced number of queries when object name case differs accross rollups : Multiple LRE Contexts when rollup definition only differs by case

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#229]
When defining a rollup, if the only difference in the definition is the case (e.g. abc vs ABC) of a value specified for parent object, relationshipfield or order by, multiple LRE Contexts are created resulting in multiple SOQL statements.

For example, if two rollups are exactly the same but differ only by their "Parent Object" value of "LookupParent__c" and "lookupparent__c", a single context could be used but two contexts will be created and processed and two identical SOQL statements issued.

**Comment by afawcett** [comment]
Fixed in v1.23
