### ISSUE TITLE
Error on deploying trigger

### ISSUE THREAD

**Issue by kristenadams** [afawcett/declarative-lookup-rollup-summaries#232]
I'm getting an error trying to deploy this child trigger:
Error:
dlrs_causeview_PaymentTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, causeview.sysLastTransUpdatePayment: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object (causeview): [] (dlrs) Class.dlrs_causeview_PaymentTest.testTrigger: line 11, column 1

Thoughts on why this could be happening? I just upgraded to the new release. 

![untitled](https://cloud.githubusercontent.com/assets/13907780/9415629/83a2b758-47f5-11e5-9be8-81a829f483d3.png)

**Comment by afawcett** [comment]
This looks like a bug in the causeview.sysLastTransUpdatePayment trigger code, its not handling the fact that all of its fields could be blank on record insert. With the latest version of this tool you can work with a developer to paste in a more sympathetic test, such as....

    dlrs.RollupService.testHandler(new causeview_Payment(VitalField__c = 'Some Value'));
