### ISSUE TITLE
Error Message with addition of Record Types

### ISSUE THREAD

**Issue by jazzyp** [afawcett/declarative-lookup-rollup-summaries#233]
I am able to edit all list views (inline editing) as the admin without any issues. But when a certain user i.e.. FS user (profile/role for newly created record type) tries to do an inline edit on list view created for them specifically he receives the below error and cannot update the record. If this same user tries to make the change within the account record itself it will allow him to do so. 

Apex trigger dlrs_AccountTrigger caused an unexpected exception, dlrs_AccountTrigger:execution of AfterUpdate caused by: dlrs.SObjectDomain.DomainException: Permission to access an dlrs__LookupRollupSummary__c dennied.:(dlrs)

**Comment by wes1278** [comment]
@jazzyp, Are you on the latest version? Earlier versions of DLRS needed to have a permission set be granted to the profiles that needed to save records, and have DLRS run. You can see in the main DLRS readme the updates around not needing these permission sets anymore. 

Basically, you can upgrade and it should fix this, or you can go to Setup --> Manage Users --> Permission Sets and find the one meant to be used for non admins, and assign that permission set to the users (which is more than likely everyone in your org).

Let me know if that helps.

**Comment by afawcett** [comment]
Spot on @wes1278, either of your two suggestions will resolve the issue.

**Comment by jazzyp** [comment]
It worked perfectly thank you! I just added their permission sets
