### ISSUE TITLE
Issue with Install

### ISSUE THREAD

**Issue by mattsutton1976** [afawcett/declarative-lookup-rollup-summaries#234]
Hi
I'm trying to Install this package but am getting the error below. I've used the tool before with other clients but now getting this issue with a new client, unfortunately I am not much of a coder so this has thrown me.

Any ideas?

This app can't be installed.
There are problems that prevent this package from being installed.
Dependent class is invalid and needs recompilation: dlrs.rollupsummariesselector: line 30, column 46: Invalid type: fflib_SObjectSelector	managetrigger: Dependent class is invalid and needs recompilation: dlrs.rollupsummariesselector: line 30, column 46: Invalid type: fflib_SObjectSelector
(LookupRollupSummariesReadOnly) In field: apexClass - no ApexClass named fflib_SObjectSelector found	LookupRollupSummariesReadOnly: In field: apexClass - no ApexClass named fflib_SObjectSelector found

**Comment by robhgilmore** [comment]
I've also had the same error appear when trying to install from the app exchange. Is there supposed to be another way of installing the app?

**Comment by mattsutton1976** [comment]
I'm wondering if it is a licence issue the current client I am working on doesn't have enterprise licence only has Salescloud Professional

**Comment by robhgilmore** [comment]
I'm on enterprise and still get the error.

**Comment by mattsutton1976** [comment]
OK, thanks, that rules that out then.....

**Comment by wes1278** [comment]
Do you have any of the other fflib utilities installed manually (not using the package)?

This error is just saying that one of your classes is no longer compiling. If you go to Setup --> Develop --> Apex Classes, and then sort the list by Status, at least one of them should say "Invalid".

Try to edit and save that file; If it saves, great, try to install DLRS again. If it doesn't save, due to an issue with syntax, then you'll need to fix that first.

Let me know if that helps.

**Comment by afawcett** [comment]
This is most odd, fflib_SObjectSelector is a core part of the package and will not have been left out. The tool doesn't work on Professional edition, but i see thats not 100% the use cases here. Are you guys running Winter'16 sandboxes by any chance? 

Having unmanaged / manually installed fflib classes in your org should not conflict with packaged versions as they are isolated by namespace.

This smells like a platform bug.

**Comment by robhgilmore** [comment]
@wes1278  Thanks for the tip, but unfortunately I'm not able to find any Apex Classes with an Invalid status in my Dev or live org. 

@afawcett  I'm not, my sandbox is Summer '15. I tried the install again today just to check if anything had changed and received the same error. Thanks for looking into it, I'm itching to use your tool.

**Comment by afawcett** [comment]
Its really odd, my only next port of call would be to raise a Salesforce Case tbh. Given its only in your org, its probably best you do that and relay what they say here? Is that ok?

**Comment by robhgilmore** [comment]
Totally. Thanks dude. I'll let you know what goes on with it.

**Comment by robhgilmore** [comment]
Hey, so I was able to install the package today. I'm assume it was fixed with your most recent release? Not totally sure though. The app is working beautifully, thanks a ton for providing it.

**Comment by afawcett** [comment]
Ah good, your welcome! :+1:
