### ISSUE TITLE
Rollup not recalculated when order by field changes

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#240]
When the order by field on a child record has changed, if no other field involved in the rollup has changed, the rollup is not recalculated.  The reason for this is that the order by field is not included in fieldsToSearchForChanges (https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupService.cls#L540).  Order by influences query based rollups and therefore not including it could result in the rolled up value being incorrect.

Note that this issue existed prior to PR #227.

See https://github.com/afawcett/declarative-lookup-rollup-summaries/commit/3f2d31e9a7b9be7c7384e1886a82b9fa9fcbd6bc#diff-4aa41bc6f886aeba1cba33ce3962348cR1535 for demonstration of issue.  This test fails with prior code base on line https://github.com/afawcett/declarative-lookup-rollup-summaries/commit/3f2d31e9a7b9be7c7384e1886a82b9fa9fcbd6bc#diff-4aa41bc6f886aeba1cba33ce3962348cR1535 because the change to Amount__c is not considered material to rollup processing.

**Comment by afawcett** [comment]
Thanks @jondavis9898 another good spot, this will be most acute on the concatenation based aggregate rollups as you say.

**Comment by afawcett** [comment]
@jondavis9898 PR 244 fixes this i think, yes?

**Comment by jondavis9898** [comment]
Yep, this one is fixed in PR #244.

**Comment by afawcett** [comment]
Fixed in v1.24.
