### ISSUE TITLE
Not sure what I did wrong, please help

### ISSUE THREAD

**Issue by penguinphan** [afawcett/declarative-lookup-rollup-summaries#245]
Hi.  I'm not sure what I did wrong, but I just can't seem to get this working for me.  I think that I completed everything correctly, but it doesn't populate the "Units_Transitioning_Out__c" field.  One thing I noticed is that when I look at the trigger, it doesn't include the relationship criteria I specified, but I don't know if it is supposed to or not.  Here is a screenshot of what I entered:

![2015-09-03_16-08-08](https://cloud.githubusercontent.com/assets/4952045/9673203/a207c7a4-5256-11e5-97bf-b9495ceea093.png)

Any help you can provide me will be greatly appreciated.  

Thanks,

Matt

**Comment by penguinphan** [comment]
Here is a screenshot of the trigger that was created:

![2015-09-03_16-14-18](https://cloud.githubusercontent.com/assets/4952045/9673226/efb00fde-5256-11e5-8237-c83a3569b5f9.png)

**Comment by afawcett** [comment]
The trigger is fine, it reads the config you enter in salesforce dynamically.

Its worth asking in the chatter group (see README for link) about this.

I would try removing the criteria to see if the YEAR check is causing an issue.

Note that when the year changes the tool will not automatically recalc things.

You would have to manually click the Calculate button each rollup for that.
