### ISSUE TITLE
Error when Process Builder runs while Lookup Rollup Summary also active

### ISSUE THREAD

**Issue by kvonachen** [afawcett/declarative-lookup-rollup-summaries#247]
I have a couple of lookup rollup summaries set up in a client's org, and I also have a Process Builder set up, both triggering off the same child records but not for the same actions.  For some reason, the Process builder action is failing due to the dlrs trigger.  How can I make them work in harmony together?

**Comment by afawcett** [comment]
Yeah a combo deal of dlrs trigger and process builder rules on the same child object is going to be a challenge, i must admit i had envisioned using them independently when adding the later. Can you port your realtime / dlrs trigger rules to process builder invoked ones and then remove your dlrs trigger?

**Comment by afawcett** [comment]
Let me know if you need to discuss more on this?
