### ISSUE TITLE
dlrs:Too many query rows: 50001 in realtime

### ISSUE THREAD

**Issue by xhiena** [afawcett/declarative-lookup-rollup-summaries#254]
When I bulk re-parent more than 85 childs  in real time I have this exception  dlrs:Too many query rows: 50001 in realtime

I have like 5 rollups with the same parent-child.

I suppose I have a lot of rollups isn't it?

**Comment by afawcett** [comment]
Well its more like you have a lot of child records related to the parents, although your only updating 85, the aggregate query functionality the tool uses recalculates with all child records. You have two options, de-activate the rollups temporarily, perform your re-parent, then re-activate and click the Calculate buttons to catchup. Or switch some or all of your rollups to schedule mode. For more information see the Readme file for limitations of the tool (which mostly stem from the platform limits).
