### ISSUE TITLE
Is this possible: run trigger after both the Child AND Master are updated?

### ISSUE THREAD

**Issue by rygramer** [afawcett/declarative-lookup-rollup-summaries#255]
Andy, thanks for this great tool. I have just started my first Salesforce organization and was shocked by the limitations of the roll-up summary functionality built into the system.

I am attempting to do something a bit different, and was wondering if this would be easy to implement with your tool:

Is it possible to run the trigger after both the Child AND Master are updated? Currently the trigger runs when the Child is updated, but I am hoping to also run it whenever the Master is updated. My reason for this is that my Master controls some of the fields on my Child. When I make changes to my several of my Master fields, the changes are reflected in my associated Child fields. My roll-up summary field, however, is not updated.

Again, THANK YOU for putting this project together.

- Ryan

**Comment by afawcett** [comment]
Thanks! :+1: 

I assume your updating your child records via an apex trigger or flow triggered on the parent. If you want the child trigger to detect these changes add the field/s to the 'Relationship Criteria Fields' field. That way the rollup trigger will spot the changes and recalculate things. Be careful for cyclic updates to your parent though.
