### ISSUE TITLE
0% code coverage on dlrs_CampaignMemberTrigger and 'MALFORMED_ID' error when deploying changeset 

### ISSUE THREAD

**Issue by RKelly88** [afawcett/declarative-lookup-rollup-summaries#256]
Have recently tried to deploy a custom visualforce component with related Apex Triggers for a client where we are using DLRS. I am using DLRS to provide a count on the Account of Contacts who are also Campaign Members. The change set we are deploying relates only to the Opportunity object. 

Unfortunately the developer I am working with has no experience with DLRS and I don't have the code knowledge to work this out myself. I've noticed that other users have hit similar issues previously but they were resolved in later releases? We are using the most up to date release of DLRS so I'm really at a loss as to how this can be fixed.

See Screenshot below of error being thrown. Hope someone can help or we'll have no choice but to uninstall DLRS as what we are trying to deploy is critical for the client.

![image](https://cloud.githubusercontent.com/assets/10605187/10634016/b1ba0a4e-77e6-11e5-88e6-a8a30bd7eedf.png)

**Comment by afawcett** [comment]
Take a look at this issue, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197, this covers something similar. This should suffice for you, but let me know if not.
