### ISSUE TITLE
Multiple BR() for Concatenate

### ISSUE THREAD

**Issue by njamison** [afawcett/declarative-lookup-rollup-summaries#258]
First I have to say that I am a HUGE fan of declarative lookup rollup summaries. This fills a huge gap in the Salesforce eco-system and you all are doing a great job. 

Suggestion: I would like to be able to have multiple line breaks for the concatenate function (Which is a great function btw). If I could put in BR() BR() or even BR() BR() BR() that would be awesome. The reason is that we are rolling up data for display in reports and want the data to look separated.

Thanks for the consideration and keep up the great work!

**Comment by afawcett** [comment]
Thanks for the kind words! I've marked this as an enhancement.

**Comment by afawcett** [comment]
Only thought in the meantime as a workaround might be a formula field over your aggregate field to do a find and replace one BR with multiple BR's? https://help.salesforce.com/apex/HTViewHelpDoc?id=customize_functions_i_z.htm&language=en_US#SUBSTITUTE

**Comment by afawcett** [comment]
Fixed in v2.2.

**Comment by njamison** [comment]
Thank you for making this enhancement! I upgraded to v2.2 but I am not able to figure out how to use this enhancement. When I try putting in BR()BR() or BR() BR() or BR(),BR() it just adds those characters as text instead of inserting 2 line breaks. Any advice?

**Comment by afawcett** [comment]
Yes, sadly the fix didn't make it in for some reason, see this bug https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/291. I'll get to it next release, apologies in the meantime.
