### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by pautaran** [afawcett/declarative-lookup-rollup-summaries#260]
Hi! I cannot uninstall the package, do you have any suggestions how fix this?

**Comment by afawcett** [comment]
You will have to give some more information on what issue / error message / screen shot your seeing?

**Comment by afawcett** [comment]
Let me know if your still having challenges. I suspect it could be that you've not undeployed the rollup trigger before deleting the rollup. Readd the rollup and press the Manage Child Trigger button.
