### ISSUE TITLE
Allow First/Last Summaries to work on Id and Reference Fields

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#264]
As per PR [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/pull/261).

**Comment by kryan0618** [comment]
Hi Andrew,
I am having a problem with the DLRS and getting the Last Id. It does not seem to be working in all instances.
Here is a screenshot of the DLRS process:
![image](https://user-images.githubusercontent.com/32651743/34690300-2ee217da-f47e-11e7-8663-5b2d0f4f866e.png)
It seems to work when manually updating the record with the first audit. But I ran the DLRS to calculate for those accounts that have existing audits. It worked for some but not others.
Can you think of a reason as to why this would sporadically not work?
Thank you so much!!
Kris

**Comment by afawcett** [comment]
Did you see anything in Apex Jobs under Setup and/or on the Lookup Rollup Summary Logs tab?
