### ISSUE TITLE
Scheduled Calculate Custom Settings

### ISSUE THREAD

**Issue by DanDonin** [afawcett/declarative-lookup-rollup-summaries#265]
With the new Scheduled Calculate it runs nightly at 2am.  Is there a way to have this customizable to say run weekly or monthly or only weekdays at times other than 2am?

**Comment by frontendloader** [comment]
This would need to be an enhancement. To do this we'll need to create a schedule picking UI component. I'm willing to take this.

**Comment by DanDonin** [comment]
That would be amazing, I have little coding skills but if I can help in anyway I'd be willing to.

**Comment by afawcett** [comment]
Awesome gents! :+1:

**Comment by wes1278** [comment]
You could also just store the cron string on the rolluo record. I actually made a comment on a commit online with where a coffee updates would need to happen if that approach is taken

**Comment by afawcett** [comment]
Yeah thats the underlying approach for sure, i think though as we've learned with the criteria, usability wise we would need a Date/Schedule UI as most folks would struggle with cron string format. I had a brief look in the open source community for VF or even Lighting Schedule UI component and sadly didn't fine one. So we may have to develop one here, or at least a basic one for common use cases.

**Comment by afawcett** [comment]
Ok i found a few JQuery based UI's for this, but in the end went for a simpler one, as i could tailor it to Apex Schedulers own limits. Looks like this currently...

<img width="787" alt="dlrs schedule customisation" src="https://cloud.githubusercontent.com/assets/1167760/15992463/2ac7b46c-30c5-11e6-98fb-ed4ade5dc52d.png">

**Comment by afawcett** [comment]
Added in v2.4.1.

**Comment by rbhagat30** [comment]
how to schedule job for calculation mode as developer
