### ISSUE TITLE
DLRS trigger error: System.NoAccessException: Entity is not api accessible (dlrs) 

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#266]
I'm not sure what caused the error or how to reproduce.  Maybe there's an api setting I need to look at? See below.  

This is what I'm getting:
Developer script exception from Keshet : dlrs_OpportunityTrigger : dlrs_OpportunityTrigger: execution of AfterUpdate caused by: System.NoAccessException: Entity is not api accessible (dlrs) Trigger.dlrs_OpportunityTrigger: line 7, column 1

Details:
Apex script unhandled trigger exception by user/organization: 005A0000003XYvo/00DA0000000YPa1
dlrs_OpportunityTrigger: execution of AfterUpdate
caused by: System.NoAccessException: Entity is not api accessible
(dlrs)
Trigger.dlrs_OpportunityTrigger: line 7, column 1

DLRS Trigger code from SF:
1 /**
2 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
3 **/
4trigger dlrs_OpportunityTrigger on Opportunity
5    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
6 {
7    dlrs.RollupService.triggerHandler();
8 }

I'm running v1.23.  I could update, but since I'm not sure how to reproduce the error, I'd like to figure out what happened before upgrading....

**Comment by afawcett** [comment]
Yeah thats going to be a tricky one without a reproduction. If you had steps to reproduce, i could perhaps login via Subscriber SUpport (with your permission of course) and grab a more detailed stacktrace to pinpoint the line of code emitting this exception.

**Comment by JodiNA** [comment]
Gack!  That's what I was afraid of.  Any suggestions for how I could try to reproduce?  

I've gotten the error twice - and only in the last two days.  I'm wondering if there might be a conflict with the most recent NPSP release, which came out on Weds... I did read about a bug with payments (though it's since been fixed), so perhaps that could do it? https://github.com/SalesforceFoundation/Cumulus/issues/1860

After the first time I got the error, I removed the opp. trigger and then clicked "manage child trigger" to set it up again.  But since I got the error again after, I don't think that did anything!

**Comment by afawcett** [comment]
I'm not sure tbh really hard to tell based on this info, i would say adding/removing the trigger via Mange Child Trigger is unlikely to effect a runtime issue. Once the trigger is in place its good. What where you doing at the time these happened?

**Comment by JodiNA** [comment]
I wasn't even at my desk!  I came in this morning, opened my email, and
there it was!

Argh.

On Fri, Dec 11, 2015 at 2:31 PM, Andrew Fawcett <notifications@github.com>
wrote:

> I'm not sure tbh really hard to tell based on this info, i would say
> adding/removing the trigger via Mange Child Trigger is unlikely to effect a
> runtime issue. Once the trigger is in place its good. What where you doing
> at the time these happened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/266#issuecomment-164027518>
> .
>



-- 
*Jodi Nemser-Abrahams*
Information & Data Manager
Keshet
284 Amory Street
Jamaica Plain, MA 02130
617.524.9227x111

Web: www.keshetonline.org
Facebook: www.facebook.com/KeshetGLBTJews
Twitter: @KeshetGLBTJews <https://twitter.com/KeshetGLBTJews>
Blog: www.myjewishlearning.com/category/keshet/

*Celebrate Hanukkah* <http://www.keshetonline.org/resources/happy-hanukkah/>
 with LGBTQ inclusive resources, prayers, stories and events!

A teen. A mom. A straight rabbi and a queer rabbi.
See how we are transforming the Jewish community together
<https://youtu.be/3b8NL5jwt4o>.

**Comment by JodiNA** [comment]
Do you think it would make sense to run all of my rollups off of opportunities and hope it generates the error again?

**Comment by judisohn** [comment]
@JodiNA Try clicking the NPSP Settings tab, which is what immediately resolves the Payment issue you referenced above. That way you can tell for sure if the issue is related or not.

**Comment by JodiNA** [comment]
Thanks @judisohn.  I did that, and checked that automatic payments are enabled.  That's all I needed to do, yes?

**Comment by judisohn** [comment]
@JodiNA Yes. Now you should find that Opportunities are now automatically creating Payments records again. I'm not sure if that has anything to do with the problem with DLRS you reported here.

**Comment by JodiNA** [comment]
Thanks, @judisohn - me neither!  I'll see if I get the error again.

**Comment by JodiNA** [comment]
@afawcett I've gotten the error three more times since Friday morning, so this is a bit worrisome...

Any further suggestions of how to figure out what's causing this or what it's impacting?

**Comment by afawcett** [comment]
Have you been able to determine any common traits to what you where doing when it was working and not working?

**Comment by JodiNA** [comment]
Nope - I have no idea what they have in common.  I'm also not sure if it's actually causing any damage...

I'm going to open a ticket with SF support and see if they can give me any more information about what is setting off the error.

**Comment by afawcett** [comment]
Yes, TBH, i was going to suggest that next myself as well at this stage. In terms of damage, any exceptions like this on the platform automatically rollback any database changes involved to avoid corruption.

**Comment by JodiNA** [comment]
Good to know.  
Though, by damage, I more was wondering what *isn't* happening.  Like if a rollup is failing, but I don't know, then my reporting might be off. That kind of thing.

Will keep you posted!  Thanks for your help in trying to get to the bottom of this!

**Comment by afawcett** [comment]
Oh yes for sure the rollups will not be being updated i'm afraid until this error is resolved i would not trust them.

**Comment by JodiNA** [comment]
@afawcett Update: SF support won't help me because we are not a partner or premier customer.  They suggested I ask at developer.salesforce.com.

I looked back through my email and just discovered that the first time I got this error was in October during our installation of NPSP 3.  The consultant we were working with to do the install was getting the apex error.  I ended up turning deactivating the rollup and we she was able to proceed.

I'm going to poke through Cumulus and see if I can get any ideas. I have a strong hunch that something in last week's NPSP release is conflicting.  It just seems too concidental that I started getting these errors at the exact same time as the release.  I'm also looking through our scheduled Apex jobs to see if I can figure out which job is getting the error.

@judisohn  - any thoughts about last week's release?

**Comment by judisohn** [comment]
@JodiNA Make sure you are on NPSP 3.59, short of that it has to be a conflict with something else in your org, even if NPSP is somehow involved. DLRS is popular with NPSP users and I just haven't seen anyone else reporting this. You may have to have a developer help you with a deeper dive in your instance.

**Comment by JodiNA** [comment]
Thanks @judisohn - fair enough.

**Comment by JodiNA** [comment]
I figured it out!  It's Rollup Helper!

**Comment by JodiNA** [comment]
Update: spent a while with Rollup Helper support looking at the issue.  There seems to be some conflict (go figure!) between Rollup Helper and DLRS.  I'll post again if it seems like the issue is more pointing at DLRS than Rollup Helper. 

Thanks for all the help trying to get to he bottom of this!

**Comment by afawcett** [comment]
np :+1:

**Comment by JodiNA** [comment]
Ugh... got stuck again.  The response I got from Rollup Helper development team is:

What is occurring is that Rollup Helper is updating a record which then causes your DLRS trigger to run since the record is updated. The DLRS trigger is then encountering its own issues. 

So, not sure what the DLRS issue is.  Could it be something with contact roles?  The Rollup that's running is to count the number of primary contact roles on an opportunity.  I know DLRS can't do that because I tried to set it up before and was getting some error about contact roles not being accessible (don't remember where/how I got said error).

Thanks!

**Comment by afawcett** [comment]
Can you include a screenshot here of your rollup definition please?

**Comment by JodiNA** [comment]
Here are two shots.  One is of the problematic rollup with RH and the other is of all of the DLRS rollups with the parent or child object is opportunities.

![rolluphelper_contactrole_rollup](https://cloud.githubusercontent.com/assets/8515331/11943328/ef7a78ba-a80a-11e5-9854-4d8f732ddebb.jpg)
![opportunity_rollups](https://cloud.githubusercontent.com/assets/8515331/11943331/f177dd1a-a80a-11e5-9141-4040375d0197.jpg)

**Comment by afawcett** [comment]
Sorry i'm not at all familiar with RH to comment. You do indeed have a lot of Active DLRS triggers on the Opportunity child record. What activity is the user performig when this error occurs?

**Comment by JodiNA** [comment]
The error is not being triggered by users, as far as I can tell.  It is only being triggered when Rollup Helper tries to run the above rollup, which is every three hours.

The confusing part is that, as I believe I already mentioned, when I go to each rollup with opportunity as parent or child and calculate it, it works just fine. I've also checked the DLRS Summary Logs and have not found anything that corresponds to this error.

I really appreciate your help in trying to troubleshoot this.  Given that it seems to be a bit allusive, any suggestions of where else to turn to try to figure it out?

**Comment by afawcett** [comment]
Can you see if you can enable Debug Logs for the next time it runs? Then if they get captured, with Subscriber Support (needs to be granted by you), i could perhaps take a closer look.

**Comment by JodiNA** [comment]
Hi there,

I enabled Debug Logs yesterday, but due to timing and quantity of NPSP logs files, I wasn't able to capture a log for the exact time of the error.

I've set up logs to run today for the DLRS Opportunity trigger and the RH Job trigger, as well as user logs for the next hour for me and for the user who is named on the RH trigger.  RH is set to run at 1:00 PM EST today.  

I know this may be bad timing with the holidays and all, but if you think you can take a look, happy to grant login access.

Warmly,
Jodi

**Comment by afawcett** [comment]
No worries, i can take a look over next couple of days if you grant access.

**Comment by JodiNA** [comment]
Done!  Don't mind the mess.  Needs a little housekeeping in there! :-)

Thank you!  Let me know if you find anything.  I can set up more debug logs if necessary as well.

**Comment by afawcett** [comment]
So sadly i took to long to get to this for you and your subscriber support timed out, sorry. 

I have been doing some googling on this error and found this, http://salesforce.stackexchange.com/questions/69300/what-is-origin-of-error-entity-is-not-api-accessible-line-1-column-8. The DLRS classes are all using API 32, however i'm not sure what API level the RH classes are at, you can check this under Setup > Apex Classes, though i think its unlikely those will be as low as the example in the StackExchange answer. 

Some other thoughts...
- Do you have any custom objects that are named like a standard object, e.g. Opportunity__c or Account__c?
- What user is running the RH job?
- If the rollups work outside a RH job context, it has to be something to do with the context or user RH is putting the DLRS code in, hence the question above.

Regarding "count the number of primary contact roles on an opportunity"...
- I'll have a look see if i can get that going via DLRS for you.

**Comment by afawcett** [comment]
Yes, sadly I get the error, SObject type does not allow triggers: OpportunityContactRole, DLRS requires trigger support to work.

**Comment by afawcett** [comment]
**RE: count the number of primary contact roles on an opportunity**

Actually scrub my previous, i'd forgotten for a moment a recent community developer contribution called Scheduled Calculate. If you set your rollup to something that doesn't require a trigger, such as Developer or Process Builder, you can make it Activate and then use the Schedule Calculate button (which currently runs at 2am every day on all parent records, so be careful volumes wise, though you can specificy criteria)... Here is some screenshots...

<img width="1401" alt="screen shot 2016-01-10 at 10 56 49" src="https://cloud.githubusercontent.com/assets/1167760/12221221/1b9f839e-b789-11e5-95e8-9dd3fd75f030.png">

<img width="1282" alt="screen shot 2016-01-10 at 10 58 07" src="https://cloud.githubusercontent.com/assets/1167760/12221222/23524eaa-b789-11e5-8619-de1a6e35ad4b.png">

<img width="553" alt="screen shot 2016-01-10 at 10 58 23" src="https://cloud.githubusercontent.com/assets/1167760/12221223/27e23890-b789-11e5-8d8a-542571485f67.png">

**Note:** I used Custom Metadata mode, but if your not ready for that you should be able to setup just the same using the original tab (see my latest blog link via README).

**Comment by afawcett** [comment]
Hope this helps, let me know if not and we can re-open this.
