### ISSUE TITLE
Add support for ALL ROWS

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#267]
As per Chatter group discussion...

Hi All! Does anyone happen to know if there's a way to reference “ALL ROWS” in the relationship criteria?
 
Just ran into an issue with counting the number of tasks and realized that Salesforce archives older activities, including:
 
Events with a due date greater than 365 days old
Closed tasks with a due date greater than 365 days old
Closed tasks without a due date that were created more than 365 days ago
 
https://developer.salesforce.com/forums/?id=906F00000008xJqIAI
 
Someone in the above thread suggested adding “IsDeleted = false LIMIT 1000 ALL ROWS ” to a query to solve the issue; however, I haven't managed to successfully use it in the Relationship Criteria field.
 
Cheers,
Carolyn

**Comment by afawcett** [comment]
Another use case...

"First of all, thanks for this wonderful tool !
I'm currently trying rollups on task and event but i can't find a way to include archived activities in the result count (tried ALL ROWS in the relationshipcriteria but it does not work).
Any idea to achieve this ?"

**Comment by afawcett** [comment]
<img width="430" alt="screen shot 2016-06-15 at 20 32 32" src="https://cloud.githubusercontent.com/assets/1167760/16094468/4e73f95a-3338-11e6-9c71-9e97d0019b21.png">

**Comment by afawcett** [comment]
Added in v2.4.1.

**Comment by cbprice25** [comment]
AMAZING! :)
