### ISSUE TITLE
Invalid field 'CurrencyIsoCode' for object 'dlrs__LookupRollupSummary2__mdt'

### ISSUE THREAD

**Issue by jbcarey00** [afawcett/declarative-lookup-rollup-summaries#275]
When I click the Manage Child Trigger button in production, I get this error:

Invalid field 'CurrencyIsoCode' for object 'dlrs__LookupRollupSummary2__mdt'

**Comment by afawcett** [comment]
Are you running v2.1? If not please try upgrading, this should resolve this issue.

**Comment by jbcarey00** [comment]
Hello Andrew,

 

I want to first say we love this program and how easy it makes rollups and we recommend to our customers all the time.

 

I am on version 2.1 for this issue. We have been having trouble with the Deploy button over last several months in addition to this new issue I encountered.  William was able to build enough test coverage for me to deploy the trigger manually to production but thought you might could benefit being in communication with my technical associates that have encountered and overcome deployment issues.

 

Best Regards,

**Comment by jbcarey00** [comment]
Hi Andrew,

I concur with John's appreciation of this invaluable tool. The issues to
which he refers are those which you have documented in this excellent
article:

https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

I have merely applied those suggestions to those unit tests that, on
occasion, throw an exception for one reason or another.

Thanks for the quick response on the new version 2.1. That fixed our issues.

William

On Tue, Dec 29, 2015 at 2:35 PM, John Carey <jcarey01@msn.com> wrote:

> Hello Andrew,
>
>
>
> I want to first say we love this program and how easy it makes rollups and
> we recommend to our customers all the time.
>
>
>
> I am on version 2.1 for this issue. We have been having trouble with the
> Deploy button over last several months in addition to this new issue I
> encountered.  William was able to build enough test coverage for me to
> deploy the trigger manually to production but thought you might could
> benefit being in communication with my technical associates that have
> encountered and overcome deployment issues.
>
>
>
> Best Regards,
>
>
>
>
>
>
>
> *From:* Andrew Fawcett [mailto:notifications@github.com]
> *Sent:* Tuesday, December 29, 2015 3:05 PM
> *To:* afawcett/declarative-lookup-rollup-summaries <
> declarative-lookup-rollup-summaries@noreply.github.com>
> *Cc:* jbcarey00 <jcarey01@msn.com>
> *Subject:* Re: [declarative-lookup-rollup-summaries] Invalid field
> 'CurrencyIsoCode' for object 'dlrs__LookupRollupSummary2__mdt' (#275)
>
>
>
> Are you running v2.1? If not please try upgrading, this should resolve
> this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/275#issuecomment-167865507>
> .
>



-- 
William Rich
Senior Consultant, Icon Cloud Consulting
william.rich@iconcloudconsulting.com

**Comment by afawcett** [comment]
Excellent, thanks guys, appreciate the support and kind words. It seems all is well for the moment regarding your deployments. If not, please feel free to re-open this or a new one. Happy new year!
