### ISSUE TITLE
Add support for space & tab in concat delimiter

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#278]
SFDC appears to "trim" leading/trailing whitespace on text fields.  When inputting "; " or "  ;  " in concat delim, the data stored in the record itself does not contain the leading/trailing whitespace.  Anonymous APEX results in the same behavior.  For this reason, specific tokens are required to be added to support leading & trailing whitespace in the concat delimiter.  

Use Case - For a semi-colon delimited list of values, need to be able to separate the values with a space after the semi-colon to make the list easier to read.  

If anyone is aware of a way to avoid the whitespace being trimmed prior to record insert/update, I'd love to hear it! :)

Proposal is to add SP() and TB() tokens to provide for single space and tab character in delimiter.

**Comment by wes1278** [comment]
I want this feature too. I would definitely want the ability to have a space after a semicolon or comma.

**Comment by afawcett** [comment]
Fixed in v2.2.

**Comment by samlimster** [comment]
Hi folks.  I just installed DLRS and it's awesome!  However, I tried using ", " as a delimiter and I noticed that the trailing space is getting removed.  Is there a special format I need to enter to add a space at the end of the comma?  

More details: when I enter ", " and save it and go back to edit the field, it refreshes with ","

Thanks!  Much appreciated!

Sam.

**Comment by afawcett** [comment]
Have you tried ",SP()" ?

**Comment by BrettHabing** [comment]
Perfecto, my man! Thanks. 
Tip, for future readers, you don't need the quotations marks in your Concatenate Delimiter field. @afawcett gave us that to specify what we needed. Pretty sure you'll figure that one out on your own. Thanks again, Andrew!
