### ISSUE TITLE
Calculation Id not populating in Version 2.1

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#280]
I have version 2.1 installed in my sandbox environment and when I click the 'Calculate' button the "Calculate Job Id" field does not get populated. I have no way of canceling a calculation job when I know it will fail.

**Comment by afawcett** [comment]
I've moved tracking of this to a new object 'Lookup Rollup Calculate Job' since Custom Metadata was added. However i didn't think anyone would miss the Job ID, my bad. I'll get this added back in, in the next release, apologies for the regression.

**Comment by afawcett** [comment]
Fixed v2.3.
