### ISSUE TITLE
multiple criteria fields don't work anymore.

### ISSUE THREAD

**Issue by wes1278** [afawcett/declarative-lookup-rollup-summaries#281]
There is a line break in the dlrs record as pictured:
![screen shot 2016-01-08 at 11 57 19 am](https://cloud.githubusercontent.com/assets/596315/12203844/0a397c26-b5ff-11e5-9a62-47f61e5116f1.png)

But the trigger seems to break.
![screen shot 2016-01-08 at 11 55 11 am](https://cloud.githubusercontent.com/assets/596315/12203804/d7bd0a24-b5fe-11e5-9bc1-83078cd6c4bd.png)

**Comment by afawcett** [comment]
Yes this is a bug. The workaround is to set these via the Custom Metadata standard UI. I believe this was reported on the Chatter group, not sure if it found its way here, i'll check.

**Comment by afawcett** [comment]
The custom metadata api is removing the \r from the \r\n delimiter. Having spent some time with various XML escaping i've not been able to work around it. As such i've resorted to modifying the parsing code to support either \r\n or \n. I'll package it soon and get this fix out.

**Comment by afawcett** [comment]
Fixed in v2.2.
