### ISSUE TITLE
Rollup Error when another trigger on Parent object

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#283]
I have built a couple of rollups from my Invoicing object to the Sales Order object. When the sales order is submitted for approval a trigger (in a managed package) kicks off, which updates the Sales Order and creates an Invoice. The problem is the trigger for my DLRS jobs kick off as well causing a self reference error. Is there a way for me to say when these rollups kick off. like 1 minute after the record is updated.

Here is the error:

Error: Invalid Data. 
Review all error messages below to correct your data.
Failed to stage the sales order for shipment. Unable to complete save the invoice - see your Administrator.Upsert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_SCMC_InvoicingTrigger: execution of AfterInsert
caused by: System.DmlException: Update failed. First exception on row 1 with id a5pJ0000000Dy9AIAS; first error: SELF_REFERENCE_FROM_TRIGGER, Object (id = a5pJ0000000Dy9A) is currently in trigger SCMC.SalesOrderUpdate, therefore it cannot recursively update itself: []
(dlrs)
Trigger.dlrs_SCMC_InvoicingTrigger: line 9, column 1: []

**Comment by afawcett** [comment]
Can you use the scheduled mode?

**Comment by afawcett** [comment]
Let me know if Schedule mode does not help you here, we can re-open this issue and discuss further. Thanks.
