### ISSUE TITLE
DLRS trigger error

### ISSUE THREAD

**Issue by PacificScienceCenter** [afawcett/declarative-lookup-rollup-summaries#285]
Some of my users are receiving the following errors relating to the declarative lookup rollup summary triggers. We do have some custom, nonprofit-oriented objects built by a third-party consultant but after submitting the issue to them, they suggest the DLRS trigger is causing the error. I have attached screenshots of the errors, any help would be great. Thank you

![jn_new_gift_error_msg](https://cloud.githubusercontent.com/assets/16766848/12404128/c93aadde-bded-11e5-8ac5-44cc7688b98a.jpg)
![ss_contact_update_error_msg](https://cloud.githubusercontent.com/assets/16766848/12404130/c9449d1c-bded-11e5-9d9f-716d534e0623.jpg)
![bc_call_log_error_msg](https://cloud.githubusercontent.com/assets/16766848/12404129/c943bea6-bded-11e5-9f2d-4f1d0a3ad7c0.jpg)

**Comment by afawcett** [comment]
Can you try upgrading to the latest version, i believe this has already been fixed. If you don't want to upgrade, their is a permission set you can assign for now.

**Comment by PacificScienceCenter** [comment]
After updating to 2.2, I'm now receiving the following error: (specifically when updating a contact address)

Error:Apex trigger dlrs_ContactTrigger caused an unexpected exception, contact your administrator: dlrs_ContactTrigger: execution of AfterUpdate caused by: **dlrs.fflib_QueryFactory.InvalidFieldException**: Invalid field **'CreatedDate'** for object 'dlrs__LookupRollupSummary__c': (dlrs)

Any advice on how to fix this error?

**Comment by afawcett** [comment]
I'm not sure, looks like a bug, would you be able to enable subscriber support and provide your org id with some steps to reproduce? This would allow me to get a debug log and look at specifically where in the code this error stems from.

**Comment by PacificScienceCenter** [comment]
Sorry for the delay- yes I will enable subscriber support for a week (exp 2/16). Our org ID is 00Do0000000J1uj.

As far as reproducing the errors; the error happened after attempting to log a call (contact report) from an individual record. Specifically, using the "log a call" button under activities on the individual record page. Is there any further information that I could give that might help?

Thank you!

**Comment by afawcett** [comment]
Please can you confirm exactly what record (ideally a link) and steps you want me to reproduce this on, i'm not sure i should be going into your org and randomly creating a call record.

**Comment by PacificScienceCenter** [comment]
Sure thing, please ahead and and attempt to log a call on this record:[https://na17.salesforce.com/003o000000Zbzqw](url). You can put "test" in the comments just so its clear why the record was created.

I'm not sure if I specified this earlier- as a system admin, I and other system admins are able to complete this without the error. It is other users who are receiving the error. I am not sure what the result will be for you logging in as support.

**Comment by afawcett** [comment]
Ok i could not reproduce with that user. If it only works for admins and not regular users, i'm wondering if it is a permissions thing. These should not be checked for child record changes since an earlier version of the tool, however i wonder if there is some checking still being done. Can you try assigning the tool permissions sets to an effected user or granted access to the DLRS objects and fields on their profile.

**Comment by PacificScienceCenter** [comment]
Alright, I've adjusted permission sets and had one of my users who was receiving the error, successfully log a call. Seems to have fixed the issue. I will follow up with a few more tests on monday and close this if nothing else comes up.

Thank you so much for the help, we really appreciate it!

**Comment by afawcett** [comment]
Your most welcome! :+1:  I'll raise a bug though myself as the current tool should not require this workaround.

**Comment by afawcett** [comment]
@PacificScienceCenter can you recall what you changed on your users permissions to get it working?
