### ISSUE TITLE
Can't Create more than one Lookup Rollup Summary for the same child object

### ISSUE THREAD

**Issue by AlexVilks** [afawcett/declarative-lookup-rollup-summaries#288]
Hi Andrew!

I've created Lookup Rollup Summary to calculate count of Tasks for Opportunity (Task.Type = 'Email'). and all works perfectly. 
But then I've tried to create another one Lookup Rollup Summary for almost the same purpose - to calculate count of Tasks for Opportunity, but Task.Type = 'Call'.
But when I try to manage child trigger to finish creating of my second Rollup Summary, I see the same trigger as for the first one. 
So, I'm not allowed to create a new trigger, and  that's why I can't create more than one Lookup Rollup Summary for the same child object.

![taskcount](https://cloud.githubusercontent.com/assets/16879258/12551443/8c4aafbc-c37b-11e5-9384-3403bbae97cb.png)
![taskcount2](https://cloud.githubusercontent.com/assets/16879258/12551449/8f88ae86-c37b-11e5-8141-030c2c79f83e.png)
![managechildtrigger](https://cloud.githubusercontent.com/assets/16879258/12551451/935fd4d0-c37b-11e5-9dde-ddc3afc8c470.png)

Please, assist.
Thanks in advance.

**Comment by matcadg** [comment]
You need to create only one trigger per child object. Make new roll-up definition 'active' and voilà, it will calculate.

**Comment by AlexVilks** [comment]
Thanks a lot! It works!
I had some thoughts, that the existing trigger can't be updated automatically and I should re-deploy it each time.

**Comment by afawcett** [comment]
Thanks @matcadg spot on! @AlexVilks glad your sorted!
