### ISSUE TITLE
Rollup Summary to count number of Tasks Realtime does not work

### ISSUE THREAD

**Issue by violetyyyy** [afawcett/declarative-lookup-rollup-summaries#289]
#Created a roll up summary to count the number of tasks on a custom object but it does not work RealTime. It works when I click Calculate

- Created a number field on custom object
- Created a formula field on Task (Activity Custom field) that is set to 1 #
- Deployed the Manage Child Object 
- set the roll up to Active 

![image](https://cloud.githubusercontent.com/assets/14101361/12557216/a4f8ede0-c357-11e5-9424-8bebfe1e99a5.png)

**Comment by afawcett** [comment]
Have you tried using the Count operation? In this case the Aggregate Result Field can just be something like Id. If its still not working can you confirm the steps your going through to test it please. Thanks.

**Comment by violetyyyy** [comment]
Thank you for the reply. Please let me know if further information is needed. 
I tried using Count as well but it still does not do
- When creating, added all the information and saved 
- deployed the trigger
- set the roll up as Active 

Testing steps:
- Added a Task to the object and tried refreshing the page a couple of times but didn't work 
- tried "Calculate" button and it worked


![image](https://cloud.githubusercontent.com/assets/14101361/12739198/48ee7392-c935-11e5-8876-3396202d8b8f.png)

**Comment by afawcett** [comment]
This seems to work for me, when i added tasks the rollup calculated. What steps are you using to reproduce your problem?

<img width="1258" alt="screen shot 2016-02-09 at 20 06 59" src="https://cloud.githubusercontent.com/assets/1167760/12929079/d62039e2-cf68-11e5-81bb-76e3109fe03a.png">
<img width="905" alt="screen shot 2016-02-09 at 20 07 30" src="https://cloud.githubusercontent.com/assets/1167760/12929082/db1f9c62-cf68-11e5-8037-519f5e07a5ad.png">

**Comment by violetyyyy** [comment]
Thank you for trying it and for the reply. I tried reverting back the roll up summary from scheduled to realtime and added a task but not luck. I have used the roll up summary in other salesforce Orgs and never been able to get realtime working not sure if I am missing a step/setting. 

- add the fields in roll up summary 
- when saving get errors about the fields not existing 
-fixed the errors and save again
-deployed the trigger 
-set the roll up summary to active
-save
-try adding records to the parent object and keep refreshing the page to see if the field gets updated

**Comment by afawcett** [comment]
Your steps sound ok, but yes it sounds like your missing something. Can you include a screenshot of your rollup, the steps your doing exactly and where your looking to see the rollup results.

**Comment by violetyyyy** [comment]
Hi Andrew! Thanks for the follow up. I figured out what was causing it,  I was using the Pilot version, I deactivated this and recreated the same thing in the Classic version and real time worked! I think I'll continue using the Classic version for now

![image](https://cloud.githubusercontent.com/assets/14101361/13025874/5c0b99e6-d1e1-11e5-8de5-70d1da6b1f9c.png)

**Comment by afawcett** [comment]
Ok thanks, i'd still be keen to dig into your problem with custom metadata version at somepoint, the code is mostly shared between the two. Anyway for now happy rollups! :+1:
