### ISSUE TITLE
SP(), BR(), TB() not working in 2.2

### ISSUE THREAD

**Issue by jondavis9898** [afawcett/declarative-lookup-rollup-summaries#291]
After deploying 2.2 and testing the new SP(), BR() & TB() features, the tokens are not being replaced as expected. I've tested in multiple orgs and same result.

";SP()" is resolving "as Field1Value;SP()Field2Value;SP()Field3Value"

All tests are passing in my DE org both via test cases and "live rollups"

Possibly there was a packing issue with 2.2 version that didn't have the latest version of the code?

**Comment by afawcett** [comment]
Hmmmm yeah i'll look into that, pretty sure i checked your code changes made it over tbh, but this is the likely explanation.

**Comment by jondavis9898** [comment]
Thanks for taking a look!

**Comment by afawcett** [comment]
Fixed v2.3.

**Comment by jondavis9898** [comment]
Thank you! :+1:
