### ISSUE TITLE
Date/Time aggregation error

### ISSUE THREAD

**Issue by AlexVilks** [afawcett/declarative-lookup-rollup-summaries#292]
Hi Andrew,

I've met the following issue:
We are trying to calculate the latest Activity date.
 
![maxdate](https://cloud.githubusercontent.com/assets/16879258/12673033/4b7caf9a-c68b-11e5-89b7-2f930ec10477.png)
![maxdatetaskerror](https://cloud.githubusercontent.com/assets/16879258/12673037/51cc2434-c68b-11e5-93a9-c3992cbeeeae.png)

When I'm changing Aggregate Operation from Max to First, I see another one issue (Latest_Activity__c - is a Date/Time field.):
![firstdate](https://cloud.githubusercontent.com/assets/16879258/12673106/c70cc9c4-c68b-11e5-9d16-b129394cc526.png)

I would really appreciate for your assistance.

**Comment by afawcett** [comment]
- The first issue, is a Salesforce platform restriction it seems, though there appears to be a [workaround](http://salesforce.stackexchange.com/questions/15858/get-last-activitydate-for-a-group-of-accounts), this would require an enhancement. 
- The second issue, according to the [API docs for Task object](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_task.htm), the ActivityDate field is of type Date, is your Latest_Activity__c field also of type Date?

**Comment by AlexVilks** [comment]
Hi Andrew,

Thank you for your response. 
I was confused by viewing ActivityDate  type as a Date/Time on Salesforce:
![duedate](https://cloud.githubusercontent.com/assets/16879258/12717682/6dacfc7a-c8fa-11e5-9b18-0db9de85c17a.png)

But it's definitely a Date field.

**Comment by afawcett** [comment]
Ok, but what field type is your Last Activity date on the Opportunity object?

**Comment by afawcett** [comment]
Let me know if you still want help on this, i'll close this issue out for now. Thanks and good luck! :+1:
