### ISSUE TITLE
Non-selective query against large object type further clarification

### ISSUE THREAD

**Issue by Sglas1** [afawcett/declarative-lookup-rollup-summaries#293]
This is basically the same issue as "Non-selective query against large object type (more than 100000 rows) #89" but I had a follow up question and didn't know if you got notifications for comments on old closed cases. 

I got the error "Non-selective query against large object type (more than 100000 rows)" after my nightly  update of Salesforce records using Jitterbit on one custom object. In the other issue, you said you had to ask salesforce support to make the roll up criteria field "indexed." Would you have to do that for any/all fields referenced in a Lookup Rollup Summary? Or just certain types of fields? Is this only for "real-time" Calculation Mode or scheduled as well?

Thanks for this great tool!

**Comment by afawcett** [comment]
Hi, yes Closed issues, i do still get notifications on. Regarding indexed fields, it is only on the criteria fields. It applies regardless of real-time or schedule mode.
