### ISSUE TITLE
After upgrading to version 2.X, the trigger handler fails with error 'attempt to dereference null object' unless you have a unique name defined for all existing rollups (including deactivated ones)

### ISSUE THREAD

**Issue by RBLopez** [afawcett/declarative-lookup-rollup-summaries#296]
Not sure why, but it would be good to add to upgrade documentation for the 2.x versions, just in case people were being lazy like me and not creating unique names.

**Comment by afawcett** [comment]
I've just tried to reproduce this with a Custom Object based rollup not active (pre-v2.0) and a Custom Metadata based rollup active and didn't see an exception. Can you elaborate more on your setup please, have i understood it correctly?

**Comment by RBLopez** [comment]
Sure. I had this happen in two separate instances. In each, I had earlier instaled DLRS 1.x and had created rollup summary records, but I did not fill in the unique name field on these records.

Then, I installed DLRS 2.x, and recreated the rollup summary records using the new custom metadata interface. As I recreated the summary records I deactivated the old custom object ones. In both instances I experienced errors when trying to force the calculation or whenever I edited the child object with an 'attempt to dereference a null object error' coming from the dlrs namespace.

When I dug into the debug logs, I saw that the error was being thrown after a SOQL query that returned zero rows somewhere within the trigger handler class. I couldn't see anything else because the code is managed, and I didn't save the logs so unfortunately I can't send them your way.

In one instance, I deleted the old rollup summary records and this resolved the error. In the other instance I put a single character ('a', 'b', 'c', etc) in the unique name field on the old, inactive rollup summary records and the error was resolved. My assumption was that you were querying for values based on the unique Id at some point in the handler and that is what was throwing the error.

**Comment by afawcett** [comment]
Ok here's what i did to try to reproduce this...
- Created a custom object based rollup ( MyObject__c parent, Task child, Count rollup, blank developer name, not activated)
- Created a custom metadata based rollup ( MyObject__c parent, Task child, Count rollup, specified developer name, activated)
- Attempted to insert a Task
- No error and the count on the parent object was updated accordingly

I'm keen to reproduce this, maybe if you can share some screenshots? Or if possible and permitted grant me subscriber access, with steps to repo and i'll jump in and grab a stack dump.

**Comment by afawcett** [comment]
I'm still struggling to reproduce this, let me know if you have any other thoughts to help, i'm sure your correct its a bug of some kind. Meanwhile i'll close this discussion for now, we can re-open anytime. Thanks for your help. :+1:
