### ISSUE TITLE
Null Pointer exception on Delete

### ISSUE THREAD

**Issue by lionkingden** [afawcett/declarative-lookup-rollup-summaries#297]
First of all great product.. I'm using V2.2 on unlimited.
I ran into an issue when trying to delete record from a child object. I don't have any other trigger on the child custom object named Forecast_Line_Item 

here is the log
---------------------------------------

28.0 APEX_CODE,DEBUG;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WORKFLOW,INFO
15:21:19.054 (54372380)|EXECUTION_STARTED
15:21:19.054 (54412641)|CODE_UNIT_STARTED|[EXTERNAL]|TRIGGERS
15:21:19.056 (56642933)|CODE_UNIT_STARTED|[EXTERNAL]|01qF00000019Ur0|dlrs_Forecast_Line_ItemTrigger on Forecast_Line_Item trigger event BeforeDelete for [a1AF0000002E59S]
15:21:19.068 (68174284)|ENTERING_MANAGED_PKG|dlrs
15:21:19.068 (68401589)|CUMULATIVE_LIMIT_USAGE
15:21:19.068 (68401589)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 0 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

15:21:19.068 (68401589)|CUMULATIVE_LIMIT_USAGE_END

15:21:19.068 (68524624)|CODE_UNIT_FINISHED|dlrs_Forecast_Line_ItemTrigger on Forecast_Line_Item trigger event BeforeDelete for [a1AF0000002E59S]
15:21:19.253 (253853086)|CODE_UNIT_STARTED|[EXTERNAL]|01qF00000019Ur0|dlrs_Forecast_Line_ItemTrigger on Forecast_Line_Item trigger event AfterDelete for [a1AF0000002E59S]
15:21:19.254 (254127851)|ENTERING_MANAGED_PKG|dlrs
15:21:19.357 (357024125)|SOQL_EXECUTE_BEGIN|[158]|Aggregations:0|SELECT CurrencyIsoCode, Name, dlrs__Active__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
15:21:19.369 (369100556)|SOQL_EXECUTE_END|[158]|Rows:0
15:21:19.431 (431426226)|SOQL_EXECUTE_BEGIN|[270]|Aggregations:0|SELECT DeveloperName, Id, Label, dlrs__Active__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__Description__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c FROM dlrs__LookupRollupSummary2__mdt WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY DeveloperName ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
15:21:19.436 (436096318)|SOQL_EXECUTE_END|[270]|Rows:7
15:21:19.510 (510629794)|SOQL_EXECUTE_BEGIN|[186]|Aggregations:0|SELECT CurrencyIsoCode, Name, dlrs__Active__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE UniqueName__c in :uniqueNames ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
15:21:19.517 (517398015)|SOQL_EXECUTE_END|[186]|Rows:2
15:21:19.524 (524872525)|DML_BEGIN|[875]|Op:Insert|Type:dlrs__LookupRollupSummary__c|Rows:1
15:21:19.533 (533822209)|ENTERING_MANAGED_PKG|dlrs
15:21:19.613 (613038271)|ENTERING_MANAGED_PKG|dlrs
15:21:19.717 (717169803)|SOQL_EXECUTE_BEGIN|[72]|Aggregations:0|SELECT ApiVersion, Body, BodyCrc, CreatedById, CreatedDate, Id, IsValid, LastModifiedById, LastModifiedDate, LengthWithoutComments, Name, NamespacePrefix, Status, SystemModstamp, TableEnumOrId, UsageAfterDelete, UsageAfterInsert, UsageAfterUndelete, UsageAfterUpdate, UsageBeforeDelete, UsageBeforeInsert, UsageBeforeUpdate, UsageIsBulk FROM ApexTrigger WHERE Name in :names ORDER BY Name ASC NULLS FIRST 
15:21:19.730 (730294504)|SOQL_EXECUTE_END|[72]|Rows:0
15:21:19.734 (734563221)|DML_END|[875]
15:21:19.735 (735235896)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

(dlrs)

Trigger.dlrs_Forecast_Line_ItemTrigger: line 7, column 1
15:21:19.735 (735251883)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

(dlrs)

Trigger.dlrs_Forecast_Line_ItemTrigger: line 7, column 1
15:21:19.735 (735304138)|CUMULATIVE_LIMIT_USAGE
15:21:19.735 (735304138)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 0 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 2 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

15:21:19.735 (735304138)|LIMIT_USAGE_FOR_NS|dlrs|
  Number of SOQL queries: 3 out of 100
  Number of query rows: 9 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 1 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

15:21:19.735 (735304138)|CUMULATIVE_LIMIT_USAGE_END

15:21:19.735 (735409408)|CODE_UNIT_FINISHED|dlrs_Forecast_Line_ItemTrigger on Forecast_Line_Item trigger event AfterDelete for [a1AF0000002E59S]

**Comment by afawcett** [comment]
Can you share a screenshot of your rollup definition please. Thanks.

**Comment by lionkingden** [comment]
[Screenshots.zip](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/124909/Screenshots.zip)

Hi Andrew.Sure..see attached.. 4 are real-time and 3 scheduled. I had checked if there were any error logs and didn't see any.

**Comment by lionkingden** [comment]
Ok..so thought i'll just do the Developer API route. Just kept one of the 7 roll-ups in my QA. First confirmed that the rollup works  by using the calculate button, It worked. 

now when i set the calculate mode to "Developer" and called it from the code. its not working. No error either.I can see the call being made in the logs

here is my call
 System.debug(LoggingLevel.ERROR,'++++++++++ Start Callling Declarative Rollup helper ');
                    List<SObject> parents = (List<SObject>) dlrs.RollupService.rollup(fliupsertList);
 System.debug(LoggingLevel.ERROR,'++++++++++ End Callling Declarative Rollup helper ');


here is the log
---------------
++++++++++ fliUpsertMapSize 1
4:47:53.993 (993058030)|USER_DEBUG|[393]|ERROR|++++++++++ Start Callling Declarative Rollup helper 
14:47:53.995 (995614905)|ENTERING_MANAGED_PKG|dlrs
14:47:54.068 (1068229151)|SOQL_EXECUTE_BEGIN|[158]|Aggregations:0|SELECT CurrencyIsoCode, Name, dlrs__Active__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
14:47:54.077 (1077445082)|SOQL_EXECUTE_END|[158]|Rows:0
14:47:54.145 (1145293166)|SOQL_EXECUTE_BEGIN|[270]|Aggregations:0|SELECT DeveloperName, Id, Label, dlrs__Active__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__Description__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c FROM dlrs__LookupRollupSummary2__mdt WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY DeveloperName ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
14:47:54.148 (1148133779)|SOQL_EXECUTE_END|[270]|Rows:1
14:47:54.183 (1183256155)|SOQL_EXECUTE_BEGIN|[583]|Aggregations:0|SELECT Forecast_Monthly_SubCat_Line_Item__c, Sum(OneTime_Amount__c) lre0, Max(Forecast_Monthly_SubCat_Line_Item__r.CurrencyIsoCode) mastercc FROM Forecast_Line_Item__c WHERE Forecast_Monthly_SubCat_Line_Item__c in :masterIds  GROUP BY Forecast_Monthly_SubCat_Line_Item__c
14:47:54.191 (1191095513)|SOQL_EXECUTE_END|[583]|Rows:1
14:47:54.193 (1193306418)|SOQL_EXECUTE_BEGIN|[69]|Aggregations:0|select IsoCode, ConversionRate from CurrencyType 
14:47:54.195 (1195383261)|SOQL_EXECUTE_END|[69]|Rows:22
14:47:54.202 (1202848168)|USER_DEBUG|[395]|ERROR|++++++++++ End Callling Declarative Rollup helper

**Comment by afawcett** [comment]
Can you clarify which issue we are now discussing? The title states you got an exception on a delete of a child record? If thats still the core issue, can you confirm which of the rollups when active cause this and the steps to reproduce, due you just delete from the UI?

**Comment by afawcett** [comment]
Let me know if you still want to progress this and we can for sure re-open it. Thanks.
