### ISSUE TITLE
Multiplication Aggregate Function

### ISSUE THREAD

**Issue by breynolds415** [afawcett/declarative-lookup-rollup-summaries#298]
Hey Andy,

Love this tool.  I really appreciate the work you've put into it.  I have a suggestion for a new aggregate function.  It would be great if we were able to multiply values in number fields on child objects and populate the product into a field on the parent.  I haven't found a way to do this outside of APEX code, so having the ability in your tool would be amazing!  Thanks again for all you do.

Brian

**Comment by wes1278** [comment]
@breynolds415,

You should be able to use a formula field on the parent record to say the multiplication. You can also use dlrs to rollup a formula. Just be sure to add all the fields to the relationship criteria field that drive the value of the formula

**Comment by breynolds415** [comment]
@wes1278,

That is what I ended up doing as a workaround.  I created fields on the parent and rolled up the values from the children into those fields then created a formula to perform the multiplication.  Just not very scalable, but it works.  Being able to rollup values and multiply them as the aggregate function would be ideal since I would only need one job to roll them up and one field to put the product into as opposed to the 6 fields and 6 rollup jobs needed to make the workaround work.  Thanks for the comment on my post!

**Comment by breynolds415** [comment]
@wes1278 - Can you give me an example of the rollup of a formula?  That sounds interesting and would like to learn more about it!

**Comment by afawcett** [comment]
@wes1278 any thoughts on the question above?

**Comment by wes1278** [comment]
Just create a formula field on the child object that does the multiplication. Then add each field that impacts the formulas value to the dlrs tool relationship criteria field data field. Then roll that field up. Any change to the fields that impact the formula will cause the tool to recalculate.

Does that help?

**Comment by afawcett** [comment]
Great advice, @wes1278 thanks. @breynolds415 will close this issue out for now, for sure repost here if you still feel you need help and we can re-open.
