### ISSUE TITLE
New user API access

### ISSUE THREAD

**Issue by mptaylor2020** [afawcett/declarative-lookup-rollup-summaries#300]
I recently installed the app and love it. When another user tries to access the app, she gets the message "Unable to connect to the Salesforce Metadata API. A Remote Site Setting must be created in your org before you can use this tool." Does the Remote Site Setting need to be created separately for each user?

**Comment by afawcett** [comment]
No, this is likely because the user needs API access on the profile to use the Metadata API. Is there an error message displayed on the screen near the bottom?

**Comment by mptaylor2020** [comment]
Thanks Andrew. I have added the API access on the user’s profile and all is fine.

**Comment by afawcett** [comment]
Excellent! :+1:

**Comment by mptaylor2020** [comment]
Hi Andrew

I received the attached error messages when trying to remove a trigger using the Declarative Rollup Summaries package. I had just deployed the trigger and found that the rollup was not working, so thought to remove the trigger and redeploy. The errors are preventing removal of the trigger. The issue is obviously wider than just that.

All of the errors seem to involve “Invalid field targetField__c for SObject rh2__Date_Sync__c null”. I am guessing that a change elsewhere may have removed or renamed a field.

In addition to the dlrs triggers, the messages refer to RHX triggers, which are created by Rollup Helper managed package.

Can you help?

Regards
Matt Taylor

**Comment by afawcett** [comment]
Sorry @mptaylor2020 i don't see the attached error messages, can you resend them using the GitHub web ui please.

**Comment by mptaylor2020** [comment]
[Errors on rollup triggers 2016 03 28.docx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/196453/Errors.on.rollup.triggers.2016.03.28.docx)
Since emailing you, I have received input from Passage Tech - the triggers from the two apps conflict, so the solution may be to use one app only per child object.

**Comment by afawcett** [comment]
Yeah that error is most odd really since the code in either managed package should in theory be safe from compilation issues (since it cannot be modified and of course compiled during package install). I do think its worth using one or the other as i have seen issues where the two collide. In this case though i do think its some kind of Apex class compilation issue that Salesforce should look into.
