### ISSUE TITLE
destructiveChanges.xml (Line: null: Column:null) : No ApexTrigger named: dlrs_TaskTrigger found

### ISSUE THREAD

**Issue by violetyyyy** [afawcett/declarative-lookup-rollup-summaries#305]
I am getting this error when trying to remove the trigger but the trigger is there. I am stuck not being able to remove it and when I try to create a new lookup summary field it gives an error saying I need to deploy the trigger.

![image](https://cloud.githubusercontent.com/assets/14101361/13331869/74204bf8-dbcd-11e5-85b8-961f077db7f3.png)

![image](https://cloud.githubusercontent.com/assets/14101361/13331859/6c7868ae-dbcd-11e5-880c-5de11e5bafb6.png)

**Comment by aheber** [comment]
It appears your current trigger is titled dlrs__**t**askTrigger where the expected name is dlrs__**T**askTrigger. The issue might be that Salesforce considers miss-matched capitalization to be a match when checking for duplicates but not in the case of managing said class through the API that we're trying to use to manage the trigger.

@afawcett I don't have a lot of experience here, thoughts?

**Comment by violetyyyy** [comment]
Thanks, but how do I fix it? Would installing the app fix the issue?

**Comment by aheber** [comment]
@violetyyyy I'm not sure the best way to fix it. If you have a sandbox that is sufficiently refreshed you could try and rename the trigger and test class and push those updates to production via change set. From there you should have correctly cased classes and could remove them with the roll-up manager interface.

The other option is to play with [Mavens Mate](http://mavensmate.com/) or[ Force.com IDE](https://developer.salesforce.com/page/Force.com_IDE) to delete the classes, that is not much fun though.
https://help.salesforce.com/apex/HTViewSolution?id=000006188

**Comment by violetyyyy** [comment]
ok, thank you. I'll give it a try.

**Comment by aheber** [comment]
@violetyyyy First I have to warn that I'm recommend destructive changes and if you don't understand what I'm recommending or are not comfortable taking the risk then don't use these instructions. No warranty and no liability.

With that out of the way, thinking about it... the quickest option might be to use the [Force.com CLI](https://force-cli.heroku.com/)
If you install that on your system then you can perform the following steps to remove the trigger and class.
[Performed from your command line]
`force login` (should pop in your browser where you can enter your credentials)
`force export Fixcode` (that will take some time to execute)
Inside the FixCode directory you will need to remove everything EXCEPT the following files
```
classes/dlrs_taskTest.cls
classes/dlrs_taskTest.cls-meta
triggers/dlrs_taskTest.trigger
triggers/dlrs_taskTest.trigger-meta
package.xml
```
You will then need to edit the -meta files and change `Active` to `Deleted` in the `status` tag
Then exit package.xml and make it look like the following (I'm no expert at this file, someone else may have other recommendations)
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <version>34.0</version>
</Package>
```
Then back at your command prompt you'll execute
`force import -directory=FixCode`
That should fix everything, in the final output you should see Failures - 0 and Successes - 3 (or a similar number...)

As I said before, I haven't worked with the metadata API much so these instructions may not be the best way to get the job done.



Let me know if that works for you, or if you solve your problem using a different tool.

**Comment by violetyyyy** [comment]
@aheber Changing the name worked!! Such a strange issue, but just renamed the trigger and class and it worked. Thank you for the help!

**Comment by aheber** [comment]
Awesome, there is probably a bug in DLRS around this, seeing the trigger but using the implied name instead of the discovered name.

**Comment by afawcett** [comment]
It was likely due to the child object name being 'task' rather than 'Task', in the Custom Metadata version the capitalization auto adjustment isn't applied the way it is for the Custom Object version. Its possible a simple fix would have been to enter Task in the UI and hit save then try again. As per the pilot release notes here 'Aesthetic case adjustment for object field API names will not be performed, e.g. account would not change to Account' is currently missing, i'll look to get this back in somehow asap. Sorry for the confusion in the meantime.

**Comment by afawcett** [comment]
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/308
