### ISSUE TITLE
Child Trigger Deployment Error

### ISSUE THREAD

**Issue by acarlesimo** [afawcett/declarative-lookup-rollup-summaries#310]
I'm trying to use the Declarative Lookup Rollup Summaries for the first time, and when I try to deploy the Child Triggers that it requires, I'm getting this error: 

![image](https://cloud.githubusercontent.com/assets/17601973/13474797/9f91702c-e08d-11e5-970d-7946fe6b1573.png) 

Is this an error on my end?

**Comment by aheber** [comment]
Venturing a guess I'd say you don't have any records of that type in your
system. Or can't access them with that user.

**Comment by acarlesimo** [comment]
Thanks @aheber I created a record with that type and it's giving me the same errror.  And I'm a system admin so I don't believe it's a permissions issue.  Any other thoughts?

**Comment by afawcett** [comment]
I suspect its a robustness issue in the existing trigger on this object, you may have to contact that developer or use the custom test code feature of DRLS. See here for more information, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by afawcett** [comment]
Hopefully this helped explain the background to this issue and some next steps.
