### ISSUE TITLE
Roll up is not working considering relationship criteria for updation of old records.

### ISSUE THREAD

**Issue by preetidubey6** [afawcett/declarative-lookup-rollup-summaries#311]
Hi,

Roll up tool is working fine for all the lookup objects, however when i m trying to update an old record which satisfies the relationship criteria,the rollup doesn't work as expected there.

Kindly provide the solution asap.

Thanks,
Preeti

**Comment by afawcett** [comment]
You'll need to provide more details on your rollup/s, screenshots, describes of your objects (Schema Builder screen shots) etc. You may also want to consider using the Salesforce Community Chatter group, see the link in the README file for this.

**Comment by preetidubey6** [comment]
Hi Andrew,

That relationship criteria issue got resolved, however i have a requirement
where i need to roll up on same object i.e.there exist a self relationship
like on Campaign object. I want some fields to be rolled from child
Campaign to Parent Campaign.
How can this be achieved through Rollup tool?
Kindly provide the resolution asap as the deployment is pending only for
this requirement.

Thanks,
Preeti Dubey

**Comment by afawcett** [comment]
Please take a look at [http://andyinthecloud.com/2014/05/08/account-hierarchy-rollups-clicksnotcode/](Account Hierarchy Rollups #ClicksNotCode) this is based on the same requirement but over Account. This should get you started! :+1:

**Comment by preetidubey6** [comment]
Thanks a lot.
It worked.:)
