### ISSUE TITLE
Rollup fields on parent not getting calculated.

### ISSUE THREAD

**Issue by vaissingh2908** [afawcett/declarative-lookup-rollup-summaries#312]
Hey,
I was using this tool and all of sudden i started facing issue on this. The issue is that if the picklist value on the child is changed it is not rolling up the value of the currency field. Also when i explicitly change the amount value to a new value then only it works.
Can someone please assist me on this, its a little urgent as the users have started testing on UAT.

Thanks
Vaishali Singh
8879245829

**Comment by afawcett** [comment]
Try posting a screenshot of your rollup. You can also use the Chatter group, see the README file for a link to it.

**Comment by vaissingh2908** [comment]
Hi Andrew,

I was able to fix the issue as I was missing the rollup criteria field.
A suggestion to put the rollup criteria field required when the where clause field is filled.

Thanks
Vaishali Singh
Consultant | Deloitte Digital
Deloitte Consulting Pty Ltd
US Direct:+1.678.299.9681 | Mobile: +91 8879245829
vaissingh@deloitte.com| www.deloitte.com

**Comment by afawcett** [comment]
Excellent! :+1:
