### ISSUE TITLE
Cannot Create new Opportunities!

### ISSUE THREAD

**Issue by StephanieKing** [afawcett/declarative-lookup-rollup-summaries#314]
I created a rollup from Task to Opportunity. Now I cannot create any new Opportunities! This is the error:

Error:Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object: Class.dlrs.RollupService.updateMasterRollupsTrigger: line 878, column 1

And here is the excerpt from a debug log that mentions the error. 

10:03:47.650 (1093900294)|SOQL_EXECUTE_END|[72]|Rows:0
10:03:47.364 (1101839043)|DML_END|[875]
10:03:47.364 (1103371587)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 878, column 1
Class.dlrs.RollupService.handleRollups: line 770, column 1
Class.dlrs.RollupService.triggerHandler: line 300, column 1
Trigger.dlrs_OpportunityTrigger: line 7, column 1
10:03:47.364 (1103526758)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

I will have to just deactivate the trigger ASAP so that users can enter Oppties... but I would love to be able to use this tool! Is there something I can do?

**Comment by StephanieKing** [comment]
I Tried to deactivate the dlrs_OpportunityTrigger that is causing this error by deactivating it in the sandbox, but the deployment failed with this error:

System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Name, StageName, CloseDate]: [Name, StageName, CloseDate] 
Stack Trace: Class.dlrs.RollupService.testHandler: line 270, column 1 Class.dlrs_OpportunityTest.testTrigger: line 11, column 1

I tried to uninstall the package, but the uninstall failed with errors related to the same dlrs_OpportunityTrigger. So the bottom line is I cannot create Opportunities in the org, and I can't figure out how to fix it! Help!!

**Comment by afawcett** [comment]
Can you include a screenshot of your Rollup definition please?

**Comment by StephanieKing** [comment]
It seems, tentatively, that it may be fixed, but I do have a follow up question!!

First a quick clarification - in my original post I said it was a rollup from Task to Opptty, but in fact it is a rollup from Opptty to Account that caused the problem. I was confused since both my dlrs touch the Opptty object...

I seem to have "fixed" it by pushing the button to DEACTIVATE the trigger, and then reactivating it. So that's nice... 

I am suspicious that somehow this arose from how I managed to create different rollups in 2 places...  Some in the "Manage Lookup Rollup Summaries" beta tab, and some in the "Lookup Rollup Summaries" tab. It was (and is) strange because I can't see ALL my rollups in one place! I see 2 of them in the dropdown menu on the "Manage Lookup Rollup Summaries" tab, and one of them in the List View on the "Lookup Rollup Summaries" Tab. And previously (when I was having the problem) ONE of my rollups appeared in both places! Of this "duplicate" one, I deleted the one that was on the "Lookup Rollup Summaries" tab, and then re-deployed the dlrs_OpportunityRollup trigger from the one on the other tab. 

So I still have rollups in both places, but not duplicated. Do I need to try to get them all onto the same tab - perhaps by deleting them in one place and re-creating them in the other? If so, which tab do I want them all on? Or does it not matter?

Oh my, and now I checked, and all three of them appear on the "Lookup Rollup Summaries" tab, but still only 2 appear on the "Manage Lookup Rollup Summaries" tab. You must think I'm deranged, but I swear they are jumping around...

**Comment by afawcett** [comment]
Ha no, your no deranged, this is some behaviour i perhaps should have explained better. The general desire is that everyone moves to Manage Lookup Rollup Summaries (Custom Metadata based) place to define rollups, for new installs of the package this is the only tab displayed. 

If you go hunting or have upgraded you will see both tabs. I also retained the original Lookup Rollup Summaries (Custom Object based) tab as for now, as per the release notes there is a few features still to be added to make it functionally complete, hence its Pilot status. The aim in the meantime is thus actually to allow users to use both ways together, mixing if needed, so they can dip into the new way of things and migrate over in time. Take a look at my [blog post](http://andyinthecloud.com/2015/12/24/declarative-lookup-rollup-summary-tool-and-custom-metadata/) for a few more guidelines. 

So your still wondering why your seeing the same rollup definition in both places.... well... the Lookup Rollup Summaries way of describing rollups still has a link to the past that even if you use the new method requires a record to be created. These are what i call 'shadow rollup' records, if you open one you'll see a comment in the description field to this effect. They are mainly needed for now for logging when using Scheduled rollups, even if you use the new tab approach. 

I wanted to make this as transparent as possible, so decided to dynamically create these 'shadow rollup' records in code, which explains why they keep popping back up. And also why i suspect if you deleted one under the tools feet it got a bit upset earlier. In short you should be able to just ignore these. 

If your happy with the functionality of the Manage Lookup Rollup Summaries tab just focus on creating all your rollups in that one location. Hopefully this clears things up a bit, if not, we can for sure keep discussing here. I do hope to remove the need for 'shadow rollups' in the future.

**Comment by StephanieKing** [comment]
Thank you Andrew -- It is very helpful for me to understand what I am seeing with the two "Create Rollups" tabs. I am now remembering to only use the "Manage Rollups" tab, and I have not had any more issues!!
