### ISSUE TITLE
Roll Up just for few number of records

### ISSUE THREAD

**Issue by jmaldona** [afawcett/declarative-lookup-rollup-summaries#315]
Before anything this package is AMAZING... THANKS...

I just wondering if there is any way how can I control the number of times of this "roll up"... I mean, the "roll up" is applied for a finite number of records, an example would be:

If I have to my child object any number of records, this "roll up" is going to run just for the first 5 records. That I trying to do is Roll Up an Aggregate Operation as Concatenate, delimited by ;, to update a record with text, so at the end I would like to have just the information from the 5 first records on this field updated.

Is it possible, or do you have any idea how can I achieve this goal???

**Comment by afawcett** [comment]
Sorry there is no way to just limit to the first 5 top child records, though this is a good enhancement idea. I've flagged it as such. And thanks for the kind words about the tool!

**Comment by afawcett** [comment]
Added in v2.4.1.

**Comment by jmaldona** [comment]
Andy... This was wonderful... Amazing... I just finished to test it, and honestly... wooooo... THANKS...

**Comment by wes1278** [comment]
@afawcett Thanks for implementing this feature. Great use case for concatenate text rollups!
@jmaldona great feature request!

**Comment by afawcett** [comment]
@jmaldona your most welcome!
