### ISSUE TITLE
DLRS Realtime Rollup and Process Builder conflict

### ISSUE THREAD

**Issue by areiprishbasati** [afawcett/declarative-lookup-rollup-summaries#316]
Scenario:
I have created a Process Builder flow to create a record on a custom object (Invoice) when a checkbox is checked on an Opportunity Record. I have also created a DLRS rollup summary to sum all the Invoice amounts and put it in a currency field in the Opportunity. 

Issue:
When the Process Builder fires to create a custom object record, there is a conflict between DLRS trigger and the Process Builder logic. Example below:

```
RECORD CREATE: myRule_2_A1
Create one Invoice_Created__c record where:
Invoice_Created_Amount__c = {!myVariable_current.Invoice_Amount__c} (3,000)
Opportunity__c = {!myVariable_current.Id} (0061a00000E7DNlAAN)
Result
Failed to create record.
Error Occurred: INSERT --- INSERT FAILED --- ERRORS : (CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY) dlrs_Invoice_CreatedTrigger: execution of AfterInsert
```

Is there a solution to this regarding realtime rollups that I'm unaware of? I am able to do it with scheduled, but the client wants real time. Is there a way to delay realtime calculate at all? 

Thanks.
-Andrew

**Comment by afawcett** [comment]
Have you tried calling the rollup from Flow / Process Builder rather than via a Trigger? By setting the Calculation Mode to Process Builder and then using the Custom Action from Flow or Process Builder to call your rollup. There is some documentation on this if you review the Declarative Lookup Rollup Summaries – Spring’15 Release blog linked from the README.

**Comment by areiprishbasati** [comment]
Andrew,

Thanks for your quick response. Actually yes, I was on the verge of getting
our development team involved, then I figured I would try the Process
Builder setting. It did work, but as you know, deletes do not trigger a
recalc, so I had to schedule a second job to calculate overnight. Thank you
for developing and maintaining a great app, all of our consultants use it.



Andrew Reiprish

Solution Engineer

EMAIL: areiprish@basati.com

OFFICE: 407-288-8650

WEB: BASATI.COM <http://basati.com/>
[image: Facebook] <https://www.facebook.com/BasatiBuzz> [image: Twitter]
<https://twitter.com/BasatiCRM> [image: Linkedin]
<https://www.linkedin.com/company/basati?trk=tyah>

VISIT US ON THE APP EXCHANGE HERE.
<https://appexchange.salesforce.com/listingDetail?listingId=a0N30000008bMBREA2>
[image: Basati]

MARCH PARTNER SPOTLIGHT:
[image: MapAnything]

CLICK HERE
<https://appexchange.salesforce.com/listingDetail?listingId=a0N3000000586bhEAA>
TO
LEARN MORE ABOUT WHY BASATI USES MAPANYTHING AND HOW IT CAN BENEFIT YOUR
BUSINESS!

**Comment by afawcett** [comment]
Most welcome! :+1:
