### ISSUE TITLE
dlrs_ContactTrigger affecting rollup field calculations

### ISSUE THREAD

**Issue by PacificScienceCenter** [afawcett/declarative-lookup-rollup-summaries#319]
Hi,
Our consulting partner is receiving a dlrs_contactTrigger error regarding their custom contact rollup fields:

*First error: Update failed. First exception on row 0 with id 003o000000OvxdCAAR; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate
caused by: System.NoAccessException: Entity is not api accessible*

Our consultant requested that we adjust this trigger to run in a batch at a different interval of theirs (twice daily 12am and 11am) instead of (before delete, before insert, before update, after delete, after insert, after undelete, after update). It is their opinion that the trigger is making our roll up jobs unable to calculate. Am I able to adjust this?

Here [https://na17.salesforce.com/003o000000XnQBv?srPos=0&srKp=003](url) is an example of a contact record with a field that is failing to update correctly; the particular fields are "Last Gift Amount" and "Date of Last Gift". The fields are just calculating incorrectly at the moment, I've also attached a screenshot of where the fields are located on the layout.
![capture_dlrs_contacttrigger_error_3-18-16](https://cloud.githubusercontent.com/assets/16766848/13891065/32c8f0ce-ed0c-11e5-8731-197b3c044616.JPG)

Let me know if this can be adjusted or if this issue is a product of any custom installations by our consulting partner.

Thank you!
Devan Larson
Pacific Science Center

**Comment by PacificScienceCenter** [comment]
Where would I find our rollup definitions to take a screenshot?

I am still working with our consultant to retrieve the steps that created this error. Their software support specialist offered this:
_"It looks like we are seeing an error that their rollup batch is trying to access an object that is not API enabled"_ 
I did recently update DLRS to the newest version on January 20; that's the only useful piece of information I think I can offer at the moment. I'm sure it is difficult to comment on the error with such little information; is there anything that I might be able to suspend or deactivate momentarily to see if the update interval is indeed the source of the problem?

Thank you, any info to help would be great.

**Comment by afawcett** [comment]
You can find these under this tab....

<img width="277" alt="screen shot 2016-03-22 at 21 13 09" src="https://cloud.githubusercontent.com/assets/1167760/13968148/eb4c9bb4-f072-11e5-8570-062c41f33482.png">

Can you also give some detail on the steps that lead up to this error.

Thanks

**Comment by PacificScienceCenter** [comment]
I was able to alleviate the problem with our custom roll-up fields by removing the child trigger from one of the rollups, thanks for the help.

**Comment by afawcett** [comment]
No worries! :+1:

**Comment by gokubi** [comment]
Please remove Steve Anderson from Grameen Foundation from this list as he
has left the org  Thanks



*From:* Andrew Fawcett [mailto:notifications@github.com]
*Sent:* Wednesday, March 30, 2016 5:39 PM
*To:* afawcett/declarative-lookup-rollup-summaries
*Subject:* Re: [afawcett/declarative-lookup-rollup-summaries]
dlrs_ContactTrigger affecting rollup field calculations (#319)



No worries! [image: :+1:]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/319#issuecomment-203645678>
