### ISSUE TITLE
Error in deploying child trigger.

### ISSUE THREAD

**Issue by jrosenbloom613** [afawcett/declarative-lookup-rollup-summaries#320]
Hi All,

I'm getting an error in deploying a child trigger.  Here's the summary https://goo.gl/ljpYq4 and here's the error https://goo.gl/wP6cMh .  Any tips?  Thanks!!

**Comment by afawcett** [comment]
You will have to ask a developer to provide you a snippet of Apex code to customise the Apex Test the tool deploys. Triggers and/or validation rules on on the child object require some field values to be completed to insert the dummy child record needed by the Apex Test. See here https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage.

**Comment by afawcett** [comment]
Hope this helps! :+1:
