### ISSUE TITLE
It doesn't seem to be working after installation

### ISSUE THREAD

**Issue by Wyoming1234** [afawcett/declarative-lookup-rollup-summaries#324]
Hello!
First of all, thanks for this tool since it covers a gap which is critical for my organization :)
I have installed the tool in my sandbox environment and apparently everything went well. I managed to create a new rollup field and I set it up without errors. I even did the "manage child trigger" thing before activating it following your instructions. However it doesn't seem to work correctly.
This rollup field is intended to count the number of assets attached to an account. 
I am attaching a screenshot of the field configuration and another screenshot of an account showing that even though there is 1 asset (assets have been renamed as "policies" in my org) attached to an account, the rollup field is empty.
Any ideas about what I am doing wrong? 
Thanks!
![setup](https://cloud.githubusercontent.com/assets/18190938/14177243/aab8124c-f755-11e5-96ff-107cfc62ea7d.PNG)
![account](https://cloud.githubusercontent.com/assets/18190938/14177242/aab488e8-f755-11e5-95a8-e89682591565.PNG)

**Comment by afawcett** [comment]
If this is in your production environment did you remmber to deploy via the Change Set the Apex Trigger and Apex Test class associated with the child object? They start with dlrs

**Comment by Wyoming1234** [comment]
It was occurring in a sandbox environment. I have uninstalled and re-installed everything and now it works as a charm :D
I must have done something wrong the first time I did it.
Thanks for this excellent tool!

**Comment by afawcett** [comment]
Your welcome! :+1:
