### ISSUE TITLE
Account Trigger->Decimal to Integer Illegal Assignment

### ISSUE THREAD

**Issue by jsh4478** [afawcett/declarative-lookup-rollup-summaries#326]
Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterUpdate caused by: System.SObjectException: Illegal assignment from Decimal to Integer: (dlrs)

Trying to rollup the NumberOfEmployees standard field between accounts using the ParentId relationship.  Using the Managed Package version 2.3

Steps to reproduce:
Parent+Child Object: Account
Relationship Field: ParentId
Field to Aggregate: NumberOfEmployees
Aggregate Operation: Sum
Aggregate Result Field: NumberOfEmployees
Calculation Mode: Realtime
Calculation Sharing Mode: System

I'll be installing the unmanaged package to see if I can code around this, thanks!

**Comment by afawcett** [comment]
Hi @jsh4478, thanks for raising this, and thanks for taking a look, let me know if you have any questions! :+1:

**Comment by afawcett** [comment]
@jsh4478 any news on this? Otherwise i'll take a look at it myself at some point.

**Comment by jsh4478** [comment]
I had a quick fix in place which hard coded the type casting, but
unfortunately didn't have a chance to come up with something more dynamic

**Comment by afawcett** [comment]
No worries, i understand. Maybe you could share here your quick fix code fragment?

**Comment by afawcett** [comment]
I tried to reproduce this in the latest version and could not. I have included screenshots below.

<img width="1249" alt="screen shot 2017-02-19 at 11 20 18" src="https://cloud.githubusercontent.com/assets/1167760/23105519/85046d9e-f695-11e6-84b2-21e855d6d234.png">

<img width="788" alt="screen shot 2017-02-19 at 11 20 34" src="https://cloud.githubusercontent.com/assets/1167760/23105520/89d55068-f695-11e6-9a2b-1d9e6abc2057.png">

**Comment by afawcett** [comment]
Fixed v2.8.
