### ISSUE TITLE
"Recalculate" features does not work after upgrade to version 2.3

### ISSUE THREAD

**Issue by szlee-srev** [afawcett/declarative-lookup-rollup-summaries#333]
After upgrading to version 2.3, the "recalculate" feature does not seem to work anymore. Our setup is pretty simple - 

There is a field in Opportunity that calculates the number of Case with specific record type related to the Opportunity - Sum of Quote Request Case. I can see from the Opportunity there is 2 cases with Quote Request record type in the related list. However the field that I have setup for DLSR is always showing 0.

Attaching the screenshot setup, appreciate any advise? 
![quote request](https://cloud.githubusercontent.com/assets/16015342/14840310/a0e4c65a-0c65-11e6-90fd-3a25202e72d5.jpg)

**Comment by afawcett** [comment]
Hi @szlee-srev did you intent to close this issue?

**Comment by szlee-srev** [comment]
Hi @afawcett, yes it's a configuration mistake. The tool works as expected. Thanks for following up though :)

**Comment by afawcett** [comment]
Welcome!
