### ISSUE TITLE
Once a one scheduled job fails, it creates "Rollup Calculate Job" records and keeps failing until those records are deleted.

### ISSUE THREAD

**Issue by skamensky** [afawcett/declarative-lookup-rollup-summaries#334]
One morning three of the 6 daily lookup batches (all on the same object) I have scheduled, failed and stopped running until the day I applied the fix.
Only 3 jobs were showing as queued and the queue submitted date was 4 days before the fail date.  I'm not sure which jobs those queues belonged to, but from the fail date until the fix date, only 3 of the scheduled jobs were running. 

I'm using the custom metadata version (latest version) and I created the scheduled jobs with the new interface.
There were no records in the "Lookup Rollup Summary Logs," but, there were 3 records in the "Rollup Calculate Job" object. When I tried to manually run the calculate jobs for those three records, I got an error 
"Error:
A calculate job for rollup 'Last Submission Date' is already executing. If you suspect it is not already running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again."

I tried deleting those 3 records, in an attempt to delete the three queued jobs so I could re-queue all jobs, but the 3 jobs remained queued.
I then ran the calculate jobs manually. The next morning all 6 jobs ran successfully and were queued again.

Please let me know if you need additional information and how to give it to you.

**Comment by afawcett** [comment]
Nope i think you've given enough info here, for me to try a repo on this, Thank you! 👍

**Comment by skamensky** [comment]
Great! Thank you!

**Comment by afawcett** [comment]
Ok @skamensky i have been reviewing this and actually i think its working as expected. I was thinking if i could automatically delete the Rollup Summary Calculate Job record in the code, this would help. However i think this will cause some regressions. The idea is that this protection prevents concurrent running of calculate jobs, which could cause accuracy problems. So i don't really want to mess with it. Let me know if you have other thoughts on what fix / enhancement we could make on this... 👍
