### ISSUE TITLE
APEX Governor limit for process scheduled items

### ISSUE THREAD

**Issue by kushkella** [afawcett/declarative-lookup-rollup-summaries#335]
Hey -

We are trying to rollup open tasks on account, and we want to ensure that when the due date is passed, it doesn't rollup on the account. To do this, we create a process builder with an immediate and a scheduled action. The immediate action is working fine because it is nearly impossible to receive more than 2 or 3 actions at a time in the flow, but the scheduled action that executes 1 hour after the due date can receive many records. This causes us to run into APEX Governor Limits specifically more than 100 DML queries in a single process.

https://help.salesforce.com/apex/HTViewHelpDoc?id=process_limits_scheduled.htm&language=en_US

Is there a work around for this? Or should I just create another rollup and schedule it to run daily? And is there a way to use a rollup in both process builder and as a scheduled job?

**Comment by afawcett** [comment]
Yes i would recommend the scheduled job for this.
