### ISSUE TITLE
Concatenate to Long Text Area

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#336]
I am trying to create a rollup that concatenates to a long text area. I am running into some errors on the record. Is this not possible? Is there a workaround because the Text area field character limit is an issue.

Thanks,

Tami

**Comment by afawcett** [comment]
What are the errors?

**Comment by tamilust** [comment]
The error was connected to another rollup. I have it figured out, you can close the ticket.

Thanks!


Tami Lust
Abel Cine NY
609 Greenwich Street, 4th - 5th Floors New York, NY 10014
888.223.1599 | 212.462.0175 |
tlust@abelcine.com<mailto:tlust@abelcine.com> | www.abelcine.com<http://www.abelcine.com/>
New York • Chicago • Los Angeles

On May 12, 2016, at 11:02 PM, Andrew Fawcett <notifications@github.com<mailto:notifications@github.com>> wrote:


What are the errors?
