### ISSUE TITLE
Event/event

### ISSUE THREAD

**Issue by henrisaslawsky** [afawcett/declarative-lookup-rollup-summaries#337]
Hi 

I have created a rule on the Event table. When I try to set the rule as active, I get an error message. 
So I rename the trigger from "dlrs_eventTrigger" to "dlrs_EventTrigger", and it works after. It seems that there is something on object name

Regards

**Comment by afawcett** [comment]
Thanks for logging! 👍

**Comment by afawcett** [comment]
I could not reproduce this with the latest build.

<img width="1249" alt="screen shot 2017-02-19 at 11 20 18" src="https://cloud.githubusercontent.com/assets/1167760/23105630/0073ab4c-f697-11e6-84f1-9d7c58207bf4.png">

<img width="788" alt="screen shot 2017-02-19 at 11 20 34" src="https://cloud.githubusercontent.com/assets/1167760/23105633/04eb4cca-f697-11e6-804b-e2fbae0cf73d.png">
