### ISSUE TITLE
Criteria based on formulas not working as expected

### ISSUE THREAD

**Issue by SebasCanseco** [afawcett/declarative-lookup-rollup-summaries#339]
We have 2 Account Recordtypes (Organizational and Household) the same goes for Contacts.
We have a custom obj called Preference which has a lookup to Account and another to Contact.

For Household Accounts we need certain field to rollup from Household Contact which first rolls up from Preference.
For Organizational Accounts we need the same field to be rolled up directly from Preference not from Organizational Contact.

Everything works fine until I add a Preference to Organizational Contact which in turn WIPES out the field in Organizational Account.

This doesn't make sense. Any clues?

NOTE: All rollups criteria include a formula field.
1- In the case of Rollup to Household Account we use a formula in Contact named Account_RecordType_Name__c (since we can't use related object's field yet) 
2- In the case of Rollup to Organizational Account we use a formula in Preference object Account_RecordType_Name__c.
3- In the case of Rollup to Household Contact we use a formula in Preference object Contact_RecordType_Name__c.

**Comment by afawcett** [comment]
@SebasCanseco i think this has now been delt with in the Chatter group. Let me know if not and we can for sure re-open. 👍

**Comment by SebasCanseco** [comment]
Indeed. Thanks!
