### ISSUE TITLE
Real Time Rollup not working

### ISSUE THREAD

**Issue by JLC999** [afawcett/declarative-lookup-rollup-summaries#342]
A count type rollup is only working when I manually calculate the rollup despite it being set to real-time and the trigger being deployed.  Other triggers are working fine.  I'm using the Id as the field to aggregate and I've tried it with and without filters.  The Log showed this error at some point: 'Required fields are missing: [Name] : CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY ()'

**Comment by afawcett** [comment]
What actions do you want to trigger the recalculation of the rollup? Adding and deleting child rows should work, editing wise, you may need to provide some more fields for the tool to "watch", typically if you've used some rollup criteria.

**Comment by afawcett** [comment]
@JLC999 let me know if your still struggling, we can for sure re-open this issue no worries.

**Comment by Sglas1** [comment]
can you clarify how to provide those extra "watch" fields so it triggers on edits? I have some rollups that show current month info and they didn't update this morning for the new month even though all records were modified via a jitterbit sync this morning.
