### ISSUE TITLE
Error deploying trigger into Financial Force SCM

### ISSUE THREAD

**Issue by markcharleton** [afawcett/declarative-lookup-rollup-summaries#343]
I have successfully deployed the trigger onto Tasks, however I would also like to rollup information from both Customer Quotations and Service Contracts in Financial Force SCM. When deploying the trigger I receive the following error. through the GUI a default currency isnt required so I am a little confused. 

Also does the Where clause support LIKE / OR as I receive an error. A standard = / AND works ok

Error:
dlrs_SCMC_Customer_QuotationTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Customer Quotations require a default currency. Please contact your Administrator.: [] Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_SCMC_Customer_QuotationTest.testTrigger: line 11, column 1

**Comment by afawcett** [comment]
Have a read through this https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. 

Basically the tool does what it does by generating code, that code needs a generated test to deploy. That generated test is pretty dumb. If your child object has some requirements to insert a record in the test the test will fail. 

The wiki page describes this in more detail and the use of a feature to provide a snippet of code (specific to your child object) that can help you teach the tool the necessary steps to insert the record and make the test pass. 

Depending on the complexity of the child object trigger or validation rules and dependent records that may also be needed this can be tricky. 

You might be able to get away with it, by using the See All Data option, as this will let the objects validation see other dependent records. Note that this can be fragile in the future if the org data changes in a way that changes the outcome of the test.

**Comment by afawcett** [comment]
@markcharleton Let me know if you still need some help with this beyond the Wiki page i gave.
