### ISSUE TITLE
Merging lead causes Permission to create dlrs__LookupRollupSummary__c error

### ISSUE THREAD

**Issue by chenchenick** [afawcett/declarative-lookup-rollup-summaries#345]
Hi there,
I create 2 LookupRollupSummaries to count lead's activity and get lead's next activity.
They all works well. But my users met this error when they merging leads.

`Apex trigger dlrs_LeadTrigger caused an unexpected exception, contact your administrator: dlrs_LeadTrigger: execution of AfterDelete caused by: System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs.RollupSummariesTrigger: execution of AfterInsert caused by: dlrs.fflib_SObjectDomain.DomainException: Permission to **create** an dlrs__LookupRollupSummary__c denied. Class.dlrs.fflib_SObjectDomain.handleAfterInsert: line 174, column 1 Class.dlrs.fflib_SObjectDomain: line 316, column 1 Class.dlrs.fflib_SObjectDomain.triggerHandler: line 271, column 1 Trigger.dlrs.RollupSummariesTrigger: line 30, column 1: []: Class.dlrs.RollupService.updateMasterRollupsTrigger: line 935, column 1`

Granting them the default permission set Lookup Rollup Summaries - Process Rollups did not help.
So I cloned it and add create permission to dlrs__LookupRollupSummary__c, and it worked. 

My question is, is this correct way to make it work? Why merging needs extra permission?

Thank you!

**Comment by afawcett** [comment]
This is for sure not supposed to be the way it works. Thanks for raising, i will investigate.

**Comment by chenchenick** [comment]
Thanks for the response, I also add screenshot of my customizations here just in case.

![20160621132459](https://cloud.githubusercontent.com/assets/8031565/16245031/c36386e8-37b3-11e6-81dd-0e6b29d66ea6.png)
![20160621132422](https://cloud.githubusercontent.com/assets/8031565/16245032/c3686e60-37b3-11e6-8952-f0becc3ea68d.png)

 here.

**Comment by afawcett** [comment]
Ok its just occurred to me what might be causing this. Do you have any using Calculation Mode Scheduled?

**Comment by chenchenick** [comment]
No, we are not using that.

**Comment by afawcett** [comment]
Fixed in v2.5.
