### ISSUE TITLE
Count Attachements

### ISSUE THREAD

**Issue by AdvanceForce** [afawcett/declarative-lookup-rollup-summaries#346]
Good day. Firstly, thank you for this amazing tool!! It has saved me a lot of time on numerous occasions!! I've created a DLRS on a custom object to count attachments. But it seems to only start 'counting' existing attachments when I add a new attachment. Any idea what i should do to get the calc to work on all my existing records? Much obliged!

**Comment by aheber** [comment]
@AdvanceForce Have you run the "calculate" function on the job? That will go through your existing records and evaluate the number of attachments.

**Comment by AdvanceForce** [comment]
Thank you for your feedback! I have, but just realized that i was being too impatient. It is still busy calculating / processing all my records. #blush

**Comment by afawcett** [comment]
No worries @AdvanceForce, let us know if your good to close this out when its done or not.

**Comment by AdvanceForce** [comment]
All my records eventually processed and it is working well, as allways. Thank you very much!

**Comment by afawcett** [comment]
👍
