### ISSUE TITLE
DLRS v2.1 - v2.3 - Lookup Rollup Calculate Jobs not Case-sensitive

### ISSUE THREAD

**Issue by JenNelsonChicago** [afawcett/declarative-lookup-rollup-summaries#347]
Hi, there - 

I have noticed in v2.1 - v.2.3 (one version is installed in one Sandbox, the other in a second Sandbox...I have not been ignoring the issue for two versions ;-)) that, from time to time, I will attempt to run a real-time Calculate on a DLRS record and get a trigger error indicating that a Lookup Rollup Calculate Job is already running for the record...upon further investigation, the Lookup Rollup Calculate Job is actually running on a different DLRS record with the same Record Id but different letter-case in the Record Id:
- a9U290000004GNy versus
- a9U290000004GNY

and
- a9U290000004GNx versus
- a9U290000004GNX

**Comment by afawcett** [comment]
Thanks @JenNelsonChicago, this very much sounds like a case sensitivity bug to me. I'll investigate, good spot btw! 👍

**Comment by JenNelsonChicago** [comment]
Awesome - thanks, Andy, as always, for the quick response! :-)

**Comment by afawcett** [comment]
Note to self, using 18 character ID's as the field value should resolve this as i cannot change the case insensitive status of a packaged field.

**Comment by afawcett** [comment]
Fixed in v2.6. Thanks @wes1278  for the fix!

**Comment by JenNelsonChicago** [comment]
Thanks @wes1278 and @afawcett !  This is awesome! :-)

**Comment by wes1278** [comment]
:)
