### ISSUE TITLE
Deploying Child Trigger fails when required field exists - test class not correct

### ISSUE THREAD

**Issue by nrawlins** [afawcett/declarative-lookup-rollup-summaries#348]
Error received when deploying child trigger, if a required field such as Master Detail relationship exists then the test class does not take this into account and therefore does not deploy:

dlrs_pse_Timecard_HeaderTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Timecard Header must specify a Project.: [pse__Project__c] Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_pse_Timecard_HeaderTest.testTrigger: line 11, column 1

**Comment by afawcett** [comment]
This is a known challenge, have a look at [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage), you will need to determine an appropriate fragment of code to add include in the test via the Test Code field on the rollup. Using the See All Data option can also help.

**Comment by nrawlins** [comment]
Thanks! Perfect, I will have a look. Great to know its a known issue

**Comment by nrawlins** [comment]
Thanks, I have written some code in the Test Code field and it has resolved the issue. I will either do the same in prod or just deploy using change set. Thanks again!

**Comment by afawcett** [comment]
Excellent @nrawlins, would you mind sharing your fragment here for future users? 

BTW, are you using the Manage Rollups tab, the one thats backed by Custom Metadata? If so you can totally deploy your rollups, triggers and test classes all together with Change Sets and then your done! 👍

**Comment by nrawlins** [comment]
Here is the solution I used for populating required fields (also I checked the See All Data option) - 

Ideally the testHandler would create these records so the solution could be deployed to another instance without issues, but my use case is small and happy with managing this in the future if required.

dlrs.RollupService.testHandler( 
new pse__Timecard_Header__c(pse__Project__c = 'a1V58000000UmsT', pse__Resource__c = '00358000001pNAP',pse__Start_Date__c = Date.newInstance(2016, 6 , 20), pse__End_Date__c = Date.newInstance(2016, 6 , 26), pse__Assignment__c = 'a0g3E0000008vII'));

Thanks @afawcett I will look into that as I am not using that tab but an excellent point! I will look into it.
