### ISSUE TITLE
Support ContentNote rollups

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#351]
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentnote.htm

**Comment by afawcett** [comment]
Upgraded the package to API 37 so it would see this object. Although it cannot use Realtime (not trigger support), it can now be used with schedule mode.

**Comment by afawcett** [comment]
Fixed in v2.5.

**Comment by kryan0618** [comment]
Hi Andy,
How do I create the DLRS for ContentNotes? Which object do I use to count the number of enhanced notes on an object and which field do I use for the Relationship Field?
Thanks!!
Kris

**Comment by afawcett** [comment]
@kryan0618 i am not sure on that object, its best to ask in the Community Chatter group, see the README file for a link to that. 👍

**Comment by kryan0618** [comment]
Hi Andy,
I found the information on how to count the Enhanced Notes on an object.
1. Child Object: ContentDocumentLink
2. Relationship field: LinkedEntityId
Thanks!
Kris

**Comment by afawcett** [comment]
Whoop, nice one! Thanks for sharing back here. 👍
