### ISSUE TITLE
Relationship Criteria (Where) - OR 

### ISSUE THREAD

**Issue by markcharleton** [afawcett/declarative-lookup-rollup-summaries#352]
Hi

Does the where clause support anything other than AND, I have tried using OR and recieve an error. 'unexpected token: OR'. I think I might also need <>

New release is working well, and I am using the Test code successfully.

Mark

**Comment by afawcett** [comment]
Good to know the release is working well! Thanks @markcharleton for sharing.

Yes you can use other operators, see the [SOQL WHERE](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm) docs.
