### ISSUE TITLE
Better messaging when scheduling jobs (was: How to cancel a scheduled calculate job)

### ISSUE THREAD

**Issue by npalatt** [afawcett/declarative-lookup-rollup-summaries#353]
I don't recall ever creating scheduled recalculations of my rollups using the 'Schedule Calculate' button, but a significant amount of records continue to update nightly at 2am with my user listed as the one making the modification(s). How can I delete any existing scheduled calculate jobs?

**Comment by afawcett** [comment]
Yes these can be viewed under the Setup menu, search for Scheduled

**Comment by neonb** [comment]
This should be documented a bit better than it is now. I figured that the jobs would be visible somewhere in Setup ->Jobs, but couldn't really decipher the list until I realized that the names included DLRS record ids. Just adding a couple words to the Schedule Calculate view along the lines of "The Calculate job can be managed at Setup -> Jobs -> Scheduled Jobs; its name will be rollup_XXXXXXXXXXXXXXX."

**Comment by afawcett** [comment]
Yeah sorry about that @neonb , another poster raised [this enhancement request](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/415) which once implemented i think will do the trick. Thanks for your feedback! 👍

**Comment by afawcett** [comment]
Re-opened this as it also relates to having some inline help on where to find the scheduled job.

**Comment by afawcett** [comment]
Fixed v2.8.
