### ISSUE TITLE
Cannot Insert Opportunity (via a custom Clone process) 

### ISSUE THREAD

**Issue by mubeen-qawi** [afawcett/declarative-lookup-rollup-summaries#354]
Hi Andy, getting the following error when users are trying to Clone an Opportunity (basically its an insert process). 
![image](https://cloud.githubusercontent.com/assets/6967840/16783733/1f62ec68-483a-11e6-91b2-a57798f87356.png)

Background: we have about 20 different RollUp Summary (Custom MetaData) records created for 20 different Roll up summary fields on Account where Account (Object) is parent while Opportunity (object) is Child. Today, I changed the Rollup Summary setting from RealTime to Schedule and have created Schedule Jobs to run nightly at 2 AM.

Since making the changes, folks have been reporting this issue. Is this is permission related issue?

**Comment by mubeen-qawi** [comment]
here is the screenshot of the one of the RollUp Summary rules: Hope this helps.
![image](https://cloud.githubusercontent.com/assets/6967840/16784027/ac5f1fe6-483b-11e6-94d1-fb2f98f18cbf.png)

**Comment by mubeen-qawi** [comment]
And here's the debug log: 
[RollupSummary_Attempt2DeferenceNullobject.txt](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/360303/RollupSummary_Attempt2DeferenceNullobject.txt)

**Comment by afawcett** [comment]
Ok this is most useful! I am sure there is some kind of issue in this area of the code and i'm keen to find it. This looks like you have got closer to a repo of it. I'll be taking a closer look at this issue as priority next window of work i get to focus on the tool.

**Comment by mubeen-qawi** [comment]
Hi Andy, thanks for getting back. I was pulled in another project, so couldn't get back to you here or on Twitter.

This issue is resolve now, i changed the setting for Calculation Mode back to 'Realtime' instead of scheduled and the issue is resolved like magic.

Currently, we are leveraging both the Realtime updates as well as scheduled job (which runs nightly). So the tool is working as expected. Will let know you if I see any related issues.
