### ISSUE TITLE
Error Deploying Apex Trigger for Campaign Member

### ISSUE THREAD

**Issue by StephanieKing** [afawcett/declarative-lookup-rollup-summaries#356]
Any ideas what to do with this Failed Trigger Deployment? I've tried it a few times with no luck...

dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: MALFORMED_ID, Invalid campaign id: null: [CampaignId] Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_CampaignMemberTest.testTrigger: line 11, column 1

Warning:
dlrs_CampaignMemberTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

**Comment by aheber** [comment]
@StephanieKing I just ran into this exact same problem. You'll need to deploy a custom test method to make this work. In the Advanced section of edit page, you'll find the Test Code field. Put this into that box and try to redeploy.
```
        Campaign camp = new Campaign(Name = 'Test Campaign');
        Insert camp;
        Contact c = new Contact(LastName = 'Test');
        Insert c;
       
        dlrs.RollupService.testHandler(new CampaignMember(CampaignId = camp.Id, ContactId = c.Id));
```

**Comment by afawcett** [comment]
Yep thanks @aheber thats trick! 👍

**Comment by StephanieKing** [comment]
Wonderful, thank you so much! @aheber !

**Comment by StephanieKing** [comment]
Thank you!

**Comment by gurudave08** [comment]
Great tip, thanks @aheber! I'm running into the same issue. But I do not see a "Test Code" text box in the Advanced section. Just a checkbox that says "Test Code See All Data".  Do I need to update to a new version?

**Comment by afawcett** [comment]
Check your on the latest version yes, if you are and your using the Custom Object based rollups (e.g. not the Manage Rollup Summaries which uses Custom Metadata) then ensure its on the layout (as these don't upgrade).

**Comment by gurudave08** [comment]
Thank you @afawcett.  Sorry for the newb question but how do I go about updating the app?

**Comment by afawcett** [comment]
No worries, just repeat the process you followed to install the package (see links in the README) you did before and the system automatically detects its an upgrade. Depending on the version your going from you may need to add some fields to layouts (these are not upgraded, see readme versions section and notes for each), though if your using the Manage Rollups page this does not apply.

**Comment by gurudave08** [comment]
got it. works perfectly now.  Thanks Andy, you rock!

**Comment by creuman** [comment]
Thank you @aheber for the test code!

**Comment by matytsio** [comment]
I have the same problem but we use Person Accounts. I get the following error:

> Error: dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Please do not create Contact records. Use Person Accounts instead.: [] Class.dlrs_CampaignMemberTest.testTrigger: line 13, column 1

How would this code need to change?
Thank you!

**Comment by chazzvader** [comment]
Thank you!

**Comment by StephanieKing** [comment]
@afawcett well here I am again... this is my post from 2016, and apparently I was able to fix this issue with the code above, but this time I don't understand at all where I am supposed to paste the code? What is the Advanced section of the Edit page?? Hoo boy....
I am using the latest version, and I am using the "manage rollups" page...

**Comment by rogeramitchell** [comment]
@StephanieKing if you are on the Manage Lookup Rollup Summaries tab, there is an Advanced section at the bottom with a Test Code box. Paste the code there and click Save.

**Comment by StephanieKing** [comment]
@rogeramitchell oh gee, there it is. Much appreciated, sir!!
