### ISSUE TITLE
Apex error occurred: System.LimitException: Apex CPU time limit exceeded

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#357]
Hi,
I'm trying to create new contacts using DemandTools, and I received the following error:
Message: dlrs_ContactTrigger: System.LimitException: Apex CPU time limit exceeded Status code: 18

I'm not really sure where to go from here.  The ContactTrigger should actually not be in use (all my rollups using the trigger are deactivated), but I also tried removing the trigger and doing the upload, and I still got the error.  Maybe I've just tried too many times now?

I tried setting up a debug log for the dlrs_ContactTrigger and then ran DemandTools again, but I'm not seeing a log yet.

I've never had this problem before creating contacts in batch.  The only change has been that I installed the new 32-bit version of DemandTools.  So, not sure if that has any influence.

This seems similar to Issue #355 and #338.

**Comment by JodiNA** [comment]
I was able to get debug logs on me as a user that caught the limit.  But, I'm still not sure what to do or how to interpret this information!

Any help is appreciated!!

**Comment by afawcett** [comment]
I suspect DLRS trigger is just the victium of it going pop, rather than the cause. Lots of Flow code eats up ironically Apex CPU resource. Its a bit hit and miss when this governor is checked, its possible it could be when it enters the first bit of Apex code. I have never see the 'Status code:18' bit, that is interesting, can you raise a case and ask Salesforce to elaborate on that?

**Comment by JodiNA** [comment]
Thanks @afawcett for your suggestions.  I have an idea of what process (flow) might be causing the problem.  How annoying!  I'll try deactivating that and see what happens.  I can also open a ticket with SF about that status code, as you suggested.

Any idea why it would be running through the apex trigger if it's not even in use, though?

Jodi

**Comment by JodiNA** [comment]
@afawcett - you were right; it is a flow (well, a Process, which is even more frustrating because there's only so much I can do to reduce the number of queries... at least as far as I know).

I didn't get an answer from SF about the status code. :-/

**Comment by afawcett** [comment]
Ok thanks for the follow up, i hope you find a way to optimise your flow soon! 👍
