### ISSUE TITLE
Should not need to mark Active to do a manual Calculation

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#359]
If you have a rollup set to Calculate Mode: Scheduled you cannot use the Calculate button to test and calculate immediately unless the Active checkbox is set to True which forces you to deploy Triggers.

However I have tested you can deploy the Triggers, Activated the Rollup, then delete/remove the Triggers and do a manual Calculate and it works correctly. 

I believe the fix is to change the error/warning to not block doing a manual Calculate if Active is not True.

**Comment by JimBTek** [comment]
I believe changing line 101 of RollupService.cls to:

`if((lookup.Active==null || lookup.Active==false) && lookup.CalculationMode=='Realtime' )`

could work, and am working on testing

**Comment by afawcett** [comment]
Oooh thanks @JimBTek , look forward to hearing more for this! 👍

**Comment by JimBTek** [comment]
OK so along with the Above code if I change in RollupServiceTest3.cls
 274 - 'rollupSummary.CalculationMode__c = 'Realtime';'

Then the tests pass and it does indeed work properly on a scheduled mode Rollup.   I am guessing I could be breaking something else?  

@afawcett is there anything else I should check before submitting a pull request?  I plan on testing a Realtime rollup and make sure it works and i did not break it.

**Comment by afawcett** [comment]
This looks ok, so i guess what we are saying here is if its realtime, it has to be active, since if you run the job and then don't activate for a few hours things will be out of sync. However if your in scheduled or other modes your already accepting that lag. So yes, i think your code change makes technical and logical sense... 👍

**Comment by JimBTek** [comment]
yeah, or the other route is to set it to active without requiring the
triggers being deployed if it's not realtime, so you can track which ones
are Active vs. not active, but I think if you are calling a rollup from
Process or a Schedule that is where you would activate or deactivate vs. on
the rollup itself.

I'll send a pull request

Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by JimBTek** [comment]
https://github.com/afawcett/declarative-lookup-rollup-summaries/pull/369

**Comment by afawcett** [comment]
Fixed in v2.5.
