### ISSUE TITLE
NPSP 3 Contact Merge error related to DLRS

### ISSUE THREAD

**Issue by jotremba** [afawcett/declarative-lookup-rollup-summaries#361]
I get the following error when I try to merge contacts in Salesforce with NPSP 3 w/Household Account Model.  It's way over my head, so I'm not sure what to do...

Error Type: System.DmlException
Error Date: 2016-07-27 20:35:33
Message: "Merge failed. First exception on row 0 with id 001i000001SIlATAA1; first error: DELETE_FAILED, dlrs_AccountTrigger: execution of AfterDelete

caused by: System.NullPointerException: Attempt to de-reference a null object

(dlrs)

: []"

Stack Trace:
 Stacktrace available at the time of saving the record - (npsp)

**Comment by afawcett** [comment]
Yeah the stack trace has been hidden by Salesforce here, which doesn't help much. One thing to try though is to ensure your on the latest version and check our the new [Merge support](https://andyinthecloud.com/2016/06/19/declarative-rollup-tool-summer-release/). If you have upgraded you should use the Manage CHild Trigger button to Remove then Deploy (effectively re-deploy) as per the blog. Though i have to say not having done this, i would not expect an exception, so not sure this will solve it. If it does not, we can either try to recreate this in another NPSP 3 org (maybe one created via developer.salesforce.com) or if possible grant access for me to the org via the support page under setup (I'll also need the org Id) and give me steps to repo. In this mode i will get the full stack trace and this might help uncover whats going on.

**Comment by jotremba** [comment]
Thanks for your quick response.  I am on the most recent version, but just
in case I completed the steps in Merge Support by removing and re-deploying
the "Manage Child Trigger" code, ensuring that the box was checked.  I will
keep an eye on it to see if I have any more trouble.  Once strange thing is
that I was able to complete the original merge where I got the error when I
used Cloudingo, but I couldn't complete it in SF w/NPSP.  I will circle
back if it happens again.  Thanks!

Jennifer Otremba
Salesforce Administrator for Organizational Performance Management
------------------------------
Breakthrough Twin Cities
2051 Larpenteur Avenue East
Saint Paul, Minnesota 55109
651-748-5548
www.breakthroughtwincities.org


Breakthrough Twin Cities prepares under-resourced students for college
success and cultivates the next generation of educators.

**Comment by jotremba** [comment]
Ok, bummer.  I created a test record to merge and it's still a problem.  Here is the exact text of the error that pops up on the screen:

Error: Merge failed. First exception on row 0 with id 0013100001jx0XBAAY; first error: DELETE_FAILED, dlrs_AccountTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []

Error: Failed to merge the contacts. Error: System.DmlException: Merge failed. First exception on row 0 with id 0013100001jx0XBAAY; first error: DELETE_FAILED, dlrs_AccountTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []

Let me know if this provides additional insight, otherwise I can provide support access to you and let you know how to recreate.  Thanks!

Jennifer

**Comment by afawcett** [comment]
Yeah that would be useful as i need to see the stack trace tbh. I'll need to know the org Id once you've enabled. Thanks

**Comment by jotremba** [comment]
Thanks for your help, and sorry for the delay getting back to you.  I set up access for the next 3 days.  Our Org ID is 00Di0000000ZpNy.  I created two accounts called "Test Merge" that you can use to replicate the error.  I navigated to the Nonprofit Starter Pack App, selected the "Contact Merge" tab, searched for "Test Merge" and hit Merge.  The errors popped up at that point.  I was able to successfully merge records this evening using Cloudingo, but none will merge using the NPSP Contact Merger functionality.  I appreciate any insight you have.  Thanks!

Here were the errors:

Error: Merge failed. First exception on row 0 with id 0013100001kPY6oAAG; first error: DELETE_FAILED, dlrs_AccountTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []

Error: Failed to merge the contacts. Error: System.DmlException: Merge failed. First exception on row 0 with id 0013100001kPY6oAAG; first error: DELETE_FAILED, dlrs_AccountTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []

**Comment by afawcett** [comment]
I didn't get a chance to look into this by the time the support access expired. However i suspect the issue might be fixed in one of the other fixes i am making to the v2.5 release. Try this release and let me know.

**Comment by jotremba** [comment]
Thanks for your response, Andrew.  I just upgraded to the new version and I
successfully merged an account that wouldn't merge a few minutes ago before
I upgraded, so it looks like it's fixed!  Thanks for your work on this.
DLRS is my new favorite App Exchange app :)

Jennifer Otremba
Salesforce Administrator for Organizational Performance Management
------------------------------
Breakthrough Twin Cities
2051 Larpenteur Avenue East
Saint Paul, Minnesota 55109
651-748-5548
www.breakthroughtwincities.org


Breakthrough Twin Cities prepares under-resourced students for college
success and cultivates the next generation of educators.

**Comment by afawcett** [comment]
Excellent and thank you! 👍

**Comment by jotremba** [comment]
Hi Andrew,

Since the NPSP upgrade recently that exposes more errors, I have been
getting this nightly.  It looks like it's related to DLRS but is way over
my head.  Any ideas?

Jennifer Otremba

Organization: Breakthrough Twin Cities(00Di0000000ZpNyEAK)
User: 033i0000000gi57aac@00di0000000zpnyeak(005i0000005QzWcAAK)

Errors:

----------
 Error #1:

Error Type: Batch Apex error
Error Date: 2016-11-05 04:01:45
Message: "First error: Update failed. First exception on row 0 with id
0013100001molTAAAY; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY,
dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.NoAccessException: Entity is not api accessible

Class...."
Context: npsp__RLLP_OppAccRollup_BATCH

Stack Trace:
 null

*Jennifer Otremba | Salesforce Consultant*

----------------------------------

Breakthrough Twin Cities

2051 Larpenteur Avenue East

St. Paul, Minnesota 55109



651-748-5548

www.breakthroughtwincities.org



*Breakthrough Twin Cities prepares under-resourced students for college
success and cultivates the next generation of educators. Support us in our
mission to close the achievement gap. Donate
<https://donate.breakthroughtwincities.org/checkout/donation?eid=70700>.*

**Comment by afawcett** [comment]
Hmmm this could be related to another issue i have just looked at. What edition is the org on btw?

**Comment by afawcett** [comment]
Actually @jotremba would you mind opening a new issue on this please, this looks unrelated to the original topic of this issue. Thanks! 👍

**Comment by jotremba** [comment]
Thanks for following up, Andrew!  I was able to resolve the issue by
following the instructions for NPSP Scheduled Jobs that Judi Sohn posted on
the Power of Us Hub recently.  Sorry I forgot to follow up!

Jennifer

*Jennifer Otremba | Salesforce Consultant*

----------------------------------------------

Breakthrough Twin Cities

2051 Larpenteur Avenue East

St. Paul, Minnesota 55109



(651) 748-5548

www.breakthroughtwincities.org



*Breakthrough Twin Cities prepares under-resourced students for college
success and cultivates the next generation of educators. Support us in our
mission to close the achievement gap. Donate
<https://www.breakthroughtwincities.org/partner/give/>.*
