### ISSUE TITLE
23 test classes failure while deploying code through https://githubsfdeploy.herokuapp.com/

### ISSUE THREAD

**Issue by dishavdatta** [afawcett/declarative-lookup-rollup-summaries#362]
I have deployed this tool in my Dev org as well as in Sandbox. It was working fine but now when I try deploy it to Production test classes are failing.

**Can you please help me out here.**

fflib_QueryFactoryTest	addChildQueries_invalidChildRelationship	System.AssertException: Assertion Failed: Same value: null 
Stack Trace: Class.fflib_QueryFactoryTest.addChildQueries_invalidChildRelationship: line 349, column 1
RollupControllerTest	testDeployedStatus	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupControllerTest.testDeployedStatus: line 62, column 1
RollupScheduledCalculateControllerTest	testCronHelperCustomised	System.AssertException: Assertion Failed: Expected: 0 0 4 2 * ?, Actual: 0 0 1 * * ? 
Stack Trace: Class.RollupScheduledCalculateControllerTest.testCronHelperCustomised: line 123, column 1
RollupScheduledCalculateControllerTest	testCronHelperDefault	System.AssertException: Assertion Failed: Expected: 0 0 2 * * ?, Actual: 0 0 1 * * ? 
Stack Trace: Class.RollupScheduledCalculateControllerTest.testCronHelperDefault: line 57, column 1
RollupScheduledCalculateControllerTest	testCronHelperError	System.AssertException: Assertion Failed: Expected: 0, Actual: 10 
Stack Trace: Class.RollupScheduledCalculateControllerTest.testCronHelperError: line 88, column 1
RollupServiceTest	testCountById	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testCountById: line 385, column 1
RollupServiceTest	testCountByType	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testCountByType: line 327, column 1
RollupServiceTest	testLimitsConsumedWithConditions	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testLimitsConsumedWithConditions: line 819, column 1
RollupServiceTest	testLimitsConsumedWithoutConditions	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testLimitsConsumedWithoutConditions: line 930, column 1
RollupServiceTest	testMultiRollup	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testMultiRollup: line 124, column 1
RollupServiceTest	testMultiRollupNoConditions	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testMultiRollupNoConditions: line 270, column 1
RollupServiceTest	testMultiRollupSumAndAvg	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testMultiRollupSumAndAvg: line 197, column 1
RollupServiceTest	testMultiRollupWithTwoParents	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest.testMultiRollupWithTwoParents: line 478, column 1
RollupServiceTest	testMultiRollupWithTwoParentsTenChunks	System.QueryException: No such column 'NumberOfLocations__c' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. 
Stack Trace: Class.RollupServiceTest.testMultiRollupWithTwoParentsTenChunks: line 598, column 1
RollupServiceTest2	testChangeInCriteriaReferencedField	System.QueryException: No such column 'NumberOfLocations__c' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. 
Stack Trace: Class.RollupServiceTest2.testChangeInCriteriaReferencedField: line 500, column 1
RollupServiceTest2	testChangeInRelationship	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest2.testChangeInRelationship: line 541, column 1
RollupServiceTest2	testMultiRollupBothScheduledWithConditions	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest2.testMultiRollupBothScheduledWithConditions: line 89, column 1
RollupServiceTest2	testMultiRollupOneScheduled	System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest2.testMultiRollupOneScheduled: line 173, column 1
RollupServiceTest2	testUnDeleteRealtime	System.QueryException: No such column 'NumberOfLocations__c' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. 
Stack Trace: Class.RollupServiceTest2.testUnDeleteRealtime: line 626, column 1
RollupServiceTest3	testDateRollupDeleteChild	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest3.testDateRollupDeleteChild: line 483, column 1
RollupServiceTest3	testDateRollupInsertConditionalChild	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [AggregateResultField__c] 
Stack Trace: Class.RollupServiceTest3.testDateRollupInsertConditionalChild: line 531, column 1
RollupSummariesTest	testInsertBadFieldTypeSumNotValid	System.AssertException: Assertion Failed: Expected: Sum/Avg doesnt looks like valid for dates ! Still want, then implement the IRollerCoaster yourself and change this class as required., Actual: Field does not exist. 
Stack Trace: Class.RollupSummariesTest.testInsertBadFieldTypeSumNotValid: line 392, column 1
RollupSummariesTest	testInsertCountByCloseDateNoErrors	System.AssertException: Assertion Failed: Expected: 0, Actual: 1 
Stack Trace: Class.RollupSummariesTest.testInsertCountByCloseDateNoErrors: line 517, column 1

Thanks in Advance.

**Comment by afawcett** [comment]
There are some sample custom fields included on some of the Standard objects in Developer Edition orgs, which will not be present in your Sandbox. Things like Account.NumberOfLocations__c. The tests do leverage these. The solution is to create these fields in your Sandbox and Production or install the managed package version of the tool (which does not need the tests to run). If your not planning on contributing back to the tools code or changing the code for your own use, i recommend installing via the managed package links in the README file.

**Comment by dishavdatta** [comment]
Thanks Andrew. Installing Package didn't give me any error.
