### ISSUE TITLE
Error occured processing component dlrs__LookupRollupSummary2.Not_Claimable_Number_of_investigations. An unexpected error occurred. Please include this ErrorId if you contact support: 1947423692-468717 (1216218650) (UNKNOWN_EXCEPTION).

### ISSUE THREAD

**Issue by alexandrafournier** [afawcett/declarative-lookup-rollup-summaries#364]
When I try to delete or inactivate a lookup rollup summary I have this error

Error occured processing component dlrs__LookupRollupSummary2.Not_Claimable_Number_of_investigations. An unexpected error occurred. Please include this ErrorId if you contact support: 1947423692-468717 (1216218650) (UNKNOWN_EXCEPTION).

**Comment by afawcett** [comment]
This is a GACK, see this [article here](https://developer.salesforce.com/blogs/engineering/2015/02/gack.html). You need to raise a case with Salesforce to get them to decode it. Once you know, let me know here, i might be able to help if Salesforce cannot.

**Comment by afawcett** [comment]
I'll close this issue out for now, however you can still add comments and if needed we can re-open. Thanks. 👍
