### ISSUE TITLE
RollupServiceTestTrigger, RollupServiceTest4Trigger and RollupServiceTest5Trigger has not been deployed.

### ISSUE THREAD

**Issue by ysato0000** [afawcett/declarative-lookup-rollup-summaries#365]
I got some errors when I tested apex classes by clicking the "Run All Tests" button. It seems that missing three triggers below are causing the errors.  I looked into the Package components list but these three triggers were not listed in the components. Has anyone seen this issue?
- RollupServiceTestTrigger
- RollupServiceTest4Trigger
- RollupServiceTest5Trigger

I installed the latest version of the tool in my Developer edition and also in Sandbox from the links below. 
https://login.salesforce.com/packaging/installPackage.apexp?p0=04tb0000000ka9e
https://test.salesforce.com/packaging/installPackage.apexp?p0=04tb0000000ka9e

error example:
Class: RollupServiceTest5
Method Name: testPolymorphicRelationshipsRealtime
Error Message: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Apex Trigger RollupServiceTest4Trigger has not been deployed. Click Manage Child Trigger and try again.: [dlrs__Active__c]

Class: RollupServiceTest6
Method Name: selfRollupDelete
Error Message: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Apex Trigger RollupServiceTestTrigger has not been deployed. Click Manage Child Trigger and try again.: [dlrs__Active__c]

Class: RollupServiceTest6
Method Name: testContactMergeAsChild
Error Message: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Apex Trigger RollupServiceTest5Trigger has not been deployed. Click Manage Child Trigger and try again.: [dlrs__Active__c]

Thank you in advance!

**Comment by afawcett** [comment]
Thanks this is a bug. Though its not common to click Run All Tests like this in an org, managed package tests typically run in the original developer org and validate the package code is working. You can run only your "local" tests in your org and not packaged ones using this [feature](https://releasenotes.docs.salesforce.com/en-us/winter16/release-notes/rn_deployment_change_sets_test_levels.htm).

**Comment by ysato0000** [comment]
Thanks for your reply! I will follow your advice and ignore the error.

**Comment by Benudek** [comment]
Andrew, is there a new version planned or any other way to eliminate & correct this error message ? 

Alternatively, we could deinstall the package but encountered some issues there.

**Comment by afawcett** [comment]
@Benudek yeah i can treat this as a bug and try to make the tests fail silently in production org. So in your case you need to do Run All Tests? And [this](https://releasenotes.docs.salesforce.com/en-us/winter16/release-notes/rn_deployment_change_sets_test_levels.htm) will not help?

What issues are preventing you uninstall btw? You have to remove the triggers first via Manage Child Triggers, but other than that you should be good.

**Comment by VirendraNaruka** [comment]
@afawcett  @Benudek 

 Test failing on production as Triggers not deployed with package like  1.RollupServiceTest5Trigger
2.RollupServiceTest4Trigger

Causing production over all test below <20%.  
Installed latest version "Latest Release Version 2.8". Any solution would you like to share.  Thanks in advance and really quick reply will be   appreciated .

**Comment by afawcett** [comment]
Hi @VirendraNaruka this should not be causing any code coverage issue at all. Code coverage is only counted for unmanaged code in your production code. Have you deployed the managed package version of the tool (via package installl link) or just deployed the code for the tool raw / unmanaged into your production org (via deploy to salesforce button)?

**Comment by VirendraNaruka** [comment]
Thanks Andrew for reply.

Actually installation goes well without any issue. its  Managed Package .
 but   After installation  if you run All test or try to deploy the change
set as default  setting then   Managed package test failed.

Its because Some of Test record created at Managed package but related
Trigger did not deployed with managed package.

I resolved some how but please try installation on dev org and then run all
test.  you will reproduce the issue.

Thanks

**Comment by afawcett** [comment]
Thanks 👍

**Comment by afawcett** [comment]
v2.9

**Comment by kappadragon** [comment]
These errors have resurfaced and similarly, I am now having code coverage issues. I don't believe this managed package to be dragging down the % directly, but if functionality fails and causes my tests to not work, then it does have an impact. Thus, to make sure these are not issues propagating into our APEX code, or the functionality of other managed packages, these should be cleaned up before a release, please.

**Comment by kappadragon** [comment]
They were, but we have such extensive validation now that all managed
packages fail their test scripts in our production environment because they
don't succeed the tests.

Best Regards,​

​

BENJAMIN FEAGIN JR., MSc, LC
