### ISSUE TITLE
Event count showing incorrect. 

### ISSUE THREAD

**Issue by findrohitsingh** [afawcett/declarative-lookup-rollup-summaries#367]
Hi, 
I have created roll up to count number of events and open events on opportunity table. It's giving me wrong count or i should say count with invitees. Like if i have 1 event on opportunity with 2 invitees. It give us count 3. 1 for Assignee and 2 for invitees.
Ideally it is single events only so count should be 1.

Please help me to figure out this issue.

**Comment by afawcett** [comment]
I'm not familar with the object model here, is invitee a custom object? Can you give a screenshot of the rollup configuration and object model (perhaps via schema builder?).

**Comment by wes1278** [comment]
I think you just need to filter the eventrelation object on the isinvitee field

**Comment by findrohitsingh** [comment]
I tried but it's not accepting.

**Comment by afawcett** [comment]
Looks like @wes1278 is familar with the object model, though i think both he and I could still help you more if you share some more info as per my previous comment. Thanks.

**Comment by afawcett** [comment]
@findrohitsingh if you still want to keep chatting on this, we can for sure re-open this issue, let us know. 👍
