### ISSUE TITLE
Setting multiple options for relationship criteria

### ISSUE THREAD

**Issue by HarryRSamuel** [afawcett/declarative-lookup-rollup-summaries#368]
Firstly, this is a great tool! I was at a complete impasse till I found this.

I'm trying to filter a roll-up summary field based on possible options for the Order Status field and it seems to be taking exception to the use of "or" in my relationship criteria. This may simply be my ignorance of SOQL syntax, but can you advise?

![image](https://cloud.githubusercontent.com/assets/20912161/17494425/8888c230-5dac-11e6-838e-048f271fec78.png)

**Comment by afawcett** [comment]
Looks like you need to put braces around it....

    (Status = 'PROCESSING' or Status = 'COMPLETED')

**Comment by afawcett** [comment]
You also only need to list Status once in the Relationship Criteria Fields.

**Comment by HarryRSamuel** [comment]
Ah great, thanks!
