### ISSUE TITLE
DLRS fails to fire, but nothing appears in DLRS Logs as an error

### ISSUE THREAD

**Issue by JenNelsonChicago** [afawcett/declarative-lookup-rollup-summaries#373]
This is very sporadic, and we still have no idea of the root cause, but since it has occurred 5 times in 6 months, I thought it was time to report it.

Every now and again, in one of our customer's Orgs with DLRS, we will notice that values on Parent records are not updating with the expected Real-time rollup from the Child.

There is no record in the DLRS Logs object to indicate an error such as a validation on parent and when I go to the DLRS and manually initiate "Calculate", the Apex Job shows completed with no error.

**Comment by afawcett** [comment]
Duplicate.
