### ISSUE TITLE
Error: Salesforce Metadata API connection failure, click the link below to configure.

### ISSUE THREAD

**Issue by Gilmc** [afawcett/declarative-lookup-rollup-summaries#376]
[Uploading 20160815_summaryErrormessage_00DK000000XNtGU.docx…]()
Hello there,
I came across the error message mentioned in the subject of this post. Although I noticed it has been reported before i could not find the solution. I am trying to create a summary roll-up between custom object (child) and contact (parent). The error message does not appear on production but only on our sandbox (as I rather test it there first).

First Installed Version Number  1.23
Package Type    Managed
I do not have a field named API Package on the under Installed Packages>Package Details

Could you please advise me how to solve this?

Kind regards,
Gil

**Comment by Gilmc** [comment]
PS: it reads click the link below, however, there is no link available to click on.

**Comment by afawcett** [comment]
Can you attach a screenshot here? (just drag drop into the comment box)

**Comment by Gilmc** [comment]
[20160815_summaryErrormessage_00DK000000XNtGU.docx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/419741/20160815_summaryErrormessage_00DK000000XNtGU.docx)

**Comment by ClarkBranson** [comment]
@Gilmc sounds like you didn't add the remote site configuration. Click the "+" at the top to view all tabs then click on "Lookup Rollup Summaries" which will give you the option to automatically create the remote site...

Hey Andy, what info are you gathering through the Metadata API anyway?

**Comment by Gilmc** [comment]
@ClarkBranson thank you for your message. I follow your instructions but I did not get an option to set up Remote Site Configuration. I see only list view of "Recent Lookup Rollup Summaries". 
What do I need to do in order to have that accessible?

**Comment by afawcett** [comment]
@ClarkBranson The Metadata API is not used to calculate the rollups once defined. It is used in two areas when setting up rollup definitions (if your using the 'Manage Rollup Summeries' tab) and when activating them for a child object for the first ever time. So the 'Manage Rollup Summaries' tab (to create, edit and delete rollup definitions stored in Custom Metadata) if your using it as apposed to the 'Lookup Rollup Summaries' tab. Also when you press 'Manage Child Trigger' button, it is used to deploy and undeploy the Apex Triggers used by the tool.

@Gilmc Your running quite an old release, but it should have the link below that error message, yet i can see that it does not from your screenshot. The link would take you to the Welcome tab of the tool, so you could try finding that and see if the option comes up to create the Remote Site. @ClarkBranson's suggest is another way, but you may have previously elected to not show the tab splash / welcome screen, which explains why your going straight to the recently used list.

Hope this helps, also note that the README has a known issues section and mentions issues connecting with the Metadata API and known reasons. The Welcome page should have a debug feature on screen to help troubleshoot.

**Comment by Gilmc** [comment]
@afawcett I could not find in the README document where I can have the link enabled (when I receive this error message: Declarative Lookup Rollup Summary Tool). Could you please direct me how can I do that? Or should I install new version from the AppExchange instead?

**Comment by afawcett** [comment]
**Clarification on the README File:** My README reference in my previous messages is to point you to a description of a known is issue with Metadata API connections. See last bullet in the list [here](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues). So it does not provide the link where it can be enabled, as i think you expected. It simply gives you a bit more information on possible cause.

**Finding the Welcome Tab:** As i per my message above, please find the Welcome tab, you should be able to select Declarative Lookup Rollup Summary from the App menu (top right) and see the tabs. The first tab should be the Welcome tab. If you don't see it you may have to enable it via your profile and then click the All Tabs page to find it. The Welcome page should validate the Metadata API connection and present you with the option to create the Remote Site setting to resolve the issue.

**Upgrading:** If you want to upgrade you can find the latest package install link in the README file [here](https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history). You need only click the link and login to your org, Salesforce will automatically upgrade your installation of the tool. 

Finally, when you say _(when I receive this error message: Declarative Lookup Rollup Summary Tool)_, i don't know what you mean, that is not an error message?

**Comment by afawcett** [comment]
Let me know if this helped you out or not, we can re-open this issue for sure if not. 👍

**Comment by Gilmc** [comment]
Hi Andrew,

Thank you for checking on it.
Unfortunately I still have the same error. I have no idea how to solve it.
I have tried now to upgrade the app on the my sandbox – see if that can help.

Do you have any other recommendations?

Kind regards,
Gil

**Comment by Gilmc** [comment]
Error:
Salesforce Metadata API connection failure, click the link below to configure.

**Comment by afawcett** [comment]
When you go to the Welcome tab for the tool, can you send me a screenshot?

**Comment by Gilmc** [comment]
That is exactly what I cannot do. The tab is not available. I looked at my profile to allow that but cannot see it.

**Comment by Gilmc** [comment]
[cid:image002.jpg@01D208EE.45A2C6E0]

When you go to the Welcome tab for the tool, can you send me a screenshot?

**Comment by afawcett** [comment]
Are you running the latest version of the tool? The Welcome tab should be visible in your profile for sure.

**Comment by afawcett** [comment]
@Gilmc did you manage to get things sorted on this issue? Did you check you had latest version and the Welcome tab? If not, we can re-open this issue and continue discussions.
