### ISSUE TITLE
COUNT operation not working in the Enhanced Lookup Pilot

### ISSUE THREAD

**Issue by MrTwoArms** [afawcett/declarative-lookup-rollup-summaries#38]
When attempting to use the Count aggregation operation using the Enhanced Lookup Pilot option, an error message appears requiring the Field to Aggregate. However, selecting the Count operation removes the Field to Aggregate field from the page layout and therefore cannot be specified.
![image](https://cloud.githubusercontent.com/assets/6123995/3150847/f9b6b946-ea7a-11e3-86d1-e59484f62766.png)

**Comment by afawcett** [comment]
So i think its best we close bugs on the old Custom Object VF UI for rollups. This issue relates to the drop downs on these pages, there is another enhancement to add these to the new custom metadata based VF page. I think effort should go into doing that, than fixing these. Happy to re-open these bugs if anyone disagrees. 👍
