### ISSUE TITLE
Stuck in "Lookup Rollup Calculate Job"

### ISSUE THREAD

**Issue by StephanieKing** [afawcett/declarative-lookup-rollup-summaries#381]
On a new rollup I created, I click "Calculate", and it just seems to hang out in "Lookup Rollup Calculate Job" forever... not calculating, nothing rolling up, nothing happening. It just stays there forever, until I delete it and try again. Any idea why that would be? Screenshot of my rollup is here:

![image](https://cloud.githubusercontent.com/assets/17727591/17785309/d9300fd6-6545-11e6-8f91-bd355fe50348.png)

**Comment by StephanieKing** [comment]
The next rollup I created did the same thing - it was a very different rollup, on different object....
They are both just stuck eternally in "jobs"...
![image](https://cloud.githubusercontent.com/assets/17727591/17787281/1ced4394-654e-11e6-8e3c-00b16df1eb98.png)

**Comment by afawcett** [comment]
Can you send a screenshot of your jobs screen? What status are they showing? Sometimes Salesforce will pause jobs under certain conditions. It usually rectifies itself. [This](https://developer.salesforce.com/page/Asynchronous_Processing_in_Force_com) gives a bit more background as to the reasons.

**Comment by StephanieKing** [comment]
Here is one of the Jobs - but I don't know what you mean about a status? Should I be looking somewhere else?
![image](https://cloud.githubusercontent.com/assets/17727591/17789630/ab02d554-6558-11e6-8d14-f01c921cc5fc.png)

**Comment by StephanieKing** [comment]
Aha, I think you meant Apex Jobs, sorry. Looks like I've got a bunch in there with a status of "holding." One idea I had is to abort these jobs, then change the type of all my rollups to "Scheduled" instead of "realtime" and then try again to see if my new ones will calculate... or perhaps wait till tomorrow if my usage for the day has hit a limit...?

**Comment by afawcett** [comment]
Yes give it some time and if not call Salesforce support or raise a case. Calculate is designed to either be a full one off recalc (to update existing records) prior to enabling Realtime. Or you can enable Schedule mode on the rollup, then schedule the RollupJob class via APex Classes under Setup and it will processes records that need recalc each day. Final option is to use Schedule Calculate button on the rollup to run a full recalc at different times

**Comment by StephanieKing** [comment]
Yep, that's all it was, was waiting 24 hours for a backed up jobs list to process through! Sorry to bother you with that - I just had not run into it before! But I guess we were having a busy day in that org.... Good to know for the future... Thanks as always!
