### ISSUE TITLE
Can't Install on Production

### ISSUE THREAD

**Issue by HarryRSamuel** [afawcett/declarative-lookup-rollup-summaries#386]
Hi Andy,

Having successfully installed and tested this tool in Sandbox, I can't seem to deploy it to Production. When I click the Deploy to SF button and login, it tries to run but then the following  happens:

> Deployment Started
> Status: Queued 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: InProgress 
> Status: Completed 
> Deployment Complete
> Failures:
> components/zip.component(zip):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> components/zipEntry.component(zipEntry):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/managelookuprollupsummaries.page(managelookuprollupsummaries):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/managetrigger.page(managetrigger):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/managetriggermdt.page(managetriggermdt):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupcalculate.page(rollupcalculate):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupcalculatemdt.page(rollupcalculatemdt):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupscheduledcalculate.page(rollupscheduledcalculate):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupscheduledcalculatemdt.page(rollupscheduledcalculatemdt):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupsummaryenhanced.page(rollupsummaryenhanced):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/rollupsummaryenhancednew.page(rollupsummaryenhancednew):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/welcome.page(welcome):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> pages/welcometab.page(welcometab):The specified Package Version number does not exist for that Package: sf_com_apps, 1.7
> objects/LookupRollupSummary__c.object(372,15):In field: page - no ApexPage named rollupcalculate found
> objects/LookupRollupSummary__c.object(383,15):In field: page - no ApexPage named rollupsummaryenhanced found
> objects/LookupRollupSummary__c.object(394,15):In field: page - no ApexPage named rollupsummaryenhancednew found
> objects/LookupRollupSummary__c.object(406,15):In field: page - no ApexPage named managetrigger found
> objects/LookupRollupSummary__c.object(417,15):In field: page - no ApexPage named rollupscheduledcalculate found
> layouts/LookupRollupSummary__c-Lookup Rollup Summary Layout.layout(LookupRollupSummary__c-Lookup Rollup Summary Layout):In field: customButtons - no WebLink named LookupRollupSummary__c.EnhancedEdit found
> weblinks/Welcome.weblink(Welcome):In field: page - no ApexPage named welcome found
> tabs/LookupRollupSummary__c.tab(LookupRollupSummary__c):In field: splashPageLinkName - no CustomPageWebLink named Welcome found
> tabs/ManageLookupRollupSummaries.tab(ManageLookupRollupSummaries):In field: page - no ApexPage named managelookuprollupsummaries found
> tabs/Welcome.tab(Welcome):In field: page - no ApexPage named welcometab found
> applications/DeclarativeLookupRollupSummaries.app(DeclarativeLookupRollupSummaries):In field: defaultLandingTab - no CustomTab named Welcome found
> classes/ApexClassesSelector.cls(ApexClassesSelector):Page managelookuprollupsummaries does not exist
> classes/ApexTriggersSelector.cls(ApexTriggersSelector):Page managelookuprollupsummaries does not exist
> classes/AsyncApexJobsSelector.cls(AsyncApexJobsSelector):Page managelookuprollupsummaries does not exist
> classes/CustomMetadataService.cls(CustomMetadataService):Page managelookuprollupsummaries does not exist
> classes/CustomMetadataServiceTest.cls(CustomMetadataServiceTest):Page managelookuprollupsummaries does not exist
> classes/LREngine.cls(LREngine):Page managelookuprollupsummaries does not exist
> classes/ManageLookupRollupSummariesController.cls(ManageLookupRollupSummariesController):Page managelookuprollupsummaries does not exist
> classes/MetadataService.cls(MetadataService):Page managelookuprollupsummaries does not exist
> classes/MetadataServiceTest.cls(MetadataServiceTest):Page managelookuprollupsummaries does not exist
> classes/RollupActionCalculate.cls(RollupActionCalculate):Page managelookuprollupsummaries does not exist
> classes/RollupActionCalculateTest.cls(RollupActionCalculateTest):Page managelookuprollupsummaries does not exist
> classes/RollupCalculateController.cls(RollupCalculateController):Page managelookuprollupsummaries does not exist
> classes/RollupCalculateJob.cls(RollupCalculateJob):Page managelookuprollupsummaries does not exist
> classes/RollupCalculateJobSchedulable.cls(RollupCalculateJobSchedulable):Page managelookuprollupsummaries does not exist
> classes/RollupController.cls(RollupController):Page managelookuprollupsummaries does not exist
> classes/RollupControllerTest.cls(RollupControllerTest):Page managelookuprollupsummaries does not exist
> classes/RollupJob.cls(RollupJob):Page managelookuprollupsummaries does not exist
> classes/RollupJobTest.cls(RollupJobTest):Page managelookuprollupsummaries does not exist
> classes/RollupScheduledCalculateController.cls(RollupScheduledCalculateController):Page managelookuprollupsummaries does not exist
> classes/RollupScheduledCalculateControllerTest.cls(RollupScheduledCalculateControllerTest):Page managelookuprollupsummaries does not exist
> classes/RollupService.cls(RollupService):Page managelookuprollupsummaries does not exist
> classes/RollupServiceException.cls(RollupServiceException):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest.cls(RollupServiceTest):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest2.cls(RollupServiceTest2):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest3.cls(RollupServiceTest3):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest4.cls(RollupServiceTest4):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest5.cls(RollupServiceTest5):Page managelookuprollupsummaries does not exist
> classes/RollupServiceTest6.cls(RollupServiceTest6):Page managelookuprollupsummaries does not exist
> classes/RollupSummaries.cls(RollupSummaries):Page managelookuprollupsummaries does not exist
> classes/RollupSummariesSelector.cls(RollupSummariesSelector):Page managelookuprollupsummaries does not exist
> classes/RollupSummariesTest.cls(RollupSummariesTest):Page managelookuprollupsummaries does not exist
> classes/RollupSummary.cls(RollupSummary):Page managelookuprollupsummaries does not exist
> classes/RollupSummaryEnhancedController.cls(RollupSummaryEnhancedController):Page managelookuprollupsummaries does not exist
> classes/RollupSummaryEnhancedControllerTest.cls(RollupSummaryEnhancedControllerTest):Page managelookuprollupsummaries does not exist
> classes/RollupSummaryScheduleItemsSelector.cls(RollupSummaryScheduleItemsSelector):Page managelookuprollupsummaries does not exist
> classes/TestContext.cls(TestContext):Page managelookuprollupsummaries does not exist
> classes/TestLREngine.cls(TestLREngine):Page managelookuprollupsummaries does not exist
> classes/Utilities.cls(Utilities):Page managelookuprollupsummaries does not exist
> classes/WelcomeController.cls(WelcomeController):Page managelookuprollupsummaries does not exist
> classes/WelcomeControllerTest.cls(WelcomeControllerTest):Page managelookuprollupsummaries does not exist
> classes/fflib_ApexMocks.cls(fflib_ApexMocks):Page managelookuprollupsummaries does not exist
> classes/fflib_ApexMocksTest.cls(fflib_ApexMocksTest):Page managelookuprollupsummaries does not exist
> classes/fflib_Application.cls(fflib_Application):Page managelookuprollupsummaries does not exist
> classes/fflib_IDGenerator.cls(fflib_IDGenerator):Page managelookuprollupsummaries does not exist
> classes/fflib_IDGeneratorTest.cls(fflib_IDGeneratorTest):Page managelookuprollupsummaries does not exist
> classes/fflib_ISObjectDomain.cls(fflib_ISObjectDomain):Page managelookuprollupsummaries does not exist
> classes/fflib_ISObjectSelector.cls(fflib_ISObjectSelector):Page managelookuprollupsummaries does not exist
> classes/fflib_ISObjectUnitOfWork.cls(fflib_ISObjectUnitOfWork):Page managelookuprollupsummaries does not exist
> classes/fflib_MethodCountRecorder.cls(fflib_MethodCountRecorder):Page managelookuprollupsummaries does not exist
> classes/fflib_MethodReturnValue.cls(fflib_MethodReturnValue):Page managelookuprollupsummaries does not exist
> classes/fflib_MethodReturnValueRecorder.cls(fflib_MethodReturnValueRecorder):Page managelookuprollupsummaries does not exist
> classes/fflib_Mocks.cls(fflib_Mocks):Page managelookuprollupsummaries does not exist
> classes/fflib_MyList.cls(fflib_MyList):Page managelookuprollupsummaries does not exist
> classes/fflib_QueryFactory.cls(fflib_QueryFactory):Page managelookuprollupsummaries does not exist
> classes/fflib_QueryFactoryTest.cls(fflib_QueryFactoryTest):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectDescribe.cls(fflib_SObjectDescribe):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectDescribeTest.cls(fflib_SObjectDescribeTest):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectDomain.cls(fflib_SObjectDomain):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectDomainTest.cls(fflib_SObjectDomainTest):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectMocks.cls(fflib_SObjectMocks):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectSelector.cls(fflib_SObjectSelector):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectSelectorTest.cls(fflib_SObjectSelectorTest):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectUnitOfWork.cls(fflib_SObjectUnitOfWork):Page managelookuprollupsummaries does not exist
> classes/fflib_SObjectUnitOfWorkTest.cls(fflib_SObjectUnitOfWorkTest):Page managelookuprollupsummaries does not exist
> classes/fflib_SecurityUtils.cls(fflib_SecurityUtils):Page managelookuprollupsummaries does not exist
> classes/fflib_SecurityUtilsTest.cls(fflib_SecurityUtilsTest):Page managelookuprollupsummaries does not exist
> classes/fflib_StringBuilder.cls(fflib_StringBuilder):Page managelookuprollupsummaries does not exist
> classes/fflib_StringBuilderTest.cls(fflib_StringBuilderTest):Page managelookuprollupsummaries does not exist
> triggers/RollupSummariesTrigger.trigger(30,37):Variable does not exist: RollupSummaries.class
> triggers/RollupServiceTestTrigger.trigger(13,6):Variable does not exist: TestContext.OpportunityTestTriggerEnabled
> triggers/RollupServiceTest5Trigger.trigger(13,6):Variable does not exist: RollupService
> triggers/RollupServiceTest4Trigger.trigger(13,6):Variable does not exist: RollupService
> triggers/RollupServiceTest3Trigger.trigger(13,6):Variable does not exist: TestContext.AccountTestTriggerEnabled
> triggers/RollupServiceTest2Trigger.trigger(13,6):Variable does not exist: RollupService
> objects/LookupRollupSummary__c.object(LookupRollupSummary__c):In field: listViewButtons - no WebLink named LookupRollupSummary__c.EnhancedNew found
> permissionsets/LookupRollupSummariesReadOnly.permissionset(LookupRollupSummariesReadOnly):In field: tab - no CustomTab named LookupRollupSummary__c found
> permissionsets/LookupRollupSummariesFull.permissionset(LookupRollupSummariesFull):In field: tab - no CustomTab named LookupRollupSummary__c found

Any ideas?

**Comment by wes1278** [comment]
@HarryRSamuel You can't deploy managed code artifacts, ever. So DLRS is no exception to that salesforce limitation. You can however just include the managed package namespace in a package.xml in the InstalledPackages node and it will install it for you in the target org. Or you can use the production link in the github readme.md to install DLRS in production. You should be able to deploy the custom metadata after that though so you have your DLRS rules.

Let me know if that helps you out. Also, do you know there is a chatter group setup for DLRS? There might be some good content or additional help in that avenue.

**Comment by afawcett** [comment]
@HarryRSamuel unless you want the unmanaged version in your org (harder to upgrade) i suggest you go via the package install links, click the link, login, follow the wizard job done! 👍

**Comment by HarryRSamuel** [comment]
Apologies if I'm being inept, but where are the package install links?

**Comment by wes1278** [comment]
if you visit the main page of github, they are there in the readme. https://github.com/afawcett/declarative-lookup-rollup-summaries

but to make things easier for you, here they are:
prod - https://login.salesforce.com/packaging/installPackage.apexp?p0=04tb0000000MXVO
sandbox - https://test.salesforce.com/packaging/installPackage.apexp?p0=04tb0000000MXVO

**Comment by HarryRSamuel** [comment]
Ah thanks! Couldn't see those links anywhere so that's very helpful.
