### ISSUE TITLE
Support for Multiple Relationship field in same rollup?

### ISSUE THREAD

**Issue by shawnholt** [afawcett/declarative-lookup-rollup-summaries#387]
My rollup is quiet simple:
Parent = custom object called "sessions"
Child = campaign member
Child lookups = "session 1", "session 2"

Want to see how many people registered to a session allow people to pick two sessions.

Creating the rollup only lets me select one Relationship Field but I have two and want to sum registrations for anyone with session in **either** field.

Not sure if this is supported.  If i have two rollup triggers, they will overwrite each

**Comment by afawcett** [comment]
So if you have two rollups each to their own total on the parent, then have a formula field on the parent that adds the two of them together. Then on the layout only show the formula field and not the two totals. This should get you the information you need i think to show to the user with the tools currently functionality. I think... ? 👍

**Comment by shawnholt** [comment]
Yes!  thanks!
