### ISSUE TITLE
Metadata API connection failure error after creating the remote site

### ISSUE THREAD

**Issue by jk94110** [afawcett/declarative-lookup-rollup-summaries#388]
Hi,

I cannot get past the Metadata API connection error after 1) installing, 2) setting up remote site, and then 3) going to the Manage Lookup Rollup Summaries tab.  On this page I get "Error: Salesforce Metadata API connection failure, click the link below to configure."

I've tried deleting and recreating the remote site, as well as uninstalling and reinstalling the entire package. For the heck of it I created a rollup record using the old tab but then got this error when trying to create the child trigger.

I've used this package many times in many different instances without any problems.

Any ideas?

Thanks,

Jim

**Comment by ClarkBranson** [comment]
Did you manually add the remote sites? The reason I ask is I got the same message after a fresh install. However when I went to the old "Lookup Rollup Summaries" tab this had the option for adding the remote sites for you automatically and afterwards everything worked.

**Comment by jk94110** [comment]
Thanks Clark, I just figured it out.  Actually someone did for me on an older issue.  On the following issue (110) there is a lot of back and forth and finally someone figured out that having the "Lock sessions to the IP address from which they originated" checked in Setup > Session Settings was causing the problem. I unchecked this, logged out and then back in and the problem went away.

Even though the solution was different I very much appreciate your taking the time to respond.

Unable to connect to the Salesforce Metadata API.  
#110 
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/110
