### ISSUE TITLE
Nested Queries? (ie Date of Previous Oppty/Order) 

### ISSUE THREAD

**Issue by ClarkBranson** [afawcett/declarative-lookup-rollup-summaries#389]
I've literally spent the last 10 hours trying to accomplish to following:

How to use the First/Last aggregate with the SOQL WHERE clause in the "Relationship Criteria" to determine the the date of the previous child record based on matching criteria.

For example, AcmeInc. has a total of 100 Opportunities where 90 are for Product and 10 for Support. However when looking at a Support Oppty the field "Date of Previous" should show the  Close/Won date for the previous/most recent Support Oppty.

Is there any way of getting the dlrs to do a nested query to loop through the child records and put the previous "Closed Date" for the respective Support/Product?

**Comment by afawcett** [comment]
So using Last/First with the criteria only focusing on Support Oppty should do work for this use case, have you tried that?

**Comment by ClarkBranson** [comment]
I tried using the Last/First with the criteria only focusing on Support Oppty but I could only write to the Parent. My apologies, if I wasn't clear. I'm trying to write to a field on the Oppty of the date of the PREVIOUS Oppty. 

Ultimately I want to use the date of the previous (similar) Oppty to calculate the number of days between them without having to use analytical snapshots, or write a complex batch apex job/headless flow. Here's a screen shot of an Account with 6 Opptys:

Line#1 has Oppty ending in "084" which was created on 3/21/2016 and shows the date of the previous Oppty as 2/2/2016 (a formula field calculates 48 days between the orders) 

The Oppty previous to "084" is on Line#2 (ending in "964") and shows the 2/2/2016 created date along with showing the Oppty previous to "964" which was on 1/4/2016 (29 days prior) ...and so on and so forth.

Two additional (superfluous) conditions, unique/specific to my use-case and where things get interesting. (READ: complex and FUN!) Using the screen-shot example with the 6 Opptys, these could be broken down into three different categories: 
3/21/2016 Product 
2/2/2016 Service, 
1/4/2016 Support
11/17/2015 Support
11/11/2015 Service
8/18/2015 Product 

Therefore when looking at the 3/21/2016 "Product" Oppty it should show 8/18/2015 as the date of the previous "Product" Oppty. 

The last condition is there could be multiple "Product" Opptys however one of them gets cancelled..and thus shouldn't show as "DateofPreviousOrder" on the subsequent Oppty.

I was hoping that your filter criteria and batch apex job could provide a quick solution. 
![ordertrending](https://cloud.githubusercontent.com/assets/21071027/18371912/15c124a0-75ed-11e6-8449-6e9f66717415.png)

**Comment by afawcett** [comment]
I think your better off looking at Process Builder to implement this, you might have to use it to differ processing to a Flow, but i think this should be possible.

**Comment by afawcett** [comment]
@ClarkBranson did you manage to  get this working? Happy to re-open this issue if you still want to discuss. 👍
