### ISSUE TITLE
Still unable to connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by gemziebeth** [afawcett/declarative-lookup-rollup-summaries#393]
Hi there, have been through issue 110 and I am still experiencing the same issue, despite following the instructions provided for the fix. I have disabled lockdown for IP addresses and domains; checked the package and I don't have a field for API Enabled. I am able to create the remote site but when I refresh the welcome page I get the same session error:

I have granted subscriber access

DEBUG USE ONLY: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

<img width="1253" alt="screen shot 2016-08-31 at 09 21 34" src="https://cloud.githubusercontent.com/assets/21357270/18121413/59e3adac-6f5c-11e6-9d9f-e118a0bc979b.png">

**Comment by afawcett** [comment]
Are you running PE edition?

**Comment by gemziebeth** [comment]
No - enterprise


________________________________

**Comment by gemziebeth** [comment]
K realised that the issue is that in fact when you disable lockdown of IP ranges, you actually do have to kill the current session by logging out and back in again for it to remember your remote site setting.

**Comment by afawcett** [comment]
Thanks for sharing @gemziebeth.

**Comment by gbillerbeck** [comment]
Hi, ... I do have the same problem - but IP ranges are enabled.
Running Enterprise edition...
