### ISSUE TITLE
DLRS New Record will not save.

### ISSUE THREAD

**Issue by nelle3223** [afawcett/declarative-lookup-rollup-summaries#395]
I created a new DLRS and for some reason it will not allow me to save it.  I Hit save and it stays on the same page.

**Comment by afawcett** [comment]
Are you using the Manage Rollup Summaries tab? If so, that is by design, so long as you don't get an error, it has saved it.

**Comment by nelle3223** [comment]
Great thanks so much!

Janelle Hunter
NexGen Consultants, Inc.
janelle@nexgenconsultants.com
Cell: (859) 814-7757
