### ISSUE TITLE
Error when calculating Scheduled Job

### ISSUE THREAD

**Issue by wjtre20** [afawcett/declarative-lookup-rollup-summaries#397]
I have about 6 fields that roll up from the Order object to the Account object. There are just above 525k order records. 

When I try to run Calculate job to get an immediate record update I get the error:

**First error: dlrs:Too many query rows: 50001**

Also it appears my scheduled jobs I have either do not run (looks like they are only set to run once a month and I can't adjust that). How do I correct this as well? I'm pretty sure this is all related to a basic issue.

What is the best way to get the job to work? I have a few filters on the rollup fields but there are still quite a bit of records included event with filters applied.

**Comment by afawcett** [comment]
You can reduce the number of records each chunk the scheduled job tries to process via a custom setting. Review this [blog](https://andyinthecloud.com/2014/02/09/new-release-spring14-declarative-rollup-summary-tool/) for more.
