### ISSUE TITLE
NBSP() not working for Concatenate Delimiter for plain text fields

### ISSUE THREAD

**Issue by rogerrogers** [afawcett/declarative-lookup-rollup-summaries#400]
I'm using the Concatenate aggregation function. This is going to a simple text field. I need the delimiter to be a comma followed by a space. I've tried using the NBSP() function as outlined in this issue: https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/149

However, this results in the output being: [Text],NB [Next text]

Is there any way you can update this so that the NBSP() is converted to a simple space for simple text fields?

We're loving this tool. Thanks for your generosity and efforts supporting it!

**Comment by rogerrogers** [comment]
Well, I just found that the solution is to just use SP() not NBSP(), nice!

**Comment by afawcett** [comment]
Thanks @rogerrogers for the kind words and glad you found your solution! 👍
