### ISSUE TITLE
Invalid field error in scheduled mode

### ISSUE THREAD

**Issue by jonlarosa** [afawcett/declarative-lookup-rollup-summaries#401]
I'm getting the following error with a Scheduled rollup:

---

First error: 
dlrs__ParentId__c FROM dlrs__LookupRollupSummaryScheduleItems__c 
^
ERROR at Row:1:Column:112
Invalid field: 'Disaster_Gift_Amount__c'

---

The field referenced is on the Opportunity, and I've checked that and the field is there and works fine.

What's interesting is that I was getting this same error with a different rollup previously (and different field). I cloned that rollup and deleted the old one, and that seems to have fixed the issue with that one. But I did the same thing with my "Disaster Gift Amount" rollup and that didn't seem to fix the issue.

Also interesting is that I have nightly full recalculation for this rollup and that works without any issue.

Screen shots of the rollup as well as the field in question:

![disaster amt dlrs record](https://cloud.githubusercontent.com/assets/22327966/18766154/cd943f8c-80e6-11e6-9f4b-5a8b1c4d0739.JPG)

![disaster amt - opp formula field](https://cloud.githubusercontent.com/assets/22327966/18766159/d4efd624-80e6-11e6-9840-6d5014fae856.JPG)

**Comment by afawcett** [comment]
@jonlarosa Sorry this dropped through the cracks, do you still need help with this?

**Comment by jonlarosa** [comment]
Well I never did figure out the issue. But I had to remove the trigger on the object so now I'm running that same rollup via a full nightly recalc and I'm not receiving any errors. So the error was never really resolved but it's also not affecting me anymore ......

**Comment by JimBTek** [comment]
I am now running into this issue as I move items from nightly full recalc to Scheduled with RollupJob.

It does not generate a Summary Log either with the error

`First error: 
dlrs__LookupRollupSummary2__c, dlrs__LookupRollupSummary__c, dlrs__ParentId__c
^
ERROR at Row:1:Column:49
Invalid field: 'Total_Cost__c'`

**Comment by JimBTek** [comment]
it looks like instead of referencing the Metadata record it generates a completely blank dlrs__LookupRollupSummary__c record that is missing all the details:

![image](https://user-images.githubusercontent.com/1176347/43167235-fb635cd2-8f66-11e8-879f-fb016daa4c2e.png)

![image](https://user-images.githubusercontent.com/1176347/43167399-864c29a0-8f67-11e8-8b0c-8d3bc49a6fff.png)

And it's created by the end user who touched the underlying record, not by an Admin.

**Comment by JimBTek** [comment]
so i just tested by installing 2.11 over 2.5 in a sandbox with Admin only permissions, and it seems to behave exactly the same EXCEPT now it works.  

It still generates these empty Lookup Rollup Summary records. 

Just commenting here in case anyone else has this problem, but I was able to fix by upgrading.
