### ISSUE TITLE
Error Deploying Apex Trigger 

### ISSUE THREAD

**Issue by labrams** [afawcett/declarative-lookup-rollup-summaries#402]
Any ideas how I can get around this error?

dlrs_pse_AssignmentTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Bill Rate is required: [pse__Bill_Rate__c] Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_pse_AssignmentTest.testTrigger: line 11, column 1

Thank you!

**Comment by afawcett** [comment]
Please take a look at [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) page, it will explain whats going on and what you need to do to resolve it. Let me know if your still struggling. 👍
