### ISSUE TITLE
declarative-lookup-rollup-summaries  Package Installation Failed

### ISSUE THREAD

**Issue by RaoNemani** [afawcett/declarative-lookup-rollup-summaries#403]
Hello Andy, 

We are planning to leverage this app in our org and we are getting following error while installing it. Can you please advise the steps to resolve it? 

AppExchange Package is Deprecated	The AppExchange package has been deprecated and can no longer be installed. Please try installing a newer version, or contact the package owner directly to resolve. 

Thanks,
rao

**Comment by merrowusa** [comment]
Same issue here -

**Comment by afawcett** [comment]
Please refer to the README for the latest package version.
