### ISSUE TITLE
Child Trigger and Code Coverage Error - Current Company Not Set

### ISSUE THREAD

**Issue by socalcloudcpa** [afawcett/declarative-lookup-rollup-summaries#406]
FFA V15

Apex Test Failures
 
Class Name
Method Name
Error Message
dlrs_c2godaCashEntryLineItemTest	testTrigger	System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Cash Entry Line Item: Object validation has failed. Current company not set.: [] 
Stack Trace: Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_c2godaCashEntryLineItemTest.testTrigger: line 11, column 1

**Comment by afawcett** [comment]
Please refer to [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) page and also the API documentation for that package, it has a sample Apex test that will help you setup the required context needed to pass the validation this object requires.
