### ISSUE TITLE
Incorrect SUM Value When Rolling Up Foreign Currency

### ISSUE THREAD

**Issue by kyle-johnson-infusionsoft** [afawcett/declarative-lookup-rollup-summaries#408]
I have a couple of Currency fields on Opportunity that both roll up various fields from Opp Line Items. These rollups work **exactly** as expected when summing up native currency line items (USD), but when the currency is changed to anything else the values sum up entirely incorrectly. 

As an example, I have an Opportunity in GBP that has one line item priced at GBP 199.00. DLRS rolls this value up to be GBP 404.35 (USD 525.54). Rolling up the exact same field with native SF rollup results in a correct result of GBP 199.00 (USD 258.64).

Are there any known issues with rolling up values in multicurrency orgs?

**Comment by jhomanncarreon** [comment]
Hi, i too have issues with other currencies rolling up incorrectly.  I have a Parent/Child Opportunity where the amount on the Child Opp does not Sum up to the Parent Opp
![cieventsoppdeclarativerollup](https://cloud.githubusercontent.com/assets/19741264/19376434/1b866a30-9221-11e6-9fd0-a78904722a40.jpg)
![cieventsoppdeclarativerolluprecord](https://cloud.githubusercontent.com/assets/19741264/19376461/5d2d4cc4-9221-11e6-876a-24154bee5d0e.jpg)

**Comment by afawcett** [comment]
Take a look at [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/284) and also the associated issue in it. I think its the same issue?

**Comment by kyle-johnson-infusionsoft** [comment]
Yep, I believe what we're seeing is the same thing! The workaround was to do what another person suggested in that thread and sum up the line items in Apex code.

**Comment by afawcett** [comment]
Closing this as a duplicate.
