### ISSUE TITLE
Error when attempting to save an Opportunity record

### ISSUE THREAD

**Issue by tp1989** [afawcett/declarative-lookup-rollup-summaries#409]
Hi Alex,

I get the following error when attempted to save an Opportunity record:

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Opportunity: Class.dlrs.RollupService.handleRollups: line 770, column 1

This is only when the following Lookup Rollup Summary is active:

![image](https://cloud.githubusercontent.com/assets/22594769/19041379/b4179422-897f-11e6-97b3-3b34fa660ff3.png)

Any help would be great.

Thanks,

Thomas

**Comment by melyssinsf** [comment]
I am having the same issue except it happens when I convert a lead with an opportunity.

**Comment by afawcett** [comment]
Not sure why it let you save this rollup? As the relationship field is invalid. It should be AccountId, as per the [docs here](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_opportunity.htm).

**Comment by afawcett** [comment]
@tp1989 Let me know if changing to AccountId worked or not. If not, we can re-open this issue and keep the conversation going. 👍
