### ISSUE TITLE
Results in scheduled mode different than direct claculate 

### ISSUE THREAD

**Issue by adamarkman** [afawcett/declarative-lookup-rollup-summaries#410]
Hi ,
In using Calculate of specific summaries we get the right results while in scheduled mode we get zeros. 
We need to run full summaries calculations one a month and in scheduled mode. 
The calculations depend on formula and date function. (X<THIS_QUARTER). 
Please help
Ada

**Comment by afawcett** [comment]
Are you using the Calculation Mode = Scheduled field? Sounds like you need to use the Schedule Calculate button (with Calculation Mode = Process Builder even though you don't intend to use via Process Builder). This will allow you to schedule a full recalculate of your rollup on a schedule.

**Comment by afawcett** [comment]
@adamarkman The above suggestion from me should get you going with time based formulas and rollups. Let me know if not, and we can re-open. 👍
