### ISSUE TITLE
Issue with Asset Rollup

### ISSUE THREAD

**Issue by georgesf7** [afawcett/declarative-lookup-rollup-summaries#411]
Hi, 

I've created a Lookup Relationship between Asset and Contact. After I deployed the dlrs_AssetTrigger, I can no longer create new Asset record. I've been getting below error whenever I'm creating a new record:
Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_AssetTrigger caused an unexpected exception, contact your administrator: dlrs_AssetTrigger: execution of AfterInsert caused by: dlrs.RollupServiceException: Lookup Rollup Summary 'Asset Rollup' is invalid, your org configuration may have changed.: Class.dlrs.RollupService.createLSFWrapper: line 1150, column 1

However, this doesn't prevent me from editing existing Asset record, and if I remove the dlrs_AssetTrigger, I can create Asset record again. 
I've turned on debug, and can't find anything particularly useful. 

Thanks.

George

**Comment by georgesf7** [comment]
Here's the debug log
[apex-07L55000007ino6EAA.log.zip](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/512610/apex-07L55000007ino6EAA.log.zip)

**Comment by georgesf7** [comment]
resolved the issue, looks like the "Asset Rollup" metadata was "stuck" even though the rollup record was deleted. So I removed it manually from Setup.

**Comment by afawcett** [comment]
Hmmmm what do you mean by stuck?

**Comment by afawcett** [comment]
Ah i see what you might have ment. I think you deleted the shadow rollup record without the metadata record. Actually the mistake was not deleting the metadata record, if you do this first in future things should be fine.
