### ISSUE TITLE
Issue with Work Orders

### ISSUE THREAD

**Issue by mattsutton1976** [afawcett/declarative-lookup-rollup-summaries#412]
I am trying to roll up from a Work Order but getting an error that the Object Doesn't exist.

I've tried the following API Names for hte Work Order object

WorkOrder
Workorder
WorkOrders
Workorders
Work_Order
Work_order
WorkOrder__c etc

any ideas?

**Comment by afawcett** [comment]
This is because the tool has not been upgraded to the latest API version. I'll flag this as an enhancement.

**Comment by afawcett** [comment]
@mattsutton1976 looks like i overlooked this one in recent release update, this issue should be closed, as the latest release has now been upgraded to latest API (well one that contains WorkOrder). Please try again and let me know. 👍

**Comment by mattsutton1976** [comment]
Hi Andy

I am getting these errors trying deploy!!

Errors

   - classes/dlrs_WorkOrderTest.cls (Line: 5: Column:9) : Entity is not api
   accessible
   - triggers/dlrs_WorkOrderTrigger.trigger (Line: 4: Column:34) : Entity
   is not api accessible


Matthew Sutton <matt@resonantcloud.info>
Director / Solution Architect
Resonant Cloud <http://www.resonantcloud.info>

Tel: 0404 500 225

**Comment by afawcett** [comment]
What version of the tool do you have installed?

**Comment by mattsutton1976** [comment]
Hi

2.7

Matt

Matthew Sutton <matt@resonantcloud.info>
Director / Solution Architect
Resonant Cloud <http://www.resonantcloud.info>

Tel: 0404 500 225
