### ISSUE TITLE
Class.dlrs.RollupService.Updater.updateRecords: line 692, column 1

### ISSUE THREAD

**Issue by aronowt** [afawcett/declarative-lookup-rollup-summaries#413]
I have a validation on account that throws an error if the below is true

> Locked__c = True && 
> NOT(ISCHANGED( One_Time_Support_Counter__c ))&& 
> NOT(ISCHANGED( Last_One_Time_Support_date__c ))

When I create a case sometimes I get the following error and sometimes not. 

> Error: Invalid Data. 
> Review all error messages below to correct your data.
> Apex trigger dlrs_CaseTrigger caused an unexpected exception, contact your administrator: dlrs_CaseTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id _____ ; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You cannot modify this account!: []: Class.dlrs.RollupService.Updater.updateRecords: line 692, column 1

Sometimes I can save without checking the "boxLast_One_Time_Support_date__c", and sometimes even if both fields are changed I still get this error.

Please advice
Thank you

**Comment by afawcett** [comment]
Add a formula field to case that references the locked status of the account and use that field to the criteria of your rollup. This will prevent the rollup tool attempting to update the account for cases that are related to a locked account.

**Comment by afawcett** [comment]
@aronowt My above suggestion should help the tool avoid Account records that cannot be updated by adding to the rollup criteria. If you have tried this and still having an issue let me know and we can re-open this issue. 👍

**Comment by aronowt** [comment]
Thanks for following up,
That suggestion would not work for us because we still want to update the
rollup for locked accounts.

**Comment by afawcett** [comment]
Ah i see. So in this case you need to find a way to adjust the validation around locked records to allow that field to update. Is it a validation rule or trigger that is enforcing the locking?
