### ISSUE TITLE
Getting Trigger has not been deployed when Calculation mode is Scheduled

### ISSUE THREAD

**Issue by agentgill** [afawcett/declarative-lookup-rollup-summaries#414]
Background: Trigger is not required for scheduled jobs

Error: Getting Trigger has not been deployed when Calculation mode is Scheduled & unable to save CMT record

Expected: Behaviour. No error message as Calculation mode is Scheduled and real-time trigger is not required.

Workaround: Deploy trigger, make changes, undeploy trigger

**Comment by afawcett** [comment]
Real time trigger is required for Calculation Mode = Scheduled, as it still needs to log that the parent record needs to be recalculated by the overall RollupJob (scheduled via Apex Classes). Conversely, if you want to use Schedule Calculate button, yes you don't need the trigger, as this is a full recalc. In this case, set the Calculation Mode = Process Builder (i know its a hack). I have an issue raised to make this clearer.
