### ISSUE TITLE
Feature Request - the ability to set schedule dlrs job name

### ISSUE THREAD

**Issue by agentgill** [afawcett/declarative-lookup-rollup-summaries#415]
Feature Request - the ability to set schedule dlrs job name

Ability to set a more meaniful name for schedule jobs instead of rollUp__Xxx

<img width="938" alt="schedule jobs" src="https://cloud.githubusercontent.com/assets/913728/19237535/551471b8-8ef5-11e6-8770-63bd09ff9f26.png">

**Comment by afawcett** [comment]
Yes, this would be an easy change [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupScheduledCalculateController.cls#L78). What name would you want to use the unique rollup name perhaps?

**Comment by agentgill** [comment]
Yes, that would be cool.

**Comment by bethbrains** [comment]
Yes please! I was just having this same thought this morning.

**Comment by afawcett** [comment]
Fixed v2.8.
