### ISSUE TITLE
NPSP contact merge error

### ISSUE THREAD

**Issue by WEC-WCV** [afawcett/declarative-lookup-rollup-summaries#416]
activated a new lookup rollup summary field this afternoon and am now receiving the following errors when using the NPSP Contact Merge functionality (SS below):

![capture_dlrs_error](https://cloud.githubusercontent.com/assets/19214900/19370025/f3d9e124-915d-11e6-8a28-7e9981135fa3.JPG)

**Error: Merge failed. First exception on row 0 with id 0037000001mt7fHAAQ; first error: DELETE_FAILED, dlrs_ContactTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []**

**Error: Failed to merge the contacts. Error: System.DmlException: Merge failed. First exception on row 0 with id 0037000001mt7fHAAQ; first error: DELETE_FAILED, dlrs_ContactTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) : []**

I tried deploying the child trigger both with and without the _Deploy code to support record merging?_ box checked.

These are the versions of DLRS and NPSP we are operating on.
DLRS ver 2.4.2
NPSP ver. 3.82

thank you,
-devan

**Comment by WEC-WCV** [comment]
bumping this issue again since I still haven't found a resolution.

**Comment by afawcett** [comment]
Sorry about this, combined with my lack of knowledge of NPSP and my recent continental home move, community things have a slipped a little last month or so. I've tagged this as a bug and also with a NPSP tag. If you look at [other issues around NPSP](https://github.com/afawcett/declarative-lookup-rollup-summaries/labels/NPSP) you can see there is something funky going on. The good people working on the NPSP have now provided me a repo of the issue/s, so its up to me to drill into it. I hope to get a burst of time on this tool soon, just to let you know i have had a few goes at this and hopefully now i have a dev org with all the code in i can finally make some progress.... Thanks for your patience. 👍

**Comment by WEC-WCV** [comment]
Great, thanks for the follow-up on this. I know that NPSP can cause some issues. I’m still interested in the solution so I will monitor the NPSP-labeled posts on community.

Also please let me know if there’s any info or testing that I could offer to help you out with NPSP issues. My contact info below is fine to reach out. Congrats on the move by the way

Devan Larson • Data Manager
206.631.2617 • cell 206.484.5971 • devan@wecprotects.org

Washington Environmental Council • wecprotects.org
1402 Third Avenue | Suite 1400 | Seattle, WA 98101

**Comment by afawcett** [comment]
Thanks @WEC-WCV thanks for your patience on this.

**Comment by afawcett** [comment]
@WEC-WCV can you just check that you have redeployed your triggers after installing the latest DLRS. Go to the Manage Child Trigger button and click it on the Contact child rollup (anyone will do). Check it shows two triggers on the screen displayed, one for Account and one for Contact. If not, click the Remove button, wait and then when it returns ensure the checkbox to support Merge is ticked and click Deploy again. If you already have a DLRS trigger deployed for Account you should not need to do this. Just want to make sure, since your issue is with merge, that your taking advantage of this fix https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/303

**Comment by WEC-WCV** [comment]
@afawcett looks like i have ver 2.4.2 installed currently so i am installing ver 2.7 right now and will report back with results

**Comment by WEC-WCV** [comment]
@afawcett no errors with contact merge since installing 2.7. looks to be working correctly now as i deploy new triggers

**Comment by afawcett** [comment]
Whoop whoop! Thanks @WEC-WCV
