### ISSUE TITLE
Lookup Rollup Summary Schedule Items not being deleted

### ISSUE THREAD

**Issue by JodieM** [afawcett/declarative-lookup-rollup-summaries#417]
I have a rollup that is acting weird in about 3 ways, but I will start with one and work through it in a step by step fashion. 

It is a new metadata rollup, so being that it was set as scheduled a record is created in the Lookup Rollup Summary object so it can manage which records need to be calculated. 

I have the rollup set to run every evening at 2am (it's running at 1am - that's yet another weird thing - possibly daylight savings related, but it's a minor issue). 

Unfortunately, there are still records in the Lookup Rollup Summary Schedule Items for over a week now. And I just did a full calculate and that didn't remove them. 

Are these Lookup Rollup Summary Schedule Items records meant to be removed after the job runs every night, and calculates the rollup based on those records? 

Some notes:
The Apex Jobs screen is showing that all the batches ran every night at 1am. 
The Relationship criteria is based off a Formula field.

Should these Lookup Rollup Summary Schedule Items be deleted every time the schedule job is run? 
Should these Lookup Rollup Summary Schedule Items be deleted when I run a full calculate? 
How do I delete these records now?

**Comment by JodieM** [comment]
Ah, I see this has been raised in #394 previously. I will try that and report back.

**Comment by afawcett** [comment]
Thanks @JodieM, that issue should give you the info you need to understand and sort this. If not ping me back. 👍
