### ISSUE TITLE
Too many query rows: 50001

### ISSUE THREAD

**Issue by UsernameNotAvailable** [afawcett/declarative-lookup-rollup-summaries#419]
I have a number of Rollup jobs with the Calculation Mode set to "Scheduled" which uses the RollupJob Class.  I get anywhere from 9 - 14 Failures every time it runs.  Is there something I can do to fix this?
Can I break up the schedule into multiple schedules?
Any help is appreciated.
![screen shot 2016-10-21 at 1 47 25 pm](https://cloud.githubusercontent.com/assets/10977277/19607147/dab89724-9795-11e6-9e3e-fe4858034a76.png)

**Comment by afawcett** [comment]
@UsernameNotAvailable sorry for the delay, i have been moving home / continents .... take a look at [this blog](https://andyinthecloud.com/2014/02/09/new-release-spring14-declarative-rollup-summary-tool/) relating to some custom settings that can adjust the chunk sizes the jobs take on. See section at the bottom Dealing with the 50k Aggregate Query Limit. I'll close out this issue, but if you still have issues, feel free to add more comments and we can re-open. Good luck! 👍
