### ISSUE TITLE
Scheduled requiring code deployed

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#420]
I am getting the below error when I attempt to make a Scheduled rol-lup Active.

![scheduled error](https://cloud.githubusercontent.com/assets/11430243/19933979/8b820906-a0eb-11e6-91cf-5e3e12c6eb90.jpg)

These are the errors when I attempt to deploy so I am stuck. I would love to be able to have these be active, can someone help me? Thanks.

**Errors**
classes/dlrs_AcctSeed_TransactionTest.cls (Line: null: Column:null) : Not available for deploy for this organization
classes/dlrs_AcctSeed_TransactionTest.cls-meta.xml (Line: null: Column:null) : Not available for deploy for this organization
triggers/dlrs_AcctSeed_TransactionTrigger.trigger-meta.xml (Line: null: Column:null) : Not available for deploy for this organization
triggers/dlrs_AcctSeed_TransactionTrigger.trigger (Line: null: Column:null) : Not available for deploy for this organization

**Comment by girlyITgeek** [comment]
My issue is resolved. Below was the culprit.

![image](https://cloud.githubusercontent.com/assets/11430243/20017894/f5618a7a-a29b-11e6-9406-ebffd36c8107.png)

**Comment by afawcett** [comment]
Thanks for sharing! 👍
