### ISSUE TITLE
Calculate Job Id not clearing from DLRS when complete

### ISSUE THREAD

**Issue by mjhill86** [afawcett/declarative-lookup-rollup-summaries#421]
I frequently use the DLRS tool for clients that I am implementing SF for. More recently, I've been noticing that when the calculate job runs, once it's finished, or failed, the "Calculate Job Id" is not cleared from the DLRS record. When the job is not cleared, the calculate function cannot be run again until the job ID is manually cleared by a user. 

Is there a work around that I can implement to track how often this is happening? During the research I have done with my colleagues, we've found the following:
1. Sometimes a job will be successful, but the Calculate Job Id will not be cleared. So, this isn't strictly related to jobs that have errored. 
2. There isn't an indicator, without manually checking the DLRS record and adding the Calculate Job Id to the page layout/listview, that denotes the Calculate Job Id was not properly cleared. 

Note: I'm using Lookup Rollup Summaries, not the Custom MetaData Lookup Rollup Summaries.

**Comment by afawcett** [comment]
There was an regression in some builds around this, can you check your on the latest release please?

**Comment by afawcett** [comment]
@mjhill86 As i said above, this "should" be ok in later releases, i recall fixing a regression in this area. Anyway let me know if upgrading didn't resolve the issue and we can re-open this issue for sure. 👍
