### ISSUE TITLE
Issue writing correct SOQL query

### ISSUE THREAD

**Issue by meggall** [afawcett/declarative-lookup-rollup-summaries#423]
I am new to SOQL, and am having difficulty writing a lookup summary that is only running on the records I want.  I am trying to do a rollup summary on the number of attachments on an opportunity.  

Here are my parameters for my summary:
Lookup Relationship:
Parent Object: Opportunity
Child Object: Attachment
Relationship Field: ParentID
Relationship Criteria: CreatedDate = this_year
Relationship Criteria Fields: Created Date

Rollup Details:
Field to Aggregate: SystemModstamp
Aggregate Operation: Count
Aggregate Result Field: Attachments__c (a custom number field on my opportunity)
Calculation Mode: Scheduled
Calculation Sharing Mode: System

In theory, I want this to only look at opportunities that were created this year, and eventually that are only of a specific record type, but I'm not familiar enough with SOQL to figure out how to make this work.  Can someone walk me through what query I should be using on the summary, or in the schedule calculate to make this only evaluate those records?

Thanks!

**Comment by meggall** [comment]
I also was having issues with hitting too many SOQL queries, but I seem to have solved that by reducing my job scope size to 10, but this is creating very long run times, and I also turned off all of my validation rules.  If I am running the lookup summary as a scheduled item, and my profile is excluded from the validation rules, this shouldn't be necessary, correct?

**Comment by meggall** [comment]
Figured it out!

**Comment by afawcett** [comment]
Thats great @meggall, can you share what you did?

**Comment by meggall** [comment]
@afawcett honestly, it was complete and total user error, I was -way- over-complicating it :D  I was trying to write the actual query in the query box, not realizing it was literally just looking for the criteria, not the whole thing. :/ :D :/

Once I had the restriction on it, that also reduced the query size, and it was just fine.  Unfortunately, it ended up running against our other trigger, so I'm not currently able to use it, but I figured it out at least! :D

**Comment by afawcett** [comment]
Ah no worries, thanks for sharing though.
