### ISSUE TITLE
Opp Task Count real time not working

### ISSUE THREAD

**Issue by patvachon77** [afawcett/declarative-lookup-rollup-summaries#424]
As per subject.

![2016-11-03_19-41-10](https://cloud.githubusercontent.com/assets/10502786/19990462/52262e7a-a204-11e6-847c-be00dc34cb2f.png)

**Comment by afawcett** [comment]
This appears to work for me, i am running release v2.5.

<img width="1186" alt="screen shot 2016-12-04 at 16 15 29" src="https://cloud.githubusercontent.com/assets/1167760/20870428/edf215e4-ba3c-11e6-9ae1-41a6929e28c2.png">

**Comment by afawcett** [comment]
@patvachon77 As i said above this appears to work fine in v2.5, let me know how it goes. If its still and issue we can for sure re-open this issue. 👍
