### ISSUE TITLE
Error while trying to create a rollup on Case with Case Comment

### ISSUE THREAD

**Issue by JJEMEGA** [afawcett/declarative-lookup-rollup-summaries#425]
Hi,
I get an error while trying to create a rollup on Case for CaseComments.

While clicking manage Child Trigger, I get the following error:
dlrs_CaseCommentTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, missing required field: [ParentId]: [ParentId] Class.dlrs.RollupService.testHandler: line 250, column 1 Class.dlrs_CaseCommentTest.testTrigger: line 11, column 1
I guess that there is no case but the problem doesn't happen on other objects like OppotunoityLineItems.

Could you please help on this?

thanks
Jean

**Comment by afawcett** [comment]
Ok so.... 

**Good news...** your immediate issue is solved by adding the following custom test code into the **Test Code** field on the rollup. The reason why this needs doing is described here.

~~~
Case testCase = new Case();
insert testCase;
CaseComment testComment = new CaseComment();
testComment.parentId = testCase.Id;
insert testComment;
~~~

**Bad news...** There is a platform issue preventing this going further. As we now get a new error deploying the trigger.  _'Cannot locate Apex Type for ID: 00ab000002AooWsAAJ Class.dlrs.RollupService.triggerHandler_' 

**Good news...** Per discussion at this [issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/17), i think we have a workaround.... 👍 

I have linked this issue with the one above, so we can close this one, [you can watch / follow this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/17) to look for an update on this.
