### ISSUE TITLE
Calculate Taking Too Long

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#427]
When I calculate a rollup it is taking days to complete. Can you please tell me how I can resolve this? Thank you.

![image](https://cloud.githubusercontent.com/assets/11430243/20156836/155e7dc6-a6a0-11e6-8945-553a18041c21.png)

**Comment by afawcett** [comment]
Some thoughts....
- Is this the Schedule Calculate page your using to schedule full recalcs? If so, does the incremental schedule mode work for you better? Providing you don't have any time dependent formula's in your criteria or cross object formulas, you could probably move to scheduling the RollupJob and then deploy the child trigger. This will record realtime which parent records (and only those) that need recalculating and dramatically reduce the time taken. See blogs on this (links on readme) for more.
- If you still need to use the full recalculate via the Schedule Calculate page, then try putting in some criteria that focuses the process on records your interested in, maybe only those created in the last year or two years? Or of a certain status? You should also check that the criteria fields are indexed (you can see this until the objects setup object page). 
- Check the Custom Settings for the tool, you can increase the chunk size which will reduce the number of batches needed to process the job. As general rule of thumb, less batches, the quicker the job runs. The default is 100 parent records per batch., so i assume your processing 766,200 parent records. You can go up to 2000 parent records. The maximum is an average of no more than 50k related child records processed per chunk of parent records. So if you go with 500 parent records you will reduce the number of batches need by a lot, but must ensure that at any time a chunk of 500 parents does not collectively read over 50k children. So knowing your max child records per parent will certainly help you calibrate your custom settings. Read more about this in the  [known issues section of the readme](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues).

**Comment by afawcett** [comment]
@girlyITgeek Let me know if the above helped or not. If not, we can re-open this issue and discuss further. Thanks Andy. 👍
