### ISSUE TITLE
Errors when installing: Permission Set must be associated with a user license

### ISSUE THREAD

**Issue by aheidrich** [afawcett/declarative-lookup-rollup-summaries#43]
Here are the errors I get upon installing:

Failures:
permissionsets/LookupRollupSummariesFull.permissionset(LookupRollupSummariesFull):Permission set must be associated to a user license
permissionsets/LookupRollupSummariesReadOnly.permissionset(LookupRollupSummariesReadOnly):Permission set must be associated to a user license

Will these impact the usability of the app, and what am I doing wrong?

**Comment by afawcett** [comment]
Fixed.
