### ISSUE TITLE
Can't Update to New Version

### ISSUE THREAD

**Issue by JesssicaHanna** [afawcett/declarative-lookup-rollup-summaries#430]
Hi,

I am trying to update from Version 2.2 to the new version and it errors out on me, I am trying to do this in my Sandbox environment. I am not sure if it's because my version is so far behind. I was wondering if I should just uninstall the app and reinstall or will that wipe out all of my roll-ups that are built out?

Thanks,
Jessie

**Comment by afawcett** [comment]
@JesssicaHanna not sure if you figured this out, but you should be able to simply upgrade the package by clicking on the latest package install link (see readme), your rollups will be retained between upgrades no problem. 👍
