### ISSUE TITLE
Error: Salesforce Metadata API connection failure, click the link below to configure.

### ISSUE THREAD

**Issue by StephanieKing** [afawcett/declarative-lookup-rollup-summaries#431]
So I follow the link below, and I try the button to reconfigure: Then it says "Error:
This Remote Site Name already exists or has been previously used. Please choose a different name."
So I try to do it "manually" by following the "Remote Site Setting" link and it takes me to a mostly-blank salesforce articles page with this message: "Invalid language code. Check that the language is included in your Knowledge language settings."
Additional Screenshots attached.
What has happened / how can I fix my Metadata API connection?

![2016-11-16_1518](https://cloud.githubusercontent.com/assets/17727591/20366535/427a8f36-ac11-11e6-8cf9-d33d0c801a2d.png)
![2016-11-16_1517](https://cloud.githubusercontent.com/assets/17727591/20366536/427eb57a-ac11-11e6-8ed3-ed0855686e73.png)
![2016-11-16_1515](https://cloud.githubusercontent.com/assets/17727591/20366537/427fb5d8-ac11-11e6-8536-215a0382836a.png)

**Comment by LindsayAgor** [comment]
Go to setup

Search for Remote Site Setting

Delete the setting with DLRS

Then you will be able to click the link to configure

**Comment by afawcett** [comment]
Thanks you @LindsayAgor for contributing to this issue, very much appreciated! 👍 

@StephanieKing did this help?

**Comment by afawcett** [comment]
@StephanieKing let us know if this helped or not. If not, we can keep the conversation going here. 👍

**Comment by koldsnapz** [comment]
I can add for myself, I am having the same problem. Though if I go to Remote Site Setting, I don't see any DLRS setting listed to delete so I am still stuck.

**Comment by StephanieKing** [comment]
@koldsnapz did you update to the latest version? I had to update my orgs to v 2.6 for it to go away; now I see there is actually a v2.7...

**Comment by KOBI1069** [comment]
Hi afawcett,
I have the same issue. Whenever I want to "Manage the Child Trigger" I receive the Error Code "Salesforce Metadata API connection failure, click the link below to configure." I follow the link to the welcome page, set "Create my remote site setting" (after deleting the already existing one), and get a positive response. However, starting all over again from the top, I keep receiving the same error message.

I was on v2.7, and went down to 2.6. The same error comes up on both versions.

Help would be much appreciated.

Best
Kobi

**Comment by afawcett** [comment]
Can you check the README file for the known issues around this problem and also include a screenshot of the problem please.

**Comment by elmord73** [comment]
Hello @afawcett .
Same issue here. Version 2.7. Remote site configured correctly.

When try to "Manage Child Trigger" got the error.
Tried everything I could but same error. Didn't find anything on the Readme.
Appreciate your help!

![capture](https://cloud.githubusercontent.com/assets/25880057/23102258/d3d37096-f6ae-11e6-9b22-b449875030e4.JPG)
