### ISSUE TITLE
Wiki Links Out of Date

### ISSUE THREAD

**Issue by DouglasCAyers** [afawcett/declarative-lookup-rollup-summaries#434]
On the [wiki page](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki) of this repo, the installation package links are out-dated, v2.3 instead of v2.5

From the readme, the latest release is, https://login.salesforce.com/packaging/installPackage.apexp?p0=04tb0000000MXVO

**Comment by afawcett** [comment]
Thanks, sorted this, with a link to the package list in the readme.
