### ISSUE TITLE
Aggregate field on the Child or compare fields Parent Vs Child

### ISSUE THREAD

**Issue by AJNMN** [afawcett/declarative-lookup-rollup-summaries#436]
Hi, I'm building fields to count the number of calls made to a lead after it has been added to a campaign.

I have the dates added pulled to the lead for 1st and last campaign

therefore I want Number of Call type tasks where the activity date is greater than this 1st Campaign Added Date.

trouble is, the Campaign date is on the Lead, Activity date on the Task so I can't compare.

I can't pull the Campaign date to the Activity, as there's no suitable relationship field on lead.
I can't pull Activity date to the lead as there is (should be) more than one.

So I either need a way to write the Campaign date to the Task/Activity (Child) (so I can compare them both as Child Fields)

Or  (preferably) to be able to reference in Relationship Criteria both Parent & Child fields

is this achievable?

**Comment by afawcett** [comment]
Have you considered trying to populate the fields you need using Workflow Field Updates and/or Process Builder?

**Comment by afawcett** [comment]
@AJNMN let me know how my suggestion worked out for you? Or if you want to keep discussing? Happy to re-open this issue what ever. 👍

**Comment by AJNMN** [comment]
Hi, I did try that initially but the fields aren't available to push through to the activity.

**Comment by afawcett** [comment]
Ah ok, so yeah if the relationship does not exist, i'm afraid a pure use of this tool will not be possible. You will have to write some code or process builder magic to maintain the relationship you need. Sorry.
