### ISSUE TITLE
AccountContactRelation.  Deploy Trigger. Entity is not api accessible

### ISSUE THREAD

**Issue by jrosenbloom613** [afawcett/declarative-lookup-rollup-summaries#438]
Hi All,

I'm trying to rollup from AccountContactRelation to Account, and getting an "entity is not api accessible" error https://goo.gl/gAh5uO .  It seems from here https://goo.gl/kk1Z0S that the object is from API version 37 and from here https://goo.gl/tQIR9S that DLRS is running on version 37.  What am I missing?

Thanks!!!

**Comment by afawcett** [comment]
So this looks like one of those objects that does not support triggers. You will have to try to use Calculatiob Mode as Process Builder. In this case try to use Process Builder itself to run the roll up (see docs in readme links) or use the Schedule Calculate button to schedule a full recalc. These are the only ways to work with objects that don't support triggers.

**Comment by tet3** [comment]
AccountContactRelation does support triggers as of API 38.0. This is happening due to the same bug as in #481 - the API version being used on the triggers and test classes is hard-coded at 32.0.

**Comment by afawcett** [comment]
Thanks @tet3, i'll take a look.

**Comment by afawcett** [comment]
v2.9
