### ISSUE TITLE
Emails attached from Outlook to Salesforce (using my email to Salesforce Link) is not rolled Up

### ISSUE THREAD

**Issue by preetishetty25** [afawcett/declarative-lookup-rollup-summaries#439]
I have created a roll up Field Last activity for Zycus in the Accounts object. This field is a date field. Basically we have divided activities in two categories valid and invalid. This field rolls up the latest valid activity date. However from past 15 - 20 days this field does not count the emails that are attached from Outlook to Salesforce from the my email to salesforce link. Please check the issue asap.

**Comment by afawcett** [comment]
Hi @preetishetty25, i am afraid i am not familar with that functionality in Salesforce, nor do i have Outlook / Exchange server to test it. Is their anything else difference between the emails that are and are not getting counted? Does it count if you manually run the rollup via the Calculate button on the rollup? Also what happens if you use the All Rows field on the rollup?

**Comment by preetishetty25** [comment]
Hi @afawcett This happens only with emails that are attached from Outlook. It doesnt count even if I manually run the roll up.

**Comment by wes1278** [comment]
@preetishetty25 are you rolling up activity or email message? Which outlook connector are you using?

**Comment by preetishetty25** [comment]
Both email message and activities appear in the object "activities". So I am rolling up both email messages and activities. This was not a problem before but suddenly emails which are attached from Outlook using "My emails to Salesforce link" are not being rolled up.

I am attaching the screenshot for your reference.

![activity history](https://cloud.githubusercontent.com/assets/24654132/21842189/a4f01b1a-d80b-11e6-81f7-4c090786305f.png)


![email to sf](https://cloud.githubusercontent.com/assets/24654132/21841765/bccf7598-d809-11e6-82ce-1d13bee83d47.png)
![last actv](https://cloud.githubusercontent.com/assets/24654132/21842130/698649be-d80b-11e6-9322-4815e08fb6f5.png)

**Comment by preetishetty25** [comment]
any update on this @afawcett

**Comment by afawcett** [comment]
I am wondering if the Apex Trigger is not being run by the platform when the Outlook integration is used? Not sure why it would not tbh. But if you can enable Apex Debug logs and do some testing that might help confirm this either way.

**Comment by afawcett** [comment]
@preetishetty25 Let me know if this is still an issue?
