### ISSUE TITLE
Calculate Job fails. Error:  First error: unexpected token: /

### ISSUE THREAD

**Issue by FeliciaM** [afawcett/declarative-lookup-rollup-summaries#440]
We have some scheduled jobs that keep failing so we're trying to delete the jobs from Lookup Rollup Calculate Jobs and do a manual calculation using the Calculate button. The job fails with this message: **First error: unexpected token: /**

Not sure where to start troubleshooting. Ideas?

Thanks,
Felicia

**Comment by afawcett** [comment]
That is a tricky one, not very informative is it. I wonder if it relates to relationship criteria on one or more rules? Do these all look valid?

**Comment by afawcett** [comment]
@FeliciaM let me know if you still need help with this?
