### ISSUE TITLE
Salesforce Metadata API connection failure, click the link below to configure.

### ISSUE THREAD

**Issue by hoytks** [afawcett/declarative-lookup-rollup-summaries#441]
I'm getting the "Salesforce Metadata API connection failure, click the link below to configure." error after installing version 2.5 into an Unlimited License org.  I have tried creating the Remote Site via the tool as well as manually with no luck.

I read some of the posts about changing the API Access for the installed package, but not sure that is possible anymore.  I'm logged in as a Sys Admin.

**Comment by afawcett** [comment]
The API Access should still be present on the Package under Installed Packages under Setup. Also have you seen the [Known Issues link here](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues) for thoughts on Session configuration being the source of issues?

**Comment by afawcett** [comment]
@hoytks let me know if you still need help with this?

**Comment by dev-oh** [comment]
I had Declarative Rollups successfully installed and running but after activating critical update "Remove Instance Names From URLs for Visualforce, Community Builder, Site.com Studio, and Content Files" I started getting this error. Deactivating the update fixed the problem. This update isn't required until 3/16/2019 so hopefully a fix is developed by then.

**Comment by afawcett** [comment]
Under @dev-oh , see this issue in the meantime https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/372
