### ISSUE TITLE
Nothing happen after successful installed and activate

### ISSUE THREAD

**Issue by new-sf-user** [afawcett/declarative-lookup-rollup-summaries#442]
I am not a developer. =)

I followed the steps to install the tool. I was able to installed successfully (no error message). However, nothing happen after I hit the "calculate" button. I don't know what's going on. Can anyone help?

Here is what I set up:
<img width="1167" alt="screen shot 2016-12-21 at 12 48 39 pm" src="https://cloud.githubusercontent.com/assets/24704746/21405712/76686210-c77c-11e6-85d4-842f8059a113.png">

Here is the code for the Child Trigger:
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_AccountTrigger on Account
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    dlrs.RollupService.triggerHandler();
}
 	 
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_AccountTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_AccountTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Account());
    }
}
 	 
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_OrderTrigger on Order
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    dlrs.RollupService.triggerHandler();
}
 	 
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_OrderTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_OrderTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Order());
    }
}

**Comment by afawcett** [comment]
Your 'Relationship Field' is wrong. What you must put in this field is the API name of a field on the Order object that points (looks up) to the Account object. According to the [Order object documentation](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_order.htm), this is the AccountId field. So put AccountId in the 'Relationship Field' and try again. 👍

**Comment by new-sf-user** [comment]
It works!! Thank you so much!!!

**Comment by afawcett** [comment]
np 👍
