### ISSUE TITLE
Cannot Install Application

### ISSUE THREAD

**Issue by hlong90** [afawcett/declarative-lookup-rollup-summaries#443]
Getting the following message when attempting to install in sandbox:

"The AppExchange package has been deprecated and can no longer be installed. Please try installing a newer version, or contact the package owner directly to resolve."

Am I using an outdated version?

Here's the link:

https://appexchange.salesforce.com/listingDetail?listingId=a0N3000000B45gWEAR

**Comment by afawcett** [comment]
Yes, please see the [README file for latest package link](https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history).
