### ISSUE TITLE
Active: Apex Trigger dlrs_pse_MilestoneTrigger has not been deployed. Click Manage Child Trigger and try again.

### ISSUE THREAD

**Issue by hlong90** [afawcett/declarative-lookup-rollup-summaries#444]
I have installed the latest version of dlrs into a sandbox. I am trying to save a new dlrs that I have created. When I hit save, I get this error message:

Active: Apex Trigger dlrs_pse_MilestoneTrigger has not been deployed. Click Manage Child Trigger and try again.

How do I fix this?

Note that Milestone is an object part of a managed package.

**Comment by afawcett** [comment]
Pretty much as the error message says, click the Manage Child Trigger button to deploy an Apex Trigger that will ensure the rollup is calculated. This is needed for Calculation Mode's Realtime or Scheduled. Hope this helps! We can re-open if not. 👍
