### ISSUE TITLE
Rollup Error on Cloning record

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#445]
I am trying to clone a quote detail and quote line and am getting the attached errror. Can you point me in the direction to rectify this error? I am trying to clone a detail record and 69 quote lines.
![quoteerror](https://cloud.githubusercontent.com/assets/9218441/21778376/3445c8c4-d671-11e6-829a-b9aa269679ca.png)

**Comment by afawcett** [comment]
Hi @tamilust, per the message shown you need to review the need for custom indexes for some of your fields in your org. Start with using the developer console to grab some debug logs, specifically the SOQL's being used. Then review the criteria's being used. Then check that the fields in the criteria have custom indexes (you can see this when viewing each objects field list, it is a column in the field list). There is quite a bit more to tuning your criteria (likely expressed in your rollup criteria) but these are the general steps. Per the [known issues of this tool](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues), once you get to large volumes, indexes must be considered.

**Comment by afawcett** [comment]
Salesforce support can also help you asses your orgs needs, the queries and recommend custom indexes to be enabled. Only salesforce support can enable these.

**Comment by tamilust** [comment]
@afawcett thanks for the info. I am in the process of working with SF to get custom indexing on our fields and they are asking for the exact SOQL queries used. Is there a way to get the exact SOQL query from the DLRS jobs?

**Comment by afawcett** [comment]
Yes, you can get this from the Salesforce Debug Logs, Salesforce support should be able to help with this, if your new to this. See Setup > Debug Logs to set this up.
