### ISSUE TITLE
Performance issues when converting leads

### ISSUE THREAD

**Issue by etech0** [afawcett/declarative-lookup-rollup-summaries#446]
Hi! First of all thanks for a great plugin.

I've been noticing performance issues when converting leads - it can take up to a minute sometimes, to create the necessary Account/Contact/Opportunity.

I'm not so experienced in debugging, but following instructions here (https://developer.salesforce.com/page/Troubleshooting_Apex_Performance_Problems) I was able to see a timeline of what happens when I converted one lead, and it looks like DLRS might be involved in the time delay.

Here's a screenshot of the Execution Tree: http://take.ms/zdD0s

When I click on the longest piece of the timeline (it falls under apex code), I see in the Execution Stack DLRS mentioned again: http://take.ms/7uXK7

Not sure  what's going on here, but I'm hoping you can help me figure this out!

Thanks!

**Comment by afawcett** [comment]
Your welcome @etech0 . The tool has great power, and with that, great opportunity to create a lot of work. How many rollups do you have defined in the system? Are you using criteria? Is that criteria using indexed fields?

**Comment by etech0** [comment]
Thanks for answering! I currently have 7 rollups, all using Opportunity as
the child object. The funny thing is that I noticed the perfomance issue in
my sandbox even before importing my rollups. Does that make any sense?

Most of them filter by the StageName field, which doesn't seem to be
indexed (unless I'm missing something). Other than that, only one of the
rollups uses a field that's not indexed.

When I scroll through debug logs, I see the line "13:06:33.772
(3824452305)|ENTERING_MANAGED_PKG|dlrs" repeated many many times (with
different times and numbers). What could that mean?

**Comment by afawcett** [comment]
The (3824452305)|ENTERING_MANAGED_PKG|dlrs just means its executing the code, its an over the top logging for managed code in packages. If you noticed it before deploying the rollups its unlikely to be the tool, it will execute the DLRS triggers but they get out of dodge immediately if there is no rollups defined. You can achieve the same by toggling the Active checkbox once they are in place. So thats a good way of testing with and without.

**Comment by afawcett** [comment]
@etech0 Let me know if you still need help with this?

**Comment by etech0** [comment]
Yes, it seems like I do! I have a couple of Process Builders that run every
time an Opportunity is edited, and it seems like they don't play nicely
with the rollups, and it makes it take longer to save records. Do you have
any idea how to fix this?

Thanks!

**Comment by afawcett** [comment]
Its hard to help without much knowledge of your Process Builder rules. I would recommend you disable different rollups and/or process builder rules in turn to determine which is causing the problem. Also review the criteria used in both cases both criteria that triggers the rules/process builder and the records they process. Although this topic https://help.salesforce.com/articleView?id=code_dev_console_solving_problems_using_system_log.htm&type=0 relates to VF pages, it actually applies to any process you execute. The Execution Overvview tab will be useful to you to reviewing where processing is occurring as you enable/disable rollups/pb rules to triage.

**Comment by etech0** [comment]
Thanks! The interesting thing is that even when I disable all my rollups,
the DLRS trigger seems to run a whole bunch of times when editing/saving
records. Does that make any sense?

**Comment by afawcett** [comment]
Hi @etech0, yes it does, but it should not be doing anything, just going in and out of the dlrs code without doing any queries, you should be able to confirm this in the debug logs.
