### ISSUE TITLE
getting hundreds of line of: ENTERING_MANAGED_PKG|dlrs

### ISSUE THREAD

**Issue by leef1030** [afawcett/declarative-lookup-rollup-summaries#447]
This is part of the APEX debug, but I can't turn it off because I need to see the apex debug info. what should I do to turn it off only for dlrs?

**Comment by afawcett** [comment]
You will see this message for any managed package code that gets executed. I know its really painful, but i do not know of any workaround, other than downloading the debug log and running some kind of script to remove it. You can try perhaps to use the filter feature in the developer console to look for what you need as well. You can also up vote this [idea](https://success.salesforce.com/ideaView?id=08730000000kzpbAAA)
