### ISSUE TITLE
Custom Metadata Pilot: manual Calculate succeeds, Lookup Rollup Calculate Job record remains

### ISSUE THREAD

**Issue by jclark-dot-org** [afawcett/declarative-lookup-rollup-summaries#449]
Fresh install of DLRS 2.7.  Created a handful of Metadata-based rollups, set for Automatic calculation; no issues.   I decided to run a couple of them manually (via "Calculate" button on the "Manage Lookup Rollup Summaries - Custom Metadata Pilot" as I (mistakenly) thought something was out of sync.  I can see in the Apex Jobs screen in setup that the jobs ran and finished (status="Completed") almost immediately (not much data to rollup).  However, the records remain in the Lookup Rollup Calculate Job table.

**Comment by tbrownbts** [comment]
I believe this same thing is happening to me. Every Job I scheudle gets stuck in the Lookup Rollup Calculate Job table after it completes.  Which I then must go and delete.  Also a fresh install  DLRS 2.7.

**Comment by StephanieKing** [comment]
Yes, I am experiencing this as well. The job runs once manually, successfully, but stays stuck in the LRCJ tab indefinitely. Real Time and Scheduled jobs just are not working...

**Comment by jonlarosa** [comment]
I think this is the same issue: https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/460

**Comment by GregRohman** [comment]
Fresh install of 2.7 into Unlimited Edition, and I am also seeing this behavior.

-Greg

**Comment by afawcett** [comment]
Ok guys, i'll get on it. I'll close this as duplicate of https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/460
