### ISSUE TITLE
dlrs.RollupCalculateJob' for job id '7071500003SSZzg' : dlrs:Too many query rows: 50001

### ISSUE THREAD

**Issue by chiruganta** [afawcett/declarative-lookup-rollup-summaries#451]
We are getting below exception when schedule job runs. Is their any way to fix this?

Subject: Developer script exception from testCompany : 'dlrs.RollupCalculateJob' for job id '7071500003SSZzg' : dlrs:Too many query rows: 50001
    
    Apex script unhandled exception by user/organization: 00515000006OqvV/00D15000000EfQe
    
    Failed to process batch for class 'dlrs.RollupCalculateJob' for job id '7071500003SSZzg'
    
    caused by: System.LimitException: dlrs:Too many query rows: 50001
    
    Class.dlrs.LREngine.QueryExecutor.query: line 631, column 1
    Class.dlrs.LREngine.WithoutSharingQueryExecutor.query: line 649, column 1
    Class.dlrs.LREngine.rollUp: line 229, column 1
    Class.dlrs.LREngine.rollUp: line 108, column 1
    Class.dlrs.RollupService.updateMasterRollups: line 482, column 1
    Class.dlrs.RollupCalculateJob.execute: line 56, column 1

**Comment by afawcett** [comment]
Yes, please review the [Documentation on the README file](https://github.com/afawcett/declarative-lookup-rollup-summaries#documentation), there are some custom settings you can tweak to calibrate how much work / records each chunk of the job takes in. You can go direct to the blog (scroll to bottom) [here](https://andyinthecloud.com/2014/02/09/new-release-spring14-declarative-rollup-summary-tool/).
