### ISSUE TITLE
Error in adding a APEX child trigger

### ISSUE THREAD

**Issue by nbellet** [afawcett/declarative-lookup-rollup-summaries#452]
I am new to using the roll up tool I was prompted to add an apex trigger using the tool provided my the roll-up tool however I am getting this error and am not sure what it means.

![new picture 15](https://cloud.githubusercontent.com/assets/25371454/22342724/3490060a-e3aa-11e6-9574-c643796a93ed.gif)

**Comment by afawcett** [comment]
You may need a small snippet of Apex code to put in the Test Code field, see here for an explanation as to [why](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage).
