### ISSUE TITLE
how to use filter rules on scheduled jobs

### ISSUE THREAD

**Issue by prichey12** [afawcett/declarative-lookup-rollup-summaries#453]
Hi

I have tried various examples of how to correctly write filter rules for inclusion when executing a scheduled job. I am using the Contact object that is rolling up line items from a custom object. The utility is properly working and summarizing all values but I'd like to filter by creation data for the line items allowing me to summarize roll up based on calendar year. This is the system I am using. Is this correct? While it executes properly it doesn't seem to update the values.

WHERE CALENDAR_YEAR(pymt__Date__c) = 2015

Paul

**Comment by afawcett** [comment]
That does look good. However be aware that the criteria your apply to is your parent records not your child objects. If you are aware of this, then... If you enable the debug log you can capture the SOQL the tool uses in the batch apex start job phase (one of 3 debug logs that will be generated). Check that that makes sense and that in the Apex Jobs page you can see it is selected some records to process.

**Comment by afawcett** [comment]
@prichey12 Let me know if you still need help with this?
