### ISSUE TITLE
Checkbox Rollup

### ISSUE THREAD

**Issue by thenryST** [afawcett/declarative-lookup-rollup-summaries#457]
What's the best way to rollup a checkbox from a Contact to an Account?

We have a checkbox that if its checked on any Contact on an Account we want a related checkbox on the Account to be True. And vice versa, if the last contact on the Account has the checkbox unchecked then the check on the Account should be unchecked. 
I was unsure which aggregate operation to use, any suggestions?

**Comment by afawcett** [comment]
Yep, you can use the Last or First aggregate operations for this.

**Comment by wes1278** [comment]
@thenryST It sounds like you might be better served with a count rollup of the number of contacts that have the checkbox checked. But maybe I'm mis-reading your question. But, if I'm understanding you correctly, you could then create a simple formula field on Account that looks at the count and outputs a checkbox state. ie
`=IF(Count_Field__c >0, true,false)`

The reason for that is that it sounds like you want to know if any contact has it checked. If any of them have it checked, you want it to be true on the account. And, if ALL contacts have it unchecked, the account field should be unchecked.

Good luck!

**Comment by thenryST** [comment]
Thanks for the tip. I think that might solve the issue

**Comment by afawcett** [comment]
Excellent, let us know if not. Thanks @wes1278 ! 👍

**Comment by tnafziger** [comment]
We have a very similar scenario that I am trying to use LAST for, but it doesn't seem to be working.

We have a gift subscription checkbox on an individual account (the subscriber) that we want checked if the most recent subscription (that has a look up field to an individual contact) is checked. Here's what I tried:

**Field to Aggregate** is set to the checkbox field (gift or not?) on the subscription object, **Field to Order By** is set to the end date for the subscription which so it knows which is "Last" and  **Aggregate Operation** is set to Last.

@afawcett you suggested that Last would work in this scenario, so I'm wondering if you might have insights.

**Comment by tnafziger** [comment]
For anyone who might come across this issue in the future: the problem was that the field I was trying to aggregate (**Field to Aggregate**) was a formula (outputting a checkbox) and DLRS is not, apparently, able to aggregate formula fields.

**Comment by wes1278** [comment]
@tnafziger, dlrs can rollup formulas if all the fields that should trigger a recalculation

**Comment by wes1278** [comment]
Sorry for the close and reopen. I'm victim of github on a cell phone.

Like I was saying, DLRS can rollup formulas that are not cross object quite easily. @afawcett has a blog about a more complex way to handle cross object formulas being rolled up successfully.

That being said, all you have to do is add all the fields that influence/affect the checkbox formula you created to the list of fields in the rollup definition to trigger a dlrs update if those dependent fields are updated.

**Comment by Blairadams14** [comment]
What do I select if a field is checked on the child account and I want it to be checked on the parent account? We have a training object and want to summarize the training check boxes on the account. It doesnt matter if its checked once or 3 times, it just needs to show its completed.
