### ISSUE TITLE
Schedule Calculation only does a default

### ISSUE THREAD

**Issue by girgentil** [afawcett/declarative-lookup-rollup-summaries#458]
Hi, I cannot seem to change the Schedule Calculation. It always goes back to 2am default
I would like to set it for everyhour. 
Thanks

**Comment by afawcett** [comment]
Can you confirm what version you are on and what steps you are performing to schedule? Some screenshots would be useful as well please. Thanks! 👍

**Comment by afawcett** [comment]
@girgentil Let me know if you still need help on this?
