### ISSUE TITLE
Issue with Checkbox Formulas

### ISSUE THREAD

**Issue by jmfarber** [afawcett/declarative-lookup-rollup-summaries#459]
Not sure if this is a bug or not but I was unable to get the real time trigger to work with Checkbox Formulas.

We created a checkbox formula on the child object.  Set up the Where clause to look for the checkbox to be True and then basically counted the records using a Stage field.  It would work in all options except for real time,  We did deploy the class, trigger and test all fine no issues, so I'm not sure what the problem was.  We changed the Checkbox formula to a number formula with an if statement giving the value of 1 or 0 and then summed the values into the parent object and it worked fine.  Seems like a bug but I'm not a coder.

**Comment by afawcett** [comment]
The tool does not see changes in formula field values (platform behaviour), unless you list the fields referenced by the formula in the Relationship Criteria Fields fields. Take a look at the known issues in the [README](https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues) and thoughts on a workaround. I am not sure why it works for number formulas, maybe your Where criteria was not quite correct for the boolean case? Either way review the [docs](https://github.com/afawcett/declarative-lookup-rollup-summaries#documentation) (also see README and doc section) for thoughts on formulas and known issues.

**Comment by afawcett** [comment]
@jmfarber Let me know if your good or not on this.
