### ISSUE TITLE
Lookup Rollup Calculate Job records are not being deleted even after the Calculate Job finishes

### ISSUE THREAD

**Issue by jonlarosa** [afawcett/declarative-lookup-rollup-summaries#460]
The calculation jobs are running fine: no errors in the apex jobs list, rollup results look good, etc., but the records don't get deleted from the Lookup Rollup Calculate Jobs object after Calculate Jobs have finished running. So then the next time the job is scheduled to run, it never runs because it sees the LRCJ record. I'm seeing this every SF org with version 2.6 or higher, and Dan Donin has reported that he is NOT seeing this in version 2.5.

Could this have something to do with the recent change to use the case-safe ID in the LRCJ object? (which I believe happened between version 2.5 and 2.6 .....)

**Comment by afawcett** [comment]
I will look into this asap!

**Comment by afawcett** [comment]
Ok i've made a fix, its ready for the next release, which will be this weekend.

**Comment by afawcett** [comment]
Fixed v2.8.

**Comment by KateLloydFRS** [comment]
I am having the same issue as described above.  I confirmed I am using version 2.8 but the Calculate Job Id never seems to clear out on its own.  Am I missing another step?

**Comment by wbmcdonald4** [comment]
I am having the same issue with Version 2.11, and I can't even find the Lookup Rollup Calculate Jobs tab

**Comment by afawcett** [comment]
@KateLloydFRS This field does not clear, for rollups configured using the Lookup Rollup Summary Custom Object (via Lookup Rollup Summaries tab), then this field is just a historic record of the job Id for the last calculate job run, and thus is for future reference. Nor does not control the error message in this issue.

@wbmcdonald4  Please make sure you have assign the Lookup Rollup Summaries - Configure Rollups permission set and then search for the Lookup Rollup Calculate Jobs tab. Make a note of the record ID (in the browser address bar) of your rollup definition. Then use the list view on that tab to look for records where the field :Lookup Rollup Summary Id" matches your lookup. If this is the case delete that record and re-run your job. Records should get automatically cleared from this object when the job completes successfullly.  Monitor the job via Apex Jobs for errors. Hope this helps.
