### ISSUE TITLE
User Fields: Delegated Approver and Hierarchy Field

### ISSUE THREAD

**Issue by chasefriedman** [afawcett/declarative-lookup-rollup-summaries#461]
When trying to use the Delegated Approver field as the relationship field, I'm getting some errors. Specifically when editing the user record, my rollup isn't working so I'm assuming there is a bug with using this field as the relationship field. Same thing for using a Hierarchy field in the user object. Is this intended or an error? 

![screenshot 2017-02-08 13 13 27](https://cloud.githubusercontent.com/assets/6874200/22753089/7ebe18ce-ee00-11e6-9578-faa0df31699b.png)

**Comment by afawcett** [comment]
Can you try DelegatedApproverId?

**Comment by afawcett** [comment]
@chasefriedman Let me know if this worked or not? 👍
