### ISSUE TITLE
Any way to Conacenate multiple fields?

### ISSUE THREAD

**Issue by acarlesimo** [afawcett/declarative-lookup-rollup-summaries#462]
Hi there - I am trying to write a Rollup that would Concatenate all Opportunity Products with their Product Name, Quantity and the total Amount on the Opportunity - for example:

SLA: Gold - 2 - $1,000;
Player Ticket - 1 - $800;
Donation - 1 - $300

Is that possible with this tool or do I need to hire a developer?  Thank you in advance!

**Comment by ChrisMattSFDC** [comment]
If you can write a formula on the Products to display the information you desire you can use a workflow rule to store that value in a another text field then Roll up that field with the DLRS.

**Comment by Jayleo243** [comment]
I'm assuming you would like this rolled up into one field? Perhaps for a merge field template or report display of some sort. 

There is a very useful tool called the [Declarative Lookup Rollup Summary](https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history) tool which allows you to "rollup" concatenate text strings into a target field on the related parent object. I would suggest using this to concatenate each set of data into a background text field. Then use a formula field or template (if it's for an email or something) to align the values properly for the display:

{Product1} - {Rolled up Quantity1} - {Rolled up Amoun1t}  br()
{Product2} - {Rolled up Quantity2} - {Rolled up Amount1}  br()

The tool is pretty intuitive and there is a lot of forums for help. No code or anything needed!

**Comment by afawcett** [comment]
Great advice both! @acarlesimo these suggestions should get you going. 👍

**Comment by afawcett** [comment]
@acarlesimo Let me know if you need more help on this.
