### ISSUE TITLE
Rollups not running in unit test context?

### ISSUE THREAD

**Issue by swillerford** [afawcett/declarative-lookup-rollup-summaries#463]
I have some Apex code that relies on a DLRS rollup. In a unit test, when I query the parent record after an update, the rollup field value is null. However, when I edit it in the UI (not unit test context), it works fine!

Here are more specifics:
1) Child object field 1 is set by user or unit test
2) Child object field 2 is set by Apex based on value of field 1 (before update)
3) ??? DLRS rolls up value of field 2 to Parent object field 1 - in a test context, this remains null.

At first I thought it might be due to order of execution or having multiple triggers, but when I set child object field 1 in the UI, the rollup works and I get a value in Parent object field 1. Any ideas?

(and yes I'm re-querying the parent object to get the supposedly-updated-by-dlrs field value)

**Comment by afawcett** [comment]
Sounds like a bug, i'll take a look.

**Comment by afawcett** [comment]
So there are a quite a few [unit tests in the tool itself that do this](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupServiceTest.cls#L78), so i don't think its a problem in the tool as yet. Also there is no kind of condition logic in the tool around testing context. 

I am wondering though, are you using custom metadata based rollups or custom object based ones? If its the later, your test will not see the rollup definition and thus even though the DLRS triggers are deployed the engine will not do anything. You can resolve this by moving to custom metadata, using SeeAllData annotation or creating the rollup definitions in your test (only for Custom object mode). My recommendation would be to use custom metadata based rollups, so you don't have to use SeeAllData or create rollup definitions in your test.

Hope this helps!

**Comment by swillerford** [comment]
Ah, I see, I'm using a custom object rollup - it all makes sense now. Thanks for your help! I'll switch to a metadata rollup or create the rollup objects along with my other test data.
