### ISSUE TITLE
Failed to find any 'Lookup Rollup Summary [dlrs]' when creating Package

### ISSUE THREAD

**Issue by cmoutes** [afawcett/declarative-lookup-rollup-summaries#465]
I am attempting to create a package that includes 5 roll-up summaries that I have created using your application. When I try and install this package into the other instance of Salesforce it goes in but then when I go to look at the roll-up summaries they are not there. The only thing that I can think of is that when creating the package I couldn't actually find the roll-up records, just the apex class and trigger. I am not sure what it is that I am missing here. Please help.

Thanks,
Chad

**Comment by afawcett** [comment]
Ok, so if i understand correctly you are creating a new package that is an extension of the DLRS one? And you want to include in your package the rollups you have defined. You must add them to your package explicitly as described in this [blog](https://andyinthecloud.com/2016/01/24/packaging-and-installing-rollups/). Also make sure after installation that you are reviewing the Manage Rollup Summaries tab (this shows rollups defined via Custom Metadata) and not the classic Lookup Rollup Summaries tab (based on Custom Objects).

**Comment by cmoutes** [comment]
My issue is that I am actually not seeing the RollUps in order to add them to the package. When I click that section in the Add Components page nothing shows up. So I am not sure if I am missing a setting or something. In  your example, it is AwesomeRollupOnOpportunity with type Lookup Rollup Summary [dlrs] when I try and look for mine there aren't any that are showing up. Hope this makes sense.

Thanks,
Chad

**Comment by afawcett** [comment]
And you have used the Manage Rollup Summaries page to add them? If you go under Setup and search for Custom Metadata Types, then find the Rollup Summaries object, click Manage Records. Do you see your records? Are they public or protected? Under the Add Components drop down you should see them, can you include a screenshot of this drop / page?

**Comment by cmoutes** [comment]
I just followed the path you gave me and I do not see them either. Is that where I need to make them in order to get them in the package? I thought just making them on the normal tab would suffice.

**Comment by afawcett** [comment]
Yes, you cannot package Custom Object based rollups, only Custom Metadata based ones. For these you need to exclusively use the Manage Rollup Summaries tab.

**Comment by cmoutes** [comment]
Oh alright. That is probably my issue then. Thanks.

**Comment by afawcett** [comment]
No worries, let me know if you still have problems and we can re-open this.
