### ISSUE TITLE
Instructions are out of date in "What you need to know about Scheduling Rollups"

### ISSUE THREAD

**Issue by Arnoldfb** [afawcett/declarative-lookup-rollup-summaries#466]
The directions in finding one's way into the Schedule Apex Area of the SF interface aren't correct. 
It's no longer: Setup > Build > Develop > Apex Jobs and clicking Schedule Apex. .

Currently you'd get there via:  Setup > Develop > Apex Classes and click Schedule Apex. 

It's a minor change, but it took me some time hunting to find the correct path. 

Thanks for this great tool.

**Comment by afawcett** [comment]
Looks like this has been fixed. Thanks for the feedback! 👍

**Comment by Arnoldfb** [comment]
No, sorry it hasn't   the directions are still  Setup > Build > Develop > Apex Jobs and clicking Schedule Apex. 
https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
Should be:   Setup > Develop > Apex Classes and click Schedule Apex.

**Comment by afawcett** [comment]
Oops yes, sorted now. Thanks! 👍
