### ISSUE TITLE
NullPointer Exception on Upsert

### ISSUE THREAD

**Issue by normcopeland** [afawcett/declarative-lookup-rollup-summaries#467]
Hi, I attempted today to upsert records to a custom object called ```person_history__c```. That object has two master-detail fields, one to the contact object and the other to an additional custom object. 

When I attempted to upsert 100 records, 83 of them failed with the message:

```
dlrs_Person_HistoryTrigger: execution of AfterInsert

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 894, column 1
Class.dlrs.RollupService.handleRollups: line 798, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_Person_HistoryTrigger: line 7, column 1
```

Looked like those few that didn't fail were already in my database, the 83 that failed would have been inserts. 

Any idea on what is going on here? Thank you in advance for your help!

**Comment by afawcett** [comment]
Can you check the README file for the latest package release and make sure you are running that please. Thanks.

**Comment by normcopeland** [comment]
Thank you Andy, it seems I’m out of date. I could have sworn I updated quite recently. I’ll update and hopefully that will take care of it. Thank you!!

**Comment by afawcett** [comment]
No worries @normcopeland , let me know if that does not resolve it. 👍
