### ISSUE TITLE
Error on Custom Object with RecordType

### ISSUE THREAD

**Issue by JodieM** [afawcett/declarative-lookup-rollup-summaries#470]
I'm getting an error editing every record in a custom object. 

Error:Apex trigger dlrs_JobDetailTrigger caused an unexpected exception, contact your administrator: dlrs_JobDetailTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field RecordType for JobDetail__c: Class.dlrs.RollupService.handleRollups: line 758, column 1

I ran a debug log but it doesn't say much more than that. 

In Sandbox I was able to fix this issue by removing the child trigger and re-creating it. 
In Production it still errors after removing the child trigger and re-creating it. 
I just updated to 2.8 before removing the child trigger and re-creating it, but the issue was on 2.7 previously also. 

This object had a few DLRS's created before the record types were added to the object. 
I have re-saved all the DLRS's for this object. 

Line 758 doesn't seem to have anything to do with Record Types - it's to do with merging.

**Comment by afawcett** [comment]
The strange thing here is JobDetail__c is not one of the objects included in the tool. The line of code is part of the logic that checks what fields have changed, to determine if the rollup should be executed. Have you got RecordType in the Criteria Relationship Fields field for any rollups associated with the JobDetail__c object?

**Comment by JodieM** [comment]
Ah, OK, so removing all references to and RecordType.DeveloperName = 'General' seems to have fixed it. Is that what #37 is about then?

**Comment by afawcett** [comment]
Thanks @JodieM for the update, glad your going again. And yes 37 is a more out of the box implementation of what currently has to be done manually.
