### ISSUE TITLE
Rollup Issue with Apttus Approvals

### ISSUE THREAD

**Issue by apttushelp123** [afawcett/declarative-lookup-rollup-summaries#472]
We use Apttus IWA and we've been running into a 'too many soql queries' error when submitting approvals. The debug log points to the declarative lookup rollup summaries tool. Not sure how to identify exactly which rollup is causing the issue; I don't believe we have any rollups directly related to any apttus fields. Can someone assist?

![screen shot 2017-03-01 at 12 46 03 pm](https://cloud.githubusercontent.com/assets/26121164/23473142/23fbf658-fe7d-11e6-94b2-c42fbe460e24.png)

**Comment by afawcett** [comment]
Its possible there is some recursive issue here, since all the soql is bulkified in the tool. Can you run some code under anonymous apex in dev console to emulate the scenario causing the issue? If so, then review the execution graph in dev console to see what might be triggering it.

**Comment by afawcett** [comment]
@apttushelp123 Let me know if the above suggestion helped or not?
