### ISSUE TITLE
Debug Log filled up with ENTERING_MANAGED_PKG|dlrs

### ISSUE THREAD

**Issue by leef1030** [afawcett/declarative-lookup-rollup-summaries#473]
There are hundreds lines of ENTERING_MANAGED_PKG|dlrs in debug log. 

How can turn/filter this off?

**Comment by afawcett** [comment]
This is a known platform [issue](https://success.salesforce.com/ideaView?id=08730000000kzpbAAA). What i usually do is copy paste the log into a text editor and do a find and replace. I know its pain. I'll log another issue to update the fflib code used by the tool as it does have a more optimized selector base class, which will reduce these some. But generally its still going to occur. Sorry not a great answer. Please vote for the idea! 👍

**Comment by afawcett** [comment]
This is really platform issue, before closing, i'll link with this issue, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/476.
