### ISSUE TITLE
Uninstall DLRS from our org

### ISSUE THREAD

**Issue by Robeela** [afawcett/declarative-lookup-rollup-summaries#477]
Hi,

I need to uninstall DLRS from our org, because it is causing time it is giving me the  System.LimitException: Apex CPU time limit exceeded on all the triggers.  This is causing a huge problem.

When I uninstall, I get the error message below.  I am unable to edit either the class or the triggers because they are managed.  I have deleted the look up summaries.
Component Type	Name	Problem
Apex Class	RollupService	Component is in use by another component in your organization.   dlrs_Project_AttendanceTest
Apex Class	RollupService	Component is in use by another component in your organization. dlrs_ContactTest
Apex Class	RollupService	Component is in use by another component in your organization. dlrs_List_MemberTrigger
Apex Class	RollupService	Component is in use by another component in your organization. dlrs_ContactTrigger
Apex Class	RollupService	Component is in use by another component in your organization. dlrs_Project_AttendanceTrigger
Apex Class	RollupService	Component is in use by another component in your organization. dlrs_List_MemberTest

Please can you advise how I can uninstall.

Thanks

Robeela

**Comment by NishchithHebbar** [comment]
Hello DanDonin, can you elaborate on that process? The dlrs_AccountTrigger does not allow some of our accounts to be updated or deleted because the account parent Ids are broken. Can you please explain how to disable the trigger or the package?
If I may, can I suggest a custom setting bypass on these triggers in future versions so that we can disable the triggers on problem records?

**Comment by afawcett** [comment]
@NishchithHebbar you can use the Active field on the rollups for this type of triaging. Unticking the Active field on the rollup will prevent processing in the triggers. But you must do this for all rollups that reference the object, via the Child Object field. Regarding the original issue, CPU is a limited resource on the platform, and is shared between all code and configurations that fire on the object. So its possible DLRS pushed it over the top, or maybe you had to many realtime rollups defined. Hope this helps for future reference. 👍
