### ISSUE TITLE
Using in Professional Edition

### ISSUE THREAD

**Issue by faceroy** [afawcett/declarative-lookup-rollup-summaries#478]
Hi,

Firstly, I love this tool... so was delighted when I saw that it was available in professional orgs.
However, I'm having difficulty setting this up. I've followed your blog post but I'm unable to see the 'Call Apex' option in the process builder.

Any pointers on how I can configure this in a PE org?

Many thanks

**Comment by SamuelHaddad** [comment]
Hi,

I face the same issue than @faceroy, I can’t find the “Call Apex” choice in the “Action type” Section:

![capture d ecran 2017-03-14 a 19 51 10](https://cloud.githubusercontent.com/assets/26430797/23941649/e447f064-0969-11e7-9a3d-5b8ef0e0d839.png)

What can I do to finish the creation of my process builder?

Thanks in advance and thank you for this tool

**Comment by afawcett** [comment]
Thats really odd, your missing the Apex Action action type? I have never seen that before. . I wonder if there is some restriction in PE orgs? If so, i wonder how i have ever got reports of DLRS working in PE tbh? The documentation seems to suggest it is [fine in PE though](https://help.salesforce.com/articleView?id=process_action_apex.htm&language=en_US&type=0).... 

This is what i see, though this is in a DE org...

![image](https://cloud.githubusercontent.com/assets/1167760/24082604/907e8636-0c85-11e7-90fb-32e7523b001c.png)

I did some searching, not 100% sure, but wondering if its this [known issue](https://success.salesforce.com/issues_view?id=a1p300000008ZFDAA2&title=process-builder-apex-action-disappears-when-apex-class-is-modified-to-include-reference-to-some-standard-fields)??? The above documentation link also notes this... "If you define an Apex action in your process and then modify the Apex class by adding a standard field reference (for example, User.Phone), the Apex action is no longer visible in the process and must be added again."

Clearly though you are not writing an invocable method or for that matter changing it.... So it does not 100% add up to me yet. I also see from your screenshot your missing a few other options. I think its worth asking Salesforce support why your missing this feature. Does it occur when you create a brand new process as well btw?

**Comment by afawcett** [comment]
Also just seen [this](https://success.salesforce.com/answers?id=90630000000DNMjAAO)....

**Comment by afawcett** [comment]
Aha.... [check this out](https://success.salesforce.com/issues_view?id=a1p3A00000188hTQAQ)...

Summary
After deploying a process, or when refreshing a sandbox, you might notice upon opening the process and reviewing its actions that it might be missing Apex Class actions that reference fields not exposed by tooling API.

Repro
1. On a Fresh Org, prepare a Process with an Action that has an Apex Class as an action that references a field not exposed by tooling API. 
2. Prepare this process as part of a package 
3. Deploy this package (using Workbench or Force.com IDE) 
4. While deploying, select Test Level: NoTestRun 
5. After it successfully deploys, review the process - The apex action will be missing 

Alternatively, simply refreshing or creating a sandbox will copy the process but the Apex action will be missing.

Workaround
Go To Setup |Apex Classes| Compile All Classes 

This should resolve the missing Apex from the process.

**Comment by faceroy** [comment]
Thanks but don't have the option to compile all classes in a PE org.

**Comment by afawcett** [comment]
Then i think its best you raise a case with Salesforce to get them to look at this. It would be great if you can follow up here for future readers. 👍

**Comment by faceroy** [comment]
Hey @afawcett,

I contacted SF support regarding this one. I have been advised that in order to have the 'Call Apex' action exposed in SF you need to have API enabled. Therefore, I'd say that Professional Edition is only supported in orgs where API is enabled.

Hope this helps.

**Comment by matti-sch** [comment]
Hi both. I have API enabled and have never had the APEX action in the Process Builder.

As per the support of the 3rd party supplier of Taskray; they say the APEX is not supported in PE.

Would this mean hat we can't use "declarative-lookup-rollup-summaries" with PE - or does it only bring som restrictions?

**Comment by faceroy** [comment]
Thanks @matti-sch I thought as much and wasn't convinced by the response I received from support.

@afawcett - leads me back to wondering if/how/why you have had reports of users utilising DLRS IN PE orgs.

AB

**Comment by afawcett** [comment]
Ok so according to this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/341 its Lightning Professional Edition, does that make a different i wonder?

**Comment by afawcett** [comment]
@faceroy Let me know if you had a chance to confirm if "Lightning Professional Edition" had the feature?

**Comment by rlwbarnes** [comment]
@afawcett - According to Salesforce Support, APEX is not a Process Builder option in ANY version of the Professional Edition. And enabling the API will not change access to APEX actions. @matti-sch is right. So, I'm currently doing manual calculations on a daily basis.

**Comment by afawcett** [comment]
@rlwbarnes Thanks for confirming, this is sad. I guess you could always use the scheduled calculate mode though in PE, would that work?

**Comment by rlwbarnes** [comment]
I will give that option a try. Right now the client is updating manually on a daily basis OR right before reports are run.

Regards,

Rachel Barnes  |  Director of Technology
 281 433 7632

**Comment by robinkoehler** [comment]
Hi team, I've been pulling my hair out over this due to the PE Apex limitation after I successfully got everything to work run from process builder in the dev org...

My understanding of the technology used here is limited, however would it be possible to create "Lookup Rollup Calculate Job" records via process builder instead of calling Apex? Do these records run the lookups when created?

Many thanks in advance, 

Robin

**Comment by robinkoehler** [comment]
> @afawcett  Thanks for confirming, this is sad. I guess you could always use the scheduled calculate mode though in PE, would that work?

I'm just trying this to retain some of the functionality and am greeted with the "child trigger not deployed" message. My understanding is I wouldn't

- be able to access the fancy new interface to press the "Schedule Calculate" button without API access
- be able to run the scheduled calculate without the ability to deploy the child trigger

Is that basically correct?

Much appreciated, 

Robin
