### ISSUE TITLE
dlrs_PropertyTrigger 

### ISSUE THREAD

**Issue by rachelwatson1** [afawcett/declarative-lookup-rollup-summaries#479]
According to the debug log, this trigger is causing a picklist field on a custom object to update erroneously to an incorrect status.

**Comment by afawcett** [comment]
Hi @rachelwatson1, can you give some more background please? Its hard to help you with this level of information sorry. What do your rules look like? What is the expected behaviour? What are the steps your performing that results in this?

**Comment by rachelwatson1** [comment]
I got it figured out...thank you.

Sent from my iPhone

On Mar 19, 2017, at 9:30 AM, Andrew Fawcett <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @rachelwatson1<https://github.com/rachelwatson1>, can you give some more background please? Its hard to help you with this level of information sorry. What do your rules look like? What is the expected behaviour? What are the steps your performing that results in this?
