### ISSUE TITLE
WorkOrder. Deploy Trigger. Entity is not API accessible.

### ISSUE THREAD

**Issue by HBIND2020** [afawcett/declarative-lookup-rollup-summaries#481]
Hallo All,

I am trying to roll up from WorkOrder (Standard Object) to a Custom Object and getting Entity is not api accessible error, entity name: WorkOrder. Seems the object is available in API version 36.0 https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_workorder.htm. I am on version 2.8 - so should be using API 37.0. What else do I need to look at?

Thanks!!

**Comment by afawcett** [comment]
Ah i see the problem, the generated code is still using API 32! This is a bug. https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupController.cls#L195. Should be easy to fix and explains a few other folks posting stuff like this!

**Comment by HBIND2020** [comment]
I generated the Apex Trigger and Test Class using API Version 37.0. That worked. Thank you!

**Comment by tet3** [comment]
@HBIND2020 How did you generate the Trigger & Test Class with a different API version? Are you running unmanaged version?

**Comment by HBIND2020** [comment]
No, I use the Managed Package! 
Steps to generate the code:

- Click on Manage Child Trigger. 
- A new page will open with the code for the Apex Trigger and Test Class needed. 
- Use a tool like Developer Console to generate it in the API version needed in a sandbox.
- Move to production using a change set.

**Comment by tet3** [comment]
Yes, that's what I did too; was wondering if there was an easier way. This issue should *not* be closed though, because the bug is absolutely still there and needs to be fixed.

**Comment by afawcett** [comment]
v2.9
