### ISSUE TITLE
Can you setup rollup summary to calculate mode to realtime and then also set up a schedule calculation at the same time. 

### ISSUE THREAD

**Issue by BrunetChris** [afawcett/declarative-lookup-rollup-summaries#483]
I have several rollup summary that are setup to run realtime. But I would like to setup a schedule calculation also. Is this possible?

My rollup are used to count records, but I would like the count to start over at the beginning of the year. So that they are zero out.

**Comment by afawcett** [comment]
Hmmm one approach would be to have a zeroing rollup that you schedule once a year. Maybe the same as your current rollup, but with a criteria that will never be met, thus the tool will put a zero in the count. This would not be the same rollup definition though. One for your realtime, one for your scheudle zeroing rollup. Keep in mind though, once your realtime one fires will it not count all existing records again? Or have you sorted that with your criteria logic for the realtime rollup?

**Comment by BrunetChris** [comment]
The realtime will re-count existing records again.




Chris Brunet
Salesforce Consultant/Engineer
StarrData
(510) 556-1997
www.starrforce.com
chris@starrforce.com

Salesforce.com Registered Partner

Facebook: facebook.com/StarrForce
Twitter: @STARRFORCE <https://twitter.com/STARRFORCE>
Blog: http://starrforce.com/cloudthink

**Comment by afawcett** [comment]
Ok is that what you want? If not add some criteria to exclude prior rows by date perhaps?

**Comment by afawcett** [comment]
@BrunetChris let me know if you still want to discuss this, i'll close for now, we can for sure re-open. 👍
