### ISSUE TITLE
DLRS will not count.

### ISSUE THREAD

**Issue by jsacpt24** [afawcett/declarative-lookup-rollup-summaries#484]
I just installed the DLRS managed package to my sandbox to count all the Campaign_Design_Profile__c (custom object) to the opportunity object. This is tied from the CDP to opportunities as a look up relationship. I put in all of the information (Image below) but it doesn't seem to be couting anything and just has a blank. I am wondering if there is anything that I am currently doing incorrectly? 

Opportunity.Active_CDP_s__c is a number field. Is there an issue with that? 

![dlrs](https://cloud.githubusercontent.com/assets/16501949/24572004/04eda1d4-162a-11e7-863c-42762dd6919f.PNG)

**Comment by DanDonin** [comment]
Change the field to aggregate to be ID
