### ISSUE TITLE
"Field does not exist" when using cross-object field

### ISSUE THREAD

**Issue by BalassaSamuelson** [afawcett/declarative-lookup-rollup-summaries#485]
Dear all,

I have a join object between `Project__c` and `Categorization__c` called `Classification__c`.

My SOQL query looks like this:
`SELECT Category__c FROM Classification__c WHERE isDeleted = false AND Project__r.Coreness__c = '3'`

However, when trying to create a new DLRS I get an 

> Relationship Field: Field does not exist.

The field I am trying to aggregate into is `Category__c.Coreness_3__c`

Where am I going wrong here?

**Comment by DanDonin** [comment]
Can't jump tables. You'll only be able to query things on the child. Use a
formula or workflow to bring that field to the child.
