### ISSUE TITLE
Manual Job fails with Error: "A calculate job for rollup 'Next Available Appointment' is already executing. If you suspect it is not already running try clearing the Calculate Job ID field and try again."

### ISSUE THREAD

**Issue by urlaubm** [afawcett/declarative-lookup-rollup-summaries#486]
Every morning I run a job, and it has been failing since 3 days ago. Upon clicking "Run Calculate Job" I get the error message, and the Jod ID field is populated with an ID. The job runs if I clear the field, but I suspect it is not completing as the next morning the issue is reoccurring.

**Comment by afawcett** [comment]
This was a regression at one point, try upgrading to the latest version that should sort it. 👍
