### ISSUE TITLE
Issue with Bulk API Delete

### ISSUE THREAD

**Issue by jschneider-nexgen** [afawcett/declarative-lookup-rollup-summaries#488]
I had two rollups built from a Custom Object up to the Account.  Rollups were enabled for Realtime and schedule for daily (2am).  I attempted to mass delete the data in Custom Object using Workbench Bulk API Delete.  I received the following 8 errors for all of the records.

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P0KVdAAN; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P0KV9AAN; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P17BxAAJ; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P188KAAR; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--"

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P1945AAB; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P17QPAAZ; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P1AqtAAF; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

-------------------------------------------------------------------------------------------------

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_PolicyTrigger: execution of AfterDelete

caused by: System.DmlException: Update failed. First exception on row 0 with id 0014100000P1BlZAAV; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Parent for Account

Class.dlrs.RollupService.handleRollups: line 784, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1: []

Class.dlrs.RollupService.Updater.updateRecords: line 1248, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1291, column 1
Class.dlrs.RollupService.updateRecords: line 1219, column 1
Class.dlrs.RollupService.handleRollups: line 855, column 1
Class.dlrs.RollupService.triggerHandler: line 302, column 1
Trigger.dlrs_PolicyTrigger: line 7, column 1:--

**Comment by afawcett** [comment]
It looks like one of your rollups is invalid, the relationship field on Account is called ParentId, not Parent. Check your rollup definitions for this.

**Comment by afawcett** [comment]
I will close this out for now. We can keep chatting though and re-open the case if needed. Thanks! 😄
