### ISSUE TITLE
Summer 17- Failed to trigger a flow. We cannot find myVariable_old.dlrs

### ISSUE THREAD

**Issue by bcsantoro** [afawcett/declarative-lookup-rollup-summaries#489]
Once my dev org got updated to Summer 17, I've run into an issue with a rollup updating a parent object, and there being an active process builder on that parent.
The only criteria is that a certain checkbox = true (and must subsequently meet that), and now everytime I try to save a record on the child I cannot because I get a flow error. If I disable the process builder it works fine. 
Why did this work flawlessly in Spring 17 but now doesn't work in Summer ?
![screen shot 2017-04-13 at 8 03 23 dm](https://cloud.githubusercontent.com/assets/8225644/25003926/b806ceea-201f-11e7-9618-724061cb9561.png)

**Comment by afawcett** [comment]
@bcsantoro i am not sure tbh, have you updated DLRS since? Can you do a test with the Active field unchecked on your rollup and see if the issue still exists?

**Comment by bcsantoro** [comment]
@afawcett hi Andrew. Yes I've tried alot of troubleshooting and it seems that no matter what the criteria is, if I have an active process builder for the Budget object, any record I try to save (with the declarative rollup summary trigger deployed) on the Transaction object will issue an error like this.
Also the email flow error says: 'The flow failed to access the value for myVariable_old.Current_Budget__c because it hasn't been set or assigned.'

I really hope its just a temporary summer 17 issue for now. I have installed this in client orgs and would cause huge issues

**Comment by afawcett** [comment]
Do DLRS trigger is neutralised by unsetting the Active field on the rollup definition. Can you just do that and let me know if the problem still exists?

**Comment by bcsantoro** [comment]
@afawcett Yes, unfortunately so. Attached is the picture. 
![transactionerror](https://cloud.githubusercontent.com/assets/8225644/25066302/27c0a8d8-21f0-11e7-84d7-83430ce62bc9.png)

**Comment by afawcett** [comment]
It looks like you still have a rollup active on this object, can you check both Manage Rollup Summaries and if your using it also Lookup Rollup Summaries tab. Some place a rollup is defined and active, otherwise the DLRS trigger code would not be invoked. This process i know will not lead directly to a solution, but is part of the discovery process to find the root cause. Disabling things one by one and see when things start to work...

**Comment by bcsantoro** [comment]
Gotcha, I misunderstood your question. 
With the Lookup Rollup Summary inactive and the process builder active, I am able to save a record on the Transaction object.

**Comment by afawcett** [comment]
Can you take a look at [this](https://salesforceyoda.com/2014/05/06/how-i-learned-to-stop-worrying-and-test-my-flow/) and see if you can add some error handling into your flow? Or see if you can find out what the actual underlying error message is, perhaps enable Debug Logs and enable the Workflow categories to Fine detail?

**Comment by bcsantoro** [comment]
Here's a debug log with fine detail on workflows. Not sure if I can see anything. Maybe you'll have a better debugging eye.
[https://gist.github.com/bcsantoro/88e6a5b60c065df9eafbccae6f69e75d](url)

**Comment by afawcett** [comment]
Yeah its not really showing anything, not nothing in fact relating to Flows.... really odd.

**Comment by bcsantoro** [comment]
I've opened a case with SF support. What do you think next troubleshooting steps should be ?

**Comment by afawcett** [comment]
Nothing really, just get Salesforce to tell you what the unhandled exception message is, i am sure that will help discover better what the root cause is. 👍

**Comment by bcsantoro** [comment]
I've been working with Salesforce Premier Support and it looks like this has been patched. The problem has vanished. Still waiting on support's confirmation but I believe this has been resolved. Thanks for your help Andy, looks like DLRS will work with no issues when Summer '17 rolls out.
