### ISSUE TITLE
Calculate job already executing error with scheduled job?

### ISSUE THREAD

**Issue by Bard09** [afawcett/declarative-lookup-rollup-summaries#491]
We have 2 realtime DLRS fields set up, with additional scheduled calculations for each at night (these are fields have criteria such as TODAY in the SOQL so we want to make sure they each calculate both on-demand and also each new day).

Intermittently (not always!) this error pops up for one field or the other field.  One is set up for 2 AM and one is set up for 3 AM.

We're stumped.  Any ideas?  Here's the error:

*******************************
Apex script unhandled exception by user/organization: 00515000007G4Ne/00D15000000NeQD

Scheduled job 'rollup_Next_Scheduled_Appointment (m0015000000PKmh)' threw unhandled exception.

caused by: dlrs.RollupServiceException: A calculate job for rollup 'Next Scheduled Appointment' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.

Class.dlrs.RollupService.checkJobAlreadyRunning: line 576, column 1
Class.dlrs.RollupService.runJobToCalculate: line 93, column 1
Class.dlrs.RollupCalculateJobSchedulable.execute: line 11, column 1
*******************************

**Comment by afawcett** [comment]
Are you on the latest version? There was a bug with this error message that has now been fixed.

**Comment by Bard09** [comment]
We're running 2.8... that is the latest, correct?

**Comment by Bard09** [comment]
I went into one of the DLRS and tried to force a manual calculation and got the same error, actually.

If I go into the the Lookup Rollup Calculate Jobs tab and clear the records there, will that affect any of the following;

1. Ongoing realtime runs of these
2. The scheduled jobs I have for each of these?  (under "Scheduled Jobs")

**Comment by Bard09** [comment]
I went into the tab and cleared the records and it allowed me to manually calculate.  However, I see that this issue has happened to several others recently and am wondering if there might be something in common with us... is there anything we can do to help you diagnose this issue?


We have another field that is on a Scheduled cadence that didn't calculate for a minimum of 2 weeks before we noticed it wasn't updating  A manual calculation 'fixed' the record in quesiton, but we are now worried that multiple DLRS jobs are not running regularly.  I checked RollupJob's history in Apex Jobs and it has successful runs each night.

Any ideas what might be happening?

**Comment by afawcett** [comment]
This should not be happening in v2.8 release, i fixed it via [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/460). You will have to clear the field to restart things. Let me know after clearing it, the problem still persists.

**Comment by cornevanklink** [comment]
@afawcett : This is still happening for me, even after clearing.

**Comment by afawcett** [comment]
@cornevanklink take a look at the comment i just added to https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/460

**Comment by cornevanklink** [comment]
@afawcett : Thanks for the response, I think I have found the problem. If I'm still having problems, I will let you know.
