### ISSUE TITLE
CPU Counting bug in Salesforce

### ISSUE THREAD

**Issue by kevinleecarr** [afawcett/declarative-lookup-rollup-summaries#492]
This was esoteric, but I noticed that DLRS CPU time was counted in the unmanaged CPU timer instead of the DLRS timer.

Salesforce currently has a bug in assigning CPU time to the correct counter when a managed class is called directly from a trigger. You can circumvent the bug by adding a class with two nested method calls before invoking the managed package.

Trigger:
```
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_AccountTrigger on Account
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    DLRSWrapper.triggerHandler();
}
```
Class:
```
public class DLRSWrapper {
    public static void triggerHandler() {
        triggerHandler2();
    }

    public static void triggerHandler2() {
        dlrs.RollupService.triggerHandler();
    }
}
```

**Comment by afawcett** [comment]
Interesting, though i think CPU time is not namespace scoped, https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm. "The cumulative limit doesn’t affect limits that are shared across all namespaces, such as the limit on maximum CPU time.".

**Comment by kevinleecarr** [comment]
Ah, good point. I don't have the cause narrowed down well enough. Though I did see that CPU time went from 15 seconds to 5 seconds with this approach. I'll close this out for now. If ever go back to the root cause, I'll update here.
