### ISSUE TITLE
Scheduled Job not working

### ISSUE THREAD

**Issue by rondavi** [afawcett/declarative-lookup-rollup-summaries#493]
HI,
I have created a DLRS that summarizes a custom field from opportunity to the account record.
I added a filter criteria so only closed-won opportunities and those which their contract end date is before today will be aggregated into the account level. I have tested the DLRS in "real time" mode and it works.
Then I tired to run a schedule job, following the instructions in  https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
However though according to "Apex Jobs" the job has run successfully, the dlrs didn't work nor does it have any "Lookup Rollup Summary Schedule Items" records.
Can you please assist?
Thank you,

Ron

**Comment by afawcett** [comment]
Which mode are you using @rondavi ?

**Comment by rondavi** [comment]
"Scheduled"

**Comment by rondavi** [comment]
Any idea what is the issue?

**Comment by Bard09** [comment]
We have noticed this with one of our Scheduled fields as well.  The RollupJob Scheduled Apex says it has run (and has numbers listing successful batches in many cases), but we found a record that hadn't been updated in almost 2 weeks.

A manual calculate fixed that one record, but we are now concerned about accuracy for Scheduled calculate jobs.  Any idea how to debug?

**Comment by Gilmc** [comment]
Hi all,

I think I have a related issue. One of the roll-up relationship between Contact and Account does not calculate while other roll-up with similar object relationship does work. I do not understand the reason that cause that. Any idea?

**Comment by afawcett** [comment]
Can you check if you have any records in Lookup Rollup Calculate Job? If you do, and you don't have any jobs running and you are running v2.8 please delete then. Let me know if this does not solve the problem.
