### ISSUE TITLE
Upgrade from 1.16 to 2.8 and the Concatenate feature is not visible

### ISSUE THREAD

**Issue by commonteri** [afawcett/declarative-lookup-rollup-summaries#495]
I updated from 1.16 to 2.8 and I don't see the Concatenate in the aggregate operation picklist from the new tab. I also don't see any of the old LRS under the new tab "manage lookup rollup summaries." did I miss a step?

**Comment by afawcett** [comment]
You need to perform some post install steps, take a read through the release history in the readme file for more info. 👍
