### ISSUE TITLE
Entity is not api accessible entity name: WorkOrder

### ISSUE THREAD

**Issue by ginamarina** [afawcett/declarative-lookup-rollup-summaries#496]
Hi, I get this error:

classes/dlrs_WorkOrderTest.cls (Line: 5: Column:9) : Entity is not api accessible entity name: WorkOrder
triggers/dlrs_WorkOrderTrigger.trigger (Line: 4: Column:34) : Entity is not api accessible entity name: WorkOrder

In previous posts, you found that the issue is the API version, and you have updated it in the latest releases. I'm on 2.8, and am still getting the error. Am I missing something? Thanks!

**Comment by ginamarina** [comment]
Hi, I'm still looking for a solution. I tried manually creating the triggers, but they don't fire. Any ideas?

**Comment by ginamarina** [comment]
Ok, main trigger works, I changed API version from 39 to 37, but the test class won't save because of the @ symbol. I'm not sure how to get this into production without a functioning test class.

**Comment by afawcett** [comment]
Take a look at the workaround on this issue, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/481. Closing as this is a dupe.
