### ISSUE TITLE
Field 'Relationship Criteria' limitation

### ISSUE THREAD

**Issue by holger78** [afawcett/declarative-lookup-rollup-summaries#497]
Dear Andy,

the DLRS is a great tool - thanks a lot.

I have browsed the issues but could not find an answer.

We want to aggregate data on user profile in order to have a performance analysis. We need to apply several filters and unfortunately noticed that field 'Relationship Criteria' is limited to 255 digits. We cannot add all required criteria.

Is there a particular reason for this limit or would it be possible to extend it?

If not, do you have any other suggestions?

Thank you very much for a short feedback!

BR
Holger

**Comment by afawcett** [comment]
There is no reason for the limit really, i just didn't imagine it going beyond that i suppose. Best approach is to encapsulate some of your criteria in a formula field. If you do that, please reference the fields you use in the Relationship Criteria Fields field still, that way the tool can recalc the rollup properly when any field used in your criteria changes. Hope this helps! 👍
