### ISSUE TITLE
Apex Jobs Stopped Running & Error Message:  A calculate job for rollup is already executing...

### ISSUE THREAD

**Issue by CrystalSuarez** [afawcett/declarative-lookup-rollup-summaries#498]
Hello…we created four DLRS records that as of 4/11 were running accordingly with no issues, however we noticed today that all the schedule Apex jobs stopped running (unable to determine at which point they had stopped).  When we attempted to manually calculate them, we received a “_A calculate job for rollup is already executing. If you suspect it is not already running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again_” error.  There is no applicable job records to delete.  We tried removing and reinstalling the Apex triggers and researching for any apparent issues that would cause the DLRS records to stop calculating but have been unsuccessful in finding a solution.  We are currently using Version 2.7 and did see some comments about installing the most recent upgrade.  Could this be our issue?

Update:  There were two packages recently installed in Production (Demand Tools & DupeBlocker)...Are there any known issues with these packages that would conflict with DLR Scheduled jobs?

<img width="757" alt="dlrs run calculate job error" src="https://cloud.githubusercontent.com/assets/28270613/25590554/0b54b2a2-2e7f-11e7-99bb-6aab3e449116.png">

**Comment by Bard09** [comment]
We experienced this problem as well (but we found that there were jobs we could delete).  We're not sure if it's back to running regularly or not yet.  We actually use DupeBlocker as well if that helps.

**Comment by CrystalSuarez** [comment]
Thanks so much Bard09.  We still can’t figure out what the problem is.  There is no clear answer on any of the forums as to why all of DLRS would just stop running.

**Comment by afawcett** [comment]
Please make sure your running v2.8 and if you do not having any jobs running you can clear any records from the Lookup Rollup Calculate Jobs object. Let me know if this does not unstick things. 👍
