### ISSUE TITLE
Bulk API causing Lock errors in Calculate Mode

### ISSUE THREAD

**Issue by jclark-dot-org** [afawcett/declarative-lookup-rollup-summaries#499]
We have a couple of rollups on an object and were getting Lock errors when loading many child records via Bulk API, so we switched them to Scheduled rollups.  But we're still getting Lock errors:

    Apex script unhandled trigger exception by user/organization: 005xxxxxxxxxxxxx/00Dxxxxxxxxxxxx
    
    dlrs_ManagedPackgeName__NewTransactionTrigger: execution of AfterInsert
    
    caused by: System.DmlException: Upsert failed. First exception on row 6; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 2 records: a0r36000002SZbxAAG,a0r36000002UlNfAAK: []
    
    Class.dlrs.RollupService.updateMasterRollupsTrigger: line 946, column 1
    Class.dlrs.RollupService.handleRollups: line 842, column 1
    Class.dlrs.RollupService.triggerHandler: line 307, column 1
    Trigger.dlrs_SalesConnect_NewTransactionTrigger: line 7, column 1

However, the IDs mentioned in the exception are the IDs of the DLRS Lookup Rollup Summary record, not of parent records.  I'm guessing the issue is the creation of the Lookup Rollup Summary Schedule Items, which are MD children of the DLRS Lookup Rollup Summary, is trying to lock the parent.  Is the only solution to change the Bulk API job to serial?

**Comment by jclark-dot-org** [comment]
Just realized those aren't the only failures, some records are failing with Lock errors on the actual Lookup Rollup Summary Schedule Item records as well.

**Comment by afawcett** [comment]
@jclark-dot-org thanks for this, yes serial is the current workaround. I'm going to make a new schedule item object (since the platform does not let me change the existing) with lookup only relationship.

**Comment by afawcett** [comment]
@jclark-dot-org I have removed the master detail relationship (at least in the package) between scheduled line items and rollups which may have been causing this lock issue. Please review v2.12 in the relase notes in the README and the linked blog (there is some post install steps). Thanks!
