### ISSUE TITLE
Scheduled Rollups Not Firing (Appearing in Queue, No Errors Shown in Apex Jobs after Running)

### ISSUE THREAD

**Issue by kevb1107** [afawcett/declarative-lookup-rollup-summaries#500]
I'm attempting to schedule hourly refreshes of a DLRS, but the rollups fail to refresh on a scheduled basis. All the Rollup rules that are failing are set to "Active" and "Scheduled." I've been testing out what could be going wrong, and here is what I've found so far:

- Again, the rollups are working just fine when set to Realtime.
- When the scheduled rollups fail to fire, no errors are shown in the Lookup Rollup Summary Logs Tabs.
- When I look at the Apex Jobs page, that page shows that all of the jobs have fired at the correct time, with no errors. However, the actual rollup information fails to refresh.
- When I manually "Calculate" the rollups, the same behavior is observed (the Apex Jobs page says that the job has been run with no errors, but the information is not updating on the parent record I'm testing).
- Finally, other posts about this issue noted to check the "Lookup Rollup Summary Schedule Items" list. When I update the child records in a way that affects the rollup, the parent record is added to the queue on the "Lookup Rollup Summary Schedule Items" page. However, once the next refresh passes, these entries are not removed from the queue.

Any idea what is going wrong here? What am I missing here in terms of where the error could be, and what else should I be checking?

**Comment by afawcett** [comment]
The fact that your seeing records still in "Lookup Rollup Summary Schedule Items" indicates there was some issue and i'm surprised there is nothing in the "Lookup Rollup Summary Logs " object? Can you capture a debug log from your next scheduled run?

**Comment by kevb1107** [comment]
I talked to my client about this, and they decided to move away from the
scheduled rollups to get around this issue. So at the moment, I can't
capture anything in the debug logs without changing the production
environment back to scheduled. I will comment back if I have any updates,
but for now you can consider this issue closed.

Thanks,
Kevin

Kevin Binder

Senior Salesforce Analyst



   Salesforce Certified App Builder, Service Cloud Consultant, Administrator
   708-209-5823

<http://torrentconsulting.com/>   torrentconsulting.com­

<https://www.facebook.com/TorrentGuides>
<https://twitter.com/TorrentGuides>   [image:
https://www.linkedin.com/in/kevinbinder]
<https://www.linkedin.com/in/kevinbinder>
<https://www.instagram.com/torrentguides>

**Comment by afawcett** [comment]
You shlould also check Rollup Summary Calculate Jobs tab for stuck records. If your johs are not running delete the records and make sure you are running v2.8
