### ISSUE TITLE
unable to obtain exclusive access to this record : UNABLE_TO_LOCK_ROW ()

### ISSUE THREAD

**Issue by Gilmc** [afawcett/declarative-lookup-rollup-summaries#501]
Hello there,

When I run (calculate) on this roll-up I got error messages: unable to obtain exclusive access to this record : UNABLE_TO_LOCK_ROW ()
It was set to Realtime and now I have changed it to schedule - the fields I use on the child object are not formula fields. I believe that there are more than 50,000 records in total (not linked to a specific parent record).
How could I solve this?
May I add that I am system admin (not a developer)

**Comment by afawcett** [comment]
Where are you seeing these error messages?

**Comment by DanDonin** [comment]
Unable to lock row normally means the record is being edited elsewhere in the system or by a user.  If you have it set to schedule are you running the scheduled apex at a time when the records are unlikely to be opened by a user?

**Comment by afawcett** [comment]
@Gilmc did @DanDonin's response shed any light?

**Comment by Gilmc** [comment]
Yes, thank you
