### ISSUE TITLE
Trigger does not run on Update

### ISSUE THREAD

**Issue by cmmoutes13** [afawcett/declarative-lookup-rollup-summaries#502]
I have a Rollup summary built to roll up completed activities to Opportunity. The rollups work when the tasks are created with the status of completed, but not when the task is edited to have the status go from open to complete.

Am I missing something here?

**Comment by chawlalaxmi** [comment]
I am facing the same problem. Any tips how to resolve it?

**Comment by cmmoutes13** [comment]
For me, I had to add the fields I was using in the criteria to the "Relationship Criteria Fields" field and then it started working.

**Comment by chawlalaxmi** [comment]
Thanks, that was my mistake too. It works now!
