### ISSUE TITLE
Unable to 'schedule' calculations

### ISSUE THREAD

**Issue by erezerezg** [afawcett/declarative-lookup-rollup-summaries#504]
When I click on any of my existing dlrs' "schedule calculate" buttons, I am redirected to https://dlrs.MYORG.visual.force.com/apex/rollupscheduledcalculate?scontrolCaching=1&id=a0C2400000o6hRU and displayed the following error message:

**SObject row was retrieved via SOQL without querying the requested field: dlrs__LookupRollupSummary__c.dlrs__UniqueName__c** 
An unexpected error has occurred. Your solution provider has been notified. (dlrs)

- I did attempt to remove the existing child triggers but was met with the same situation.
- I did read that section in the documentation but there were no technical explanations of specs

Any help would be greatly appreciated.

**Comment by afawcett** [comment]
I have tried to recreate this but i cannot. What version are you running?

**Comment by afawcett** [comment]
@erezerezg let me know if you still want to chat on this, happy to re-open and keep going! 👍
