### ISSUE TITLE
Update RollupController.cls to remove hard-coded API version references

### ISSUE THREAD

**Issue by tet3** [afawcett/declarative-lookup-rollup-summaries#505]
`RollupController.cls` currently uses API 32 in it's several methods that generate `package.xml`, `destructiveChanges.xml` and `*-meta.xml`. This results in failed deployment of triggers on standard objects newer than that API version, such as AccountContactRelation and WorkOrder (see #481 #438 and #496 ) 

At a minimum, this API version should be declared once in a `static final` at the top of the class, though dynamic calculation or storing it's value in an admin-accessible spot would be good options too.

**Comment by afawcett** [comment]
Agree👍🏻

**Comment by afawcett** [comment]
v2.9
