### ISSUE TITLE
Apex Trigger Deployment Errors

### ISSUE THREAD

**Issue by BRRLLS** [afawcett/declarative-lookup-rollup-summaries#507]
V2.8

Errors...
dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: MALFORMED_ID, Invalid campaign id: null: [CampaignId] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_CampaignMemberTest.testTrigger: line 11, column 1
dlrs_ContactTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, ContactTrigger2: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Trigger.ContactTrigger2: line 9, column 1: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_ContactTest.testTrigger: line 11, column 1
-----
Issues implies that the second error was fixed in a previous version (1.14?)
Not sure how the CampaignId can be malformed.
Rollup runs fine one-time on a "Developer" schedule.

**Comment by dionisus1122** [comment]
I'm having a very similar error:
Error:
dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: MALFORMED_ID, Invalid campaign id: null: [CampaignId] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_CampaignMemberTest.testTrigger: line 11, column 1

Also:
Warning:
dlrs_CampaignMemberTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required


_

**Comment by afawcett** [comment]
Have a look through some of the other issues using this child object, https://github.com/afawcett/declarative-lookup-rollup-summaries/search?q=CampaignMember&type=Issues&utf8=%E2%9C%93. You do need a little bit of custom code to get the test to pass for this object. Are you using a some custom test code in the Test Code field?

**Comment by dionisus1122** [comment]
Thanks Andrew -

I should have checked resolved issues first.  Sorry about that.

I solved it on contact using the test code found in a resolved issue:

Campaign camp = new Campaign(Name = 'Test Campaign');
        Insert camp;
        Contact c = new Contact(LastName = 'Test');
        Insert c;

        dlrs.RollupService.testHandler(new CampaignMember(CampaignId = camp.Id, ContactId = c.Id));

I will fiddle with it to get the same test code for Leads I assume?

**Comment by afawcett** [comment]
Thanks @dionisus1122 for the update. Honestly i'm not a major user of the Leads object, so not sure, try it without first. 👍
