### ISSUE TITLE
Duplicate Value Found: <unknown>

### ISSUE THREAD

**Issue by Stormin4880** [afawcett/declarative-lookup-rollup-summaries#508]
I am trying to install the 2.8 vs into my sandbox org. I first uninstalled the old package. I select install for Admins and all users and then I get the following error:

Package: Declarative Lookup Rollup Summaries Tool (04tb0000000MXkF) Error Number: 1226387624-35137 (-728077655)
Problem:

1. (DeclarativeLookupRollupSummaries) duplicate value found: <unknown> duplicates value on record with id: <unknown>
DeclarativeLookupRollupSummaries: duplicate value found: <unknown> duplicates value on record with id: <unknown>

Any help would be greatly appreciated.
Nate

**Comment by afawcett** [comment]
This looks like a platform problem, maybe a cache or echo or something from the old version. I am not sure why you uninstalled the old version as you can upgrade for future reference. Meanwhile i suggest you raise a case with Salesforce on this, it looks like some platform bug, possibly related to custom metadata records (a guess). Sorry i cannot be of more help here. Here is some more info Gacks, https://developer.salesforce.com/blogs/engineering/2015/02/gack.html.
