### ISSUE TITLE
Require Validation for Converted Leads Error

### ISSUE THREAD

**Issue by jillmyers** [afawcett/declarative-lookup-rollup-summaries#509]
Hello! So declarative lookup roll-up summaries was installed on our salesforce way before I took over the account. Unfortunately, I am not familiar with it at all and when I turn on the "Require Validation for Converted Leads" setting I am getting the following error message:
Error: System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Trigger]: [Trigger] Class.leadconvert.BulkLeadConvert.handleOpportunityInserts: line 740, column 1 Class.leadconvert.BulkLeadConvert.convertLead: line 104, column 1

Thoughts on where I might go from here?

Thanks!!

**Comment by afawcett** [comment]
Based on the error message i don't see anything related to DLRS? The easy way to confirm this is to untick the Active field on the rollups and retry your problem. On the face of it, it looks like you have class call leadconvert in your system that is trying to update a record and has not provided all the field values needed. Try reviewing the code around line 740 in the leadconvert class. Sorry i cannot be more help based on the available information. Please feel free to ping back here if you find anything that does point to DLRS and i can try to help further. Thanks! 👍
