### ISSUE TITLE
FATAL_ERROR|System.DmlException: Update failed. First exception on row 0 with id a1hA0000005UnEWIA0; first error: NUMBER_OUTSIDE_VALID_RANGE, Data Released Order Totals: value outside of valid range on numeric field: 1008500.0000000AAA: [Data_Released_Order_Totals__c]

### ISSUE THREAD

**Issue by jamgarciax** [afawcett/declarative-lookup-rollup-summaries#512]
For some reason the APEX class is returning a number with a 8 decimal points, I checked all field data types and saw that all fields associated are currency fields. 

This roll up is also using a process builder to update a shadow from the Order Amount field which is formula. The reason I am using a shadow is so that I can force a hard update on the field to roll up the value to the parent object. 

Checked and it's not my process that is adding the extra decimal points too. Any help would be appreciated please.

**Comment by afawcett** [comment]
I've not seen this kind of error before and with the information given its hard for me to reproduce. I did some googling of the error and did not find much either tbh. My recommendation is to try and disable parts of your solution bit by bit until you get to the root of the issue and see what additional insights that process reveals. Extensive use of multiple process builder, rollups, can make it hard to spot whats going on, so try to boil it down to one operation and as little process builder or other work as possible, to see if it is the rollup itself. A good tool for getting an overview is the Developer Console, switching on the Execution Overview feature.

**Comment by afawcett** [comment]
@jamgarciax hope your well, let me know if you still want to discuss, we can for sure re-open this discussion. 👍
