### ISSUE TITLE
Location object does not exist

### ISSUE THREAD

**Issue by ginamarina** [afawcett/declarative-lookup-rollup-summaries#514]
I'm getting an error that the Location object does not exist. This is a standard Salesforce object, API name is Location, I verified in Workbench. It also says the Lookup field on the Entitlement object Location__c doesn't exist, which it does. Any ideas how to fix this? 
<img width="1277" alt="screen shot 2017-06-05 at 2 05 16 pm" src="https://cloud.githubusercontent.com/assets/27941410/26800881/19d54b9a-49f8-11e7-8578-fe57a39dbdb6.png">
I have version 2.9 installed.

**Comment by afawcett** [comment]
This is a list of all the latest standard objects and I do not see Location in it, https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_list.htm. Can you share a screenshot of what your looking at in Workbench?

**Comment by ginamarina** [comment]
Location is a new standard object. 
![image](https://user-images.githubusercontent.com/27941410/27148517-d280ff3e-50fd-11e7-9f2b-f92c10534e5a.png)

**Comment by afawcett** [comment]
Thanks for sharing @ginamarina, though i still don't see it in the docs. Can you share a screenshot of the object showing up via Salesforce Workbench please?

**Comment by afawcett** [comment]
@ginamarina did you get this resolved? Happy to re-open this issue to discuss. 👍
