### ISSUE TITLE
Salesforce Metadata API connection failure

### ISSUE THREAD

**Issue by WEC-WCV** [afawcett/declarative-lookup-rollup-summaries#515]
Been having issues with remote site settings. I have deleted and re-created new remote sites 2-3 times but when I return my next session to manage lookup rollup summaries, i receive the metadata failure error.

I have 2.8 installed and my instance uses custom domain (not sure if that affects the remote site). I have tried re-creating the remote site using my standard domain and custom domain.

thanks,
devan
![screenshot 2017-06-06 at 10 27 49](https://user-images.githubusercontent.com/19214900/26842797-e01f29e2-4aa2-11e7-8839-5077efbf4d85.png)

**Comment by DanDonin** [comment]
Do you block IP ranges?

**Comment by WEC-WCV** [comment]
I did initially but turned those settings off after the first time. still seeing the same error though

**Comment by afawcett** [comment]
Does your user have API access and Modify All?

**Comment by kentallman** [comment]
I'm running into a similar problem. DLRS was working fine, but I just went in to update a lookup and saw these errors:

![dlrs errors](https://user-images.githubusercontent.com/29442419/27157297-2c4434a8-511e-11e7-89d8-b5ac324857b6.jpg)

I tried creating the remote site, but it complained that it was already installed. 

Any suggestions?

**Comment by afawcett** [comment]
Does your use @kentallman still have API access and Modify All?

Keep in mind to edit rollups (via the Rollup Summaries tab) you don't need this, only to deploy triggers. If you are using the Manage Rollup Summaries tab you will need this access to edit rollups currently.

**Comment by dcinzona** [comment]
I'm also experiencing the same problem with a developer org.  I'm logged in as sys admin with mod all and the remote site exists, yet I still get the same error message (even on the roll up summaries tab - on the pilot version using custom metadata)

**Comment by afawcett** [comment]
@dcinzona yep thats covered in the known issues in the readme file. Glad your up and running! 👍
