### ISSUE TITLE
Multiple rollups on same Aggregate Result Field?

### ISSUE THREAD

**Issue by astehman-summa** [afawcett/declarative-lookup-rollup-summaries#516]
I am taking a guess that this is not possible? Based on the type of the target objects, the rollup should behave differently. E.g.

**Parent Object**
------------------
Result
Aggregate Result 
Max Result

**Child Object (Types: Competing, Noncompeting)**
------------------------------------------------------
type=[Competing]

Where within a Parent, all children must either be all competing or all noncompeting.

**The Problem**
Basically, I would want Parent.Result to be populated with either 1. the sum of all child objects if they are all noncompeting or 2. the max of all child objects if they are all competing.   

However, I am guessing there cannot be two DLRS records that populate one agregate result field, so I would probably have to implement two fields, e.g. Aggregate Result to be populated with the sum of all noncompeting child objects, and Max Result to be populated with the sum of all competing child objects.   Then make Result a formula field to hold the final result of comparing one or the other? (Whichever one is nonzero, and if they are both zero, throw an error?)

**Comment by afawcett** [comment]
Yep Formula field is the way to go! 👍
