### ISSUE TITLE
Fewer fields available to aggregate?

### ISSUE THREAD

**Issue by ginamarina** [afawcett/declarative-lookup-rollup-summaries#519]
In the previous version of DLRS, we were able to SUM a formula field. In the newest version, it appears to break our existing lookup summaries, we are getting trigger errors. When I open the lookup summary, I see a new button "Enhanced Edit" that has a dropdown of the fields available, and the field we need to aggregate isn't there. Are we unable to SUM formula fields anymore?

**Comment by afawcett** [comment]
I recommend you use the Manage Rollup Summaries tab instead of that UI. While you don't have the drop downs ( a subject of another enhancement request), you can enter formula fields. The Enhanced Edit has been superseded by this new tab.

**Comment by afawcett** [comment]
@ginamarina hopefully your up and running, let me know if not and we can re-open this issue.
