### ISSUE TITLE
SOQL statement difficulties

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#522]
I'm trying to write an OR statement for my lookup summary and am getting a syntax error.  I've read and re-read the documentation on SOQL statements and can't figure out what I'm doing wrong.

The statement is:
Current_Year_Expected__c=true OR Current_Year_Payment__c=true

And the error I'm getting is:
Error: Relationship Criteria 'Current_Year_Expected__c=true OR Current_Year_Payment__c=true' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: OR'
![soql_or_statement](https://user-images.githubusercontent.com/8515331/27287361-55732c06-54d1-11e7-8ed3-0d2e37452b19.jpg)

**Comment by DanDonin** [comment]
Wrap it in ( )

**Comment by JodiNA** [comment]
Phew. I love it when it's something that simple. It worked. Thanks @DanDonin.
