### ISSUE TITLE
Sum Rollup not calculating correctly after a few hours

### ISSUE THREAD

**Issue by ace3574** [afawcett/declarative-lookup-rollup-summaries#523]
We are trying to sum Salesforce rollups fields on the Child object. When I run a calculate job, they seem to be working for a few hours and then when I check later, they are calculating incorrectly. Below are the rollups. How can I find what would be causing them to change?

<img width="1215" alt="screenshot 2017-06-21 09 32 16" src="https://user-images.githubusercontent.com/23327957/27386737-b7afaa36-5664-11e7-82a7-9550a9627068.png">
<img width="1182" alt="screenshot 2017-06-21 09 33 37" src="https://user-images.githubusercontent.com/23327957/27386740-b88c5b3e-5664-11e7-8975-5b285423aeb7.png">

**Comment by afawcett** [comment]
Do you use sharing on your objects (e.g. Private sharing model under Sharing in Setup), if so try changing your Calculation Sharing Mode to System, so the rollup engine sees All records regardless of what the user sees. Are you doing any Merge operations, if so you might want to ensure that option was ticked when you used the Manage Child Trigger button. Finally make sure your on the latest version. Beyond this, try to look at the child records and parent record and do some sums to see what records might be missing and look for patterns.

**Comment by afawcett** [comment]
@ace3574 Did any of my suggestions above help? Let me know if you still want to discuss and we can re-open this issue. 👍
