### ISSUE TITLE
Realtime rollups not working - formulas?

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#524]
At least one, and probably more, of my rollups are not working in real-time mode.  This particular one, attached, works when I click on calculate but not through real-time changes.  

My hypothesis is that it is because the field triggering the rollup (Count_Action_Plan_in_Totals__c) is a formula field.  Am I correct that this could be the source of my issues, because a change to a formula field is not actually an edit, so DLRS wouldn't know to evaluate the record?

If I am correct about this, is there any workaround I can use in setting up the rollups in order to have them calculate real-time?

If I'm not correct, anything else I should look at?  I tried cloning this lookup and have the criteria be based off of a non-formula field, and it seems to be working.  So, if the formula is NOT the issue, I have no clue where to go next!
![lp_dlrs](https://user-images.githubusercontent.com/8515331/27548811-14fd5a42-5a68-11e7-8cd3-26f5978a1672.png)

**Comment by DanDonin** [comment]
you could just add into the Criteria Fields the fields that the formula is
looking at then when those change it will trigger the DLRS record to fire
but as they are not part of the Relationship Criteria they wont be added to
the SOQL.

**Comment by JodiNA** [comment]
Thanks @DanDonin! That's what I figured.  Can I do fields from both the child object and parent object in the criteria?  And, if so, for which one (and how) do I need to reference that it is a different object?  The parent?  In this case, my formula spans both.

**Comment by DanDonin** [comment]
DLRS can't jump tables sadly.  So I'd just put some of the fields in that
formula that live on the object itself.

**Comment by JodiNA** [comment]
Okay. Thanks.  I will probably have to do a workflow and an extra field on the child object.  With this formula in particular, the field on the parent is frequently the change that would cause the formula result to change.

Any chance table jumping might be possible in the future, @afawcett ?

**Comment by DanDonin** [comment]
Pretty hard for the trigger to table jump as an edit on the parent doesn't
ALWAYS mean an edit to the child thus a child trigger would never be
called.  I've seen people do some I think Child>Parent in the SOQL with
standard dot stuff like Contact.Account.Name but I've seen others who have
issues with it, so I can't say for sure if it should ALWAYS work or ALWAYS
fail. =/

**Comment by JodiNA** [comment]
Got it!  I'll play around and see what I can get working. Many thanks!  I love this tool!

**Comment by afawcett** [comment]
Thanks @DanDonin, @JodiNA hope your good! 👍

**Comment by JodiNA** [comment]
Yes!  All good over here now!

**Comment by 7114234** [comment]
Hi,
Having issue with a rollup on a formula field. any suggestions? all other roll ups are functioning properly. Only the realtime is not. When I press Calculate it works properly.

**Comment by afawcett** [comment]
You will need to complete the “relationship criteria fields” field with the fields your formula used. Otherwise DLRS will not see the change.

**Comment by 7114234** [comment]
> 
> 
> You will need to complete the “relationship criteria fields” field with the fields your formula used. Otherwise DLRS will not see the change.

Hi Andy, Thanks for you prompt reply. I have done as you mentioned and it did not help. I would like to mention that I believe in the past it was working and something happened.
Also, when I click "Calculate" it does it just fine and is correct.

**Comment by afawcett** [comment]
Is the rollup active and is the child trigger deployed?

**Comment by 7114234** [comment]
Yes!

**Comment by afawcett** [comment]
Do you have any other rollups on for that child object that are perhaps targeting that field? Or workflows? Does inserting or deleting child records also have no effect?

**Comment by jhoanborges** [comment]
Save problem... my rollup was using a criteria formula, it was active and trigger deployed and also did not work.
