### ISSUE TITLE
Not possible to roll up Article CreatedDate to Case record

### ISSUE THREAD

**Issue by jjuez** [afawcett/declarative-lookup-rollup-summaries#526]
Just updated Rollup Helper with DLRS 2.9 on a Sandbox running Unlimited Edition.
Need to rollup the oldest CreatedDate of the articles attached to Cases. I seem to be able to use 2 different child objects: the API of our Knowledge Article Type (screenshot) or CaseArticle (in which case the relationship field should be CaseId).

When I calculate the rollup, I get an error saying that "A calculate job for rollup 'KCS Maturity' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again." The "Lookup Rollup Summary Logs" tab does not display anything, so I cannot delete anything.

Cases are not being updated either. I have even disabled all Case validation rules. Not sure what I am doing wrong.
Note that I cannot use Real Time nor Scheduled modes because Knowledge Articles and CaseArticle do not support triggers.

![image](https://user-images.githubusercontent.com/25209888/27809390-86dca3f6-604f-11e7-8fee-cca5050f5ca3.png)

**Comment by afawcett** [comment]
Just checking, but your checking the "Lookup Rollup Calculate Jobs " tab? Your post refers to the "Lookup Rollup Summary Log" tab and thats not the one the message is referring to its, its the jobs one.

**Comment by afawcett** [comment]
@jjuez Did you check this above? Happy to keep discussing with you, let me know and we can re-open this issue. 👍
