### ISSUE TITLE
Question: If using a trigger framework with an unmanaged DLRS, is it sane to delete the "dlrs_OpportunityTrigger on Opportunity" so as to bake it into trigger framework?

### ISSUE THREAD

**Issue by peternoges** [afawcett/declarative-lookup-rollup-summaries#527]
In using the DLRS tool to summarize some child records beneath Opportunities, this was created:
```
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
trigger dlrs_OpportunityTrigger on Opportunity
    (before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
    dlrs.RollupService.triggerHandler();
}

```
However I'm using the 1-trigger per object pattern (framework) as defined here https://github.com/kevinohara80/sfdc-trigger-framework

Since I'm using the UNmanaged DLRS, I think my go-forward action is to call     `dlrs.RollupService.triggerHandler();`
Within my framework trigger, rather than in "trigger dlrs_OpportunityTrigger"

Does that seem reasonable?  Thank you for the sanity check ;)

**Comment by afawcett** [comment]
Yep that will be fine. If you need more find grained control, for example your also updating parent records of the child, there are other methods on the RollupService class.
