### ISSUE TITLE
How to deploy DLRS lookups?

### ISSUE THREAD

**Issue by astehman-summa** [afawcett/declarative-lookup-rollup-summaries#529]
I'm looking at how to deploy/promote DLRS rollup summaries from one sandbox to another.  Any links to this documentation would be most appreciated! Thank you!

**Comment by astehman-summa** [comment]
From what I can see it seems there is a data load component, but the only dlrs_* object I found with any data in it is dlrs__LookupRollupSummary__c

**Comment by afawcett** [comment]
@astehman-summa you need to create rollups using the Manage Rollup Summaries tab, then you will see your rollups and their triggers (if you used one of the modes that needed them) in your Change Set display. I know folks in the Chatter group have done this (see README file for link to Chatter Group). 👍

**Comment by jvolkov** [comment]
Search engines keep directing to this old issue so it's useful to provide an update.

You can now deploy between orgs using the Lookup Rollup Summary as the parent object right?

![image](https://user-images.githubusercontent.com/1066119/205726977-1015e642-ffcc-4b5f-b014-f15ac17fc271.png)
