### ISSUE TITLE
Rollup Not Working when 3rd Criteria added

### ISSUE THREAD

**Issue by astehman-summa** [afawcett/declarative-lookup-rollup-summaries#530]
I learned a new requirement that now the rollups must be filtered on a third criteria. (This will mean creating 62 new fields to capture the rollups... but I digress).

I tried creating just one (so I could then clone). However, it's not working. I have checked and re-checked and re-re-checked.

![image](https://user-images.githubusercontent.com/28109374/28081380-10926e9e-663d-11e7-825e-72c5e5a070e4.png)

I ran a query with those criteria to ensure I wasn't missing something.
![image](https://user-images.githubusercontent.com/28109374/28081485-6970df00-663d-11e7-882b-cb950ed10d04.png)

Any ideas?

T H A N K   Y O U ! ! !

**Comment by DanDonin** [comment]
You need to add the field names in the relationship fields from your where.

**Comment by astehman-summa** [comment]
@DanDonin - thank you for responding.

I originally had them in there.  A colleague said they're not necessary so I removed them. Either way - with or without - doesn't affect the outcome. The rollup field isn't rolling up regardless.  I put 'em back in, ran calculate, reloaded the parent record and... no dice. :(  

![image](https://user-images.githubusercontent.com/28109374/28081841-a6b073b6-663e-11e7-9a96-fc2a430a756d.png)

**Comment by DanDonin** [comment]
Is Project__c a ID field that links the two objects?

**Comment by astehman-summa** [comment]
Yes. Lookup from Opportunity to custom Project object.  The other rollup fields are working. I am unsure why this one does not.
