### ISSUE TITLE
Trigger Deployment Error - Multi-Company FFA

### ISSUE THREAD

**Issue by eggletm** [afawcett/declarative-lookup-rollup-summaries#532]
Hi 
Am I trying to deploy DLRS in a multi-company FFA environement to roll up from FFA Sales Invoice to Account object.

I get an error deploying the trigger about the current Company not being set (see screenshot). I do have one of the company's set.

Thoughts, tips pointers?
Cheers
Martin

![screenshot 2017-07-27 09 32 07](https://user-images.githubusercontent.com/10072131/28661460-9fea7c1c-72ae-11e7-997e-675b21f01e01.png)

**Comment by afawcett** [comment]
Sure, take a look at this, http://help.financialforce.com/accounting-api/16X/WritingApexTests.htm and this https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage
