### ISSUE TITLE
techmatrixconsulting/fflib-apex-mocks

### ISSUE THREAD

**Issue by techmatrixconsulting** [afawcett/declarative-lookup-rollup-summaries#533]
Deployment Started
Status: Queued 
Status: Completed 
Deployment Complete
Failures:
classes/fflib_VerificationMode.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_System.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_SystemTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_Answer.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_AnswerTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_Answer : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_AnyOrder.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MethodCountRecorder : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_AnyOrderTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MyList : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_ApexMocks.cls(67,15):Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_ApexMocksTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_Mocks : Dependent class is invalid and needs recompilation:
 Class fflib_MyList : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_ArgumentCaptor.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_Match : Dependent class is invalid and needs recompilation:
 Class fflib_MatcherDefinitions : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_ArgumentCaptorTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MyList : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_InOrder.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MethodCountRecorder : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_InOrderTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MyList : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_InheritorTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_InvocationOnMock.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_Match.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MatcherDefinitions : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MatchTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MatcherDefinitions : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MatcherDefinitions.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MatcherDefinitionsTest.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MatchersReturnValue.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MethodReturnValue : Dependent class is invalid and needs recompilation:
 Class fflib_Answer : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MethodCountRecorder.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MethodReturnValue.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_Answer : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MethodReturnValueRecorder.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MethodReturnValue : Dependent class is invalid and needs recompilation:
 Class fflib_Answer : Dependent class is invalid and needs recompilation:
 Class fflib_InvocationOnMock : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MethodVerifier.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_VerificationMode : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_Mocks.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_MyList : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type test
classes/fflib_MyList.cls(67,15):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocks : Method does not exist or incorrect signature: void createStub(System.Type, fflib_ApexMocks) from the type tes

**Comment by afawcett** [comment]
@techmatrixconsulting  Do you happen to also have a class called Test in your org? This can mask the system version and can be a cause of this error?

**Comment by afawcett** [comment]
@techmatrixconsulting Let me know if your last suggestion didn't get you going and we can re-open this discussion. 👍
