### ISSUE TITLE
Not able to edit any fields in my custom object Application__c

### ISSUE THREAD

**Issue by cacosta1** [afawcett/declarative-lookup-rollup-summaries#534]
I have the 2.9 version of DLRS and I cannot edit any fields in my custom object Application__c in my sandbox.  When I contacted Salesforce support, they looked at the debug log and said it's DLRS, your managed package, and we cannot help you with this.  I found another issue with JodieM Error on Custom Object with RecordType #470 and I tried to remove all of the triggers and replace them, but even after that I still cannot edit any fields.  I know that her issue was regarding the RecordType and for me it's only happening with my student applications that rely heavily on DLRS for several fields.  I'm sorry too because I am a newbie and I couldn't see anything in my debug log that referred to record type.

**Comment by afawcett** [comment]
Hi @cacosta1 can you share some more informaton on the steps your performing, error your getting and what is in your debug log? Thanks.

**Comment by cacosta1** [comment]
Never mind!  I deactivated DLRS to see if that was causing the issue and I still got the error.  The long and short of it is that I just deleted by sandbox and reinstalled it and it's now working fine.

Appreciate your reply though!
