### ISSUE TITLE
Cannot get it to work since updating. 

### ISSUE THREAD

**Issue by jillmyers** [afawcett/declarative-lookup-rollup-summaries#537]
We recently updated to version 2.9 with this tool and now the roll-ups are no longer working. 

I have tried everything I can think of. I have recreated the summaries, even tried to do them in the pilot and still no luck.

The annoying thing is I am not getting any errors in the logs, so I cannot figure out what is happening?

Thanks!

**Comment by afawcett** [comment]
@jillmyers can you give me a bit more detail on what type of rollups you have? realtime or scheduled? if scheduled, what type of scheduled (see wiki page for the difference)? What steps are you doing to confirm they are not working? Has anything else changed in your org or objects?

**Comment by jillmyers** [comment]
@afawcett 
Thank you for your response I am currently using 2 roll-ups in Realtime. We are pulling in active subscription information from our managed billing software object. These were working fine before the update so I have not manipulated any of the child/parent info.

When I click calculate I am not getting any error messages so I am not sure where to go from here. Upon clicking calculate I am not seeing the accounts with multiple subscriptions rollup.

Here is a screen shot of the roll-up I have created.
![screen shot 2017-08-07 at 3 57 54 pm](https://user-images.githubusercontent.com/28907558/29047522-3f3372b4-7b89-11e7-8bb9-b4bf87ee3761.png)

Here is an account screen shot with 2 subscription dates:
![screen shot 2017-08-07 at 3 59 46 pm](https://user-images.githubusercontent.com/28907558/29047589-8cde502e-7b89-11e7-81e6-9de950adcfb2.png)

But then the rollup field shows this:
![screen shot 2017-08-07 at 3 59 57 pm](https://user-images.githubusercontent.com/28907558/29047602-97f319b8-7b89-11e7-9d24-9770c1c1e35c.png)
(FYI Renewal Date is the field name. Last_Renewal_Date__c is the API name but it is the same field)

Where should I look from here?

Thanks!

**Comment by afawcett** [comment]
Try putting Last_Renewal_Date__c in the Field to Order By field.

**Comment by afawcett** [comment]
@jillmyers let me know if my last suggestion helped? We can re-open the issue for sure. 👍
