### ISSUE TITLE
Salesforce Session Settings

### ISSUE THREAD

**Issue by jschwaem** [afawcett/declarative-lookup-rollup-summaries#539]
After enabling Lock sessions to the IP address from which they originated, the "manage lookup rollup summaries" page displays the error "Salesforce Metadata API connection failure, click the link below to configure."

Has anyone experienced something similar?

**Comment by afawcett** [comment]
Yes this is covered in the known issues list. https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues
