### ISSUE TITLE
Review all error messages below to correct your data. Only Date/DateTime/Time/Numeric fields are allowed

### ISSUE THREAD

**Issue by rbhagat30** [afawcett/declarative-lookup-rollup-summaries#540]
I am trying to count the no of tasks (created by app) on the lead object.but i am getting error.
![lookup2](https://user-images.githubusercontent.com/29428190/29108364-451e1368-7cfc-11e7-8fa0-0c5fe383aae8.png)
is is possible to count the particular task type through this tool .if not can you please help me with the field information.
FYI:- i am using isfromapp check box field to  differentiate the tasks. here  want to count the task where checkbox value is true.

**Comment by afawcett** [comment]
Just use "Id" in the Field to Aggregate and make sure the field Number_of_Lead_Touches__c field is a number field. It also looks like your Relationship Field is wrong? This should be the lookup field between the Task child and the Lead parent, this should be WhatId i believe. Many folks are doing this kind of rollup, if you still encounter issues i suggest you try the Salesforce Community Chatter group for the tool (see README for this repo).
