### ISSUE TITLE
Validation rules triggering 

### ISSUE THREAD

**Issue by khadija87** [afawcett/declarative-lookup-rollup-summaries#541]
Hi,
I created lookup summary to calculate last activity date based on certain user roles, I have a validation rule that prevent making changes to closed opportunities but it excludes the lookup summary Aggregate Result Fields. when a user that doesn't match the relationship criteria tries to log an activity they get this error:

Apex script unhandled trigger exception by user/organization: XXXXXXXX/00XX0000000XXXX

dlrs_TaskTrigger: execution of AfterUpdate

caused by: System.DmlException: Update failed. First exception on row 1 with id XXXXXXXXXXX; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Only Operations or Finance can set the stage to Closed Won or Closed Booked: []

Class.dlrs.RollupService.Updater.updateRecords: line 1269, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1312, column 1
Class.dlrs.RollupService.updateRecords: line 1240, column 1
Class.dlrs.RollupService.handleRollups: line 846, column 1
Class.dlrs.RollupService.triggerHandler: line 301, column 1
Trigger.dlrs_TaskTrigger: line 7, column 1

Any ideas why the validation rule triggers since the roll up summary is not supposed to update the record that don't match the relationship criteria, all help is much appreciated

Thank you!

**Comment by JeffSieck** [comment]
I have encountered a very similar issue, a trigger which was inactive being triggered by the test code when deploying child trigger.  I switched to using the "test code" field, but now get strange token errors.

**Comment by afawcett** [comment]
In your validation rule logic are you check for the condition only when the Stage field changes?

**Comment by khadija87** [comment]
@afawcett No, because I don't want anyone to change anything in closed opportunities. I added these lines to the Validation rule:
NOT(ISCHANGED(Sales_Last_Activity__c)), 
NOT(ISCHANGED(SDR_Last_Activity__c)), 
NOT(ISCHANGED(CSM_Last_Activity__c)), 
to prevent it from running if these fields (Aggregate Result Field) are the ones being changes and it works when I update them manually but it doesn't when the Roll up summary is trying to update them 

the other thing that I don't understand is why the roll up summary is trying to update the Aggregate Result Fields when the relationship criteria is not met, like an activity being logged by someone who is not an SDR, Sales or CSM

**Comment by afawcett** [comment]
@khadija87 hows things with this issue? Did you get to the bottom of it?

**Comment by Agroag** [comment]
Hi - I'm having a similar issue. DLRS scheduled calculate is ignoring validation rules. This is causing the recurring donation to refresh related Opportunities, which we don't want.

**Comment by afawcett** [comment]
@Agroag its impossible to ignore validation rules in the platform, you must be using ISCHANGED in them and thus if no values are changing the validation rules are not firing, this is by design of course. So i think what you mean is we want DLRS not to update records needlessly in full recalc scheduled mode?

**Comment by Agroag** [comment]
Hi @afawcett  yes I was using an ISCHANGED with an AND formula.  I would like it to not update the record unless the new value is greater than 0.00.  We have roll ups on none open ended pledges and the scheduled roll ups are causing opportunity refreshes and i thought a validation rule would stop those records from being edited, but it's not working.

**Comment by afawcett** [comment]
Got it, in this case, we need this enhancement. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/370
