### ISSUE TITLE
Relationship Criteria Fields

### ISSUE THREAD

**Issue by nicholassewitz** [afawcett/declarative-lookup-rollup-summaries#542]
If the Relationship Criteria is `OwnerId IN (SELECT Id from User WHERE UserRoleId IN ('00EC0000001TvyD', '00EC0000001o2se', '00EC0000001TwA4', '00EC0000001TvyI'))`

what should the relationship criteria fields be listed as.

**Comment by tet3** [comment]
```OwnerId```
 The Relationship Criteria Fields are those fields checked for a change to trigger a rollup recalc.

**Comment by afawcett** [comment]
Spot on @tet3
