### ISSUE TITLE
INVALID_PERSON_ACCOUNT_OPERATION, cannot reference person contac

### ISSUE THREAD

**Issue by danhowellnz** [afawcett/declarative-lookup-rollup-summaries#544]
I am struggling to track down the cause of this error. 
I have a flow that creates a person account and then adds a campaign member. It works with rollups turned off and then with them turned on I get this. 

If I add them to the campaign seperately (after the flow created the person account). I don't hit an error.

The roll up is:
Parent: Contact
Child: CampaignMember
Relationship: ContactId
Field to Aggregate: custom_datetime__c
Aggregate Operation: Min
Aggregate Result Field: custom_datetime__c
Calculation Mode Realtime
Aggregate Operation System

Error Occurred: This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_CampaignMemberTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 1 with id 0037F0000056ibCQAQ; first error: INVALID_PERSON_ACCOUNT_OPERATION, cannot reference person contact: [] Class.dlrs.RollupService.Updater.updateRecords: line 1269, column 1 Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1312, column 1 Class.dlrs.RollupService.updateRecords: line 1240, column 1 Class.dlrs.RollupService.handleRollups: line 872, column 1 Class.dlrs.RollupService.triggerHandler: line 301, column 1 Trigger.dlrs_CampaignMemberTrigger: line 7, column 1. For details, see

**Comment by danhowellnz** [comment]
Ok, I think I have tracked it down. 

If I create a person account by creating a contact and a matching account and then update the account with person account recordtypeid then Salesforce merges the account and contact. However, I think there is some sort of delay in the process. So the trigger fails as the merge hasn't finished.

If I create a person account by just creating an account straight with the personaccount recordtypeid. It is created instantly and no delay and the trigger works. 

If you have something to fix in the dlrs tool that would be awesome. I split the creation of person accounts into two calls  to keep my flows generic and can be used in orgs with or without PAs.

**Comment by afawcett** [comment]
I think this relates to how merging is handled in the tool (assuming your on the latest version). Some of the processing is differed to background (due to a platform restriction). If you check back through the release history of the tool you can find more information on the merge support. 👍
