### ISSUE TITLE
Scheduling Page

### ISSUE THREAD

**Issue by danhowellnz** [afawcett/declarative-lookup-rollup-summaries#545]
Hi Andy, 

Firstly, you are a master, I want to use your simple cron job scheduling tool in a declarative scheduling tool I am building and maybe with DouglasCAyers tool (https://github.com/DouglasCAyers/sfdc-add-campaign-members-by-report/issues/14)

Firstly, I would like permission to base it off your page, controller and test class. Credit wil be given in the source. 

I also redid it in lightning styles to make it cleaner. Happy to push that back for your VF page if you are interested
![image](https://user-images.githubusercontent.com/21028276/29296331-b8c74efa-81ad-11e7-9e37-c08a2745c79a.png)

**Comment by afawcett** [comment]
Most kind and yes totally fine, go for it! 👍

**Comment by afawcett** [comment]
Oh and yes, a Lightning Theme'd contribution back would be excellent, thank you! 👍
