### ISSUE TITLE
How to Delete Active Triggers and Classes

### ISSUE THREAD

**Issue by bhavnabanodha** [afawcett/declarative-lookup-rollup-summaries#546]
Hi Team,

I created one Summary Record to count number of Events for Account. Now I no more need it. So, I deleted that but there are some active classes and triggers still exists relating to the Summary Record I created. How can I delete those?

Thanks in Advance!!!

**Comment by afawcett** [comment]
Two options...
1. Easy one, recreate your rollup record and use the Manage Child Triggers button to remove it.
2. Use a Sandbox and delete the trigger and test class, then Change Set to deploy the removal.
