### ISSUE TITLE
Issue with trigger on Campaign Member

### ISSUE THREAD

**Issue by acarlesimo** [afawcett/declarative-lookup-rollup-summaries#548]
I have a field called "Score" on the Campaign Member record.  I'm trying to use the DLRS to average the Score on the Contact record.  However, I'm getting this error message:

Error: Invalid Data.
Review all error messages below to correct your data.
Apex trigger dlrs_CampaignMemberTrigger caused an unexpected exception, contact your administrator: dlrs_CampaignMemberTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Contact for CampaignMember: Class.dlrs.RollupService.handleRollups: line 801, column 1

It seems the issues is on the field called "Contact" but I'm not sure how to fix this.  Thoughts?  Is there any way to do this?

**Comment by aheber** [comment]
@acarlesimo could you share content of your rollup? If I had to guess I'd say your rollup has the Relationship field as Contact where it should be ContactId
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_campaignmember.htm

If not that then hopefully it will be more obvious with a screenshot of how your rollup is configured.

**Comment by acarlesimo** [comment]
That was the Issue - THANK YOU!!!

**Comment by aheber** [comment]
Excellent.

@afawcett, please close.
