### ISSUE TITLE
Relationship criteria error

### ISSUE THREAD

**Issue by mavenmelody** [afawcett/declarative-lookup-rollup-summaries#549]
Parent object: SFDC_Acct_Plan__c
Child: Opportunity
Relationship Field: Name
Field to aggregate: Amount
Relationship Criteria fields: StageName, CloseDate

I am trying to populate new fields (e.g., YTD Revenue, 2016 Revenue, 2015 revenue)  buy using DCRU to look at Opportunities in closed won stage and aggregating the amount field within relevant date ranges.

So for my YTD rollup, my relationship criteria is StageName=Closed Wone AND CloseDate >= 01-01-2017.

And I get this error (screen shot attached):

Error: Relationship Criteria '(StageName= Closed Won AND CloseDate>= 01-01-2017)' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'expecting a colon, found 'Closed''

I cannot figure out the issue.  I've not yet tried to build the 2015 or 2016 rollup summaries where the criteria would be StageName=closed won and then somehow specify the date range of Jan 1, 2015 to Dec 31, 2015, etc... (not sure how to do this either).

Can you help?

![dru_rc_error](https://user-images.githubusercontent.com/31253637/29579006-3bd32f12-8726-11e7-86bc-bfc1baf912f7.JPG)

**Comment by aheber** [comment]
@mavenmelody your core problem is two fold
StageName = Closed Won AND CloseDate = 01-01-2017 should actually be written
StageName = 'Closed Won' AND CloseDate = 2017-01-01

You'll notice the single-quotes around the text and the YYYY-mm-DD date formatting.


You may still want to build this a little differently, I would probably go with the following for the YTD query
IsClosed = true AND IsWon = true AND CloseDate = THIS_YEAR

That change will allow for significantly more flexibility in other configurations in your org without having to revisit the query.

Hope that helps.

**Comment by JenNelsonChicago** [comment]
Hey @afawcett and @aheber :-)  Hope you are both well.  I just installed the current version (2.9) on a Winter 18 Org and I am getting the same error as above when my Relationship Criteria contains an "OR"

If I go in Workbench, my query is 
**SELECT count() FROM Route_Location__c WHERE Loads_To__c = 'Highly Desirable' OR Loads_From__c = 'Highly Desirable'**

So, on my DLRS, the Relationship Criteria I am trying to save is
**Loads_To__c = 'Highly Desirable' OR Loads_From__c = 'Highly Desirable'**

But I am getting the same error as above.
**Error: Relationship Criteria 'Loads_To__c = 'Highly Desirable' OR Loads_From__c = 'Highly Desirable'' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: OR'**

If I use "AND" in my criteria, no error...only OR.

**Comment by DanDonin** [comment]
Put ( )'s around your OR

**Comment by DanDonin** [comment]
So field1 = x and (x=y or x=z)

**Comment by JenNelsonChicago** [comment]
Thank you @DanDonin !

**Comment by afawcett** [comment]
Thanks @DanDonin @aheber for your support on this ticket. 👍
