### ISSUE TITLE
Error on Lookup Rollup Summary

### ISSUE THREAD

**Issue by kogelman** [afawcett/declarative-lookup-rollup-summaries#550]
I am trying to create the attached lookup rollup summary (Rollup) to rollup timecards onto a contact record.  I keep getting the attached error (Error Message) and I don't know why.  Can someone help me troubleshoot?  
![error message](https://user-images.githubusercontent.com/31254838/29580755-f1068fc8-872b-11e7-80c3-23322abf0961.JPG)
![rollup](https://user-images.githubusercontent.com/31254838/29580801-218f58b4-872c-11e7-8691-371e78e56f00.JPG)

**Comment by aheber** [comment]
@kogelman FinancialForce PSA has a lot of objects and interconnected dependencies. There might be a better way to set this up but this is what I've come up with, fairly quick and dirty. Your org might have different requirements and validation rules that come into play but this worked in my FF org.

You'll need custom test code to make this work. In the Advanced section of the Page Layout, in the Test Code field you'll want to add this:
![image](https://user-images.githubusercontent.com/2173116/29590476-47bb337a-8757-11e7-84f4-6ca0068345d8.png)

```
Contact c = new Contact(LastName = 'Last'); 
Insert c; 
pse__Permission_Control__c pc = new pse__Permission_Control__c( 
pse__User__c = UserInfo.getUserId(), 
pse__Billing__c = true, 
pse__Staffing__c = true, 
pse__Timecard_Entry__c = true, 
pse__Resource__c = c.Id 
); 
Insert pc; 
pse__Proj__c proj = new pse__Proj__c(pse__Allow_Timecards_Without_Assignment__c=true); 
Insert proj; 
dlrs.RollupService.testHandler( 
new pse__Timecard_Header__c( 
pse__Project__c = proj.Id, 
pse__Resource__c = c.Id, 
pse__Start_Date__c = Date.today(), 
pse__End_Date__c = Date.today().addDays(6), 
pse__Billable__c = false));
```

I think that is the bare minimum to make this work, short of any tricks I'm not aware of. I was able to deploy the rollup trigger with that custom test code.

**Comment by kogelman** [comment]
Hi Heber,

Thanks for the help, however when I paste this in the Test Code field I am getting the error that the data is too large.  Any idea how to correct?  Additionally, while I have you, I want to also add a filter to this rollup so that it only looks at one specific project.  Would this work? I’m not sure if I can use AND in this way

[cid:image002.png@01D31CD6.E0AA69C0]

Thanks for the help.  I don’t have a developer at my disposal so I need to try to get this figured out on my own.


| Kara Kogelman | Delivery Operations Specialist | LLAMASOFT<http://www.llamasoft.com/> INC. |
| Office: 734.418.3119, Ext.278
www.LLamasoft.com<http://www.llamasoft.com/>

**Comment by aheber** [comment]
@kogelman I think the size is a problem because the new updates of the DLRS use Custom Metadata which doesn't have fields larger than 255. Unfortunately the test code I came up with is ~600 characters. You can still use the traditional custom object for the configuration data, you can't migrate it inside of a change set but otherwise you should be fine.

You'll want to find the Lookup Rollup Summaries tab and create a legacy rollup which will work wonderfully and enable you to do this. The other option is that someone can come up with test code that is smaller and will accomplish the purposes.

You can track this in #304 which will hopefully be supported in the near future.

**Comment by aheber** [comment]
As for your project filtering, you'll want to update the Relationship Criteria field from
`pse__End_Date__c = THIS_YEAR`
to
`pse__End_Date__c = THIS_YEAR AND pse__Project__r.Name = 'PTO Project'`

Swapping PTO Project out for whatever the name of your PTO project actually is. If I'm understanding your goals correctly that should work.

**Comment by kogelman** [comment]
Hi Heber,

I tried this and am still receiving the below error.  Additionally, since I added in the extra criteria of the project name does the test code you supplied me with need to be updated?  I really appreciate your help on this.

[cid:image002.png@01D31FD5.353865E0]

| Kara Kogelman | Delivery Operations Specialist | LLAMASOFT<http://www.llamasoft.com/> INC. |
| Office: 734.418.3119, Ext.278
www.LLamasoft.com<http://www.llamasoft.com/>

**Comment by kogelman** [comment]
Hi Heber,

I was wondering if you might be available to jump on a call and help me work through this new error.  Please let me know if you can.  Thanks.

| Kara Kogelman | Delivery Operations Specialist | LLAMASOFT<http://www.llamasoft.com/> INC. |
| Office: 734.418.3119, Ext.278
www.LLamasoft.com<http://www.llamasoft.com/>

From: Kara Kogelman
Sent: Monday, August 28, 2017 8:11 AM
To: 'afawcett/declarative-lookup-rollup-summaries' <reply@reply.github.com>; afawcett/declarative-lookup-rollup-summaries <declarative-lookup-rollup-summaries@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [afawcett/declarative-lookup-rollup-summaries] Error on Lookup Rollup Summary (#550)

Hi Heber,

I tried this and am still receiving the below error.  Additionally, since I added in the extra criteria of the project name does the test code you supplied me with need to be updated?  I really appreciate your help on this.

[cid:image001.png@01D320C8.27E12190]

| Kara Kogelman | Delivery Operations Specialist | LLAMASOFT<http://www.llamasoft.com/> INC. |
| Office: 734.418.3119, Ext.278
www.LLamasoft.com<http://www.llamasoft.com/>

**Comment by aheber** [comment]
Would love to setup a time to get together. Email me at anthony dot heber gmail com and we can get some time set aside.

The test code shouldn't need to be changed based on your filter.

**Comment by afawcett** [comment]
Hey both, i hope you managed to figure this out, if not we can re-open this case. Meanwhile, Custom Metadata Types now finally support large text fields, so there is another enhancement issue that covers adding support for large text code fields (noticed that was in the discussion above). Again thanks @aheber for your support here! 👍
