### ISSUE TITLE
deploying trigger taking too long

### ISSUE THREAD

**Issue by tylerzikaHM** [afawcett/declarative-lookup-rollup-summaries#551]
I'm trying to deploy the trigger that allows real time updates. 
<img width="841" alt="screen shot 2017-08-25 at 4 26 10 pm" src="https://user-images.githubusercontent.com/30838406/29736009-41f8dbb0-89b2-11e7-8563-368d13cd2f43.png">

What should I do if it doesn't deploy? I think I've been waiting close to 30 minutes.

**Comment by aheber** [comment]
You can monitor the actual deployment through the Deployment Status page in
Setup. From there you can see what stage it is in.

**Comment by afawcett** [comment]
Over the years, this has bee no optimized to only run tests for the deployed trigger code and not run managed package tests, so i am not sure why it would take so long. The only other thing i can think is some salesforce instances do queue deployments (if that instance is under high load) and this would show in the current UI above as being in progress. @aheber recommendation is the best to determine what is going on.
