### ISSUE TITLE
Error deploying Child Trigger on NPSP object npsp__Allocation__c

### ISSUE THREAD

**Issue by BHFoundation** [afawcett/declarative-lookup-rollup-summaries#554]
In reference to this closed issue - Error deploying Child Trigger on NPSP object npe03_Recurring_Donation #490

I am having similar issues and could use some assistance.  I am trying to roll up the GAU Allocations to the Opportunity record. We are recording the GAU Allocations through a lookup on the opportunity and upon save this creates the Allocation records. But I need to verify the allocation totals equal the opportunity total. Any assistance would be greatly appreciated.

Here is the error I am receiving - looking for assistance on the test code needed for this roll-up.

![image](https://user-images.githubusercontent.com/31489994/29896917-6fb45624-8da4-11e7-891f-554f3f9998d4.png)

**Comment by BHFoundation** [comment]
Attached is the test code we are attempting along with the new error code
![image](https://user-images.githubusercontent.com/31489994/29947423-2b335d12-8e6f-11e7-88a0-c7ce1fa8cffe.png)

**Comment by aheber** [comment]
@BHFoundation a few notes;

1. No need to manage the savepoint yourself, that is built into the test infrastructure
2. I think the format of your CloseDate is incorrect, I believe you can move it to be 1980-01-01 and drop the time clarity as that date field doesn't support time. You could also switch to use Date.Today() if the former doesn't work.

Hope that helps. I don't know the NPSP package or have any orgs with it installed right now or I could try and replicate for you.

**Comment by BHFoundation** [comment]
We made the corrections above and have tried to deploy again - now we are receiving the following error:  Anyone have any assistance they could offer??
![image](https://user-images.githubusercontent.com/31489994/30171983-15c99d3e-93b9-11e7-9cd8-69a09ea6dbf0.png)

**Comment by aheber** [comment]
@BHFoundation could you attach a screenshot of your current rollup configuration? I would like to see what you have for test code at this time.

**Comment by BHFoundation** [comment]
Andrew - please find below screenshots for the current set-up and manage apex trigger deployment.  Thank you in advance for any assistance you could offer.

![image](https://user-images.githubusercontent.com/31489994/30555060-0a37883a-9c6c-11e7-83d2-1de5680a32eb.png)

![image](https://user-images.githubusercontent.com/31489994/30555067-0e9a414c-9c6c-11e7-8975-0b2ea10e0d2d.png)

**Comment by aheber** [comment]
@BHFoundation taking a quick look it seems your Relationship Field is not setup correctly. I don't think ID is correct, this would imply the ID field on the Allocation is where the Id of the General Accounting Unit is stored. I think you should start by switching that to npsp__General_Accounting_Unit__c and seeing what happens.

I don't know that this will correct your 0% coverage but having the rollup configured correctly is a good first step.

It appeared you were running custom test code in your original post. Is that not happening anymore? Are you still receiving an error when trying to deploy the trigger?

**Comment by BHFoundation** [comment]
Sorry - we have been trying several options - please find below the updated Relationship Field and custom test code.  We are receiving the following error.

![image](https://user-images.githubusercontent.com/31489994/30557200-1ff37ca4-9c73-11e7-84e5-6bed7d97f1df.png)

![image](https://user-images.githubusercontent.com/31489994/30557218-2a8f1f38-9c73-11e7-87cb-8c01298eeda9.png)

**Comment by afawcett** [comment]
Can you try this from execute anonymous in the dev console...

~~~~
SavePoint sp = Database.setSavePoint();
Opportunity opp = new Opportunity(Name='Test', StageName='Received in Full?', CloseDate=Date.Today());
insert opp;
insert new npsp__Allocation__c(npsp__Opportunity__c=opp.id);
Database.rollback(sp);
~~~~

I am wondering if the dlrs.RollupService.testHandler is masking an error we are not seeing here.

Andy

**Comment by BHFoundation** [comment]
Per your suggestion we finalized the test code to the code listed below - this corrected the error we kept getting pertaining to the allocation amount/percentage being required:  

Opportunity opp = new Opportunity(Name='Test', Amount=100,StageName='RIF', CloseDate=Date.Today());
insert opp;
insert new npsp__Allocation__c(npsp__Opportunity__c=opp.id, npsp__Amount__c=100, npsp__General_Accounting_Unit__c= 'a0e4100000A9vUr');

THANK YOU SO MUCH FOR ALL OF YOUR ASSISTANCE!!!

**Comment by afawcett** [comment]
@BHFoundation thats good to know! 👍  Thanks for the update. Regarding the character limits, i have an enhancement i can now implement now custom metadata has large text field support.

**Comment by aaronsteinbergmadow** [comment]
Hi all! I'm trying to do something similar to BHFoundation, but am finding myself a bit lost on the subject of test code.

I'm attemping to create a DLRS field that will count the number of GAU Allocation records associated with a given Opportunity. The GAU Allocation records have a lookup to the Opportunity.

The challenge I'm encountering is getting zero percent code coverage and this error message: "dlrs_npsp_AllocationTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Enter a value in either the Amount field or the Percent field.: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_npsp_AllocationTest.testTrigger: line 11, column 1"

Based on this thread, it sounds like the answer is to write some test code so the test stops trying to create a record where the Amount or Percent is blank, but I'm not quite sure how to convert BH Foundation's Code, given we're not looking at the same objects (they were looking at General Accounting Units and GAU Allocations). 

Could anyone provide any guidance?

**Comment by afawcett** [comment]
@aaronsteinbergmadow It might be worth posting this ask for test code for these objects in the community chatter group (see README for link).
