### ISSUE TITLE
Query Returns Results But Field In Salesforce Is Empty

### ISSUE THREAD

**Issue by christinemarshall** [afawcett/declarative-lookup-rollup-summaries#555]
![rollup help 5](https://user-images.githubusercontent.com/31542642/29973484-9f107c02-8f27-11e7-8130-5b6b11f10f55.JPG)
I've created a query in my sandbox. The code doesn't return any errors and returns results in both workbench and the developer console. However when I check records that match my criteria in Salesforce, my field is empty! I've worked through all the documentation I could find and posted on the success community but without any solutions. 

This is my relationship criteria:
(Deal_Owner_Role__c = 'Client Relationship Managers' AND RecordTypeId = '0122400000026Vg' AND BU__c = 'Summit' AND Sold_On_Last_12_Months__c = 'Sold On Last 12 Months')

This is my SOQL query which returns matching records:
SELECT Deal_Count__c FROM Order WHERE Deal_Owner_Role__c = 'Client Relationship Managers' AND BU__c = 'Summit' AND Sold_On_Last_12_Months__c = 'Sold On Last 12 Months' AND RecordTypeId = '0122400000026Vg'

I am trying to get a count of orders (that match certain criteria) on the relevant contact record. 

I am doing a count and my field on contact is a number field. I've tried using both ID to aggregate and also a formula field that assign each record 1 (power of one). 

The rollup summary is active. I have checked all my field names and included the __c at the end etc. 
![rollup help 4](https://user-images.githubusercontent.com/31542642/29973470-93dde7ac-8f27-11e7-817d-5492de526601.JPG)

**Comment by MarcDBehr** [comment]
@christinemarshall Silly question - have you deployed the trigger (Clicked the 'Manage Child Trigger' button and then deployed the code?

**Comment by christinemarshall** [comment]
Hi Marc, 

I have! I've been following 'How to DLRS' by Dan Kludgy and followed the steps. I created the DLRS, saved, clicked the manage child trigger button, pressed deply, then made the DLRS active and saved again.
