### ISSUE TITLE
Manage Child Trigger Button not appearing

### ISSUE THREAD

**Issue by CallaV23** [afawcett/declarative-lookup-rollup-summaries#557]
![image](https://user-images.githubusercontent.com/31679082/30092737-e06aea48-9314-11e7-91b7-ef1d23da416f.png)
This is what it should be but this is what I see:
![image](https://user-images.githubusercontent.com/31679082/30092751-f24ba464-9314-11e7-9bbf-b1109afd1364.png)

**Comment by DanDonin** [comment]
Save it then what do you see?

**Comment by CallaV23** [comment]
![image](https://user-images.githubusercontent.com/31679082/30093022-b5ff1f20-9316-11e7-8052-c11858c39533.png)
This is what then happens

**Comment by DanDonin** [comment]
Turn off the active checkbox. Click save. Deploy trigger. Reactivate.

**Comment by afawcett** [comment]
@CallaV23 did this help?

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄

**Comment by MaxinitoEl** [comment]
I know this is from 4 years ago, but I only just installed DLSF a week ago. I tried this before and had the same issue, but couldn't get it solved. It is now 2022 and still no buttons. I even tried to switch to Classic to see if they'd appear, but they don't. Is there a step in the implementation that I may have missed? I followed everything, but no buttons.

**Comment by aheber** [comment]
@MaxinitoEl, this issue is closed. If you can open a new issue then I will try and give you a hand figuring out your buttons.
