### ISSUE TITLE
How to call Google spreasheet apis from salesforce

### ISSUE THREAD

**Issue by SMH74** [afawcett/declarative-lookup-rollup-summaries#560]
I am new to apex development. Can anyone help me how to code to call google spreadsheet APIs on button click using google HTTP request for 
PUT https://sheets.googleapis.com/v4/spreadsheets/{spreadsheetId}/values/{range} and
GET https://sheets.googleapis.com/v4/spreadsheets/{spreadsheetId}/values/{range}
I have to update 5 cell values in a sheet stored on google drive from Salesforce.

**Comment by afawcett** [comment]
https://github.com/financialforcedev/ffhttp-googledrive
