### ISSUE TITLE
How to trigger rollup by ISCHANGED formula

### ISSUE THREAD

**Issue by drroundcorner** [afawcett/declarative-lookup-rollup-summaries#561]
Hi,

Does declarative-lookup-rollup-summaries support triggering a rollup when a field is changed and re there limitations on the field/data types where this can be done?  What is the syntax I need to use in the "Relationship Criteria" field to do this?

Thanks!!!
Dan

**Comment by aheber** [comment]
@drroundcorner I don't understand the requirement. Are you saying rollup under error scenarios or rollup only when a combination of values are present?

**Comment by afawcett** [comment]
By default the tool only monitors for changes in the field that you are rolling up (the child field). If you want it to monitor changes in other fields (such as those you have put in your criteria). List them in the 'Relationship Criteria Fields' field.
