### ISSUE TITLE
No dropdowns in rollup setup

### ISSUE THREAD

**Issue by cesera** [afawcett/declarative-lookup-rollup-summaries#562]
I have just installed this app in my sandbox, as I liked what I read about it. On [this blog post](https://andyinthecloud.com/2014/04/09/new-declarative-rollup-tool-release-community-powered/
![capture]
)  it says that there should be dropdown boxes with object names, etc when you create a new rollup. However when I click on 'Manage Lookup Rollup Summaries' I get a page entitled: "Manage Lookup Rollup Summaries - Custom Metadata Pilot', but there are no dropdown boxes there, just normal text boxes I need to fill in with API names. See here for a acreenshot: (https://user-images.githubusercontent.com/9389629/30477121-0062839c-9a04-11e7-8c94-54a0ac2d7653.PNG)

Have I done something wrong when I installed the app?

**Comment by aheber** [comment]
@cesera you've done nothing wrong. That is an older UI that didn't make it through some other changes. For now you want to use the text fields and type in your field/object names.

**Comment by cesera** [comment]
OK, thank you for letting me know. And thank you for this add on, it works great.

Are there any plans to reintroduce the UI with the dropdown boxes? Would make this even easier to use.

**Comment by aheber** [comment]
This isn't my project, I just help out as I can. I think the drop downs could be added as soon as someone wanted to put in the dev time, I don't think they were discarded because they were bad. They were the effort of another contributor and that work hasn't been ported/duplicated over to the newer configuration screens. I could be totally wrong though.

**Comment by afawcett** [comment]
Thanks @aheber your statement is spot on as to why there are no drop downs currently. And for sure, i want to get these back. I am due to re-implement the UI (hopefully for the last time in the foreseeable future) in Lightning, and these drop downs will be back then!  👍
