### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by linzbar** [afawcett/declarative-lookup-rollup-summaries#563]
Getting the following errors when attempting to uninstall app from org. Screenshot attached as well.

Apex Class | RollupService | Component is in use by another component in your organization. dlrs_OpportunityTrigger
Apex Class | RollupService | Component is in use by another component in your organization. dlrs_OpportunityTest
Apex Class | RollupService | Component is in use by another component in your organization. dlrs_AccountTest
Apex Class | RollupService | Component is in use by another component in your organization. dlrs_AccountTrigger

<img width="942" alt="screen shot 2017-09-17 at 3 33 25 pm" src="https://user-images.githubusercontent.com/32042226/30524231-a784948e-9bbd-11e7-9cb2-d96348507477.png">

**Comment by DanDonin** [comment]
Go to each DLRS Record, remove the child trigger then try and uninstall
again

**Comment by afawcett** [comment]
Thanks @DanDonin . @linzbar this is the solution.
