### ISSUE TITLE
Remote Site setting not created

### ISSUE THREAD

**Issue by ST147** [afawcett/declarative-lookup-rollup-summaries#565]
After installing I clicked on the 'Create remote setting' button. However I cannot see any Remote setting under 'Remote settings in Salesforce'. Needlesss to say I'm getting the ''Salesforce Metadata API connection failure, click the link below to configure.'' error. I'm logged in as a System Admin. Please help. Thanks

**Comment by afawcett** [comment]
There is a DEBUG ONLY message at the bottom of the page where the remote site is added, what does that say? Also please check the README of this project for known issues around Session settings in our Salesforce org.

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
