### ISSUE TITLE
Lookup Rollup Summary Schedule Items Using Huge Amount of Storage

### ISSUE THREAD

**Issue by nicholassewitz** [afawcett/declarative-lookup-rollup-summaries#566]
The Lookup Rollup Summary Schedule Items Object is taking up a huge amount of storage space in my SF org. Anyone have recommendations to lesson the size?

**Comment by aheber** [comment]
@nicholassewitz it sounds like you are not clearing these out. Do you have a scheduled job setup to process these? The Schedule Items is the "queue" of changes that have yet to be processed. If you have a schedule job setup and active but haven't setup the actual processing job then this can happen.
More information on the wiki page, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups under the Incremental Calculate section.

**Comment by nicholassewitz** [comment]
@aheber I think that the wiki page might be out of date as you can now schedule the apex job directly on the manage rollup page as you can see here https://cl.ly/0Q1m3O0Y2G0L.

My rollups are all scheduled https://cl.ly/3x42380D0M2K. 

What I'll try do is clear out that object and see if it builds back up again.

**Comment by aheber** [comment]
You could also see if there is a pattern for any that are left behind, maybe it is a specific job that is not being run. You could review the lsrs__LookupRollupSummary(2)__c fields on the schedule items to see if there is any commonality.

Aside from that I would do as you're doing and cancel the current schedules and reschedule.

Please let us know if any of these solutions fix your problem. Thanks.

**Comment by afawcett** [comment]
There are two (and addmittly rather confusing) schedule modes in the tool. Please take a look at this wiki https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. If your using the Scheduled Full Calculate there should be no records in this object at all, its not used. If you still see them it suggests you still have some rollups configured to use Scheduled Incremental Calculate and thus those triggers are dumping records into the  Lookup Rollup Summary Schedule Items, but as @aheber stated if you don't have the RollupJob apex class scheduled, nothing will be consuming them and deleting them. Hopefully the wiki explains this better along with this message. If not please let us know. 👍

**Comment by praveenk03** [comment]
I understand that this is a closed thread. But, I am faced with the same issue, and I have gone through the comments here. However, I am not able to get a clear understanding on whether we can delete the records in **Lookup Rollup Summary Schedule Items** objects without any further actions on those records, will that disturb any of the current rollups. Please let me know if I should post it in a different thread.
