### ISSUE TITLE
Error: Salesforce Metadata API connection failure, click the link below to configure.

### ISSUE THREAD

**Issue by rbhagat30** [afawcett/declarative-lookup-rollup-summaries#567]
Hi,

I am experiencing the same problems as reported in issue #102.

I've installed the package 1.16, also tried uninstalling and installed 1.15 but receive the same error message. Re-installed 1.16 and currently receive the error message:

Unable to connect to the Salesforce Metadata API.
A Remote Site Setting must be created in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

Under Remote Sites, I have an entry for dlrs_mdapi setup as https://--dlrs.na26.visual.force.com
When trying to activate a summary, I receive the error message:
Error: Apex Trigger dlrs_AccountTrigger has not been deployed. Click Manage Child Trigger and try again.

**Comment by rbhagat30** [comment]
![dlr2](https://user-images.githubusercontent.com/29428190/30736070-f67ceaca-9f9e-11e7-9d17-1027dab21bf5.png)
![dlr3](https://user-images.githubusercontent.com/29428190/30736081-fc2a0ae8-9f9e-11e7-901d-9d8c01a32bef.png)

![dlr1](https://user-images.githubusercontent.com/29428190/30736058-eff0d78e-9f9e-11e7-94c3-fe932e9d0baa.png)

**Comment by MarcDBehr** [comment]
Take a look at the setting shown here and see if changing it makes any difference https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/110#issuecomment-197383738

Also, can you try updating to the latest version 2.9? - 1.16 seems really old

**Comment by rbhagat30** [comment]
updated the latest version still not working,any idea how developer mode will work .how to schedule a job on daily basis

**Comment by afawcett** [comment]
@rbhagat30 did you see @MarcDBehr comment above, did it fix the issue? You should also review the known issues in the README for this type of issue. You can learn about the develop mode by reviewing the comments around the global methods in the RollupService.cls in this repo, for the schedule mode there is this wiki, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. Pleaes review the above and if you still have issue we can keep the discussion going here. 👍
