### ISSUE TITLE
Manual/manually-scheduled roll-ups update records without differences

### ISSUE THREAD

**Issue by Bard09** [afawcett/declarative-lookup-rollup-summaries#568]
We have several roll-ups we have to run real-time in addition to nightly (due to having date components in their filter criteria).  By design, the nightly calculation iterates over all records, which we understand.  What we don't understand is why that nightly calculation (which was manually-scheduled) updates records that don't actually have changes.

For example....

Record A
Roll-up Total 12 -> 12  (should not be updated)

Record B
Roll-up Total 15 -> 18 (should be updated)

Right now both of these scenarios are being updated by DLRS, leading to the Last Modified By information being inaccurate for Record A (because the record wasn't 'really' modified at all).

Is it possible to do a SOQL query prior to any update, iterating & comparing the results against the update set, and only updating records that actually have different values?

**Comment by afawcett** [comment]
@Bard09 any reason why you closed this issue? Did you solve it?
