### ISSUE TITLE
Lightning Enterprise Edition

### ISSUE THREAD

**Issue by kateybasyesalesforce** [afawcett/declarative-lookup-rollup-summaries#569]
Will this package function in Lightning for an Enterprise Edition? I am not concerned with the UI or SLDS but with the functionality.

**Comment by DanDonin** [comment]
It should function just fine in Lightning it "runs" off Apex and SOQL but 100% supported in Lightning.

**Comment by afawcett** [comment]
@DanDonin is correct, once setup the tool works in LEX, however the configuration and setup UI's and app of the tool will not appear in LEX, you will have to do that in classic for now. I will flag this as an enhancement to create a LEX app and ensure the UI's appear in LEX, not a big job. 👍

**Comment by aheber** [comment]
@afawcett is this going to have a problem communicating with the MDAPI while in LEX? The LEX session isn't API enabled.

Might have to give the ability to communicate with the org using Named Credential, or some other OAuth carrier for the code deployment.

**Comment by afawcett** [comment]
@aheber not so long as VF is used, VF pages still work in this regard, even in LEX.

**Comment by afawcett** [comment]
Fixed in v2.11
