### ISSUE TITLE
unable to schedule calculate button

### ISSUE THREAD

**Issue by rbhagat30** [afawcett/declarative-lookup-rollup-summaries#572]
i am using calculation mode as 'developer'but can not get  the option to schedule calculate it i tried to schedule rollupsummary . i want to execute calculate button on daily basis  please help to schedule calculation on daily basis

**Comment by rbhagat30** [comment]
how Scheduled Full Calculate, also know as Schedule Calculate is just setting up automation to press the Calculate button for you will work

**Comment by afawcett** [comment]
Hi, this wiki page should tell you all you need to know about schedule mode, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. If you want to call the rollup engine from your own triggers, set the calculation mode to developer and review the global methods in the RollupService.cls (in the source of this repo) for comments/docs on which one to call.
