### ISSUE TITLE
Realtime Calculation is not working Accurately in Classic or Custom Metadata Pilot

### ISSUE THREAD

**Issue by nishantjadav** [afawcett/declarative-lookup-rollup-summaries#573]
Hello,

I am calculating roll up between Opportunity and Custom Product object. Different rollup fields are "Pending Products" and "Active Products".

Roll-ups are calculated based on Product field called Status. If Status is pending, Pending Products will calculate and if Status is Active, "Active Products" will be populated.

Screenshots:
![dlrs___salesforce_-_unlimited_edition](https://user-images.githubusercontent.com/30579060/31451202-824f994c-ae79-11e7-897e-247febd5e231.png)

![cs13___lookup_rollup_summary__opportunity__active_products___salesforce_-_unlimited_edition](https://user-images.githubusercontent.com/30579060/31451383-f0ff3ac8-ae79-11e7-8ea7-b5e4e18432e1.png)

When Product Status gets changed to Active, I still see the values in Pending Products field on Opportunity.

Example:
![cs13___opportunity__1016_lexington_avenue_corp_-___salesforce_-_unlimited_edition](https://user-images.githubusercontent.com/30579060/31451744-e4a8b83e-ae7a-11e7-9129-fcdf8b0847aa.png)

If I add another product and follow the process Roll up will kick in and change the appropriate value.

Can you please help me to find out why this is happening? Please let me know if anything is required from my side.

Thanks in advance!

**Comment by wes1278** [comment]
I presume you have 2 rollups defined, right? Are you sure that you have Status__c populated in the 'Relationship Criteria Fields' of the custom metadata for BOTH? I've done very similar things before and it should work fine.

Also ensure that your criteria is actually correct. Status__c = 'Active' might really need to be Status__c = 'Active Products'.

Doublecheck your picklist values and ensure you're selecting the records correctly.

**Comment by nishantjadav** [comment]
Thanks for the response Wes!
Are you sure that you have Status__c populated in the 'Relationship Criteria Fields' of the custom metadata for BOTH? - Yes

Also ensure that your criteria is actually correct. Status__c = 'Active' might really need to be Status__c = 'Active Products'. - Status is formula field, it gets calculated based on the stage of Opportunity and it has Active, Pending and Cancel only option.

**Comment by DanDonin** [comment]
Changes in a formula field wont trigger DLRS.  Put your Opportunity Stage in the Relationship Criteria so DLRS will look for changes in that field and thus trigger a new calculation.

**Comment by nishantjadav** [comment]
Thanks for the response Dan! I will give it a shot and let you know the outcome.

**Comment by afawcett** [comment]
@DanDonin is (as is often the case) correct! 👍 Hopefully this got you going @nishantjadav . Let us know if not and we can re-open.

**Comment by nishantjadav** [comment]
@DanDonin That worked! Thanks for the solution and apology for the late reply!
