### ISSUE TITLE
Error when converting a lead that has a lead forensic visit.

### ISSUE THREAD

**Issue by PaulTest** [afawcett/declarative-lookup-rollup-summaries#575]
Hi, I have a lead roll up that counts how many lead forensic visit records there are. when i try and convert a lead that has 1 or more visit records i get the below error. please can you assist? thanks 

There was an error converting the lead. Please resolve the following error and try again: LF.trgCopyVisit: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id a0F0Y000005I3IkUAK; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_LF_VisitTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 00Q0Y000008kpP2UAI; first error: SELF_REFERENCE_FROM_TRIGGER, Object (id = 00Q0Y000008kpP2) is currently in trigger LF.trgCopyVisit, therefore it cannot recursively update itself: [] Class.dlrs.RollupService.Updater.updateRecords: line 1269, column 1 Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1312, column 1 Class.dlrs.RollupService.updateRecords: line 1240, column 1 Class.dlrs.RollupService.handleRollups: line 846, column 1 Class.dlrs.RollupService.triggerHandler: line 301, column 1 Trigger.dlrs_LF_VisitTrigger: line 7, column 1: [] Trigger.LF.trgCopyVisit: line 16, column 1

**Comment by afawcett** [comment]
There are two schedule modes in this tool, which you should consider carefullly as to which one you use. Please review this wiki... https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

If you are using the full mode, you can select this from the UI. If you are using the incremental mode, review this, https://help.salesforce.com/articleView?id=code_schedule_batch_apex.htm&type=0.

If you are still having issues, please include some screenshots here of what you have been trying, so we can better help you.

**Comment by afawcett** [comment]
Yes it looks like another trigger on the child object is also trying to update the same master object. This can only be resolved if you have access to both sets of code and can rewrite them to resolve.  The other solution is to switch to one of the schedule modes for this tool, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
