### ISSUE TITLE
Unable to schedule a job  in the right time

### ISSUE THREAD

**Issue by cesarforeroexponentpartners** [afawcett/declarative-lookup-rollup-summaries#576]
Hi good day,

I am trying to schedule a roll up job, nightly, I haven't been able so far, just monthly and no matter how much I change my options, when I tried to modify the scheduled job is salesforce who doesn't let me do it. So I am stock basically with this. Some help will be appreciated.

Please reach me if you need further information.

Cesar

cesar.forero@exponentpartners.com

+1(786) 352-8399

**Comment by afawcett** [comment]
There are two schedule modes in this tool, which you should consider carefullly as to which one you use. Please review this wiki... https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

If you are using the full mode, you can select this from the UI. If you are using the incremental mode, review this, https://help.salesforce.com/articleView?id=code_schedule_batch_apex.htm&type=0.

If you are still having issues, please include some screenshots here of what you have been trying, so we can better help you.

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
