### ISSUE TITLE
Does not SUM all rows.

### ISSUE THREAD

**Issue by vsxrmv** [afawcett/declarative-lookup-rollup-summaries#584]
I am trying to sum all the custom field amount of each contact tied to one account. It would sum only one contact and ignore the rest.

I have the _Parent_ as **Account**, the _Child_ as **Contact**, the _Relationship Field_ as **AccountId**, and the custom field amount (**Last 30 Days**) to aggregate.

How can I fix this?

**Comment by aheber** [comment]
Can you post a picture of your rollup configuration?

**Comment by vsxrmv** [comment]
![screen shot 2017-11-07 at 12 24 01 pm](https://user-images.githubusercontent.com/33463458/32511082-51884a4e-c3b8-11e7-8578-6471b4127578.png)

**Comment by aheber** [comment]
That looks well enough. I would probably uncheck Aggregate All Rows as that will include items that have been deleted.

To confirm, when you modify the value in one of the contact records that individual value is summed to the parent but the sibling values are not included. If you then go to a sibling and modify the value there, that new siblings amount is summed to the account?

**Comment by vsxrmv** [comment]
I would like to keep Aggregate All Rows to ignore contacts that have been removed from the account.

One account has four contacts with Last 30 Days amount each:
A: 103
B: 119
C: 384
D: 235
Total: 841

The sum should show as 841, not 234 as it is showing now.

**Comment by aheber** [comment]
Can you try placing the Last_30_Days__c field name into the Relationship Criteria Fields field then perform the edit exercise again? I thought that field was automatically tracked but it may not be.

**Comment by vsxrmv** [comment]
No impact after the Relationship Criteria Fields field placement.

**Comment by vsxrmv** [comment]
I got it figured out. I was tying the Aggregate field to a wrong field. 

Thank you for your help!
