### ISSUE TITLE
Apex script unhandled trigger exception error

### ISSUE THREAD

**Issue by ashiquekhan** [afawcett/declarative-lookup-rollup-summaries#586]
Hi - getting this error message and not sure what it means.

> dlrs_AccountTrigger: execution of AfterUpdate
> 
> caused by: System.NoAccessException: Entity is not api accessible
> 
> Class.dlrs.fflib_SObjectSelector: line 36, column 1
> Class.dlrs.RollupSummariesSelector.CustomObjectSelector.<init>: line 102, column 1
> Class.dlrs.RollupSummariesSelector.<init>: line 43, column 1
> Class.dlrs.RollupService.describeRollups: line 992, column 1
> Class.dlrs.RollupService.handleRollups: line 673, column 1
> Class.dlrs.RollupService.triggerHandler: line 307, column 1
> Trigger.dlrs_AccountTrigger: line 7, column 1

Please help.

**Comment by MarcDBehr** [comment]
It would help if you could show us a screenshot of your DLRS setup page that is having the issue.
What is the parent object and the child? It sounds like you are trying to run against an object that does not allow triggers or updates maybe

**Comment by afawcett** [comment]
Are you running the latest version (per README file) of the package?

Also see this...
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/496
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/481

Which objects in are referenced in your lookup btw?

**Comment by afawcett** [comment]
@MarcDBehr  +1 also a good possibility! 👍

**Comment by ashiquekhan** [comment]
It's on the Account object - this is the trigger:

[image: Inline image 1]

**Comment by MarcDBehr** [comment]
@ashiquekhan  - the image did not come through, looks like email ate it

**Comment by afawcett** [comment]
Yeah its a frustrating problem, @ashiquekhan you will have to use the GitHub web ui to add a comment to this issue and drag drop your image.

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
