### ISSUE TITLE
User receives dlrs error during Lead conversion process

### ISSUE THREAD

**Issue by megachuckmc** [afawcett/declarative-lookup-rollup-summaries#587]
This one comes out of left field an I have no idea where to start looking!

I created a Lookup Summary rule with a custom object called **Sales Quotas** as the Parent and **Opportunity** as the child, which seeks to do a summary of the Amounts in Opportunities where the owner of the Opp matches the owner of the Sales Quota record.

A user got the following error when converting a Lead to a contact and creating an Opportunity.  
![dlrs error](https://user-images.githubusercontent.com/19916720/33030323-e4fe031a-cdcf-11e7-9426-434f882ab206.jpg)

Here is the Lookup Rollup:

![dlrs screen](https://user-images.githubusercontent.com/19916720/33030432-282df85c-cdd0-11e7-842b-ccf9467e070e.jpg)

Any help/suggestions greatly appreciated!
Mike

**Comment by DanDonin** [comment]
Try no spaces in the unique name

**Comment by slowburn** [comment]
The errorcode is actually not enough to guess what's happening.
But are you sure that OwnerId is the correct Relationship Field from Opp to your custom object?

**Comment by MarcDBehr** [comment]
@megachuckmc  it might help us to see what the fields on the custom object look like, to narrow down what @slowburn is asking

**Comment by afawcett** [comment]
So.... 

I enhanced in a recent release the error handling around this message to give a better clue as to what part of the rollup is invalid. If you cannot upgrade, find the rollup and attempt to edit it again and click Save to re-run and it should show whats invalid. This can happen if you rename a field or object referenced on the lookup (something my ongoing adoption of custom metadata will resolve in the future btw). 

~~~~
		SObjectType parentObjectType = getSObjectType(lookup.ParentObject);
		if(parentObjectType==null)
			throw RollupServiceException.invalidRollup(lookup, 'Parent Object : ' + lookup.ParentObject);
		Map<String, Schema.SObjectField> parentFields = getSObjectTypeFields(parentObjectType);
		SObjectType childObjectType = getSObjectType(lookup.ChildObject);
		if(childObjectType==null)
			throw RollupServiceException.invalidRollup(lookup, 'Child Object : ' + lookup.ChildObject);
		Map<String, Schema.SObjectField> childFields = getSObjectTypeFields(childObjectType);
		SObjectField fieldToAggregate = childFields.get(lookup.FieldToAggregate);
		SObjectField relationshipField = childFields.get(lookup.RelationshipField);
		SObjectField aggregateResultField = parentFields.get(lookup.AggregateResultField);
		if(fieldToAggregate==null)
			throw RollupServiceException.invalidRollup(lookup, 'Field to Aggregate: ' + lookup.FieldToAggregate);
        if(relationshipField==null)
            throw RollupServiceException.invalidRollup(lookup, 'Relationship Field: ' + lookup.RelationshipField);
        if(aggregateResultField==null)
            throw RollupServiceException.invalidRollup(lookup, 'Aggregate Result Field: ' + lookup.AggregateResultField);
~~~~

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
