### ISSUE TITLE
"Test Code" field Long Text

### ISSUE THREAD

**Issue by akramer16** [afawcett/declarative-lookup-rollup-summaries#588]
I know this is a dupe of [Issue 503](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/503) but I never heard back and since that issue is closed I thought more eyes would see it as a new issue here. It appears long text area fields are now supported in custom metadata types as of Summer 17: https://releasenotes.docs.salesforce.com/en-us/summer17/release-notes/rn_forcecom_development_custom_metadata_long_text_areas_ga.htm. Any chance we could get this updated in the next release?

**Comment by afawcett** [comment]
Yep, its down as a priority enhancement for my next burst of time on the tool. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/304
