### ISSUE TITLE
Temporarily suspend realtime calculation

### ISSUE THREAD

**Issue by maquel** [afawcett/declarative-lookup-rollup-summaries#589]
Hi all,

I have a flow that creates Quote Line Items. I have several DLRS that roll up from QLIs to the Quote. When the situation arises that the flow creates many QLIs, it causes the following error:

dlrs_QuoteLineItemTrigger: System.LimitException: dlrs:Too many SOQL queries: 101

I believe this is because the DLRS are triggered for each new QLI. Is there any way to suspend the realtime calculation until the flow is finished and all QLIs are created to avoid the SOQL query limit?

**Comment by afawcett** [comment]
The DLRS trigger / engine is bulkified, however recursion and platform trigger chunking can cause it to run multiple queries despite this. Can you use the Developer Console to grab a debug log, then filter of SOQL and/or use the Execution Overview feature. This will give you a graphical view of the execution flow. You should also check what other Process Builder/Workflows/Triggers etc are on your parent and child objects. Finally you don't state how your adding the lines, is this via some code or via the UI? If its code, is that code itself bulkified?

**Comment by maquel** [comment]
Thanks for the reply afawcett,

The quote line items are originally added by code which works fine. The flow in this situation is copying quote line items from the original quote and creating them on a new quote. I don't see any other flows causing the error in the debug log, but it sounds like this must be the source of the problem? I do have a couple other flows that could be triggered. I'm not a coder but I would assume the consulting we had done to create the  to my knowledge the code should be bulkified 

I think a quick way to solve this would be to have a checkbox on the quote that would disable the query. Is there a short IF(ISTRUE(DON"TCALC,CALC) type statement I could add to the DLRS trigger to prevent it from calculating when the box is checked?

**Comment by afawcett** [comment]
Yes, so the Flow should be using the "Fast" database elements to bulkify, if its not thats your problem. Or if its using the "Fast" database elements in a loop, thats also your problem. So thats worth checking. You can also run up the Developer Console and use the Execution Overview to see whats happening.

If you cannot change or improve the flow, then yes something like you propose or set a static in your Apex code that the trigger can reference. Use try/finally in your code to unset the static though, stop it leaking beyond the operation in your code it is intended for.

**Comment by maquel** [comment]
Sounds like that could be the issue, but this article says all flow elements are automatically bulkified? https://help.salesforce.com/articleView?id=vpm_admin_bulkification.htm&type=0

If fast elements in a loop are the issue, can I use the regular (not fast) element to solve it?

I'm pretty basic with coding skills, anywhere you could point me to help with writing the static?

**Comment by afawcett** [comment]
Take a look through this, https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_static.htm. To create a static variable on a class of your choosing.  Then set it, do some stuff that triggers the flow and DLRS, check for the static variable to condition whatever execution you need. Then unset the static. I recommend using try/finally so that the static gets set back to false even in the case of an exception. https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_exception_statements.htm?search_text=finally. Hope this helps! :+1:
