### ISSUE TITLE
Remote Site Setting has stopped working

### ISSUE THREAD

**Issue by stephanielitus** [afawcett/declarative-lookup-rollup-summaries#590]
Hello,

We've been using DLRS for quite some time without any problems.  Nevertheless, when I tried to deploy a new child trigger today, I got the following error:
Error:
Salesforce Metadata API connection failure, click the link below to configure.

There is no link at the bottom of the page, as shown in the screenshots.

I have confirmed that the known issues for Session Settings are unchecked.
<img width="1192" alt="screen shot 2017-11-28 at 8 19 28 pm" src="https://user-images.githubusercontent.com/17297637/33356426-9f802056-d479-11e7-94ff-4fba13dc8e42.png">
<img width="541" alt="screen shot 2017-11-28 at 8 19 03 pm" src="https://user-images.githubusercontent.com/17297637/33356427-9f956dda-d479-11e7-8469-0ef87c3cda07.png">

**Comment by afawcett** [comment]
Click the link to Return to the Welcome page, this should provide steps to create the remote site? Has your org moved instances maybe? Or enabled My Domain?

**Comment by stephanielitus** [comment]
ah, we moved instances.  Sorry about that, and thank you!
