### ISSUE TITLE
LREngine Test Class code coverage assistance needed

### ISSUE THREAD

**Issue by Alio401** [afawcett/declarative-lookup-rollup-summaries#592]
The LREngine Test class is only passing 12 of the 43 tests. Giving us lower than ideal coverage to migrate. The errors are all internal Validation rules that are causing the failures, ie. System.DmlException: Insert failed. First exception on row 4; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, If Exposition or Exhibitor Sales opportunity is lost, the details of reason lost field is required. 
What are the deployment specifics to get pass this?

**Comment by aheber** [comment]
@Alio401 could you provide more information?

Are you using this unmanaged? Is there a specific reason why?

Are you using this managed? If so you shouldn't need tests to pass, could you provide the use-case around running these tests on a managed package?

Thanks!

**Comment by Alio401** [comment]
@aheber It's a managed package. We are wanting to ensure that it passes all tests. We had rollup helper previously installed and it failed because of our validations.

**Comment by aheber** [comment]
Normally I recommend against running the "all" tests in your org. This executed not only the tests that you have written for your local customizations but also executes the test code from the managed package which isn't built to be able to run in your org. They are designed to run in the packaging org, which is normally a very simple org as far as customizations go.

The managed code cannot know about your validation rules thus can't create objects that pass your validation. You're not going to be able to get all of the test to pass. It would be awesome if you could run this once just to be able to confirm correct behavior, but that is not my experience with managed packages.

If you need to test the LREngine code you could copy the tests from the package (by copying them from the GitHub repos) then adjust your local versions to be compatible with your org. You still wouldn't run the managed versions of the code but you could validate correct behavior using the same types of test scenarios.

Overall I would strongly recommend against this. You shouldn't expect managed package test code to pass in your org and those tests are not an accurate representation of the tools ability or reliability to perform under your workload.

**Comment by afawcett** [comment]
Yes totally agree with @aheber , could not have put it better myself.

@Alio401 if your objective is to ensure your validations do not break your rollups, you really need to write tests for your rollups, not run the generic rollup tests (it creates its own rollups anyway). 

Writing your own Apex tests for declaratively defined rollups may sound a bit odd, but actually it is considered [best practice to write Apex tests in cases where there is complex declarative configurations, flows, validation rules, workflows etc](https://salesforce.stackexchange.com/questions/67901/unit-testing-workflow-field-update ), as its the best way to test your system. That said i have seen other tools that help you test your declarative solutions in your org without code, have [read of this thread](https://developer.salesforce.com/forums/?id=906F00000008pBnIAI).

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
