### ISSUE TITLE
Apex CPU time limit exceeded - Please help!

### ISSUE THREAD

**Issue by travisgsmith** [afawcett/declarative-lookup-rollup-summaries#593]
Hi there!

First of all, **thank you** for building, sharing, and maintaining this amazing project. Really, truly, a great public service!

I've been running into some problems, as we are occasionally getting the following CPU time limit exceeded errors:

|METHOD_EXIT|...|dlrs.RollupService.triggerHandler()
|FATAL_ERROR|System.LimitException: Apex CPU time limit exceeded

At first I thought this might be an caused by Processes not being bulkified, so I took the effort to convert all Processes into workflows/triggers to ensure it's not a Flow issue. Sadly, this has **not** resolved the problem!

# **Details:**

- In our production Salesforce, we have 11 Lookup Rollup Summaries (6 on Tasks, which update Leads. 4 on Leads, which updates Blah__c (a Custom Object), and 1 on Account which also updates Blah__c.
- We are on Latest Release Version 2.9
- We do not currently have any Active Flows or Processes (just workflows)
- We have two Triggers on Opportunity which are simple and bulkified
- Database size is fairly large: We have 500,000 Lead records, and 500,000 Blah__c records.

The 'CPU Limit Exceeded' errors when a 3rd party system is Inserting new Task records in batch via the API. when the batch number of records gets close to 200, the errors start happening.

I was able to catch one of the errors with Developer Console! Although I am not an expert, the analysis does not scream anything obvious. The dlrs.RollupService trigger simply appears to be eating up too much CPU time...?

I have attached screenshots of the Developer Console analysis. I would greatly appreciate it if someone more knowledgeable than myself could take a look and offer suggestions!

Thank you **very much** for your time!
# **Screenshots:**

**1.** Below is a screenshot of the 'Execution Overview - Save Order'

It doesn't look like anything is getting stuck in endless update loops or anything:
![2017-12-01 - devloper console analysis 6](https://user-images.githubusercontent.com/34114336/33507912-7b8e62cc-d6c5-11e7-8686-672e622d8827.png)

**2.** Below is a screenshot that shows a breakdown of the APEX_CODE category (total of 10 seconds). In the top right window, you can see there is a mysterious six second jump in execution time for dlrs_TaskTrigger. This seems suspicious. Can anyone provide insight?

![2017-12-01 - devloper console analysis 1](https://user-images.githubusercontent.com/34114336/33507911-7a65ddc6-d6c5-11e7-9bff-e3b6c05946b6.png)

**3.** Below is a screenshot of the DB category (12.8 seconds) execution. Notice that each of the SELECT SOQL queries are relatively healthy (the longest SELECT takes 0.8 seconds):

![2017-12-01 - devloper console analysis 3](https://user-images.githubusercontent.com/34114336/33507909-796504ce-d6c5-11e7-9ebe-d8db770131be.png)

**4.** Below is Execution Overview - Executed Units view:

![2017-12-01 - devloper console analysis 2](https://user-images.githubusercontent.com/34114336/33507910-799ca2da-d6c5-11e7-896b-a0805fa55c5d.png)

**5.** Below is 2nd longest DB category overview:

![2017-12-01 - devloper console analysis 4](https://user-images.githubusercontent.com/34114336/33507913-7c65cf1e-d6c5-11e7-93cd-a76466d86d17.png)

**6.** Finally, below is 2nd longest APEX_CODE category overview:

![2017-12-01 - devloper console analysis 5](https://user-images.githubusercontent.com/34114336/33507914-7d9a1782-d6c5-11e7-9713-4fde48b3fd59.png)

**THANK YOU!**

**Comment by afawcett** [comment]
Wow, this is great analysis, truly a master class in reporting such issues! 👍  

So yes, you have quite a cascade of triggers firing here, along with large volumes. Mostly DLRS attempts to use the database (SOQL queries) to calculate things, but some operations, do in memory calculations, can you share some details on your rollups? 

In the end the tool is subject to the limits of Apex, per the README notes, here are some things though to consider meanwhile...

- **Going async.** Review the wiki page on schedule modes and consider moving at least some from realtime mode to incremental scheduled calc (the cals are differed to async mode) or full scheduled calc. You can read more here. https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
- **Disable rules during injects**. Some folks have scripted flipping the Active field on the rollups off and back on again as part of a data load. Then kicked off a one calcs to catchup the rollups before reactivating the realtime rollups.
- **Check none Apex code stuff**. Yes thats correct per [this reference from a Salesforce PM](https://salesforce.stackexchange.com/questions/18244/how-does-sf-calculate-the-cpu-time) declarative things like validation, workflow, process builder etc is included in Apex CPU consumption. Can you peel back further to rule things out? Is there any other triggers on the objects, validations, workflows?

**Comment by travisgsmith** [comment]
Thank you **very much** - I ended up converting all of the Rollups from realtime to scheduled, and things are running smoothly now.

Sadly, it seems Salesforce cannot handle 500,000 records in a table, which is disappointing!
