### ISSUE TITLE
Remove count when lead is converted

### ISSUE THREAD

**Issue by preetishetty25** [afawcett/declarative-lookup-rollup-summaries#594]
I would not want to count the lead once its converted as it will be counted in the contacts as well.

I have created two counts total leads count  and total contacts count. Once a lead is converted it should be removed from the leads count. Right now it is being counted in both.

**Comment by preetishetty25** [comment]
Still doesnt work.

**Comment by aheber** [comment]
@preetishetty25 could you post a screen shot? Have you added IsConverted to the Field listing below the actual query field? This should instruct DLRS to monitor for applicable changes. If it still doesn't work we will need to figure out if the trigger is firing at the expected time and that will take a debug log.

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
