### ISSUE TITLE
Scope size fields in Custom Settings are locked

### ISSUE THREAD

**Issue by rmleverett** [afawcett/declarative-lookup-rollup-summaries#597]
I'm trying to decrease the scope sizes but these and some other fields are greyed out.  I am the System Administrator.

**Comment by afawcett** [comment]
This is really odd, can you send a screenshot?

**Comment by DanDonin** [comment]
![image](https://user-images.githubusercontent.com/16108202/34474212-eef4a374-ef30-11e7-97dd-0ad98a18b65c.png)


![image](https://user-images.githubusercontent.com/16108202/34474214-f9332a4a-ef30-11e7-9643-902c9106cea2.png)

**Comment by DanDonin** [comment]
That said I think those are meant to be locked.

To adjust you'll want to go to the custom setting and click Manage.

![image](https://user-images.githubusercontent.com/16108202/34474290-eae9dcb2-ef31-11e7-9f3a-9d2dbe7e5f35.png)

Then click New
![image](https://user-images.githubusercontent.com/16108202/34474291-f67a3fb8-ef31-11e7-9592-1647bcf00881.png)

Then here is where you can change the scope size.

![image](https://user-images.githubusercontent.com/16108202/34474295-049bc328-ef32-11e7-912e-7a55ec8bad61.png)


Sorry I gave bad info back on the Community! @rmleverett

**Comment by rmleverett** [comment]
Thanks!

**Comment by afawcett** [comment]
@DanDonin you rock, thanks! 👍
