### ISSUE TITLE
Issue with Relationship Criteria

### ISSUE THREAD

**Issue by gbillerbeck** [afawcett/declarative-lookup-rollup-summaries#598]
Hi, 
I've an issue with a relationship criteria.
Sum of an child object shall be related to a status field "Approved"
Relationship criteria = Status LIKE 'Approved' is working ... but only if a new record is created.
Means:  
1. Status to 'Approved". Save. Nothing happen in the aggregate result field
2. Create new child record. Aggregate result filed is updated.
3. Status to "Not Approved". Save. Nothing happen in the aggregate result field
4. Create new child record. Aggregate result filed is updated.

If the sum in the child record is changed without relationship criteria its working as it should...

Any ideas?
Thank you!

**Comment by aheber** [comment]
@gbillerbeck can you post a screenshot of your rollup configuration?

At first guess I would think that you have Status is the Relationship criteria but not in the RelationshipCriteria Fields, this would cause DLRS not to monitor that field for changes to invoke the rollup logic. Its sounds like this could be resolved by adding Status to the Relationship Criteria Fields.

Hope that helps, if not then the picture of your configuration should

**Comment by gbillerbeck** [comment]
@aheber (Fields?)... they need to be configured?
here it is...


![siaf_rollup](https://user-images.githubusercontent.com/31031932/33776137-c1a164f0-dc40-11e7-8ac0-b81ba06d2a6b.jpg)

**Comment by aheber** [comment]
Yes, I would add Position_Status__c to the Relationship Criteria Fields under Relationship Criteria. You have to tell the tool which fields to monitor for change, it is a performance optimization designed to only run the rollup logic when a qualifying change happens to the record.

**Comment by gbillerbeck** [comment]
Thanks Anthony,...that was the problem. Solved!
