### ISSUE TITLE
Newbie trying to install DLRS - Apex trigger error 

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#599]
Hi All
I've just installed DLRS managed package into a partial sandox and am trying to set up my first rollup summary.  I'm getting an error: Apex Trigger dlrs_OpportunityTrigger has not been deployed. Click Manage Child Trigger and try again.

Looking at the Apex triggers I have installed the only ones I have from this package are RollupServiceTest2Trigger and RollupSummariesTrigger.  Can anyone point me towards a solution?

Thanks in advance

**Comment by DanDonin** [comment]
Click manage child trigger. Install the child trigger. Then make the DLRS
record active again.

**Comment by LawranceT** [comment]
Thanks Dan - I know I'm not overly technical, but I don't see a link to click, where I read 'Click manage child trigger', it is just text...
![image](https://user-images.githubusercontent.com/34403841/33799187-9a1681d4-dd1e-11e7-8c49-10158046902b.png)

**Comment by DanDonin** [comment]
Uncheck Active. Save it. Then a button with Manage Child Trigger will show
up.

https://www.dandonin.com/2017/10/19/troubleshooting-dlrs-101/

**Comment by LawranceT** [comment]
OK, got it!  Many thanks, have a great evening.
