### ISSUE TITLE
Errors with FinancialForce

### ISSUE THREAD

**Issue by johnson80245** [afawcett/declarative-lookup-rollup-summaries#603]
I am getting an error with trying to set up the DLRS for a FinancialForce object. I am attempting to use a child object of Transaction.  The error I am receiving is:

dlrs_c2godaTransactionTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction: Object validation has failed. Current company not set.: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_c2godaTransactionTest.testTrigger: line 11, column 1

I attempted to run this in the developer console :
`SavePoint sp = Database.setSavepoint();
dlrs.RollupService.testHandler(new c2g__codaTransaction__c(c2g__OwnerCompany__c='<<Company ID>>'));
Database.rollback(sp);`

and I get the following error:

Line: 272, Column: 1
System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction: Object validation has failed. You cannot create or edit transactions.: []

I have tried to go through challenges with code coverage but I cannot seem to get this. I am new to all of this and I have been attempting for several days without any traction gained.

**Comment by aheber** [comment]
@johnson80245 I'm not an expert here. I do have experience with FinancialForce. I have never built a rollup on this object.

My experience is that it is difficult to get a Company setup to pass that validation error. Here is a blog post I've referenced in the past: http://amitsalesforce.blogspot.com/2015/05/creating-sales-invoice-with-financial.html

Another common recommendation for this is allowing this test SeeAllData=true. I hate that setting with a passion but it really is difficult to get the test data model setup to be compatible with this. I have a utility class in my org with a foundation method that does all the heavy lifting, it is built from the linked blog post. I can share if it would help but it has some adaption to be more compatible with my org.

As for your second error, I'm not sure what the possible work-arounds are there. Would have to dig deeper into the package options.

If I can get some time I'll give it a try, don't hold your breath though.


What data are you rolling up? Maybe there is a different way to gain access to it.

**Comment by johnson80245** [comment]
Thanks for the advice, where would I put the 'SeeAllData=True'? I am assuming before the save point?
Here is my roll up:
![capture](https://user-images.githubusercontent.com/24464964/34232309-fa5236d4-e59c-11e7-8c67-ba4c1be513cf.PNG)

**Comment by aheber** [comment]
At the very bottom of the record there should be "Test Code See All Data" checkbox, you'll want to check that. Then you'll probably want to use custom test code that pulls a transaction record from the database and passes it through for update. You'll probably have to jump through a few hoops.

No need for the save points in the test code.

As a note, it looks like you're using the older rollup config model, using data records instead of custom metadata. You may want to think about upgrading, no specific benefit but rollups will carry down to all sandboxes. Day to day use they behave the same.

Also confirm you're on the latest release, though I don't expect it to fix the problem you're having, but if you can't see the above mentioned checkbox it might not be available in your release, or hasn't been added to the page layout post-upgrade... or you just didn't capture that part of the layout.

**Comment by johnson80245** [comment]
Thanks for the heads up, I switched to the custom metadata and receiving the same error. I am on the most recent, I am assuming that for the test code, I type it in and then click Manage Child Object?

Sorry for all the questions, this is a lot of trial and error learning for me. I enjoy it but it can be difficult!

**Comment by aheber** [comment]
Yes if you're building your trigger and test code via the DLRS UI you still deploy via Manage Child Trigger.

I was able to get this working. It certainly isn't ideal but hopefully it gets stuff off the ground.
Test Code: update [select Id from c2g__codaTransaction__c LIMIT 1];
Test Code See All Data = true
![image](https://user-images.githubusercontent.com/2173116/34274135-8044bdb8-e654-11e7-920c-550e54db3370.png)

This test class will fail in any org that doesn't include at least one transaction record but should be safe in production or any sandbox that has real data.

**Comment by johnson80245** [comment]
You are a savior, thank you. This allowed me to get past and it is working properly now!
