### ISSUE TITLE
Is it possible to include a space in the concatenate delimiter

### ISSUE THREAD

**Issue by lgreer0517** [afawcett/declarative-lookup-rollup-summaries#604]
Hi,
I want to start by saying that I really appreciate that you've made this available. It's really great.

I have a question. I want to separate concatenated values with a comma followed by a space (value1, value2, value3...). I tried putting comma space in the delimiter field but it seems to strip out the space. Is there a way to include one?
Thanks,
Laura

**Comment by afawcett** [comment]
Yes, enter SP()

**Comment by lgreer0517** [comment]
Thank you! That did the trick!
Laura
