### ISSUE TITLE
Dynamic Dates?

### ISSUE THREAD

**Issue by acarlesimo1** [afawcett/declarative-lookup-rollup-summaries#606]
Hi - is it possible to use DLRS to create a dynamic date rollup field, based on for example "Current Quarter", "Previous Quarter", etc?  How would I write that?

**Comment by DanDonin** [comment]
You can use soql like datefield >= last_quarter or other date functions.

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_date_functions.htm

**Comment by aheber** [comment]
@acarlesimo1 please keep in mind that these rollup fields are not automatically updated to the current time period, they will be accurate to the most recent time that one of the children records was update enough to re-evaluate the rollup, if you're using realtime or scheduled delta processing.
You can setup the job to be a realtime rollup but ALSO schedule the full recalculate job to run periodically (the first of the month maybe) to fully recalculate the fields. This will setup DLRS to be able to keep these fields accurate to the current time period.

**Comment by acarlesimo1** [comment]
Thank you both!
