### ISSUE TITLE
I don't have access to the Apps Tabs

### ISSUE THREAD

**Issue by tylerzika** [afawcett/declarative-lookup-rollup-summaries#609]
I have access to the App, but I'm not sure why I can't assign the App's Tabs to my view. The App's Tabs are not even available for me to select. Any ideas?

![screen shot 2018-01-08 at 2 24 43 pm](https://user-images.githubusercontent.com/1011888/34695543-1d9c3e68-f480-11e7-86e6-fdaf6d24ef1d.png)

**Comment by afawcett** [comment]
Have you assigned the permission set that comes with the tool to your user?

**Comment by afawcett** [comment]
@tylerzika let us know if you still need help on this and we re-open. Thanks!
