### ISSUE TITLE
Unable to connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by DavidMilner** [afawcett/declarative-lookup-rollup-summaries#610]
After returning from a leave of absence over the festive season I wanted to setup some new rollup summaries.

When trying to run the dlrs plugin I was thrown an error on the Welcome page - see attached file.
When I click on the "Create Remote Site Setting" I am thrown another mesage saying that "This Remote Site Name already exists or has been previously used. Please choose a different name."

Please help to resolve.

Thanking you in advance.

![dlrs error 20170109 dm](https://user-images.githubusercontent.com/35244913/34747636-3fa46f8a-f5ed-11e7-9e57-3e0d361e18aa.PNG)

**Comment by aheber** [comment]
@DavidMilner sounds like the URL of your org has changed. This is a known issue and being discussed in #372.

I would navigate to Remote Site Settings in Salesforce Setup and delete the setting titled "dlrs_mdapi" then you should be able to re-create it using the package pages. If you prefer to keep it around you can change the name and then let DLRS create a new one.
If you review you will probably notice the differences between the current URL in the setting and the one you have in your screenshot, lawinorder.lightning.force.com.

If it isn't the remote site setting it could be your session token, I'm not sure how capable this is when using Lightning, the session token received from Lightning Experience isn't API enabled, as a last-ditch I would attempt to access the page from Classic UI.

Please report back to us if/what resolves your issue.

**Comment by DavidMilner** [comment]
Hello Heber,

Thank you for your quick response – much appreciated.

I changed the name of the original Remote site setting and then created a new one successfully.
So, your first solution has worked for me.

Many thanks.

Regards,

DavidM


Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.

**Comment by teachout** [comment]
Hello @afawcett ,

I am encountering the same problem shown above. When I come into the DLRS Welcome page, I see this: 
![image](https://user-images.githubusercontent.com/64217300/80124147-6e738400-8555-11ea-8f34-41396e51ef44.png)
When I click the "Remote Site Setting" button, I get the following error:
![image](https://user-images.githubusercontent.com/64217300/80124198-8519db00-8555-11ea-9c57-8066a8e81781.png)

I changed the name of the original Remote Site Setting record, and recreating it like so:
![image](https://user-images.githubusercontent.com/64217300/80124308-b1cdf280-8555-11ea-9e64-c3394ebc44cf.png)
However, the error persists.

I also tried accessing the DLRS through Classic, but still not working:
![image](https://user-images.githubusercontent.com/64217300/80124968-a3cca180-8556-11ea-9abe-ca31f1cca720.png)

I could truly use your help to figure out what is going on here. If it would be easier for me to uninstall and reinstall the DLRS package, please provide pages with instructions for doing so.

It may help for you to know that my understanding of deep Salesforce code/programming is quite limited.

**Comment by rogeramitchell** [comment]
@teachout it looks like the Remote Site URL in your screenshot does not match what DLRS expects. Try updating to: https://charlemagne--dlrs.visualforce.com

**Comment by teachout** [comment]
@rogeramitchell  -- Thank you! That did the job!  My problem is fixed!
