### ISSUE TITLE
Only rollup records that fall in the past 12 months based on a date field

### ISSUE THREAD

**Issue by DavidMilner** [afawcett/declarative-lookup-rollup-summaries#611]
How can I rollup only those records that fall withing the past 12 months since a particular date field.

Example
Let's say we want to roll up those items on invoices that relate to a particular product line and the Invoice Date falls within the past 12 months.

Hoping there is an easy way to achieve this.

Thanks in advance.

**Comment by aheber** [comment]
If I’m understanding:
You want to roll up lines where their parent invoice date field is within
the last 12 months?

You can run a filter on the related record Invoice__r.Date__c >=
Last_N_Months:12 (syntax may be a little wrong)

The key problem is if that record slides out of the time boundary it isn’t
automatically recalculated. You can setup both the real-time and a monthly
scheduled job to cover that gap.

Hope that helps, for more specific I would probably need more detail.

**Comment by DavidMilner** [comment]
Hello Heber,

Thank you for your quick reply – much appreciated.

Where exactly should the criteria statement Invoice__r.Date__c >= Last_N_Months:12 be entered?
Should this be entered as the Relationship Criteria?

Please confirm.

Thank You,


Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.

**Comment by aheber** [comment]
Yes, relationship criteria. Those fields will likely be different in your
org.

**Comment by DavidMilner** [comment]
Hello Heber,

So I have entered in the Relationship Criteria – see below screen image
But the value on the Aggregate Result Field has not updated.
Is there a log I can view to see what is and what isn’t getting updated?

Thank You,


[cid:image001.png@01D38A26.D7B77070]






















































Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.

**Comment by aheber** [comment]
Did you run a full calculate?

**Comment by DavidMilner** [comment]
Hello Heber,

When I try to run a full calculate I get the following error message…

[cid:image001.png@01D38A2A.4073B260]



Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.

**Comment by manasga** [comment]
Hello Andy,

Hope you are doing good.
i have installed your managed package for one of my use case, i have similar criteria where i need to sum up the certain currency field for last 12 months. For few records, it's showing up the old value even though there are no records created in last 12 months instead of 0 or a blank value.

Any pointers would be really helpful, as i'm not able to access logs as well because of managed package.

Thanks,
Manasi

**Comment by afawcett** [comment]
So if you are wanting to use relative date based criteria you cannot use realtime mode, since the recalc only occurs when records change, not during the passage of time. For criteria like this you need to use one of the schedule modes. https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. 

Also apologies, but none of the screenshots etc in the above are visible in the GitHub issue view. I would recommend dragging and dropping screenshots via the GitHub Issue browser you and not using your email program (this also avoids all the email footers etc getting copied into the thread here). Thanks! 👍

**Comment by afawcett** [comment]
@manasga let us know if you still need help on this and we can try to progress. I will close for now, but we can for sure re-open if needed.
