### ISSUE TITLE
Relationship Criteria Fields field with multiple fields breaks other processes

### ISSUE THREAD

**Issue by cgerth** [afawcett/declarative-lookup-rollup-summaries#614]
We use a 3rd party tool called Smart Sandbox to move records between Salesforce instances. This is useful for testing things in sandboxes using realistic data. 

During a recent Smart Sandbox transfer, any DLRS summaries that contained multiple fields in the Relationship Criteria Fields errored out in Smart Sandbox with the message, "Field   Date_Out_For_Repair__c   Date_Returned_From_Repair__c does not exist on the child object."

It appears that Smart Sandbox assumes that the Relationship Criteria Fields field will contain one field name like a normal field, but in this case it actually contains two, separated by a line break, which Smart Sandbox reads as a concatenated mess ("Date_Out_For_Repair__c   Date_Returned_From_Repair__c").

This is not critical functionality for DLRS, but I wanted to let you know about the effect that this non-standard design (having a field that contains multiple field names separated by line breaks) has on other systems.

**Comment by DanDonin** [comment]
I'd argue that's an issue with smart sandbox as the field is a standard
text box field that by default accepts line breaks. You are more or less
just storing text there like any other text box field in sfdc.

**Comment by afawcett** [comment]
Yeah i have to agree with @DanDonin on this. It sounds like SmartBox is losing the line breaks and thus the DLRS trigger is firing this error thinking its a single field. Since large text areas in general support line breaks, this feel like an easy repo and bug report for SmartBox tbh.

**Comment by afawcett** [comment]
@cgerth let us know if you need more help on this and we can re-open. Thanks!
