### ISSUE TITLE
Error in Trigger: Too Many DML Rows

### ISSUE THREAD

**Issue by kacrouse** [afawcett/declarative-lookup-rollup-summaries#615]
Getting the following error caused by the dlrs trigger:

>  Error inserting [object type] record(s).  Message:  dlrs_[object type]Trigger: System.LimitException: dlrs:Too many DML rows: 10001 . StatusCode = CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY 
Number of records that failed with this error : 200

There is a large number of rollup summaries where this object is the child object (...126 to be exact 😳), is that the cause of this error? If so, is there a way to stop the error other than deactivating some of the summaries?

All summaries are set to Calculation Mode of `Scheduled` and use the `RollupJob` method of calculation as opposed to `Schedule Calculate`.

**Comment by aheber** [comment]
@kacrouse If you do the math you see a batch size of 200 * 126 rollups, this causes the system to try and insert 25200 schedule records into the system to be processed later.
With the current architecture of the tool there isn't a good way to reduce the number from a 1 to 1 with the # of rollups * records. 
At this point I would probably recommend not inserting 200 records at once. You'll likely have to reduce that number significantly to get this to process correctly.

You could submit an issue to request optimization for this scenario. Somehow the system would have to be able to either queue multiple records or multiple rollups into a single "row" in the database. This is certainly possible but would take some code refactoring.

Hope that helps, and doesn't just tell you what you already know, smaller batch sizes.

**Comment by kacrouse** [comment]
That was my suspicion, thanks for confirming and providing some more clarity to it.

We were able to solve the issue by deactivating some of the rollups. I'll look into decreasing the batch size of records inserted if it pops up again.
