### ISSUE TITLE
Rollups not auto calculating

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#616]
I'm sure that this is an issue that is raised often, in which case my apologies in advance:

I have a set of roll-ups created against a custom object.  Each rollup is set to count the number of records in the child object with a specified status, and writes the result to a different field (total number of confirmed records, total number of cancelled records, total number of prospect records etc)

What I need is when the status is changed on the child record the rollups are triggered and each of the target fields are populated with updated figures.

When I manual start the calculation on each rollup everything works fine, but if I make a change to the status value on the child object and save the change this does not trigger the rollups to calculate.  Am I missing something?

**Comment by aheber** [comment]
@LawranceT could you post a screenshot of your rollup?

It sounds like you haven't populated your Status field into the Relationship Criteria Fields box. Fields in that box are the signals to DLRS to monitor those fields for changes. That is how it knows if it should recalculate the parent values for that job.

**Comment by LawranceT** [comment]
![dlrs](https://user-images.githubusercontent.com/34403841/35183375-d7757060-fddc-11e7-8685-57ef09397f04.PNG)
Thats for the response@aheber, here is the screenshot  - the Relationship Criteria is populated.  The field here, Reg_V_Hours_Status__c, is usually being updated by a trigger and a process builder, but even when I update it manually the DLRS is not recalculating, it only works when I select Calculate

**Comment by LawranceT** [comment]
I see the problem @aheber, Relationship Criteria Fields were not populated.  Thanks for the steer
