### ISSUE TITLE
SObject type does not allow locking rows

### ISSUE THREAD

**Issue by asinclair56** [afawcett/declarative-lookup-rollup-summaries#619]
Just a heads up on version 2.10 we installed this and did a rollup from Opportunity to User via OwnerID and got the error "SObject type does not allow locking rows". 

We uninstalled and installed version 2.9 and this same rollup worked without issue.

**Comment by afawcett** [comment]
@asinclair56 thanks very much this heads up! I should hopefully be able to determine this at runtime without hard coding a list of objects. Thanks again!

**Comment by BalassaSamuelson** [comment]
Ran into the same issue when trying to rollup from a custom object to User via OwnerID. Will try the uninstall and install 2.9 workaround

**Comment by afawcett** [comment]
Fixed in v2.11
