### ISSUE TITLE
AccountContactRelation Rollup of Account Names to Contact

### ISSUE THREAD

**Issue by RussAtlanta** [afawcett/declarative-lookup-rollup-summaries#620]
I'm trying to create a rollup of Account Names from the AccountContactRelationship object to a text field on the Contact. This is just a text field list on the Contact detail of all Accounts associated with a specific Contact.
I set the Parent object as "Contact" and the Child object as "AccountContactRelation". I set the Relationship Field as "AccountId". I have also tried "ContactId" in the Relationship Field but no result.
Is there something I'm missing to allow this to work?
![capture](https://user-images.githubusercontent.com/20213771/35341454-c2060428-00f3-11e8-9d01-80a85837f5a6.JPG)

**Comment by afawcett** [comment]
So a few things...
- I would say ContactId is the one you want given your Parent object is Contact
- It appears you have added Related_Accounts__c to the AccountContactRelation object yes? Is this the field you want to rollup? If so, how has that got the Account name in it?
- Also does the Accounts related list on the Contact not give this information? Or is that you need it in a field for reporting purposes?
- Keep in mind depending on the size of your Contact.Related_Accounts__c and the number of Accounts associated with an Account you may get some truncation. 
- Ok so i have started to try to reproduce this and found this myself... i have run out of time to continue my investigation but will resume hopefully later this weekend. It could be that Salesforce is just not firing the Apex Trigger for AccountContactRelation for this operation? 
- Btw, what steps are you doing? I assume these.... https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_sales_shared_contacts.htm

**Comment by afawcett** [comment]
@RussAtlanta let us know if you need more help on this and we can re-open. Thanks!
