### ISSUE TITLE
Contact Child Trigger Deployment Error

### ISSUE THREAD

**Issue by jttrieu** [afawcett/declarative-lookup-rollup-summaries#622]
Hi, I am encountering the following error when attempting to deploy the child trigger for contact.  
Error:
![1-25-2018 4-18-01 pm](https://user-images.githubusercontent.com/35822026/35419190-7f689556-01eb-11e8-8253-58ac11b8428f.jpg)

The RU attempting to create:
![image](https://user-images.githubusercontent.com/35822026/35419217-99ab27f8-01eb-11e8-90b6-1794893f6aca.png)

**Comment by DanDonin** [comment]
Make sure you have the author apex permission

**Comment by jttrieu** [comment]
ahh... thank you, i forgot i changed profile.
