### ISSUE TITLE
Error: /**  * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)  **/ trigger dlrs_TaskTrigger on Task      (before delete, before insert, before update, after delete, after insert, after undelete, after update) {     dlrs.RollupService.triggerHandler(); }

### ISSUE THREAD

**Issue by Scubafiend** [afawcett/declarative-lookup-rollup-summaries#623]
We just started getting this when reps are trying to update tasks. For example, to push out a due date.  I've dug around and looked at all of the Lookup Rollup Summaries under Custom Metadata Types, can't find anything. If I pull up Apex Triggers, look at the Task Trigger, and select Show Dependencies, none of the checkboxes associated with Object Operational Scope for Task (Insert, Update, Delete, Upsert, Undelete, and Merge) are checked. Under Apex Class, Trigger, and Page References there is a clickable link to Rollup Service (Installed Package: Declarative Lookup Rollup Summaries Tool). If I click it I'm taken to the Apex Class Detail.

Under Methods - Signature - I see the following.
static Boolean checkMetadataAPIConnection()
--
static List rollup(List childRecords)
static void rollup(List rollupsToCalculate)
static void rollup(Map existingRecords, Map newRecords, Schema.SObjectType sObjectType)
static Id runJobToCalculate(Id lookupId)
static Id runJobToCalculate(String lookupId)
static Id runJobToCalculate(Id lookupId, String masterWhereClause)
static Id runJobToCalculate(String lookupId, String masterWhereClause)
static Id runJobToProcessScheduledItems()
static void testHandler(SObject dummyChildRecord)
static void triggerHandler()
static void triggerHandler(Schema.SObjectType childObjectType)

The full error that displays on the record when attempting to save is:
Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_TaskTrigger caused an unexpected exception, contact your administrator: dlrs_TaskTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 0011N000017rMcsQAE; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 3011N000000PUsS. Flow error messages: An unhandled fault has occurred in this flow
An unhandled fault has occurred while processing the flow. Please contact your system administrator for more information. Contact your administrator for help.: []: (dlrs)

I can't seem to chase down what the problem is with updating these specific records. If it was a problem with the flow I would expect it to be happening all of the time. I should note the only new flows are in the sandbox and have nothing to do with tasks.

I inherited this so I'm just trying to wade through and figure out what the goal was - there are at least 4 or 5 people's fingerprints on some of the automation, everyone taking a different tactic which isn't helping.

Any suggestions would be greatly appreciated!

**Comment by aheber** [comment]
@Scubafiend that flow sent an email somewhere when it crashed. Is it possible for you to track down that email? All the really good debugging info is held in that email.
From there you can determine what was wrong about the state of the record that caused that. 

Usually DLRS runs into these kinds of problems when it is pushing data from the Task up to a parent and there is something wrong with the parent.

You can chase down the specific Flow using this help article: https://help.salesforce.com/articleView?id=000239860&type=1

If you can't find the emails you can deactivate the flow, then reactivate, and your user will start getting the emails. Then have someone replicate the bug and review the resulting email.

In my experience this are more often due to Flows that aren't quite right or haven't checked for a null field somewhere.

I hope that gets your users moving again.

**Comment by DanDonin** [comment]
Another helpful way to track down a flow is open the dev console go to the
query tab and use

select masterlabel from flow where id = 'flowid'

Then make sure you check the box use tooling API next to the submit/execute
button.

Be sure to uncheck that box next time you wanna do a normal soql search ;)

**Comment by Scubafiend** [comment]
Thanks so much! The email did the trick. Deactivated the workflow and everything is fine so I can QA it at my leisure - fortunately it isn't a critical flow.

I'll play with the dev console suggestion when I get a chance to.

Thank you both!!!

**Comment by Scubafiend** [comment]
Thanks so much! The email did the trick. Deactivated the workflow and everything is fine so I can QA it at my leisure - fortunately it isn't a critical flow.

I'll play with the dev console suggestion when I get a chance to.

Thank you both!!!
