### ISSUE TITLE
Cannot include Opportunity record type in selection criteria

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#626]
I am trying to include the Opportunity Record Type in my selection criteria, but am getting an error.  The full criteria I want is:
RecordType='0120Y0000015o9cQAA' AND StageName='Closed Won'

but whenever I include, or have on its own, the first part of the clause I get the following error returned:
error is 'No such column 'RecordType' on entity 'Opportunity'.
As Record Type is a standard field I don;t understand the error - can anyone assist?

**Comment by DanDonin** [comment]
Try recordtypeid

**Comment by LawranceT** [comment]
Thanks for the response Dan, that gives me another error:  error is 'invalid ID field: 120Y0000015o9cQAA'

**Comment by DanDonin** [comment]
Use the 15 digit not the 18 digit.

**Comment by LawranceT** [comment]
Thanks Dan, seems that it is happy with a 15 digit or 18 digit, but for 14 or 17!  Missed a leading zero.  Looks like it's working
