### ISSUE TITLE
Upgrade to Latest API: New object are not available 

### ISSUE THREAD

**Issue by hiteshsalesforce** [afawcett/declarative-lookup-rollup-summaries#627]
New objects are not available e.g ProductRequest and Product Transfer. I think they are introduced in version 39.0 and above.

**Comment by afawcett** [comment]
Yep the tool needs to upgrade to the latest API for this.

**Comment by hiteshsalesforce** [comment]
Hello Andrew,

Any idea by when it will be ready with the new version ?

Thanks
Hitesh

**Comment by afawcett** [comment]
Fixed in v2.11
