### ISSUE TITLE
Created Rollup SUmmary with DRS is not working correctly and Salesforce application crashes

### ISSUE THREAD

**Issue by Mari8872** [afawcett/declarative-lookup-rollup-summaries#628]
Hi guys, 

I installed DRS in my Salesforce developer application.
I then created a Rollup Summary field on Account this way:

![unbenannt](https://user-images.githubusercontent.com/19390833/35591743-53aa9800-060b-11e8-832b-0d52696e4bdd.jpg)

By testing this, I created an opportunity with CloseDate=30/01/2018 and Amount=500. When I check if this was summarized on the Total_Amount__c on Account, this is not being summarized.

Another point: my application became slower and crashes after installation of the last update of your software. 

I would appreciate if someone could help me here.

**Comment by Mari8872** [comment]
Can please somebody help me here?

**Comment by afawcett** [comment]
So I just tried to reproduce this and could not. Below is my rollup definition (using the preferred Manage Rollup Summaries tab). One thing to note is that unless the Amount field or CloseDate field changes your rollups will not be recalculated. So when 2019 comes along, you will either have to click Calculate manually yourself or change your rollup schedule to the Full Recalculate mode described [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups). Regarding performance you do not say what version you where on and what version you have upgraded to, so it's hard to help. Some other factors to consider would be other users creating rollups and/or more data in the system. 

![image](https://user-images.githubusercontent.com/1167760/35780351-cf1528c6-098e-11e8-9d25-15c94a8d6c6e.png)

**Comment by Mari8872** [comment]
Thanks afawcett for your response. I see. The version I had installed was 2.10, the latest vesrion according to this site: 

https://github.com/afawcett/declarative-lookup-rollup-summaries

**Comment by afawcett** [comment]
No problem, glad you got sorted!
