### ISSUE TITLE
dlrs_CaseTrigger Interfering with Asset Lookups on Case?

### ISSUE THREAD

**Issue by cgerth** [afawcett/declarative-lookup-rollup-summaries#632]
We are having an issue where certain assets are not able to be added to certain cases. It's been difficult to see a pattern to the problems. It is giving us this error:

**"When you try and add your asset C-6302-CP, it is not complete with the trigger that was created."**

Salesforce Support reports that the error is being caused by the dlrs_CaseTrigger Apex Trigger when we attempt to save the case.

Is there any additional info you can provide regarding this message? How do we make the Case "complete with the trigger"?

**Comment by aheber** [comment]
@cgerth if possible I would start by disable the DLRS jobs on cases, possibly even removing the rollup triggers. If disabling DLRS fixes it then we can dig deeper, if it doesn't then we know this is not the tree you're looking for.

Please take those steps and let us know.

**Comment by afawcett** [comment]
@cgerth let us know if @aheber suggest helped or if we need to progress here? I will close out in the meantime, but we can for sure re-open. Thanks!
