### ISSUE TITLE
Rollup Max for Dates

### ISSUE THREAD

**Issue by MegK8** [afawcett/declarative-lookup-rollup-summaries#634]
Thanks for creating this app! One thing I would love to see is a way to rollup a max for dates. It looks like it can only do max for numeric fields. Is that something you hope to create?

**Comment by DanDonin** [comment]
For dates you could always order by date then select the first/last either
for max/min

**Comment by MegK8** [comment]
The max function works for dates.  I had read it only worked for numeric fields, but that was wrong.
