### ISSUE TITLE
Are "Scheduled" DLRS runs that fail skipped or queued for the following Scheduled run?

### ISSUE THREAD

**Issue by Bard09** [afawcett/declarative-lookup-rollup-summaries#635]
We've had a few "Scheduled" DLRS runs for fields that have failed due to the 50,001 error.  We're aware of how to work around the problem (by reducing the # of records processed at once) but we are wondering of the accuracy of our scheduled roll-ups days after errors like this are resolved.

Are the records that fail processed in future scheduled runs, or are they skipped over completely for future runs until there are changes (meaning the only way to fix the issue is a forcing a manual calculation on the field)?

Let me know-- thanks!  This may also be helpful for documentation :)

**Comment by afawcett** [comment]
I have updated the wiki [doc](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups) with details on failure. Hopefully, this makes sense? Let me know if not.

**Comment by Bard09** [comment]
Thank you!  This clears a lot of stuff up for us.  :)
