### ISSUE TITLE
Rollup where parent and child objects are on the same table, is it possible?

### ISSUE THREAD

**Issue by renatoliveira** [afawcett/declarative-lookup-rollup-summaries#636]
I've provided the rollup information with the object's API name, relationship field to be used, field to aggregate as `Id`, aggregate operation as `Count`. This doesn't seem to work.

My use case is that I have a custom object that can be related to other object on the same table. I'd like to know the quantity of records related to the parent.

Is this a limitation, or am I doing something wrong when configuring the tool?

**Comment by afawcett** [comment]
Take a look at [this](https://www.dandonin.com/2017/04/21/counting-tasks-with-dlrs/) and [this](http://andyinthecloud.com/2014/05/08/account-hierarchy-rollups-clicksnotcode/). If you can also include a picture of your roll-up definition and steps you are performing with expected results.
