### ISSUE TITLE
Modify test code for parent object

### ISSUE THREAD

**Issue by cmcfarling** [afawcett/declarative-lookup-rollup-summaries#637]
The Parent Object (Account) has validation that requires a value in a field. I've read through the Wiki but I'm not understanding how to modify the test code to accommodate this. It seems the Test Code field is only for modifying the Child Object. Am I missing something?

I just need
new Account()
to be
new Account(Account_Shortcode__c='ZZZ')

![image](https://user-images.githubusercontent.com/36546584/36321945-98708a42-1319-11e8-946d-1a66c680508b.png)

![image](https://user-images.githubusercontent.com/36546584/36322140-44616e48-131a-11e8-85ed-9ef9da341256.png)

**Comment by afawcett** [comment]
You are not missing something, the Test Code field only applies to child object. I have marked this as an enhancement. Meanwhile if you have access to Developer Console in your Sandbox you can copy paste these triggers and add them with your changes. So long as you use the same names the tool will let you activate the rollup. You do not need to use Manage Child Trigger.

**Comment by afawcett** [comment]
Fixed in v2.12
