### ISSUE TITLE
Declarative Lookup Rollup Summaries Tool (Managed)

### ISSUE THREAD

**Issue by TamiFrederick** [afawcett/declarative-lookup-rollup-summaries#641]
We are migrating from salesforce unlimited to enterprise edition and will need to install all of our managed packages in our new Org before the data can be migrated.  What is the impact to Declarative Lookup Rollup Summaries Tool? Can the existing data be copied/migrated to the new Org?

**Comment by afawcett** [comment]
If you have been using Manage Rollup Summaries tab (Custom Metadata based), your rollups are stored in metadata which can be extracted as metadata along with all your other custom objects, reports, fields etc etc. If you are using the Lookup Rollup Summaries tab (Custom Object based) you can use tools like Salesforce Data Loader. Make sure in either case to also include the DLRS generated triggers and test classes in your orgs metadata export and import.
