### ISSUE TITLE
Summing a field value from one object to other object

### ISSUE THREAD

**Issue by shruthsj** [afawcett/declarative-lookup-rollup-summaries#642]
I am using DLRS for updating a field(currency) value from one object to the other object.
but the problem is Source Object field value is in different currency but when the value flows into Destination object field it appears in USD irrespective of the currency type in source file.

**Comment by DanDonin** [comment]
Roll into a numeric field, use a workflow rule that updates the currency field by formula of CURRENCYRATE(currency) * field?

**Comment by shruthsj** [comment]
Two fields are currency field and its on two different object.

**Comment by afawcett** [comment]
Currency fields honor the currency of the record. So if the source and target currencies are not the same on the source and target record you will need to find a means to convert. @DanDonin's idea looks good. Or we can raise an enhancement here.

**Comment by afawcett** [comment]
@shruthsj let us know if you still need help on this one and we can for sure re-open this issue.
