### ISSUE TITLE
2.10 MetaData Trigger does not find Trigger for DLRS

### ISSUE THREAD

**Issue by Opopanax** [afawcett/declarative-lookup-rollup-summaries#643]
Create a metadata based roll up summary, realtime mode. 

Create a child record

Nothing happens. Looking at the debug log, it doesn't find there is anything that needs to be done.

The using the meta-data rule works.  Only difference I can find is the MetaData trigger uses difference Case in the trigger name compared to the non-meta data trigger rules.

[Dlrs debug log.log](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/1749663/Dlrs.debug.log.log)

https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p&fId=0D53A00003RpJq7

**Comment by DanDonin** [comment]
Was on this call some of the strangeness we saw is the naming of the trigger was slightly different when deployed with Metadata than vs Classic style.  The classic style had ObjectName where the Metadata has objectName in the trigger name.

Also using the Classic record with the trigger deployed from the classic style works in his org.   Also as you can see in his logs DLRS makes a SOQL for DLRS records finds none and returns but doesn't seem to scan for Metadata records.

**Comment by DanDonin** [comment]
@Opopanax  dont you mean the Non-metadata style works?

**Comment by afawcett** [comment]
The Trigger name case will not matter, they just get the tool running, which it clearly is. So it's looking for a match on the child object name, calculation mode realtime or scheduled and an active rollup.  Are all these conditions true on the rollup you expect to be selected? Can you include a screenshot? Also are you using the standard DLRS triggers?

**Comment by DanDonin** [comment]
He was using the standard triggers. Interesting if he deployed the trigger
via metadata dlrs the standard dlrs didn't find it and would ask to deploy
a new trigger.  Vice versa also. If he deployed via standard dlrs then the
metadata didn't see the already deployed trigger. Even when deployed via
metadata when his dlrs ran it was looking for standard dlrs records then
when the soql returned none the dlrs code would return.  He was using
lightning if that matters.

**Comment by afawcett** [comment]
Oooh i see! This is not a runtime thing? Its a deploy thing? Gotcha. So yeah some issue here then. Need to really try to avoid the hybrid use of roll-up custom object vs custom metadata tbh. As it cases a number of confusions.... this said, re-reading the original post it looks like a runtime thing? Confused now...

**Comment by DanDonin** [comment]
Also a runtime thing. He deployed via metadata and if you look at his logs
dlrs makes a query for old style dlrs records. When it doesn't find any it
just returns and doesn't do it's magic.

**Comment by DanDonin** [comment]
He only tried the object based classic style to troubleshoot cus I asked
him to. Surprisingly the classic style works because when it runs the soql
search it returns dlrs records to process. So the TLDR he deployed via
metadata and only used metadata yet the dlrs code was still set on looking
for classic dlrs records

**Comment by afawcett** [comment]
It does look for both though, per the above debug log...

SELECT Name, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 

Then...

SELECT DeveloperName, Id, Label, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__Description__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c FROM dlrs__LookupRollupSummary2__mdt WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY DeveloperName ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST

**Comment by DanDonin** [comment]
Well that is even more weird why it didn't find any...

**Comment by afawcett** [comment]
@DanDonin  and/or @Opopanax whats the next steps with this one?

**Comment by afawcett** [comment]
Closing for now due to inactivity.
