### ISSUE TITLE
Error:Apex trigger dlrs_AssetTrigger caused an unexpected exception System.SObjectException: Invalid field Account for Asset: 

### ISSUE THREAD

**Issue by huskerwendy** [afawcett/declarative-lookup-rollup-summaries#644]
First off, I've created quite a few rollup summaries using your tool and it's awesome and works great. Thanks for creating this and offering it for free! Much, much appreciated!

I'm trying to create a rollup summary on accounts from assets but am getting an Apex trigger error.  The rollup summary saves okay without error. However, when I try to update my asset, I get the error:

Error:Apex trigger dlrs_AssetTrigger caused an unexpected exception, contact your administrator: dlrs_AssetTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Asset: Class.dlrs.RollupService.handleRollups: line 843, column 1

I've attached a screenshot of the actual rollup summary. I cant' figure out what the problem is. Any help you could provide would be awesome. 
![ru_summary](https://user-images.githubusercontent.com/1280768/36613629-b6ebc44c-189f-11e8-9e96-dd1b3daa9a35.PNG)

**Comment by DanDonin** [comment]
Try AccountId not account for the relationship field

**Comment by huskerwendy** [comment]
That fixed it. Thanks! I feel sort of stupid for not trying that. I appreciate the help.
