### ISSUE TITLE
Schedule the DLRS batch to run at 11 PM pacific time instead

### ISSUE THREAD

**Issue by mubeen-qawi** [afawcett/declarative-lookup-rollup-summaries#645]
Hello, 

Is there a way we can schedule the DLRS to run at 11 PM pacific time instead of running at 2 AM pacific time.

MQ

**Comment by DanDonin** [comment]
Ever since a handful of releases ago you can schedule a calculate for
whatever cadence and time you want.  Might try updating your dlrs package.
