### ISSUE TITLE
Relationship Criteria is not being honoured and all records are being included instead of just the filtered ones

### ISSUE THREAD

**Issue by DavidMilner** [afawcett/declarative-lookup-rollup-summaries#646]
First off we are finding the dlrs tool for Salesforce invaluable and easy to use.

However, we have an issue where we are noticing that the Relationship Criteria is not being honoured and all records are being included instead of just the filtered ones.

In Relationship Criteria we have the following Processing_Date__c >= LAST_N_MONTHS:12
and in Relationship Criteria Field exists  Processing_Date__c

The dlrs is scheduled to run daily at 2:00AM (Aust. Eastern Daylight Time)

When I run a manual calculate to test, the incorrect amount is being rolled up to the parent field.

Hoping someone can help resolve this issue.

Many thanks in advance.

**Comment by afawcett** [comment]
Thanks! Are you using the [full scheduled calculate](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups)? This would be the correct thing to do as you have time-dependent aspects to your criteria. Is there any pattern you can observe to those records and those not updating? You might also want to try posting to the community chatter group linked on the README.

**Comment by DavidMilner** [comment]
Hello Andrew,

Thank you for your quick response – much appreciated.

Yes – I am using the Scheduled Full Calculate, also known as Schedule Calculate.

The issue is not that the schedule does not run, it is that the dlrs is not honouring the Relationship Criteria (in this instance it is Processing_Date__c >= LAST_N_MONTHS:12)
The dlrs is running as scheduled but the incorrect values are being rolled up to the Parent Object for all records.

Question
On which object is the Relationship Criteria applied?
I am assuming it is on the Child Object so as to filter out non-required records for the Parent Object?

I will also post to the community chatter group linked on the README.

Regards,

DavidM


Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.

**Comment by afawcett** [comment]
@DavidMilner did my last response help or not? If not, we can for sure re-open this issue and keep chatting. Thanks.

**Comment by DavidMilner** [comment]
Hello Andrew,

Yes, your last response helped.

With thanks it is ok to close this support call.

Regards,


Law In Order
David Milner
Senior Business Systems Administrator
P: +61 2 9223 9200 | F: +61 2 9223 9600
E: david.milner@lawinorder.com | W: www.lawinorder.com.au
A: Level 3, 123 Pitt Street Sydney NSW 2000
We help legal teams achieve winning outcomes
Consider the environment. Do you really need to print this email?
The information in this transmission is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or other
use of, or taking of any action in reliance upon, this information by persons
or entities other than the intended recipient in regard to the transmission's
original intent is prohibited. If you have received this in error, please
contact the sender and delete the material from any computer it may be stored
within under your control.
