### ISSUE TITLE
Set Criteria for Parent Records to Receive Roll Up Values

### ISSUE THREAD

**Issue by mizzltoy** [afawcett/declarative-lookup-rollup-summaries#647]
Hi there - I absolutely LOVE this tool!!!  This has helped with many projects!  One thing I haven't been able to figure out is the ability to determine WHICH PARENT records receive the roll up values.  For example, if I want to count the number of contacts on an Account, but ONLY want to count for Accounts where type = Prospect and not where Type = Customer, how can I do this within the roll up logic?  The only place to add criteria appears to be on child object.  Is there a way to determine criteria for the parent?

Please advise!

Thanks!

- LT

**Comment by afawcett** [comment]
You can create a formula field on the child object that references the parent type, then use that formula field in your criteria. Keep in mind though, that if the account type changes the tool will not notice this (as it's not a change to the child record). If that is an issue I guess you can develop a process builder to clear the rollup value on the account. Hope this helps, glad you like the tool!

**Comment by afawcett** [comment]
@mizzltoy Let me know if you have any other thoughts or help needed on this issue. I will close it out for now, but we can for sure re-open as need. Thanks!
