### ISSUE TITLE
Calculate Job Error

### ISSUE THREAD

**Issue by DCTMorris** [afawcett/declarative-lookup-rollup-summaries#649]
Hello,

I have four scheduled rollups that are continuing to produce the error: "A calculate job for rollup [Name of Rollup] is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again" 

Two of the rollups pull a date and a text field from a custom object and roll them to the Contact, and the other two also pull a date and a text field from the Contact to the Account. When I clear the jobs from the Lookup Rollup Calculate Jobs tab, the rollups are able to work without any trouble, but they're not able to run again when they're scheduled. When this first started happening I updated the app to version 2.11, but it keeps happening (or *not* happening).

**Comment by afawcett** [comment]
Are you seeing any errors in the Apex Jobs page for these job?

**Comment by DCTMorris** [comment]
nope. the Apex Jobs are able to process without any failures. I just ran them again to double check.
 (https://www.screencast.com/t/xZoZm5RpBpf)

**Comment by afawcett** [comment]
So the records stick around in Lookup Rollup Calculate Jobs? Are you using Custom Metadata based rollups or Custom Object based ones?

**Comment by DCTMorris** [comment]
That isn't something that I typically think about or look at frequently, so I'm not sure what the difference is between Custom Metadate and Custom Object based rollups, but I think it's metadata because these are DLRS lookups...but again, I'm not 100% sure. Here are screenshots of them:

Object to Contact Date: https://www.screencast.com/t/K6yFmwwik
Object to Contact Text: https://www.screencast.com/t/nX21k7ahwk

Contact to Account Date: https://www.screencast.com/t/RGZg9pQn
Contact to Account Text: https://www.screencast.com/t/4HOZDY7eP3

**Comment by DCTMorris** [comment]
I'm still not having any luck getting this DLRS to run.

**Comment by afawcett** [comment]
Are you around today to discuss?

**Comment by afawcett** [comment]
It looks like you are using Custom Metadata based rollups.

So the records stick around in Lookup Rollup Calculate Jobs?

**Comment by DCTMorris** [comment]
sorry i missed those posts. Yeah, the inial job runs without any errors, but then it gets stuck in the lookup rollup calculate jobs, and it just quits doing future batch jobs.

**Comment by afawcett** [comment]
So...

1. You check and/or clear records in the Lookup Calculate Jobs
2. You open a roll-up record definition
3. You press Calculate and run the job, there are no errors on the Apex Jobs page and it completes
4. You check Lookup Calculate Jobs tab and it has a record in it
5. You press Calculate and to run the job again and get the error

Have i got this correct?

If so i would love to take a close look at this, either over the phone or via subscriber support. 

Andy

**Comment by DiannaStockdale** [comment]
Did you come up with a solution to this?  It has also just started happening with 4 DLRS rollups that have been running fine for 10 months.

**Comment by AimGee** [comment]
I'm experiencing the same issue...

**Comment by MJWasburnTrailhead** [comment]
Andrew, I am seeing the same bug, just starting today. Running DLRS v 2.11

**Comment by afawcett** [comment]
@DiannaStockdale  @AimGee @MJWasburnTrailhead  can you all please comment as to if my steps to reproduce Apr 2018 are what your seeing? And if not, what are you steps to repo?
