### ISSUE TITLE
Can remove child trigger with active "Scheduled" rollups

### ISSUE THREAD

**Issue by davidknoll** [afawcett/declarative-lookup-rollup-summaries#651]
I'm using the metadata DLRS for (amongst other things) counting the number of Tasks associated with an Opportunity. Until recently it was active in "Scheduled" mode. The trigger was deployed, as "Getting Started" says so for this mode.

A new scheduled job elsewhere needs to send out a bunch of emails and have them automatically saved as activities. (This is done with one call to Messaging.sendEmail for the batch.) When it hits 50 emails, it breaks with `System.LimitException: dlrs:Too many SOQL queries: 101: []`. It looks like DLRS is doing two separate queries for each Task that is invoking the trigger (even though I'm only calling sendEmail once). I'll need to use Schedule Calculate instead.

So I removed the trigger- first, with the lookup still active and "Scheduled". **It let me remove it.** (However, it didn't let me then save the lookup again- until I actually changed the calculation mode.)

**Comment by afawcett** [comment]
Yes, the trigger can be removed while active. I decided not to try and protect against this. Since using Manage Child Trigger is not the only way to remove the trigger. The other ways the tool would not notice anyway, e.g. via Change Sets. Thanks for the feedback though! 👍
