### ISSUE TITLE
Cannot remove trigger and cannot install change set with trigger in place

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#653]
I've hit a problem relating the DLRS:  A developer of another 3rd party app is trying to install a change set from a sandbox to a production environment.  In doing so we are hitting a validation error:

dlrs_AccountTest testTrigger System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Name]: [Name]
Stack Trace: Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_AccountTest.testTrigger: line 11, column 1

I can't work out what is causing the problem.  There is an inactive trigger named dlrs_AccountTrigger, which I thought might be related, so I thought I could delete this and recreate it from the Manage Child Trigger button, but whilst I could delete this trigger in my sandbox I do not have a delete option for it in Production.

Unfortunately the previous system administrator of this site, who was here before I was called in, had deleted all of the roll up summaries that I had previously created but had not first removed the triggers, so it looks like I have an orphan trigger with no related roll-up summary.  Could this have anything to do with it?

I thought I could uninstall and reinstall DLRS but I'm prevented from uninstalling because of the two triggers dlrs_AccountTrigger and dlrs_AccountTest

Has anyone any ideas what the cause may be or how I could get around it?  Many thanks in advance for any ideas or advice

**Comment by ybiyani** [comment]
@LawranceT, I faced a similar issue with another app and the way to resolve this is to create empty triggers in the sandbox. So in a sandbox, remove all the code from the triggers then use a changeset to deploy to Production. If successful, try to uninstall DLRS.

**Comment by LawranceT** [comment]
@ybiyani , many thanks for the reply.  I can see the idea here, but how do I create a new trigger with no code?  If I use the default code that comes with a new trigger I get a compile error:  Error: Compile Error: Unexpected token '<'. at line 1 column 9	

If I remove all the code entirely I get a compile error Error: Compile Error: Unexpected token '<EOF>'. at line 1 column 1

I get the same problem if I use DLRS to create the relevant child trigger and then try to delete the code from it.

Sorry if it's a rookie question but I'm not a developer...

**Comment by afawcett** [comment]
Have a read through this, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage, you may need some customer test code on your rollup. I am surprised it was not needed before tbh. What you can try is to use the Manage Child Trigger button to remove the trigger, do the changeset deploy, then re-deploy the dlrs trigger, again via the Manage Child Trigger button.

**Comment by LawranceT** [comment]
Thanks Andrew.  Removing the trigger as you suggest was my preferred option but I had a problem in that the roll-up summaries had been removed, leaving the triggers behind, so then I could not remove the triggers.  Eventually I got a developer to deactivate the triggers, deployed the change set and deployed the triggers.  Not straight forward but it worked.
