### ISSUE TITLE
Incorrect child trigger showing on Manage Child Trigger

### ISSUE THREAD

**Issue by NHodsonIdeal** [afawcett/declarative-lookup-rollup-summaries#656]
Hi,
I was experiencing some deployment issues with a roll up that was not in use. To solve the problem, I removed the trigger and deleted the rollup. 

When I try to deploy an brand new rollup, the trigger for the previously removed trigger is deploying instead.

Is there a way to prevent this?

Natalie

**Comment by aheber** [comment]
@NHodsonIdeal are you still having this problem? Could you provide some additional details? Is it the wrong object it is trying to deploy for?

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
