### ISSUE TITLE
dlrs_c2godaTransactionLineItemTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction Line Item: Object validation has failed. Current company not set.: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_c2godaTransactionLineItemTest.testTrigger: line 11, column 1

### ISSUE THREAD

**Issue by Dianacloudteam** [afawcett/declarative-lookup-rollup-summaries#657]
Hi

I'm having this error any idea of why is this happening?

![image](https://user-images.githubusercontent.com/37808601/37917343-7730d346-311e-11e8-8a8c-db9a51b68b34.png)

Error:
dlrs_c2godaTransactionLineItemTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Object validation has failed. Transaction Line Item: Object validation has failed. Current company not set.: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_c2godaTransactionLineItemTest.testTrigger: line 11, column 1

And also this other 2 messages

Warning:
dlrs_c2godaTransactionLineItemTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

Messages

Deployment complete.
Click Deploy to install the Apex Trigger and Apex Class for this child object.

what does that mean? how can I solve this? please I need your help

**Comment by aheber** [comment]
This one is a pain. I would probably review this closed issue for thoughts.
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/603

It is a hack to get the test code working but in most cases it is enough. Doing it the "right" way requires significantly more effort, there are a few other closed issues on here that might help.

**Comment by afawcett** [comment]
Yes also take a look at this, http://help.financialforce.com/accounting-api/17X/WritingApexTests.htm
