### ISSUE TITLE
Rollup (count of contacts) not calculating 

### ISSUE THREAD

**Issue by zoejcwilliams** [afawcett/declarative-lookup-rollup-summaries#658]
Hi there, my apologies if this is a basic question with an easy fix, but I'm still a bit new to this tool. 

I created a straightforward rollup to count the number of contacts on an account, but for certain accounts (which most definitely have contacts) the rollup is not calculating -- and I can't figure out why. 

Rollup: 
![screen shot 2018-03-26 at 12 52 33 pm](https://user-images.githubusercontent.com/37810121/37920346-a137ed98-30f4-11e8-924e-9f5e1ea29a83.png)

Example (there are 3 contacts on this account, and yet the "Count of Contacts" field is not populated): 

![screen shot 2018-03-26 at 12 54 55 pm](https://user-images.githubusercontent.com/37810121/37920490-f846ba38-30f4-11e8-808d-736c8f494aee.png)

**Comment by aheber** [comment]
@zoejcwilliams to confirm, have you already run a full calculation on your org? That would be done by selecting Calculate from the DLRS summary screen, then pressing Calculate again without any filter criteria. This problem often comes from activating the rollup and modifying some of the children so they calculate the parent but never running the full calculate as part of the initial creating.

If you have done the full calculate this could have been the result of a segment of records failing, could you check the Apex Jobs in Setup and find where the Rollup job was run, see if there were any errors during the execution?

Hopefully that is enough to get started.

**Comment by zoejcwilliams** [comment]
@aheber thanks for the quick response! I did do the full calculation and just ran it again, and confoundingly enough, no errors -- 

![screen shot 2018-03-26 at 1 20 55 pm](https://user-images.githubusercontent.com/37810121/37921750-a675ae7c-30f8-11e8-917e-91a83141163b.png)

Not sure what to make of this -- it's not working for 1,191 accounts, but is working just fine for the rest.

**Comment by aheber** [comment]
That is very interesting. You have the job running in User Sharing mode, is it possible your user doesn't have access to these accounts? (I realize that isn't likely as you're running reports against them)
You could try switching to System and re-running.

What is the total number of account records in your system? Does the 69 chunks roughly match up to that? (200 x 69 = ~13,800) Or does number represent only those records which were successfully calculated and exclude those without a value?

I'm not sure of any reason why you would be missing the data. I would expect at least those fields would show zero if it couldn't find any children for them.

**Comment by zoejcwilliams** [comment]
Total number of accounts is only 6,812 -- I'm re-running it with sharing mode set to System and will see if that changes anything!

**Comment by zoejcwilliams** [comment]
Ran it again with sharing mode set to System, same result (no failures) -- but the same batch of accounts is still not populating. Argh!

**Comment by zoejcwilliams** [comment]
Update - I tried running it using the 18 digit Contact ID instead of the standard Contact ID; exact same result.

The extra confounding thing is that *another* rollup I created ("Sum of Contact Scores") is populating off of these contacts just fine: 

![screen shot 2018-03-28 at 10 29 59 am](https://user-images.githubusercontent.com/37810121/38035736-06046812-3273-11e8-987f-47a97b591f76.png)

**Comment by dkryger** [comment]
We are also experiencing an issue rolling up Contact information to the Account.  We have some flags on the Contact for different Departments and the Rollups are not always correct.  We are using Version 2.8 of DLRS.  On one Account I removed all Contacts and I am getting Department counts > 0.

Thanks for any help,
dkryger

**Comment by afawcett** [comment]
_"but the same batch of accounts is still not populating"_

If you update some of the contacts on those accounts in the UI, do you see any errors? Does it update the accounts then?

**Comment by afawcett** [comment]
@dkryger hows things going? Did you try my last suggestion?

**Comment by ajhunt80** [comment]
I'm also fairly novice with DLRS and having this same issue. I have other DLRS triggers that are running just fine (on other objects) and I'm pretty sure the record I created for this one is good. I'm not sure what further information would be useful to provide for troubleshooting.

![dlrs nps record](https://user-images.githubusercontent.com/38767486/39328159-0ccc5e08-4960-11e8-8ed9-55950e66811e.png)

**Comment by slhemingway** [comment]
I have a similar issue with the using the Sum aggregate operation where about 11% of the records that meet the relationship criteria are not being counted/added together.

**Comment by afawcett** [comment]
Can anyone on this thread having this issue simply create a contact manually in the ui for an account and confirm if the rollup is run or not?

**Comment by slhemingway** [comment]
Not sure if this will be helpful but the field I was summing up was a formula field and DLRS wasn't recognizing 'changes' on the field. I've made some process changes so that DLRS is no longer referencing a formula field and that seemed to resolve the issue for me. Thanks!

**Comment by careerwise-colorado** [comment]
Hi all, 

I'm having the exact same issue with Contacts and a Custom Object. I can confirm that when one of the Child Custom objects is created, the parent is updated. But when I try to calculate the job, the batch runs with no errors but fails to update the parents. None of the fields involved are formulas and there is another roll-up relying on the same Child Trigger that is running just fine. 

Curiously, I am only running into this issue in production? This trigger and the batch update works fine in my Full Copy Sandbox that was refreshed about 3 weeks ago. 

All help is appreciated!

**Comment by Przemowild** [comment]
@afawcett Hi Andrew, I have got a similar issue. The rollup counts properly for 14k campaign records but there are 376 that are not being calculated and the rollup field remains blank.
I don't understand why it works fine for most of the records and doesn't for a small group of them. There are no validation rules or anything that would prevent the update, the records can be modified manually without any issues, debug log doesn't show any issues. Do you have any suggestions why count job wouldn't work for some records? Thanks in advance, Przemek

**Comment by afawcett** [comment]
@Przemowild sorry - its hard to guess without seeing the data and steps to reproduce. You might want to raise this in the community chatter group for further eyes.
