### ISSUE TITLE
User validaion: Preventing save

### ISSUE THREAD

**Issue by maddmurdoc1** [afawcett/declarative-lookup-rollup-summaries#659]
My users are making changes to the opportunity object and receiving the following error: 
    Apex script unhandled trigger exception by user/organization: 00540000001NkQg/00D300000000O4F
    
    dlrs_OpportunityTrigger: execution of AfterUpdate
    
    caused by: System.DmlException: Update failed. First exception on row 0 with id 70140000001MHf4AAG; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, The Show Close Date CAN NOT be a date prior to the Show Open Date. Please update the Show Close Date.: [Show_Close_Date__c]
    
    Class.dlrs.RollupService.Updater.updateRecords: line 1311, column 1
    Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1354, column 1
    Class.dlrs.RollupService.updateRecords: line 1282, column 1
    Class.dlrs.RollupService.handleRollups: line 888, column 1
    Class.dlrs.RollupService.triggerHandler: line 311, column 1
    Trigger.dlrs_OpportunityTrigger: line 7, column 1

The validation in question is working normally without the dlrs in play. Any ideas on what this is or how to get around it would be very helpful. Thanks.

**Comment by aheber** [comment]
@maddmurdoc1 going out on a limb here, if I had to guess this is validation on the parent record being triggered when the child record is modified. Is it possible if you went to that same record and hit Edit -> Save it would throw the same validation error? If so there isn't anything DLRS can do when the data is already non-compliant.

If DLRS is rolling up a value that causes the validation to fail you'll have to re-think how your rollup and validation work together.

We can talk about it a little more if you need technical details, or if I didn't understand the problem you're having.

**Comment by maddmurdoc1** [comment]
Thanks so much for responding, but when I go to the record and hit edit and save it saves. The validation cited is in compliance and it's really rather simple. So, I am very much at a loss here of even how to troubleshoot this.

**Comment by afawcett** [comment]
Can you post pictures of your rollup and your validation rule please?

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
