### ISSUE TITLE
Getting recurring error CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY

### ISSUE THREAD

**Issue by Seoladair** [afawcett/declarative-lookup-rollup-summaries#661]
Using NPSP and Volunteers for Salesforce on my org (Enterprise Edition) with DLRS (v2.9). We are attempting to roll up a number of hours volunteers are working if they are flagged as a special group. This roll up was working at one point, but now is getting errors. No real changes to that part of the org have been identified. The error message is:

GW_Volunteers.VOL_VRS_MaintainHours: execution of AfterUpdate

caused by: System.ListException: Duplicate id in list: a3q0P000000UloIQAS

(GW_Volunteers)
: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY ()
Parent Object: GW_Volunteers__Volunteer_Recurrence_Schedule__c

Attached is a screenshot of the rollup declaration.
![dlrs bbb 50 hour club](https://user-images.githubusercontent.com/3173352/38178308-93bae950-35d5-11e8-988b-c5693d6c5fc7.PNG)

**Comment by afawcett** [comment]
I have to confess, NPSP issues are a big challenge for me. It's a super complex package to navigate and even to start asking more questions here it's hard to pinpoint. The only thing i can suggest is DM me some details and we can perhaps arrange for me to go into the org (subscriber support?) and find out a bit more. That said the debug logs can be huge still and hard to understand. An ideal option is to sit down with a dev on NPSP and myself at the same screen. I have no idea if this is possible, but i am willing to give it a try if such a thing could be arranged? I am based in San Francisco.

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
