### ISSUE TITLE
Rollup for Non Profit Success Pack for Fund Code Allocation is not rolling up to Parent record

### ISSUE THREAD

**Issue by gavinbritto** [afawcett/declarative-lookup-rollup-summaries#662]
Dear Trailblazer Ohana,

I am helping out the Christian Broadcasting Network who are on NPSP. 
![donation_erd_2018-04-03_0125](https://user-images.githubusercontent.com/38031114/38236010-e8e1487c-36f0-11e8-9d6f-f4a29357f1b0.png)

The Child record, Fund Allocation is 3408, but Fund Code on parent record, Donation says says 3401

Take a look at the screen capture
https://www.screencast.com/t/MBYziNyLFaBi

I have also attached the ERD of the object structure and the Schema definitions
[ob_schema10-01-2017 (1).xlsx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/1870600/ob_schema10-01-2017.1.xlsx)

**Comment by afawcett** [comment]
That should work, but i would have used First and applied Field to Order By to sort the child record i wanted. I assume yuo want the first or last or something?

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
