### ISSUE TITLE
INTERNAL_ERROR, __MISSING LABEL__ PropertyFile - val WorkflowLogOnlyException_desc not found in section

### ISSUE THREAD

**Issue by MrStarbuck** [afawcett/declarative-lookup-rollup-summaries#665]
We started getting the following error after upgrading to v2.11 from 1.9.  Any ideas on what is going on or how to workaround?

> Error: Invalid Data. 
> 
> Review all error messages below to correct your data.
> 
> Apex trigger PaidHolidayTrigger caused an unexpected exception, contact your administrator: PaidHolidayTrigger: execution of AfterInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_Time_EntryTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id a140e000005StPgAAK; first error: INTERNAL_ERROR, \_\_MISSING LABEL\_\_ PropertyFile - val WorkflowLogOnlyException_desc not found in section Exception: [] Class.dlrs.RollupService.Updater.updateRecords: line 1315, column 1 Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1358, column 1 Class.dlrs.RollupService.updateRecords: line 1286, column 1 Class.dlrs.RollupService.handleRollups: line 918, column 1 Class.dlrs.RollupService.triggerHandler: line 329, column 1 Trigger.dlrs_Time_EntryTrigger: line 7, column 1: []: Class.PaidHolidayTriggerHandler.insertTimeEntries: line 167, column 1

**Comment by afawcett** [comment]
I cannot think of anything tbh. The originating error message here is actually not from the DLRS tool code. But it is preventing the DLRS tool from updating the parenter record on the Time_Entry__c object. It looks like some code at Class.PaidHolidayTriggerHandler.insertTimeEntries: line 167, column 1 is doing an insert.

~~~
INTERNAL_ERROR, __MISSING LABEL__ PropertyFile - 
val WorkflowLogOnlyException_desc not found in section
~~~

Does the above error message text occur in any other code in the org? You can use Developer Console via the menu to search for text or fragments of the above in your code.

**Comment by afawcett** [comment]
@AltiusRupert  thanks for reporting, appreciate it. 👍
