### ISSUE TITLE
Created a roll up summary to count the records related to an opportunity but it does not work RealTime.

### ISSUE THREAD

**Issue by Jmazzurco6** [afawcett/declarative-lookup-rollup-summaries#670]
I've tried adding new records but it doesn't appear to be working.

![image](https://user-images.githubusercontent.com/38352507/38734943-50ad39dc-3ef5-11e8-9d8a-f2f5513c4b5e.png)

**Comment by afawcett** [comment]
Have you clicked the Manage Child Trigger button to deploy the trigger code to your child object?

**Comment by Jmazzurco6** [comment]
Yes, it's deployed. What triggers the update of the record? It appears only
some of them are working. My hypothesis is that only net new ones causes
the update but haven't confirmed that yet.

*Jeremy Mazzurco*, Systems & Insights Manager
*Nulogy Corporation* | 480 University Ave, Suite 1200, Toronto, Ontario,
M5G 1V2
<https://maps.google.com/?q=480+University+Ave,+Suite+1200,+Toronto,+Ontario,+M5G+1V2&entry=gmail&source=g>
*M**:* 416-629-7321  |  *E:* jeremym@nulogy.com | www.nulogy.com
[image: www.nulogy.com] <http://www.nulogy.com/>

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
