### ISSUE TITLE
Parent Object: Object does not exist.

### ISSUE THREAD

**Issue by DonSco307** [afawcett/declarative-lookup-rollup-summaries#672]
I seem to be unable to create a rollup from an object called Inforce_Insurance__c to the Product object.

I have a lookup on the Inforce object for Product.  There are values on the Inforce that I want to rollup to the Product.

Any idea why I would get this error??

**Comment by DonSco307** [comment]
Thank you. I was able to figure it out.

Thank you,
Donna Lutchman
Consultant | Appcentrica, Inc.
647-336-6944

**Comment by afawcett** [comment]
@DonSco307 excellent! 😀

**Comment by sullivannich** [comment]
I am having this same issue, are you able to share what solved your issue?
![image](https://user-images.githubusercontent.com/51796429/114726483-0cca9d80-9d03-11eb-9e1d-1ea52cbeeacb.png)

Here's an image of my attempt.
