### ISSUE TITLE
Improved UI messaging to direct users to the Manage Lookup Rollup Summaries tab

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#677]
This upcoming release is the first to add new features only to the Custom Metadata based rollup definitions. So i have added some new messaging to the UI's displayed when using the Custom Object based UI's to start to encourage migration over to the recommended Manage Lookup Rollup Summaries tab. I plan to also build a migration tool to avoid having to re-enter the rollup definitions and delete the old ones manually.

**Comment by shawnholt** [comment]
@afawcett hi - was looking for new metadata api and cannot see it.  Is this new UI feature planned?  is metadata available in lightning?  thanks!

**Comment by afawcett** [comment]
Fixed in v2.12

**Comment by afawcett** [comment]
<img width="717" alt="warning" src="https://user-images.githubusercontent.com/1167760/78516131-5df99600-776d-11ea-9390-451b704ecaff.png">
