### ISSUE TITLE
DLRS Meeting Attendees Not Being Rolled Up

### ISSUE THREAD

**Issue by alexmarkle** [afawcett/declarative-lookup-rollup-summaries#681]
Hi all, 

I created a DLRS of Activity Dates where subject of related Activity records equals 'Meeting'.

This Most Recent Meeting Date works great for contacts with Individual Meetings, however group meeting records only roll up on the primary contact. Other contacts attached as Attendees show the record on their Activity History related list, but it is not registering in the DLRS result field. 

Is there a solution  for this? Or do group activities just not work? I can attach pics if necessary. 

Thanks, 

Alex

**Comment by afawcett** [comment]
Yes i think some pics and steps to reproduce, with expected behaviour and actual behaviour detailed would be good thank you.

**Comment by escholl** [comment]
@alexmarkle - Were you ever able to figure this out? I'm having the same issue and I'm starting to think it's not possible.
