### ISSUE TITLE
Issue Deploying CampaignMember Trigger

### ISSUE THREAD

**Issue by vpesaturo** [afawcett/declarative-lookup-rollup-summaries#683]
I am getting the following error when deploying the Campaign Member trigger:

![image](https://user-images.githubusercontent.com/38990703/39648783-7307928a-4fb1-11e8-8d20-f6e2212fee75.png)

Can you please let me know how to fix this issue?

**Comment by afawcett** [comment]
Have a read through this, it should help. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197
