### ISSUE TITLE
Adding filter exclusions to the rollup

### ISSUE THREAD

**Issue by MLHEUMANN** [afawcett/declarative-lookup-rollup-summaries#687]
We want to roll-up a field but want to EXCLUDE certain fields that fit certain parameters.

**Comment by afawcett** [comment]
Hi @MLHEUMANN can i ask for more detail on your request please. Background, use case, example etc?

**Comment by afawcett** [comment]
@MLHEUMANN pleae feel free to give some more details on this and we can re-open np 👍
