### ISSUE TITLE
Apex Debug Log : a lot of DLRS lines

### ISSUE THREAD

**Issue by DavidOxa** [afawcett/declarative-lookup-rollup-summaries#688]
Hello,

I'l trying to solve an issue on my "preprod" org.
With Salesforce support, we ran an "Apex Debug Log" on my "Preprod" org and also on my "Prod" org to see the differences.

On the "Preprod" one, half of the lines are DLRS lines. Here are some examples of lines:
`17612:09:38.0 (192648511)|ENTERING_MANAGED_PKG|dlrs
17712:09:38.0 (197180100)|ENTERING_MANAGED_PKG|dlrs
17812:09:38.0 (197462332)|ENTERING_MANAGED_PKG|dlrs
17912:09:38.0 (204134083)|ENTERING_MANAGED_PKG|dlrs
18012:09:38.0 (211022445)|ENTERING_MANAGED_PKG|dlrs
18112:09:38.0 (214476775)|ENTERING_MANAGED_PKG|dlrs
18212:09:38.0 (214630411)|ENTERING_MANAGED_PKG|dlrs
18312:09:38.0 (216535524)|ENTERING_MANAGED_PKG|dlrs
18412:09:38.0 (216720471)|ENTERING_MANAGED_PKG|dlrs
18512:09:38.0 (216799662)|ENTERING_MANAGED_PKG|dlrs
18612:09:38.0 (217009288)|ENTERING_MANAGED_PKG|dlrs
18712:09:38.0 (217395984)|ENTERING_MANAGED_PKG|dlrs
18812:09:38.0 (217932849)|ENTERING_MANAGED_PKG|dlrs
18912:09:38.0 (222168845)|ENTERING_MANAGED_PKG|dlrs
19012:09:38.0 (222283924)|ENTERING_MANAGED_PKG|dlrs
19112:09:38.0 (223169225)|ENTERING_MANAGED_PKG|dlrs
19212:09:38.0 (223245849)|ENTERING_MANAGED_PKG|dlrs
19312:09:38.0 (223369687)|ENTERING_MANAGED_PKG|dlrs
19412:09:38.0 (223454330)|ENTERING_MANAGED_PKG|dlrs
19512:09:38.0 (223779065)|ENTERING_MANAGED_PKG|dlrs
19612:09:38.0 (223886369)|ENTERING_MANAGED_PKG|dlrs
19712:09:38.0 (223972519)|ENTERING_MANAGED_PKG|dlrs
19812:09:38.0 (227248575)|ENTERING_MANAGED_PKG|dlrs
19912:09:38.0 (227490155)|ENTERING_MANAGED_PKG|dlrs
20012:09:38.0 (227723588)|ENTERING_MANAGED_PKG|dlrs
20112:09:38.0 (227876091)|ENTERING_MANAGED_PKG|dlrs
20212:09:38.0 (228184846)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
20312:09:38.0 (228272059)|ENTERING_MANAGED_PKG|dlrs
20412:09:38.0 (228388987)|ENTERING_MANAGED_PKG|dlrs
20512:09:38.0 (228596529)|HEAP_ALLOCATE|[239]|Bytes:8
20612:09:38.0 (228645257)|VARIABLE_ASSIGNMENT|[EXTERNAL]|this|{}|0x3c89d89b
20712:09:38.0 (228663866)|VARIABLE_ASSIGNMENT|[EXTERNAL]|object|{}
20812:09:38.0 (228681289)|ENTERING_MANAGED_PKG|dlrs
20912:09:38.0 (228847852)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
21012:09:38.0 (228914503)|ENTERING_MANAGED_PKG|dlrs
21112:09:38.0 (229028522)|ENTERING_MANAGED_PKG|dlrs
21212:09:38.0 (229205221)|HEAP_ALLOCATE|[239]|Bytes:8
21312:09:38.0 (229235852)|VARIABLE_ASSIGNMENT|[EXTERNAL]|this|{}|0x3c89d89b
21412:09:38.0 (229253493)|VARIABLE_ASSIGNMENT|[EXTERNAL]|object|{}
21512:09:38.0 (229270247)|ENTERING_MANAGED_PKG|dlrs
21612:09:38.0 (229432119)|HEAP_ALLOCATE|[239]|Bytes:8
21712:09:38.0 (229457494)|VARIABLE_ASSIGNMENT|[EXTERNAL]|this|{}|0x681204a5
21812:09:38.0 (229473781)|VARIABLE_ASSIGNMENT|[EXTERNAL]|object|{}
21912:09:38.0 (229489741)|ENTERING_MANAGED_PKG|dlrs
22012:09:38.0 (229673142)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
22112:09:38.0 (229741540)|ENTERING_MANAGED_PKG|dlrs` (etc...)
 

then

`206212:09:38.0 (440332624)|ENTERING_MANAGED_PKG|dlrs
206312:09:38.0 (440525815)|ENTERING_MANAGED_PKG|dlrs
206412:09:38.0 (440891159)|ENTERING_MANAGED_PKG|dlrs
206512:09:38.0 (441175240)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
206612:09:38.0 (441201504)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x57b29386
206712:09:38.0 (441209696)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
206812:09:38.0 (441227367)|VARIABLE_ASSIGNMENT|[627]|o|{}
206912:09:38.0 (441308659)|ENTERING_MANAGED_PKG|dlrs
207012:09:38.0 (441522412)|ENTERING_MANAGED_PKG|dlrs
207112:09:38.0 (441904385)|ENTERING_MANAGED_PKG|dlrs
207212:09:38.0 (442382141)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
207312:09:38.0 (442420055)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x119ef7b3
207412:09:38.0 (442436738)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
207512:09:38.0 (442466191)|VARIABLE_ASSIGNMENT|[627]|o|{}
207612:09:38.0 (442620064)|ENTERING_MANAGED_PKG|dlrs
207712:09:38.0 (442907310)|ENTERING_MANAGED_PKG|dlrs
207812:09:38.0 (443346665)|ENTERING_MANAGED_PKG|dlrs
207912:09:38.0 (443815623)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
208012:09:38.0 (443853931)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x4cbc8e37
208112:09:38.0 (443870291)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
208212:09:38.0 (443902151)|VARIABLE_ASSIGNMENT|[627]|o|{}
208312:09:38.0 (444059613)|ENTERING_MANAGED_PKG|dlrs
208412:09:38.0 (444344334)|ENTERING_MANAGED_PKG|dlrs
208512:09:38.0 (444781857)|ENTERING_MANAGED_PKG|dlrs
208612:09:38.0 (445231107)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
208712:09:38.0 (445260981)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x6cdc9b0b
208812:09:38.0 (445270127)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
208912:09:38.0 (445285056)|VARIABLE_ASSIGNMENT|[627]|o|{}
209012:09:38.0 (445370578)|ENTERING_MANAGED_PKG|dlrs
209112:09:38.0 (445552212)|ENTERING_MANAGED_PKG|dlrs
209212:09:38.0 (445800942)|ENTERING_MANAGED_PKG|dlrs
209312:09:38.0 (446057862)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
209412:09:38.0 (446084545)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x3ff644b0
209512:09:38.0 (446093297)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
209612:09:38.0 (446107199)|VARIABLE_ASSIGNMENT|[627]|o|{}
209712:09:38.0 (446194965)|ENTERING_MANAGED_PKG|dlrs
209812:09:38.0 (446368908)|ENTERING_MANAGED_PKG|dlrs
209912:09:38.0 (446608666)|ENTERING_MANAGED_PKG|dlrs
210012:09:38.0 (446874743)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
210112:09:38.0 (446900282)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x4b407203
210212:09:38.0 (446908798)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
210312:09:38.0 (446922960)|VARIABLE_ASSIGNMENT|[627]|o|{}
210412:09:38.0 (447003471)|ENTERING_MANAGED_PKG|dlrs
210512:09:38.0 (447179023)|ENTERING_MANAGED_PKG|dlrs
210612:09:38.0 (447416271)|ENTERING_MANAGED_PKG|dlrs
210712:09:38.0 (447667347)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
210812:09:38.0 (447691975)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x63c4f305
210912:09:38.0 (447700310)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
211012:09:38.0 (447714155)|VARIABLE_ASSIGNMENT|[627]|o|{}
211112:09:38.0 (447793405)|ENTERING_MANAGED_PKG|dlrs
211212:09:38.0 (447958285)|ENTERING_MANAGED_PKG|dlrs
211312:09:38.0 (448206885)|ENTERING_MANAGED_PKG|dlrs
211412:09:38.0 (448457254)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
211512:09:38.0 (448481535)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x17a7ed08
211612:09:38.0 (448489723)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
211712:09:38.0 (448503345)|VARIABLE_ASSIGNMENT|[627]|o|{}
211812:09:38.0 (448581746)|ENTERING_MANAGED_PKG|dlrs
211912:09:38.0 (448744849)|ENTERING_MANAGED_PKG|dlrs
212012:09:38.0 (448965156)|ENTERING_MANAGED_PKG|dlrs
212112:09:38.0 (449218841)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
212212:09:38.0 (449243976)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x67855094
212312:09:38.0 (449251783)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
212412:09:38.0 (449265103)|VARIABLE_ASSIGNMENT|[627]|o|{}
212512:09:38.0 (449342577)|ENTERING_MANAGED_PKG|dlrs
212612:09:38.0 (449509117)|ENTERING_MANAGED_PKG|dlrs
212712:09:38.0 (449741844)|ENTERING_MANAGED_PKG|dlrs
212812:09:38.0 (449988072)|VARIABLE_SCOPE_BEGIN|[627]|this|dlrs.fflib_QueryFactory.QueryField|true|false
212912:09:38.0 (450012267)|VARIABLE_ASSIGNMENT|[627]|this|{}|0x7cb79ad
213012:09:38.0 (450021118)|VARIABLE_SCOPE_BEGIN|[627]|o|Object|false|false
213112:09:38.0 (450035005)|VARIABLE_ASSIGNMENT|[627]|o|{}
213212:09:38.0 (450118515)|ENTERING_MANAGED_PKG|dlrs
213312:09:38.0 (450286579)|ENTERING_MANAGED_PKG|dlrs
213412:09:38.0 (450520592)|ENTERING_MANAGED_PKG|dlrs`

`219512:09:38.0 (469060494)|ENTERING_MANAGED_PKG|dlrs
219612:09:38.0 (469926970)|ENTERING_MANAGED_PKG|dlrs
219712:09:38.0 (470046816)|ENTERING_MANAGED_PKG|dlrs
219812:09:38.0 (471308714)|ENTERING_MANAGED_PKG|dlrs
219912:09:38.0 (471389277)|ENTERING_MANAGED_PKG|dlrs
220012:09:38.0 (471472437)|ENTERING_MANAGED_PKG|dlrs
220112:09:38.0 (471556451)|ENTERING_MANAGED_PKG|dlrs
220212:09:38.0 (471610212)|ENTERING_MANAGED_PKG|dlrs
220312:09:38.0 (471652938)|ENTERING_MANAGED_PKG|dlrs
220412:09:38.0 (471709504)|ENTERING_MANAGED_PKG|dlrs
220512:09:38.0 (471753418)|ENTERING_MANAGED_PKG|dlrs
220612:09:38.0 (471805170)|ENTERING_MANAGED_PKG|dlrs
220712:09:38.0 (471847681)|ENTERING_MANAGED_PKG|dlrs
220812:09:38.0 (471894583)|ENTERING_MANAGED_PKG|dlrs
220912:09:38.0 (471935514)|ENTERING_MANAGED_PKG|dlrs
221012:09:38.0 (471981762)|ENTERING_MANAGED_PKG|dlrs
221112:09:38.0 (472023092)|ENTERING_MANAGED_PKG|dlrs
221212:09:38.0 (472070036)|ENTERING_MANAGED_PKG|dlrs
221312:09:38.0 (472111516)|ENTERING_MANAGED_PKG|dlrs
221412:09:38.0 (472165202)|ENTERING_MANAGED_PKG|dlrs
221512:09:38.0 (472207086)|ENTERING_MANAGED_PKG|dlrs
221612:09:38.0 (472253084)|ENTERING_MANAGED_PKG|dlrs
221712:09:38.0 (472294312)|ENTERING_MANAGED_PKG|dlrs
221812:09:38.0 (472340329)|ENTERING_MANAGED_PKG|dlrs
221912:09:38.0 (472381736)|ENTERING_MANAGED_PKG|dlrs
222012:09:38.0 (472427635)|ENTERING_MANAGED_PKG|dlrs
222112:09:38.0 (472469564)|ENTERING_MANAGED_PKG|dlrs
222212:09:38.0 (472516080)|ENTERING_MANAGED_PKG|dlrs
222312:09:38.0 (472557990)|ENTERING_MANAGED_PKG|dlrs
222412:09:38.0 (472605072)|ENTERING_MANAGED_PKG|dlrs
222512:09:38.0 (472646836)|ENTERING_MANAGED_PKG|dlrs
222612:09:38.0 (472692513)|ENTERING_MANAGED_PKG|dlrs
222712:09:38.0 (472734200)|ENTERING_MANAGED_PKG|dlrs
222812:09:38.0 (472780718)|ENTERING_MANAGED_PKG|dlrs
222912:09:38.0 (472822595)|ENTERING_MANAGED_PKG|dlrs
223012:09:38.0 (472869030)|ENTERING_MANAGED_PKG|dlrs
223112:09:38.0 (472910899)|ENTERING_MANAGED_PKG|dlrs
223212:09:38.0 (472957125)|ENTERING_MANAGED_PKG|dlrs
223312:09:38.0 (473012709)|ENTERING_MANAGED_PKG|dlrs
223412:09:38.0 (473111741)|ENTERING_MANAGED_PKG|dlrs
223512:09:38.0 (473192720)|ENTERING_MANAGED_PKG|dlrs
223612:09:38.0 (473319586)|ENTERING_MANAGED_PKG|dlrs
223712:09:38.0 (473383943)|ENTERING_MANAGED_PKG|dlrs
223812:09:38.0 (473417568)|ENTERING_MANAGED_PKG|dlrs
223912:09:38.0 (473444869)|ENTERING_MANAGED_PKG|dlrs
224012:09:38.0 (473476895)|ENTERING_MANAGED_PKG|dlrs
224112:09:38.0 (473513593)|ENTERING_MANAGED_PKG|dlrs
224212:09:38.0 (473546816)|ENTERING_MANAGED_PKG|dlrs
224312:09:38.0 (473583060)|ENTERING_MANAGED_PKG|dlrs
224412:09:38.0 (473615866)|ENTERING_MANAGED_PKG|dlrs
224512:09:38.0 (473652186)|ENTERING_MANAGED_PKG|dlrs
224612:09:38.0 (473685049)|ENTERING_MANAGED_PKG|dlrs
224712:09:38.0 (473721399)|ENTERING_MANAGED_PKG|dlrs
224812:09:38.0 (473753930)|ENTERING_MANAGED_PKG|dlrs
224912:09:38.0 (473790740)|ENTERING_MANAGED_PKG|dlrs
225012:09:38.0 (473823859)|ENTERING_MANAGED_PKG|dlrs
225112:09:38.0 (473859672)|ENTERING_MANAGED_PKG|dlrs
225212:09:38.0 (473892447)|ENTERING_MANAGED_PKG|dlrs
225312:09:38.0 (473928677)|ENTERING_MANAGED_PKG|dlrs
225412:09:38.0 (473961098)|ENTERING_MANAGED_PKG|dlrs
225512:09:38.0 (473997427)|ENTERING_MANAGED_PKG|dlrs
225612:09:38.0 (474029818)|ENTERING_MANAGED_PKG|dlrs`

etc etc...

It seems there is a recursive problem. Are you able to help me to understand what is happening?

Thanks in advance!

David

**Comment by afawcett** [comment]
According to this https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_forcecom_debugging_log_levels.htm Salesforce should have fixed it. You might want to share this with Salesforce Support.
