### ISSUE TITLE
Realtime triggers don't work 

### ISSUE THREAD

**Issue by adamarkman** [afawcett/declarative-lookup-rollup-summaries#689]
I have several realtime triggers that work on status and record type. Only part of them work in realtime. If there  are  2 triggers that must be fired on change in one of the 2 fields, only one is fired. 
The triggers are working fine on "calculate" . All are deployed. 
No formula. One has a where clause with IN, the other with NOT IN. Pretty simple rules. 
Any idea why only one trigger is fired ? 
Thanks
Ada

**Comment by afawcett** [comment]
The default behaviour of the rollup tool is to look for changes to the field your rolling up on, the one specified in the Field to Aggregate field. In addition you can list other fields for it to look at via the Relationship Criteria Fields field, which as the name suggests is also important information if you’ve used rollup criteria. However its also important if the field your rolling up on is a Formula field. In the case of formula field rollups the platform doesn’t inform the tools Apex Trigger of changes to these. So it cannot directly monitor such fields and to resolve this must instead be told explicitly about the fields that are referenced by the formula expression. So far so good…
