### ISSUE TITLE
Unable to unInstall

### ISSUE THREAD

**Issue by Gilnl** [afawcett/declarative-lookup-rollup-summaries#690]
Hi there,
I am trying to remove (uninstall) DLRS from our sandbox environment but I get an error message that I cannot uninstall because of 2 permission sets in use:
 

1. Lookup Rollup Summaries - Process Rollups
2. Lookup Rollup Summaries - Configure Rollups |  

However, I cannot delete them from the Setup menu.
What is the approach to successfully  remove it?
Thank you,
Gil

**Comment by Gilnl** [comment]
@afawcett

**Comment by afawcett** [comment]
You need to unassign these permission sets from your users not delete them, they will be deleted when the package is uninstalled. Simply click on each and manage the users assigned to each. Once you have no assigned users to either of these permission sets you should be able to get past the error shown.

**Comment by afawcett** [comment]
@Gilnl the above should have solved your issue, let me know if not and we can discuss further.
