### ISSUE TITLE
Concatenate Distinct in a text field

### ISSUE THREAD

**Issue by rioulesmills** [afawcett/declarative-lookup-rollup-summaries#691]
Hi everyone 

I've an issue DLRS and this lookup.
Running a calculate on lookup is doing the job but if i update a SBQQ_Subcription__c nothing happens. 
In my case "Aggregate Result Field" is an text field (255 caracters)
Have you any idea ?

![capture d ecran 2018-05-17 a 11 13 11](https://user-images.githubusercontent.com/35811081/40168567-18fa5300-59c4-11e8-86db-effe3a08a0e4.png)

**Comment by afawcett** [comment]
The default behaviour of the rollup tool is to look for changes to the field your rolling up on, the one specified in the Field to Aggregate field. In addition you can list other fields for it to look at via the Relationship Criteria Fields field, which as the name suggests is also important information if you’ve used rollup criteria. However its also important if the field your rolling up on is a Formula field. In the case of formula field rollups the platform doesn’t inform the tools Apex Trigger of changes to these. So it cannot directly monitor such fields and to resolve this must instead be told explicitly about the fields that are referenced by the formula expression. So far so good…

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
