### ISSUE TITLE
SOQL 101 Error - Writing equivalent trigger doesn't hit the limit

### ISSUE THREAD

**Issue by TheMIkeyBoosh** [afawcett/declarative-lookup-rollup-summaries#692]
Hi,

After using the DLRS tool for a few roll ups, i have encountered an issue with the SOQL 101 governor limit. I am not a developer, so the issue might be a misunderstanding of what the DLRS does in the background.

I have the issue posted on StackExchange too - [Stack](https://salesforce.stackexchange.com/questions/218422/soql-query-limits-in-wrapper-class-using-dlrs).

The issue is that when creating multiple records using a wrapper class the governor limits are being hit with a subsequent DLRS update to a parent record. When I write a trigger, which does the same job, the SOQL limits come right back down (to 4 in total).

Does the DLRS do something else other than just trigger update, which causes the DLRS? Does it not play nicely with wrapper/multiple record creations etc.?

Other than this, the tool is great and a fantastic effort on your part!

Thanks

Mike

**Comment by TheMIkeyBoosh** [comment]
Whilst the scenario is concerning, I have managed to find another solution.

**Comment by afawcett** [comment]
Thanks @TheMIkeyBoosh . I see the issue was a Process Builder config. https://salesforce.stackexchange.com/questions/218422/soql-query-limits-in-wrapper-class-using-dlrs Thanks for closing.
