### ISSUE TITLE
DLRS NOT calculating for all records

### ISSUE THREAD

**Issue by AnilGithubCommunity** [afawcett/declarative-lookup-rollup-summaries#693]
Hi, We are using DLRS(andyinthecloud) for multiple use-cases and everything seems to be working fine.

But when I recently created a new DLRS rule on a custom object, its NOT calculating roll up for all the records. Rollup is calculated on few records and not on others. (I do not have any Relationship Criteria as you can see on the attached snapshot)

I could not find a unique pattern, when I tried doing some analysis on why few records are not getting updated. 

But when I manually edited one of the child record's calculation field(Date__c), DLRS seems to be calculating and rolling up to its parent object.

So I'm not sure, why the DLRS is not calculating for all the records in real time when I click the calculate button. Could you please share me your thoughts ? Thank You!!

\\DLRS rule: Calculate Max date from child records. Date is a custom field on child record.\\
<img width="835" alt="screen shot 2018-05-20 at 9 28 55 pm" src="https://user-images.githubusercontent.com/39472175/40287334-a6a8f432-5c7a-11e8-932f-e0b1afdb9dab.png">

PS: Thank you for creating this great app.

**Comment by afawcett** [comment]
Background: What causes a Rollup to recalculate?
The default behaviour of the rollup tool is to look for changes to the field your rolling up on, the one specified in the Field to Aggregate field. In addition you can list other fields for it to look at via the Relationship Criteria Fields field, which as the name suggests is also important information if you’ve used rollup criteria. However its also important if the field your rolling up on is a Formula field. In the case of formula field rollups the platform doesn’t inform the tools Apex Trigger of changes to these. So it cannot directly monitor such fields and to resolve this must instead be told explicitly about the fields that are referenced by the formula expression. So far so good…

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
