### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mowata** [afawcett/declarative-lookup-rollup-summaries#694]
Hi Andy, trying to install 2.11 and getting:

![image](https://user-images.githubusercontent.com/13166612/40310384-7515c9d8-5d04-11e8-9998-901df54e4a62.png)

**Comment by afawcett** [comment]
Wow not seen this before. That error makes no sense tbh. I would raise this with Salesforce support to see if they have any ideas. Maybe share what they say here if you can. Thanks.

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
