### ISSUE TITLE
Realtime Calculation is not working 

### ISSUE THREAD

**Issue by mollybockwoldt** [afawcett/declarative-lookup-rollup-summaries#695]
Hello! 
I have created two roll-ups and scheduled them in realtime and using system sharing mode. My criteria is when a box is checked on the Quote, to sum up the GrandTotal on a Quote to the Opportunity but this only works when I manually click "Calculate". I thought it had something to do with the total fields but we are manually checking the accepted box and it still isn't firing. Any thoughts on this one? 
![screen shot 2018-05-21 at 11 00 38 am](https://user-images.githubusercontent.com/39492225/40314363-46971058-5ce6-11e8-9913-75ebdb3a8e0f.png)

**Comment by afawcett** [comment]
Have a read of this, https://andyinthecloud.com/2016/02/13/rollups-and-cross-object-formula-fields/ especially the bit about Relationship Criteria Fields. You need to put your checkbox field in that as well basically. Good luck, happy to re-open if no joy. 👍
