### ISSUE TITLE
Mary Myers

### ISSUE THREAD

**Issue by MaryMyers** [afawcett/declarative-lookup-rollup-summaries#697]
Error:
Salesforce Metadata API connection failure, click the link below to configure. 
Declarative Rollup Summaries App already have a remote site and it was working fine until about a week ago
Mary Myers
mmyers@acocares.org

**Comment by DanDonin** [comment]
Did you have a cluster migration or turn on a custom domain name?

**Comment by MaryMyers** [comment]
i personally did not do either. Salesforce had an update during this time frame. I am new to Salesforce,

**Comment by DanDonin** [comment]
Just remove the old one and readd the new one. Should fix it right up.

**Comment by MaryMyers** [comment]
Remove what old one and readd what new one, i'm sorry i dont know what you are referring to

**Comment by DanDonin** [comment]
The remote site settings

**Comment by MaryMyers** [comment]
I have 2 remote site settings for Declarative rollup summare one is DLRS and one it dlrs mdapi both are active. could this be causing some problem

**Comment by MaryMyers** [comment]
DLRS has 

https://acocares--dlrs.na67.visual.force.com
-- as remote site URL

mdapi as 

https://acocares--dlrs.na33.visual.force.com
as remote site URL
--

**Comment by rogeramitchell** [comment]
You'll want to update the mdapi setting to have the same base URL that you see when viewing the page that gave you the error. Presumably this will be `https://acocares--dlrs.na67.visual.force.com`

**Comment by MaryMyers** [comment]
do i make the DLRS not Active

**Comment by rogeramitchell** [comment]
Your remote site setting named "DLRS" should not have an effect on the app, so it's up to you whether you deactivate / delete it

**Comment by MaryMyers** [comment]
on dlrs mdapi i change the URL to the na69 URL and refreshed and it still has the error in the app and then i made the DLRS not active and i still have the error. Should i disable the protocol security

**Comment by MaryMyers** [comment]
sorry na67 URL

**Comment by rogeramitchell** [comment]
Assuming the page that gives you the error starts with **https://acocares--dlrs.na67.visual.force.com**, the values should appear as below:

- Remote Site Name: dlrs_mdapi
- Remote Site URL: https://acocares--dlrs.na67.visual.force.com
- Disable Protocol Security: unchecked (false)
- Description: Metadata API Remote Site Setting for Declarative Rollup Tool (DLRS)
- Active: checked (true)

An alternative would be deleting the Remote Site named "dlrs_mdapi" and recreating it from the Welcome tab.

**Comment by MaryMyers** [comment]
deleting and recreating worked. thanks

**Comment by rogeramitchell** [comment]
Awesome, you should be able to mark this issue as closed now @MaryMyers

**Comment by afawcett** [comment]
@rogeramitchell  thank you!
