### ISSUE TITLE
Preexisting Apex Class and Trigger has disappeared for Child Object

### ISSUE THREAD

**Issue by SentiaUSAInc** [afawcett/declarative-lookup-rollup-summaries#698]
Hi!

I was just creating a new rollup to average a value on all Contact (child object) for a User (parent object) and received an error I haven't seen before. I've attached a screenshot of the error but basically it says:

classes/dlrs_ContactTest.cls (Line: null: Column:null) : Error: A class with name sentia_vda.dlrs_ContactTest was deprecated for this package or this name is already in use!
triggers/dlrs_ContactTrigger.trigger (Line: null: Column:null) : A trigger with name sentia_vda.dlrs_ContactTrigger was deprecated for this package or this name is already in use!

I've created a few rollups with the contact as the child object and the apex class and apex trigger already existed and is a part of our managed app on Salesforce. However sometime in the last week the trigger has been lost or removed somehow.

Now, when I create a new rollup, it prompts me to create and deploy the trigger as if it was new but then throws up the error whenever I try to do so.

The dlrs_ContactTrigger and dlrs_ContactTest are no longer in the list of Apex Classes and Triggers in Salesforce, and as far as I can see the other rollup summaries that use Contact as a child object don't run in realtime any more, but don't throw up the error despite being set to calculate in realtime and needs the trigger and class as well.

I have created new rollups today for other objects already with the apex classes and triggers deployed and haven't had this issue for any other objects.

Thanks!!

![error](https://user-images.githubusercontent.com/39687568/40597740-9e44e528-6286-11e8-8c1a-e1b7fbc809d3.PNG)

**Comment by demanda** [comment]
Seemingly related, I suddenly am getting an error when I try to save my new rollup: 	
Error:
Active: Apex Trigger dlrs_lit_AttendanceTrigger has not been deployed. Click Manage Child Trigger and try again.

There's no Manage Child Trigger button until the rollup is saved, so it's preventing me from creating in the first place.

**Comment by DanDonin** [comment]
Save it as inactive. Deploy trigger. Then activate the dlrs.

**Comment by demanda** [comment]
Oh!! Right!  Thank you Dan.

**Comment by afawcett** [comment]
Thanks @DanDonin
