### ISSUE TITLE
Not allowed to add Account Relationships

### ISSUE THREAD

**Issue by rpresnell** [afawcett/declarative-lookup-rollup-summaries#699]
We use the Declarative Lookup Rollup Summaries tool to add account relationships in our Salesforce implementation.  We currently receive the error message: 

dlrs_AccountContactRelationTrigger: execution of   AfterInsert caused by: dlrs.RollupServiceException: Lookup Rollup Summary   'Account Relationship' is invalid, your org configuration may have changed (Aggregate   Result Field: Organization__c). Class.dlrs.RollupService.createLSFWrapper:   line 1231, column 1 Class.dlrs.RollupService: line 1093, column 1   Class.dlrs.RollupService: line 1027, column 1 Class.dlrs.RollupService: line   919, column 1 Class.dlrs.RollupService.triggerHandler: line 311, column 1   Trigger.dlrs_AccountContactRelationTrigger: line 7, column 1

When we contacted Salesforce support and they said that we had to contact the app provider because the trigger is coming from this managed package.  I tried reaching out via the telephone number given, but it did not go through.  Please let me know the best way to contact you.  I can send the debug log, as well.  Thank you!

**Comment by afawcett** [comment]
Go the Lookup Rollup Summaires tab OR Manage Rollup Summaries tab and find the Rollup 'Account Relationship'. Open it and either delete it or fix it. The Aggregate Result Field field has an invalid field defined in it. The Organization__c field no longer exists on the specified Child Object.
