### ISSUE TITLE
Apex trigger dlrs error

### ISSUE THREAD

**Issue by juhnniemer** [afawcett/declarative-lookup-rollup-summaries#700]
Hi,

Could someone advise me please on how I can resolve my issue. I created a trigger because I wanted to get the max date each under Notes and Attachments section in my salesforce object. I have the attached trigger set to active and when I tried creating a new note, I can't save it as I am getting the apex trigger issue. Would you help me resolve this please. What do I need to change in my code?

Thanks in advance, and if you have any questions, please let me know.
![apex trigger issue](https://user-images.githubusercontent.com/39890532/40894090-a9c2dee8-67d9-11e8-9801-c72e009637e3.jpg)
![apex trigger code](https://user-images.githubusercontent.com/39890532/40894092-adc5a462-67d9-11e8-84fb-b6641796bb09.jpg)

Thanks so much,
Juhn

**Comment by DanDonin** [comment]
Looks like you are trying to roll a date time into a date field.

**Comment by juhnniemer** [comment]
Hello DanDonin,

Yes, the original date is datetime field.

**Comment by afawcett** [comment]
@juhnniemer  you need to roll into a date, not datetime field. That should fix it.

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.
