### ISSUE TITLE
dlrs:Too many SOQL queries: 101

### ISSUE THREAD

**Issue by battarro** [afawcett/declarative-lookup-rollup-summaries#701]
Good morning, I have been trying to deploy to my production environment my own custom solution, but even the simplest tests that creating a new account/contact runs into the too many soql calls.

I have even disabled all the DLRS, marking them as inactive but they still generate the following error
ContactRolesBatchFillMasterTest.testGenerateAccountsForTesting -- System.LimitException: dlrs:Too many SOQL queries: 101
Stack trace: Class.dlrs.RollupSummariesSelector.CustomObjectSelector.selectActiveByChildObject: line 164, column 1
Class.dlrs.RollupSummariesSelector.selectActiveByChildObject: line 80, column 1
Class.dlrs.RollupService.describeRollups: line 1069, column 1
Class.dlrs.RollupService.handleRollups: line 750, column 1
Class.dlrs.RollupService.triggerHandler: line 329, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1

these two are the queries that show up over and over
13:26:12:421 SOQL_EXECUTE_BEGIN [164]|Aggregations:0|SELECT Name, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 

13:26:09:789 SOQL_EXECUTE_BEGIN [286]|Aggregations:0|SELECT DeveloperName, Id, Label, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__Description__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c FROM dlrs__LookupRollupSummary2__mdt WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY DeveloperName ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST

**Comment by afawcett** [comment]
Closing, happy to re-open for further discussion.

**Comment by alpalch** [comment]
Is this case resolved? I have the same issue, but the most weird thing, is that this issue fires in a test context, when I'm trying to create 250 campaign members and then send them emails using SingleEmailMessage
