### ISSUE TITLE
Dependent picklist copying issues

### ISSUE THREAD

**Issue by budmelvin** [afawcett/declarative-lookup-rollup-summaries#703]
A contractor we hired created a routine to copy picklists and their dependencies from one object to a couple other custom objects - to keep all items in sync.

The code appears to be using this declarative lookup rollup summaries managed package to create a list of List<MetadataService.CustomField> to copy and using MetadataService.MetadataPort .updateMetadata() to update them.

We are using this on 3 level picklists Picklist A,  controlling Picklist B. Then picklist B, controlling picklist C and picklist D. Copy of items and depencencies works great for picklist A and picklist B, but items for C and D are not copying.

I am wondering if I will need to install the unmanaged package for further debugging in a sandbox or if this problem has come up or can be looked at.

Thanks.

**Comment by budmelvin** [comment]
I haven't got the source code working yet - error  Apex type not found for element restrictedPicklist that I need to research.

I've found that by running the updateMetadata() one at a time for each field, instead of a loop - I can get the items to copy. However, on the 3rd level picklist the dependencies are not copying over. On the 2nd level it seems fine.

I think 3rd level dependency was a more recent addition - is there something buggy happening here?

Anyone?

**Comment by budmelvin** [comment]
I've found something else through testing. Everything works fine when there is only one 3rd level dependent picklist. Meaning Pickist1 -> Picklist2 -> Picklist3  and picklist 3 items and dependencies copy ok

But if Picklist2 is controlling field for both a Picklist3 and a Picklist4, neither of these lists have the dependencies carried over.

**Comment by afawcett** [comment]
Are you sure this relates to DLRS?

**Comment by afawcett** [comment]
@budmelvin still not sure how this relates to DLRS, i think its more of Apex Metadata API issue tbh. Happy to continue to discuss.
