### ISSUE TITLE
inspite of the batch job being scheduled it is not getting executed

### ISSUE THREAD

**Issue by drroundcorner** [afawcett/declarative-lookup-rollup-summaries#704]
- Although the Scheduled Jobs page says that the RollupCalculateJob last ran on 5/23 at 3 am, I'm not seeing any record of the job running in the Apex Jobs page:

 - at the time the batch was suppose to execute, at the scheduled time it was observed that it did not even attempt to run the scheduled job. No error was also seen neither on the debug logs page nor in the apex jobs page.

 - We submitted a Salesforce.com case:  19115101: Salesforce on their end sees the job immediately failed with the message "Scheduled Apex job not finding its core.async_apex_row: jobId: 70736000061Uwr7, orgId: 00D36000000JE79" classId: 01p3600000JQPzC

 - We have deleted the scheduled jobs and then rescheduled them but the issue persists.  

 - We are seeing this behavior with all of the dlrs rollups we have built that they are not rescheduled again.

**Comment by afawcett** [comment]
@drroundcorner please let me know if you want to discuss further.
