### ISSUE TITLE
Triggering the duplicate rules when closing a case

### ISSUE THREAD

**Issue by saihanuman** [afawcett/declarative-lookup-rollup-summaries#706]
first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AssetTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 1 with id .....................; first error: DUPLICATES_DETECTED, You're creating a duplicate Account. We recommend you to use existing Account Instead.: [] (dlrs) : []: ()

we do have other places where this error caught, we placed the code at dml operations like insert/update to bypass the duplicate rule. In the the above one we cannot able to fix it because of managed package code. Please suggest

**Comment by afawcett** [comment]
It must be that a child record for a duplicate account is being updated/inserted/deleted, is that possible?

**Comment by afawcett** [comment]
@saihanuman happy to re-open this if you want to discuss more.
