### ISSUE TITLE
System.AsyncException: Future method cannot be called from a future or batch method

### ISSUE THREAD

**Issue by bdJohnson72** [afawcett/declarative-lookup-rollup-summaries#707]
I was trying to run a roll up on tasks and it looks like I am firing errors on from a Pardot trigger.   Will this throw an error for every contact in my Org? I have been getting errors for about 15 minutes now. 

ContactTrigger: execution of AfterUpdate

caused by: System.AsyncException: Future method cannot be called from a future or batch method: CustomPARDOT.ProspectAPIRequest(String, String, String, String, Boolean, Boolean)

**Comment by afawcett** [comment]
Looks like a bug in the pardot trigger code. It should be checking if its running in async before trying to invoke its own async code. I am assuming your rollup is running in schedule mode?

**Comment by sharmavishal94** [comment]
Hi Andrew, Can you please elaborate more about - 
It should be checking if its running in async before trying to invoke its own async code.

**Comment by afawcett** [comment]
@sharmavishal94  yes 100% correct
