### ISSUE TITLE
Working with validation rules

### ISSUE THREAD

**Issue by FBosler** [afawcett/declarative-lookup-rollup-summaries#708]
I am using Rollup Summaries to count the number of tasks on opportunities. However, I have a validation rule in place that won't allow users to edit closed opportunities. Since the rollup summary runs with the users context it is also not able to calculate the number correctly. Any way to work around this?

Cheers and thx!

**Comment by DanDonin** [comment]
Make the dlrs read only then set changes to that field when change bypass
the validation rule

**Comment by FBosler** [comment]
Thx for the reply don! I am unfortunately not quite sure what exactly you mean. Could you maybe elaborate a bit?

**Comment by DanDonin** [comment]
Sorry it took a while.

Set the field DLRS is writing to be a Read-Only field in the FLS.  Set the
DLRS to run as System. In your Validation Rule set something like
NOT(ISCHANGED(DLRS_FIELD__C)) that way if DLRS makes a change to that field
it is read only so you know it is a system based change.

**Comment by FBosler** [comment]
Thx Don! This is pretty smart, but also pretty simple :)
