### ISSUE TITLE
zipFile is not defined

### ISSUE THREAD

**Issue by jbergKC** [afawcett/declarative-lookup-rollup-summaries#709]
When I click the "Deploy" button on a child trigger nothing happens. Checking the console log files clicking the button results in a "SCRIPT5009: 'zipFile' is not defined" error.
This is in a Sandbox environment.

**Comment by afawcett** [comment]
Hmmm this is a new one. What browser are you using? Are you in classic or Lightning? Running any plugins that might impact?

**Comment by jbergKC** [comment]
FWIW this resolved itself by refreshing he sandbox. Thanks for following up!

Jeff Berger
513-675-9327

Please forgive typos--this email was crafted on the go! 📱
