### ISSUE TITLE
Can't deploy Apex Trigger for NPSP OppPayment object

### ISSUE THREAD

**Issue by ejablow** [afawcett/declarative-lookup-rollup-summaries#711]
Keep running into this error when I try to deploy the Apex Trigger for the NPSP object Payment. I tried temporarily deactivating the trigger handlers that have the referenced Class in the error message and redeploying but still got the errors (one on the Payment object, one on the Opportunity object). Any help would be appreciated! Thanks.

<img width="1407" alt="screen shot 2018-06-21 at 12 48 37 pm" src="https://user-images.githubusercontent.com/40470663/41733292-74b5ae26-7551-11e8-9a7e-4c578f8f242e.png">

**Comment by afawcett** [comment]
Have a read through this, https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. You will need a dev to give you a snippet of test code to past into the rollup config i suspect.
