### ISSUE TITLE
Apex trigger dlrs_OpportunityTrigger caused an unexpected exception

### ISSUE THREAD

**Issue by venkatasatishp** [afawcett/declarative-lookup-rollup-summaries#712]
Getting this error and because of managed package i don't know how to resolve this issue.

![dlrs opportunity trigger](https://user-images.githubusercontent.com/40670904/42048615-60f248d6-7ac9-11e8-8138-efa9dba877ec.JPG)

Please advise.

**Comment by afawcett** [comment]
It looks like you may need to have used AccountId as the relationship field in your rollup.
