### ISSUE TITLE
Scheduling RollupJob

### ISSUE THREAD

**Issue by cesera** [afawcett/declarative-lookup-rollup-summaries#715]
I have been using Declarative Lookup Rollup Summaries for about a year now, and it makes Salesforce so much more usable, I absolutely love it.

Recently I have run into problem where I keep getting the "dlrs Too many SOQL queries: 101" error. I understand from doing some research that I can get around that by using "Scheduled Incremental Calculate" mode for several rollups as described in this article: "https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups". However the problem that I am running into is that I only seem to be able to schedule the RollupJob apex class to run daily or monthly. I would be able to use this if I could run it something like every 30 mins. Can you tell me if there is a way to use "Scheduled Incremental Calculate" mode and schedule it to run every 30 mins?

**Comment by afawcett** [comment]
Sorry thats not possible due to a platform restriction for scheduling Apex jobs. The only other option would be schedule it a few more times throughout the day. But be aware you have a limited number of scheduled jobs per org.
