### ISSUE TITLE
Error during class deploy

### ISSUE THREAD

**Issue by kking8899** [afawcett/declarative-lookup-rollup-summaries#716]
I get the following error when i try to deploy the class:

![image](https://user-images.githubusercontent.com/29736044/42652250-cf656f8e-85df-11e8-83d5-290d26798c69.png)

triggers/dlrs_OpportunityTrigger.trigger (Line: null: Column:null) : Not available for deploy for this organization
triggers/dlrs_OpportunityTrigger.trigger-meta.xml (Line: null: Column:null) : Not available for deploy for this organization
classes/dlrs_OpportunityTest.cls (Line: null: Column:null) : Not available for deploy for this organization
classes/dlrs_OpportunityTest.cls-meta.xml (Line: null: Column:null) : Not available for deploy for this organization

**Comment by afawcett** [comment]
This looks like its a Person Edition org, the tool is not supported in this org.
