### ISSUE TITLE
Rollup Picklist Into Number Field

### ISSUE THREAD

**Issue by guituacek** [afawcett/declarative-lookup-rollup-summaries#720]
Hello, 

Are Max/Min Rollups supported on Picklists? I have an Contact picklist raging from 1-5 and need the max value to populate on the Account. I thought this was supported but I am getting the following error: 
Only Date/DateTime/Time/Numeric fields are allowed for Sum, Max, Min and Avg

Is this unsupported?

**Comment by aheber** [comment]
@guituacek the picklist doesn't really store as a number, we access it like a text string. This prevents us from running things like Max on it. We can still order the query results however. That would allow you to take the First value.

If you select a rollup type of First with an Order By of Picklist__c DESC NULLS LAST that might do what you're looking for. Let us know if it works.

**Comment by aheber** [comment]
I usually recommend counting Id where Checkbox = true. That should do the trick.

**Comment by guituacek** [comment]
Thank You! @aheber
