### ISSUE TITLE
Roll Up adding values 

### ISSUE THREAD

**Issue by timteagueuk** [afawcett/declarative-lookup-rollup-summaries#721]
I am pulling my hair out here :) 
We have multi-currency enabled but its not correctly giving me the right amount for all won opps this year in the field.
Will attach screenshots - Help is appreciated (Havn't used Github before either)
![result](https://user-images.githubusercontent.com/41996459/43519694-605f38f0-9588-11e8-90df-548151f5c581.JPG)
![report check](https://user-images.githubusercontent.com/41996459/43519699-641b0ffa-9588-11e8-82a1-8386ae8739fb.JPG)
![roll](https://user-images.githubusercontent.com/41996459/43519703-68015034-9588-11e8-8b98-daed684da96d.JPG)

**Comment by timmy2cakes** [comment]
Total Spend This Year is the Roll Up field on the account

**Comment by afawcett** [comment]
@timteagueuk sorry this got missed - let me know if you still want to chat - we can re-open.
