### ISSUE TITLE
Rollup not triggering for only one user sporadically

### ISSUE THREAD

**Issue by KellySFAdmin** [afawcett/declarative-lookup-rollup-summaries#722]
I have a realtime roll up set to sum individual commission amounts (child) to a placement record (parent) which are linked via a lookup relationship. The field to aggregate is not a formula field, it is a currency field. It is working consistently for all users with the same profile except one. For that one user it sometimes works and sometimes doesn't. When I manually change the field as them it then rolls up. Has anyone ever encountered this before? Any ideas on next steps or what could be causing it? I have tested this logged in as them and I can not seem to replicate the non roll up outcome so short of sitting next to them for a period of time I am at a loss.

![image](https://user-images.githubusercontent.com/42020162/43562050-553e300c-966e-11e8-8eed-88acab008eab.png)

**Comment by afawcett** [comment]
@KellySFAdmin  it might be worth posting this on the chatter group if you didn't already. See link in the README file.
