### ISSUE TITLE
Code deployment error in Sandbox only, not Production

### ISSUE THREAD

**Issue by tcharles12** [afawcett/declarative-lookup-rollup-summaries#723]
I'm receiving the below error when I try to deploy the dlrs code (manage child trigger) in Sandbox. I tested deployment in production, and I did not receive an error. Any ideas why this might be still happening in sandbox only?

dlrs_ContactTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Failed to create Account for Contact null null. Record Type ID: this ID value isn't valid for the user: 01246000000dYJkAAM: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_ContactTest.testTrigger: line 11, column 1

dlrs_ContactTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

![dlrs](https://user-images.githubusercontent.com/42197522/43817743-e2737f7a-9a8f-11e8-812d-601ccc611f56.png)

**Comment by tcharles12** [comment]
Hi there,

Thanks for your response! Actually, my colleague did track down the ID
yesterday and he said he deleted it from both sandbox and production since
we didn't need it (part of NPSP), but maybe there is another ID triggering
the error? It's a bit odd that it's only triggering in sandbox. I'll keep
looking, but I'm not an expert at DLRS, so I'm pretty stumped. I let my
colleague know and he is also finding it strange that it's not working in
sandbox.

Thank you,
Tara

**Comment by tcharles12** [comment]
Hi again,

I found it! It was the household record type that wasn't set as active, and
that record type didn't exist in production. Thanks!!

Best,
Tara

**Comment by aheber** [comment]
👍 

Glad you got it worked out. If you can, go ahead and close the issue.
