### ISSUE TITLE
Excluding data on Multiple Contacts

### ISSUE THREAD

**Issue by JozoTClown** [afawcett/declarative-lookup-rollup-summaries#724]
I have a lookup with sales and order data. Here is the path it takes

Account-Contact-Campaignmember-Campaign
My Issue is:
When multiple contacts on the same account are members of the same campaign the sales and order data rolls up with each contact giving me a higher than actual figures.

Is there a way to have data rollup to only one campaign member but still letting multiple campaign members from the same account be in a campaign.

**Comment by afawcett** [comment]
@JozoTClown it might be better to post this one on the Chatter Community Group linked on the README file for this repo.
