### ISSUE TITLE
Lighting Application

### ISSUE THREAD

**Issue by brianbier** [afawcett/declarative-lookup-rollup-summaries#726]
Can I use this for my lightning application?

I want to utilizes the functionality but I don't know if the declarative lookup rollup summaries I create on my scratch org will come down through meta data. Is there a package version number to make it a dependency of a sfdx project

**Comment by afawcett** [comment]
@brianbier yes you can define rollup rules and triggers in a scratch org and pull them in a scratch org. Just install the dlrs package in your scratch org.
