### ISSUE TITLE
Receiving error for deleted Rollup

### ISSUE THREAD

**Issue by NimblyJen** [afawcett/declarative-lookup-rollup-summaries#729]
I deleted a rollup AND a field, but I still receive error. 

- Deleted Pilot_Status__c
- Deleted rollup ‘Opportunity Products - Roll up PIlot Status’

Apex trigger dlrs_OpportunityLineItemTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityLineItemTrigger: execution of AfterInsert caused by: dlrs.RollupServiceException: Lookup Rollup Summary ‘Opportunity Products - Roll up PIlot Status’ is invalid, your org configuration may have changed (Field to Aggregate: Pilot_Status__c).: Class.dlrs.RollupService.createLSFWrapper: line 1227, column 1

**Comment by afawcett** [comment]
You need re-instate the rollup definition and click the Manage Child Trigger button then click Remove. This will undeploy the generated Apex Trigger that is still active. Or you can use Developer Console or another developer tool to deactivate the trigger or remote it manually.
