### ISSUE TITLE
Calculation of sum wrong, when Multicurrency enable

### ISSUE THREAD

**Issue by raulramoso** [afawcett/declarative-lookup-rollup-summaries#730]
I am making a sum roll up on the opportunity for all opportunity products with specific product family.

The Base Currency is USD, but when Opportunity and Opportunity product use other currency (same in both e.g MXN), it seems that it first convert to USD and then convert again to MXN. 

If I definy the record type as a number, the calculation is correct showing the USD, but when I put currency as the record type, it got wrong.

My opportunity type is 60,000 MXN (2,876.90 USD), and it calculates 54,534 MXN (2,614.84 USD).

I would like to calculate the SUM in MXN, since it is the currency for both the child and parent. Thank you for the advise

**Comment by timmy2cakes** [comment]
Please can someone help with this issue we are very stuck https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/733

**Comment by aheber** [comment]
@timmy2cakes and @raulramoso there are a few posts in the historical issues related to this. Probably best to start there and review the related issues, #284 

This is a known issue in how SOQL performs the value aggregation. There are some options but none of them have been added to this tool yet. Though there is an open MR to enable this in #591 I believe.

**Comment by afawcett** [comment]
@raulramoso i noticed another user got round this by creating a formula currency field on the child object and rolling that up.
