### ISSUE TITLE
Sum on Currency is wrong 

### ISSUE THREAD

**Issue by timteagueuk** [afawcett/declarative-lookup-rollup-summaries#733]
@afawcett  what can I do here as I believe this issue is messing up my roll up. Any advice is appreciated. Our corporate currency is GBP but we have opps in USD, EURO and dates exchange rates. Please see a better explanation here with screenshots 
https://success.salesforce.com/answers?id=9063A000000t1wx

**Comment by aheber** [comment]
@timmy2cakes there are a few posts in the historical issues related to this. Probably best to start there and review the related issues, #284 

This is a known issue in how SOQL performs the value aggregation. There are some options but none of them have been added to this tool yet. Though there is an open MR to enable this in #591 I believe.

In the future please avoid tagging your issue across unrelated issues. I understand the frustration of not feeling heard but this project doesn't have any full time support staff and we simply didn't get to it yet. On top of that it has been a long weekend in the US and other countries, many people are finally coming back online after some extended time away.

In reviewing your success community post it seems Christine Marshall already pointed you at the related issue. The answer is unfortunately the same, this is a known issue and we would like it fixed but we simply aren't there yet.
