### ISSUE TITLE
DLRS for KnowledgeArticles

### ISSUE THREAD

**Issue by Arunprakash1990** [afawcett/declarative-lookup-rollup-summaries#734]
Hi @afawcett ,

I am trying to create a roll-up between these two objects (Knowledge_Base__kav and KnowledgeArticleVersion) but it is throwing me an error (Error: Object does not exist). 

Can you please help me with this?

Thanks,
Arun Prakash

**Comment by VASTbeth** [comment]
Are you using the API name? I had that same error when I accidentally used the field name.

**Comment by afawcett** [comment]
I don't see Knowledge_Base__kav as a valid Salesforce object. Have you got the correct API name? We can re-open this to discuss further if needed.
