### ISSUE TITLE
UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 1 records

### ISSUE THREAD

**Issue by konradbeck** [afawcett/declarative-lookup-rollup-summaries#736]
I have a batch which updates records matching the criteria.

It seems the update of *Lookup Rollup Summary Schedule Item* is causing the issue

[ {
  "message" : "dlrs_Product_TransactionTrigger: execution of AfterUpdate\n\ncaused by: System.DmlException: Upsert failed. First exception on row 0; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 108 records: a0z9E0000037L1jQAE: []\n\nClass.dlrs.RollupService.updateMasterRollupsTrigger: line 1023, column 1\nClass.dlrs.RollupService.handleRollups: line 892, column 1\nClass.dlrs.RollupService.triggerHandler: line 329, column 1\nTrigger.dlrs_Product_TransactionTrigger: line 3, column 1",
  "errorCode" : "System.DmlException"
} ]

**Comment by aheber** [comment]
I'm not entirely sure what object that is that you're trying to lock but I would guess you're DLRS jobs are in scheduled mode and there are multiple transactions trying to add scheduled job entries to the database at the same time.

Is this happening via Apex Batch, Bulk API, some other mass-update system?

If your rollups are in scheduled mode, do you need them in scheduled mode or could you move them to real-time? That might avoid that particular error.

Is this a one-time update or something that is happening regularly? If one-time I would recommend you consider disabling the rollups for the update and run a full calculation later.

Hopefully that gives you a few options.

**Comment by konradbeck** [comment]
A batch process inserts multiple records which meet the scheduled rule criteria.

So it seems for each iteration of the batch, an update is made to the Lookup Rollup Summary Schedule Item which causes the lock.

Salesforce suggest using FOR UPDATE in the soql query, alternatively only querying the Lookup Rollup Summary Schedule Items which have children meeting the criteria could potentially resolve the issue?

**Comment by aheber** [comment]
@konradbeck is this a single transaction or are there multiple transactions running concurrently? (BulkAPI in parallel mode?)

**Comment by konradbeck** [comment]
Multiple transactions running concurrently

**Comment by aheber** [comment]
If you're running multiple concurrently it sounds like they are trying to write children to the Rollup definition which holds a Master-Detail relationship. This is due to your mode of `Scheduled` which is writing the Scheduled Items for a scheduled job to come back and process later.

I would recommend either not running concurrent transactions or changing your rollup setup to either be real-time (if you can afford the performance tax) or a full scheduled calculate.
https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups Scheduled Full Calculate

**Comment by afawcett** [comment]
@konradbeck i have nothing more to add to @aheber wonderful comments here. Let us know if you need more help and we can re-open.

**Comment by afawcett** [comment]
Actually leaving open to add something to the wiki on this topic, its comes up enough to warrent it.
