### ISSUE TITLE
Test coverage error in production but not developer org?

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#738]
I wanted to set up a DLRS rollup between Account and Contact using a value in a multi-select pick-list in the criteria.  I set this up in a developer org, deployed the trigger and activated the roll-up without a problem.
Replicating this in a production environment I am getting an error deploying the trigger:

Warning:  dlrs_ContactTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required.

What is the difference here and how can I work around the error?  I have attached images of the two roll-up configurations.  Thanks in advance.
[DLRS errors.docx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/2356670/DLRS.errors.docx)

**Comment by aheber** [comment]
@LawranceT how are you deploying the trigger? Using the Manage Child Trigger button?
Were there any other errors? It seems like your test code is missing or not compatible with your production org. Often times we'll see the automatic test coverage try and push a blank object that is rejected by the rules of the org. 

Let us know if there are any other failings of the deploy, you may need to check the Deployment Status screen to recover detailed errors.

**Comment by LawranceT** [comment]
Thanks for coming back to me @aheber .  Yes, I'm using the Manage Child Trigger button.  The error returned is "Warning:  dlrs_ContactTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required".  There is no additional detail on the screen or in the Deployment Status record.

**Comment by aheber** [comment]
Sounds like your test class isn't running, or somehow isn't firing the dlrs_ContactTrigger trigger. I'm not sure how that is possible if you'r allowing the package to deploy both the trigger and test class.

You said there is no other details in the deployment logs, can you verify both the trigger and the test class are included in the deployment job?

**Comment by LawranceT** [comment]
Sorry for the delay in responding @aheber , been travelling.  Not sure what the cause of the issue was but got the help of a developer colleague to help out and the issue was resolved.
