### ISSUE TITLE
Schedule Recurring Calculate Job with Master Object Where clause

### ISSUE THREAD

**Issue by athisachi** [afawcett/declarative-lookup-rollup-summaries#740]
Hi
Schedule Recurring Calculate Job with Master Object where clause. However after scheduled, I couldn't see any where clause on the scheduling page. How will I make sure where clause included in schedule? Also Other Administrator need to know where clause when I am not around.
Thanks in advance
athi

**Comment by aheber** [comment]
To my knowledge this isn't currently recorded anywhere in the app and isn't retrievable.

**Comment by athisachi** [comment]
thanks @aheber
