### ISSUE TITLE
DLRS Trigger not firing after 2.11 update

### ISSUE THREAD

**Issue by pkersh** [afawcett/declarative-lookup-rollup-summaries#741]
Previously we were getting an error with DLRS - https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/558#issuecomment-354684940

However now, after upgrading the managed package in our partial sandbox from 2.09 to 2.11, the trigger does not appear to be working at all.  

This issue originated when we were unable to add a file or attachment without getting an error. Now there is no error, but also no trigger. We want to get this working in our Partial before updating in Prod.

![capture 1a](https://user-images.githubusercontent.com/14239106/45308038-d2128000-b4dd-11e8-8b67-2656ae60b718.PNG)
![capture 1b](https://user-images.githubusercontent.com/14239106/45308045-d50d7080-b4dd-11e8-929b-388e19bae693.PNG)

**Comment by b2000** [comment]
I installed version 2.11 last night.  There are no formulas used in the rollup. The before and after update triggers fire when I update the record but the aggregate result field is not updated.  However, when I use the Calculate button the aggregate result field is updated.

Debug log from edit/save child record:
05:12:47.0 (380428)|CODE_UNIT_STARTED|[EXTERNAL]|TRIGGERS
05:12:47.0 (403345)|CODE_UNIT_STARTED|[EXTERNAL]|01qm0000000DO1K|dlrs_Leg_CrewTrigger on Leg_Crew trigger event BeforeUpdate|__sfdc_trigger/dlrs_Leg_CrewTrigger
05:12:47.0 (2331740)|SYSTEM_MODE_ENTER|false
05:12:47.0 (3748119)|CODE_UNIT_FINISHED|dlrs_Leg_CrewTrigger on Leg_Crew trigger event BeforeUpdate|__sfdc_trigger/dlrs_Leg_CrewTrigger
05:12:47.0 (41215673)|CODE_UNIT_STARTED|[EXTERNAL]|01qm0000000DO1K|dlrs_Leg_CrewTrigger on Leg_Crew trigger event AfterUpdate|__sfdc_trigger/dlrs_Leg_CrewTrigger
05:12:47.0 (41840663)|SYSTEM_MODE_ENTER|false
05:12:47.0 (56640014)|SOQL_EXECUTE_BEGIN|[164]|Aggregations:0|SELECT Name, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c, dlrs__UniqueName__c FROM dlrs__LookupRollupSummary__c WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY Name ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
05:12:47.0 (64664949)|SOQL_EXECUTE_END|[164]|Rows:0
05:12:47.0 (71444455)|SOQL_EXECUTE_BEGIN|[286]|Aggregations:0|SELECT DeveloperName, Id, Label, dlrs__Active__c, dlrs__AggregateAllRows__c, dlrs__AggregateOperation__c, dlrs__AggregateResultField__c, dlrs__CalculationMode__c, dlrs__CalculationSharingMode__c, dlrs__ChildObject__c, dlrs__ConcatenateDelimiter__c, dlrs__Description__c, dlrs__FieldToAggregate__c, dlrs__FieldToOrderBy__c, dlrs__ParentObject__c, dlrs__RelationshipCriteriaFields__c, dlrs__RelationshipCriteria__c, dlrs__RelationshipField__c, dlrs__RowLimit__c, dlrs__TestCodeSeeAllData__c, dlrs__TestCode__c FROM dlrs__LookupRollupSummary2__mdt WHERE CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true ORDER BY DeveloperName ASC NULLS FIRST , dlrs__ParentObject__c ASC NULLS FIRST , dlrs__RelationshipField__c ASC NULLS FIRST 
05:12:47.0 (76672101)|SOQL_EXECUTE_END|[286]|Rows:1
05:12:47.0 (93196718)|CODE_UNIT_FINISHED|dlrs_Leg_CrewTrigger on Leg_Crew trigger event AfterUpdate|__sfdc_trigger/dlrs_Leg_CrewTrigger
05:12:47.0 (93908628)|CODE_UNIT_STARTED|[EXTERNAL]|Workflow:01I36000002XJG0
05:12:47.0 (108370601)|WF_RULE_EVAL_BEGIN|Workflow
05:12:47.0 (108399951)|WF_CRITERIA_BEGIN|[Leg Crew Member: CM00383 a0Lm00000030JD1]|Set_Leg_Crew_Crew_Member_Account301m000000077oW|01Qm0000000E7yo|ON_ALL_CHANGES|0
05:12:47.0 (108509241)|WF_FORMULA|Formula:ENCODED:[treatNullAsNull]true|Values:
05:12:47.0 (108516411)|WF_CRITERIA_END|true
05:12:47.0 (109061413)|WF_SPOOL_ACTION_BEGIN|Workflow
05:12:47.0 (109105265)|WF_ACTION| Flow Trigger: 1;
05:12:47.0 (109111835)|WF_RULE_EVAL_END
05:12:47.0 (109740081)|WF_FLOW_ACTION_BEGIN|09Lm00000000chr
05:12:47.110 (110886997)|FLOW_CREATE_INTERVIEW_BEGIN|00Dm00000008oWh|300m00000004Zxb|301m000000077oW
05:12:47.110 (111501924)|FLOW_CREATE_INTERVIEW_END|160404d1f89eb5da4008cebf0f116667adb91f-5169|Set Leg Crew Crew Member Account
05:12:47.111 (111951480)|FLOW_START_INTERVIEWS_BEGIN|1
05:12:47.111 (111975431)|FLOW_START_INTERVIEW_BEGIN|160404d1f89eb5da4008cebf0f116667adb91f-5169|Set Leg Crew Crew Member Account
05:12:47.111 (126475205)|FLOW_START_INTERVIEW_END|160404d1f89eb5da4008cebf0f116667adb91f-5169|Set Leg Crew Crew Member Account
05:12:47.111 (126500011)|FLOW_START_INTERVIEWS_END|1
05:12:47.0 (127773890)|WF_FLOW_ACTION_END|09Lm00000000chr
05:12:47.0 (127872315)|WF_ACTIONS_END| Flow Trigger: 1;
05:12:47.0 (127883833)|CODE_UNIT_FINISHED|Workflow:01I36000002XJG0
05:12:47.0 (137990653)|CODE_UNIT_FINISHED|TRIGGERS

![image](https://user-images.githubusercontent.com/12448255/46869622-6aac6080-cdfa-11e8-9faa-6c852b51ac32.png)

**Comment by aheber** [comment]
@b2000 can you confirm what fields you are changing on the child record? It should update the parent record if the Crew_Member_Account__c, Leg_End_Date__c, or PIC_Proficiency_Check__c change.

**Comment by aheber** [comment]
@pkersh Can you confirm that you are changing either the amc__Billing_Event_Item__c or amc__Amount__c fields on the amc__Expense__c child object and it is not causing the amc__Amount__c field on the Billing Item to be updated?

**Comment by b2000** [comment]
You are correct. I just edited and saved the record without making changes to any fields not realizing the rollup actually looks at a change to the Relationship Criteria fields and Relationship fields. Updating any of those fields did result in the Aggregate Result Field updating. Thanks.

**Comment by afawcett** [comment]
@aheber  you rock!
