### ISSUE TITLE
About Upgrade to Version 2.11

### ISSUE THREAD

**Issue by athisachi** [afawcett/declarative-lookup-rollup-summaries#742]
Hello all,
I enabled 2 DLRS to active in scheduled mode and schedule apex class "RollupJob" nightly.
Scheduled item filling so quickly just for update of the child records even though changes are not related to rollup.

Example. Any changes in contact added to schedule item. DLRS just rollup when Parental Flag='True' on Contact. Schedule item holds contact even though parental flag='False'. Apparently, schedule items filled up fast though cleared on nightly. There are only 2000 contact with Parental Flag='True'. However 100k records inserted in schedule item before nightly. We don't want schedule item occupy storage unnecessarily at any point of time.

I saw there was an enhancement in 2.10 version 'Enhancement: Schedule calculate - don't DML update record if rollup value unchanged'.

We are in currently version 2.9. By upgrading to 2.11, **_whether scheduled item will reduce or DML will reduce ?_** as We don't want schedule item occupy storage unnecessarily at any point of time. .
Let me know
Thanks
Athi

**Comment by afawcett** [comment]
@athisachi i think i saw another issue where you concluded full recalc is best for your needs. So setting Mode = Process Builder (per the wiki on scheduling rollups) worked. Closing this, but let me know if you still want to chat more.
