### ISSUE TITLE
DLRS - can't deactivate; can't save

### ISSUE THREAD

**Issue by R0cket** [afawcett/declarative-lookup-rollup-summaries#744]
I'm wondering if I should uninstall DLRS in Salesforce.
It seems like I really screwed up all of my lookups.
I can't deactivate, I can't save, I can't edit my lookup fields on my contact field.
Can anybody tell me if the following message justifies my thinking? 

`Apex script unhandled trigger exception by user/organization: 005f2000008y2gu/00Df2000001Kv2H

dlrs_ContactTrigger: execution of AfterUpdate

caused by: System.QueryException: value of filter criterion for field 'Current_Grade__c' must be of type string and should be enclosed in quotes

Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1
Class.dlrs.LREngine.WithoutSharingQueryExecutor.query: line 680, column 1
Class.dlrs.LREngine.rollUp: line 238, column 1
Class.dlrs.LREngine.rollUp: line 117, column 1
Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1035, column 1
Class.dlrs.RollupService.handleRollups: line 892, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_ContactTrigger: line 7, column 1`

**Comment by aheber** [comment]
@R0cket could you add a screenshot of your rollup configuration? It sounds like the "Current_Grade__c" field in your relationship query field isn't assembled correctly. If it is the target of your rollup it might be a few other things.

**Comment by R0cket** [comment]
All fixed thank you aheber!
