### ISSUE TITLE
Too many SOQL Queries:201

### ISSUE THREAD

**Issue by emoran** [afawcett/declarative-lookup-rollup-summaries#745]
Hi, after create the configuration of the record, deploy the trigger and activate it,  we click on the "calculate" button, reviewing the Apex Job, we see "_Too many SOQL Queries:201_". We are aggregating around 2500 records.

![image](https://user-images.githubusercontent.com/1028534/45495085-87dd0900-b740-11e8-8d75-de940d573158.png)

**Comment by afawcett** [comment]
Try adjust the scope size via the Custom Settings for the tool. It is perhaps due to the fact other apex triggers on your parent object are doing queries or are perhaps not bulkified. Let me know if you still want to chat.
