### ISSUE TITLE
Roll-up on Parent: Lead/Contact Child: Task based on subject

### ISSUE THREAD

**Issue by sbasuk** [afawcett/declarative-lookup-rollup-summaries#746]
Hi,

I created a roll-up (see attached) and I'm getting the following error:

dlrs_TaskTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Who for Task Class.dlrs.RollupService.handleRollups: line 905, column 1 Class.dlrs.RollupService.triggerHandler: line 311, column 1 Trigger.dlrs_TaskTrigger: line 7, column 1

Any idea?

Thanks!
Samantha
![screen shot 2018-09-19 at 12 03 46 pm](https://user-images.githubusercontent.com/43416549/45765886-303d1280-bc04-11e8-9054-97902174dcf3.png)

**Comment by aheber** [comment]
I think you want WhoId and I think you may want Who.Type = ‘contact’ as an
additional Relationship Criteria.

I would also consider changing your field from Subject to Id if you’re
trying to count how many tasks exist.

**Comment by aheber** [comment]
Glad that got you going. Please mark the issue closed to clean it up.

**Comment by sbasuk** [comment]
Thank you!
