### ISSUE TITLE
Calculate Mode - Scheduled not querying all data records

### ISSUE THREAD

**Issue by mmaloney123** [afawcett/declarative-lookup-rollup-summaries#747]
I have several roll ups Real-Time from CPQ Subscription to the CPQ Contract. Then Scheduled Roll-ups should be Processing Contract Fields to the Parent Account record. The job is scheduled Hourly. Right now, we are seeing many records where the Account Roll up is not being Queued as part of the Hourly Process. What am I missing? 
Please Advise!

**Comment by aheber** [comment]
Is it possible your rollups from Contract to the Account aren't monitoring the correct fields to understand there was a meaningful change?

Are records being added to the LookupRollupSummaryScheduleItems__c custom object? Is it possible they are sitting there but your scheduled job isn't seeing them/or not running?

**Comment by afawcett** [comment]
@mmaloney123 makes a good point. Please check and let us know if it does not help and we can re-open. 👍
