### ISSUE TITLE
Error Deploying Apex Trigger and Apex Class 

### ISSUE THREAD

**Issue by jttrieu** [afawcett/declarative-lookup-rollup-summaries#750]
Getting this error when deploying DLRS for custom object:

 | Error:dlrs_BillingScheduleTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, BillingScheduleCalloutTrigger: execution of BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject Class.BillingScheduleInvoiceNSCalloutClass.setCurrency: line 191, column 1 Trigger.BillingScheduleCalloutTrigger: line 43, column 1: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_BillingScheduleTest.testTrigger: line 11, column 1
-- | --
	
Warning:
dlrs_BillingScheduleTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

![manage apex trigger error](https://user-images.githubusercontent.com/35822026/45910492-6de59b00-bdbe-11e8-8a70-68c0e76612af.jpg)

**Comment by jamiesbartlett** [comment]
I am receiving the same error.  Everything works in the sandbox but when in production, I cannot deploy my child trigger.  Looking forward to any feedback!

**Comment by aheber** [comment]
@jttrieu it looks like the auto-generated test class isn't creating enough data for the surrounding processes to complete. Either someone will have to develop some more complete test code (setting up the necessary supporting objects most likely) or the other code will have to be adapted to function when the supporting objects are empty.

**Comment by afawcett** [comment]
@jttrieu hopefully your sorted now. For future reference this wiki page has more info > https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage
