### ISSUE TITLE
Lookup Rollup Summary causing flow to error.

### ISSUE THREAD

**Issue by hholbrook** [afawcett/declarative-lookup-rollup-summaries#752]
We have a flow set up to create a custom object record off of a case as well as an account and contact record. The floe keeps erroring out so i went through doing a debug in the flow and got these results below...
"Error Occurred: This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_Retailer_Supplier_Associaa00Trigger: execution of AfterInsert caused by: dlrs.RollupServiceException: Lookup Rollup Summary 'AutoZone Associations' is invalid, your org configuration may have changed. Class.dlrs.RollupService.createLSFWrapper: line 1150, column 1 Class.dlrs.RollupService: line 1016, column 1 Class.dlrs.RollupService: line 950, column 1 Class.dlrs.RollupService: line 842, column 1 Class.dlrs.RollupService.triggerHandler: line 307, column 1 Trigger.dlrs_Retailer_Supplier_Associaa00Trigger: line 7, column 1. You can look up ExceptionCode values in the "

"AutoZone Associations" is a roll up created in the "Lookup Rollup Summaries" tab in our SF instance. Would anyone be able to direct me in how to resolve this error?

**Comment by aheber** [comment]
Could you post a screenshot of your configuration? If I had to guess I would think one of your field names no longer exists.

**Comment by hholbrook** [comment]
Do you mean screenshot of Flow inputs or the Lookup Record page?
Sorry i am not very familiar with this and inheriting our SF instance without documentation from past admins!

**Comment by hholbrook** [comment]
<img width="564" alt="new acct inputs" src="https://user-images.githubusercontent.com/44233108/47091783-2d294800-d1eb-11e8-9c19-c5959009bbb8.PNG">
<img width="729" alt="flow design" src="https://user-images.githubusercontent.com/44233108/47091784-2d294800-d1eb-11e8-8d11-21b68d316916.PNG">
<img width="759" alt="lookup record page" src="https://user-images.githubusercontent.com/44233108/47091786-2dc1de80-d1eb-11e8-9695-54aceebfa6d6.PNG">

Here attached is screenshots of the flow design, Inputs for creating new acct, and the Lookup record page!

**Comment by aheber** [comment]
Looks like you're using the Custom Metadata configuration for your Rollup but you've attached the copy from the custom object. Could you provide the other rollup configuration?

Thanks.

**Comment by hholbrook** [comment]
<img width="776" alt="rollup trigger" src="https://user-images.githubusercontent.com/44233108/47093556-1258d280-d1ef-11e8-86c6-464925940db0.PNG">

this is the trigger on the rollup object.

**Comment by aheber** [comment]
If you look at your available tabs there is one titled "Manage Lookup Rollup Summaries" (I think that is the name) That is the interface for the metadata management. From there you should be able to select your rollup via drop-down.

**Comment by hholbrook** [comment]
<img width="846" alt="manage page" src="https://user-images.githubusercontent.com/44233108/47098362-b2672980-d1f8-11e8-9003-5a833b2b9f68.PNG">
Ok got here! And i do see this highlighted field that i removed from the account object so this is probably what is causing the issue.  I "Undeleted" this account field but it seems to still give me the same error. We do not need this field anymore, and we actually don't even need the rollup anymore. Would deleting it entirely mess up other things or would that resolve the flow error?

**Comment by aheber** [comment]
Depending on how you've done it undeleting a field changes the API name, you'll need to adjust that on the field to get the rollup working again.

If you really don't need this rollup you can delete it. I would evaluate if you still need the trigger on the object or not, if you don't need the trigger then go ahead and remove it from your system before deleting the rollup.

**Comment by hholbrook** [comment]
Would it be the trigger on the rollup object that i need to delete first?

**Comment by aheber** [comment]
If you have no other rollups on this child object then you should be able to use the Manage Child Trigger button to delete the rollup.

**Comment by hholbrook** [comment]
When i clicked "Manage Child Trigger" i got the following error..

"Attempt to de-reference a null object 
An unexpected error has occurred. Your solution provider has been notified. (dlrs)"

**Comment by hholbrook** [comment]
nevermind that was because i wasn't on the manage Rollup tab! ok i clicked into the manage child trigger and i see the string of code. I am going to now remove this trigger then delete the rollup

**Comment by hholbrook** [comment]
Thank you SO much @aheber for all the help!! The flow is back to working properly!!!

**Comment by aheber** [comment]
Glad you were able to get everything working. I know I get a lot of grief when processes don't work.

If you get a chance can you mark this issue as closed? I don't have permissions to do it ;)
