### ISSUE TITLE
Apex CPU time limit exceeded - reduce records per batch job

### ISSUE THREAD

**Issue by yaminm** [afawcett/declarative-lookup-rollup-summaries#753]
Hello,
I getting this error while trying to calculate one of my DRLS fields in production.
Since I disable already all the things that I could disable for this job and still getting that error on some of the batch jobs I would like to ask if there is any configuration that we can customize for the number of records per batch.

I guess now it's 200 records per batch job and I would like to somehow reduce that.

Unfortunately, I couldn't find any solution for that in the documentation and it makes us big problems in production :(

Thanks in advance!

**Comment by aheber** [comment]
@yaminm were you able to get this resolved?

There are configuration options in the settings for the app that would allow you to change the batch size.

**Comment by afawcett** [comment]
@yaminm  let us know if you didn't find the Custom Setting to reduce the batch size. We can re-open and discuss further. 👍

**Comment by yaminm** [comment]
Sorry for the late response! found it and it's worked !
