### ISSUE TITLE
First error: dlrs:Too many query rows: 50001

### ISSUE THREAD

**Issue by ehebert7** [afawcett/declarative-lookup-rollup-summaries#755]
A little background, we have 100 or so custom rollups in our organization, and we are trying to consolidate into one scheduled job using the RollupJob class instead of scheduling each one individually, since we hit the scheduled apex job limit of 100. However we have been getting the error "First error: dlrs:Too many query rows: 50001". Thinking it was a query size issue, we incrementally disabled scheduled rollups and eventually realtime calculations down to 0, and we still get the same number of errors (7).

Is this an erroneous or expected error? Running the scheduled job with nothing to calculate should not give any query errors yet it continues to do so.

**Comment by aheber** [comment]
@ehebert7 are you still having trouble with this? Were you able to figure out where the errors were coming from?

**Comment by afawcett** [comment]
Closing due to lack of response. @ehebert7 we can for sure re-open anytime! 👍
