### ISSUE TITLE
Error: REQUIRED_FIELD_MISSING, Required fields are missing

### ISSUE THREAD

**Issue by leogarc** [afawcett/declarative-lookup-rollup-summaries#757]
Gettign the following error.  Any idea how to fix this?

Error:
dlrs_BMCServiceDesk_Incident_Chana2BTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, BMCServiceDesk.UpdateIncidentChangeLinkFields: execution of BeforeInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [BMCServiceDesk__FKIncident__c]: [BMCServiceDesk__FKIncident__c] Trigger.BMCServiceDesk.UpdateIncidentChangeLinkFields: line 35, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_BMCServiceDesk_Incident_Chana2BTest.testTrigger: line 11, column 1
![2018-10-25_20-02-30](https://user-images.githubusercontent.com/44484399/47536939-f14c4d80-d890-11e8-8e3c-a83d4e085e25.jpg)
![2018-10-25_20-02-01](https://user-images.githubusercontent.com/44484399/47536940-f14c4d80-d890-11e8-95ef-931e1b44bd68.jpg)

**Comment by aheber** [comment]
@leogarc were you able to get this fixed? Looks like you need to implement custom test code to get this working.

**Comment by leogarc** [comment]
Yes custom test code worked.

**Comment by afawcett** [comment]
https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage
