### ISSUE TITLE
missing LRS records in "Manage Lookup Rollup Summaries - Custom Metadata Pilot" view

### ISSUE THREAD

**Issue by erezerezg** [afawcett/declarative-lookup-rollup-summaries#760]
Title says it all: 
In the Manage Lookup Rollup Summaries - Custom Metadata Pilot while looking through the "Select Lookup Rollup Summary" select element, I couldn't find some of our existing DLRS records. I could only find them in the "Lookup Rollup Summaries" page

**Comment by aheber** [comment]
@erezerezg were you able to figure this out?
The system allows for two different sets of configuration. The older custom object and the new custom metadata style.

**Comment by afawcett** [comment]
@erezerezg let us know if the above didn't help, we can re-open. 👍
