### ISSUE TITLE
dlrs_OpportunityTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

### ISSUE THREAD

**Issue by jhoosemans** [afawcett/declarative-lookup-rollup-summaries#762]
I'm unable to deploy the Trigger for Opp. 

Error:
dlrs_OpportunityTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, noExchangeRate: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Trigger.noExchangeRate: line 9, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_OpportunityTest.testTrigger: line 11, column 1

**Comment by jhoosemans** [comment]
I've contacted the developer of the referenced noExchangeRate Trigger. As far as I understand it, I believe the Test Class should cover also for that Trigger?

**Comment by afawcett** [comment]
@jhoosemans no, not necessarily, the DLRS generated test classes are pretty basic, so may miss code paths in other triggers that get run at runtime. You can enhance the DLRS test code through this https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by afawcett** [comment]
@jhoosemans we can re-open if needed. 👍
