### ISSUE TITLE
Inconsistent Realtime execution of DLRS

### ISSUE THREAD

**Issue by ejk1477** [afawcett/declarative-lookup-rollup-summaries#764]
Hello - we've been using DLRS in scheduled mode for about a year now.  Great tool although it was incorrectly configured by a vendor at first.  Recently I took ownership of correcting those issues as well as optimizing its performance.  After correcting, scheduled mode works fine.  With close to 2MM (opportunity) records and some un-indexed fields in the criteria, each of the 20 or so scheduled runs could take from 4 to 8 hrs to complete which makes scheduling them take a week to complete one cycle.  It also updates LastModifiedDate on ~90% of the account and contact records in our org.  We'd like to use that field for logic in other processes.
My company is a not-for-profit.  We use the opportunity object for donations that have multiple recordtypes and stagenames. The Opty object has a relationship to account through the Accountid field.  There's a custom field for relationship to Contact.  Every time a donation comes in (or gets updated to meet certain criteria), I'd like to update (for ex) Lifetime Giving Amount to the sum of all the gifts in our org for that account/contact.  A screenshot example of this config is attached.
About 5 days ago, I killed all the scheduled jobs and inactivated their DLRS' and activated all the realtime versions.  There are about 9 of the realtime jobs with account as parent and opty as child.  Looking at the results of the last 5 days, the only dlrs that calculates consistently is the first one alphabetically (another screenshot attached) which might lead to believe that there's a timing issue?
I've been working with DLRS pretty consistently for the last 3 months and across multiple tweaks, just can't get this work.  Would appreciate any advice that could be provided.
Thanks!
Eric
![sampconfig](https://user-images.githubusercontent.com/12599228/49021427-95f7ce80-f160-11e8-81ee-187a14a729b6.GIF)
![dbresults](https://user-images.githubusercontent.com/12599228/49021435-998b5580-f160-11e8-8a98-1dcd35ced9e1.GIF)

**Comment by aheber** [comment]
@ejk1477 can you let us know what version of the tool you have installed? I've had several realtime updates on the same object in the past and not had the problems you're describing.

With regard to your scheduled jobs. Were you running a full calculate every week or were you using scheduled mode, which would queue specific records to be updated and defer processing of only those records?

**Comment by ejk1477** [comment]
Hey @aheber - thanks for the quick reply!  We are on 2.8.  Sorry, not sure what you mean by full calculate.  I used the 'Schedule Calculate' button in the dlrs GUI and set up 3 recurring Calculate runs a day on different lookup summaries.  This allowed me to run each lookup summary once across a week.
I've attached another screenshot of one of the dlrs.  Not knowing exactly what the fields represent, do they still look correct to you? 
![sampconfigii](https://user-images.githubusercontent.com/12599228/49023242-ce011080-f164-11e8-979f-b70584cabb1e.GIF)

**Comment by aheber** [comment]
@ejk1477 I think some of your problems might be resolved in the more recent versions. I don't see anything specific about some rollups failing depending on order but I might have missed where it was fixed. Either way would you be able to install the newest version into a sandbox and do some testing to see if it resolves your issue?

You might also be interested in this fix: https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/547

Lets give that a try and then at least we're troubleshooting on the latest version. Does that work for you?

**Comment by ejk1477** [comment]
Yes - it works for me and thanks again @aheber.  I've had the most recent version installed in Sandbox for a couple weeks now and there've been no issues so, moved it to prod.  The records that trigger dlrs come in piecemeal so, I had to wait for one to arrive and - it worked after the upgrade!  I'm going to wait to look at the results across the day and if it is consistent, I'll close the ticket
Like the #547 article.  Scheduled execution might be an alternative to realtime now.
Eric

**Comment by ejk1477** [comment]
Hi @aheber - Hope all's well.  If you recall your recommendation to upgrade.  It was done mid-day last Monday and at first looked promising.  We've had about 400 donations come thru the system since then and only 3 records have a full rollup set calculated.  3 of the 12 rollups calculate consistently (gif attached) but the rest generally don't at all.  I pulled the setup information out of the system to do a comparison of those that work against those that don't (xlsx attached) - can't see any common denominator.  Is there any way to debug this?  Could you recommend a different mode?  I seem to recall there is a near real-time mode for DLRS.  Could you point towards documentation?  Again - thanks!
Eric
[DLRSSetup.xlsx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/2629590/DLRSSetup.xlsx)
![rudb](https://user-images.githubusercontent.com/12599228/49229928-8e346600-f3bc-11e8-8055-0d7c689562c2.GIF)

**Comment by aheber** [comment]
@ejk1477 I missed this coming back in. Are you still having the few flaky configurations?

**Comment by ejk1477** [comment]
Hey @aheber

**Comment by ejk1477** [comment]
Thanks for following up. We’re working now. Don’t know if it’s possible but had both a scheduled version and real-time of the same rus when I went with realtime I inactivated the scheduled rus.  As soon as I reactivated scheduled, they started calcing again realtime
