### ISSUE TITLE
Issue with Child trigger

### ISSUE THREAD

**Issue by CarlMah** [afawcett/declarative-lookup-rollup-summaries#766]
Hi 
We are unable to deploy child trigger on an object because we have other apex code that insists that one of the fields is never BLANK or NULL.
I cannot remove that code, it is required, can you please advise how we can tweak the test class to account for this?

Thanks

**Comment by aheber** [comment]
@CarlMah it sounds like you need to create some custom test code for this trigger. You can do so at the bottom of the DLRS job definition. You should be able to insert a version of your custom object that meets the criteria. If you don't have the development experience you might need some help. To be clear, the text you enter is the *body* of the test method, not the entire class.

Let me know if that isn't clear enough.

**Comment by afawcett** [comment]
@CarlMah take a look at https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. Let us know if you need us to re-open this issue. We totally can. 👍
