### ISSUE TITLE
dlrs_OpportunityTrigger blocking insert/updates of Opportunities

### ISSUE THREAD

**Issue by chrisleavengood** [afawcett/declarative-lookup-rollup-summaries#768]
Errors when creating or updating an opportunity.

Error Message #1: "Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Account for Opportunity: (dlrs)"

Error Meesage #2: "Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field RecordType for Opportunity: (dlrs)"

Both of the "invalid" fields referenced are standard fields on the Opportunity object. Please make fixing this issue a priority as we cannot create a single opportunity record in our org right now.

Thanks!

**Comment by chrisleavengood** [comment]
Which part of the configuration would you like screenshots for? 

We've deactivated every Lookup Rollup Summary in our org and the problem persists, so I'm not sure what to document. Also, everything was working for us yesterday, but it looks like an update to the package was pushed to our org last night around 12:00 am CST. I'm not sure if that update could have caused anything to change.

**Comment by aheber** [comment]
I wasn't aware any updates had been pushed for the package. What version are you on?

If you could screenshot the configuration of any related rollups on the Opportunity that might be a good start. I'm not sure what would have changed in your system.

Is it possible for you to run a debug log for one of the transactions that is failing? Maybe pull the stack trace portion that is reporting all of the classes involved in the crash? (Might not work well depending on where it is in the managed package)

Nothing else in the org that could have changed in that window?

**Comment by DanDonin** [comment]
I didn't think the dlrs package was setup for auto pushing always manual
upgrades.

**Comment by chrisleavengood** [comment]
Yes, I mispoke on the automatic upgrade - that was for a separate package installed for a similar function. There are currently two Lookup Rollup Summaries on the Opportunity. I've attached screenshots of both.

And unfortunately, it's tough to pinpoint the error because we've had a large team deploying, loading data, etc. to get through our pre-deployment UAT phase. I'll follow-up with the rest of my team to see if any of them are aware of what else might have changed.

I appreciate you looking at the config to confirm nothing is causing issues there.

![opp - total properties](https://user-images.githubusercontent.com/45641115/49587097-38ae0b00-f920-11e8-9d6c-dc3225234b98.png)

![opp - total purchase amount](https://user-images.githubusercontent.com/45641115/49587103-3ba8fb80-f920-11e8-9e22-ac3eb5f0dbd3.png)

**Comment by chrisleavengood** [comment]
We got to the bottom of this one. Your initial assessment of referencing Account and RecordType instead of AccountId and RecordTypeId was spot on.

The challenge in finding which Rollup was causing this errror was due to my accessing the Lookup Rollup Summary tab directly instead of going to the "Manage Lookup Rollup Summaries tab". When accessing that tab directly, it was only my two rollup summaries that showed an association to the Opportunity object, however there was another that was scheduled to run (but showed inactive in the UI) that was actually still calculating. As soon as we updated those field references, everything started working again.

Thank you both for your help!

**Comment by aheber** [comment]
Awesome! Yeah DLRS can be a bit confusing wherein you can schedule through two different interfaces and into two different sets of rollups jobs.

Glad you got it taken care of.

**Comment by Dhruv9221** [comment]
Hey I have same problem but, not able to figure out which DLRS is causing this. 

As I am new to this tool, if any one can help me it would be great help!!
