### ISSUE TITLE
Question about Remote Site Setting and Gov Cloud Orgs

### ISSUE THREAD

**Issue by gracefang** [afawcett/declarative-lookup-rollup-summaries#769]
Hi Andrew and Friends, a quick question about the Remote Site Setting and whether I likely need to explain the usage of it by DLRS when installing in a Gov Cloud org. I'm in the process of confirming the IT approval process for managed packages. Any description of how DLRS uses the Remote Site Setting (e.g., metadata API access only?, no org data sent?, what about the org id / domain?) would be helpful and most appreciated. Thank you!

**Comment by aheber** [comment]
The Remote Site setting that DLRS installs is to enable DLRS to make remote calls into the same org to execute metadata deployments. It is through this use of the Metadata API that DLRS can create triggers on objects that have realtime and scheduled rollups configured.
