### ISSUE TITLE
DLRS not loading in Spring 19' Sandbox

### ISSUE THREAD

**Issue by GiancarloBM** [afawcett/declarative-lookup-rollup-summaries#775]
Hi All

So one of our clients has been testing DLRS solutions in their sandbox for some time without issues, but since Spring '19 was pushed to the sandbox, whenever they click on the Welcome or Manage Lookup Rollup Summaries nothing happens. The main body of the page goes blank like it is about to load something, but it just stays that way.

Has anyone else encountered this?

Thanks in advance for all your help.

**Comment by aheber** [comment]
@GiancarloBM, I haven't been able to test in Sprint '19 but can you give it another try? This could have been a short term bug that has been resolved as I've had a few of those this week.

**Comment by afawcett** [comment]
@GiancarloBM let us know if this is still an issue we can re-open.
