### ISSUE TITLE
Contact task rollup is not letting users save changes without refreshing

### ISSUE THREAD

**Issue by mwrayjr** [afawcett/declarative-lookup-rollup-summaries#779]
I have users reporting a pretty common issue, although I can't reproduce it yet.  They tell me they are logging a call using the Lightning sidebar for recording a call activity.  This then triggers the task rollup to update the Contact's Last Contacted Date.

If they click the Edit screen on the contact to update additional notes immediately after logging the call, they get an error that they need to reload the page because the Rollup user (Bill M.) has modified the record.

This rollup is running in Realtime.  Would it possibly help if I put a row limit of 1 on this if all I need is the max record?

**Comment by aheber** [comment]
@mwrayjr the realtime rollups shouldn't be running as Bill M., that would only come into play if you have scheduled calculations.

Do you have any other kind of processing that might be done by this user?

This may be hard to troubleshoot if it isn't happening regularly but my expectation is that DLRS would happen much more consistently. Do you have any integrations or periodic processing happening under that username that could also be contributing to record updates?

**Comment by afawcett** [comment]
@mwrayjr per @aheber we kinda need some more intel on this to progress. If you have some and want to talk more we can for sure re-open this issue. 👍
