### ISSUE TITLE
Concatenate Text Fields

### ISSUE THREAD

**Issue by daveerickson** [afawcett/declarative-lookup-rollup-summaries#78]
I would like to be able to rollup text fields. It would be helpful to be able to choose the delimiter as well, such as a punctuation value or newline.

**Comment by wes1278** [comment]
Is this a duplicate of issue #76? 
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/76 Can we close this and track there instead?

Thanks

**Comment by daveerickson** [comment]
Yes, I think this qualifies as a duplicate of #76 .
