### ISSUE TITLE
SUM is wrong and 7% of a value are missing

### ISSUE THREAD

**Issue by CSchulenburg** [afawcett/declarative-lookup-rollup-summaries#780]
At a SUM (PreCalcSellingSalesGrossTEST__c / Currency(16, 2)) of all projects in 2019 with a special product to this product object (Forecast_Actual_Projects_2019__c / Currency(16, 2)) I lost 7% of the field value..

The DLRS is working but I get different values at the product. 

It could not be an currency issue (both objects are USD), no errors at the logs, permissions are fine, no field update with this fields, not related triggers, "Aggregate All Rows" is unchecked...

Any ideas?
![sum](https://user-images.githubusercontent.com/46805601/51366617-d3d0fd80-1ae6-11e9-89f9-975597467dc2.PNG)

**Comment by Tara-CK** [comment]
Following.  I'm having a similar issue.  

I have several records with related opportunities and have a field that I'd like to aggregate, but it is not summing anything at all...and it is showing no errors when I calculate.  Hopefully Someone has a fix for you and I can steal the solution.

**Comment by Tara-CK** [comment]
Hi there,  I just fixed a similar issue in my system.  My issue was that I needed to configure the remote site settings.  This might have nothing to do with your issue...I'm a new user and don't know much yet. 
 But in case it helps here's a link: https://help.salesforce.com/articleView?id=configuring_remoteproxy.htm&type=5

**Comment by CSchulenburg** [comment]
Issues was only at one projekt. Cloned this project and with the copy it does not happened. Exported both projects and all fields have the same value (without creation field etc.). No idea where the problem came from and hope it will not come again...

Thanks
