### ISSUE TITLE
Convert Active DLRS to Custom metadata via Custom metadata loader

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#781]
I want to convert the active existing DLRS records to Custom metadata via Custom metadata loader.
Since the field Calculate Job id is absent on Custom metadata DLRS so the migration tool throws the error 
"Webservices returned with Soap Fault: Field dlrs_CalculateJobId__c does not exist on entity dlrs__lookupRollupSummary2"

**Comment by aheber** [comment]
@Shraddha-Ingale the Custom Metadata doesn't hold that value. I'm not familiar with the Custom Metadata Loader but is it possible to exclude the value?

I don't think this is something that we can help with from an application perspective as this seems to be a problem with the specific loader you are using.

**Comment by Shraddha-Ingale** [comment]
@thanks for your support @aheber 
We have a requirement to convert the Active Real-time and scheduled DLRS records to Custom Metadata DLRS. Is there any other way that we can migrate the DLRS? Avoiding maximum manual work. 
I tried with the Custom metadata loader but failed to achieve the purpose.

**Comment by aheber** [comment]
@Shraddha-Ingale how many are you talking about?

Is it simply possible to modify the load file before feeding to the Custom Metadata Loader?

**Comment by afawcett** [comment]
@Shraddha-Ingale indeed, per @aheber that field is not needed in the Custom Metadata version of DLRS, so you are safe to drop it from your import file. 👍
