### ISSUE TITLE
Attempt to de-reference a null object: [BillingCountry]

### ISSUE THREAD

**Issue by dosmakov** [afawcett/declarative-lookup-rollup-summaries#782]
Hello -

Using installed package ver 2.11.

Can you help me to investigate the root cause? The error is not informative.

`dlrs_OpportunityTrigger: execution of AfterUpdate

caused by: System.DmlException: Update failed. First exception on row 0 with id 0015000000T3niaAAB; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.DmlException: Update failed. First exception on row 0 with id 0015000001Qa4NnAAJ; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Attempt to de-reference a null object: [BillingCountry]

(dlrs)

: []

(dlrs)

Trigger.dlrs_OpportunityTrigger: line 7, column 1`

**Comment by aheber** [comment]
@dosmakov can you post a picture of your rollup configuration that is driving this error?

**Comment by dosmakov** [comment]
@aheber seems like i found the root cause - it was a bug in one of our custom trigger. I have fixed it. We can close the issue, but i think the main problem with the error message is that it is not informative as it doesn't show trace log of the code execution. As result, you do not know the exact line of code that throw an error. It could be a limitation of the managed package installation.

**Comment by aheber** [comment]
@dosmakov I'll poke around and see if I can figure out where the error was lost. Glad you got it fixed and maybe we can quickly improve the tool for all else.

**Comment by dosmakov** [comment]
@aheber thanks! looking for make the tool better.

**Comment by afawcett** [comment]
@aheber let me know if your poking around found anything re: why the error got dropped, we can re-open if so. 👍
