### ISSUE TITLE
Trying to get latest date of tasks

### ISSUE THREAD

**Issue by mpun-scimarketview** [afawcett/declarative-lookup-rollup-summaries#784]
Hi,

 I am trying to find the "last activity date" of tasks associated with a case. I tried the Due date field (ActivityDate) and the Last Modified Date (LastModifiedDate). I am getting different errors with both. See error messages below.. I thought this would be a fairly common use case. According to documentation, the operator MAX is supposed to work on date fields... so not sure what the problem is.
```

 ActivityDate
 System.QueryException: field ActivityDate does not support aggregate operator MAX: Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1
 
 
 LastModifiedDate
 System.SObjectException: Illegal assignment from Datetime to Date: Class.dlrs.LREngine.rollUp: line 263, column 1


```

**Comment by cumulus-robert** [comment]
Try using the 'last' option instead of MAX. Make sure field on Case is date. Activity Date is date field, not date time field.

**Comment by afawcett** [comment]
@mpun-scimarketview let us know if @cumulus-robert answer did not help and we can re-open.
