### ISSUE TITLE
Calculate 200 Schedule jobs 

### ISSUE THREAD

**Issue by rui-mcl** [afawcett/declarative-lookup-rollup-summaries#785]
Hello everyone, i need to have around 200 fields be calculated every day overnight, and right now the approach was to use calculation mode "Schedule" but that goes over the 100 Apex jobs limit, anyway i can have all the rollups in a single Apex job? or even split them up into 20-30 chunks. I've created a button that calls the "runJobToCalculate" method multiple times with a bunch of id's from the "dlrs__LookupRollupSummary2__mdt" custom metadata but not a single one goes through. Any ideas? 

Appreciate all the help.

**Comment by afawcett** [comment]
@rui-mcl is there any reason why you need to do full recalc and not incremental? If you use incremental you only need one job. See https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. We can re-open this issue if you want to discuss more. 👍
