### ISSUE TITLE
Multiple values in the 'Relationship Field' are ignored; Only the first value gets the roll up information

### ISSUE THREAD

**Issue by SharkySharj** [afawcett/declarative-lookup-rollup-summaries#787]
Hey all,

I'm having an issue when I'm trying to roll up details from a task to multiple connected contacts (the task has more than one contacts in the 'WhoId' field). DLRS only rolls up the information to the first associated contact and ignores the remaining contacts. 

Any fixes or am I better suited off to writing a trigger for this?

Any help is appreciated! Thank you!

**Comment by aheber** [comment]
@SharkySharj unfortunately, as mentioned here https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p&fId=0D53A0000493lGu&s1oid=00D300000000iTz&OpenCommentForEdit=1&emkind=chatterPostNotification&s1nid=0DB30000000072L&emtm=1548860240692&s1uid=0053000000BKvJM&fromEmail=1&s1ext=0

DLRS doesn't understand how these items come together. You would need to get multiple DLRS jobs to roll up from the EventRelation object (possibly as a full scheduled calculation) up to the Task then from the Task you could push up to the parent. As seen in the ERD here: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_erd_activities.htm

DLRS doesn't really bring an understanding of the Salesforce data model, things like how multiple Contacts are linked to a single Task. DLRS expects users to be able to know what the data model looks like and assemble single or multiple jobs that can work together to achieve what is needed.

**Comment by SharkySharj** [comment]
@aheber Thank you for your response.
Yes, I think it's fair enough that DLRS does not do that automatically for us as this relation comprises of a junction object and that makes the job a bit more complex. Took me a while to realize this. Appreciate your comment to help me better understand this concept.
