### ISSUE TITLE
Cannot see Lookup Rollup Summary Custom Metadata Type to add to change

### ISSUE THREAD

**Issue by corbettnco** [afawcett/declarative-lookup-rollup-summaries#789]
When I go to Setup > Platform Tools > Custom Code > Custom Metadata Types, I see Lookup Rollup Summary installed by the installed package Declarative Lookup Rollup Summaries Tool.

However, when I try find this component to add it to my Change Set, it is not listed.  Other Custom Metadata Types are listed but not LRS.  I can also see all of the DLRS Apex Triggers, Apex Classes, Custom Fields.

Is there something I'm missing when it comes to migrating DLRS config using change sets?

![image](https://user-images.githubusercontent.com/16656164/52314069-cb414980-2965-11e9-818d-1422097e5872.png)

**Comment by jmings** [comment]
I've run into the same issue. Would love some help!

**Comment by cumulus-robert** [comment]
FYI, CustomMetadata entries only show up in Change Sets for non-managed packages. Change your changeset option to this instead:
![2019-02-12_11-45-52](https://user-images.githubusercontent.com/8163365/52663586-d4796b80-2ebb-11e9-9dc5-27a8b07a1c41.png)

**Comment by corbettnco** [comment]
> FYI, CustomMetadata entries only show up in Change Sets for non-managed packages. Change your changeset option to this instead:
> ![2019-02-12_11-45-52](https://user-images.githubusercontent.com/8163365/52663586-d4796b80-2ebb-11e9-9dc5-27a8b07a1c41.png)

So , I was missing something. :-)  Found it.  This makes perfect sense now.  Thank you @cumulus-robert !!
