### ISSUE TITLE
Filter by last create date

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#79]
I want to only rollup a record that was created last. I tried putting CreatedDate:LAST in the Relationship Criteria field but it doesn't work. Is what I am trying to do possible with this tool? Thank you!

**Comment by wes1278** [comment]
I agree, this is something that would be amazing. I've wanted to think through this. However, it would almost assuredly need to be a separate method that does not use LREngine.

I would want to have the ability to rollup a singular value based on the value of a different field in general, not just date field restrictions.

So like, I want to rollup a currency field for the first, or last record that was created.
I would also want to rollup a text field value (or a concatenation) for the first (or all) record/s that met a certain criteria.

etc...

**Comment by ndeanw** [comment]
Another request for this, if possible! Rolling up only from the most recent record would be hugely helpful.

**Comment by afawcett** [comment]
This will be covered in the next release, which i happen to be working on right at this moment! :+1: 

Watch this space!

**Comment by afawcett** [comment]
Added in version 1.18, see README for more.
