### ISSUE TITLE
Standard buttons have disappeared for new DLRS jobs

### ISSUE THREAD

**Issue by ashlynnrs** [afawcett/declarative-lookup-rollup-summaries#790]
While attempting to build a new rollup today, I see that the "Manage Child Trigger" and all other standard buttons excepting "Save" are missing when I select "create new" from the dropdown menu of the Manage Lookup Rollup Summaries tab. I have confirmed that they are present on the page layout, and they can be seen when I select an existing rollup to edit. Of course, I am unable to save any new rollups without using the manage child trigger button. 

This is a real headscratcher. It's been a while since I've built a new rollup, but I haven't changed anything about the app configuration. Thanks for any light you can shed.

My only page layout:
![dlrs my only page layout](https://user-images.githubusercontent.com/38735013/52430779-db2b6b80-2ad4-11e9-94ce-4e9562aeaf14.PNG)

What I see when I select "New" from the dropdown:
![dlrs missing buttons](https://user-images.githubusercontent.com/38735013/52430703-b20adb00-2ad4-11e9-9a94-b9fe6a58995a.PNG)

**Comment by cumulus-robert** [comment]
I believe with current version, those buttons don't appear until you've successfully created at least one DLRS. You have to also be on a view page and not an edit page.
![2019-02-13_11-11-14](https://user-images.githubusercontent.com/8163365/52737049-3e5b4900-2f80-11e9-825c-67b9ba8a67bf.png)

**Comment by ashlynnrs** [comment]
Thanks. I had multiple rollups already created and activated, so I don't think that was the issue. And today I have successfully created and saved a test rollup, so I'm still not sure what was stopping me last time, but the issue is resolved. And you were right, once I hit 'save', the other buttons appeared. Thanks @cumulus-robert .

**Comment by afawcett** [comment]
@cumulus-robert thank you sir! 👍

**Comment by martyychang** [comment]
I had a similar issue with `dlrs` 2.12 when trying to create my _first_ rollup summary. The error below was printed.

> Active: Apex Trigger dlrs_ContactTrigger has not been deployed. Click Manage Child Trigger and try again.

However, there is no **Manage Child Trigger** button on the page. What I discovered was that clearing the **Active** checkbox allowed me to save the rollup summary, at which point the **Manage Child Trigger** appeared.
