### ISSUE TITLE
Concatenation Operation not working properly on update of child record

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#791]
Hi,
I have the RealTime DLRS which concatenates text field of the child on parent record. but if I change a child record, the text rollup doesn't flow to the parent object unless I manually run the Calculate Job again.
Is this the known issue of concatenation operation? 
If yes can anyone please suggest a solution for this.

**Comment by cumulus-robert** [comment]
Hard to tell without more details. It would be helpful if you provide a screenshot of the current configuration.

**Comment by aheber** [comment]
What kind of field is the text field you're concatenating? Does it or another field need to be added to the Relationship Criteria Fields list?

Is it by chance a formula field?

**Comment by afawcett** [comment]
@Shraddha-Ingale let us know if you want to keep discussing. We can for sure re-open this issue. 👍
