### ISSUE TITLE
Not working with valid data

### ISSUE THREAD

**Issue by chrishickman81** [afawcett/declarative-lookup-rollup-summaries#793]
I created a record that sums a currency field Total_Price__c on ContractLineItem (mirrors the native field but is available for rollup summaries/etc.) to a field TCV_2__c on ServiceContract through the ServiceContract lookup. When I try to calculate, it indicates my lookup is invalid, but that is in fact the native lookup on the native object from Contract Line Item to Service Contract.

![lrs1](https://user-images.githubusercontent.com/8466012/52903637-035a4f00-31e6-11e9-981b-70145916f267.PNG)

![lrs2](https://user-images.githubusercontent.com/8466012/52903638-09e8c680-31e6-11e9-8d6d-57d6ed390281.PNG)

I'm using the latest managed package for DLRS in a Developer Edition org, in classic UX. Does not matter if I use system or user sharing, and no DLRS logs are generated.

**Comment by aheber** [comment]
@chrishickman81 from what I can see you might have at least one problem. Your Relationship Field value is `ServiceContract` when I think it should be `ServiceContractId` (https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contractlineitem.htm)

**Comment by afawcett** [comment]
@chrishickman81 i am pretty sure @aheber suggestion above will help resolve your issue. Let us know if not and we can re-open. 👍
