### ISSUE TITLE
Tool shows up "job running" error when org is short on storage.

### ISSUE THREAD

**Issue by renatoliveira** [afawcett/declarative-lookup-rollup-summaries#794]
This looks similar to #498 but if the organization has no space for records, the calculate job will fail with the wrong message due to the lack of storage.

https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/6571ab183e32d9c3faeb6b10d1fa685d47d485bd/force-app/main/classes/RollupService.cls#L634

Right below this line, in the catch statement, we could check for the available exceptions that the platform throws, and catch the DMLException and handle the system-signed StatusCode for ```STORAGE_LIMIT_EXCEEDED```, and maybe others as well.

**Comment by aheber** [comment]
@renatoliveira thanks for digging into this. Looks like you found a good one that would be ripe for submitting a merge request. Care to take a crack at it?

**Comment by renatoliveira** [comment]
I'll work on this later today and submit a MR then.
