### ISSUE TITLE
Spurious results in record count

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#798]
I have set up a set of nine Lookup Rollup Summaries with the same parent (Contact) and child (Download Records) object.  Each Download Record is linked to one of nine Sector records and has a date.  On the Contact record I have a numeric field for each of the Sectors.  The idea is to maintain a record at the Contact level of the number of downloads of each Sector that a Contact has made over the past 24 months.  The Lookup Rollup Summaries are the same with the exception of the Sector ID and the numeric results field.  

The problem is that the record count returned by the Lookup Rollup Summaries is incorrect and I can see no pattern as to why the numbers are not adding correctly.  Has anyone got any ideas on this?
![clrs](https://user-images.githubusercontent.com/34403841/53148915-15503f00-35a4-11e9-86bd-9d8fa88405d6.PNG)

**Comment by LawranceT** [comment]
I have found a solution to this but am leaving the issue open to see if anyone can give an explanation:

I resolved the issue by changing the relative date filter from LAST_N_Months:24 to LAST_N_DAYS:730
Does anyone know why this worked?

**Comment by aheber** [comment]
@LawranceT, unfortunately without seeing some of the sample records that are and are not being included I am not much help. This does sound like a problem in the generated SOQL query so you should be able to troubleshoot and review without too much trouble outside of DLRS. You should also be able to get a report built that does the same thing and compare numbers.

If you can find that you SOQL queries are working as expected and DLRS is still not working correctly please let me know and with the specific examples we can try and figure it out.

To confirm, LAST_N_MONTHS and LAST_N_DAYS include different periods. LAST_N_MONTHS starts on the last day of the previous month and then goes back through 24 months. So if I ran that SOQL right now it would include from Jan 31st 2019 back through Feb 1st 2017. LAST_N_DAYS being a little different would include Feb 20th 2019 back through Feb 20st 2017.
I would assume you're comparing this to some other output for validity, do you expect its filters align more closely to the Months or Days?

Depending on how frequently these Download Records are created you might find that your data becomes stale and old rather quickly. Filter on relative dates can become complicated. If you haven't already you may want to think about performing a full recalculation on some periodic basis that makes sense for when things roll off your data set in additional to the realtime rollup.

The other thing I would ask, are you sure you want to aggregate by Name? Normally we recommend aggregating by Id when counting the number of children records. Depending on your type of name field it might be equally unique or you might be intending to count only unique names. Just thought I would call it out as that can easily be the cause of unexpected numbers. Likely not as changing your date range seems to have provided the expected values.

For your current rollup you should be able to run a query very similar to 
`SELECT Contact__c, COUNT(NAME) from Download_Record__c WHERE Sector__c = 'a1Z1v000003vXfzEAE' AND Date__c = LAST_N_MONTHS:24 GROUP BY Contact__c`
(Likely adding an additional WHERE clause element to limit it to your test Contact Id)
Then compare that to 
`SELECT Contact__c, COUNT(NAME) from Download_Record__c WHERE Sector__c = 'a1Z1v000003vXfzEAE' AND Date__c = LAST_N_DAYS:730 GROUP BY Contact__c`

**Comment by LawranceT** [comment]
Hi

Many thanks for this, you have identified the problem - several of the
records that I expected and wanted included in the result were dated this
month and so were being excluded from the roll-up when using LAST_N_MONTHS,
but were included with LAST_N_DAYS.

Thanks for taking the time to help.

Best wishes

Lawrance
____________________
Lawrance Titterton
NGO Business Services
Skype: lawrance.titterton.caf
+44 7974 073 736 UK
+256  775 139 340 Uganda

**Comment by LawranceT** [comment]
@afawcett  Many thanks for this, you have identified the problem - several of the records that I expected and wanted included in the result were dated this month and so were being excluded from the roll-up when using LAST_N_MONTHS, but were included with LAST_N_DAYS.

Many thanks as always for the support and a great product

**Comment by LawranceT** [comment]
PS - The name in this instance is an auto-number, so is unique.
