### ISSUE TITLE
Rollups not showing updated value

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#800]
I have DLRS with following Relationship Criteria :

![image](https://user-images.githubusercontent.com/35553420/54120871-e4cf2880-441e-11e9-8851-3f1fd7d5b5aa.png)

It is not calculating on update of child record, I have to calculate it manually.
As I thought I am facing this issue because of Parent_Program__r.Name = 'CRS' condition.
I have modified criteria as :

![image](https://user-images.githubusercontent.com/35553420/54121020-5b6c2600-441f-11e9-8de1-44beea27fc22.png)

But still I am not getting the updated values in Aggregate Result Field.
am I missing something? Can someone please help me with this?

**Comment by aheber** [comment]
@Shraddha-Ingale thank you for including a screen shot. What specific change are you making your the child records that you're expecting to roll up? Which fields are you modifying?

The filter on the Parent_Program__r.Name should be fine as long as you aren't depending on a change on the parent record to fire a trigger on the child. If there is a relevant change on the child record then the filter will still be used to calculate the value to save to the Village__c record.

The way you have these two configured it should recalculate the value when any of the following fields change value
Male: Total_Male_Clients__c, Village__c, IsDeleted, Parent_Program__c, Program_End_Date__c
Female: Total_Female_Clients__c, Village__c, IsDeleted, Parent_Program__c, Program_End_Date__c

**Comment by Shraddha-Ingale** [comment]
Thanks @aheber 

Yes, it should recalculate, But it is not even if the value of Total_Male_Clients__c and Total_Female_Clients__c changes.
Do you have any idea what could be the issue?

**Comment by aheber** [comment]
I'm going on the assumption that to move this to Active you deployed the triggers. Can you confirm? Maybe even going as far as remove then deploy again?

**Comment by Shraddha-Ingale** [comment]
@aheber 

Tried the same but issue not yet resolved, Observed one more strange behavior with this DLRS.
After Deleting child record I am getting updated value on Village.

**Comment by Shraddha-Ingale** [comment]
Hello, Any other way that I could try?

**Comment by aheber** [comment]
@Shraddha-Ingale I'm not sure why this is happening. The best thing I can offer is to get on screen sharing with you and see it in action, or have you set this up in a sandbox and give me a user that I can login with and review. Let me know if you would like to coordinate that with me. (I'm not able to use the support login features)

**Comment by Shraddha-Ingale** [comment]
Thank you for your support. We should get on a call on this week.
I would prefer friday in between 9AM to 2 PM GMT. Let me know your availability.
Thanks.

**Comment by aheber** [comment]
@Shraddha-Ingale I've been away from my computer most of the week.

Happy to try and make it work after Monday next week.

**Comment by Shraddha-Ingale** [comment]
Hi @aheber 

Can we have a call tomorrow in between same time 9AM to 2 PM GMT? Let me know your availability.
Thanks.

**Comment by afawcett** [comment]
@Shraddha-Ingale do you still want to chat about this?
