### ISSUE TITLE
Groups of rollups stopped working, large number of scheduled jobs

### ISSUE THREAD

**Issue by sethgolub** [afawcett/declarative-lookup-rollup-summaries#801]
I'm so confused...
I have a set of rollups defined, using the same child triggers, and created these when I was an active user/consultant for an organization.  These were working for a long time.

My user account was deactivitated. Half of the triggers seemed to stop working - firing only after child records were deleted or modified, and inconsistently.  There was a large backlog of scheduled items, even though execution was set to realtime.

I have tried creating new rollups with new fields and same structure using the sys admin ID (they allowed me access). But no luck.  Still inconsistent behavior.  New ID has the permission sets.

Based on another post, I removed the child trigger, then reinstalled it.  Now, none of the rollup summaries are working.

Any suggestions?

**Comment by aheber** [comment]
@sethgolub I've not seen this before. I wonder if something about things being owned/created by your old inactive user is causing problems. I assume no users are getting error messages at this point. Could you check the Apex Jobs in setup to see if anything is running in error?

Do you have any Scheduled Apex jobs that are tied to the old user?

For next steps I would probably have Developer Console open and do what I thought should trigger the rollup, review the logs if you're familiar with how to do that and see if you can see the records being processed.

**Comment by sethgolub** [comment]
Hi Andrew,

I unfortunately am not very savvy technically.  Is there a way to identify and clear out all of the unrun APEX jobs, and then re-run.  The behavior is odd and unpredictable.  For example: when I create a new record, some of the rollups seem to run, but not others (all part of the same trigger).  When I delete the record, the ones that were not filled in suddenly appear with the values from the deleted record.  I removed and redeployed the trigger from the new ID, but now, nothing works.  The new ID is an admin, with permission sets for configuration and running.

 

Any inisghts appreciated.  Or, if you can tell me what to ask Salesforce support, I can do this as well.

 

Thanks,

Seth

**Comment by afawcett** [comment]
There is an enhancement issue listed to improve awareness of scheduled jobs that will help (at least in part) with this in the future .
