### ISSUE TITLE
Manage Lookup Rollup Summaries Edit Issue

### ISSUE THREAD

**Issue by ddatawitch** [afawcett/declarative-lookup-rollup-summaries#805]
When in lightning experience, when an existing summary is selected, the page does not change from adding a new rollup to editing an existing rollup.

**Comment by afawcett** [comment]
@ddatawitch i was not able to reproduce this just now. Are you still able to?

**Comment by afawcett** [comment]
@ddatawitch we can re-open this if you want to continue to discuss. Thanks.
