### ISSUE TITLE
Receive Test Coverage Error in Production Only 

### ISSUE THREAD

**Issue by amypurdy** [afawcett/declarative-lookup-rollup-summaries#807]
I received an Test coverage error in production but not in Sandbox. We used the Manage Child Trigger, and received this error message: 

  | Error:dlrs_AdvisingTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, Advising: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Class.AdvisingTriggerHandler.SetAffiliation: line 79, column 1 Trigger.Advising: line 8, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_AdvisingTest.testTrigger: line 11, column 1
-- | --

  | Warning:dlrs_AdvisingTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required
-- | --
 

We only received this error when the Child Object is the Advising Object. We are able to successfully deploy all DLRS Rollups on all other child objects.

Please advise how to fix this in production.
My email is amypurdy@docs.rutgers.edu

![Contact Error Child Trigger Deploy DLRS Capture](https://user-images.githubusercontent.com/43614326/55111732-6d052d00-50b1-11e9-8c63-b79a746f734e.PNG)
![Affiliation - Number of Advising Records-  DLRS Field Error](https://user-images.githubusercontent.com/43614326/55111743-71c9e100-50b1-11e9-8669-7f57d5580c09.PNG)

**Comment by afawcett** [comment]
So the DLRS generated test code causes other triggers to run. In your sandbox its likely those other triggers behave differently based on the presence or lack of, data in the objects. Which will likely cause this type of issue. Its hard to debug, but if you can reproduce it, its likely then down to lack of sophistication in the generated DLRS test trigger code that satisfies whatever field value requirement the code at Class.AdvisingTriggerHandler.SetAffiliation: line 79 has. Take a look at this for more intel and background > https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by afawcett** [comment]
@amypurdy we can re-open this issue if you want to keep chatting, but its really something your developer of the AdvisingTriggerHandler.SetAffiliation: line 79  needs to consult with you on. Show them the generated DLRS test code and they can propably teach it some new tricks to insert a dummy parent or related record (depending on what their code needs). Hope this helps! 👍
