### ISSUE TITLE
Error with Accounting Seed Object

### ISSUE THREAD

**Issue by bmason33** [afawcett/declarative-lookup-rollup-summaries#808]
Getting this Error when I try to Deploy the code on the child object:

Error:dlrs_AcctSeed_Account_PayableTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, AcctSeed.AccountPayable: execution of BeforeInsert caused by: System.DmlException: Upsert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [AcctSeed__Ledger_Id__c]: [AcctSeed__Ledger_Id__c] Class.AcctSeed.SFDCSecurityUtils.ProxyDMLHelper.upsertByProxy: line 607, column 1 Class.AcctSeed.SFDCSecurityUtils.upsertProxy: line 469, column 1 Class.AcctSeed.SFDCSecurityUtils.upsertProxy: line 464, column 1 Class.AcctSeed.FinancialSuiteUtils.updateLedgerCustomSettingFromAccountingSettings: line 440, column 1 Class.AcctSeed.FinancialSuiteUtils.validateAndReturnDefaultLedgerId: line 416, Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_AcctSeed_Account_PayableTest.testTrigger: line 11, column 1
--

**Comment by JimBTek** [comment]
Looks like your existing records are missing field values and failing to allow any update to happen to them. DLRS does not create any records. Let us know if you solve this.

**Comment by bmason33** [comment]
I couldn't add the required code to the Accounting Seed objects as they are managed packages, so I could not run in real time, I changed the settings to run as part of a process and then used process builder to update the records. Everything is working now.

**Comment by JimBTek** [comment]
@bmason33 good to know. I am a fan of the Scheduled Incremental Calculate here https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
