### ISSUE TITLE
LAST_N_MONTHS parameter doesn't work

### ISSUE THREAD

**Issue by PabloSche** [afawcett/declarative-lookup-rollup-summaries#812]
Hi, 

I noticed that some of the Roll-Up Summaries that contains a time variable are not currently updating the Parent object properly. I didn't modified the statement lately and I'm wondering if someone else is having a similar issue.

Best, Pablo

**Comment by afawcett** [comment]
@PabloSche i am not sure what to make of this issue without more information. Please can you provide a screenshot of your rollup and steps to reproduce and we can totally re-open this issue. 👍
