### ISSUE TITLE
Duplicate records creation for scheduled Metadata DLRS record

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#813]
Hi @afawcett 

Observed that after creating DLRS metadata record of scheduled type, a duplicate record in Lookup Rollup Summary with N/A values gets generated as follows :

![image](https://user-images.githubusercontent.com/35553420/56425563-7a898d80-62d2-11e9-8ea3-d9253eea04c2.png)

Could you confirm the working of scheduled DLRS?

**Comment by afawcett** [comment]
@Shraddha-Ingale this can be ignored, If you are using Manage Rollup Summaries tab and not any other to manage rollups you can totally ignore anything on the Lookup Rollup Summaries tab. In a future release I will remove the need for these funny records that distract and worry users.
