### ISSUE TITLE
Relationship Criteria Fields: Field ResponseStatus does not exist on the child object.

### ISSUE THREAD

**Issue by kryan0618** [afawcett/declarative-lookup-rollup-summaries#814]
Hi Andy,

I am having problems creating a rollup of the SurveyInvitation object to a custom object, TASKRAY__Project__c. I am trying to get the number of completed surveys on a project.

I get the following error messages when I try to save my rollup:
1. Relationship Criteria Fields: Field ResponseStatus does not exist on the child object.
2. Relationship Criteria: Relationship Criteria 'ResponseStatus = 'Completed'' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'No such column 'ResponseStatus' on entity 'SurveyInvitation'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.'

However, I can run the following SOQL on workbench without any issues:
SELECT Id,Project__c,ResponseStatus,Survey_Name__c FROM SurveyInvitation where ResponseStatus = 'Completed'
![DLRS_Error](https://user-images.githubusercontent.com/32651743/56673361-c1360980-667d-11e9-9052-36d3d7298a3f.jpg)

Thank you for your help!
Kris

**Comment by kryan0618** [comment]
Andy... anything that can be done in regards to this?
Thanks!
Kris

**Comment by aheber** [comment]
@kryan0618 it looks like this field came with v44 and I think DLRS is only up to v42. The API version of the classes will need to be updated to support this field.

CC @afawcett

**Comment by JimBTek** [comment]
I have opened a new issue #831 that will resolve this hopefully in the next release. For now you could create a custom formula field that mirrors the missing field and roll that up instead. Or you could go with the unmanaged version of DLRS and update the API numbers yourself, but that could cause you some longer term maintenance issues.

**Comment by afawcett** [comment]
Good workaround @JimBTek . WIll close this issue as its indeed resolve by the API upgrade issue you raised. 👍
