### ISSUE TITLE
caused by: System.DmlException: Upsert failed. First exception on row 2; first error: 

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#817]
Hi @afawcett,

I am facing below error :
Apex script unhandled trigger exception by user/organization: 0050J000006Spb1/00Db0000000IrDI

dlrs_SMSTrigger: execution of AfterInsert

caused by: System.DmlException: Upsert failed. First exception on row 2; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 4 records: **a2E0J000000i8bpUAA,a2Eb0000000gONHEA2,a2E0J0000001HBUUA2,a2E0J000000i8YqUAI**: []

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1023, column 1
Class.dlrs.RollupService.handleRollups: line 919, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_SMSTrigger: line 7, column 1

The 4 record Id's mentioned in error are the scheduled DLRS records.
and all are scheduled at different time, then what could be the reason that this issue has arrived.

Also, The records which were failed to update due to this error, Will they process in DLRS's next scheduled batch?

**Comment by JimBTek** [comment]
Do you know that each job is completing before the next one starts?

**Comment by afawcett** [comment]
Yes, @Shraddha-Ingale do you have multiple RollupJob's scheduled that might overlap?

**Comment by afawcett** [comment]
@Shraddha-Ingale can you update to latest release as there was some improvements in this area. Meanwhile will close this out - but we can for sure re-open as needed.
