### ISSUE TITLE
Support Dated Currency Rates

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#82]
Version 1.12 fixed an issue with the use of Currency fields, this enhancement represents the desire to convert according to a dated exchange rate, perhaps via a custom setting or field on the parent record? Please feel free to add thoughts and requirements about this here.

**Comment by Kilay** [comment]
Hello @afawcett ,

I created a PR in LREngine repo to handle dated exchange rates : https://github.com/abhinavguptas/Salesforce-Lookup-Rollup-Summaries/pull/19.
Do you think it is the best way to handle it ? Any advice would be welcome.

**Comment by afawcett** [comment]
See https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/284

**Comment by afawcett** [comment]
Closed, see https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/284 for more info.
