### ISSUE TITLE
Lightning - calculated field showing previous cached value

### ISSUE THREAD

**Issue by fourfourfun** [afawcett/declarative-lookup-rollup-summaries#820]
I believe this is a Lightning issue rather than a DLRS issue.

Commented this on Chatter:

"Has anyone seen a properly weird Lightning issue that I'm getting. It may be unrelated to DLRS, but I've only noted it happen so far on DLRS updated fields.

I'm on a record, in Lightning, I'm looking at the field where something should be rolled up to. They are blank when they should be populated.

 If I switch to Classic, the fields are populated. If I report on it, they are populated.

 Another user views the fields in lightning, they are populated.

 A weirdly inconsistent spread of visibility. I've tried the old SHIFT F5 to no avail here and it is a frankly weird situation to troubleshoot. The data is clearly there."

Known issue points to here:

https://success.salesforce.com/issues_view?id=a1p3A0000001C8QQAU

**Comment by harrisoe69** [comment]
Are you using Chrome? If so update your Version and Relaunch your browser

**Comment by JimBTek** [comment]
Thanks for providing this issue so others may find it!  Since it's not a DLRS issue I am closing it out though.
