### ISSUE TITLE
Adding a date value to realatiuonship criteria

### ISSUE THREAD

**Issue by thinkconor** [afawcett/declarative-lookup-rollup-summaries#821]
Scheduled job 'rollup_m000f000000bmTs' threw unhandled exception.

caused by: dlrs.RollupServiceException: A calculate job for rollup 'Reservation amount paid' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.

Class.dlrs.RollupService.checkJobAlreadyRunning: line 639, column 1
Class.dlrs.RollupService.runJobToCalculate: line 97, column 1
Class.dlrs.RollupCalculateJobSchedulable.execute: line 11, column 1

Before our consultant left, she thought this error might be caused by the query timing out in searching all the opportunities (85,000) in our instance.

The current Relationship Criteria is:
opportunity.StageName = 'Posted' AND (opportunity.type = 'Guesthouse retreat'  OR opportunity.type = 'Emery House retreat’)

Im trying to change this so it would only look at Opportunities modified Today().

opportunity.LastModifiedDate = 'Today()' AND opportunity.StageName = 'Posted' AND (opportunity.type = 'Guesthouse retreat'  OR opportunity.type = 'Emery House retreat’)

I'm having no luck!
Would you have any advise on how I could fix this?

Thanks

**Comment by JimBTek** [comment]
I am guessing you are doing a nightly Schedule Calculate? Look at the docs for switching to realtime or a delayed scheduled job. this only recalcs when the records are actually changed. You could also use Process Builder to the same effect

**Comment by thinkconor** [comment]
Hi Jim,
Thanks, but it is scheduled for realtime calculating. I hadn’t understood that this would then only be actual changes.

Might  switching to process builder, or scheduled be a way to remove this?

Conor Byrne
Director of Projects
Society of Saint John the Evangelist
980 Memorial Dr, Cambridge MA 02138

www.SSJE.org<http://www.SSJE.org>

On May 10, 2019, at 3:38 PM, Jim Bartek <notifications@github.com<mailto:notifications@github.com>> wrote:


I am guessing you are doing a nightly Schedule Calculate? Look at the docs for switching to realtime or a delayed scheduled job. this only recalcs when the records are actually changed. You could also use Process Builder to the same effect

**Comment by JimBTek** [comment]
also I believe you are writing your SOQL query with a Date Literal incorrectly, but it should not matter if it is realtime.  i'd try the incremental schedule https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

There are some salesforce limits if you have over 50,000 records you might have to look into.  Good luck and please report back how you fix your issue to help the next person

**Comment by thinkconor** [comment]
Ok, thank you for your help.

Conor Byrne
Director of Projects
Society of Saint John the Evangelist
980 Memorial Dr, Cambridge MA 02138

www.SSJE.org<http://www.SSJE.org>

On May 10, 2019, at 3:54 PM, Jim Bartek <notifications@github.com<mailto:notifications@github.com>> wrote:


also I believe you are writing your SOQL query with a Date Literal incorrectly, but it should not matter if it is realtime. i'd try the incremental schedule https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

There are some salesforce limits if you have over 50,000 records you might have to look into. Good luck and please report back how you fix your issue to help the next person

**Comment by afawcett** [comment]
@thinkconor let us know if you still want to chat and we can re-open for sure! 👍
