### ISSUE TITLE
dlrs_CaseTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field MasterRecordId for Case: Class.dlrs.RollupService.handleRollups

### ISSUE THREAD

**Issue by pdebidutta** [afawcett/declarative-lookup-rollup-summaries#822]
In our sandboxes, we are getting this error while saving the case with the  checkbox **'Assign using active assignment rules'**  checked.

It works fine when the checkbox is not checked.

I have looked into our assignment rules as well, but there is nothing wrong with them too.

**There was custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_CaseTrigger caused an unexpected exception, contact your administrator: dlrs_CaseTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field MasterRecordId for Case: Class.dlrs.RollupService.handleRollups: line 681, column 1".**

 
I have looked into the code and as a part of my investigation, I have deactivated the DLRS case trigger and I was able to create the case without any error.

Also only analyzing the trigger I see that an apex class dlrs.RollupService.triggerHandler(); is being called. In order to check the functionality, I have commented out the dlrs.RollupService.triggerHandler(); line and the case was created without any error.

I know that we don't have read/edit permission for dlrs.RollupService.triggerHandler(); class as it's from the managed package.

This issue is not replicated in our production environment.

Please help me out here if we could do anything with the class  **dlrs.RollupService.triggerHandler().**
Our case creation was working 4 days ago and we didn't change anything in our org after that.

**Comment by JimBTek** [comment]
@pdebidutta please see issue #818, there is a known issue with DLRS and Summer '19 and a patch is available for testing.

**Comment by revathikalai** [comment]
We received the same type of error :
One or more failures occurred in last execution of apex job SBQQ.RootIdSetterParentSubscriptions. 1 failed out of 1 on 2021-09-28 06:15:41. Extended Status: First error: Update failed. First exception on row 0 with id a1H3L000000HpLHUA0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_SBQQ_SubscriptionTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field SBQQ__Contrac

Can you please suggest the action item.
