### ISSUE TITLE
Roll up one Event value to Multiple Contacts

### ISSUE THREAD

**Issue by Jyuukenbu** [afawcett/declarative-lookup-rollup-summaries#825]
Hi All, i'm having an issue when rolling up a value to multiple contacts, it only rolls up into the first contact. I saw the thread down here -https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/787
It says i'll need EventRelations object, but i think its not a standard object? How do i add the aggregate custom field into it then? Thats where i'm stuck, any advise will be truly appreciated.
Thanks!

**Comment by afawcett** [comment]
So this is a standard object, its defined here > https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_eventattendee.htm. Can you share more information on your issue? Screenshot of your rollup, what your steps are and expected results?
