### ISSUE TITLE
Scheduling Roll up CAlculate Job

### ISSUE THREAD

**Issue by srichardsonxmatters** [afawcett/declarative-lookup-rollup-summaries#826]
When I'm scheduling the apex roll up job, which class do I use?  The documentation says to use "RollupJob", however I want to confirm:

"RollupJob"
Or
"RollupCalculateJobSchedulable"

**Comment by DanDonin** [comment]
RollupJob

**Comment by srichardsonxmatters** [comment]
Thx! I initially created the roll up summary fields to calculate on real time, but have since decided to move them to scheduled.  however, I'm noticing they are still running real time. Do I need to delete or inactivate triggers that were installed when I initially set the calculation to real time?
