### ISSUE TITLE
Roll up summary solution not stable - works vs. doesn't work

### ISSUE THREAD

**Issue by juliettelessing** [afawcett/declarative-lookup-rollup-summaries#827]
Hi all, 

We have set up the roll up summary using the package as below. In general it works perfectly, but sometimes it doesn't update the Aggreggate Result field even though the opportunities which drive the roll up are similar as the ones which work as designed. When I then go into the app and click calculate it works again (which is not realtime!). I don't find this a stable solution for our client. Did somebody experience the same problem and has a possible solution?

Thanks in advance!

Juliette

![image](https://user-images.githubusercontent.com/51149712/58533181-2657be80-822b-11e9-9a79-3db662033a68.png)

**Comment by JimBTek** [comment]
Hi Juliette,  DLRS is heavily used by many orgs and can be considered stable.  If you are having inconsistencies in scheduled jobs, look at the batch logs.  you could have 1 record that fails in a batch, killing the whole batch, causing some records to not update.  This is usually a data or permissions issue, a lot of times a new validation rule can break things.  Please let us know how you resolve it to help the next person.

**Comment by afawcett** [comment]
@juliettelessing keep in mind the DLRS engine only looks for changes you tell it to look for in the Relationnship Criteria Fields field. So please add StageName and RecordTypeId to this field so it will spto changes to those fields and recalculate the rollup.

**Comment by afawcett** [comment]
Let us know if this does not help. 👍
