### ISSUE TITLE
Cannot uninstall 

### ISSUE THREAD

**Issue by kenhayes69** [afawcett/declarative-lookup-rollup-summaries#829]
When we try to uninstall Declarative Lookup, we are getting this error. We are not programmers - just Finance people :)  We cannot figure out how to get rid of the DRLS Opportunity trigger without hiring a developer.
Any help would be appreciated!

![Capture](https://user-images.githubusercontent.com/51238595/58830587-a9f12100-8618-11e9-8f22-acef153eb2b3.JPG)

**Comment by DanDonin** [comment]
Go to a dlrs record that has the opp object as a child. Click manage child
trigger. Click remove.

**Comment by kenhayes69** [comment]
How do I find the drls record that has the opp object as a child?

Sent from my iPhone

On Jun 3, 2019, at 4:03 PM, DanDonin <notifications@github.com<mailto:notifications@github.com>> wrote:

Go to a dlrs record that has the opp object as a child. Click manage child
trigger. Click remove.

**Comment by DanDonin** [comment]
You can just create one

**Comment by kenhayes69** [comment]
Ok, I did that and then tried to remove the Child Trigger and got his error

![image](https://user-images.githubusercontent.com/51238595/58831728-53391680-861b-11e9-85e5-0b2a68fe8da4.png)

**Comment by DanDonin** [comment]
You'll need to create the remote site setting

**Comment by kenhayes69** [comment]
Worked!

YDM

**Comment by JimBTek** [comment]
thanks @DanDonin!  Closing this
