### ISSUE TITLE
AccountContactRelationship rollup when deleting Contact record

### ISSUE THREAD

**Issue by benzybrg** [afawcett/declarative-lookup-rollup-summaries#830]
We have "Contacts to Multiple Accounts" enabled, and I am trying to count the number of contacts related to an account, regardless if the relationship is direct or indirect (ie: count ALL related contacts) via the AccountContactRelationship object.

The rollup works when adding or removing a relationship. However, it does not work when deleting a contact record. I believe the issue might be that the trigger is on the AccountContactRelation object?

How can I get it to calculate the rollup when deleting a contact record?

Thanks

**Comment by JimBTek** [comment]
Hmm, does deleting a contact cause the ACR record to get deleted as well? I would think so. 

You could write a custom trigger on Contact to toss the parent Account(s) into the scheduled job, and clean them out every hour.

**Comment by benzybrg** [comment]
Yes that could work. However, I guess that defeats the purpose of having a declarative tool!

**Comment by afawcett** [comment]
"I believe the issue might be that the trigger is on the AccountContactRelation object?" this is correct. DLRS only monitors changes on the child object and then only on fields you tell it to monitor via "Relationship Criteria Fields" field. You might have to use a full recalc rollup, see wiki here > https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. Let us know if this helps. 👍
