### ISSUE TITLE
Update API version of DLRS

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#831]
There have been several issues that have come up because of the API versions of DLRS.  The goal is to update all files to the latest API and ensure tests pass.

#814

**Comment by tet3** [comment]
With the flurry of new objects coming out in the industry vertical products, can this be stored in CMDT so that it's user updateable when a new SFDC release comes out without a new package release being required? Hitting this issue with Health Cloud objects today.

**Comment by afawcett** [comment]
@tet3 that is a great idea, but would unfortunatlly only apply to the scope of the trigger code not the packaged code it calls. I'll ponder further though. Meanwhile will update statically.

**Comment by afawcett** [comment]
Fixed in v2.12

**Comment by Jnew21** [comment]
@afawcett I have upgraded the most recent version of DLRS, as we are wanting to roll up CareRequests to the Care Plan Case.  I have created the record appropriately (see attached), but I am receiving the follow error and cannot figure out why?

![DLRS Record](https://user-images.githubusercontent.com/61887157/79381777-7ec1a880-7f30-11ea-9b3e-c4ff99efdd56.jpg)
![DLRS Error](https://user-images.githubusercontent.com/61887157/79381779-7ec1a880-7f30-11ea-8ef4-210c98eec64b.jpg)

 the following error when deploying the trigger.

**Comment by afawcett** [comment]
https://developer.salesforce.com/blogs/engineering/2015/02/gack.html 

Can you ask Salesforce to decode this for you? Maybe it will shed some light. Feel free to share back here or ideally a new issue, as its not really related to API version increase. Thanks!

**Comment by Jnew21** [comment]
Andy,

When looking at the Care Requests for Health Cloud, it is required to have
a Care Plan Case and then an additional Case between the Care Plan and the
Care Request.  (Please see below)  We are wondering if the code in DLRS can
handle this in its current state?  Let me know if this helps clear things
up.  I do have a ticket in with support, but thought I would clarify what
we are trying to do.

[image: image.png]

*Regards,*

*Jonathan Newcomer*
*724-316-5998*

**Comment by Jnew21** [comment]
We also tested using the MemberPlan object from Health Cloud and the Care
Request and received the same error.  The Image above should show a line
from Care Request Level 1 to Care Plan Case Record.  That is ultimately
what we are trying to do.  Thank you for your time.

*Regards,*

*Jonathan Newcomer*
*724-316-5998*

**Comment by Jnew21** [comment]
@afawcett I heard back from Salesforce support and they wanted me to relay the following:

I have checked into server logs and i can see the below exception it might be in the Package code.

java.lang.NullPointerException

There is a null pointer exception in the package code.

dlrs/RollupService


Please let me know if I can provide any other information, but that is all they gave me.  Thanks so much.

**Comment by afawcett** [comment]
@Jnew21 thanks for this intel - did they happen to give a line number for that file? RollupService.cls is quite large.
