### ISSUE TITLE
Scheduled DLRS Not Firing Correctly

### ISSUE THREAD

**Issue by erinAtZip** [afawcett/declarative-lookup-rollup-summaries#832]
Hi!
I have an hourly scheduled DLRS. It's built on the Contact object but looking at the case object in order to update a date/time field. When a survey is sent via the case status, a field, Survey Sent, is updated by a workflow rule. We then need a field on the contact called Last Survey Sent to be updated with the same timestamp. This is so we can avoid inundating contacts with surveys.
![Snip20190611_1](https://user-images.githubusercontent.com/40807383/59281750-a2cfa180-8c1c-11e9-8bed-bf53c019a8cc.png)

It went live 5/28 but has only worked off and on and really for only one random day 6/5. It would constantly review over 32,000 records each time it ran. So it would hit limits and fail. The reports with these fields take forever to run and update in salesforce as well.
![Snip20190611_2](https://user-images.githubusercontent.com/40807383/59281935-f4782c00-8c1c-11e9-863c-df1c82e9c599.png)

I have since had to turn this DLRS off due to the fact that some of our email-to-cases have been encountering the following error:

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY : dlrs_CaseTrigger: execution of AfterInsert

caused by: System.DmlException: Upsert failed. First exception on row 0; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 1 records: a0g0f00000bIMxKAAW: []

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1023, column 1
Class.dlrs.RollupService.handleRollups: line 919, column 1
Class.dlrs.RollupService.triggerHandler: line 329, column 1
Trigger.dlrs_CaseTrigger: line 7, column 1

a0g0f00000bIMxKAAW is the ID  of the DLRS.

Any one have any suggestions on how I can go about this and fix these issues?

**Comment by JimBTek** [comment]
Make sure you are using the correct scheduled job  vs. the nightly scheduled full calculate.  Why is it hitting so many records within an hour? Are there really that many contacts being edited within an hour?  You can have the job run more than once an hour if you create multiple schedules jobs. I have done every 15 min this way.  You can also try Process Builder with a Scheduled Action for 0 hours to isolate each parent object into its own transaction. There may be some other tricks.

Please report back with how you solved this.

**Comment by afawcett** [comment]
@erinAtZip any thoughts in respect to @JimBTek 's suggestions?
