### ISSUE TITLE
System.LimitException: Apex CPU time limit exceeded on DLRS_CampaignMember

### ISSUE THREAD

**Issue by pdebidutta** [afawcett/declarative-lookup-rollup-summaries#833]
We are frequently getting this System.LimitException: Apex CPU time limit exceeded error while loading Campaign members to our system and below is the debug :

ERNAL]|01q24000000TqWr|dlrs_CampaignMemberTrigger on CampaignMember trigger event AfterInsert|__sfdc_trigger/dlrs_CampaignMemberTrigger
12:57:04.716 (24719416041)|USER_DEBUG|[23]|DEBUG|#dlrs_OpportunityTrigger#checkDeployment
12:57:04.716 (24720041329)|SYSTEM_MODE_ENTER|false
12:57:04.716 (24727715197)|FATAL_ERROR|System.LimitException: Apex CPU time limit exceeded

Class.dlrs.RollupService.handleRollups: line 677, column 1
Class.dlrs.RollupService.triggerHandler: line 319, column 1
Trigger.dlrs_CampaignMemberTrigger: line 27, column 1
12:57:04.716 (24727740313)|FATAL_ERROR|System.LimitException: Apex CPU time limit exceeded

Class.dlrs.RollupService.handleRollups: line 677, column 1
Class.dlrs.RollupService.triggerHandler: line 319, column 1
Trigger.dlrs_CampaignMemberTrigger: line 27, column 1

It's a bummer that we cannot check the dlrs classes from our side.
Steps we followed from our side:
We converted all of the Campaign members DLRS's from real-time to scheduled.
We also added many filters to our CM flows so that they don't cause the DLRS to fail still, it is failing.
Is this a known bug?
Please help us with the same.

**Comment by pdebidutta** [comment]
[DLRS errors CPU time limit 4824.log](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/3306072/DLRS.errors.CPU.time.limit.4824.log)

**Comment by JimBTek** [comment]
I do not believe there is a known bug.  There are limitations with how many records and how many rollups on a single object you can have.  You should not do a nightly Schedule full-recalculate, you should do the scheduled job that you can run hourly. There is documentation in the readme/wiki about different schedule types.

If you are beyond the limits you may not be able to use DLRS for this problem, and may have to write your own solution.  Please reply back with how you decided to resolve this issue to help others. thanks!

**Comment by afawcett** [comment]
Its odd that you have converted all to schedule and still get this, as DLRS does very little CPU in this mode, just logs a record on a queue for the schedule job to do the actual rollup. So it makes me think there is some other Apex code running. The CPU limit is shared by ALL apex code that is run, DLRS code plus another other packages or custom code on related objects. What other triggers are on the parent and child objects or ones that might fire as a result of those being updated?
