### ISSUE TITLE
VisualForce Page not found after saving

### ISSUE THREAD

**Issue by daniielev** [afawcett/declarative-lookup-rollup-summaries#834]
Hello there!

I installed the Sandbox managed packaged and everything went good.

After creating and saving the first entry without the 'Active' checkbox on, I can't access anymore to the Tabs: Welcome & Manage pages, I get a Not Found error.

I was able to view all these tabs before creating the first entry.
<img width="888" alt="Screen Shot 2019-06-20 at 11 53 14 AM" src="https://user-images.githubusercontent.com/8409876/59870111-1b87d980-9352-11e9-876b-71abf01d3368.png">

Now I am not able to access them. I can just entry to the Logs.
<img width="918" alt="Screen Shot 2019-06-20 at 11 49 12 AM" src="https://user-images.githubusercontent.com/8409876/59869944-bb913300-9351-11e9-898e-c5f0b5785770.png">
I check all the permission sets and the modify all data is also enabled on my profile. Any ideas?

**Comment by JimBTek** [comment]
Were you able to solve this? Do you have Permissions to the VF Page?
