### ISSUE TITLE
Roll Up Summary Calculate Not Working

### ISSUE THREAD

**Issue by Retreever** [afawcett/declarative-lookup-rollup-summaries#835]
I have successfully used this application in other client orgs I manage but there seems to be an issue with this implementation. I installed the tool in a client Sandbox and created a Roll Up Summary rule as before then installed the Child Trigger successfully and clicked the calculate button but nothing has happened. I am attached a screen capture of the rule in case someone can spot my mistake.
![Roll Up on MRR](https://user-images.githubusercontent.com/47255780/60007048-f348f500-9647-11e9-88d1-da377e27ec00.JPG)

**Comment by JimBTek** [comment]
Did you see a job in your logs? did it fail? Does it also do nothing when you manually edit a record and let the trigger run?  You may also want to run as the System vs. User.

**Comment by afawcett** [comment]
@Retreever any updates?

**Comment by Retreever** [comment]
@afawcett Hi Andrew, thanks for following up - never was able to solve this problem. Issue is my skill set I think.
