### ISSUE TITLE
CPU Time Limit Issue

### ISSUE THREAD

**Issue by sue888** [afawcett/declarative-lookup-rollup-summaries#836]
Hi, 

I have a client who is experiencing a CPU Time Limit issue.  They've created a Visualforce page that allows them to insert  a batch of parent records, and then the controller goes on to insert child records for those parent records.  They use DLRS in realtime mode for rollup summaries on the parent record, and then on the parent's parent record.  Anyway, long story short, DLRS is invited into the execution context a lot, and when it updates the parent records there's a fresh round of workflows and process builder flows that are invoked - that's when the CPU Limit Error occurs.

I've read [this link](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups) and thought schedule mode might work, but they need a quicker update.  I'm wondering if I could use Developer mode and basically launch those updates in a new execution by calling DLRS methods using @future.  Problem is my search skills have failed me,  I can't find much information on how to use the Developer mode, or anyone having done this.  Which makes me suspect there's a good reason it hasn't been done.

Would appreciate any pointer to documentation, or a warning if I'm happily skipping down the wrong path.

Many thanks.

**Comment by DanDonin** [comment]
You could also set the PB/WFR to not fire if the dlrs field is updated.

**Comment by sue888** [comment]
Good idea, will propose that too.

**Comment by JimBTek** [comment]
I would use a Process Builder with Scheduled Actions.  but then set the scheduled action to 0 hours. It will happen similar to a @future, in the next few seconds/minutes.

Or you can use the scheduled DLRS, and setup 4 or more schedules so it runs every 15 minutes or less.
