### ISSUE TITLE
How to return one value based on min value of another?

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#841]
Hi
I want to populate a lookup field, so return the record ID, on a parent object based on the min value of a date field in the child object.  In other words, I want to populate the parent lookup field with the ID of the most recent child record.

Is this possible using DLRS?

**Comment by DanDonin** [comment]
Order by date field either asc or desc then pick first or last based upon
sort order

**Comment by LawranceT** [comment]
Many thanks for the fast response @DanDonin , much appreciated
