### ISSUE TITLE
Rollup Summary on Case with a SUM of a custom field on Task not working

### ISSUE THREAD

**Issue by mwinklerbiac** [afawcett/declarative-lookup-rollup-summaries#842]
Found this thread from 2016 that didn't seem to resolve the issue that I am also having (https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/289)   #289 @violetyyyy @afawcett 

Here is a screen shot of my rollup:
![In-person meeting minutes on case rollup](https://user-images.githubusercontent.com/53020789/61411235-25462380-a8a3-11e9-98ad-8fc394cac434.jpg)

I also have a parent record filter when I calculated for the only Case Record Types that we are currently using RecordType.Name = 'Resource Navigation' OR RecordType.Name = 'Self-management' OR RecordType.Name = 'Education Consultation'

Any help would be much appreciated!

**Comment by mwinklerbiac** [comment]
**Update:** It appears to be working Realtime, but the Calculate job for all existing records does not seem to work. The In_Person_Meeting_Minutes__c field reads 0 (Zero) until I create a new task on the case or edit an existing task on the case.

**Comment by afawcett** [comment]
Yes, In_Person_Meeting_Minutes__c needs to have a value (not null) in it to be aggregated by SOQL. Make sure that this field is always popupualted.
