### ISSUE TITLE
Creates an error on bulk update

### ISSUE THREAD

**Issue by jayomayan** [afawcett/declarative-lookup-rollup-summaries#843]
I installed and tried DLRS but it creates an issue on our Email Services when it is being processed.
The Email Service upserts activities in Task in bulk usually around 500 rows every hour.
Does anyone had the same issues as mine? Is there something that I need to configure in order not to make conflict with Bulk update/insert from Email Services.

Thanks in Advance.

**Comment by afawcett** [comment]
If your using Data Loader, disable parrell inserts. Also look at https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
