### ISSUE TITLE
Scheduling Rollup Jobs via Apex

### ISSUE THREAD

**Issue by Varun-Sharma-1981** [afawcett/declarative-lookup-rollup-summaries#845]
I am attempting to write an Apex class that will be run when we refresh our Sandboxes. The class will be responsible for scheduling all of our Apex jobs in the Sandbox (to mimic Production). We have many Declarative roll-up jobs which we would like to schedule in our Sandbox. However, I can't seem to find the names of the schedulable Apex Classes.

Can you provide insight on how we can schedule DLRS jobs to run via Apex? The jobs that get created when you schedule a DLRS record via the GUI must be running a schedulable Apex class. It would help tremendously if we could reference these in our code

**Comment by afawcett** [comment]
Sure that would be dlrs.RollupJob (just one of these) and then dlrs.RollupCalculateJobSchedulable  (however this is not global so you cannot access it). Does the sandbox copy not bring the schedules over?
