### ISSUE TITLE
caused by: System.DmlException: Upsert failed. First exception on row 2; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 4 records: a2E0J000000i8bpUAA,a2Eb0000000gONHEA2,a2E0J0000001HBUUA2,a2E0J000000i8YqUAI: []

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#847]
Hi,
I have received the below exception multiple times.
as per my understanding, it throws UNABLE_TO_LOCK_ROW exception for some dlrs records, DLRS Id's are mentioned in the below error message.
Could anyone help me to understand the cause of this exception?

Here is the exception :
Apex script unhandled trigger exception by user/organization: 005b0000001s5As/00Db0000000IrDI

SMSTrigger: execution of AfterInsert

caused by: System.DmlException: Update failed. First exception on row 0 with id a0N0J00000OPSAVUA5; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_SMSTrigger: execution of AfterUpdate

caused by: System.DmlException: Upsert failed. First exception on row 2; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 4 records: a2E0J000000i8bpUAA,a2Eb0000000gONHEA2,a2E0J0000001HBUUA2,a2E0J000000i8YqUAI: []

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1023, column 1
Class.dlrs.RollupService.handleRollups: line 892, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_SMSTrigger: line 7, column 1: []

Trigger.SMSTrigger: line 559, column 1

**Comment by afawcett** [comment]
This can occur when there are many high concurrent inserts of records in your child object as the platform cannot lock the parent record. If you are using a dataloader to load child record data try switching off parrellel insert.
