### ISSUE TITLE
Schedule realtime dlrs

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#848]
Hi @afawcett 

We have one realtime rollup records but want to schedule at the start of season i.e. year to reset the values.
Can we schedule it through apex by accessing dlrs scheduler or some other way?

**Comment by afawcett** [comment]
Maybe use a full recalc with year in the criteria? See https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
