### ISSUE TITLE
dlrs_ContactTrigger: execution of AfterUpdate

### ISSUE THREAD

**Issue by lereromri** [afawcett/declarative-lookup-rollup-summaries#850]
Hi, i'm getting this error on the contact trigger:
**Message: 
Id:null
dlrs_ContactTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field isPersonAccount for Account

Class.pi.RandomUtils.hasPersonAccounts: line 109, column 1
Trigger.pi.LogAccountChange: line 3, column 1**

This looks similar to the Case merge problem #818  but on another object maybe?
iv'e checked the summary config and the field is AccountId so this is not the problem, what cloud be causing this?
thanks, omri

**Comment by afawcett** [comment]
So it looks like DLRS is updating Account as the paraent in the rollup config, correct? If so, there is a trigger called pi.LogAccountChange that is having this error, not DLRS. DLRS is just blamed because its at the root of the operation. You will have to consult with the package owner of "pi".

**Comment by dschach** [comment]
The "pi" namespace is Pardot
