### ISSUE TITLE
Real Time Calculation Triggering Validation Rules with No Update

### ISSUE THREAD

**Issue by Sawlty-Admin** [afawcett/declarative-lookup-rollup-summaries#851]
Hello!

I'm having an issue somewhat similar to the original query in issue #541, but for Real-Time Calcs: 

- Whenever a Real-Time/System rollup is run, a Validation Rule is triggered _only_ if there are NO updates to the aggregate field that the rollup calc is attempting to determine...

I have a field, "Total Touches" on the Lead object that DLRS populates with the total number of Tasks for that Lead that are in a "Completed" Task Status (a filtered calc based on relationship criteria).  I also have a Validation Rule that requires a Country to be filled in for each Lead before a User can edit it, but I have already added a check to bypass the Validation Rule if the "Total Touches" field is the one being changed (using ISCHANGED).  

If I add a new Task that is already "Completed", the rollup works just fine, ignores the Validation Rule, and updates the value in "Total Touches" based on the rollup calculation.  If, however, I add a Task that isn't "Completed" (in other words, DLRS should ignore this Task in it's count and not change the "Total Touches" value), the Validation Rule triggers, and the Task insert fails.

**Question**:  Is DLRS attempting to reinsert the same field value into the "Total Touches" field that was already there before, even if it determines that value is unchanged?  This would be the only explanation that I can think of, based on the Validation Rule triggering despite no updates.  If so, is there a way to structure a Validation Rule to ignore this, too?  I know an update was done for Scheduled calcs that would not do anything if the value in the aggregate field was unchanged...can something similar be done for Real-Time calcs?

Thanks in advance for the help!

**Comment by Shmooty** [comment]
What is the DLRS relationship criteria and fields?

**Comment by afawcett** [comment]
" Is DLRS attempting to reinsert the same field value into the "Total Touches" field that was already there before, even if it determines that value is unchanged?" Yes it is. For performance reasons it does not attempt to read the parent record or lock it, just updates it. I believe there is an enhancement request to add a config to change this behavior if desired. Try using the ISCHANGED fucntion in your validation rule setup.
