### ISSUE TITLE
DLRS Error

### ISSUE THREAD

**Issue by Dhruv9221** [afawcett/declarative-lookup-rollup-summaries#852]
We have a 2.11 version in our Salesforce. I have created one lookup job between account and campaign and did not use Field record type field but, got an error 
Error:Apex trigger dlrs_CampaignTrigger caused an unexpected exception, contact your administrator: dlrs_CampaignTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field RecordType for Campaign: (dlrs)

relationship criteria is 
Program_Recordtype_DevName__c = 'USA' and Status != 'Canceled' and (Email_opt_out__c = False OR Primary_contact_do_not_call__c = False)

It is urgent so please help me.

Thanks

**Comment by afawcett** [comment]
I'm not sure either sorry. Can you include a screenshot of your rollup definition?
