### ISSUE TITLE
dlrs.LREngine.BadRollUpSummaryStateException: All of Master/Detail Describefieldresult and RollupOperation info is mandantory

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#855]
Hi,

I have one DLRS which uses its parent's field(lookup relationship) in Relationship Criteria as follow : 
![ss 1](https://user-images.githubusercontent.com/35553420/63512050-6c59b100-c500-11e9-91a6-d828f360762c.JPG)

As the change of parent's field is not recognizable by DLRS, I tried to manually calculate this DLRS but I am facing below exception on manual calculation

**Exception :** 
DML_BEGIN|[1023]|Op:Upsert|Type:dlrs__LookupRollupSummaryScheduleItems__c|Rows:4
DML_END|[1023]
FATAL_ERROR|dlrs.LREngine.BadRollUpSummaryStateException: All of Master/Detail Describefieldresult and RollupOperation info is mandantory

Class.dlrs.LREngine.RollupSummaryField.validate: line 473, column 1
Class.dlrs.LREngine.RollupSummaryField.<init>: line 468, column 1
Class.dlrs.RollupService.createLSFWrapper: line 1235, column 1
Class.dlrs.RollupService: line 1093, column 1
Class.dlrs.RollupService: line 1027, column 1
Class.dlrs.RollupService: line 919, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_SMSTrigger: line 7, column 1
FATAL_ERROR|dlrs.LREngine.BadRollUpSummaryStateException: All of Master/Detail Describefieldresult and RollupOperation info is mandantory

Class.dlrs.LREngine.RollupSummaryField.validate: line 473, column 1
Class.dlrs.LREngine.RollupSummaryField.<init>: line 468, column 1
Class.dlrs.RollupService.createLSFWrapper: line 1235, column 1
Class.dlrs.RollupService: line 1093, column 1
Class.dlrs.RollupService: line 1027, column 1
Class.dlrs.RollupService: line 919, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_SMSTrigger: line 7, column 1

I have some existing DLRS which uses parent field in relationship criteria but they are working fine. i.e below DLRS
![ss 2](https://user-images.githubusercontent.com/35553420/63512637-ee96a500-c501-11e9-8390-017d157509cd.JPG)

Not sure what I am missing here.
Could anyone please help me to understand this issue?

Thanks in advance

**Comment by afawcett** [comment]
So in the first one your operation is "SUM" and in the second it is "Sum". The correct value is "Sum". This could be it.
