### ISSUE TITLE
50k row limit - how to configure the custom setting

### ISSUE THREAD

**Issue by rhgrant5** [afawcett/declarative-lookup-rollup-summaries#856]
I am hitting the 50k row limit and came across posts that say you can reduce the "Calculate Job Scope Size" in the DCLRS custom setting..

I click manage and am creating a new record....there is a pick-list value for Location (Profile or User) --- do I have to create a record for every possible Profile/User that may trigger the DCLRS?  Or can I just create one for the System Administrator?

Thanks

**Comment by cesera** [comment]
I'm having the same problem. Did you ever find out how to configure custom settings?

**Comment by rogeramitchell** [comment]
@rhgrant5 @cesera when you are viewing the custom setting, click Manage. This will let you update the default, which applies to all users invoking DLRS.

**Comment by cesera** [comment]
@rogeramitchell Thank you very much, that is helpful. I was not aware of the Custom Settings section in the setup, learned something new today.

**Comment by rhgrant5** [comment]
Hey guys (@rogeramitchell, @cesera)...so the setting is to help set the batch size for a realtime and scheduled calculate...This does NOT solve the 50k row limit problem...That is due to how many records are returned to do the rollup summary.

My use case involved Tasks as the child object --- the filter criteria was pretty broad and therefore was returning lots of rows....what I did was reduce the "population" of records returned by only including tasks back 90 days...I added a formula checkbox field to tasks called "In DCLRS Scope"...if true the task was created within the last 90 days....that solved my problem....Of course if you cannot reduce the amount of records returned during the roll-up - I don't think there is a solution with DCLRS...I think you would have to re-factor the roll-up using apex (from my understanding you can avoid the 50k limit in that manner - I am not an apex expert so I can't totally confirm that)...

I hope this helps...
