### ISSUE TITLE
Relationship Criteria Issue.

### ISSUE THREAD

**Issue by SenseiJP** [afawcett/declarative-lookup-rollup-summaries#857]
I currently have a Relationship Criteria on one of the Lookup Rollup Summary's I created and having issues with it working correctly.  I am looking for it to look for records that are Active, IsNew=True and the name of the record needs to start with either, AB, CE, EF, or GH. 
 See below for the criteria I created. 

**Status='Active' AND IsNew__c=TRUE AND (Name LIKE '%AB%' OR Name LIKE '%CD%' OR Name LIKE '%EF%' OR Name LIKE '%GH%')**

Relationship Criteria Fields are:  **Status, IsNew__c, Name**

For some reason, other values other than the ones I specified within my criteria are displaying in the Aggregated Results Field.  Example, it will show 'TM34553', and TM is not even part of the criteria.  

Any thoughts and/or suggestions are welcomed.

**Comment by afawcett** [comment]
Hmmm none I am afraid that does not make sense. Maybe try the query in the Developer Console which lets you see the records selected. Perhaps this will shed some light?
