### ISSUE TITLE
Rollup Issue of Task Text on Opportunities

### ISSUE THREAD

**Issue by tomknauss** [afawcett/declarative-lookup-rollup-summaries#860]
I have been having an issue rolling up a Task Text Field on an Opportunity.  Any suggestion would be appreciated.

Use Case:
Want to Rollup Latest Comments from the Last Completed Task to a field Called "Last Activity" on the Opportunity. 

Issue:  If I change the Due Date, which is how Completed Activity is logged, the Rollup works.  If I keep logging tasks on the same day it intermittently fires.  No logic to what record they are actually getting the value from.  Help. :-)

**Comment by afawcett** [comment]
Can you include a screenshot of your rollup and also steps your doing to highlight the issue,

**Comment by afawcett** [comment]
@tomknauss happy to keep chatting - let me know - we can re-open this issue for sure.
