### ISSUE TITLE
Non-selective query against large object type (more than 200000 rows).

### ISSUE THREAD

**Issue by mattromeo911** [afawcett/declarative-lookup-rollup-summaries#862]
Hey @afawcett - great tool, we use it for a number of implementations!

Recently we've been getting this error for some of our bigger implementations who have lots of data and I'm wondering if there's a recommended approach to deal with it.

dlrs_DonationTrigger: execution of AfterUpdate caused by: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter of contact salesforce.com about indexing. Even if a field is indexed a filter might still not be selective when: 1. The filter value includes null (for instance binding with a list that contains null). 2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)
Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1
Class.dlrs.LREngine.WithoutSharingQueryExecutor.query: Line 680, column 1
Class.dlrs.LREngine.rollup: Line 238, column 1
Class.dlrs.LREngine.rollup: Line 117, column 1
Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1038, column 1
Class.dlrs.RollupService.handleRollups: line 895, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_DonationTrigger: line 6, column 1

**Comment by owenmcgorry** [comment]
Hi @afawcett  This is a great tool and has helped us so much with rollups across our Org. 
We've been encountering this error recently as well and I was wondering there was a solution known?

**Comment by JimBTek** [comment]
This is a salesforce platform limit and you should look into indexing.
"Non-selective query against large object type (more than 200000 rows).
Consider an indexed filter of contact salesforce.com about indexing. Even
if a field is indexed a filter might still not be selective when: 1. The
filter value includes null (for instance binding with a list that contains
null). 2. Data skew exists whereby the number of matching rows is very
large (for instance, filtering for a particular foreign key value that
occurs many times)"

You can see that is coming from the underlying library LREngine.

**Comment by owenmcgorry** [comment]
Thanks I was afraid that was the case. We are trying to run about total counts for the values in 4 picklists on the contact object. Rolling up totals onto 4 different objects to track at different levels is creating quite a lot of calculations and filtering so not sure how Salesforce will respond.

**Comment by afawcett** [comment]
@owenmcgorry hope you managed to get your index created by salesforce and/or adjust your criteria to support indexing.
