### ISSUE TITLE
Too Many SOQL Queries with 2 Processes

### ISSUE THREAD

**Issue by lucasarno** [afawcett/declarative-lookup-rollup-summaries#863]
Hello,

We have a model in Salesforce in place that uses Parent and Child Opportunities to manage subscriptions and consumptions. We have 2 processes in place that create child opportunities based on a product(s) being added to the parent opp. Soon as a product is added, 1,4, or 12 child opps are created (number based on a dropdown). 

We've set up about 6 DLRS rollups to total amounts from the child and rollup to the parent, and the rollups work fine IF we only had 1 product. If we try add 2 products (sub and cons) at the same time, we hit the SOQL error.

The 2 processes work the exact same, the only difference being one is to create child opps for Sub products, and one is to create child opps for Con products (we use 2 different lookups, one for Child con, and one for Sub con, which are both lookups from child opp to parent opp, as we need to seperate the view of these child opps by type). 

When testing with only adding one its fine, but with both at the same time it errors, and I can't wrap my head around why its erroring only when we add sub and con products at the same time, as I don't think we should be hitting that limit.

Any help around this would be great. thanks

**Comment by lucasarno** [comment]
Hi,

Can I get some assistance on this please? as this is still an open issue for us.

Kind regards,

Luca

**Comment by afawcett** [comment]
@lucasarno It sounds like this is some custom code you are using to automate the creation of these opportunities? Are you create the opportunities by observing bulkifcation best practice in your code? If your using Flow, make sure to use collection variables and fast insert operations.
