### ISSUE TITLE
Issue in multi currency handling 

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#866]
Hi @afawcett ,

We have an urgent issue regarding multicurrency conversion.
Salesforce doesn't consider multicurrency in the aggregate query.
Please check https://success.salesforce.com/ideaView?id=08730000000b1lLAAQ

Are you using an aggregate query to return the rollup results?
Waiting for your response.

**Comment by aheber** [comment]
@Shraddha-Ingale, most of this tool is built on aggregate queries. There are many historical issues around this problem and it has been an issue for years. I don't think we have any ETA for a fix as it would be a significant logic branch from how this is handled today.
I'm not sure if any of the open PRs would fix these specific issues or are more focused on the dated currency conversion.

**Comment by Shraddha-Ingale** [comment]
Thank you @aheber for your quick response.

**Comment by afawcett** [comment]
Yep thanks @aheber  its a big bit of work and in sensitive part of the code. We do have some PR's and other issues open that are exploring it. So i think we can close this as a duplicate meanwhile.
