### ISSUE TITLE
Rollup on ActivityHistory - Relationship Criteria Issue

### ISSUE THREAD

**Issue by AnnaRudenkoA** [afawcett/declarative-lookup-rollup-summaries#868]
I was tasked to count number of Tasks/Events on Lead (of certain status) created by certain user. 
However according to SF documentation, we can't do direct Select on ActivityHistory - we need to use nested select instead.
Is there any way to achieve it? When I am using "Select" in Relationship criteria, I am getting "error is 'unexpected token: 'SELECT''.

**Comment by afawcett** [comment]
Sorry no, nested selects are not supported in criteria.
