### ISSUE TITLE
DLRS Question about Filtered Rollups

### ISSUE THREAD

**Issue by navafit** [afawcett/declarative-lookup-rollup-summaries#870]
I am new to DLRS and need to create a rollup summary field where the value being rolled up is filtered by a picklist value on a separate object, connected through a junction object. Where do I enter the filter path? Is it in the "Field to Order By" field?

**Comment by afawcett** [comment]
Paths are not supported in the criteria only fields on the child object. What you can do is echo (via process builder) the updates to the separate object field to a field on your child object that the rollup references. Its also worth studying this. https://andyinthecloud.com/2016/02/13/rollups-and-cross-object-formula-fields/
