### ISSUE TITLE
Count not working as expected

### ISSUE THREAD

**Issue by meganleary** [afawcett/declarative-lookup-rollup-summaries#871]
I have a custom child object with a lookup to the Opportunity. I want to count the number of child objects with a status of Approved. I can't get it to go past counting 1.

**Comment by meganleary** [comment]
![Screen Shot 2019-10-11 at 5 22 58 PM](https://user-images.githubusercontent.com/42704220/66685923-ce56ad00-ec4b-11e9-88c2-7d4676a07bf0.png)


![Screen Shot 2019-10-11 at 5 23 31 PM](https://user-images.githubusercontent.com/42704220/66685946-df072300-ec4b-11e9-8500-91863ec712f4.png)
![Screen Shot 2019-10-11 at 5 23 31 PM](https://user-images.githubusercontent.com/42704220/66685949-e0d0e680-ec4b-11e9-9947-7f830f888130.png)

**Comment by rogeramitchell** [comment]
Try setting Field to Aggregate to “Id”

**Comment by afawcett** [comment]
I am a bit confused by this rollup. It looks like your criteria is dependent on a standard field (hence no __c) called Status on your child object Quote_Request__c. is that correct? If so, thats news to me that such a standard field exists on custom objects. Typically one uses Workflow or Process Builder to update a custom field with an applicable value/status and thus then your rollup would reference that? @JimBTek am I missing anything here in my thoughts?
