### ISSUE TITLE
Getting an error since friday

### ISSUE THREAD

**Issue by mila0504** [afawcett/declarative-lookup-rollup-summaries#872]
All was good before Friday, now this error is coming up

Subject: Developer script exception from: dlrs_OpportunityTrigger : dlrs_OpportunityTrigger: execution of AfterUpdate  caused by: dlrs.fflib_QueryFactory.InvalidFieldException: Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSum...﻿Apex script unhandled trigger exception by user/organization: 005f100000HkCk9/00Dj0000000IC03dlrs_OpportunityTrigger: execution of AfterUpdatecaused by: dlrs.fflib_QueryFactory.InvalidFieldException: Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSummary__c'Class.dlrs.fflib_QueryFactory.getFieldPath: line 91, column 1Class.dlrs.fflib_QueryFactory.addOrdering: line 543, column 1Class.dlrs.fflib_SObjectSelector.configureQueryFactory: line 389, column 1Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 273, column 1Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 255, column 1Class.dlrs.RollupSummariesSelector.CustomObjectSelector: line 165, column 1Class.dlrs.RollupSummariesSelector: line 80, column 1Class.dlrs.RollupService: line 1069, column 1Class.dlrs.RollupService: line 750, column 1Class.dlrs.RollupService.triggerHandler: line 311, column 1Trigger.dlrs_OpportunityTrigger: line 7, column 1
--

**Comment by withnumber** [comment]
I'm also getting this error, except mine is on Account.

**Comment by JimBTek** [comment]
Closing this since #873 is more descriptive and they are the same
