### ISSUE TITLE
A calculate job for rollup 'Overdue Open Tasks' is already executing

### ISSUE THREAD

**Issue by rododson** [afawcett/declarative-lookup-rollup-summaries#874]
We are getting the following, intermittent error being reported: 
Subject: Developer script exception from <ORGNAME>: 'rollup_Overdue_Open_Tasks (m021Y000000GnAQ)' : A calculate job for rollup 'Overdue Open Tasks' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rol...

Apex script unhandled exception by user/organization: 005i0000008Wl7T/00Di0000000iaRo

Scheduled job 'rollup_Overdue_Open_Tasks (m021Y000000GnAQ)' threw unhandled exception.

caused by: dlrs.RollupServiceException: A calculate job for rollup 'Overdue Open Tasks' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.

Class.dlrs.RollupService.checkJobAlreadyRunning: line 593, column 1
Class.dlrs.RollupService.runJobToCalculate: line 93, column 1
Class.dlrs.RollupCalculateJobSchedulable.execute: line 11, column 1

**Comment by afawcett** [comment]
Per the message ``` If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.``` have you tried look at that tab? Sometimes jobs fail due to governor limits (you will see in Apex Jobs view) and then these records do not get cleaned up.

**Comment by cornevanklink** [comment]
I tried clearing the record, but this did not solve the problem. Is there anything else I can do?
