### ISSUE TITLE
After Winter 20 release Non-selective query error

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#875]
Ever since the winter 20 release we randomly are getting System.QueryException:

Non-selective query against large object type(more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing... (The whole error message is attached)

I am not sure where to look for the issue because none of the filter fields are null on the executed record. Has anyone else run into this issue and have any advice?

Thank you.

Tami
![Screen Shot 2019-10-24 at 11 57 27 AM](https://user-images.githubusercontent.com/9218441/67504162-e6202f00-f656-11e9-8796-fca864358088.jpg)

**Comment by JimBTek** [comment]
Speaking with Andy,  Winter '20 would not cause this issue, but you could have just coincidentally gone over the limit around the same time.  If you can provide more details, about the object size and query that may help.

**Comment by afawcett** [comment]
@tamilust let us know if indeed this was a progressive data growth issue? Per @JimBTek  message above, if you can provide some more info we can help you determine if so. Thanks. 👍
