### ISSUE TITLE
Rollup summary not calculated

### ISSUE THREAD

**Issue by SonaliOomph** [afawcett/declarative-lookup-rollup-summaries#876]
I have just noticed the roll up summaries are not calculated real time i have to go and click calculate. After I do that its fine why..Please help

**Comment by SonaliOomph** [comment]
just FYI there are 4 look up summary fields others seems to be working but not this one

**Comment by slhyatt77** [comment]
I'm experiencing the same issue.  Were you able to resolve?

**Comment by subbuchunduri** [comment]
we also having the same problem. Real time option is not working at all. any pointers please?

**Comment by mickbroberts** [comment]
I am having the same issue - worked in sandbox , but not in production

**Comment by mickbroberts** [comment]
When I ran the calculation option it worked

**Comment by afawcett** [comment]
Please check the DLRS triggers for your child objects are deployed to production and your rollups are active. Its hard otherwise to give a more detailed answer given the lack of detail on describing these issues, sorry about this. Andy.
