### ISSUE TITLE
Rollup count working on some but not all object records

### ISSUE THREAD

**Issue by rowanlean** [afawcett/declarative-lookup-rollup-summaries#877]
Hi there,
I am trying to do a simple count of all "Completed" status activities for each Opportunity__c record, where the activity field "whatId" has been set.

This is my configuration:
![image](https://user-images.githubusercontent.com/25043249/68234119-70e91e00-ffb5-11e9-89b9-6c9124b5bc92.png)

The count works for most records, however for some it doesn't appear to be counting the activities and I cannot work out why.

I have looked at separate example records and manually counted and compared, and also looked at the activity record data to compare and look for differences but I can't for the life of me work out why some aren't included. Can anyone help me troubleshoot this?

**Comment by karissarothstein** [comment]
Any update on this?  I am experiencing a similar issue

**Comment by afawcett** [comment]
Your rollup looks good to me. Is there anything notable about the Task records that work and those that don't? Are they all created the same way? Any differences in other fields? etc

**Comment by afawcett** [comment]
@rowanlean  let me know if you want to continue to chat - we can re-open.
