### ISSUE TITLE
Getting this error Active: Apex Trigger dlrs_AccountTrigger has not been deployed. Click Manage Child Trigger and try again. when trying to build my first lookup.

### ISSUE THREAD

**Issue by ndlstrong** [afawcett/declarative-lookup-rollup-summaries#878]
Used the packaged install and tried to run my first lookup - got the error 

Active: Apex Trigger dlrs_AccountTrigger has not been deployed. Click Manage Child Trigger and try again.

When I go into my Apex Triggers I see this:
![Screen Shot 2019-11-13 at 5 20 00 PM](https://user-images.githubusercontent.com/57732419/68809395-d97d6e00-0639-11ea-906e-275c109306cb.png)

What am I missing here?

**Comment by afawcett** [comment]
You have a trigger on Account, but its one from another developer / package. Please perform the action per the error message and click Manage Child Trigger, then click Deploy. This will deploy the required trigger for the tool to operate. You need to be an admin.
