### ISSUE TITLE
MALFORMED_ID, Invalid campaign id: null:

### ISSUE THREAD

**Issue by TGMarcovecchio** [afawcett/declarative-lookup-rollup-summaries#879]
I'm attempting to create a rollup rule on Contact referencing CampaignMember. I cannot deploy the dlrsTrigger. I receive the following error.

dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: MALFORMED_ID, Invalid campaign id: null: [CampaignId] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_CampaignMemberTest.testTrigger: line 11, column 1

I have no problem manually forcing a recalculation. I can move it to a process builder but would really prefer the trigger.
![Capture](https://user-images.githubusercontent.com/8320829/68966208-8fb49500-07ab-11ea-962b-fc2e2bfd3bf6.PNG)

**Comment by JimBTek** [comment]
Just guessing, but have you made sure you have all admin permissions for DLRS, and that you are a marketing user who can create Campaigns? Winter 20 is causing some stricter evaluation of permissions.

**Comment by afawcett** [comment]
@TGMarcovecchio  Have you customized the test code on your rollup definition?

Also see [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) and [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197).

**Comment by AlexKasper** [comment]
Seeing exact same errors here on a vanilla installation in both sandbox and production. Marketing permissions are granted.

**Comment by afawcett** [comment]
@AlexKasper can you check the links i shared in the previous post? Happy to re-open this issue.

**Comment by shawnholt** [comment]
@afawcett   I can confirm that this issue occurs in v. 2.12 with child campaign member.  It was resolved by https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197 adding 
`Campaign c=new Campaign(Name='Test');
insert c;
Contact con=new Contact(Lastname='fred');
insert con;

// Force the dlrs_CampaignMemberTrigger to be invoked, fails the test if org config or other Apex code prevents this.
SavePoint sp = Database.setSavepoint();
dlrs.RollupService.testHandler(
    new CampaignMember(campaignid=c.id, Contactid=con.id));
Database.rollback(sp);` 
To the child trigger code.

**Comment by chicagojcb** [comment]
Hello guys, I'm trying to implement this solution with the help of a developer, and we can't figure out where to add the logic.  The CampaignMember trigger is not getting deployed, because of the error.  Can you help?  Where do you insert the code above?
