### ISSUE TITLE
Count for Emails with Specific Subject Not Populating on Contact

### ISSUE THREAD

**Issue by eparr822** [afawcett/declarative-lookup-rollup-summaries#880]
I am new to this tool and trying to set up a count for all Tasks that contain "Settlement" in their subject line and have that populate on the related Contact page. I am receiving this error:

 **Relationship Criteria Fields:** Field Subject does not exist on the child object.
**Relationship Criteria:** Relationship Criteria 'CONTAINS(Subject, "Settlement")' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: ','

Here is what I have so far:
![image](https://user-images.githubusercontent.com/58044766/69360013-c41acc00-0c57-11ea-96a8-126e17d6e4ea.png)

**Comment by afawcett** [comment]
There is no CONTAINS function in SOQL. Maybe look at the LIKE operator? See the link in the error message for examples.

**Comment by afawcett** [comment]
@eparr822 let me know if you want to discuss more and we can reopen.
