### ISSUE TITLE
Email message count not populating in related contact object

### ISSUE THREAD

**Issue by eparr822** [afawcett/declarative-lookup-rollup-summaries#881]
I am new to the tool and having an issue. We use enhanced email, so I am trying to do a count of email messages (object) containing the word "settlement" in it but not "re:" (filtering out the replies). I have it configured like below currently, but it isn't populating for me. Any help is greatly appreciated. 

![image](https://user-images.githubusercontent.com/58044766/69374610-621c8f80-0c74-11ea-88d7-98c2b76edc7a.png)

**Comment by afawcett** [comment]
You have not activated your Rollup, the Active checkbox needs to be ticked. For this to be ticked you need to click Manage Child Trigger that allows the tool to deploy an Apex Trigger for you (you have to be an admin user).
