### ISSUE TITLE
legacy scheduled jobs

### ISSUE THREAD

**Issue by lreneeblock** [afawcett/declarative-lookup-rollup-summaries#882]
Hello - I am joining a established org as new admin. There are legacy scheduled jobs, which error out at irregular frequencies. I cannot find the roll ups that comprise these jobs. In fact, it only seems like there's one DLRS job available, but two scheduled jobs are failing.  Are there any creative ways to see any legacy set up / jobs?

**Comment by afawcett** [comment]
Check both the Manage Rollup Summaries tab and the Rollup Lookup Summaries tab. The scheduled jobs should have a rollup name or rollup record ID in their name you can reconcile with the records in the above tabs. If you don't see any you can delete them. Your error messages in email should also indicate the scheduled job id as well. I am working on a dashboard to do these kind of checks, its partially written.
