### ISSUE TITLE
DLRS Triggers not showing on change set for selection

### ISSUE THREAD

**Issue by AA-SFDC** [afawcett/declarative-lookup-rollup-summaries#883]
I am experiencing issues around adding roll-up triggers to a change.
dlrs app was an old version which would not allow me to create new dlrs triggers so have installed latest dlrs version - 2.11.1
After installation, I was able to create new dlrs triggers but I am not able to add the new dlrs triggers to a change set, it simply does not appear on the change set.

This is a sandbox environment.

**Comment by afawcett** [comment]
So if you have 3 rollups all using the same child object, you will only have one trigger. If you add a 4th rollup in your sandbox for the same child object you won't need to redeploy the trigger. Maybe this is the case?
