### ISSUE TITLE
Created rollup are not correctly displayed

### ISSUE THREAD

**Issue by PierreLELEU** [afawcett/declarative-lookup-rollup-summaries#884]
Created rollup in july are not correctly displayed : 

- lookup relationship 

- rollup details are "N/A" 

- Created By is not the one who created the setup...

But in this SQOL query "select id, CreatedBy.name,dlrs__LookupRollupSummary__c, dlrs__LookupRollupSummary__r.name,dlrs__LookupRollupSummary2__c, dlrs__ParentId__c, dlrs__ParentRecord__c, 
dlrs__QualifiedParentID__c, Name from dlrs__LookupRollupSummaryScheduleItems__c" 
the dlrs__LookupRollupSummary2__c gives an Id that displays correctly the setup !

The right setup has moved to the Custom Metadata...

What's going wrong, is there a way to fix this ?

Thank you 

![Wrong_display](https://user-images.githubusercontent.com/58466352/70042369-ffee5380-15be-11ea-9820-bb73a9770ffb.jpg)
![Right_display](https://user-images.githubusercontent.com/58466352/70042370-0086ea00-15bf-11ea-9c4c-bf881428b948.jpg)

**Comment by afawcett** [comment]
No need for concern. Its the Custom Metadata Type based rollup definition you should focus on. The one created under Lookup Rollup Summaries (your first screenshot) is just a kind of shadow needed for internal workings. If you are use the Manage Rollup Summaries page exclusively you need not view or bother with the Lookup Rollup Summaries tab.
