### ISSUE TITLE
DLRS daily schedule limit exceeded 

### ISSUE THREAD

**Issue by nehawakchaure** [afawcett/declarative-lookup-rollup-summaries#885]
Hi,
We have to schedule 100+ dlrs a day, is it possible to exceed limit for a day? We have already exceeded limit of 100 per day.

**Comment by JimBTek** [comment]
I would recommend you look into the trigger based or process builder based
scheduled jobs to async update only records that have changed.

**Comment by nehawakchaure** [comment]
Hi, thanks for the sugession.

Could you please explain this process in brief?
1. In this case we do not need to create scheduler right? We just need to press calculate button using process builder
2. Could you help me in detail like how to write a process builder(like what should be object and and how to schedule lets say XYS dlrs in process builder) for this with any good example?

**Comment by afawcett** [comment]
Wow thats a lot of schedules. Are these full recalcs or incremental? See this wiki page ... https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups.
