### ISSUE TITLE
Is MyDomain required to use DLRS?

### ISSUE THREAD

**Issue by BobBailey** [afawcett/declarative-lookup-rollup-summaries#887]
I apologize if this is not the right place for this question or if the question has been answered. I have installed DLRS for three clients in the past and it has worked wonders for me. I'm about to install it for another client but before I do...

I seem to recall getting an error because the client was on LEX but did not have a Domain. Is this a problem. I have at least one client who will not add the domain. (Don't ask.)

Thanks for a great addition to Salesforce... Bob

**Comment by rogeramitchell** [comment]
Negative, you’re good to go.

**Comment by BobBailey** [comment]
Thanks.
