### ISSUE TITLE
DLRS not executing

### ISSUE THREAD

**Issue by dariadstepanova** [afawcett/declarative-lookup-rollup-summaries#888]
Hello!

I have two almost identical lookup summaries, and one is executing while the other isn't. The one that looks at "Invited" campaign members works; the one that looks at "Attended" campaign members never returns any data. Any idea why? 

<img width="868" alt="Screen Shot 2019-12-10 at 06 41 45" src="https://user-images.githubusercontent.com/58060555/70459003-290b6880-1b18-11ea-9cbd-f0109650a1f0.png">
<img width="876" alt="Screen Shot 2019-12-10 at 06 41 22" src="https://user-images.githubusercontent.com/58060555/70459027-3163a380-1b18-11ea-8585-91d8234ca4f9.png">

Thank you so much in advance for your help!

Best wishes,
Daria

**Comment by thirdsectorit** [comment]
Might be something to do with your aggregate result fields 🐙
