### ISSUE TITLE
Apex error

### ISSUE THREAD

**Issue by andysuciu** [afawcett/declarative-lookup-rollup-summaries#890]
Hello. I started receiving an email with some apex errors since 1-2 months now, usually is one per day but sometimes more.
Can you please help debug? I have the latest version of the app installed in SalesForce. Thank you!

Apex​ ​script​ ​unhandled​ ​trigger​ ​exception​ ​by​ ​user/organization:​ ​00520000005wX56/00D20000000oEls

dlrs_OpportunityTrigger:​ ​execution​ ​of​ ​AfterUpdate

caused​ ​by:​ ​dlrs.fflib_QueryFactory.InvalidFieldException:​ ​Invalid​ ​field​ ​'CreatedDate'​ ​for​ ​object​ ​'dlrs__LookupRollupSummary__c'

Class.dlrs.fflib_QueryFactory.getFieldPath:​ ​line​ ​91,​ ​column​ ​1
Class.dlrs.fflib_QueryFactory.addOrdering:​ ​line​ ​543,​ ​column​ ​1
Class.dlrs.fflib_SObjectSelector.configureQueryFactory:​ ​line​ ​389,​ ​column​ ​1
Class.dlrs.fflib_SObjectSelector.newQueryFactory:​ ​line​ ​273,​ ​column​ ​1
Class.dlrs.fflib_SObjectSelector.newQueryFactory:​ ​line​ ​255,​ ​column​ ​1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector:​ ​line​ ​165,​ ​column​ ​1
Class.dlrs.RollupSummariesSelector:​ ​line​ ​80,​ ​column​ ​1
Class.dlrs.RollupService:​ ​line​ ​1072,​ ​column​ ​1
Class.dlrs.RollupService:​ ​line​ ​753,​ ​column​ ​1
Class.dlrs.RollupService.triggerHandler:​ ​line​ ​311,​ ​column​ ​1
Trigger.dlrs_OpportunityTrigger:​ ​line​ ​7,​ ​column​ ​1

**Comment by afawcett** [comment]
Can you add some more information to this issue https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/873. Do you have any leads on when it occurs and/or what type of users? I will mark this as a duplicate for now, lets conrtinue over on the existing issue.

**Comment by andysuciu** [comment]
Hi Andrew,
I am not sure what triggers the occurrence, I only get it in the email about 1-2 times per day. If you want be to further debug, can you please lay down some steps?
Thanks, Andy

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dw&cv=10.0.3&pv=10.0&source=email_footer_2]
On Sat, Dec 28, 2019 at 3:44am, Andrew Fawcett < notifications@github.com [notifications@github.com] > wrote:Can you add some more information to this issue #873 [https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/873] . Do you have any leads on when it occurs and/or what type of users? I will mark this as a duplicate for now, lets conrtinue over on the existing issue.

**Comment by afawcett** [comment]
@andysuciu this is being tracked in detail here https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/873. Some good theories and possible fixes in the thread. 👍
