### ISSUE TITLE
Suggestion: Add 'Description' field to Lookup Rollup Summary SObject

### ISSUE THREAD

**Issue by cropredy** [afawcett/declarative-lookup-rollup-summaries#90]
Since a Lookup Rollup Summary record is functionally equivalent to a parent object RSF field, provide as part of the OOB package a `dlrs__description__c` field of type TextArea (long) so sysads can enter notes about _why_ the DLRS record was created as well as any maintenance notes, references to SDLC ids, etc.

I realize I can add my own custom description field (and did) but this would be a 'nice-to-have'.

**Comment by afawcett** [comment]
Fixed in v1.17
