### ISSUE TITLE
Roll up summary not calculating in realtime

### ISSUE THREAD

**Issue by PaulTest** [afawcett/declarative-lookup-rollup-summaries#900]
Hi Everyone, i have a simple Roll up that should take the Total amount of every order and roll it up on to a field on the opportunity. There is no criteria, just everytime a new order is added, roll up the amount. Unfortunately this is not working in real time. it works every time i press calculate though. it is active and the child trigger is deployed, any idea what i am doing wrong?

I have included a screenshot
![roll up error](https://user-images.githubusercontent.com/32731735/73160777-cc710680-40e1-11ea-999b-420550ccc5b3.JPG)

**Comment by subbuchunduri** [comment]
hi paul,
did your problem resolved.
