### ISSUE TITLE
The database save operation failed | organizationId: 00D58000000ZNNt 

### ISSUE THREAD

**Issue by Abhipsa86** [afawcett/declarative-lookup-rollup-summaries#901]
**Describe the bug**
dlrs package has been installed in Our Production Org , organizationId: 00D58000000ZNNt .
Currently we are facing an issue in Production  - Lightning Sync for Calendar event.
We have raised a salesforce case  and as per salesforce support analysis, multiple transaction failed in salesforce database because of the dlrs.RollupService.triggerHandler();
 No of failure occurences in 7 days: 271
Issue caused by Trigger Name : dlrs_EventTrigger

Seems like if user is updating any event series it fails because of multiple transaction

**To Reproduce**
Currently we don't have any step to reproduce this in Production.Seems like if user is updating any event series it is giving exception

**Expected behavior**

**Screenshots**

**Additional context**

.

**Comment by afawcett** [comment]
@Abhipsa86  i wonder if this is due to this platform restriction? https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/896

**Comment by afawcett** [comment]
@Abhipsa86 let me know your thoughts on the above suggestion. We can re-open this issue for sure.
