### ISSUE TITLE
InsurancePolicy object not supported by DLRS

### ISSUE THREAD

**Issue by sneha2390** [afawcett/declarative-lookup-rollup-summaries#902]
InsurancePolicy Object is not supported by the application, its new feature of salesforce and can be query after 42 API versions.
![Capture DLRS](https://user-images.githubusercontent.com/60588058/73618709-afa67700-467d-11ea-9dd6-2737c8f2f89f.JPG)

**Comment by afawcett** [comment]
@sneha2390 try this again with v2.12 just released, this is at v48.
