### ISSUE TITLE
Test failed and throwing Salesforce Internal Error with no stack trace. Any idea?

### ISSUE THREAD

**Issue by rahulmjn** [afawcett/declarative-lookup-rollup-summaries#906]
@IsTest
private class dlrs_ContentDocumentLinkTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_ContentDocumentLinkTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new ContentDocumentLink());
    }
}

**Comment by kryan0618** [comment]
I am encountering this issue, as well.

**Comment by afawcett** [comment]
Its worth being more expressive when talking about errors, such as giving the error itself. In this case though, salesforce internal errors can only be decoded by Salesforce Support. Meanwhile this might be a useful read through. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/433. Sorry I am not able to help on this one, even with the salesforce error id.
