### ISSUE TITLE
Support for Survey objects

### ISSUE THREAD

**Issue by DBub** [afawcett/declarative-lookup-rollup-summaries#907]
I created a DLRS to roll up SurveyResponse (child object) records to SurveyInvitation (parent object). These are standard objects that are part of the new(ish) [Surveys feature](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_salesforce_surveys_object_model.htm).

In the DLRS setup, when attempting to install the trigger & class from the "Manage Apex Trigger for SurveyResponse" page, I got the following error:

> Error:dlrs_SurveyResponseTest.testTrigger System.TypeException: DML operation INSERT not allowed on SurveyResponse Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_SurveyResponseTest.testTrigger: line 11, column 1

I think this has to do with what the new survey objects do and do not allow, since the records are added via the survey form UI.  I manually created the trigger and test class using the auto-generated code and named them according to the naming convention you use, then commented out the line from the test class where the insert happens.  This works and my rollup is working as expected.  I think it just means I won't have the code coverage for this(?) but I think I'll still be over the threshold.  But just letting you know in case the surveys feature can be supported in later versions of DLRS.

Thanks.

**Comment by renatoliveira** [comment]
I think it is not as if the tool doesn't support the new object, but rather the platform itself doesn't allow the insert of the object in Apex. A deployment of a trigger with both insert contexts work, but a insert statement doesn't.

This issue has also a [question on SFSE](https://salesforce.stackexchange.com/questions/262793/how-would-i-test-a-trigger-on-non-writable-surveyresponse-object) and a reply from Chris Peterson from the Apex team.

A possible workaround would be to make a change to the RollupController class to generate a specific test code for the rollup trigger on objects like this, surrounded in a try/catch block, maybe? 🤔

**Comment by afawcett** [comment]
@renatoliveira per update from Chris, this object simply does not support Apex Triggers, which is a big issue for realtime rollups. You can try scheduled rollups maybe? See Wiki in this repo for notes on scheduled rollups.
