### ISSUE TITLE
Simple Aggregate function not working

### ISSUE THREAD

**Issue by mickbroberts** [afawcett/declarative-lookup-rollup-summaries#908]
I installed the App successfully in my sandbox org and tested it was working. It was a simple rollup and all was OK 

I than installed in my Production system but when I tested it, it no longer worked.

The lookup summary rule simply takes a numeric formula field from the Child object and aggregates to the parent (Contact object).   However when you update the child object and the number is set to 1, the parent object still shows a zero instead of the expected 1.

I have checked the security in the fields, checked the logs to ensure the dlrs triggers are running, but still no joy.

So you have any suggestions to troubleshoot?

**Screenshots**

![DLRS Issue](https://user-images.githubusercontent.com/29703225/74148429-4c788f80-4bfd-11ea-880a-cc344eb64a95.jpg)

**Additional context**

**Comment by mickbroberts** [comment]
I just noticed that when I ran the calculate option, the rollup summary worked but it does not seem to work when I do an update

**Comment by mickbroberts** [comment]
I have just noticed , the aggregate only seems to work when the child field changes and not just on editing a child record.

**Comment by mickbroberts** [comment]
Maybe worth adding in the documentation

**Comment by afawcett** [comment]
@mickbroberts yes you need to list in the field relationship criteria fields field the fields you want to track for changes on the child record. I believe there is an enhancement to update this UI to make this more clear. Andy.
