### ISSUE TITLE
Spring '20 and now a test fails

### ISSUE THREAD

**Issue by mkolodner** [afawcett/declarative-lookup-rollup-summaries#910]
I've got a DLRS on ContentDocumentLink. It's been working fine for more than a year. Just got a test error, presumably because we're now on Spring '20.
dlrs_ContentDocumentLinkTest.testTrigger: Internal Salesforce Error: 981955442-23307 (842578630) (842578630)

**To Reproduce**
1. Go to Apex Tests
2. Run dlrs_ContentDocumentLinkTest
3. See error

**Expected behavior**
Test passed as of Friday 2/14 for sure. (I have an app that runs tests daily and emails me if any fail.)

**Comment by julies66** [comment]
I came across the same issue today.   Was working prior to Spring '20.  I had to deploy a change set and this error was blocking the deploy.  So I ended up having to remove the dlrs_ContentDocumentLinkTest.testTrigger in order to deploy.  And of course, can not redeploy this child trigger.

**Comment by kryan0618** [comment]
Just encountered this today. I am trying to deploy changes to production and it will not allow me due to this error.

**Comment by stepanvitecek** [comment]
I'm having the same problem, it's currently blocking our deployment. Seems that we will have to remove it temporarily or replace it with our own Triggers.

**Comment by kkorynta** [comment]
I think spring '20 made a new field required for the ContentDocumentLink object. I was able to resolve this by modifying the test class to the following:

```
@IsTest
private class dlrs_ContentDocumentLinkTest {

    @IsTest private static void testTrigger() {
        // Force the dlrs_ContentDocumentLinkTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new ContentDocumentLink(ShareType = 'C'));
    }
}
```
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentdocumentlink.htm

**Comment by kryan0618** [comment]
Thank you! I will try that. I ended up deleting the rollup summary so I could deploy my change sets. But when I'm done, I will try what you have suggested.

Thanks!!

**Comment by julies66** [comment]
AWESOME!  You just resolved what became a major headache for us.  This solution worked.

**Comment by stepanvitecek** [comment]
Great job @kkorynta! Seems like it has fixed the problem :-)

**Comment by afawcett** [comment]
This snippet can be used on the rollup definition to customize the test code.

``
dlrs.RollupService.testHandler(new ContentDocumentLink(ShareType = 'C'));
``
