### ISSUE TITLE
IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://sofacto--data--dlrs.cs101.visual.force.com/services/Soap/m/34.0

### ISSUE THREAD

**Issue by cshiwani** [afawcett/declarative-lookup-rollup-summaries#911]
**Describe the bug**
When clicking on button : 'Manage child trigger' in Lookup Rollup Summary the error is coming : 

Unable to connect to the Salesforce Metadata API.
A Remote Site Setting must be created in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

I added Remote site setting manually with the org url : https://sofacto--data--dlrs.cs101.visual.force.com

then also the new error is coming: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

I tired the step of unchecking : Lock sessions to the IP address from which they originated in session setting

but it is also not resolving the issue 

Also I checked critical update : Remove Instance Names From URLs for Visualforce, Experience Builder, Site.com Studio, and Content Files
this is also deactivated in org

**Expected behavior**
remote site setting should be created own its own

**Screenshots**
![Screenshot 2020-02-18 at 13 41 47](https://user-images.githubusercontent.com/61191430/74737253-bf64b480-5254-11ea-87f0-1d371fd4979a.png)
![Screenshot 2020-02-18 at 13 44 34](https://user-images.githubusercontent.com/61191430/74737283-d4414800-5254-11ea-8c39-ed753473f698.png)

**Additional context**
Please update as soon as possible , this issue is in production org as well and is stopping the business.

**Comment by cshiwani** [comment]
Team, I hope you got time to review this issue, After logging out and logging in I was able to fix the issue by unchecking "Lock sessions to the IP address from which they originated in session setting"

However I would like to know why this error came all of the sudden as earlier it was working fine with this permission as well?
Also I would like to know if it the only solution to uncheck this permission,  what will be the solution if we want to keep this permission.

**Comment by afawcett** [comment]
@cshiwani in the latest release i used a new platform feature that avoids the need for remote site setting (if you have my domain enabled, which it looks like you do?). If so please retry with the latest version of the package (see README release notes).
