### ISSUE TITLE
Date fields not rolling up...

### ISSUE THREAD

**Issue by pdrewer** [afawcett/declarative-lookup-rollup-summaries#913]
I have a managed summary that doesn't provide the most recent "admit date."

I'm not sure why it is happening. I'm new to the company and it was set up by a previous implementation partner. I'm not sure what is causing the issue. Can someone help! 

![image](https://user-images.githubusercontent.com/57507988/75284085-1254e380-57e2-11ea-9c2d-f1d97748012e.png)

**Comment by afawcett** [comment]
@pdrewer welcome to the tool. I would suggest you drop a note with as much info as you can in the chatter community group (see link in the readmme for this repo). Please try to help others help you with as much info as you can, screenshot of the rollup definition (check either Manage Rollup Summaries or Lookup Rollup Summaries tabs for rollups referencing these objects and fields). Also include a list of steps you are doing to update the records and your expected results. Thanks!
