### ISSUE TITLE
Relationship Criteria  Field error help

### ISSUE THREAD

**Issue by nelle3223** [afawcett/declarative-lookup-rollup-summaries#914]
(checkbox field) Original_Snapshot__c = TRUE & (Date field) OED__c >/ 1/1/2020 & (Date field) OED__c < 1/1/2021 &  (Formula Field) Line_of_Coverage__c = "Medical"

If someone could help to see what I need to change that would be great.  Thanks!

**Comment by afawcett** [comment]
@nelle3223 its just not clear from your very short explanation what you issue is? Error message? Or screenshot? Its worth posting on the chatter community group (with more additional info) linked on the README file of this repo. The community is strong with this tool, but please help them help you with more background and explanations. Thank you! 👍
