### ISSUE TITLE
Rollup field not updating correctly

### ISSUE THREAD

**Issue by kaldrich** [afawcett/declarative-lookup-rollup-summaries#915]
One of our dlrs rollup fields is not consistently updating accurately and I'm not sure why. We have a rollup field on the Account record that is working well to pull the membership $ amount field from the last opportunity (most recent close date) with record type of membership. We have a similar rollup field on the contact record but that one is not populating the same data as the field on the account. Below are the details on the rollup field. Am I missing something? Can I grant login access for someone to help me out?

Lookup Rollup Summary Name: Membership Dues - Contact
Lookup Rollup Summary Unique Name: Membership_Dues_Contact

Parent Object: Contact
Relationship Field: npsp__Primary_Contact__c
Child Object: Opportunity
Relationship Criteria: iswon = TRUE AND dlrs_Membership_Amount__c > 0 AND npe01__Member_Level__c != NULL
Relationship Criteria Fields: npe01__Member_Level__c; iswon; dlrs_Membership_Amount__c

Field to Aggregate: dlrs_Membership_Amount__c
Active: TRUE
Field to Order By: CloseDate
Calculation Mode: REAL TIME
Aggregate Operation: LAST
Calculation Sharing Mode: SYSTEM
Aggregate Result Field:	dlrs_Last_Membership_Dues_Amount__c
Aggregate All Rows: FALSE

**Comment by afawcett** [comment]
@kaldrich This looks good to me tbh. Can you include the other one for comparison?

**Comment by kaldrich** [comment]
Thanks for looking at this @afawcett! Here's the similar rollup field from the Account object for comparison:
Lookup Rollup Summary Name: Last Membership Dues Amount - Account
Lookup Rollup Summary Unique Name: Last_Membership_Dues_Amount_Account

Parent Object: Account
Child Object: Opportunity
Relationship Field: AccountId
Relationship Criteria: iswon = TRUE AND dlrs_Membership_Amount__c > 0 AND npe01__Member_Level__c != NULL
Relationship Criteria Fields: npe01__Member_Level__c; iswon; dlrs_Membership_Amount__c

Field to aggregate: dlrs_Membership_Amount__c
Active: TRUE
Field to Order by: CloseDate
Calculation Mode: Realtime
Aggregate operation: Last
Calculation Sharing Mode: System
Aggregate Result Field: dlrs_Last_Membership_Dues_Amount__c
Aggregate All Rows: FALSE

**Comment by samlimster** [comment]
Thanks for the response.

To be more clear.  what if the Field to aggregate was actually a look up
field. e.g. it was the Primary Contact of the opportunity and I wanted to
aggregate their Last Name

Thanks!

Sam.

**Comment by kaldrich** [comment]
Hi @samlimster! In both the Account and Contact, the Field to aggregate is a custom field and not a lookup.

**Comment by afawcett** [comment]
@samlimster Honestly I cannot spot the issue sorry. I think it might be worth reposting this on the Community Chatter Group (see README) and see if some others can spot whats going on. Sorry.
