### ISSUE TITLE
Error:Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Opportunity: (dlrs)

### ISSUE THREAD

**Issue by mhakikat** [afawcett/declarative-lookup-rollup-summaries#916]
Parent Object | Account                                Relationship Field | AccountId

Child Object | Opportunity                            Relationship Criteria  
                                                                            STAGENAME='7-Closed Won' 
                                                                               AND ((Service_Start_Date__c <=Today )OR ( 
                                                                                 Service_start_date__c< NEXT_N_DAYS:90)) AND 
                                                                                 SERVICE_END_DATE__C >= Today
                                                                         
                                                               Relationship Criteria Fields  
                                                                   StageNameService_Start_Date__cService_End_Date__c

Field to Aggregate | Actual_Opportunity_Value__c                     Active  True

                                                                                                         Calculation Mode | Realtime
Aggregate Operation  Sum                                                           Calculation Sharing Mode | User
Aggregate Result Field  Total_Contract_This_term__c

**Comment by mhakikat** [comment]
Hi,
I am using AccounId as a relationship field but still getting this error.any suggestion?

**Comment by afawcett** [comment]
@mhakikat  have you reviewed https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/768 and https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/409? Note that there maybe more than one rollup not using AccountId.

**Comment by afawcett** [comment]
@mhakikat let me know if you need further help and we can re-open this. 👍
