### ISSUE TITLE
Deploy new rollup

### ISSUE THREAD

**Issue by joanlui-ws** [afawcett/declarative-lookup-rollup-summaries#917]
Created a rollup in Sandbox, click [Manager Child Trigger], instead of [Deploy] & [Cancel] buttons, I get [Removed] & [Cancel] buttons. Is the rollup not ready for deployment?

**Comment by afawcett** [comment]
Triggers are deployed against the Child Object you specify on the rollup definition. So it looks like you already have another rollup using that Child Object (which is fine btw) and someone already deployed the trigger via that rollup. In short. All good!
