### ISSUE TITLE
Errors on Installation

### ISSUE THREAD

**Issue by aclavin298** [afawcett/declarative-lookup-rollup-summaries#920]
Getting two errors trying to deploy Apex Trigger for CampaignMember

1. dlrs_CampaignMemberTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: MALFORMED_ID, Invalid campaign id: null: [CampaignId] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_CampaignMemberTest.testTrigger: line 11, column 1

2. dlrs_CampaignMemberTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

**Comment by afawcett** [comment]
Hiya, take a look through this issue for test code to use to avoid this. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197
