### ISSUE TITLE
Unable to deploy trigger for DLRS

### ISSUE THREAD

**Issue by situdubey** [afawcett/declarative-lookup-rollup-summaries#923]
I am trying to deploy Trigger but facing an issue:

- classes/dlrs_ContractTest.cls (Line: 11: Column:28) : Method does not exist or incorrect signature: void testHandler(Contract) from the type dlrs.RollupService

- triggers/dlrs_ContractTrigger.trigger (Line: 7: Column:48) : Variable does not exist: SObjectType

Please refer the attachment for the same.

![image](https://user-images.githubusercontent.com/62977988/78233301-24b5f180-74f3-11ea-9bde-7c9d2da3c68d.png)

This is the configuration which I have done :

![image](https://user-images.githubusercontent.com/62977988/78233775-df45f400-74f3-11ea-8146-322ff999611d.png)

**Comment by afawcett** [comment]
@situdubey do you have the package installed for this tool or have you deployed the code direct from this repo into your org?

**Comment by situdubey** [comment]
> @situdubey do you have the package installed for this tool or have you deployed the code direct from this repo into your org?

I have installed the Package ..!! @afawcett 

![image](https://user-images.githubusercontent.com/62977988/78420344-ce1ff300-766b-11ea-974b-ef8e288eac43.png)

**Comment by afawcett** [comment]
@situdubey I see that this is now being tracked as a discussion in the chatter community group. Thank you and I will go ahead and close this issue out to avoid duplication.
