### ISSUE TITLE
Unable to deploy child trigger on Address Object

### ISSUE THREAD

**Issue by BHFoundation** [afawcett/declarative-lookup-rollup-summaries#924]
I keep receiving the following error:

Error:
dlrs_npsp_AddressTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, To use Addresses with non-Household Accounts, you must select Organizational Account Addresses Enabled in NPSP Settings | People | Addresses.: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_npsp_AddressTest.testTrigger: line 11, column 1

See below for NPSP Address Settings:

![image](https://user-images.githubusercontent.com/31489994/78385694-e3c8e600-75a1-11ea-9e42-6038e36e3f37.png)

**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

**Comment by afawcett** [comment]
@BHFoundation the test code needs to either enable this setting progmatically or you can have the test see all data (not best practice) by checking that field on the rollup definition. This later option assumes the org has the setting enabled. To read up more have a look through this https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage hope this helps!
