### ISSUE TITLE
Lookup is not working on realtime

### ISSUE THREAD

**Issue by kmadolli** [afawcett/declarative-lookup-rollup-summaries#927]
I have created Rollup summary on Campaign with Campaign member field. This is not working on realtime. Can anybody suggest solution on how to achieve this.

How to run Lookup Rollup Summary using process builder.

**Comment by afawcett** [comment]
@kmadolli you really need to provide more information to get the best responses from the community. For example what does your rollup definition look like? What is your prefered steps and expected result and what are you seeing instead. It may take you more time to explain and capture all this, but in the end you will get a better response as those reviewing will be more informed. It is also worth focusing on one issue at a time, you appear to be asking two questions above, which also leads to confusion. Hope this guidance helps. Lastly I would recommend (per the guidelines when raising issues here) that you do in-fact use the chatter community group to pose questions like this when there is no clear enhancement or bug to be described.
