### ISSUE TITLE
Has anyone used dlrs for a Federal Agency ?

### ISSUE THREAD

**Issue by arorard** [afawcett/declarative-lookup-rollup-summaries#932]
This is a question, not an issue.
Has anyone used dlrs for a Federal agency which usually requires products to be "FedRamp" approved? If yes, was it implemented as Managed or unmanaged form?

thanks in advance!

**Comment by afawcett** [comment]
@arorard per instructions when raising this issue, best to ask these kind of questions on the community chatter group (see link on the README).
