### ISSUE TITLE
Salesforce critical update: Restrict Access to @AuraEnabled Apex Methods for Authenticated Users Based on User Profile

### ISSUE THREAD

**Issue by scaracand** [afawcett/declarative-lookup-rollup-summaries#934]
Salesforce intends to release a critical update to Apex classes containing an @AuraEnabled method so that an authenticated user can access an @AuraEnabled Apex method only when the user’s profile allows access to the Apex class. In Winter ‘21, Salesforce will automatically activate the critical update for all orgs. This critical update enforces user profile restrictions for Apex classes used by Aura and Lightning web components. Authenticated users will need to have permission in their profiles or permission sets to access an Apex class. Aura or Lightning web components that call @AuraEnabled methods contained in these Apex classes may fail to load or operate correctly.

Is DLRS compatible with the upcoming security update?

**Comment by afawcett** [comment]
This won't effect rollup calcs or defining a rollup (thats using Visualforce). But it may effect the new Rollup Summary Tools tab I added in the latest release (see README for a blog on what this is). Is there an org you can use to help test for us?

**Comment by scaracand** [comment]
Thanks Andy. We are still on 2.11 (no Rollup Summary Tools tab) and don't intend to upgrade unless there is a security or other critical improvement. 
We are running a heavily-customized Enterprise Edition org + Pardot and a few integrations. Once we enable the @AuraEnabled security update I will be happy to share results from our org. Fingers crossed!
