### ISSUE TITLE
Enhanced Edit Limit Error

### ISSUE THREAD

**Issue by JoaquinMerlino** [afawcett/declarative-lookup-rollup-summaries#935]
Hi!

I've just upgraded the DLRS to version 2.12 in a sandbox environemnt. When inside a DLR Summary record, I click on **Enhanced Edit** and I get a VF Page error saying **Collection size 1,188 exceeds maximum size of 1,000.** Don't have VF coding experience so I'm at a loss at what I should be looking for here.

**To Reproduce**
1. Go to any **Lookup Rollup Summary record**
2. Click on **Enhanced Edit**
3. Wait for the page to load
4. See error **Collection size 1,188 exceeds maximum size of 1,000.**

**Expected behavior**
Haven't used this functionality in the past so don't know what should be happening now, but clearly not this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/19696403/79379313-1de89f00-7f35-11ea-8260-93b098b4d0e5.png)

**Comment by afawcett** [comment]
Do you have more than 1000 objects in your org by any chance?

**Comment by afawcett** [comment]
You don't have to use the Enhanced Edit btw, you can just edit the record directly. You will have to know the correct API names for parent, child and field names etc. But that is a workaround. You should also consider using the Manage Rollup Summaries tab to define rollups this uses Custom Metadata and helps when moving definitions around between Sandbox to Production. See the README file for a blog on this. Thanks.

**Comment by JoaquinMerlino** [comment]
Hi Andrew,

Yeah we have over that if I'm not mistaken. We have a few managed packages that come with lots of objects in them and some old ones that might be no longer in use. 
Didn't know that about the Manage Rollup Summaries tab, I'll go over the README file to get more acquainted with it.
Thanks for the help! Closing this issue now :)
