### ISSUE TITLE
Apex resource warnings

### ISSUE THREAD

**Issue by LawranceT** [afawcett/declarative-lookup-rollup-summaries#937]
I have a single DLRS Summary running.  I have recently been receiving the error message email below which appears to be related to DLRS.  Can anyone shed any light on what might be causing this?  Thanks in advance.

Operation: /flow/interview.apexp

By user/organization: 0054H000004vr1d/00D58000000c4kR

Caused the following Apex resource warnings:

Number of DML statements: 151 out of 150
dlrs:Number of SOQL queries: 100 out of 100

**Comment by rogeramitchell** [comment]
@LawranceT it looks like there is either non-bulkified code or some recursive update that is occurring in your org. Are you able to share the limits for any other managed/unmanaged code that is running?

**Comment by LawranceT** [comment]
@rogeramitchell Thanks for the swift response Roger.  I'm not a developer so not sure if I can respond to your request 'Are you able to share the limits for any other managed/unmanaged code that is running?'.  We do not have any bespoke triggers running apart from those that come with standard managed packages such as NPSP.  I have several process builders and flows running.  Do you if it is possible to see what processes are causing this?

**Comment by rogeramitchell** [comment]
@LawranceT based on what you shared in the first post, it looks like the exception occurred based on something that was being done inside a flow.

Are you able to go to the DLRS, click "Full Calculate" (and on next page, "Run Full Calculate Job"), and see that the DLRS is calculating the rollup successfully?

**Comment by LawranceT** [comment]
@rogeramitchell Everything is working fine.  I had a couple of error message emails come through, but none in the last 24 hrs.  I think I'll need to monitor this and see if I can trace what happened at the time if / when the next email comes through.
