### ISSUE TITLE
Multiple Salesforce critical updates

### ISSUE THREAD

**Issue by scaracand** [afawcett/declarative-lookup-rollup-summaries#938]
Salesforce is releasing a number of critical updates that will gradually be automatically activated for all orgs. Is DLRS compatible with the upcoming security updates? Here is the list: 

1. Disable Access to Non-global Controller Methods in Managed Packages
>> https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_lc_apex_methods_packages_cruc.htm
2. Enforce Access Modifiers on Apex Properties in Lightning Component Markup
>> https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_lc_enforce_prop_modifiers_cruc.htm
3. Enable ICU Locale Formats
>> https://help.salesforce.com/articleView?id=icu_migration_how.htm&type=5
4. Prevent Creation of Function Expressions When Using $A.createComponent() or $A.createComponents() in Aura Components
>> https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_aura_expr_dynamic_cmp_cruc.htm
5. Restrict Reflective Access to Non-Global Controller Constructors in Packages
>> https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_apex_publicConstructorsInMgdPackages.htm
6. Enable Dependency Access Checks in Lightning Components
>> https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_lc_dependency_access_checks_cruc.htm
7. Restrict Access to @AuraEnabled Apex Methods for Authenticated Users Based on User Profile
>> https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_lc_restrict_apex_authenticated_users.htm -- already under discussion in issue #934

**Comment by afawcett** [comment]
@scaracand thanks so much listing these updates out so easily! All good!

RE: 1 - not applicable - there is no reason for installations to attempt to access the packages controllers in this way
RE: 2 - no impact - tool has minimal lightning web components and no private accessors are used
RE: 3 - not applicable - no parsing of date formats in the tool
RE: 4 - not applicable - this is not used in the package
RE: 5 - not applicable - there has been no need for this type of use case when using this package
RE: 6 - not applicable - this tool does not utilize this aura component use case
RE: 7 - not applicable - this tool does not utilize this aura component use case
