### ISSUE TITLE
"Apex Trigger .. has not been deployed"; too restrictive for dev-to-stage-to-prod workflow

### ISSUE THREAD

**Issue by cropredy** [afawcett/declarative-lookup-rollup-summaries#94]
Here's our deployment model:
1. Create LRS entry in Dev; click Manage Child Trigger (trigger deployed into Dev); click LRS active checkbox
2. Use ANT to push changed apex from Dev to Stage sandbox. This includes the dlrs__xxx trigger/test class created in #1 
3. Go to Stage sandbox, create a LRS to match the one in Dev
4. Click Active checkbox on Stage LRS record

Oops - won't work as DLRS returns this error:
**Error: Apex Trigger dlrs_xxxTrigger has not been deployed. Click Manage Child Trigger and try again.**

*where xxx is the name of the child object*

But the trigger/test class **are deployed**, but not via DLRS, but via the Ant build

The only way around this is to delete (or never include in the ant build) the trigger/test class and then deploy via the Manage Child Trigger button in Stage sandbox (and PROD)

So, suggestion(s):
1. Update the doc to tell users not to do this (probably under a section organized by error message) or ..
2. When clicking 'Active' checkbox on LRS page, if the trigger/test class are already present, use them, or, if this is not possible, tell the user that they were found but not deployed via Manage Child Trigger and must be removed.

**Comment by cropredy** [comment]
OK, here is some more info but not exactly what you asked for as I can't give you access to these orgs

1. We are running a Deployment Validation using ANT into our Production org

2. We have a test class that runs as @isTest V31 to test a class that mocks DLRS rows. That is, we know the trigger already exists because it was deployed as metadata a sprint release ago but since I don't like to have testmethods that are SeeAllData=true, I wrote a utility method to mock the DLRS row for those tests that require a DLRS to be present. 

3. The testmethod that tests the DLRS mocking runs fine in dev and stage sandboxes; but when it runs (via a PROD validation), it fails with the message below where I am using an upsert to (insert) a mock DLRS row.

4. FIELD_CUSTOM_VALIDATION_EXCEPTION, Apex Trigger dlrs_Agreement_Line_ItemTrigger has not been deployed. Click Manage Child Trigger and try again.: [dlrs__Active__c]
    (dlrs__LookupRollupSummary__c:{Name=ProductLineItemCount, dlrs__ChildObject__c=Agreement_Line_Item__c, dlrs__RelationshipField__c=ContractID__c, dlrs__ParentObject__c=Contract, dlrs__AggregateOperation__c=Count, dlrs__RelationshipCriteria__c=	line_item_type__c IN ('Content Product Line Item','Product Line item'), dlrs__RelationshipCriteriaFields__c=line_item_type__c, dlrs__Active__c=true, dlrs__FieldToAggregate__c=CreatedDate, dlrs__CalculationMode__c=Realtime, 

dlrs Stack Trace
class.UtilityFns.mockDLRS: line 932, column 1 
Class.TestUtilityFns.testMockDlrsNoOrgData: line 351, column 1

5. The trigger does exist in PROD - see attached image:
![image](https://cloud.githubusercontent.com/assets/2321266/5713767/95208fca-9a74-11e4-81e5-5fa421742fd5.png)

6.  We're at V14 of DLRS in PROD; deploying user has System Administrator profile and access to all DLRS sobjects

7. In PROD, if I click Manage Child Trigger for the DLRS in question, I get expected Info message:
![image](https://cloud.githubusercontent.com/assets/2321266/5713874/e8ef2700-9a75-11e4-80d4-f52c16fa825a.png)

8. The mocking is done via simple setup (some bits omitted for clarity)

```
Map<String,dlrs__LookupRollupSummary__c>	dlrsNameToMockDlrsMap	= new Map<String,dlrs__LookupRollupSummary__c> {
'productlineitemcount' =>new dlrs__LookupRollupSummary__c(	
   name = 'ProductLineItemCount',																		
   dlrs__Active__c = true,																		
   dlrs__AggregateOperation__c			= 'Count',																					
   dlrs__AggregateResultField__c		= 'Product_Line_Item_Count_rsf__c',
   dlrs__CalculationMode__c			= 'Realtime',																
   dlrs__ChildObject__c				= 'Agreement_Line_Item__c',																					
   dlrs__FieldToAggregate__c			= 'CreatedDate',																					
   dlrs__ParentObject__c				= 'Contract',																					
   dlrs__RelationshipCriteriaFields__c	= 'line_item_type__c',																					
   dlrs__RelationshipCriteria__c		= '	line_item_type__c IN (\'Content Product Line Item\',\'Product Line item\')',																					
   dlrs__RelationshipField__c			= 'ContractID__c') };

upsert dlrsNameToDlrsMap.values();
```

So, I'm baffled -- the trigger exists in all envs, the testclass exists in all envs, but when we try to mock a DLRS row via a testmethod with seeAllData=false, we get the error in #4 above - but only in PROD now

**Comment by afawcett** [comment]
Are you stilling getting this issue with your DLRS test?

Have you got the latest release?

**Comment by afawcett** [comment]
Also can you try to do upsert the DLRS records one by one, instread of in bulk as your doing via upsert dlrsNameToDlrsMap.values();

**Comment by afawcett** [comment]
@cropredy Sorry this one is dragging, any thoughts on my latest questions?

**Comment by vadkinson** [comment]
Hi Andy -
We are having a similar issue to this one with our Salesforce instance and were hoping to get your help.  When we try to activate a DLRS from the Lead to the Task objects, we get an error message stating: Apex Trigger dlrs_TaskTrigger has not been deployed. Click Manage Child Trigger and try again.  However, from the Manage Child Trigger, screen, the screen indicates that the trigger has already been deployed.  
We're having a another, seemingly unrelated, issue deploying a Contact to Campaign Member rollup.  The error message that we receive references the MailChimp Subscribers object (see screenshot below) and we're trying to understand the connection:
![screen shot 2015-05-06 at 2 18 49 pm](https://cloud.githubusercontent.com/assets/12283073/7505182/3427e408-f405-11e4-822c-cdc1321c3a80.png)

Please let us know if you can help us troubleshoot these issues.  Much appreciated!

**Comment by afawcett** [comment]
Sorry for the late reply, i've been on holiday.

Can you include a screenshot of the Lead to Task trigger activation error as well please?

Also if you run MCSubscriberTest test via the standard Salesforce Setup or Developer Console UI does give the same error?

**Comment by DanielleLutsky** [comment]
Hi Andrew.  Victoria and I work together - we resolved the first issue that she sent over, but now were running into a different issue.  We love the app, so hopefully this can be resolved.

Our client is using the nonprofit starter pack and trying to convert a lead to a contact that already exists.  They're getting a DLRS error.

![screen shot 2015-06-04 at 3 12 35 pm](https://cloud.githubusercontent.com/assets/12752361/7992322/88725290-0acc-11e5-8b1d-05eb22547d36.png)

**Comment by afawcett** [comment]
Hmmm i thing there is something special about Leads and Tasks around this tool, i've seen a few other issues crop up recently. Can you send me a screen shot of the rollup/s you have, i'd like to try and replicate. Also the steps your doing to get to the above screen, as i am not a big CRM app expert.

**Comment by DanielleLutsky** [comment]
Here's a screen shot:


Were just creating a lead; clicking convert which brings you to the lead
conversion page, then clicking convert again, and we get the dlrs error.

I want this to work so badly, we need it for so many of our analytics. Your
help is so appreciated!



Danielle Lutsky

Director of Consulting

danielle@yurgoskyconsulting.com

**Comment by afawcett** [comment]
Wow this is a complex setup, any chance i can login via Subscriber Support and grab a debug log? If you r ok to set this for the next few days, and tell me which Lead to click Convert on, i'll see what i can see from the Debug Log.

**Comment by DanielleLutsky** [comment]
I just granted you log in access.
I cant activate these until the evening when everyone is logged off.. we'll
have to coordinate.  Can you email me personally to set something up?

Im not sure its the complexity of the org thats affectng things; its
happening in many orgs around the new lead conversion page on the nonprofit
starter pack.

Danielle Lutsky

Director of Consulting

danielle@yurgoskyconsulting.com

**Comment by afawcett** [comment]
I've recently written up some shared details on the [code coverage](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) issue described in this case, please check the details here and comment at the bottom of the wiki page.

**Comment by DanielleLutsky** [comment]
Thank you andrew!  I'll check this out!

Danielle Lutsky

Director of Consulting

danielle@yurgoskyconsulting.com

office: (718) 392-3085

cell: (917) 438-8553


Please note that I will be out of the office from June 27-30th, and July
28-August 11th.

**Comment by afawcett** [comment]
Thanks, i've been reviewing this issue and its morphed several times from one issue to another, so i am going to close it now. Would you mind opening a new issue if you do happen to still have a problem. Thanks and appreciated.
