### ISSUE TITLE
Cannot deploy child trigger

### ISSUE THREAD

**Issue by BMJSKS** [afawcett/declarative-lookup-rollup-summaries#940]
Hi

Trying to deploy the child trigger, but I am getting an error:

Error:
dlrs_Krow_Timesheet_SplitTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Split can not saved without date.: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_Krow_Timesheet_SplitTest.testTrigger: line 11, column 1

Warning:
dlrs_Krow_Timesheet_SplitTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

I have already tried turning off all the validation on the child object, but the error still occurs.  Any help would be appreciated, thanks.

**Comment by afawcett** [comment]
@BMJSKS you need to resolve the validation rule in the test code - disabling the validation is a temp workaround really - but if you want to try just look for the validation rule that outputs the error 'Split can not saved without date' and disable it. If you want a more perminant and robust fix you will need a developer to ensure the test child record created in the test code satisfies this validation rule (at a guess seems a date field needs to be populated?). See here for more https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage
