### ISSUE TITLE
Count of Completed Events on Opportunity

### ISSUE THREAD

**Issue by Speedfreak99** [afawcett/declarative-lookup-rollup-summaries#943]
Hi,
I have tried this using the lookup summary with a criteria of ActivityDate < TODAY and also the same thing with the End date of an event < TODAY but its not calculating the number of completed activities on an opportunity
I have used Opportunity as my Parent and Event as my Child Object with WhatID as the link and ID as the count field.
Is this a limitation of what have I missed

**Comment by afawcett** [comment]
If your trying to do this with a Realtime rollup then yes - what your missing is the fact that realtime mode needs to see an actual change to the record - in your case you are just monitoring the passage of time - to address this view these options - https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups
