### ISSUE TITLE
Realtime recalculation not working after a Flow inserts a record 

### ISSUE THREAD

**Issue by petermoustrides** [afawcett/declarative-lookup-rollup-summaries#945]
We have a rollup summary that is working in realtime, but does not calculate when the record is created by a Flow.

Version 2.12 is installed in the org.

**Comment by petermoustrides** [comment]
I was able to get around this by creating an InvocableMethod and use RollupService.runJobToCalculate for the LookupRollupSummary.

**Comment by afawcett** [comment]
@petermoustrides thanks for the update
