### ISSUE TITLE
System.NullPointerException: Attempt to de-reference a null object - Error - Post v1.14 Upgrade

### ISSUE THREAD

**Issue by eggletm** [afawcett/declarative-lookup-rollup-summaries#95]
Hi
We were suffering with the "DLRs falling out of Sync" issue and upgraded yesterday to v1.14 to see if that would resolve the issue, however, since upgrading we have been receiving the following error:
System.NullPointerException: Attempt to de-reference a null object

I have switched on debugging and here is the relevant section.

Any help, pointers or tips gratefully accepted.
Thanks

Debug Log Extract
12:02:00.226 (226149094)|ENTERING_MANAGED_PKG|dlrs
12:02:00.258 (258143043)|SOQL_EXECUTE_BEGIN|[76]|Aggregations:0|select Name,dlrs__Active__c,dlrs__AggregateOperation__c,dlrs__AggregateResultField__c,dlrs__CalculationMode__c,dlrs__ChildObject__c,dlrs__FieldToAggregate__c,dlrs__ParentObject__c,dlrs__RelationshipCriteria__c,dlrs__RelationshipCriteriaFields__c,dlrs__RelationshipField__c,dlrs__CalculateJobId__c,CurrencyIsoCode from dlrs__LookupRollupSummary__c where CalculationMode__c in :calculationModeNames and ChildObject__c in :childObjectNames and Active__c = true order by ParentObject__c, RelationshipField__c
12:02:00.266 (266120257)|SOQL_EXECUTE_END|[76]|Rows:6
12:02:00.406 (406530765)|SOQL_EXECUTE_BEGIN|[145]|Aggregations:0|SELECT pse__Project__c, Sum(RRV__c) lre0, Sum(RRV__c) lre1, Max(pse__Project__r.CurrencyIsoCode) mastercc FROM pse__Resource_Request__c WHERE pse__Project__c in :masterIds  GROUP BY pse__Project__c
12:02:00.416 (416704017)|SOQL_EXECUTE_END|[145]|Rows:1
12:02:00.418 (418115482)|SOQL_EXECUTE_BEGIN|[60]|Aggregations:0|select IsoCode, ConversionRate from CurrencyType 
12:02:00.419 (419777112)|SOQL_EXECUTE_END|[60]|Rows:28
12:02:00.425 (425133289)|METHOD_EXIT|[7]|01pw0000001zm9N|dlrs.RollupService.triggerHandler()
12:02:00.425 (425336695)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object
(dlrs)
Trigger.dlrs_pse_Resource_RequestTrigger: line 7, column 1
12:02:00.425 (425363379)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object
(dlrs)
Trigger.dlrs_pse_Resource_RequestTrigger: line 7, column 1

**Comment by eggletm** [comment]
Hi Andrew
Apologies for delay in response.
The issue appear to have gone away - we have not had any roll ups falling out of sync since mid-December.

As a belt and braces approach I did set up nightly scheduled runs of the Roll Up batch, which may have "fixed" or at least masked the issue.

With my overnight batch I am getting an error in the Apex Jobs list, see below:

26/01/2015 02:00	Batch Apex	Completed	First error: Invalid Id for pse__Milestone__c	27	27	27	Eggleton, Martin	26/01/2015 02:02	RollupJob

I am still very happy to have a call if that would be the best way forward. let me know.
Thanks once again.
Martin

**Comment by afawcett** [comment]
Fixed in v1.17.

**Comment by eggletm** [comment]
Thank you!
