### ISSUE TITLE
criteria for the parent record

### ISSUE THREAD

**Issue by stephanielitus** [afawcett/declarative-lookup-rollup-summaries#952]
**Is your feature request related to a problem? Please describe.**
I have a target field on the parent that is updated in multiple ways based on the record type.  Some record types should be updated by a DLRS record, and some record types should be updated by a workflow rule.

With both the DLRS record and the workflow rule existing at the same time, the DLRS record is writing over the results of the workflow rule.

**Describe the solution you'd like**
I would like for a DLRS record to update only some parent records meeting certain criteria.  For parent records meeting other criteria, these values would be updated in a different way.

**Comment by afawcett** [comment]
Thanks @stephanielitus - the master records do not actually get queried by the tool - but you can achieve this by adding a formula field on the child record to expose the parent record type and then include that in your relationship criteria. 👍
