### ISSUE TITLE
Avoiding Duplicates in Sum Rollups

### ISSUE THREAD

**Issue by Carlos3732** [afawcett/declarative-lookup-rollup-summaries#953]
We have many cases where there is overlap in our child objects which we do not wish to double count when rolling up.

For example:

Child Account A: region 1 & region 2
Child Account B: region 2 & region 3

If we roll up to the parent account of these two accounts, the data from region 2 will be double counted.

Is there any workaround for this?

Thanks!

**Comment by afawcett** [comment]
@Carlos3732  this is indeed an interesting problem - i think its best you use the community chatter group to ask this question of folks that have more experience implementing different scenarios. You can find the link to the group in the README.
