### ISSUE TITLE
Rollup Schedule Job Error: Already Executing

### ISSUE THREAD

**Issue by Martinch713** [afawcett/declarative-lookup-rollup-summaries#955]
**Describe the bug**
I am receiving errors for almost all, if not all, of my scheduled rollups saying it is already running.

"Error: A calculate job for rollup '[Rollup Name]' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again. Review the error, rollup definition and/or delete the Apex Scheduled job under Setup. Check if the rollup still exists via the Manage Rollup Summaries and/or Lookup Rollup Summaries tabs."

**To Reproduce**
1. Go to Lookup Rollup Summaries
2. Create Lookup Rollup Summary in Scheduled calculate mode
3. Schedule Calculate for early morning (between 3-7am ET; I haven't tried later in the day)

**Expected behavior**
The jobs should run without producing an error that they're already running.

**Additional context**
I have already deleted the scheduled jobs and rescheduled. This did not resolve the issue.

**Comment by Martinch713** [comment]
@afawcett 

When I go to Apex Jobs, I see them just sitting in Queued status.

![image](https://user-images.githubusercontent.com/63259756/85330079-b48b8c00-b4a1-11ea-9486-4b6b5ace8dd4.png)

**Comment by afawcett** [comment]
@Martinch713 yes - this is the problem - salesforce has not processed the jobs and thus you get the error message.  This might help explain why - https://help.salesforce.com/articleView?id=000319687&type=1&mode=1
