### ISSUE TITLE
HELP! My DLRS rollup is not calculating in real time

### ISSUE THREAD

**Issue by kellyraines** [afawcett/declarative-lookup-rollup-summaries#957]
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

I have 2 DLRS rollup summaries calculating a sum of Opportunity Products values looking up to a custom Object (Event__c). The child trigger is deployed and one roll up is working fine, but the other doesn't work unless I manually run a calculate job. Both are set to 'Active' in Realtime and System calculation. I have no idea why one is working but not the other, I even tried to delete both and remove the child trigger and recreate both rollups, but still no luck. Please help!

**Comment by afawcett** [comment]
@kellyraines i recommend you post this in the community chatter group where you can share more details on your rollup configurations.
