### ISSUE TITLE
Another Unable to connect to the Salesforce Metadata API issue

### ISSUE THREAD

**Issue by kfeng86** [afawcett/declarative-lookup-rollup-summaries#962]
I know there's so many of these issues already, but I read through all of the related issues and unfortunately can't seem to fix my issue.

Just installed 2.12, clicked the link to create remote site site, remote site setting exists and domain matches. 

![image](https://user-images.githubusercontent.com/31517599/87486374-0b433c00-c5f0-11ea-9310-91b266cd0b43.png)

Still getting the "unable to connect" error when I try to create a manage lookup rollup summary record or manage child triggers.

![image](https://user-images.githubusercontent.com/31517599/87486712-be139a00-c5f0-11ea-9341-f2445297dda7.png)

I've manually deleted and recreated the remote site setting 4 times now. 

I'm on unlimited edition, still on spring 20 for now.

Is there something else I'm missing?????

**Comment by emcobb** [comment]
I'm having the same issue... have installed this in many different orgs and have never had a problem until now!  Let me know if you find a resolution.

**Comment by afawcett** [comment]
@kfeng86 can you try manually creating with the URL shown at the bottom of the page in the grey "DEBUG" text area.

**Comment by afawcett** [comment]
I am going to flag this as a bug - because for some reason the calculated URL seems to be wrong - maybe this is a change in VF in recent releases. Folks that have reported this elsewhere seem to have worked around it by using the URL in the error message shown at the bottom of the screen.

**Comment by kfeng86** [comment]
Haha! Thanks @afawcett - that did work for me finally. I was just really confused because I thought for 2.12 there was no longer a need to set up the remote site setting so my covid-brain could not computer. Thanks!

**Comment by afawcett** [comment]
@kfeng86 ha no worries - and yeah no longer any need for my domain enabled orgs.
