### ISSUE TITLE
No records in rollup summary log

### ISSUE THREAD

**Issue by aoldenkamp** [afawcett/declarative-lookup-rollup-summaries#968]
I have created several rollup summaries which work correctly when I set them on Realtime. But I want to schedule them. When a record has changed, I suppose there should be created a record in the rollup summary log, but is doesn't. What could be the problem and more important, what would be the solution to solve this problem?

**Comment by afawcett** [comment]
These should be in "Lookup Rollup Summary Schedule Items"
