### ISSUE TITLE
Salesforce is trying to run an inactive rollup

### ISSUE THREAD

**Issue by n-green** [afawcett/declarative-lookup-rollup-summaries#973]
The error message is as follows: 
Apex script unhandled exception by user/organization: ***

Failed to process batch for class 'dlrs.RollupJob' for job id ***

caused by: System.QueryException:
dlrs__LookupRollupSummaryScheduleItems__c
^
ERROR at Row:1:Column:146
Invalid field: ***

The invalid field exists, and the specific rollup is inactive. 
So, why is Salesforce trying to run an inactive rollup?
Please advise.

**Comment by JimBTek** [comment]
You likely still have the DLRS Scheduled Apex class in your scheduled jobs. Please check and let us know.

**Comment by kenke** [comment]
@JimBTek , I have the same issue. How can I differentiate which one is for a specific field roll up? They are all called 
RollupCalculateJob in Apex jobs

**Comment by afawcett** [comment]
You should be able to use the job id and look in the url when you review the scheduled job to match them.
