### ISSUE TITLE
Field to Aggregate

### ISSUE THREAD

**Issue by peppers312** [afawcett/declarative-lookup-rollup-summaries#974]
Is there a way to aggregate more than one field on the child object when creating a DLRS? We use multiple amount fields and were not sure if DLRS was capable of this. 

Any help would be appreciated.

**Comment by afawcett** [comment]
No not really only one per rollup - maybe try some forum fields on your child object? But please be sure to list the physical fields in the "Lookup Criteria Fields" so that the tool looks for changes on all amount fields.
