### ISSUE TITLE
Looping Remove and Deploy

### ISSUE THREAD

**Issue by joanlui-ws** [afawcett/declarative-lookup-rollup-summaries#976]
First time user of DLRS. Rollup an opportunity field to populate in Account object in Sandbox. Save without error, then [Deploy]. It asked for to 'Remove to uninstall the Apex Trigger and Apex Class for this child object.' Once Removed, [Deploy]. When Deploy is completed, Message show:
Deployment complete.
Apex Trigger dlrs_OpportunityTrigger is installed.
Apex Class dlrs_OpportunityTest is installed.
Apex Trigger dlrs_AccountTrigger is installed.
Apex Trigger dlrs_AccountTest is installed.
Click Remove to uninstall the Apex Trigger and Apex Class for this child object.
It keeps looping.
Please advise how to fix it. Thanks

**Comment by joanlui-ws** [comment]
After refreshing Salesforce sandbox, create the rollup again. After Deploy is complete, still asking 'Click Remove to uninstall the Apex Trigger and Apex Class for this child object'. When removed is complete, 'Click Deploy to install the Apex Trigger and Apex Class for this child object'. And it keeps looping.

**Comment by afawcett** [comment]
Sorry the experience is not clear here. Basically its working as designed. The page is either used to deploy or remove - you don't have to keep going. Basically activate the rollup, click Manage Child Trigger and deploy - job done. Then in the future if you ever want to unstall or remove the rollup from child object, you can use Mnaage Child Trigger button again to remove then delete the rollup. Hopefully this makes sense.
