### ISSUE TITLE
Limit Rollup Job to Record Types

### ISSUE THREAD

**Issue by tymo1991** [afawcett/declarative-lookup-rollup-summaries#977]
Is there anyway to limit a rollup job to certain record type of an object for the initial job? We have about 80,000 account records that will be checked against when I create a rollup job which will bog down our integration with our other CRM. This would only affect the initial run as these records wouldn't meet the criteria in future jobs. I don't think this is possible but wanted to check. Thank you.

**Comment by ScubaJimmE** [comment]
Yes, you should be able to do this with a filter when you run your rollup. 

Click 'Calculate' and you get a box where you can type the WHERE clause of an SOQL query.... so in your case you could use WHERE RecordType.Name = 'Record Type Name Here' for example, and that should do what you're looking for.

**Comment by tymo1991** [comment]
> Yes, you should be able to do this with a filter when you run your rollup.
> 
> Click 'Calculate' and you get a box where you can type the WHERE clause of an SOQL query.... so in your case you could use WHERE RecordType.Name = 'Record Type Name Here' for example, and that should do what you're looking for.

I've tried this with both RecordType.Name & RecordType.Id and neither are working. The job will run but it will not complete. If I go to the Lookup Rollup Calculate Jobs tab several hours later, the job I created is still there.

**Comment by tymo1991** [comment]
So i removed the WHERE clause and just used RecordType.Name = 'Commercial' and that worked. Thanks for the help ScubaJimmE
