### ISSUE TITLE
DLRS is giving an error of Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by jhunter3223** [afawcett/declarative-lookup-rollup-summaries#980]
**	
Errors
Unable to connect to the Salesforce Metadata API.
This could be because it is the first time installing this tool or your Salesforce domain has changed.
A Remote Site Setting must be created or updated in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.
**

I have deleted the Remote Setting and created a new one and still nothing is fixing the issue.  It was working in the sandbox just last week and now it seems to be giving us issues.  I was able to add to production and it works fine.

Thoughts?

**Comment by borge-77** [comment]
Just installed, and am experiencing the same issue

**Comment by JVerboekend** [comment]
Just installed, and am experiencing the same issue.

**Comment by FabienneBetD** [comment]
Just installed and experiencing the same issue
![API error](https://user-images.githubusercontent.com/71716836/93900767-11dbe700-fcf6-11ea-9a0f-7a98e7f470c1.PNG)
![site](https://user-images.githubusercontent.com/71716836/93900778-156f6e00-fcf6-11ea-83f2-c8703b743e31.PNG)

**Comment by aka128** [comment]
Did you all ever figure this out? I'm also having the same issue and even if I press create/update remote site setting, it still doesn't fix the issue

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
