### ISSUE TITLE
dlrs task trigger causing issue at the time lead conversin

### ISSUE THREAD

**Issue by akansh22** [afawcett/declarative-lookup-rollup-summaries#981]
Hi 
We have a trigger that will fire after lead conversion and will create a record on matter object. What is happening if we have tasks on lead and we will convert lead then matter will not create but if we don't have tasks on lead and we will convert lead then the record will be created.

This is what we have done
![image](https://user-images.githubusercontent.com/32503705/92924655-f1d73880-f456-11ea-9ca0-466313a5227b.png)

What we want when Our trigger on lead fires then dlrs trigger should not fire

**Comment by afawcett** [comment]
I am not an expert in these objects but you should be able to leverage the filter criteira to exclude these records. You might also want to post in the community chatter group - typically github is for known enahncements and bugs - https://github.com/afawcett/declarative-lookup-rollup-summaries#community-support
