### ISSUE TITLE
Case Merge Issues

### ISSUE THREAD

**Issue by alexcarroll-prolocity** [afawcett/declarative-lookup-rollup-summaries#982]
Hello! I'm on 2.12 and have the Deploy code to support record merging? marked TRUE on my trigger, but I'm still receiving an error when editing a case that's been merged. I've removed and re-deployed the trigger a few times, but still receiving the error. I installed 2.12 last week, case merge was turned on after the fact, but I did the re-deployment of the trigger today once discovering the issue. This is in production.. What can I do to fix this?

_Originally posted by @alexcarroll-prolocity in https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/818#issuecomment-696252960_

**Comment by alexcarroll-prolocity** [comment]
Hey team, I have a client who this is leaving in the lurch. Is it possible to get an update?

**Comment by afawcett** [comment]
Sorry @alexcarroll-prolocity this is not always the best place to tap into the rich community for this tool - please try https://github.com/afawcett/declarative-lookup-rollup-summaries#community-support
