### ISSUE TITLE
Getting Schedule Item records created when the calculation mode is Realtime

### ISSUE THREAD

**Issue by RobLofaroFMT** [afawcett/declarative-lookup-rollup-summaries#983]
We have rollups that are set to Realtime calculation mode, but we get a handful of Schedule Item records created each day and they are building up.  I thought Schedule Items would only be created for jobs that have a schedule - why are these being created and can I delete them?

**Comment by JimBTek** [comment]
@RobLofaroFMT that is weird.  Can you confirm that all of your DLRS sObject and custom metadata records are both all set to Realtime if you have both? DLRS used to use the sObject records and leverages the Custom Metadata records now, sometimes there can be some ghosts that crop up from old DLRS config.

**Comment by RobLofaroFMT** [comment]
We deactivated all the old sObject based DLRSs but I didn't change them all to Realtime.  The Custom Metadata records have a mix of realtime and scheduled, but the issue we are seeing is with the realtime ones creating Jobs.
________________________________

**Comment by afawcett** [comment]
So long as you have one rollup defined as Scheduled in the Processing Mode field it will generate "Lookup Rollup Summary Schedule Items" - and yeah check both "Manage Rollup Summaries" tab and "Lookup Rollup Summaries" tab both.
