### ISSUE TITLE
Unable to Connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by aka128** [afawcett/declarative-lookup-rollup-summaries#986]
Bug
When I go to the welcome page for DLRS, I see the following message: 

Errors
Unable to connect to the Salesforce Metadata API.
This could be because it is the first time installing this tool or your Salesforce domain has changed.
A Remote Site Setting must be created or updated in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

When I press the 'create/update' button, it says it created, and then I refresh and the error message shows again. 

I also created the remote site manually, and the same thing happened. 

I also see this error in gray at the bottom of the page: DEBUG USE ONLY: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

<img width="1179" alt="Screen Shot 2020-10-01 at 8 22 23 AM" src="https://user-images.githubusercontent.com/72205011/94810544-2ab55e00-03c2-11eb-8058-5d48e4c78a0c.png">

<img width="1101" alt="Screen Shot 2020-10-01 at 8 38 18 AM" src="https://user-images.githubusercontent.com/72205011/94810555-2db04e80-03c2-11eb-9f94-98eeefd1160e.png">

**Comment by aka128** [comment]
I read through some of the issue people had, and the fixes didn't work for me. I'll list those:

#962 - When I delete it entirely, the same URL shows up at the bottom

**Comment by aka128** [comment]
Also to clarify, we have enterprise edition

**Comment by ashir2020** [comment]
Errors- Unable to connect to the Salesforce Metadata API.
![dlrs](https://user-images.githubusercontent.com/72383678/95064222-518fcf00-06f7-11eb-9b48-754d77091edb.png)

Hey @afawcett 

I am getting the above error when i try to click manage Lookup Rollup Summaries tab.
We have Enterprise licence.

We have recently upgraded from DLRS version 2.4.2 to 2.12.

I have clicked the Create/Update Remote Site Setting button and although it says "Remote Site Setting dlrs_mdapi has been created." but I keep getting the Errors- Unable to connect to the Salesforce Metadata API.
I have also tried to create the Remote Site manually under under remote in setup but the issue still persists.

**Comment by ashir2020** [comment]
@afawcett is there any update on the above?
thanks

**Comment by aka128** [comment]
Update for me - I took a back up of all of our roll ups, uninstalled the entire package, reinstalled and we are still getting the error above

**Comment by aka128** [comment]
I've also tried the following:

Tried the custom metadata access changed recommended in this thread, still gave error (https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/684)

Tried disabling 'lock sessions to the IP address from which they originated' as per info and known issues, still gave error (https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues)

**Comment by aka128** [comment]
Hey @ashir2020 in case it's helpful for you, something FINALLY worked for me! 

I tried again to uncheck the 'lock sessions to the IP address from which they originated', pressed saved, logged out, then logged back in (I didn't do this step last time), and then the error finally went away! 

Hope it works for you as well.

**Comment by 01ivr3** [comment]
I just installed the DLRS managed package into an Enterprise sandbox. Clicked the "Create/Update Remote Site Setting" button, which appeared to work as expected. But the error persists. This seems to be a long-standing known issue. Does anyone know a permanent solution?

**Comment by Nvhengel** [comment]
We managed to get this resolved by changing the remote site url to the instance url, in our case https://cs100.salesforce.com

**Comment by ashir2020** [comment]
@Nvhengel thanks for sharing this, i also added our org url on the remote site setting and logged out and logged back in and the issue was resolved on my instance.
many thanks,

**Comment by rrobinsoncpa1** [comment]
I tried everything on all of the posts with no success, then I tried 'lock sessions to the IP address from which they originated' . IT WORKED!

**Comment by David-Rudd** [comment]
Just hit the exact same problem - We had just implemented a number of Security Tech Debt Items including 'lock sessions to the IP address from which they originated' - Which then shut down DLRS - Would be useful to know WHY this is happening as our Security Teams are going to want to implement this setting again.

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
