### ISSUE TITLE
How to rollup count of unique values

### ISSUE THREAD

**Issue by kvonachen** [afawcett/declarative-lookup-rollup-summaries#99]
I have a situation where I have a related list on leads that stores records.  In the related list, I have a field called Chain.  In the Lead, I need to count the # of unique chains from all related list records associated to the lead.  Is this possible, and if so, what is the Relationship Criteria to use?

**Comment by afawcett** [comment]
Ok, good news, grabbed some time during my holiday to chill with the laptop and just finished coding this up, it will be in the next release, hopefully this weekend!

**Comment by afawcett** [comment]
It is achieved by selecting 'Count Distinct' instead of 'Count'.

**Comment by kvonachen** [comment]
Excellent!  Thank you so much!  I did figure out a workaround for this client (albeit it wasn't an easy one!) but I can see using this for other configurations with this and other clients too!

**Comment by afawcett** [comment]
Added in version 1.18, see README for more.
