### ISSUE TITLE
Unable to uninstall DLRS

### ISSUE THREAD

**Issue by cbesch** [afawcett/declarative-lookup-rollup-summaries#990]
**Describe the bug**

**To Reproduce**
Claims RollupService is unable to uninstall due to apex classes and triggers that are connected to it.

**Expected behavior**
app uninstalled

**Screenshots**
![image](https://user-images.githubusercontent.com/73599214/97450530-d63dc980-1900-11eb-833e-b395555aa766.png)

**Additional context**

**Comment by brennanbutlerRAD** [comment]
Can someone make this a priotiry. Being unable to uninstall is keeping me from doing a go live with a client. I am hoping that by uninstalling it will delete the Test Trigger that was written that seems to not want to go away.

**Comment by aheber** [comment]
@brennanbutlerRAD, I can help you get rid of the Apex. If you email me at anthony heber at gmail com we can setup a meeting and I can help you clear those out.

**Comment by afawcett** [comment]
Thanks @aheber - i also moved this to a wiki page and updated the README.
