### ISSUE TITLE
I don't see anything in Lookup Rollup Summaries Tools tab. 

### ISSUE THREAD

**Issue by filkanczula** [afawcett/declarative-lookup-rollup-summaries#992]
Hi.

When I use the latest version of DLRS, go to Lookup Rollup Summaries Tools tab, I don't see any actual tools there. It's blank. Should I install something extra to have access to these tools?

Thanks :)

**Comment by afawcett** [comment]
@filkanczula have you assigned the rollup permission set?

**Comment by jonccg** [comment]
Same issue, I just see the "Lookup Rollup Summaries Tools" heading, no Optimizer.  My user profile is system admin, but I tried assigning both the rollup permission sets to my user just in case, no better.  When I upgraded to 2.12 I did delete the no-longer-needed field from the  Lookup Rollup Summary Schedule Items object, and ran a report to ensure that I had no old rollups without a value in the Lookup Rollup Summary 2 field.  Oddly, I upgraded to DLRS 2.12 in both my sandbox and production instance on the same day, the Optimizer SHOWS in the sandbox, it does NOT show in production.

**Comment by afawcett** [comment]
@filkanczula that is odd - and more so @jonccg that you got it going by installing on the same days - very odd. The optinizer component is hard coded onto that page - no conditional logic - https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/force-app/main/flexipages/LookupRollupSummariesHome.flexipage-meta.xml#L9. I will keep a look out for more errors on this - but for now I don't have a enough to progress this issue. By all means add some more intel if/when you get it guys - thanks!

**Comment by afawcett** [comment]
Found the issue! The OptimizerComponentController needs adding to a permisisonset/profile - sorry I missed that in the apckaged permisison set - i will add for the next release.

**Comment by afawcett** [comment]
Fixed in v2.13.
