### ISSUE TITLE
Error occuring

### ISSUE THREAD

**Issue by bdare91** [afawcett/declarative-lookup-rollup-summaries#994]
Hello, 

I've been referred to you guys from Salesforce support for an error occurring on my Salesforce Production org.
I'm fairly new as a Salesforce admin (As in 1 month so please excuse my lack of knowledge).

The users are opening the quote record and trying to convert this to an order record and getting the following error message:

You encountered some errors when trying to save this record.
We can't save this record because the “Quote Handler” process failed. Give your Salesforce admin these details. An error occurred when executing a flow interview. Error ID: 1895350340-81054 (-525322883).

I've had a look at the flow error email and it says:

Error element Create_Order_Products (FlowRecordCreate).
This error occurred when the flow tried to create records: FIELD_INTEGRITY_EXCEPTION: Enter the same currency as the parent Order.: Currency ISO Code. You can look up ExceptionCode values in the SOAP API Developer Guide.

I'm very confused as the Account, Opportunity, Quote & Products are all the same value. Obviously, there is no way for me to go back in and change the price book assigned, unless there is?

Salesforce have confirmed there is no error occuring with the workflow rule or email alert in Salesforce. Therefore they have referred me to you.

Thanks, Beckie

**Comment by bdare91** [comment]
Hello, What is the normal response time? Thank you.

**Comment by afawcett** [comment]
Hi Beckie - welcome to Salesforce as an Admin! This tool will only update the fields indicated on the Manage Rollup Summaries tab for your objects. Try looking at those and see if there is anything that looks odd. Note you may have rollup definitions on the "Look Rollup Summaries" tab (older way to define). Typically the tool updates numeric values so I am not sure why it would try to change the currency code tbh. Its hard to say without looking at the rollup definitions to see if anything looks odd, maybe a rollup definition is trying to sync the currency code and it needs some filter criteria to avoid doing this for certain types of qoutes? (just a guess sorry). Also there is a great community support chatter group here - https://github.com/afawcett/declarative-lookup-rollup-summaries#community-support (this is not a commercial product, its entirely supported by the community). Hope this helps and welcome again!
