### ISSUE TITLE
Declarative Lookup Rollup Summaries not running full calculate automatically

### ISSUE THREAD

**Issue by GabrielleHa** [afawcett/declarative-lookup-rollup-summaries#995]
The Lookup Rollup Summaries on Custom objects on Salesforce aren't calculating automatically. However, they do work when I click the "Full Calculate". I'm not sure why this is.

![Screenshot 2020-11-10 at 14 24 49](https://user-images.githubusercontent.com/74252467/98686454-80393f00-2360-11eb-91e6-57fd56f64c60.png)

**Comment by rjayagopal** [comment]
Hi Andy, It stopped working for us as well. 

Existing Rollups are working fine, any newly created ones were not working.

I noticed there are no entries created under "Lookup Rollup Summaries" tab for the newly created rollups.

**Comment by afawcett** [comment]
"Lookup Rollup Summaries" tab is for old style rollups - its fine if you don't have any in that just use "Manage Rollup Summaries" tab. Make sure the triggers/rollup is active and that you have the correct fields in "Relationship Critiera Fields" for release time rollups as only changes to those fields will cause a recalc (for updates). Hope this helps.
