### ISSUE TITLE
DLRS error Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by ktysco10** [afawcett/declarative-lookup-rollup-summaries#996]
I am receiving an error in DLRS "Unable to connect to the Salesforce Metadata API." I have tried to update the remote site settings and they are correct.  I click create/update remote site settings and receive the same error.  I have updated the package and still receive the error. help.

**Comment by afawcett** [comment]
@ktysco10 look at this now - if you update the remote site manually with the URL in the error mesage does that work?

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
