### ISSUE TITLE
DLRS Deleted object field error

### ISSUE THREAD

**Issue by mkitimbo** [afawcett/declarative-lookup-rollup-summaries#998]
I deleted a bunch of fields on a custom object called alu_application and now am getting the following error upon saving a record on this object

**dlrs_alu_ApplicationTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Recommendation_Completed__c for alu_Application__c Class.dlrs.RollupService.handleRollups: line 892, column 1 Class.dlrs.RollupService.triggerHandler: line 311, column 1 Trigger.dlrs_alu_ApplicationTrigger: line 7, column 1**
Any help on how I can fix this issue on the DLRS configuration?

**Comment by afawcett** [comment]
@mkitimbo please go to your "Manage Rollup Summaries" tab or "Lookup Rollup Summaires" (if you have had the tool install fora. while) - in either case - look for a rollup on your alu_Application__c and either delete it or update it. If you decide to delete it - be sure to check for other rollups on this object - if there are none - you can also click Manage Child Trigger (before you delete the last rollup). and it will delete the apex trigger and test code related. Hope this helps! :-)
