### ISSUE TITLE
Unable to connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by nadavki** [afawcett/declarative-lookup-rollup-summaries#999]
**Describe the bug**
![image](https://user-images.githubusercontent.com/74714948/99663549-781f8480-2a6f-11eb-882d-45320103af4e.png)

I can see that there is an issue with the IP and we are using the SF Network Access, can you share the IP so we can add it to our system? Is that the problem?

Thanks!

**Comment by vcutler** [comment]
Sorry to be dense.  Which IP do you need?

**Comment by nadavki** [comment]
Hi,
Thanks for your email!
I have found the issue, there is an option in the Session Setting that called - Enforce login IP ranges on every request. If this option is checked, the DLRS is not working, so maybe you can add it to the documentation so other users will know that 😊

I have another question – when using the Schedule Full Calculate, it means that the DLRS will go over all the records in the Parent Object? In my use case the Parent Object is Account and the Child is Asset. So at the time that I will determine, it will go over all the accounts that I have? Or only those that have changed?

Thanks!

[cid:image001.jpg@01D38F7A.4A5801A0]
Nadav Kiani
Analyst | IT | Strauss Water

Mobile Phone: 054-4427493
Nadav.Kiani@Strauss-water.com
www.strauss-water.com<http://www.strauss-water.com/>

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
